### PR TITLE
Fix deadzone when panning while zoomed in.

### LINKED ISSUE #22805: When zoomed to zoom level -2, right click scrolling the viewport has a bias towards the top left
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.14

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Check the steps to reproduce below.
The offending code is here:

https://github.com/OpenRCT2/OpenRCT2/blob/24d02855bcb52c3c5bab55f124195102f40ac85c/src/openrct2-ui/input/MouseInput.cpp#L583-L598

### Steps to reproduce

1. Zoom all the way in to zoom level -2 (as of writing this, this is only possible on OpenGL)
2. Right click scroll the viewport.
3. Notice that small movements to the bottom right do not move the viewport but similar movements to the top left do.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mrmbernardi**
Fixes #22805

### CODE REVIEW

File: src/openrct2-ui/input/MouseInput.cpp [hunk 1]
```diff
@@ -586,8 +586,14 @@ static void InputViewportDragContinue()
...
 
-            differentialCoords.x = (viewport->zoom + 1).ApplyTo(differentialCoords.x);
-            differentialCoords.y = (viewport->zoom + 1).ApplyTo(differentialCoords.y);
+            // applying the zoom only with negative values avoids a "deadzone" effect where small positive value round to zero.
+            const bool posX = differentialCoords.x > 0;
+            const bool posY = differentialCoords.y > 0;
+            differentialCoords.x = (viewport->zoom + 1).ApplyTo(-std::abs(differentialCoords.x));
+            differentialCoords.y = (viewport->zoom + 1).ApplyTo(-std::abs(differentialCoords.y));
+            differentialCoords.x = posX ? -differentialCoords.x : differentialCoords.x;
+            differentialCoords.y = posY ? -differentialCoords.y : differentialCoords.y;
```
Comment (Gymnasiast) [inline src/openrct2-ui/input/MouseInput.cpp:595]: Could you explain this? I don’t quite understand why we need to invert the value in all cases.

Comment (mrmbernardi) [reply src/openrct2-ui/input/MouseInput.cpp:595]: The values are guaranteed to be negative at this point. These two lines only invert them (restore them to positive) if they were positive previously.

Comment (Gymnasiast) [reply src/openrct2-ui/input/MouseInput.cpp:595]: Oh wait, there was a little `-` hiding just before the `std::abs`.

**Review by Gymnasiast — APPROVED** [review]
