### PR TITLE
Fix #4920: Crash in peep pathfinding

### LINKED ISSUE #4920: Crash in fence_in_the_way / map_element_get_type
**OS:** Linux
**Commit/Build:** a05557cb7

Game crashes when loading attached park.

**Backtrace:**
```
0x0000555557d4df8d in map_element_get_type (element=0x0) at /home/janisozaur/workspace/OpenRCT2/src/world/map.c:256
256		return element->type & MAP_ELEMENT_TYPE_MASK;
>>> bt
#0  0x0000555557d4df8d in map_element_get_type (element=0x0) at /home/janisozaur/workspace/OpenRCT2/src/world/map.c:256
#1  0x0000555557d228b7 in fence_in_the_way (x=4256, y=-32, z0=2, z1=6, direction=1) at /home/janisozaur/workspace/OpenRCT2/src/world/footpath.c:855
#2  0x0000555556906f42 in guest_surface_path_finding (peep=0x55555a1064c0 <_spriteList+27392>) at /home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:8559
#3  0x00005555568f3191 in guest_path_finding (peep=0x55555a1064c0 <_spriteList+27392>) at /home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:9995
#4  0x00005555568dc7a7 in sub_693C9E (peep=0x55555a1064c0 <_spriteList+27392>) at /home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:10236
#5  0x000055555684d84a in peep_update_walking (peep=0x55555a1064c0 <_spriteList+27392>) at /home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:6510
#6  0x00005555567d8201 in peep_update (peep=0x55555a1064c0 <_spriteList+27392>) at /home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:6735
#7  0x00005555567d703d in peep_update_all () at /home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:602
#8  0x00005555565a1722 in game_logic_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:390
#9  0x00005555565a0b22 in game_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:309
#10 0x000055555697ab39 in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:467
#11 0x0000555557e27cb2 in OpenRCT2::RunFixedFrame () at /home/janisozaur/workspace/OpenRCT2/src/OpenRCT2.cpp:424
#12 0x0000555557e2789f in OpenRCT2::RunGameLoop () at /home/janisozaur/workspace/OpenRCT2/src/OpenRCT2.cpp:381
#13 0x0000555557e27825 in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/OpenRCT2.cpp:298
#14 0x000055555695e14d in main (argc=2, argv=0x7fffffffdda8) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:59
>>> up 4
#4  0x00005555568dc7a7 in sub_693C9E (peep=0x55555a1064c0 <_spriteList+27392>) at /home/janisozaur/workspace/OpenRCT2/src/peep/peep.c:10236
10236				result = guest_path_finding(peep);
>>> p peep
$1 = (rct_peep *) 0x55555a1064c0 <_spriteList+27392>
>>> p *peep
$2 = {
  sprite_identifier = 1 '\001', 
  var_01 = 0 '\000', 
  next_in_quadrant = 25, 
  next = 305, 
  previous = 87, 
  linked_list_type_offset = 4 '\004', 
  sprite_height_negative = 16 '\020', 
  sprite_index = 107, 
  flags = 0, 
  x = 4259, 
  y = 16, 
  z = 16, 
  sprite_width = 8 '\b', 
  sprite_height_positive = 5 '\005', 
  sprite_left = 4235, 
  sprite_top = -2169, 
  sprite_right = 4251, 
  sprite_bottom = -2148, 
  sprite_direction = 24 '\030', 
  pad_1F = "\000\000", 
  name_string_idx = 50439, 
  next_x = 4256, 
  next_y = 0, 
  next_z = 2 '\002', 
  next_var_29 = 8 '\b', 
  outside_of_park = 0 '\000', 
  state = 5 '\005', 
  sub_state = 18 '\022', 
  sprite_type = 0 '\000', 
  type = 0 '\000', 
  {
    staff_type = 1 '\001', 
    no_of_rides = 1 '\001'
  }, 
  tshirt_colour = 15 '\017', 
  trousers_colour = 27 '\033', 
  destination_x = 4259, 
  destination_y = 16, 
  destination_tolerence = 10 '\n', 
  var_37 = 1 '\001', 
  energy = 128 '\200', 
  energy_growth_rate = 255 '\377', 
  happiness = 243 '\363', 
  happiness_growth_rate = 243 '\363', 
  nausea = 51 '3', 
  nausea_growth_rate = 51 '3', 
  hunger = 186 '\272', 
  thirst = 228 '\344', 
  bathroom = 29 '\035', 
  var_41 = 72 'H', 
  var_42 = 0 '\000', 
  intensity = 244 '\364', 
  nausea_tolerance = 1 '\001', 
  window_invalidate_flags = 23 '\027', 
  paid_on_drink = 0, 
  ride_types_been_on = "\000\000\000\000\000\000\000\000\020\000\000\000\000\000\000", 
  item_extra_flags = 0, 
  photo2_ride_ref = 0 '\000', 
  photo3_ride_ref = 0 '\000', 
  photo4_ride_ref = 0 '\000', 
  pad_5F = "\000\000\000\000\000\000\000\000", 
  current_ride = 0 '\000', 
  current_ride_station = 4 '\004', 
  current_train = 1 '\001', 
  {
    {
      current_car = 0 '\000', 
      current_seat = 3 '\003'
    }, 
    time_to_sitdown = 768, 
    {
      time_to_stand = 0 '\000', 
      standing_flags = 3 '\003'
    }
  }, 
  special_sprite = 0 '\000', 
  action_sprite_type = 0 '\000', 
  next_action_sprite_type = 0 '\000', 
  action_sprite_image_offset = 0 '\000', 
  action = 255 '\377', 
  action_frame = 13 '\r', 
  var_73 = 72 'H', 
  {
    var_74 = 65535, 
    next_in_queue = 65535
  }, 
  var_76 = 0 '\000', 
  pad_77 = 0 '\000', 
  {
    maze_last_edge = 3 '\003', 
    direction = 3 '\003'
  }, 
  var_79 = 255 '\377', 
  time_in_queue = 1370, 
  rides_been_on = "\001", '\000' <repeats 30 times>, 
  id = 19277, 
  cash_in_pocket = 700, 
  cash_spent = 0, 
  time_in_park = 28605550, 
  var_AC = 0 '\000', 
  previous_ride = 255 '\377', 
  previous_ride_time_out = 720, 
  thoughts = {[0] = {
      type = 17 '\021', 
      item = 0 '\000', 
      var_2 = 1 '\001', 
      var_3 = 95 '_'
    }, [1] = {
      type = 255 '\377', 
      item = 255 '\377', 
      var_2 = 2 '\002', 
      var_3 = 168 '\250'
    }, [2] = {
      type = 34 '"', 
      item = 255 '\377', 
      var_2 = 20 '\024', 
      var_3 = 179 '\263'
    }, [3] = {
      type = 4 '\004', 
      item = 8 '\b', 
      var_2 = 24 '\030', 
      var_3 = 82 'R'
    }, [4] = {
      type = 13 '\r', 
      item = 255 '\377', 
      var_2 = 25 '\031', 
      var_3 = 46 '.'
    }}, 
  var_C4 = 94 '^', 
  {
    staff_id = 255 '\377', 
    guest_heading_to_ride_id = 255 '\377'
  }, 
  {
    staff_orders = 169 '\251', 
    peep_is_lost_countdown = 169 '\251'
  }, 
  photo1_ride_ref = 0 '\000', 
  peep_flags = 2097152, 
  pathfind_goal = {
    x = 61 '=', 
    y = 50 '2', 
    z = 52 '4', 
    direction = 2 '\002'
  }, 
  pathfind_history = {[0] = {
      x = 56 '8', 
      z = 52 '4', 
      direction = 11 '\v'
    }, [1] = {
      x = 61 '=', 
      y = 56 '8', 
      z = 52 '4', 
      direction = 7 '\a'
    }, [2] = {
      x = 54 '6', 
      y = 56 '8', 
      z = 52 '4', 
      direction = 7 '\a'
    }, [3] = {
      x = 54 '6', 
      y = 55 '7', 
      z = 52 '4', 
      direction = 11 '\v'
    }}, 
  no_action_frame_no = 3 '\003', 
  litter_count = 0 '\000', 
  {
    time_on_ride = 4 '\004', 
    var_E2 = 4 '\004'
  }, 
  disgusting_count = 0 '\000', 
  {
    paid_to_enter = 0, 
    staff_lawns_mown = 0, 
    staff_rides_fixed = 0
  }, 
  {
    paid_on_rides = 0, 
    staff_gardens_watered = 0, 
    staff_rides_inspected = 0
  }, 
  {
    paid_on_food = 0, 
    staff_litter_swept = 0
  }, 
  {
    paid_on_souvenirs = 0, 
    staff_bins_emptied = 0
  }, 
  no_of_food = 0 '\000', 
  no_of_drinks = 0 '\000', 
  no_of_souvenirs = 0 '\000', 
  var_EF = 0 '\000', 
  voucher_type = 0 '\000', 
  voucher_arguments = 0 '\000', 
  var_F2 = 5 '\005', 
  angriness = 0 '\000', 
  var_F4 = 0 '\000', 
  days_in_queue = 6 '\006', 
  balloon_colour = 0 '\000', 
  umbrella_colour = 0 '\000', 
  hat_colour = 0 '\000', 
  favourite_ride = 0 '\000', 
  favourite_ride_rating = 255 '\377', 
  pad_FB = 0 '\000', 
  item_standard_flags = 0
}
```

**Save game:**
[Canyoneer.by.Xophe_crash.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/672861/Canyoneer.by.Xophe_crash.sv6.zip)

Note: this is a slightly fast-forwarded version of http://www.nedesigns.com/park/2132/canyoneer/

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

File: src/world/footpath.c [hunk 1]
```diff
@@ -852,6 +852,8 @@ bool fence_in_the_way(int x, int y, int z0, int z1, int direction)
 
 	mapElement = map_get_first_element_at(x >> 5, y >> 5);
 	do {
+		if (mapElement == NULL)
+			return false;
```
Comment (IntelOrca) [inline src/world/footpath.c]: This doesn't need to go in the loop.

Comment (janisozaur) [inline src/world/footpath.c]: 👍
