### PR TITLE
Make renaming staff use staff permissions, fixes #3243, closes #3400

### LINKED ISSUE #3243: Changing staff's name is a GUEST command (permissions)
**OS: Win 7** 
**Version: 0.4.0.0** 
**Commit: a8efcef** 

When you edit a staff members name online, it counts as a **Guest** command, therefor restricting it if the player ain't allowed to edit Guest commands.
The rest of the stuff (hire staff, patrol areas & tell them what to do) is all staff commands
The names should be too, if possible

- [ ] Reproducable in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Host a server and join as a client
2. Edit a staffs name
3. See what command the user did ('Guest')

**Screenshots / Video:**
staff

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/peep/peep.c [hunk 1]
```diff
@@ -10607,11 +10607,17 @@ money32 set_peep_name(int flags, int state, uint16 sprite_index, uint8* text_1,
  *
  *  rct2: 0x00698D6C
  */
-void game_command_set_peep_name(int *eax, int *ebx, int *ecx, int *edx, int *esi, int *edi, int *ebp) {
+void game_command_set_guest_name(int *eax, int *ebx, int *ecx, int *edx, int *esi, int *edi, int *ebp) {
+	uint16 sprite_index = *ecx & 0xFFFF;
+
+	rct_peep *peep = GET_PEEP(sprite_index);
+	if (peep->type != PEEP_TYPE_GUEST)
```
Comment (IntelOrca) [inline src/peep/peep.c]: You need to set ebx to ```MONEY_UNDEFINED``` before returning.

**Comment by Gymnasiast** [comment]
Ok, changed it.
