### PR TITLE
Fix #5511: Backspace behaves inconsistently in track manager

### LINKED ISSUE #5511: Backspace inconsistency in track design manager
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** dabaddd

**Steps to reproduce:**
1. Open track design manager
2. Hit backspace (nothing happens)
3. Click the close button (quits)
4. Open track design manager
5. Select any ride
6. Click the close button (returns to previous window)
7. Select any ride
8. Hit backspace (renders TDM useless)
9. Be left with no other option than to quit the track design manager using the top toolbar

Backspace usually has the same function as closing the window with the mouse, but in step 2 backspace does nothing while step 3 closes the track design manager and quits to the main menu.
In step 8, the window will disappear entirely, leaving the track design manager (TDM) useless. I'd expect it to do nothing (like in step 2) or to go back to the main TDM screen (like in step 7), the latter being preferred.
The close buttons work as expected.

### PR DESCRIPTION
**Pull request by rwjuk**
This does the same check as in `window_track_list_mouseup()` when closing a track list window, to ensure that the main track manager window is loaded if the user is in track manager mode.

I don't like the idea of copy-paste code in multiple areas - I did try to include the relevant check in a function, but couldn't make it work. Open to suggestions!

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I'm not very happy with code for a single window in such a core function. Is there really no other way?

**Comment by rwjuk** [comment]
Nor am I really - I tried putting it in `window_track_list_close()` and wrapping said function, but both led to lock-ups, I believe from infinite loops. I'll have another look in a bit.

File: src/openrct2/windows/track_list.c [hunk 1]
```diff
@@ -259,11 +265,7 @@ static void window_track_list_mouseup(rct_window *w, rct_widgetindex widgetIndex
 		break;
 	case WIDX_BACK:
 		window_close(w);
-		if (gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER) {
-			window_close_by_number(WC_MANAGE_TRACK_DESIGN, w->number);
-			window_close_by_number(WC_TRACK_DELETE_PROMPT, w->number);
-			trackmanager_load();
-		} else {
+		if (gScreenFlags | SCREEN_FLAGS_TRACK_MANAGER) {
```
Comment (Gymnasiast) [inline src/openrct2/windows/track_list.c]: This looks odd. Does `gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER` not work?

File: src/openrct2/interface/window.c [hunk 2]
```diff
@@ -811,7 +811,6 @@ rct_window *window_find_by_number(rct_windowclass cls, rct_windownumber number)
 void window_close_top()
 {
 	rct_window* w;
-
```
Comment (Gymnasiast) [inline src/openrct2/interface/window.c]: Could you reinstate this line?

File: src/openrct2/windows/track_list.c (hunk 1 above)
Comment (rwjuk) [inline src/openrct2/windows/track_list.c]: Uhhh I'm not honestly sure what happened there - it wasn't what I was going for! Fixed in next commit.

Comment (rwjuk) [inline src/openrct2/windows/track_list.c]: Actually, something more serious is wrong here - I'll figure out what's gone on.

Comment (rwjuk) [inline src/openrct2/windows/track_list.c]: Fixed! I goofed - forgot to check the flag to determine whether to load the track manager or not.

File: src/openrct2/windows/track_list.c [hunk 3]
```diff
@@ -259,11 +265,7 @@ static void window_track_list_mouseup(rct_window *w, rct_widgetindex widgetIndex
 		break;
 	case WIDX_BACK:
 		window_close(w);
-		if (gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER) {
-			window_close_by_number(WC_MANAGE_TRACK_DESIGN, w->number);
-			window_close_by_number(WC_TRACK_DELETE_PROMPT, w->number);
-			trackmanager_load();
-		} else {
+		if (!(gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER)) {
```
Comment (Gymnasiast) [inline src/openrct2/windows/track_list.c]: Does this mean it will open the New Ride window when in normal mode? I don't think that's what you intended.

Comment (rwjuk) [inline src/openrct2/windows/track_list.c]: No, that's right - in normal mode if you click the 'Select another ride' button, it loads the 'New Ride' window so you can pick another ride type.

Comment (IntelOrca) [inline src/openrct2/windows/track_list.c]: Yeah, please don't do that - that is just confusing! 😆

Comment (rwjuk) [inline src/openrct2/windows/track_list.c]: But if I hadn't done that, it'd have looked something like
```if (gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER) {
} else {
 window_new_ride_open();
}
```

Comment (Gymnasiast) [inline src/openrct2/windows/track_list.c]: Oh wait, this was just me not looking properly. I didn't see it was under WIDX_BACK. For some reason I thought it was the code to handle the X button.
