### PR TITLE
Fix #5946: assertion hit when building new ride

### LINKED ISSUE #5946: Assertion hit when building new rides
**OS:** Windows 10 x64
**Version:** 0.1.1
**Commit/Build:** fab8efb

The following line is triggered when building new rides:
https://github.com/OpenRCT2/OpenRCT2/blob/f5923dbe99657ccbafc2f11b2293b6fc75c38188/src/openrct2/ride/track.c#L652

f5923dbe99657ccbafc2f11b2293b6fc75c38188 is the commit that causes this to be hit now.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a new ride (flat, tracked, shops)

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/station.c [hunk 1]
```diff
@@ -346,3 +346,15 @@ sint8 ride_get_first_valid_station_start(const rct_ride *ride)
...
+{
+    for (sint32 i = 0; i < MAX_STATIONS; i++)
+    {
+        if (ride->station_starts[i].xy == RCT_XY8_UNDEFINED)
+        {
+            return i;
+        }
+    }
+    return -1;
+}
```
Comment (IntelOrca) [inline src/openrct2/ride/station.c]: image
