### PR TITLE
Fix #23597: Adjust any staff set to EatFood animation

### LINKED ISSUE #23597: Game crashes when opening this save file 0.4.18-51 and newer versions
### Operating System

Windows 11

### OpenRCT2 build

0.4.18-51

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The game crashes when opening this save file from a park I made last year. It starts happening from develop version 0.4.18-51 and up.

[17 Pacific Pyramids But Beautiful.zip](https://github.com/user-attachments/files/18386142/17.Pacific.Pyramids.But.Beautiful.zip)

### Steps to reproduce

Download OpenRCT2 develop version (0.4.18-51 and up)
Play attached save file
game will crash

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by AaronVanGeffen**

### CODE REVIEW

File: src/openrct2/park/Legacy.cpp [hunk 1]
```diff
@@ -2335,6 +2335,21 @@ static bool ConvertPeepAnimationType(TPeepType* peep, AnimObjectConversionTable&
     auto& conversion = table[legacyPAG];
     peep->AnimationObjectIndex = conversion.first;
     peep->AnimationGroup = static_cast<PeepAnimationGroup>(conversion.second);
+
+    if (!peep->template Is<Staff>())
```
Comment (AaronVanGeffen) [inline src/openrct2/park/Legacy.cpp:2339]: NB: because the `peep` variable here is of type `TPeepType*` we have to explicitly invoke `template` to get this to parse.

**Comment by deurklink** [comment]
I just tested this PR, I was able to load the parks again that were submitted in the issue, and all the entertainer animations look normal!

**Review by Gymnasiast — APPROVED** [review]
