### PR TITLE
Fix #14102: NPE in window_tile_inspector_invalidate() 

### LINKED ISSUE #14102: [c28ccb] openrct2.exe: window_tile_inspector_invalidate, window_find_widget_from_point, GameHandleInputMouse, GameHandleInput...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/c28ccba141c770ad453f63f67f3b71bbe74597c6b69c932af155ed65f89b37a5">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Gebruiker\Documents\OpenRCT2\1e60f3aa-fe3e-4828-b40a-56b3ecaa82fe.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Gebruiker\Documents\OpenRCT2\1e60f3aa-fe3e-4828-b40a-56b3ecaa82fe.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Gebruiker\Documents\OpenRCT2\1e60f3aa-fe3e-4828-b40a-56b3ecaa82fe.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Gebruiker\Documents\OpenRCT2\screenshot\Kingdom Rich park 2021-02-15 19-47-31.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>882d3d6</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
window_tile_inspector_invalidate
window_find_widget_from_point
GameHandleInputMouse
GameHandleInput
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2-ui/windows/TileInspector.cpp [hunk 1]
```diff
@@ -1625,6 +1625,16 @@ static void window_tile_inspector_invalidate(rct_window* w)
             break;
         case TileInspectorPage::Wall:
         {
+            bool canBeSloped = false;
+            bool hasAnimation = false;
+            const auto sceneryEntry = tileElement->AsWall()->GetEntry();
```
Comment (IntelOrca) [inline src/openrct2-ui/windows/TileInspector.cpp:1630]: `tileElement->AsWall()` can return nullptr. Usually I don't mind if it checks the tile element type beforehand. But in this case it makes an assumption that the tile element is always the right type for the current page that is showing. So it it would be safer if we started checking nullptr after `AsWall` etc. in this method.

Comment (Gymnasiast) [reply src/openrct2-ui/windows/TileInspector.cpp:1630]: Why don't we just change the `switch` condition to `tileElement->GetType()`? Then we can also be sure the type is correct and `AsWall() will not return `nullptr`.

Comment (IntelOrca) [reply src/openrct2-ui/windows/TileInspector.cpp:1630]: That is fine with me.

**Review by IntelOrca — APPROVED** [review]

File: src/openrct2-ui/windows/TileInspector.cpp [hunk 2]
```diff
@@ -999,9 +998,13 @@ static void window_tile_inspector_mousedown(rct_window* w, rct_widgetindex widge
         return;
     }
 
-    switch (w->tileInspectorPage)
+    const TileElement* tileElement = window_tile_inspector_get_selected_element(w);
+    if (tileElement == nullptr)
+        return;
+
+    switch (tileElement->GetType())
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/TileInspector.cpp:1005]: Shouldn't we have a validate function that confirms the type matches the page. You can't check widget addresses across pages so any miss match will cause very unexpected behaviour.

Comment (Broxzier) [reply src/openrct2-ui/windows/TileInspector.cpp:1005]: Probably not a bad idea. It _should_ be impossible for the selected elements's type and current page to not match, but an assert and exit should at least avoid crashes.

Comment (duncanspumpkin) [reply src/openrct2-ui/windows/TileInspector.cpp:1005]: It would happen if your on a server and two people edit the same tile

Comment (IntelOrca) [reply src/openrct2-ui/windows/TileInspector.cpp:1005]: > assert and exit should at least avoid crashes.

That is still a crash. So better to just return and not show anything.

Comment (Broxzier) [reply src/openrct2-ui/windows/TileInspector.cpp:1005]: >It would happen if your on a server and two people edit the same tile

If two players edit the same tile, the local selection index is updated accordingly, so it should be impossible still. That's why an assert may be preferable here, as that way it'll be found out when it gets broken instead of failing silently.

I may be misunderstanding something, but asserts do not crash the game, right? They just show a message that can be clicked away and the game continues its execution.
