### PR TITLE
Prevent closing object selection window when selection is invalid

### LINKED ISSUE #23486: Object selection minimum requirements can be bypassed with close window hotkey
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

OpenRCT2 Release 0.4.17

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When using the object selection window from the cheats button in-game, you can bypass minimum object requirements just by using the close window hotkey (backspace by default) which can allow you to create save files with invalid object setups (eg: 0 path surfaces).

This only applies to the in-game object selection window accessible from the cheats button, the one in the scenario editor doesn't respond to the hotkey.

### Steps to reproduce

1. Open any park.
2. Open the object selection window from the cheats button.
3. Deselect all of any required object type (eg: disable all path surfaces).
4. Try to close the window with the X button, you get blocked as expected.
5. Try to close the window with the hotkey, you bypass the block.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This PR allows internal windows to prevent their own closure. This is achieved by changing the global signature for the window `OnClose` event from `void` to `bool`. Currently, all windows simply return `true` to allow their closure at all times. The one exception is the object selection window, which can now return `false` if the current selection is invalid.

Fixes #23486.

### CODE REVIEW

File: src/openrct2/interface/Window.cpp [hunk 1]
```diff
@@ -227,7 +227,11 @@ void WindowSetWindowLimit(int32_t value)
  */
 void WindowClose(WindowBase& w)
 {
-    w.OnClose();
+    if (!w.OnClose())
+    {
+        // Something's preventing this window from closing -- bail out early
+        return;
+    }
```
Comment (tupaschoal) [inline src/openrct2/interface/Window.cpp:234]: I wonder whether it would be clearer from a design standpoint if we added another function instead, and made it such as:

```c++
if (w.CanClose())
{
    w.OnClose();
}
```

Then you wouldn't need to touch so many windows, reducing the PR size, and I think it would be easier for the random contributors to understand what is expected

Comment (ZehMatt) [reply src/openrct2/interface/Window.cpp:234]: I also agree with this, OnClose should stay strictly an event for when the window is really going to close. It would also reduce the amount of changes needed as not all windows need to override CanClose. Also how sure are we that this function is always used to close a window?

Comment (AaronVanGeffen) [reply src/openrct2/interface/Window.cpp:234]: Alright, I'll add another `CanClose` function then.

> Also how sure are we that this function is always used to close a window?

Well, it is literally called when a window is on the cusp of being closed. One of the window event functions.

Comment (ZehMatt) [reply src/openrct2/interface/Window.cpp:234]: I've seen code like w->Close() so just making sure it actually ends up preventing it. This adds a bit of fuzzyness given that when someone calls WindowClose or w->Close one would ordinarily expect the window to be closed but I can see to why we should prevent it, at least that one window. Not gonna lie not a big fan of adding a virtual function for that one window but I can't really think of any better solution at the moment.

**Review by tupaschoal — APPROVED** [review]
Looks ok, needs the changelog entry
