### PR TITLE
Fix #23859: Wrong banner text displayed after loading different park

### LINKED ISSUE #23859: Wrong ride name displayed on queue banner
### Operating System

Windows 11 64 bit

### OpenRCT2 build

v0.4.19.1 (008a476b8f)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

I first opened up a park that had a coaster named Wild Vines:
Image

Then I opened up a different park that has a ride named Railroad, with 4 stations. One of the queue banners in the screen displays Wild Vines. The other one still displays Railroad. If I rotate the view 90 degrees a different queue displays the text Wild Vines. The sign looks a bit glitchy and restarts earlier than a normal sign would.

Image

After opening the first park again I noticed the ride name on the queue banner changed to railroad. It sometimes glitches a bit and switches to the original names for a split second.

Image

I went through some more parks and I noticed another queue banner swap. Here's a ride called Minetrain of which the queue banner says Tiny Twister, which was in the park I looked at before it.

Image

### Steps to reproduce

Open this park first
[MC2_Aj_Perry.zip](https://github.com/user-attachments/files/18889837/MC2_Aj_Perry.zip)

Then open this park
[MC2_andae23.zip](https://github.com/user-attachments/files/18889848/MC2_andae23.zip)

Then look at the queue banners. One should display the wrong ride name

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by frozensnowy**
Fixes #23859 and also the crash reported in #25659 (Haiku port) where multithreaded rendering caused use-after-free in the banner text formatting

I was asked by @Gymnasiast to take a look at these bugs so here we are...

## Overviewing the problem(s)

My first assumption was that these issues were related to the formatter and text rendering code, but the actual root causes were somewhere else

Based on the Haiku developer's analysis in #25659: "This indicates pretty clearly that OpenRCT is performing a use-after-free. The freeing thread is different from the allocating thread." Combined with the knowledge that disabling multithreaded rendering completely eliminated the crashes, it pointed me toward a threading issue rather than a formatter bug

I also think both reported problems, being crashes on Haiku and wrong text across parks were actually two separate bugs that happened to manifest in similar ways, in the form of banner text issues. I'll explain why, below.

## Root Cause Analysis

**Bug 1: Race condition in `Banner::formatTextWithColourTo()`**

The `Banner` struct had a `mutable std::string formattedTextBuffer` member that was written during every call to `formatTextWithColourTo()`. When multithreaded rendering is going on, viewport columns are processed in parallel (see `Viewport.cpp`). 

When the same banner is visible in multiple columns:
1. Thread A calls `formatTextWithColourTo()`, writes to `formattedTextBuffer`, stores pointer in Formatter
2. Thread B calls `formatTextWithColourTo()` on the same Banner, writes to `formattedTextBuffer` (potentially reallocating)
3. Thread A's pointer is now dangling

This would explain both the Haiku crashes, the use-after-free detected by their malloc implementation, and the flickering text, aka threads reading partially written data.

**Bug 2: ScrollingText cache not invalidated on park load**

The scrolling text cache in `ScrollingText.cpp` matches entries using:
```cpp
std::memcmp(scrollText->string_args, ft.Buf(), sizeof(scrollText->string_args)) == 0
```

The `string_args` buffer contains raw Formatter data, including `const char*` pointers to ride/banner names. 

When loading a new park:
1. Park A has a cache entry created with pointer `0x12345678` pointing to "Wild Vines", bitmap rendered
2. Park B is loaded and the memory gets freed and reallocated
3. New ride allocated at same address `0x12345678` containing "Railroad"
4. Cache lookup happens where `memcmp` matches because the raw pointer value is identical
5. The result is that the old bitmap showing "Wild Vines" rears its head

This explains why wrong text persisted across parks specifically, and why it wasn't just momentary flickering.

It was hard to diagnose because:
1. The `mutable` keyword on `formattedTextBuffer` made it non obvious that a `const` method was modifying shared state
2. The race condition only happens with multithreading enabled, and timing dependent bugs are extremely hard to reproduce and locate
3. The cache issue requires specific memory reuse patterns that depend on allocator behavior
4. Both bugs produced similar symptoms (wrong banner text), making it seem like one issue was happening
5. The formatter code was suspected but was actually not involved at all here

## So: 

**Fix 1:** Remove `mutable std::string formattedTextBuffer` from Banner struct and replace it with `thread_local std::string` inside the function. This pattern is already used a bunch of times in the codebase (TTF.cpp, Chat.cpp, Drawing.String.cpp, ScrollingText.cpp, etc.).

**Fix 2:** Add `ScrollingText::invalidate()` calls to both park loading paths.
- `GameLoadInit()` which handles normal park loading like File menu, network, replays, scenarios
- `TitleSequencePlayer::PrepareParkForPlayback()` which handles title sequence loading, this is a separate code path that bypasses GameLoadInit

This matches the existing pattern where `invalidate()` is already called when ride names, banner names, park names, or language settings change

// End tedtalk

### CODE REVIEW

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Nice job!

Since these are unrelated issues, I'd like you to split up the commit into two.

Commit 1 should contain the fix and changelog entry for #23859.

Commit 2 should contain the fix for the use-after-free, with its own changelog entry, and 25908 as its reference (instead of 25659).

File: src/openrct2/world/Banner.cpp [hunk 1]
```diff
@@ -52,6 +52,11 @@ std::string Banner::getText() const
 
 void Banner::formatTextWithColourTo(Formatter& ft) const
 {
+    // Use thread_local buffer to avoid race conditions during multithreaded rendering.
+    // Multiple threads can call this on the same Banner simultaneously when rendering
+    // different viewport columns in parallel.
+    thread_local std::string formattedTextBuffer;
```
Comment (Gymnasiast) [inline src/openrct2/world/Banner.cpp:58]: I guess this needs to be `thread_local` in order to keep the reference to the string in Formatter valid. Have I understood that correctly?

Comment (frozensnowy) [reply src/openrct2/world/Banner.cpp:58]: Yes, that's one reason, the pointer stored in Formatter needs to remain valid until rendering completes. but the main reason is thread safety because the original mutable member meant all threads shared the same buffer, so when multiple threads called this on the same banner at the same time, they'd race to write to it. With thread_local, each thread gets its own buffer and that makes sure both the race condition and the lifetime issue don't happen

**Comment by Gymnasiast** [comment]
I have renamed commit `Fix #25908: Crash from use-after-free in banner text formatting during multithreaded rendering` to `Fix: Crash from use-after-free in banner text formatting during multithreaded rendering`.

The reason for this is that there was never an issue for this problem. As such, any commits message will just lack a reference, and in the changelog we refer to the PR that fixed it instead.

Also rebased to resolve merge conflicts with the changelog.

**Comment by Gymnasiast** [comment]
@Peppersawce Could you test if this solves the crash when multithreaded rendering is on?

**Review by Gymnasiast — APPROVED** [review]
Seems to work well on my machine.

Awaiting @deurklink ’s test for the stale banner text stuff.

**Comment by deurklink** [comment]
Just tested out this pull, the behavior from issue #23859 is no longer present.

**Comment by Peppersawce** [comment]
> @Peppersawce Could you test if this solves the crash when multithreaded rendering is on?

Sure, I'll try compiling from the latest source one of these days and let you guys know.
(And make a PR to restore the config *if* it works)
