### PR TITLE
Fix #25961: Only draw next vehicle sprite if it is present

### LINKED ISSUE #25961: [12477d] openrct2.exe: OpenRCT2::Ui::Windows::RideWindow::VehicleOnScrollDraw
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIxMjQ3N2QzNDhmYTU0ZTc1YTY1NGE5NTllNWIyYzM3NTliNTE5ZTFlMTM3ZmVhODE1MTI3ZDg5NDVmMDY2MDdkIiwidHgiOjM0NzgzfSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=12477d348fa54e75a654a959e5b2c3759b519e1e137fea815127d8945f06607d&amp;_tx=87df&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Fri Feb 06 2026 20:06:10 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\maxma\Documents\OpenRCT2\crash\e414c722-9fe9-4429-84f3-147b52f73031.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                e7246eb2f1 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x00000000000000010000000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.31 (e7246eb2f1 on develop) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>0b000000-479f-390f-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2::Ui::Windows::RideWindow::VehicleOnScrollDraw</code> 
                                <code>OpenRCT2::Ui::WidgetScrollDraw</code> 
                                <code>OpenRCT2::Ui::widgetDraw</code> 
                                <code>OpenRCT2::Ui::Windows::WindowDrawWidgets</code> 
                                <code>OpenRCT2::Ui::Windows::RideWindow::VehicleOnDraw</code> 
                                <code>OpenRCT2::WindowDrawSingle</code> 
                                <code>OpenRCT2::WindowDrawCore</code> 
                                <code>OpenRCT2::WindowDraw</code> 
                                <code>invoke</code> 
                                <code>std::_Func_impl_no_alloc&lt;`OpenRCT2::WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,OpenRCT2::WindowBase *&gt;::_Do_call</code> 
                                <code>OpenRCT2::WindowVisitEach(std::function&lt;void __cdecl(OpenRCT2::WindowBase *)&gt;)</code> 
                                <code>OpenRCT2::WindowDrawAll</code> 
                                <code>OpenGLDrawingEngine::DrawDirtyBlocks</code> 
                                <code>OpenRCT2::Drawing::InvalidationGrid::traverseDirtyCells&lt;`OpenGLDrawingEngine::DrawAllDirtyBlocks&#39;::`2&#39;::&lt;lambda_1&gt; &gt;</code> 
                                <code>OpenGLDrawingEngine::DrawAllDirtyBlocks</code> 
                                <code>OpenGLDrawingEngine::PaintWindows</code> 
                                <code>OpenRCT2::Paint::Painter::Paint</code> 
                                <code>OpenRCT2::Context::Draw</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::Launch</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> OpenRCT2::Ui::Windows::RideWindow::VehicleOnScrollDraw OpenRCT2::Ui::WidgetScrollDraw OpenRCT2::Ui::widgetDraw OpenRCT2::Ui::Windows::WindowDrawWidgets OpenRCT2::Ui::Windows::RideWindow::VehicleOnDraw OpenRCT2::WindowDrawSingle OpenRCT2::WindowDrawCore OpenRCT2::WindowDraw invoke std::_Func_impl_no_alloc&lt;`OpenRCT2::WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,OpenRCT2::WindowBase *&gt;::_Do_call OpenRCT2::WindowVisitEach(std::function&lt;void __cdecl(OpenRCT2::WindowBase *)&gt;) OpenRCT2::WindowDrawAll OpenGLDrawingEngine::DrawDirtyBlocks OpenRCT2::Drawing::InvalidationGrid::traverseDirtyCells&lt;`OpenGLDrawingEngine::DrawAllDirtyBlocks&#39;::`2&#39;::&lt;lambda_1&gt; &gt; OpenGLDrawingEngine::DrawAllDirtyBlocks OpenGLDrawingEngine::PaintWindows OpenRCT2::Paint::Painter::Paint OpenRCT2::Context::Draw OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -3043,7 +3043,8 @@ namespace OpenRCT2::Ui::Windows
                     y -= (carEntry.spacing / 2) / 17432;
                 }
 
-                if (ride->getRideTypeDescriptor().flags.has(RtdFlag::layeredVehiclePreview))
+                if (ride->getRideTypeDescriptor().flags.has(RtdFlag::layeredVehiclePreview)
+                    && (nextSpriteToDraw - trainCarImages) >= 2)
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/Ride.cpp:3053]: This is not an intuitive equation, to me. I suppose it reads like two different types/units are involved. I would guess, `nextSpriteToDraw` is an image id/index, while `trainCarImages` is a count or offset of images? Or are both image ids/incides?

Comment (janisozaur) [reply src/openrct2-ui/windows/Ride.cpp:3053]: https://github.com/OpenRCT2/OpenRCT2/blob/03c33b026e160da369afc6b7b6d8f321e5eed3c7/src/openrct2-ui/windows/Ride.cpp#L2991-L2992
`nextSpriteToDraw` is a pointer into `trainCarImages` array. A very similar calculation is done just after the block being changed:
https://github.com/OpenRCT2/OpenRCT2/blob/03c33b026e160da369afc6b7b6d8f321e5eed3c7/src/openrct2-ui/windows/Ride.cpp#L3053-L3055

Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/Ride.cpp:3053]: Thanks for the clarification. Tbh, this entire function isn't going to win any competitions. I _can_ see where the two comes in, of course, given the body block.

I think maybe we should just go for it, for now. I'd definitely like to see the function chopped up into logical blocks, though. Extracting the inner for loop would go a long way, for example, right. I might give that a go later.

**Review by AaronVanGeffen — COMMENTED** [review]
Worth a changelog entry? (Something with malformed vehicles?)

**Review by AaronVanGeffen — APPROVED** [review]

File: src/openrct2-ui/windows/Ride.cpp (hunk 1 above)
Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/Ride.cpp:3053]: Following up in #26080 (WIP)

File: distribution/changelog.txt [hunk 2]
```diff
@@ -1012,6 +1012,7 @@
 - Fix: [#20099] Some scrollbar is glitched or have incorrect size when open window for the first time.
 - Fix: [#20104] [Plugin] Some network APIs use player index and group index.
 - Fix: [#20134] Grass length being updated for tiles in the void, causing unneccesary drawing operations.
+- Fix: [#25961] Fix crash when rendering malformed vehicles in the ride window.
```
Comment (Gymnasiast) [inline distribution/changelog.txt:1015]: Why did you list this fix under version 0.4.5? That was released 3 years ago.

Comment (janisozaur) [reply distribution/changelog.txt:1015]: Oh wow, that's so bad. Thanks for catching this

https://github.com/OpenRCT2/OpenRCT2/pull/26090
