### PR TITLE
Fix #24761: Reliability progress bar no longer has a min value of 10

### LINKED ISSUE #24761: Ride window Reliability bar has wrong length
### Operating System

Windows 11 64-bit

### OpenRCT2 build

v0.4.24-39-gfdc4d4d892

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Image

In the ride window, the Realiability bar has the wrong length compared to the percentage (it's also like that for over 1% values). Bug also present in a version some weeks old.

### Steps to reproduce

Click a ride window and let it open for some time during which a mechanic fixes the ride.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by NylePudding**
PR for fixing #24761 

This is a strange one as it's unclear why this was like this in the first place. I have done some testing and don't know why the use of the max function was in place initially. This has been here for almost a decade though, so it's very much possible I'm missing something obvious. That said even if the reliability couldn't go below 10, it seems confusing to limit it here?

Anyway, I'm keen to find out why it was like this in the first place, no any ideas or info is very welcome before this gets merged in. :)

### CODE REVIEW

**Comment by ZehMatt** [comment]
Is this issue also in the vanilla game? It could be simply a bad reimplementation where it was meant to be 1 and not 10.

**Comment by NylePudding** [comment]
> Is this issue also in the vanilla game? It could be simply a bad reimplementation where it was meant to be 1 and not 10.

Good point, never thought it could be a typo. The strange part is how the downTime progress bar doesn't share this issue. When I'm next at my dev computer I will check the history for the downTime bar.

**Comment by NylePudding** [comment]
If this does occur in vanilla, what's the policy for fixing those bugs? If this has no breakage should it even be merged in?

**Comment by AaronVanGeffen** [comment]
Tbh I think it might be stuck at 10 for visibility reasons. I'd have to check the disassembly though.

**Comment by NylePudding** [comment]
> Tbh I think it might be stuck at 10 for visibility reasons. I'd have to check the disassembly though. 

Sort of makes sense, but I guess that begs the question why would this be like this for visibility reasons when the downTime bar doesn't have this treatment. 

I guess it's more important the player is an aware of low reliability than low downtime?

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -4032,7 +4032,7 @@ namespace OpenRCT2::Ui::Windows
                 return;
 
             uint16_t reliability = ride->reliabilityPercentage;
-            widgetProgressBarSetNewPercentage(widgets[WIDX_RELIABILITY_BAR], std::max<uint8_t>(10, reliability));
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Ride.cpp:4035]: You're misinterpreting this. It means the value will be 10 or the actual reliability, whichever is _higher_. It makes 10 the minimum, rather than the maximum.

Comment (NylePudding) [reply src/openrct2-ui/windows/Ride.cpp:4035]: Ah crumbs, I understand that's how it works I just wrote the title and the comment message wrong.

Comment (NylePudding) [reply src/openrct2-ui/windows/Ride.cpp:4035]: @Gymnasiast I have amended my commit message, to "reliability progress bar no longer has min value of 10" the code itself is still valid, can you please review again? :)

**Comment by NylePudding** [comment]
> Tbh I think it might be stuck at 10 for visibility reasons. I'd have to check the disassembly though.

I did some investigation and this behaviour does in fact occur in the original RCT2 (at least the Triple Thrill pack version on Steam) But I have no idea why it's like this, because you can see it's not consistent with the Down-Time bar. 

image

I think it makes sense for both bars to behave the same, right?

**Comment by tupaschoal** [comment]
@NylePudding I think a good test would be to hack the code and set the variables being read there for reliability and down-time to their max and seeing how they're drawn. I'm assuming they would fill-up the bar, but reaching that ingame might be very tricky.

**Comment by NylePudding** [comment]
@tupaschoal This was the first thing I did, it looks fine, I will attach some screenshots when I get an opportunity. :)

**Comment by NylePudding** [comment]
> @NylePudding I think a good test would be to hack the code and set the variables being read there for reliability and down-time to their max and seeing how they're drawn. I'm assuming they would fill-up the bar, but reaching that ingame might be very tricky.

Here's a comparison of the bars ranging from 0-10, and it all behaves as it should. (of course ignore the numbered values)

OpenRTC2_downtime_reliabilty_comp

I also made a quick check for this in the RCT1 and it's not an issue because the bars aren't there in the first place.

ORTC1_downtime_reliability

Finally I updated the change log if this fix is approved, in hindsight I should have made this PR is draft, won't make this mistake next time. :)

File: distribution/changelog.txt [hunk 2]
```diff
@@ -5,6 +5,7 @@
 - Change: [#24730] Security guards now only walk slowly in crowded areas.
 - Fix: [#24598] Cannot load .park files that use official legacy footpaths by accident.
 - Fix: [#24711] The map smoothing function only partially works for custom height map image files.
+- Fix: [#24761] Reliability bar in the ride inspector now acts consistently with the Down-Time bar, it no longer has a minimum value of 10.
```
Comment (AaronVanGeffen) [inline distribution/changelog.txt]: By convention, we describe the issue rather than the fix.
```suggestion
- Fix: [#24761] The reliability bar in the ride window visually does not go below 10%.
```

**Review by AaronVanGeffen — APPROVED** [review]
To my knowledge, the reliability score never goes below zero, so I think we can risk this :)

**Review by tupaschoal — APPROVED** [review]
