### PR TITLE
Fix #17481: Roto-drop cars try going up to the wrong top pieces

### LINKED ISSUE #17481: Roto drop built on top of another without top piece can crash the bottom roto drop
### Operating System

MarcelvOS

### OpenRCT2 build

?

### Describe the issue

See this Marcel Vos video at around this time: https://youtu.be/in1FVEV5bww?t=530, where the bug is reproduced and described.

The suggestion is to customise the 'topless' roto drop behaviour so that it always operates like a standalone topless roto drop, regardless of surrounding rides. I.e.: the vehicle stays at the bottom. As suggested by Marcel, this might be due to the bottom roto drop detecting a (ghost) top piece from another roto drop being built above itself. If that is the cause of the bug, then it should not detect pieces that aren't part of its own ride.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Build a roto drop without a top piece and open it.
2. Build a roto drop exactly on top of it and have the build ghost of the top piece showing.
3. Wait until the bottom roto drop starts riding.
4. Get rid of the ghost top piece.
5. The bottom roto drop will crash or start crashing permanently.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
This adds two checks:
- For the ride id, so that it won’t go up to top pieces that belong to other rides
- For ghosts, which fixes a very similar bug when you use ghost train simulation mode on tower rides.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I'd prefer to see it laid out into multiple ifs. I find this style harder to read and it doesn't match the rest of the codebase

File: src/openrct2/ride/Vehicle.cpp [hunk 1]
```diff
@@ -3011,18 +3011,22 @@ void Vehicle::TestReset()
     test_reset(*curRide, current_station);
 }
 
-bool Vehicle::CurrentTowerElementIsTop()
+bool Vehicle::CurrentTowerElementIsTop(RideId currentRideId)
```
Comment (Broxzier) [inline src/openrct2/ride/Vehicle.cpp:3014]: You can omit this argument entirely, the vehicle stored the RideID already.

**Review by duncanspumpkin — APPROVED** [review]
