### PR TITLE
Fix presets from old vehicle type being used for new vehicle type (fixes #3014)

### LINKED ISSUE #3014: Crash in debug builds when switching between vehicle types
**OS:** Windows 10 x64
**Version:** 0.04
**Commit:** adde88c

The game crashes when switching between vehicle types a couple of times.

- [ ] Original bug?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a Monorail with all 3 vehicle types
2. Switch vehicle type between "Streamlined" and "Retro"
3. Do this a couple of times (~5) and the game will crash

This crash only occurs in debug builds and happens somewhere around this line (the stack trace is kinda useless due to the vtables):

https://github.com/OpenRCT2/OpenRCT2/blob/adde88ca920253484b6847a494fbfb635226b5fc/src/windows/ride.c#L2764

From this line on a crash in `memcpy` is caused and it happens when drawing the first vehicle of a train for the preview.

### PR DESCRIPTION
**Pull request by Overv**
This fixes `ride_get_unused_preset_vehicle_colour` using the old vehicle type to select a preset when switching vehicle types.

### CODE REVIEW

File: src/ride/ride.c [hunk 1]
```diff
@@ -7551,7 +7549,14 @@ void game_command_set_ride_vehicles(int *eax, int *ebx, int *ecx, int *edx, int
 		invalidate_test_results(rideIndex);
 		rideEntry = get_ride_entry(ride->subtype);
 		ride->subtype = value;
+
+		if (!(*ebx & GAME_COMMAND_FLAG_NETWORKED)) {
```
Comment (Overv) [inline src/ride/ride.c]: The `GAME_COMMAND_FLAG_APPLY` has already been checked before this point and the value of `eax` is not read before this point.
