### PR TITLE
MapCanConstructAt refactor

### LINKED ISSUE #11675: [d59b15] openrct2.exe: strnlen, format_string_code, format_string_part_from_raw, format_string, GameActionResult::GetErrorMes...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/d59b15c09d062e062a6f9db2c3c1aec488847c1bde75f8a75f9e916117509cf4">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
strnlen
format_string_code
format_string_part_from_raw
format_string
GameActionResult::GetErrorMessage
GameActions::ExecuteInternal
window_staff_overview_tool_down
input_widget_left
game_handle_input_mouse
game_handle_input
context_handle_input
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by duncanspumpkin**
I've been meaning to do this for a while now. This passes back the game action result from map can construct at which means that less global state has to be played with. Also this should fix #11675 (and its duplicates).
There is still work to do in a later PR with refactoring the uses of `map_can_construct_with_clear_at` with `MapCanConstructWithClearAt`. Once that is done we can finally get rid of the `GroundFlags` global var.

### CODE REVIEW

File: src/openrct2/actions/PlaceParkEntranceAction.hpp [hunk 1]
```diff
@@ -93,10 +93,11 @@ DEFINE_GAME_ACTION(PlaceParkEntranceAction, GAME_COMMAND_PLACE_PARK_ENTRANCE, Ga
                 entranceLoc.y += CoordsDirectionDelta[(_loc.direction + 1) & 0x3].y * 2;
             }
 
-            if (!map_can_construct_at({ entranceLoc, zLow, zHigh }, { 0b1111, 0 }))
+            if (auto res2 = MapCanConstructAt({ entranceLoc, zLow, zHigh }, { 0b1111, 0 }); res2->Error != GA_ERROR::OK)
```
Comment (Gymnasiast) [inline src/openrct2/actions/PlaceParkEntranceAction.hpp:96]: I'd prefer if the assignment would take place outside the if. I think this is hard to read (and also not consistent with the rest of the code).

Comment (duncanspumpkin) [reply src/openrct2/actions/PlaceParkEntranceAction.hpp:96]: the result is only useful for the inside of the if statement. It doesn't seem that useful bringing it out into the larger scope of the function.
