### PR TITLE
Close #11437: Migrate old platform methods

### LINKED ISSUE #11437: Refactor platform source files
Currently, the platform source files are halfway in between refactoring. We started to rewrite routines to use more modern C++, but some legacy (C) routines were left behind. The wait was for `std::filesystem` to be available on all platforms, but that's been available since #10261.

Note that functions should not be moved as-is. We prefer to move to take the opportunity to rewrite them to use `std::string` and `std::filesystem` routines instead.

The following are the 'new' platform files:

- Platform.Android.cpp
- Platform.Linux.cpp
- Platform.macOS.mm
- Platform.Posix.cpp
- Platform.Win32.cpp
- Platform2.h

The following are files whose functions need to be refactored into the new files:

- Android.cpp
- Linux.cpp
- macos.mm
- platform.h
- Posix.cpp
- Shared.cpp
- Windows.cpp

Note that Crash.cpp and Crash.h are not on this list.

Please contact us here or on Discord if you'd like to work on this.

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/core/String.cpp [hunk 1]
```diff
@@ -39,6 +39,10 @@
 #include "String.hpp"
 #include "StringBuilder.h"
 
+#ifdef __ANDROID__
+#    include <jni.h>
+#endif // __ANDROID__
+
```
Comment (Gymnasiast) [inline src/openrct2/core/String.cpp:45]: Revert

File: src/openrct2-cli/Cli.cpp [hunk 2]
```diff
@@ -21,7 +21,7 @@ int main(int argc, const char** argv)
 {
     int32_t rc = EXIT_SUCCESS;
     int runGame = cmdline_run(argv, argc);
-    core_init();
+    Platform::CoreInit();
```
Comment (ZehMatt) [inline src/openrct2-cli/Cli.cpp:24]:
```suggestion
    Platform::Init();
```
I think this would be a bit nicer, just a suggestion.

File: src/openrct2-ui/windows/Options.cpp [hunk 3]
```diff
@@ -681,7 +681,7 @@ class OptionsWindow final : public Window
                 break;
             case WIDX_MINIMIZE_FOCUS_LOSS:
                 gConfigGeneral.minimize_fullscreen_focus_loss ^= 1;
-                platform_refresh_video(false);
+                RefreshVideo(false);
```
Comment (tupaschoal) [inline src/openrct2-ui/windows/Options.cpp:684]: Weird, is this one out of the namespace or is there an using lurking nearby that I missed?

File: src/openrct2-ui/input/Shortcuts.cpp [hunk 4]
```diff
@@ -774,7 +774,7 @@ void ShortcutManager::RegisterDefaultShortcuts()
         }
     });
 
-    RegisterShortcut(ShortcutId::ScaleToggleWindowMode, STR_SHORTCUT_WINDOWED_MODE_TOGGLE, "ALT+RETURN", []() { platform_toggle_windowed_mode(); });
+    RegisterShortcut(ShortcutId::ScaleToggleWindowMode, STR_SHORTCUT_WINDOWED_MODE_TOGGLE, "ALT+RETURN", []() { ToggleWindowedMode(); });
```
Comment (tupaschoal) [inline src/openrct2-ui/input/Shortcuts.cpp:777]: Same question for namespace here

File: src/openrct2-ui/windows/Options.cpp (hunk 3 above)
Comment (Gymnasiast) [reply src/openrct2-ui/windows/Options.cpp:684]: It’s not a platform function, so I dropped that prefix. Same thing applies to the other occurrences.

**Review by ZehMatt — APPROVED** [review]
