### PR TITLE
Fix #18970: Trying to load a non-park save will now display context error

### LINKED ISSUE #18970: Trying to load a non-park save does nothing
### Operating System

Windows 10, 64bit

### OpenRCT2 build

v0.4.3

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

_No response_

### Describe the issue

When you use the system file selector, tell it to match any file and then try to load something that is clearly not a park save, it will just close silently without any error. It should error out that it is not a save or that the file is corrupted, which is what already happens when you try to load something that is not a scenario as one.

### Steps to reproduce

1. Open the load window
2. Use the system file browser
3. Change the filter to show all files
4. Try to select a non-park save file

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by jazzysoggy**
Fix #18970
Issue: Trying to load a non-park save file or corrupted park save would error silently, giving no context to the user what had occurred. 

Fix: Added a call to Editor::LoadLandscape(pathBuffer) to check whether a file is a valid park save file. If it returns true, the loading procedure continues as normal. If it returns false, the loading procedure is stopped and a context error is displayed.

### CODE REVIEW

File: src/openrct2-ui/windows/LoadSave.cpp [hunk 1]
```diff
@@ -269,9 +269,18 @@ static void Select(const char* path)
     {
         case (LOADSAVETYPE_LOAD | LOADSAVETYPE_GAME):
             SetAndSaveConfigPath(gConfigGeneral.LastSaveGameDirectory, pathBuffer);
-            InvokeCallback(MODAL_RESULT_OK, pathBuffer);
-            window_close_by_class(WindowClass::Loadsave);
-            gfx_invalidate_screen();
+            if (Editor::LoadLandscape(pathBuffer))
```
Comment (tupaschoal) [inline src/openrct2-ui/windows/LoadSave.cpp:272]: I think the `LoadLandscape` is not the best choice, as it only accounts for extensions compatible with landscape and doesn't account for `.sea` or `.sv7 (though I don't know if it should, should it @Gymnasiast?). `Context::LoadParkFromFile` seems more appropriate, though one might wonder if this is exactly the same thing that the callback is doing.

Comment (jazzysoggy) [reply src/openrct2-ui/windows/LoadSave.cpp:272]: I tested with Context:LoadParkFromFile originally, and it worked as well, but InvokeCallback also calls that indirectly as well, so I’m sure if that would be optimum.

Comment (tupaschoal) [reply src/openrct2-ui/windows/LoadSave.cpp:272]: Yeah, that's what I thought, if it would be wasteful. @Gymnasiast can you weigh in on my first comment, please?

Comment (Gymnasiast) [reply src/openrct2-ui/windows/LoadSave.cpp:272]: I agree with you. Editor::LoadLandscape is made specifically to, well, load landscapes. In general, our load/save functions seem to have overlap. By the way, the point about loading twice (once here, once in the callback) appears to apply to all cases, whether you call Editor::LoadParkFromFile() or Context::LoadParkFromFile() or even another function.

Comment (tupaschoal) [reply src/openrct2-ui/windows/LoadSave.cpp:272]: Yeah, there's also that, other places are already doing it twice.

Can you please change it accordingly then Henry?

Comment (jazzysoggy) [reply src/openrct2-ui/windows/LoadSave.cpp]: Changed the check from LoadLandscape to LoadParkFromFile

**Review by tupaschoal — APPROVED** [review]
Tested and it works just fine, thanks!

**Comment by Gymnasiast** [comment]
@tupaschoal Could you create an issue about 1) the duplication, and 2) the missing extensions from the Editor::LoadLandscape method?
