### PR TITLE
Fix #9559: benchspritesort is broken after #8481

### LINKED ISSUE #9559: benchspritesort got broken in #8481
```
$ ./openrct2 benchspritesort out/usr/local/share/openrct2/title/titleseq/CocoaBayou.sv6 --benchmark_min_time=0.1
INFO[../src/openrct2/cmdline/BenchSpriteSort.cpp:74 (extract_paint_session)]: Starting...
INFO[../src/openrct2/cmdline/BenchSpriteSort.cpp:128 (extract_paint_session)]: Obtaining sprite data...
INFO[../src/openrct2/cmdline/BenchSpriteSort.cpp:134 (extract_paint_session)]: Got 0 paint sessions.
2019-07-13 16:37:10
Run on (4 X 1500 MHz CPU s)
Load Average: 0.14, 2.24, 3.73
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
---------------------------------------------------------------------
Benchmark           Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------
baseline         2175 ns         1987 ns        70500 items_per_second=503.291k/s
$
```

#8481 broke benchmarking with `benchspritesort` (https://github.com/OpenRCT2/OpenRCT2/pull/8458)

### PR DESCRIPTION
**Pull request by janisozaur**
This takes multithreading into account as well

### CODE REVIEW

File: src/openrct2/interface/Viewport.cpp [hunk 1]
```diff
@@ -836,9 +836,26 @@ void viewport_render(
...
 
-static void viewport_fill_column(paint_session* session)
+static void viewport_fill_column(paint_session* session, std::vector<paint_session>* sessions, size_t index)
 {
     paint_session_generate(session);
+    // Perform a deep copy of the paint session, use relative offsets.
+    // This is done to extract the session for benchmark.
+    if (sessions != nullptr)
+    {
+        (*sessions)[index] = (*session);
```
Comment (ZehMatt) [inline src/openrct2/interface/Viewport.cpp]: I think it would be better to move the code into a new function to better separate the testing code out visibly.

File: src/openrct2/interface/Viewport.cpp [hunk 2]
```diff
@@ -937,6 +954,11 @@ void viewport_paint(
 
     // Splits the area into 32 pixel columns and renders them
     size_t index = 0;
+    uint16_t column_count = (rightBorder - floor2(dpi1.x, 32)) / 32 + 1;
```
Comment (ZehMatt) [inline src/openrct2/interface/Viewport.cpp]: This should be only done when sessions != nullptr otherwise unused.

File: src/openrct2/interface/Viewport.cpp [hunk 3]
```diff
@@ -836,9 +836,26 @@ void viewport_render(
 #endif
 }
 
-static void viewport_fill_column(paint_session* session)
+static void viewport_fill_column(paint_session* session, std::vector<paint_session>* sessions, size_t index)
```
Comment (ZehMatt) [inline src/openrct2/interface/Viewport.cpp]: The thing between session and sessions is unclear the same applies to the index, would be better to give it more concrete names.

File: src/openrct2/interface/Viewport.cpp (hunk 1 above)
Comment (ZehMatt) [inline src/openrct2/interface/Viewport.cpp]: You can also copy it after getting session_copy

**Comment by janisozaur** [comment]
Hey @ZehMatt can you take another look? I addressed all your comments

File: src/openrct2/interface/Viewport.cpp [hunk 4]
```diff
@@ -827,9 +827,33 @@ void viewport_render(
...
 }
 
-static void viewport_fill_column(paint_session* session)
+static void record_session(const paint_session* session, std::vector<paint_session>* recorded_sessions, size_t record_index)
+{
+    // Perform a deep copy of the paint session, use relative offsets.
+    // This is done to extract the session for benchmark.
+    // Place the copied session at provided record_index, so the caller can decide which columns/paint sessions to copy; there
+    // is no column information embedded in the session itself.
+    if (recorded_sessions != nullptr)
```
Comment (ZehMatt) [inline src/openrct2/interface/Viewport.cpp]: Makes more sense to check that before the call, also have you forgotten our coding style by now 😄

Comment (janisozaur) [reply src/openrct2/interface/Viewport.cpp]: Yeah, I figured as this is TU-local function I would rather put this check inside, since all our builds use LTO anyway and not clobber up the caller. I'll update it if that's what you prefer.

Tha clang-format check passes, do you have anything else in mind?

Comment (ZehMatt) [reply src/openrct2/interface/Viewport.cpp]: Looks otherwise good. The reason why I want the check moved is that you can avoid the call and it makes it more clear.

Comment (janisozaur) [reply src/openrct2/interface/Viewport.cpp]: Updated
