### PR TITLE
Fix #5417: Crooked House tracked rides do not dispatch vehicles

### LINKED ISSUE #5417: Crooked House Tracked Rides Not Running
**OS:** Windows 10]
**Version:** [0.0.7]
**Commit/Build:** [1ab90d8]

A common hack used in some RCT parks is to change the ride track type to "crooked house", this enables the track to become invisible... often useful for realistic rapids rides to hide the default rapids track.  However, upon loading these in Open, the rides do not run and will simply sit in the station forever and never move.  The ride will being to work again if the track type is switched back to the original type, in this case river rapids... and also if its then moved back to crooked house.  So its simply an issue when loading games up and not when creating new rides, at least untill the games are re-loaded.

This basically breaks a large number of parks that rely on this hack for rides to run.

- [No] Reproducible in RCT2 (vanilla)?
- [YES] Multiplayer?

**Steps to reproduce:**
1. Load Park with a tracked ride set to "crooked house" track type.  I can supply more examples if needed.

**Screenshots / Video:**
-Ride upon loading up the park simply does not dispatch vehicles.
worlds of fun 2017-04-30 15-30-17

-Ride set back to the original track type, double closed and re-opened, works again.
worlds of fun 2017-04-30 15-30-58

**Save game:**
[G Force's Worlds of Fun - G Force.zip](https://github.com/OpenRCT2/OpenRCT2/files/966947/G.Force.s.Worlds.of.Fun.-.G.Force.zip)

### PR DESCRIPTION
**Pull request by rwjuk**
I'll freely admit that I do not like this - I'm not sure we should be allowing potentially buggy behaviour. However, it seems this is a widely-used hack, so until we have a better way to handle arbitrary track/vehicle combinations this may be the best option.

### CODE REVIEW

File: src/openrct2/ride/vehicle.c [hunk 1]
```diff
@@ -1852,7 +1852,14 @@ static int ride_get_train_index_from_vehicle(rct_ride* ride, uint16 spriteIndex)
     while (ride->vehicles[trainIndex] != spriteIndex)
     {
         trainIndex++;
-        if (trainIndex >= ride->num_vehicles || trainIndex >= countof(ride->vehicles))
+        if (trainIndex >= ride->num_vehicles)
```
Comment (ZehMatt) [inline src/openrct2/ride/vehicle.c]: Have you ever checked what the trainIndex value is for those rides? Maybe its a specific value where we could use some exception.

Comment (duncanspumpkin) [inline src/openrct2/ride/vehicle.c]: It's not. They just force a couple trains from a different track onto this one so it will vary with each park

**Comment by IntelOrca** [comment]
This will have to do for now and we will have to protect invalid values elsewhere. When we have a new save format it won't matter to keep compatibility and therefore we can change the ride type back and hide the track another way.
