### PR TITLE
Fix #17229: Rename G1_FLAG_BMP to G1_FLAG_HAS_TRANSPARENCY

### LINKED ISSUE #17229: Rename G1_FLAG_BMP to G1_FLAG_HAS_TRANSPARENCY
`G1_FLAG_BMP` has the wrong name its the inverse of its name it is used to indicate that the sprite has transparency and will require blending with the background to produce the end result. The vast majority of images have this flag set.

### PR DESCRIPTION
**Pull request by jazzysoggy**
Fix for #17229 

Renamed all instances of G1_FLAG_BMP to GA_FLAG_HAS_TRANSPARENCY in order to have more consistency with the actual meaning of the flag on a sprite.

### CODE REVIEW

File: src/openrct2-ui/scripting/CustomImages.cpp [hunk 1]
```diff
@@ -155,7 +155,7 @@ namespace OpenRCT2::Scripting
         obj.Set("width", g1->width);
         obj.Set("height", g1->height);
 
-        obj.Set("isBMP", (g1->flags & G1_FLAG_BMP) != 0);
+        obj.Set("isBMP", (g1->flags & G1_FLAG_HAS_TRANSPARENCY) != 0);
```
Comment (duncanspumpkin) [inline src/openrct2-ui/scripting/CustomImages.cpp:158]: Change to `hasTransparent`

File: src/openrct2/drawing/Drawing.Sprite.cpp [hunk 2]
```diff
@@ -634,7 +634,7 @@ void FASTCALL gfx_draw_sprite_raw_masked_software(
     }
 
     // Only BMP format is supported for masking
```
Comment (duncanspumpkin) [inline src/openrct2/drawing/Drawing.Sprite.cpp:636]: Update comment to state that must have transparency. Tbh there is a bug here as it also must not be rle but we will leave that for another day.

File: src/openrct2/drawing/Drawing.h [hunk 3]
```diff
@@ -146,7 +146,7 @@ assert_struct_size(rct_g1_element_32bit, 0x10);
 
 enum
 {
-    G1_FLAG_BMP = (1 << 0), // Image data is encoded as raw pixels (no transparency)
+    G1_FLAG_HAS_TRANSPARENCY = (1 << 0), // Image data is encoded as raw pixels (no transparency)
```
Comment (duncanspumpkin) [inline src/openrct2/drawing/Drawing.h:149]: Update comment. Image data contains transparent pixels (0xFF) which will not be rendered.

File: src/openrct2/interface/Viewport.cpp [hunk 4]
```diff
@@ -1509,7 +1509,7 @@ static bool is_pixel_present_bmp(
     PROFILED_FUNCTION();
 
     // Probably used to check for corruption
```
Comment (duncanspumpkin) [inline src/openrct2/interface/Viewport.cpp:1511]: This comment is incorrect. I'm unsure why this check exists but it's not because of corruption. Change the comment to something like "odd, investigate why pure bmp not considered"

**Review by duncanspumpkin — APPROVED** [review]
