### PR TITLE
Fix #11804: Some RCT1 fences are imported at the wrong height

### LINKED ISSUE #11804: Fences in RCT1 parks import at incorrect heights for certain slopes.
**OS:** Windows 10
**Version:** 0.2.6-638
**Commit/Build:** g1020969c

When opening a RCT1 park, some fences on sloped surfaces are imported at the incorrect height. See attached screenshots. It seems specific to RCT1 import and does not happen in RCT2 parks and does not happen in vanilla RCT1.

- [ ] Reproducible in RCT2 (vanilla)? 
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Link RCT1 to OpenRCT2.
2. Open a park with slopes and fences, for example Three Monkeys Parks or Thunder Rock.

**Screenshots / Video:**
[Thunder Rock](https://cdn.discordapp.com/attachments/691736850980667514/714066474268098620/unknown.png)
[Three Monkeys Park](https://cdn.discordapp.com/attachments/691736850980667514/714065417114746900/unknown.png) (on the angled slope above the yellow coaster's entrance, and on the far top left at the top of the stairs)
[Three Monkeys Park](https://cdn.discordapp.com/attachments/691736850980667514/714065533779312660/unknown.png) (at the park entrance, the fences are underground)

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/rct1/S4Importer.cpp [hunk 1]
```diff
@@ -2807,13 +2807,25 @@ class S4Importer final : public IParkImporter
                             ConvertWall(&type, &colourA, &colourB);
 
                             type = _wallTypeToEntryMap[type];
-                            auto edgeSlope = LandSlopeToWallSlope[slope][edge & 3] & ~EDGE_SLOPE_ELEVATED;
+                            auto baseZ = originalTileElement.GetBaseZ();
+                            auto clearanceZ = originalTileElement.GetClearanceZ();
+                            auto edgeSlope = LandSlopeToWallSlope[slope][edge & 3];
+                            if (edgeSlope & EDGE_SLOPE_UPWARDS || edgeSlope & EDGE_SLOPE_DOWNWARDS)
```
Comment (tupaschoal) [inline src/openrct2/rct1/S4Importer.cpp:2813]:
```suggestion
                            if (edgeSlope & (EDGE_SLOPE_UPWARDS || EDGE_SLOPE_DOWNWARDS))
```
Just a suggestion

File: src/openrct2/rct1/S4Importer.cpp [hunk 2]
```diff
@@ -2807,13 +2807,25 @@ class S4Importer final : public IParkImporter
...
+                            {
+                                clearanceZ += LAND_HEIGHT_STEP;
+                            }
+                            if (edgeSlope & EDGE_SLOPE_ELEVATED)
+                            {
+                                edgeSlope &= ~EDGE_SLOPE_ELEVATED;
+                                baseZ += LAND_HEIGHT_STEP;
+                                clearanceZ += LAND_HEIGHT_STEP;
```
Comment (tupaschoal) [inline src/openrct2/rct1/S4Importer.cpp:2821]: This is equal in both `if`s, which hints like it could be extracted, unless there are vlaues other than the three `EDGE_SLOPE_*`s you mentioned.

File: src/openrct2/rct1/S4Importer.cpp [hunk 3]
```diff
@@ -2807,13 +2807,25 @@ class S4Importer final : public IParkImporter
...
                             type = _wallTypeToEntryMap[type];
-                            auto edgeSlope = LandSlopeToWallSlope[slope][edge & 3] & ~EDGE_SLOPE_ELEVATED;
+                            auto baseZ = originalTileElement.GetBaseZ();
+                            auto clearanceZ = originalTileElement.GetClearanceZ();
+                            auto edgeSlope = LandSlopeToWallSlope[slope][edge & 3];
+                            if (edgeSlope & EDGE_SLOPE_UPWARDS || edgeSlope & EDGE_SLOPE_DOWNWARDS)
+                            {
+                                clearanceZ += LAND_HEIGHT_STEP;
+                            }
+                            if (edgeSlope & EDGE_SLOPE_ELEVATED)
```
Comment (tupaschoal) [inline src/openrct2/rct1/S4Importer.cpp:2817]: Should this be `else if` ?

File: src/openrct2/rct1/S4Importer.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/rct1/S4Importer.cpp:2813]: That's not going to work like that - you need a bitwise or, not a boolean or.

File: src/openrct2/rct1/S4Importer.cpp (hunk 3 above)
Comment (Gymnasiast) [reply src/openrct2/rct1/S4Importer.cpp:2817]: No. They can be set independently.

File: src/openrct2/rct1/S4Importer.cpp (hunk 2 above)
Comment (Gymnasiast) [reply src/openrct2/rct1/S4Importer.cpp:2821]: I don't know what you're talking about. It can one of the two branches, but also both.

Comment (tupaschoal) [reply src/openrct2/rct1/S4Importer.cpp:2821]: Ok, that also answers the other issue

File: src/openrct2/rct1/S4Importer.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/rct1/S4Importer.cpp:2813]:
```suggestion
                            if (edgeSlope & (EDGE_SLOPE_UPWARDS | EDGE_SLOPE_DOWNWARDS))
```
