### PR TITLE
Fix #21054: `No entrance` style selected by default in track designer

### LINKED ISSUE #21054: Ride entrances and exits are not visible in Track Designer
### Operating System

Void Linux x86-64, kernel 6.5.12_1

### OpenRCT2 build

OpenRCT2, v0.4.6-186 (004592b58 on develop, DEBUG)

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

_No response_

### Describe the issue

When placing ride entrances and exits in Track Designer, they don't show up initially. You can see where the entrance and exit should be due to a small break in the station fence, but the actual buildings are completely invisible. In the colour scheme options tab of the ride window, the station style is also blank. Only after selecting one of the options in that dropdown do the entrance and exits actually become visible.

### Steps to reproduce

1. Launch OpenRCT2
2. Go into Track Designer
3. Select some ride(s)
4. Build a ride and place the entrance and exit.
5. Entrance and exit will not be visible.

### Attachments

Unnamed park 2023-12-04 12-48-54

### PR DESCRIPTION
**Pull request by zzril**
This PR adds a bit of code to `FinishObjectSelection` in `src/openrct2/EditorObjectSelectionSession.cpp` to set the global variable `gLastEntranceStyle` to a sensible value when entering the track designer, similar to how it's done in `ScenarioReset` in `src/openrct2/scenario/Scenario.cpp`. Basically, it is attempted to set it to the "plain" station style, backing up to whatever is first in the list if that one could not be loaded.  
(That backup option may not actually be needed and better be replaced by an assert.)

Before, `gLastEntranceStyle` was set to 12 when entering the track designer (indicating the `no entrance` style), which is (as of now) not even available in the track designer by normal means.  
I am not 100% sure where that value came from. Possibly from loading the park in the title sequence.

Closes #21054 .

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]
Code and changelog look good, needs testing.

File: src/openrct2/EditorObjectSelectionSession.cpp [hunk 1]
```diff
@@ -483,6 +483,15 @@ void FinishObjectSelection()
     {
         SetEveryRideTypeInvented();
         SetEveryRideEntryInvented();
+
+        auto& objManager = OpenRCT2::GetContext()->GetObjectManager();
+        gLastEntranceStyle = objManager.GetLoadedObjectEntryIndex("rct2.station.plain");
+        if (gLastEntranceStyle == OBJECT_ENTRY_INDEX_NULL)
+        {
+            // Fall back to first entrance object
```
Comment (Gymnasiast) [inline src/openrct2/EditorObjectSelectionSession.cpp:491]: Already obvious from the code.

```suggestion
```

**Review by tupaschoal — APPROVED** [review]
Looks sensible, haven't tested.

**Comment by Gymnasiast** [comment]
Tested it now, works correctly.
