### PR TITLE
Fix #17992: Virginia Reel doesn't show sloped tracks

### LINKED ISSUE #17992: Virginia Reel doesn't show sloped tracks (construction)
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-304-g4f0f660 (4f0f660 on develop)

### Describe the issue

The construction menu of the Virginia Reel doesn't show the sloped track pieces.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Open construction on new Virigina Reel
2. No sloped pieces available

### Attachments

Virginia Reel construction sloped pieces

### PR DESCRIPTION
**Pull request by spacek531**
Adds 'dummy' sprite groups to Virginia Reel and River Rapids rides to allow building slopes on these rides

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]

File: src/openrct2/object/RideObject.cpp [hunk 1]
```diff
@@ -229,16 +229,28 @@ void RideObject::Load()
...
-                        * SpriteGroupMultiplier[spriteGroup];
-                    imageIndex += spriteCount;
-                }
+                case VEHICLE_VISUAL_RIVER_RAPIDS:
+                case VEHICLE_VISUAL_VIRGINIA_REEL:
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::SlopeFlat)] = { baseImageId, SpritePrecision::Sprites16 };
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::Slopes12)] = { baseImageId + 8,
+                                                                                     SpritePrecision::Sprites4 };
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::Slopes25)] = { baseImageId + 40,
+                                                                                     SpritePrecision::Sprites4 };
```
Comment (Broxzier) [inline src/openrct2/object/RideObject.cpp:240]: Where do these magic offsets (8 and 40) come from? Did they exist before, but were removed?

Comment (spacek531) [reply src/openrct2/object/RideObject.cpp:240]: They come from the number of sprites involved in these sprite groups: 8 flat sprites, 32 slope transition sprites, 32 slope sprites. These values are unused by the paint code but used by the limit-track-elements code that was added recently.

Comment (Broxzier) [reply src/openrct2/object/RideObject.cpp:240]: Figured something like that was the case here - are there no constants to use here instead of magic numbers?

**Comment by Broxzier** [comment]
Not sure why the title message changed when I cancelled the auto-squash merge.

File: src/openrct2/object/RideObject.cpp (hunk 1 above)
Comment (spacek531) [reply src/openrct2/object/RideObject.cpp:240]: As far as I know, no constants exist for spinning rides - it's all done through magic numbers in VirgniaReel.cpp and RiverRapids.cpp.

Comment (Gymnasiast) [reply src/openrct2/object/RideObject.cpp:240]: Can you introduce `constexpr` for those values? It’s OK if they’re just static to the RideObject.cpp file.

Comment (Broxzier) [reply src/openrct2/object/RideObject.cpp:240]: If there are too many, we can just merge this PR and leave that for another PR. Just figured this is a good opportunity to prevent introducing more magic numbers to the codebase.

**Comment by spacek531** [comment]
I wasn't exactly sure how many constexpr values was expected so I added the one.

File: src/openrct2/object/RideObject.cpp [hunk 2]
```diff
@@ -229,16 +231,32 @@ void RideObject::Load()
...
+                case VEHICLE_VISUAL_RIVER_RAPIDS:
+                case VEHICLE_VISUAL_VIRGINIA_REEL:
+                    // Paint code for these rides do not use sprite groups but #17909 requires them. Dummy sprite groups are
+                    // added.
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::SlopeFlat)] = { baseImageId, SpritePrecision::Sprites16 };
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::Slopes12)] = {
+                        baseImageId + RiverRapidsNumSpinningSprites, SpritePrecision::Sprites4
+                    };
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::Slopes25)] = {
+                        baseImageId + RiverRapidsNumSpinningSprites * (1 + NumOrthogonalDirections), SpritePrecision::Sprites4
```
Comment (Gymnasiast) [inline src/openrct2/object/RideObject.cpp:245]: Are you sure this is correct? I’m especially talking about the `(1 + NumOrthogonalDirections)` bit.

**If** it is correct, I’d like to see it written as this:
```suggestion
                        baseImageId + (RiverRapidsNumSpinningSprites * (NumOrthogonalDirections + 1)), SpritePrecision::Sprites4
```

Comment (spacek531) [reply src/openrct2/object/RideObject.cpp:245]: It's supposed to be 40 so it should be correct.

File: src/openrct2/object/RideObject.cpp [hunk 3]
```diff
@@ -229,16 +231,32 @@ void RideObject::Load()
...
+                case VEHICLE_VISUAL_RIVER_RAPIDS:
+                case VEHICLE_VISUAL_VIRGINIA_REEL:
+                    // Paint code for these rides do not use sprite groups but #17909 requires them. Dummy sprite groups are
+                    // added.
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::SlopeFlat)] = { baseImageId, SpritePrecision::Sprites1 };
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::Slopes12)] = {
+                        baseImageId + RiverRapidsNumSpinningSprites, SpritePrecision::Sprites4
+                    };
+                    carEntry->SpriteGroups[EnumValue(SpriteGroupType::Slopes25)] = {
+                        baseImageId + RiverRapidsNumSpinningSprites * (NumOrthogonalDirections + 1), SpritePrecision::Sprites4
```
Comment (Broxzier) [inline src/openrct2/object/RideObject.cpp:245]: It now kinda looks like there are 5 directions, while 1 of the 5 is for its base offset. Though longer, perhaps this makes it easier to understand:

```suggestion
                        baseImageId + RiverRapidsNumSpinningSprites + RiverRapidsNumSpinningSprites * NumOrthogonalDirections, SpritePrecision::Sprites4
```

Also pinging @Gymnasiast

(I'm heading off to bed now, feel free to merge once this is addressed)

**Review by Broxzier — APPROVED** [review]

**Comment by jensj12** [comment]
I'm afraid this didn't fix the issue, see post in original issue.
