### PR TITLE
Fix #16617: Park format storing/loading temporary paused state

### LINKED ISSUE #16617: Game not simulating after pausing
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (9466e27 on develop) provided by GitHub

### Describe the issue

Im having a strange issue, when I pause the game it just doesn't resume the simulation anymore after pausing. If I restart the game or reboot my computer it still doesn't resume. I can build and do everything but the simulation just don't run. If I load the same park from an earlier time it still loads. It Might be related to the savegame, so I will attaching the same park from 2 different times and latest updates I played. The file Coaster dreams Entrance works fine, while I cant get Coaster Dreams Pause to resume. 

I would attatch a savefile of the park but Github doesn't seem to support any zip file, but I shared them on this dropbox link: https://www.dropbox.com/sh/c69tjzkvqf3ubxy/AAAyNqH2QmbCOOiWpsthXsIza?dl=0

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Load the park named Coaster Dreams Not running and you will see its not simulating

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZehMatt**
Small oversight, only one flag is relevant for the save file. This doesn't require a new version as we are only interested in one bit, so we discard the rest.

### CODE REVIEW

File: src/openrct2/park/ParkFile.cpp [hunk 1]
```diff
@@ -422,7 +422,20 @@ namespace OpenRCT2
...
         {
             auto found = os.ReadWriteChunk(ParkFileChunkType::GENERAL, [this](OrcaStream::ChunkStream& cs) {
-                cs.ReadWrite(gGamePaused);
+                if (cs.GetMode() == OrcaStream::Mode::READING)
+                {
+                    cs.ReadWrite(gGamePaused);
+                    // The flags have been stored in some park files, remove them
+                    // as they are used to temporarily pause the game, only user driven state.
+                    gGamePaused &= ~GAME_PAUSED_MODAL;
+                    gGamePaused &= ~GAME_PAUSED_SAVING_TRACK;
```
Comment (IntelOrca) [inline src/openrct2/park/ParkFile.cpp:431]: Wouldn't you want to do something like this instead?
```cpp
auto isPaused = cs.Read<uint8_t>();
gGamePaused &= ~GAME_PAUSED_NORMAL;
gGamePaused |= (isPaused & GAME_PAUSED_NORMAL);
```

Comment (ZehMatt) [reply src/openrct2/park/ParkFile.cpp:431]: Well I think I understand what you want but then wouldn't it be simpler to simply test the single bit and just assign it like:
```cpp
gGamePaused = (cs.Read<uint8_t>() & GAME_PAUSED_NORMAL);
```
Just masks of the single state and directly assigns it.

Comment (ZehMatt) [reply src/openrct2/park/ParkFile.cpp:431]: I wanted to be explicit about why we deal with the uint8_t the way it does since we use only a single bit of it, the logical way would be to use a bool then but if we would simply ignore the extra bits then its UB (always evalutes to true due to the codegen), but I won't mind simplifying it since we also didn't officially release NSF yet.

Comment (Broxzier) [reply src/openrct2/park/ParkFile.cpp:431]: Since we only care about the user pause, &-ing with `~GAME_PAUSED_NORMAL` makes more sense than removing the other flags. It doesn't really matter how exactly.

```cpp
cs.ReadWrite(gGamePaused);
gGamePaused &= GAME_PAUSED_NORMAL;
```

Comment (IntelOrca) [reply src/openrct2/park/ParkFile.cpp:431]: @ZehMatt I did it that way to preserve the other flags. I don't know if that your way would have consequences or not.

Comment (ZehMatt) [reply src/openrct2/park/ParkFile.cpp:431]: The other flags should not be imported, they have been exported by accident.

Comment (ZehMatt) [reply src/openrct2/park/ParkFile.cpp]: I went with @IntelOrca suggestion and only import/export the state of GAME_PAUSED_NORMAL in gGamePaused

**Review by IntelOrca — APPROVED** [review]
