### PR TITLE
Fix parameter validation for cheat action

### LINKED ISSUE #20500: Cannot turn on Allow Special Color Schemes
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.5 (cf7c486 on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Just updated to the new development build and I no longer can turn on Allow Special Colour Schemes under the Cheats menu. For parks where this is already turned on, if I turn it off, I no longer can turn it back on.

No error is given. It shows a red text box with no text inside.

### Steps to reproduce

Open cheats menu
Try to select Allow Special Colors

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZehMatt**
I made the default throw an assertion now instead of returning a default value, I tested every cheat to ensure the parameter range is correct and that the parameter range actually exists.

Closes #20500

### CODE REVIEW

File: src/openrct2/actions/CheatSetAction.cpp [hunk 1]
```diff
@@ -357,12 +365,40 @@ ParametersRange CheatSetAction::GetParameterRange(CheatType cheatType) const
...
+        case CheatType::RenewRides:
+            [[fallthrough]];
+        case CheatType::TenMinuteInspections:
+            [[fallthrough]];
+        case CheatType::ResetCrashStatus:
+            [[fallthrough]];
+        case CheatType::RemoveLitter:
             return { { 0, 0 }, { 0, 0 } };
+        default:
+            Guard::Assert(false, "Missing validation parameter for cheat: %d", _cheatType.id);
```
Comment (tupaschoal) [inline src/openrct2/actions/CheatSetAction.cpp:398]: Wouldn't it be better to not have a default? Then the compilation would fail with case not handled, assuming all cheats are already handled here.

File: src/openrct2/actions/CheatSetAction.cpp [hunk 2]
```diff
@@ -357,12 +365,40 @@ ParametersRange CheatSetAction::GetParameterRange(CheatType cheatType) const
...
     }
+    // Unreachable
```
Comment (tupaschoal) [inline src/openrct2/actions/CheatSetAction.cpp:400]: I'd add an assert here instead

File: src/openrct2/actions/CheatSetAction.cpp (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/actions/CheatSetAction.cpp:398]: That is unfortunately not happening, I tried that. Probably only gets caught by static analysis

File: src/openrct2/actions/CheatSetAction.cpp (hunk 2 above)
Comment (ZehMatt) [reply src/openrct2/actions/CheatSetAction.cpp:400]: I still would need the return there, otherwise `warning C4715: 'CheatSetAction::GetParameterRange': not all control paths return a value` as Guard::Assert is not marked as noreturn

**Review by Broxzier — APPROVED** [review]
