### PR TITLE
Further pathfinding improvements

### LINKED ISSUE #785: Mechanic Attempts to enter ride via the wrong entrance (Literally)
Mechanics will occasionally attempt to enter a ride to fix it via the wrong entrance. They will walk up the queue and then, because they can't enter via the entrance, will turn around and walk down to the end of the queue, then walk back. Eventually he will correct himself, but generally it will be ages before he does. Picking him up and dropping him at the exit will correct this.

No save attached, will attach when I manage to get one of them to do it again.

### PR DESCRIPTION
**Pull request by zaxcav**
Main changes to the pathfinding are:
1. Tiles are only considered if they have heuristic score == 0 (i.e. the goal is reached) or are a continuing path at the search limit. Otherwise tiles are ignored.  Fixes #785.
2. Wide tiles are only seen as a continuing tile from wide tiles. So wide tiles are used to path find from wide tiles to non-wide tiles; thereafter pathfinding sticks to the non-wide tiles.
3. Only store thin junctions in the vanilla peep->pathfinding_history[].
4. Search path telemetry is collected and returned for the best result, consisting of the thin junctions passed through and the corresponding directions taken, end tile reached and total number of steps taken to get there. This primarily aids with debugging the pathfinding and **could be** (but is **not** currently) used to visualise the pathfinding result if desired (see #4201).
5. Pathfinding debug logging (in debug builds) is improved - in particular guest logging is enabled only for the tracked guest(s); staff logging is enabled only for the name "Mechanic Debug".
6. Introduced some code identifying ride queues as the search is performed - this will be useful in the future for including transport rides in the heuristic search.
7. Update the path wide flag update to affect only a single tile at a time (resolving the first glitch below).

Glitches in the pathfinding still result from the following causes:
- wide flag updates occurring in the same area of the map as the pathfinding will cause glitches - the pathfinding will recover from these glitches (now resolved - see 7 above).
- the heuristic search still only tracks the single best result so far. Alternate, longer routes to nearer tiles will still be returned as a better result than a route that goes through that same tile (with less steps) and then continues on to end overall further from the goal though closer to getting to the goal. The only way to fix this is to implement a truer A* algorithm (over at least the thin junctions, that tracks the shortest number of steps to each thin junction), so that for searches that don't reach the goal only the edges of the search area are considered.
- laying multiple pieces of path at the same location with clearance checks disabled will cause trouble. At the very least, the pathfinding probably won't appear to follow the rendered path.

Tested reasonably extensively with various save games exhibiting pathfinding problems for guests and staff.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Update the network version.

**Comment by zaxcav** [comment]
Does the global state used by map_update_path_wide_flags() (in src/world/map.c) get synchronised between server and clients?
If not, this is a source of desyncs due to how the path wide flag updates and the pathfinding interact... just in case this has not been identified already.

**Comment by janisozaur** [comment]
Do you mean `gWidePathTileLoopX` and `Y`? It looks like it is: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/rct2/S6Exporter.cpp#L426-L427

I think if it wasn't, desyncs would be much more severe, I have a hard time reproducing one when just idling and it would undoubtedly be triggered in this case.

**Comment by duncanspumpkin** [comment]
No he means the update wide paths function. Which as far as I know would be updated but it shouldn't matter that much as the results are always the same

**Comment by zaxcav** [comment]
You're both right.  The update wide paths function uses the globals gWidePathTileLoopX & Y to set which portion of the map is updated in the current cycle.  The critical point is that the wide flags for the group of path tiles updated last in each cycle are incorrect, which is why path finding over these path tiles can glitch.

If this wasn't synchronised, the glitching this causes in the pathfinding was cause desyncs very quickly.

Testing this PR, I was surprised to observe how often the wide paths update causes the path finding to glitch. I suppose in a park with enough peeps this is bound to happen. I just hadn't seen it previously.

Hmm, it would not be too hard to modify the update wide paths function to preserve the wide flags at the end of the update to avoid glitching the path finding.

**Comment by duncanspumpkin** [comment]
@zaxcav i feel that sometimes its best to keep some of these glitchy pathfinds to make it a bit more believable with peeps sometimes behaving erratically.

**Comment by zaxcav** [comment]
@duncanspumpkin I agree that occasional erratic behaviour can make the simulation more believable.
But I believe it should only happen intentionally. There are several such things in the peep implementation already.
When it happens unintentionally it makes the intended behaviour much harder to troubleshoot.

**Comment by zaxcav** [comment]
I've been experimenting with 2 more changes today, but as neither really provides any benefits I won't be committing any changes for these:
- a better heuristic - this will be important when implementing a truer A* algorithm, but my observations are that the existing heuristic performs better overall with the current algorithm than the alternative I'd use with a truer A* (which currently results in more glitches of the 2nd type listed in the description) despite giving what I'd consider bad results in some circumstances.
- favoring directions that don't double-back when both the score and #steps are equal - this might help a little with glitches of the 2nd type listed in the description, but doesn't ensure there won't be a later double-back by the pathfinding and should be unnecessary with a truer A* algorithm.

As of right now I don't have anything else I want to try out for this PR.  So unless reviewers require some changes, I don't plan on doing anything more for this PR.

**Comment by Gymnasiast** [comment]
Merging this is OK AFAIC.

File: src/peep/peep.c [hunk 1]
```diff
@@ -8998,40 +9283,96 @@ int peep_pathfind_choose_direction(sint16 x, sint16 y, uint8 z, rct_peep *peep)
...
+
+			/* Variable bestJunctions is the number of junctions
+			 * pass through in the search path.
+			 * Variables bestJunctionList and bestDirectionList
+			 * contain the junctions and corresponding directions
+			 * of the search path.
+			 * In the future these could be used to visualise the
+			 * pathfinding on the map. */
+			uint8 endJunctions = 0;
+			rct_xyz8 endJunctionList[16];
```
Comment (duncanspumpkin) [inline src/peep/peep.c]: ` = { 0 };` is a much simpler way of zeroing this.

**Comment by duncanspumpkin** [comment]
How is this performance wise on busy maps?

**Comment by zaxcav** [comment]
Updated as suggested.

Performance impact on my old laptop for a map with 2000+ peeps is about 0-1fps slower.  The performance impact from the extra rendering when a peep status window is open is worse on this computer!
