### PR TITLE
Fix #19517: Crash when peeps try to exit or enter a hacked ride

### LINKED ISSUE #19517: [014ccc] openrct2.exe: Guest::UpdateRideLeaveEntranceWaypoints, Guest::UpdateRideAdvanceThroughEntrance, PeepUpdateAll, OpenR...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/014cccc6111c13d951a5362f6f24d829aa58060aea7aeba24d4e8fac5f294234">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>a7000000-ee72-ac09-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\raymo\OneDrive\Documenten\OpenRCT2\crash\cd939457-c59c-45f2-8294-07493fb13c34.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>24</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.3-320-g4f361bf (4f361bf on develop) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li>4f361bf &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
Guest::UpdateRideLeaveEntranceWaypoints
Guest::UpdateRideAdvanceThroughEntrance
PeepUpdateAll
OpenRCT2::GameState::UpdateLogic
OpenRCT2::GameState::Tick
OpenRCT2::Context::Tick
OpenRCT2::Context::RunFixedFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by ZehMatt**
openrct2_2023-02-28_18-26-3794f2b4c6989864bd7

Peeps trying to get on or off this ride triggers the assert, such a ride doesn't really contain waypoints where the peeps should move to when entering it which are just offsets added to the station, this PR simply checks if waypoints exist and only then adds the specified offsets, there should be no side effects as the typical ride either operates in a mode where they don't need waypoints or the ride typically specifies them, this is a rather special case but its still functional with the changes, peeps get on the ride take a seat and then walk off to the exit station so I'm quite confident this won't suddenly break other things, I mean it currently crashes so thats not really better.

Closes #19517

### CODE REVIEW

File: src/openrct2/entity/Guest.cpp [hunk 1]
```diff
@@ -3627,9 +3627,12 @@ void Guest::UpdateRideLeaveEntranceWaypoints(const Ride& ride)
     CoordsXY waypoint = rtd.GetGuestWaypointLocation(*vehicle, ride, CurrentRideStation);
 
     const auto waypointIndex = Var37 / 4;
```
Comment (duncanspumpkin) [inline src/openrct2/entity/Guest.cpp:3629]: pretty sure the upper part is a rotation.

Comment (ZehMatt) [reply src/openrct2/entity/Guest.cpp:3629]: Yeah theres another variable masking it with `& 3`

**Review by duncanspumpkin — APPROVED** [review]
