### PR TITLE
Fix #18140 & #18143: Invalid read in Staff

### LINKED ISSUE #18140: [e3ad43] openrct2.exe: get_ride, Staff::IsMechanicHeadingToFixRideBlockingPath
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/e3ad437cb8cc46f8b6fcdbb6f181f850496c65852c578fe5b833059641164c57">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>09000000-d596-ea08-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Nico\Documents\OpenRCT2\crash\fce89e39-2c33-4788-8ccc-0c496c5af5d1.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>12</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.1-367-g6f3790c (6f3790c on develop) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>6f3790c</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
get_ride
Staff::IsMechanicHeadingToFixRideBlockingPath</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by rik-smeets**
The tile element should be determined the same way as is done when checking if the footpath is blocked by a vehicle.

Also added some extra safety checks and made the code a bit more efficient / reusable. For example: when the staff member is not a mechanic, the tile element doesn't have to determined.

Resolves both #18140 and #18143.

### CODE REVIEW

File: src/openrct2/world/Map.h [hunk 1]
```diff
@@ -198,6 +197,22 @@ void map_invalidate_selection_rect();
...
+    do
+    {
+        if (tileElement->GetType() != T::ElementType)
+            continue;
+        if (tileElement->base_height >= loc.baseZ && tileElement->base_height <= loc.clearanceZ)
+            return tileElement->as<T>();
+    } while (!(tileElement++)->IsLastForTile() && tileElement->base_height <= loc.clearanceZ);
+
+    return nullptr;
+}
```
Comment (IntelOrca) [inline src/openrct2/world/Map.h:214]: Try to keep as much code as you can in the .cpp file. For this you can have a non-template version in the .cpp file, then just have the template version call the non-template version and do `->as<T>` at the end.

Comment (rik-smeets) [reply src/openrct2/world/Map.h:205]: Thanks, that's much better indeed.

File: src/openrct2/world/Map.h [hunk 2]
```diff
@@ -198,10 +198,16 @@ void map_invalidate_selection_rect();
 bool MapCheckCapacityAndReorganise(const CoordsXY& loc, size_t numElements = 1);
 TileElement* tile_element_insert(const CoordsXYZ& loc, int32_t occupiedQuadrants, TileElementType type);
 
+template<typename T = TileElement> T* MapGetFirstTileElementWithBaseHeightBetween(const TileCoordsXYRangedZ& loc)
```
Comment (duncanspumpkin) [inline src/openrct2/world/Map.h:201]: This isn't how i would expect this function to work. If you are specifying a type then you would expect it to find the first element of that type in the range.

File: src/openrct2/world/Map.h [hunk 3]
```diff
@@ -198,10 +198,16 @@ void map_invalidate_selection_rect();
...
+{
+    auto* element = MapGetFirstTileElementWithBaseHeightBetween(loc, T::ElementType);
+    return element != nullptr ? element->template as<T>() : nullptr;
+}
+
 template<typename T> T* TileElementInsert(const CoordsXYZ& loc, int32_t occupiedQuadrants)
 {
     auto* element = tile_element_insert(loc, occupiedQuadrants, T::ElementType);
-    return (element != nullptr) ? element->template as<T>() : nullptr;
+    return element != nullptr ? element->template as<T>() : nullptr;
```
Comment (Gymnasiast) [inline src/openrct2/world/Map.h:210]: Stray change, please revert.

File: src/openrct2/world/Map.cpp [hunk 4]
```diff
@@ -371,6 +371,22 @@ TileElement* map_get_nth_element_at(const CoordsXY& coords, int32_t n)
...
+    TileElement* tileElement = map_get_first_element_at(loc.ToCoordsXY());
+    if (tileElement == nullptr)
+        return nullptr;
+    do
+    {
+        if (tileElement->GetType() != type)
+            continue;
+        if (tileElement->base_height >= loc.baseZ && tileElement->base_height <= loc.clearanceZ)
+            return tileElement;
+    } while (!(tileElement++)->IsLastForTile() && tileElement->base_height <= loc.clearanceZ);
```
Comment (Gymnasiast) [inline src/openrct2/world/Map.cpp:385]:
```suggestion
    } while (!(tileElement++)->IsLastForTile());
```

**Never** assume tile elements are in order of height, because they aren’t.

**Review by Gymnasiast — APPROVED** [review]
LGTM, have you tested if everything still works?

**Comment by rik-smeets** [comment]
Yes, I have a couple of parks to test all kinds of stuff regarding railway crossings by now. Everything still works as intended!
