### PR TITLE
Fix #13894: Block brakes do not animate

### LINKED ISSUE #13894: Block brakes do not animate
I was pawing through a g1 dump and I noticed the wooden coaster has sprites for closed and open block brakes. Considering that in the code only one ride has calls to `BlockBrakeClosed()` (the junior coaster) and I recall RCT2 having animated block brakes, I think this is a regression.

for example:

Wooden coaster even direction block brake open: 23757
Wooden coaster odd direction block brake open: 23758
Wooden coaster even direction block brake closed: 23759
Wooden coaster odd direction block brake closed: 23780

Reimplementing these sprites should be simple since they all follow the same pattern as outlined above.

4D coaster station block brakes start at 15812
4D coaster block brakes start at 16220
4D coaster inverted block brakes start at 26551
Corkscrew block brakes start at 16232
LIM Launched block brakes start at 15020
Bobsled block brakes start at 14586
Steel wild mouse block brakes start at 16904
B&M block brakes start at 17150
Inverted wild mouse block brakes start at 17030 - maybe
Giga coaster block brakes start at 18076
Giga coaster front side block brakes start at 18080
Mini coaster block brakes start at 18742
Mine train coaster block brakes start at 20060
Wooden coaster block brakes start at 23757
Standup coaster block brakes start at 25571
Junior Coaster block brakes start at 28193

Suspended swinging coaster block brakes absent
Vekoma SLC block brakes absent
B&M inverted block brakes absent
Single rail suspended coaster block brakes absent
Wooden wild mouse block brakes absent
Steeplechase block brakes absent

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/coaster/LimLaunchedRollerCoaster.cpp [hunk 1]
```diff
@@ -19,23 +19,36 @@
 #include "../TrackData.h"
 #include "../TrackPaint.h"
 
+static constexpr const uint32_t LIM_LAUNCHED_RC_BLOCK_BRAKE_SW_NE_OPEN = 15020;
+static constexpr const uint32_t LIM_LAUNCHED_RC_BLOCK_BRAKE_NW_SE_OPEN = 15021;
+static constexpr const uint32_t LIM_LAUNCHED_RC_BLOCK_BRAKE_SW_NE_CLOSED = 15022;
+static constexpr const uint32_t LIM_LAUNCHED_RC_BLOCK_BRAKE_NW_SE_CLOSED = 15023;
+
+static constexpr const uint32_t _CorkscrewRCBlockBrakeImages[NumOrthogonalDirections][2] = {
```
Comment (duncanspumpkin) [inline src/openrct2/ride/coaster/LimLaunchedRollerCoaster.cpp:27]: LimLauncherBlockBrakeImages

File: src/openrct2/ride/coaster/MultiDimensionRollerCoaster.cpp [hunk 2]
```diff
@@ -108,18 +123,19 @@ static void multi_dimension_rc_track_station(
...
+        { 15811, MULTI_DIM_STATION_BLOCK_BRAKE_NW_SE_OPEN, MULTI_DIM_STATION_BLOCK_BRAKE_NW_SE_CLOSED },
     };
 
     if (tileElement->AsTrack()->GetTrackType() == TrackElemType::EndStation)
     {
+        bool isClosed = tileElement->AsTrack()->BlockBrakeClosed();
         PaintAddImageAsParentRotated(
-            session, direction, imageIds[direction][1] | session->TrackColours[SCHEME_TRACK], 0, 0, 32, 26, 1, height, 0, 3,
-            height + 3);
+            session, direction, imageIds[direction][1 + isClosed] | session->TrackColours[SCHEME_TRACK], 0, 0, 32, 26, 1,
```
Comment (duncanspumpkin) [inline src/openrct2/ride/coaster/MultiDimensionRollerCoaster.cpp:137]: I don't like using bool to mean 1 for maths personally but if you are okay.

**Review by duncanspumpkin — APPROVED** [review]
See minor comment on incorrect name

**Comment by duncanspumpkin** [comment]
Checked this against the original and yeah looks like this was a mistake in testpaint as they were all there in the original.
