### PR TITLE
Fix #17816: Game shows the ability to pause game when Steam Overlay is enabled even though OpenGL renderer has no such ability

### LINKED ISSUE #17816: Steam Overlay doesn't pause game with box ticked
### Operating System

Windows 10, 64 Bit 

### OpenRCT2 build

OpenRCT2, v0.4.1-182-ga07daae (a07daae on develop) provided by GitHub

### Describe the issue

When launching OpenRCT2 through steam (non steam game, or in my case I replaced RCT2.EXE with Ted's launcher) when opening steam overlay with the `Pause game when Steam overlay is open` doesn't actually pause the game. 
image
It'd be nice to have this feature working (again, idk if it ever did) or if not this button should be removed entirely.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Open game through Steam
2. Tick box `Pause game when Staem overlay is open` in the options menu.
3. Open a game that's running the simulation
4. Open steam overlay (by default Shift+Tab)
5. The game doesn't pause

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by jazzysoggy**
#17816

Issue: When using the OpenGL hardware rendering option, the check to enable pause when Steam Overlay appears is enabled. This option, however, does nothing when using the OpenGL hardware rendering option.

Fix: Add a check so that the option is grayed out when using OpenGL hardware rendering.

### CODE REVIEW

File: src/openrct2-ui/windows/Options.cpp [hunk 1]
```diff
@@ -878,7 +878,7 @@ class OptionsWindow final : public Window
         }
 
         // Disable Steam Overlay checkbox when using software rendering.
```
Comment (jensj12) [inline src/openrct2-ui/windows/Options.cpp:880]: Please also update the comment to reflect your changes.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Please fix the commit message and add a changelog entry.

File: distribution/changelog.txt [hunk 2]
```diff
@@ -43,6 +43,7 @@
 - Fix: [#17784] Colour preset RNG is biased (original bug).
 - Fix: [#17834] Finance window becomes blank after 4096 years.
 - Fix: [#17905] The chain button in the map window is enabled for rectangular maps when (re)opened.
+- Fix: [#17816] Game shows the ability to pause game when Steam Overlay is active with OpenGL renderer
```
Comment (Gymnasiast) [inline distribution/changelog.txt:46]:
```suggestion
- Fix: [#17816] Option to pause game when Steam Overlay is active is not greyed out when using the OpenGL renderer.
```
