### PR TITLE
Fix #5896 Fences not always removed when building a tracked ride through

### LINKED ISSUE #5896: Fences are not always removed when building a tracked ride through them
**OS:** Windows 10
**Version:** 0.1.1-develop
**Commit/Build:** 553e161

When building a tracked ride though a fence, the fence is removed when placed along one axis, but _not_ when placed along the other axis.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Place fences in a square
2.  Build a tracked ride through two non-opposite sides.
3. On one side the fence is removed, on the other it is not.

**Screenshots / Video:**

rct2fence

### PR DESCRIPTION
**Pull request by aw20368**
Fence removal did not account for track direction. Added the rotation for the track/fence intersection test.

Note that this bug also caused extraneous fences to be removed when building curved track (the picture on the left is the behavior in v0.2.2, my branch on the right).

Fence

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Is there not a rol4 function? If there isn't can you just create one since you are using it a few times.

**Comment by AaronVanGeffen** [comment]
There is not, yet. Since it's only rotating a nybble, you probably can't fit it in the templated rotate functions #8633 introduced, though…?

**Comment by aw20368** [comment]
I can use rol8 if I copy over the lower 4 bits to the upper 4 (and then mask with 0x0F), but that might be slightly hacky.

Should I...
1) Do the above
2) Add rol4 and ror4 to Numerics.hpp (or somewhere else)
3) Leave as-is (plus changelog/network)?

**Comment by aw20368** [comment]
Also looks like this will resolve #4568.

**Comment by duncanspumpkin** [comment]
Create a rol4 in numerics.

File: src/openrct2/core/Numerics.hpp [hunk 1]
```diff
@@ -30,6 +30,18 @@ namespace Numerics
         return (((_UIntType)(x) << shift) | ((_UIntType)(x) >> (limits::digits - shift)));
     }
 
+    /**
+     * Bitwise left rotate of lowest 4 bits
+     * @param x unsigned 8-bit integer value
+     * @param shift positions to shift
+     * @return rotated value
+     */
+    static constexpr uint8_t rol4(uint8_t x, size_t shift)
```
Comment (AaronVanGeffen) [inline src/openrct2/core/Numerics.hpp]: Ugly, but to silence a CI warning:
```suggestion
    [[maybe_unused]] static constexpr uint8_t rol4(uint8_t x, size_t shift)
```
