### PR TITLE
Fix #17834: Finance window becomes blank after 4096 years

### LINKED ISSUE #17834: Finance window becomes blank after 4096 years
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4 and 9e1b24d) provided by GitHub

### Describe the issue

When the in-game year exceeds 4096, the finance window appends blanks at the end instead of showing the info for the months after October, year 4096. This appears to be caused by some of the finance window code treating `date.monthsElapsed` as a signed integer instead of an unsigned integer.

Actual result

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Play any park or scenario until the in-game year 4096, or set that year via the cheats window.
2. Play another year to reach year 4097.
3. Check the finance window. Info for months after October, year 4096 does not show up; instead, the spaces remain blank like in the above image.

### Attachments

Originally reported by @lordmarcel in https://discord.com/channels/601789725090643968/601794846658789377/1008763582185472031
(Discord server "Marcel's Hangout," channel "video-discussion," message dated August 15, 2022)

### PR DESCRIPTION
**Pull request by skdltmxn**
This PR fixes #17834

### CODE REVIEW

File: src/openrct2-ui/windows/Finances.cpp [hunk 1]
```diff
@@ -379,19 +379,19 @@ class FinancesWindow final : public Window
...
-            int16_t monthyear = currentMonthYear - i;
+            int32_t monthyear = currentMonthYear - i;
             if (monthyear < 0)
                 continue;
 
             // Month heading
             auto ft = Formatter();
             ft.Add<StringId>(STR_FINANCES_SUMMARY_MONTH_HEADING);
-            ft.Add<uint16_t>(monthyear);
+            ft.Add<int32_t>(monthyear);
```
Comment (IntelOrca) [inline src/openrct2-ui/windows/Finances.cpp:394]: I am not sure you can do this without editing the string first to take a 32-bit value.

Comment (skdltmxn) [reply src/openrct2-ui/windows/Finances.cpp:394]: `STR_FINANCES_SUMMARY_MONTH_HEADING` formats `{MONTH}` and it seems like formatter takes int32_t for the argument?

```c++
case FormatToken::Month:
    if constexpr (std::is_integral<T>())
    {
        auto szMonth = language_get_string(DateGameMonthNames[date_get_month(arg)]);
        ...
    }
```

```c++
int32_t date_get_month(int32_t months)
{
    return months % MONTH_COUNT;
}
```

Comment (IntelOrca) [reply src/openrct2-ui/windows/Finances.cpp:394]: I think, unless you call the template version of FormatString, this will be uint16 still. See:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/localisation/Formatting.cpp#L778

I could be wrong though, have you tried running this code with larger than uint16 month numbers?

Comment (skdltmxn) [reply src/openrct2-ui/windows/Finances.cpp:394]: Yes I tried with month bigger than 0x10000 and it works find.
Maybe `BuildAnyArgListFromLegacyArgBuffer` is not called in this case?

Comment (skdltmxn) [reply src/openrct2-ui/windows/Finances.cpp:394]: Oh no, I was wrong.
`BuildAnyArgListFromLegacyArgBuffer` is called and month value is read as uint16_t.
However final month value is `months % MONTH_COUNT`, so it was the same by accident.

I will modify `BuildAnyArgListFromLegacyArgBuffer` as well.

Comment (skdltmxn) [reply src/openrct2-ui/windows/Finances.cpp]: Actually, it looks like keeping {MONTH} as uint16 is simpler than making it 32bit wide...!

File: src/openrct2-ui/windows/Finances.cpp [hunk 2]
```diff
@@ -379,19 +379,19 @@ class FinancesWindow final : public Window
         }
 
         // Expenditure / Income values for each month
-        int16_t currentMonthYear = static_cast<int16_t>(gDateMonthsElapsed);
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Finances.cpp:382]: Why not just make it a uint16_t all along, rather than casting it at the end?

Comment (skdltmxn) [reply src/openrct2-ui/windows/Finances.cpp:382]: Good point. uint16_t makes whole code a lot simpler

File: src/openrct2-ui/windows/Finances.cpp [hunk 3]
```diff
@@ -379,14 +379,12 @@ class FinancesWindow final : public Window
...
+        uint16_t currentMonthYear = static_cast<uint16_t>(gDateMonthsElapsed);
         for (int32_t i = SummaryMaxAvailableMonth(); i >= 0; i--)
         {
             screenCoords.y = 0;
 
-            int16_t monthyear = currentMonthYear - i;
-            if (monthyear < 0)
-                continue;
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Finances.cpp:389]: You cannot just remove this check, it is there for a reason.

```
if (i > currentMonthYear)
    continue;
```
should do the trick.

Comment (skdltmxn) [reply src/openrct2-ui/windows/Finances.cpp:389]: Is it even possible to satisfy that condition?
I thought `i` cannot exceed `gDateMonthsElapsed`.

Comment (Gymnasiast) [reply src/openrct2-ui/windows/Finances.cpp:389]: I took a look, and you’re right. The if was put in in 2014 to guard against `i > gDateMonthsElapsed`. At the time, `i` was always initialised to 4, rather than `SummaryMaxAvailableMonth()`.

**Review by Gymnasiast — APPROVED** [review]
