### PR TITLE
Fix #21317: Track designer allows proceeding without an object selected

### LINKED ISSUE #21317: Track Designer allows proceeding to track designer step without any vehicle/attraction selected
### Operating System

Linux

### OpenRCT2 build

8abda17cb3bb204a2394eb7311c221f0e69a2c46

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

In the track designer, before allowing the player to proceed from the initial "object selection" step to the actual "track designer" step, the game usually checks if the player has selected at least one vehicle / attraction, and forbids proceeding to the next step otherwise.  
This check is not executed when proceeding to the track designer step by simply closing the object selection window.  
This is somewhat inconsistent.

### Steps to reproduce

1. From main menu, start track designer
2. Proceed to next step without selecting any objects
3. Observe error message
4. Close object selection window
5. Observe that you have de facto proceeded to track designer step

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
For https://github.com/OpenRCT2/OpenRCT2/issues/21317

### CODE REVIEW

**Comment by Harry-Hopkinson** [comment]
oie_XoTpAqZSbCW6

File: src/openrct2-ui/windows/EditorBottomToolbar.cpp [hunk 1]
```diff
@@ -182,27 +182,6 @@ class EditorBottomToolbarWindow final : public Window
         GfxInvalidateScreen();
     }
 
-    bool CheckObjectSelection() const
```
Comment (Harry-Hopkinson) [inline src/openrct2-ui/windows/EditorBottomToolbar.cpp:185]: I moved this to another header file so I could import it in the EditorObjectSelection file.

**Comment by Harry-Hopkinson** [comment]
This also fixes the bug in the Track Designs Manager

File: src/openrct2-ui/windows/EditorObjectSelection.cpp [hunk 2]
```diff
@@ -353,7 +353,9 @@ class EditorObjectSelectionWindow final : public Window
         switch (widgetIndex)
         {
             case WIDX_CLOSE:
-                WindowClose(*this);
+                if (!CheckObjectSelection() && !(gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER))
```
Comment (zzril) [inline src/openrct2-ui/windows/EditorObjectSelection.cpp:356]: Can swap these conditions, so CheckObjectSelection does not need to be executed in the track designs manager case:  
```suggestion
                if (!(gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER) && !CheckObjectSelection())
```

Comment (Harry-Hopkinson) [reply src/openrct2-ui/windows/EditorObjectSelection.cpp:356]: Good catch.

**Review by tupaschoal — COMMENTED** [review]
I haven't tested it, but it looks ok on how we block moving forward from the arrow.

I have rewritten the PR title and this also needs a changelog entry

File: distribution/changelog.txt [hunk 3]
```diff
@@ -4,6 +4,7 @@
 - Fix: [#20907] RCT1/AA scenarios use the 4-across train for the Inverted Roller Coaster.
 - Fix: [#21332] Mini Helicopters and Monorail Cycles ride types are swapped in research within RCT1 scenarios.
 - Fix: [#21347] Too many options are hidden if the platform has no file picker.
+- Fix: [#21317] Track designer allow proceeding without an object selected.
```
Comment (tupaschoal) [inline distribution/changelog.txt:15]:
```suggestion
- Fix: [#21317] Track designer allows proceeding without an object selected.
```

Missed an 's' on my edit of the title. Also note that the entry needs to be sorted by issue number (aside from fix type), so you need to move this one a few lines above

**Review by tupaschoal — APPROVED** [review]
Tested it and it looks and works ok

File: src/openrct2-ui/windows/EditorObjectSelection.cpp [hunk 4]
```diff
@@ -354,7 +354,9 @@ class EditorObjectSelectionWindow final : public Window
         switch (widgetIndex)
         {
             case WIDX_CLOSE:
-                WindowClose(*this);
+                if (!(gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER) && !CheckObjectSelection())
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/EditorObjectSelection.cpp:357]: This bit concerns me. There are four(!) situations where this code is run:
1. In the Scenario Editor
2. In the Track Designer
3. In the Track Designs Manager
4. In a regular game

What I’m afraid of is that this breaks some of those. The original issue also mentions closing via hotkey, which would also need to be tested.

Alternatively, the following code might have fewer side effects (needs testing though):
```

```
```suggestion
                if ((gScreenFlags & SCREEN_FLAGS_TRACK_DESIGNER) && !CheckObjectSelection())
                {
                    return;
                }
                WindowClose(*this);
```

Comment (Harry-Hopkinson) [reply src/openrct2-ui/windows/EditorObjectSelection.cpp]: When trying this code, the game crashes when you close the track design menu with an object selected.

Comment (Harry-Hopkinson) [reply src/openrct2-ui/windows/EditorObjectSelection.cpp]: Should I revert the changes?

Comment (zzril) [reply src/openrct2-ui/windows/EditorObjectSelection.cpp]: > here are four(!) situations where this code is run: 
>     1. In the Scenario Editor
>     2. In the Track Designer
>     3. In the Track Designs Manager
>     4. In a regular game
> What I’m afraid of is that this breaks some of those.

For the scenario editor, it should also be run.  
(Otherwise it lets you for example deselect all park entrances and then allow you to create a park without a working entrance.)
