### PR TITLE
Fix #5596: Incorrect colours in the Map window

### LINKED ISSUE #5596: The map menu displays the park with weird colours
Windows 8
v0.0.8
3988b77

The in-game map window shows the park with different colours than it used to, or what is used in ClosedRCT. Most notable, rides are no longer displayed in red but in blue, making the map very hard to read. Red stands out. Blue looks like water. The secondary view, the rides-focused one, also looks funny because the tiles without a ride or path are displayed in black, and no longer in gray.

I assume this is a bug, but it's actually a nice idea to play with these colours. It should be totally up to the user though. Can this be included in the interface theme options? I would surely have a lot of fun with that. But first I would make the rides red again. ;)

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/windows/map.c [hunk 1]
```diff
@@ -34,7 +34,7 @@
 
 #define MAP_COLOUR_2(colourA, colourB) ((colourA << 8) | colourB)
 #define MAP_COLOUR(colour) MAP_COLOUR_2(colour, colour)
-#define FALLBACK_COLOUR(colour) ((colour << 24) || colour << 16)
+#define FALLBACK_COLOUR(colour) ((colour << 24) | colour << 16)
```
Comment (janisozaur) [inline src/openrct2/windows/map.c]: Nice catch
