### PR TITLE
Fix #14201: Assert in research_finish_item for invalid ride type

### LINKED ISSUE #14201: Assert in research_finish_item for invalid ride type
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/4ac3462a55da31cdbd94d205ec628a872480f949def4fdf7efde1fbf21757b63">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Cooper\Documents\OpenRCT2\13d84d29-1476-4618-b4fe-55264593295c.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Cooper\Documents\OpenRCT2\13d84d29-1476-4618-b4fe-55264593295c.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>Location: ride_type_set_invented:542</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Cooper\Documents\OpenRCT2\13d84d29-1476-4618-b4fe-55264593295c.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Cooper\Documents\OpenRCT2\screenshot\Unnamed park 2021-02-28 16-15-52.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>cea5fab</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-write</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
Guard::Assert_VA
openrct2_assert_fwd
research_finish_item
research_reset_current_item
scenario_begin
OpenRCT2::Context::LoadParkFromStream
OpenRCT2::Context::LoadParkFromFile
context_load_park_from_file
window_scenarioselect_scrollmousedown
input_scroll_begin
input_widget_left
game_handle_input_mouse
game_handle_input
context_handle_input
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by IntelOrca**
Prevent crash and assert. Instead just log a warning and continue as normal.
All functions that take ride type should now handle invalid ride types.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I'd like to autofix these as well. `research_fix` could do `RideTypeIsValid` on the ride type, and overwrite it with `ride_entry_get_first_non_null_ride_type()` if it is invalid.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Needs https://github.com/OpenRCT2/OpenRCT2/pull/14260#issuecomment-792274921 , but otherwise looks good.

File: src/openrct2/management/Research.cpp [hunk 1]
```diff
@@ -200,11 +200,14 @@ void research_finish_item(ResearchItem* researchItem)
 
         if (rideEntry != nullptr && base_ride_type != RIDE_TYPE_NULL)
         {
-            rct_string_id availabilityString;
+            if (RideTypeIsValid(base_ride_type))
```
Comment (Gymnasiast) [inline src/openrct2/management/Research.cpp:203]:
```suggestion
            if (!RideTypeIsValid(base_ride_type))
```

**Review by Gymnasiast — APPROVED** [review]
