### PR TITLE
Fix #9502: Unhandled exception when object download fails

### LINKED ISSUE #9502: Unhandled exception when object download fails
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/4c3bacebac1b03895d62a6efdc22efa936dbc9c8b14d944cfb058f869e6c01e0?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Jun 29 2019 08:53:43)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_screenshot.png:</strong> C:\\Users\\Chris\\Documents\\OpenRCT2\\screenshot\\Yokum Creek Park 2019-06-29 01-53-45.png: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Chris\\Documents\\OpenRCT2\\17f45343-a4fc-4ab4-a0a1-ed4d917b6686.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Chris\\Documents\\OpenRCT2\\17f45343-a4fc-4ab4-a0a1-ed4d917b6686.sv6.gz: <em>1</em><br><strong>commit:</strong> e149722: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>unhandled-exception</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>std::_Func_impl_no_alloc<<lambda_835cdd6479c5b12fd4c3fb048eae00ed>,void,OpenRCT2::Network::Http::Response &>::_Do_call -> std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_b4dc34ea0f811813b0e5ae2ef13b6161> >,std::default_delete<std::tuple<<lambda_b4dc34ea0f811813b0e5ae2ef13b6161> > > > >::_Go -> std::_Pad::_Call_func -> invoke_thread_procedure( -> thread_start<unsigned int (*)(void *)></code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

File: src/openrct2-ui/windows/ObjectLoadError.cpp [hunk 1]
```diff
@@ -119,7 +119,7 @@ class ObjectDownloader
                 }
                 else
                 {
-                    throw std::runtime_error("Non 200 status");
+                    std::printf("  Failed to download %s\n", name.c_str());
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/ObjectLoadError.cpp]: Is there a specific reason for the two spaces at the start of the string?

Comment (IntelOrca) [reply src/openrct2-ui/windows/ObjectLoadError.cpp]: This is a copy of the one below which I indented just so that it stood out from the "downloading object..." status messages.
