### PR TITLE
Fix #15161 #15159 one-off error when getting stationIndex

### LINKED ISSUE #15161: Ride window viewport for "Station 1" is broken
**OS:** Windows 10
**Version:** 
**Commit/Build:** Broken by commit ab96ca85165ac1710c2cf5dac85ee5be4e9a78bb (still broken at most recent commit 864de57877773bda0d1b96714faae082df635849)
**Related issue:** #14918
**Related pull:** #15133 

When you click on a Rollercoaster and open the Ride window, changing to "Station 1" will result in the window viewport showing the top-left corner of the map.

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open a Rollercoaster ride window
2. Using the drop-down selection, choose "Station 1"
3. The window viewport will show the top-left hand corner of the map

**Screenshots / Video:**
Bumbly Beach 2021-08-02 01-50-30

### PR DESCRIPTION
**Pull request by SaadRehmanCS**

### CODE REVIEW

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -1599,22 +1626,18 @@ static void window_ride_init_viewport(rct_window* w)
...
-                break;
-            }
+            StationIndex stationIndex = GetStationIndexFromViewSelection(*w).value();
+            auto location = ride->stations[stationIndex].GetStart();
+            focus.coordinate.x = location.x;
+            focus.coordinate.y = location.y;
+            focus.coordinate.z = location.z;
+            focus.sprite.type |= VIEWPORT_FOCUS_TYPE_COORDINATE;
+        }
+        catch (const std::bad_optional_access& e)
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Ride.cpp:1638]: Although this is one way of doing this exceptions are expensive. Instead you can just check the validity with something like:
```cpp

            auto stationIndex = GetStationIndexFromViewSelection(*w);
            if (stationIndex){
            auto location = ride->stations[*stationIndex].GetStart();
}
            ```

File: src/openrct2-ui/windows/Ride.cpp [hunk 2]
```diff
@@ -1546,6 +1547,32 @@ static void window_ride_anchor_border_widgets(rct_window* w)
 
 #pragma region Main
 
+std::optional<StationIndex> GetStationIndexFromViewSelection(const rct_window& w)
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Ride.cpp:1550]: declare this static as it is only used in this file.

File: src/openrct2-ui/windows/Ride.cpp [hunk 3]
```diff
@@ -2528,35 +2547,42 @@ static rct_string_id window_ride_get_status_station(rct_window* w, Formatter& ft
         return STR_NONE;
 
     int32_t count = w->ride.view - ride->num_vehicles - 1;
-    StationIndex stationIndex = STATION_INDEX_NULL;
     rct_string_id stringId = STR_EMPTY;
+    int32_t stationIndex = 0;
+    auto lastStation = ride->stations[0];
 
-    do
+    for (const auto& station : ride->stations)
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Ride.cpp:2554]: The whole reason for making a helper function is to use it. Replace this bit with the new helper function.

**Review by duncanspumpkin — APPROVED** [review]
