### PR TITLE
 Fix #14409: NPE when demolishing banner 

### LINKED ISSUE #14409: [5b2424] RCT2.exe: BannerWindow::OnMouseUp, InputStateWidgetPressed, GameHandleInputMouse, GameHandleInput, context_handle_in...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/5b242482d9b08a13cfaf3b39ae7aa27830248530af43454be78ce9885aeb8442">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>RCT2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\parkl\OneDrive\문서\OpenRCT2\1e378a71-e8e0-4754-8831-847dedd4cce6.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\parkl\OneDrive\문서\OpenRCT2\1e378a71-e8e0-4754-8831-847dedd4cce6.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\parkl\OneDrive\문서\OpenRCT2\screenshot\이상한 성 2021-03-31 03-43-51.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>6bff0fb</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
BannerWindow::OnMouseUp
InputStateWidgetPressed
GameHandleInputMouse
GameHandleInput
context_handle_input
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2-ui/windows/Banner.cpp [hunk 1]
```diff
@@ -76,7 +76,7 @@ class BannerWindow final : public Window
 private:
     Banner* _banner;
     CoordsXYZ _bannerViewPos;
-    TileElement* _tileElement = nullptr;
+    BannerElement* _tileElement = nullptr;
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Banner.cpp:79]: Can you change the variable name as well
