### PR TITLE
Fix #8064 Ride construction errors shown as (undefined string)

### LINKED ISSUE #8064: Construction error about local authority not allowing construction that high is shown as (undefined string) every other height
**OS:** Windows 10]
**Version:** 0.2.1 and latest develop
**Commit/Build:** f468bef6cce7b55e0b5104f7260da8bb07675913

"local authority won't allow construction above tree height" errors get displayed as (undefined string) - `STR_CONSTRUCTION_ERR_UNKNOWN` in code - every other height step (when you're holding shift). so eg in the attached park you click to build a swinging inverter pirate ship, you get (undefined string), hold shift and move it 1 up, you get the proper error, move it 1 higher again and you get the (undefined string) again. 

I did try to investigate but I find the error code stuff a little baffling. All I can say is the error is set on line 1093 of Track.cpp. 

Related to #7439 and #8014 

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open attached save
2. Try and build an inverted pirate ship

**Save game:**
[Raceway Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/2457788/Raceway.Park.zip)

### PR DESCRIPTION
**Pull request by tupaschoal**
I'm picking up on stale #9432 

I did apply the changes to the maze, as @duncanspumpkin suggested:
> If you are going to make this change make the change for mazes as well its just inconsistent as it is at present.
> As this is a complex equation it should really be a constexpr that is named.

I didn't convert it to a `constexpr` because I was unsure if @ZehMatt 's comment was applicable without changing other places or not:
https://github.com/OpenRCT2/OpenRCT2/pull/9432/files#r294541067

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I want to test it.

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 1]
```diff
@@ -3797,9 +3789,12 @@ void ride_construction_tooldown_construct(ScreenCoordsXY screenCoords)
         z = _trackPlaceZ;
     }
 
+    // search for z value to build at, up to max ride height
+    int numAttempts = (z <= (8 * MAX_TRACK_HEIGHT) ? MAX_TRACK_HEIGHT - (z / 8) + 1 : 2);
+
     if (ride->type == RIDE_TYPE_MAZE)
     {
-        for (int32_t zAttempts = 41; zAttempts >= 0; zAttempts--)
+        for (int32_t zAttempts = numAttempts; zAttempts > 0; zAttempts--)
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/RideConstruction.cpp]: Is there any reason this is done backwards?

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 2]
```diff
@@ -3859,7 +3854,7 @@ void ride_construction_tooldown_construct(ScreenCoordsXY screenCoords)
         return;
     }
 
-    for (int32_t zAttempts = 41; zAttempts >= 0; zAttempts--)
+    for (int32_t zAttempts = numAttempts; zAttempts > 0; zAttempts--)
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/RideConstruction.cpp]: Same as above, this can be probably done forward.

File: src/openrct2-ui/windows/RideConstruction.cpp (hunk 1 above)
Comment (tupaschoal) [reply src/openrct2-ui/windows/RideConstruction.cpp]: I don't think so, maybe the original author thought that counting down is more intuitive for attempts?

**Comment by tupaschoal** [comment]
I applied the changes you requested @ZehMatt and everything seems to be working fine. I tested #8064 without my patch, saw the undefined strings and, applying the patch, they're gone.

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 3]
```diff
@@ -3561,9 +3560,12 @@ void ride_construction_toolupdate_construct(ScreenCoordsXY screenCoords)
     }
 
     _previousTrackPiece = _currentTrackBegin;
+    // search for appropriate z value for ghost, up to max ride height
+    int numAttempts = (z <= (8 * MAX_TRACK_HEIGHT) ? MAX_TRACK_HEIGHT - (z / 8) + 1 : 2);
+
     if (ride->type == RIDE_TYPE_MAZE)
     {
-        for (;;)
+        for (int zAttempts = 1; zAttempts < numAttempts; ++zAttempts)
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/RideConstruction.cpp]: Whats the reason here to start at 1? The other loops seem to be starting at 0

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 4]
```diff
@@ -3844,7 +3839,7 @@ void ride_construction_tooldown_construct(ScreenCoordsXY screenCoords)
                     context_broadcast_intent(&intent2);
                     break;
                 }
-                else if (zAttempts >= 0)
+                else if (zAttempts < numAttempts)
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/RideConstruction.cpp]: zAttempts < numAttempts will be always true

File: src/openrct2-ui/windows/RideConstruction.cpp (hunk 3 above)
Comment (tupaschoal) [reply src/openrct2-ui/windows/RideConstruction.cpp]: The previous code had:
```
bx--;
if (bx == 0)
    break;
```
So it meant that the `currentTrackBegin.z += 16` was only done `bx - 1` times. I guess that's why the for starts at `1`

Comment (ZehMatt) [reply src/openrct2-ui/windows/RideConstruction.cpp]: Something doesn't quite add up, a few lines below it also had the check for when ```bx >= 0``` which is impossible to reach given that it would break out if ```bx == 0```. Can you test what happens if you were to start every loop at 0?

Comment (tupaschoal) [reply src/openrct2-ui/windows/RideConstruction.cpp]: Seems to not make a difference, at least in what I'm doing. I'm using `Raceway Park` and testing building above the tree line.

**Comment by tupaschoal** [comment]
> This PR allows me to demolish trees on tiles that I only have construction rights for.
> 
> Can be tested easily by trying to build a flat ride on a construction-rights-owned piece of land with a tree on it.

I found out something very interesting. If you enable the sandbox mode to set the construction rights (and do), you can do this even without applying this branch. I'm thinking whether the game doesn't reset the land to just construction rights (kind of does OWN & CONSTRUCTION RIGHTS), I find it likely.

**Comment by Gymnasiast** [comment]
Hm, it might be that I didn't turn off sandbox mode properly.

I'd like to double-check.

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 5]
```diff
@@ -3561,9 +3560,12 @@ void ride_construction_toolupdate_construct(ScreenCoordsXY screenCoords)
     }
 
     _previousTrackPiece = _currentTrackBegin;
+    // search for appropriate z value for ghost, up to max ride height
+    int numAttempts = (z <= (8 * MAX_TRACK_HEIGHT) ? MAX_TRACK_HEIGHT - (z / 8) + 1 : 2);
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/RideConstruction.cpp]: This is hard to read and uses hard coded `8`s instead of constants.

I'd prefer the following:
```suggestion
    const auto smallZ = z / COORDS_Z_STEP;
    int numAttempts = (smallZ <= MAX_TRACK_HEIGHT ? (MAX_TRACK_HEIGHT - smallZ + 1) : 2);
```

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 6]
```diff
@@ -3796,9 +3788,12 @@ void ride_construction_tooldown_construct(ScreenCoordsXY screenCoords)
         z = _trackPlaceZ;
     }
 
+    // search for z value to build at, up to max ride height
+    int numAttempts = (z <= (8 * MAX_TRACK_HEIGHT) ? MAX_TRACK_HEIGHT - (z / 8) + 1 : 2);
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/RideConstruction.cpp]: See previous comment

**Comment by tupaschoal** [comment]
Done
