### PR TITLE
Let security guards alternate between slow and fast walking

### LINKED ISSUE #23480: Security guards never leave patrolling state
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

OpenRCT2 0.4.17 Release

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

Security guards will never leave their patrolling state (slow walking with hands behind back) and as such never walk normally asides from the first few seconds after you hire them as changing the walking style depends on leaving the patrolling state which security guards don't do.

From what i can tell this issue has existed since RCT2 vanilla and RCT1LL although it's a bit hard to test vanilla. For now i've marked this as an original issue as it seems unlikely that there's a niche situation where it does swap back to the regular walking style.

### Steps to reproduce

1. Open any park
2. Spawn a security guard
3. The security guard will be normally walking at first, and then move their hands behind their back and slow walk for all eternity.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Security guards are known for their slow-paced movement throughout the park. They only have a passive effect on guests: vandals think twice when there are security guards in the vicinity. This PR is an experiment to add a bit more variety to security guards: we now let them alternate between slow and fast/regular walking speeds.

Surprisingly, both of these walking speeds are actually facilitated in the vanilla sprite set, though the 'slow walking' set is the only one used. This is characterised by the guard walking with their hands behind their backs. Conversely, the fast/regular walking speed simply has the guard with their hands next to their hips, like other peeps.

Currently, I'm letting the guards alternate based on their surrounding crowd density. If there are more than 20 guests in the surrounding 3x3 tiles, the guards will patrol slowly. If not, they will walk regularly. This threshold could perhaps do with some tweaking, but at least security guards no longer walk slowly in deserted areas.

Personally, I think this adds a nice bit of variety to security guards, while not impacting gameplay. Please let me know what you think.

Closes #23480.

https://github.com/user-attachments/assets/392754d0-bba8-4af2-8e37-305bc4413e70

### CODE REVIEW

**Comment by J-PIE-314** [comment]
Before this PR, one can observe the security guard walk quickly for a brief moment after placing them on a path.

File: src/openrct2/entity/Staff.cpp [hunk 1]
```diff
@@ -1644,14 +1644,57 @@ bool Staff::UpdatePatrollingFindSweeping()
...
 {
     if (AssignedStaffType != StaffType::Security)
         return;
 
-    PeepAnimationGroup newAnimationGroup = PeepAnimationGroup::Alternate;
-    if (State != PeepState::Patrolling)
-        newAnimationGroup = PeepAnimationGroup::Normal;
+    // Alternate between walking animations based on crowd size
+    auto newAnimationGroup = PeepAnimationGroup::Normal;
+    if (State == PeepState::Patrolling)
```
Comment (tupaschoal) [inline src/openrct2/entity/Staff.cpp]: It seems like the security guards state can never be different than patrolling from what I checked (?)

File: src/openrct2/entity/Staff.cpp [hunk 2]
```diff
@@ -1644,14 +1644,57 @@ bool Staff::UpdatePatrollingFindSweeping()
...
+    {
+        for (int32_t tileY = y - kLookupRadius; tileY <= y + kLookupRadius; tileY += kCoordsXYStep)
+        {
+            for (auto* guest : EntityTileList<Guest>({ tileX, tileY }))
+            {
+                if (guest->x == kLocationNull)
+                    continue;
+
+                int16_t zDist = std::abs(z - guest->z);
+                if (zDist > 48)
```
Comment (tupaschoal) [inline src/openrct2/entity/Staff.cpp]: Maybe add a comment explaining how many tiles apart vertically this is?

File: src/openrct2/entity/Staff.cpp [hunk 3]
```diff
@@ -1644,14 +1644,57 @@ bool Staff::UpdatePatrollingFindSweeping()
...
-    if (State != PeepState::Patrolling)
-        newAnimationGroup = PeepAnimationGroup::Normal;
+    // Alternate between walking animations based on crowd size
+    auto newAnimationGroup = PeepAnimationGroup::Normal;
+    if (State == PeepState::Patrolling)
+    {
+        constexpr auto kSecurityAltThreshold = 20;
+        bool useAlternative = CountNearbyPeeps() > kSecurityAltThreshold;
+        if (useAlternative)
+            newAnimationGroup = PeepAnimationGroup::Alternate;
```
Comment (tupaschoal) [inline src/openrct2/entity/Staff.cpp]:
```suggestion
        if (CountNearbyPeeps() > kSecurityAltThreshold)
            newAnimationGroup = PeepAnimationGroup::Alternate;
```
Not sure the boolean is adding too much value

File: src/openrct2/entity/Staff.cpp [hunk 4]
```diff
@@ -1644,14 +1644,57 @@ bool Staff::UpdatePatrollingFindSweeping()
...
         return;
 
-    PeepAnimationGroup newAnimationGroup = PeepAnimationGroup::Alternate;
-    if (State != PeepState::Patrolling)
-        newAnimationGroup = PeepAnimationGroup::Normal;
+    // Alternate between walking animations based on crowd size
+    auto newAnimationGroup = PeepAnimationGroup::Normal;
+    if (State == PeepState::Patrolling)
+    {
+        constexpr auto kSecurityAltThreshold = 20;
```
Comment (tupaschoal) [inline src/openrct2/entity/Staff.cpp]: I'm trying to think whether 20 is too much, but I have no clear opinion yet.

**Review by tupaschoal — COMMENTED** [review]
I haven't tested yet, just looked at the code and the idea sounds pretty nice, specially to make the security guard speed when no one is around,

By looking at the gif there are some times where he starts walking slowly again but no peep is nearby, and I wonder if it's because we're counting peep on rides. Maybe we should exclude PeepStates like `OnRide`, `EnteringRide`, `LeavingRide` and so on and only count the ones where they're likely on footpaths.

**Comment by AaronVanGeffen** [comment]
> By looking at the gif there are some times where he starts walking slowly again but no peep is nearby, and I wonder if it's because we're counting peep on rides. Maybe we should exclude PeepStates like OnRide, EnteringRide, LeavingRide and so on and only count the ones where they're likely on footpaths.

That's a good idea. I was also thinking we could exclude peeps in queues, as I don't think they vandalise anything while queued. 

(Speaking of queues, I would like security staff to not bother to walking into queues. But that's probably best left for another PR.)

**Comment by ZehMatt** [comment]
> > By looking at the gif there are some times where he starts walking slowly again but no peep is nearby, and I wonder if it's because we're counting peep on rides. Maybe we should exclude PeepStates like OnRide, EnteringRide, LeavingRide and so on and only count the ones where they're likely on footpaths.
> 
> That's a good idea. I was also thinking we could exclude peeps in queues, as I don't think they vandalise anything while queued.
> 
> (Speaking of queues, I would like security staff to not bother to walking into queues. But that's probably best left for another PR.)

I would try to avoid any additional complexity in the loop, there is no limit to how many guests are within the radius and this can easily expand to thousands, it might be fine but just saying, there are no bounds for this kind of query.

**Comment by tupaschoal** [comment]
It probably would help to early exit if the threshold is reached, to avoid querying unnecessarily

File: src/openrct2/entity/Staff.cpp (hunk 1 above)
Comment (AaronVanGeffen) [reply src/openrct2/entity/Staff.cpp]: They can be in the `Falling` state, e.g. when they're being placed, or being drowned... 🤐

File: src/openrct2/entity/Staff.cpp (hunk 2 above)
Comment (AaronVanGeffen) [reply src/openrct2/entity/Staff.cpp]: I think the z step size is half of the x and y step size. I think I based the loop on the `Staff::EntertainerUpdateNearbyPeeps` one, fwiw.

File: src/openrct2/entity/Staff.cpp (hunk 3 above)
Comment (AaronVanGeffen) [reply src/openrct2/entity/Staff.cpp]: Hmm, I was going for self-describing code, but the condition has admittedly gotten less complicated.

File: src/openrct2/entity/Staff.cpp (hunk 4 above)
Comment (AaronVanGeffen) [reply src/openrct2/entity/Staff.cpp]: Yes, I think it may be too high now that queuing peeps no longer count towards crowdedness. Worth experimenting with. (I mentioned this in the OP as well.)

**Comment by AaronVanGeffen** [comment]
> It probably would help to early exit if the threshold is reached, to avoid querying unnecessarily

Good idea. I've rewritten the loop function to return a bool instead of the count, so it now just returns early.

> By looking at the gif there are some times where he starts walking slowly again but no peep is nearby, and I wonder if it's because we're counting peep on rides. Maybe we should exclude PeepStates like `OnRide`, `EnteringRide`, `LeavingRide` and so on and only count the ones where they're likely on footpaths.

I've opted to only count guests for whom `IsActionWalking` returns true. Let me know what you think.

File: src/openrct2/entity/Staff.cpp (hunk 4 above)
Comment (AaronVanGeffen) [reply src/openrct2/entity/Staff.cpp]: Seems to be working relatively well. A relatively empty Bumbly Beach save gets a walking guard, while an overfull Funtopia gets the slow patrolling one. It looks fairly intuitive to me. Please give it a go as well :)

Comment (tupaschoal) [reply src/openrct2/entity/Staff.cpp]: Seems alright from a small test. Are you considering excluding the people on rides?

Comment (AaronVanGeffen) [reply src/openrct2/entity/Staff.cpp]: I am only including guests that are actually walking right now. To my knowledge that should exclude guests that are on rides.

**Comment by AaronVanGeffen** [comment]
I've updated the replays (`StaffFireAction`, `StaffSetPatrolAreaAction`), so CI should pass now. Note that the `bpb1000` replay doesn't require an update, as the park does not employ any security guards.

NB: network version still needs to be bumped before this can be merged.

~~Edit: ahh, I based the replay bundle on v0.0.88, the change of which ended up reverted. So now bpb1000 fails after all. I'll have to rework it later.~~ Done.
