### PR TITLE
Fix #7030: Ride reliability underflows

### LINKED ISSUE #7030: Reliability goes above 100% on old rides that lack inspection
**OS:** MacOS 10.13
**Version:** 0.1.2
**Commit/Build:** 3ba0cc3

Noticed that my Enterprise had a higher reliability than 100%. I tried to reproduce this in a new game and found out that the reliability will overflow at a certain point. This will cause less breakdowns for quite some time.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Build some ride and set inspection on never. Place some mechanic for the breakdowns.
2. Use cheats to move time 15 years in advance.
3. Change the speed of the game and notice the reliability going down very quick (as expected).
4. At some point it will reach zero, then it will overflow to above 250% and slowly going down.

**Dump file**

**Screenshots / Video:**
schermafdruk 2018-01-14 20 31 27

**Save game:**
[Overflow.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1629737/Overflow.sv6.zip)

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -2327,7 +2327,7 @@ static void ride_breakdown_update(sint32 rideIndex)
 
     // Calculate breakdown probability?
     sint32 unreliabilityAccumulator = ride->unreliability_factor + get_age_penalty(ride);
-    ride->reliability = Math::Max((uint16)0, (uint16)(ride->reliability - unreliabilityAccumulator));
+    ride->reliability = (uint16) Math::Max(0, (ride->reliability - unreliabilityAccumulator));
```
Comment (AaronVanGeffen) [inline src/openrct2/ride/Ride.cpp]: std::max<uint16> ?

Comment (pss9205) [reply src/openrct2/ride/Ride.cpp]: its more nice than my fix 👍
