### PR TITLE
Fix #7536: Android build fails to start

### LINKED ISSUE #7536: Android build fails to start
**OS:** Android 8.1
**Commit/Build:** 829ac11bece800db78e6e52a2b572b3a2866783d

Trying to start Android build causes a crash.

Attached stack trace:
```
Build fingerprint: 'OnePlus/OnePlus5/OnePlus5:8.1.0/OPM1.171019.011/04201219:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 24135, tid: 24801, name: Thread-2  >>> website.openrct2.debug <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: java_class == null'
    x0   0000000000000000  x1   00000000000060e1  x2   0000000000000006  x3   0000000000000008
    x4   0000202020232a3d  x5   0000202020232a3d  x6   0000202020232a3d  x7   3d2a23202020ffff
    x8   0000000000000083  x9   45f17b4a70418a14  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  ffffffffffffffff  x14  ffff000000000000  x15  ffffffffffffffff
    x16  0000000291ae6fa8  x17  00000079795ee598  x18  00000078db60c5f0  x19  0000000000005e47
    x20  00000000000060e1  x21  00000078d8b98b00  x22  0000000000000000  x23  00000078daf01b99
    x24  0000000000000b79  x25  00000078db114400  x26  0000000000000b78  x27  00000078daf01c50
    x28  0000000000000059  x29  00000078daf01b40  x30  00000079795a3df8
    sp   00000078daf01b00  pc   00000079795a3e14  pstate 0000000060000000

backtrace:
    #00 pc 000000000001de14  /system/lib64/libc.so (abort+104)
    #01 pc 0000000000473034  /system/lib64/libart.so (art::Runtime::Abort(char const*)+552)
    #02 pc 00000000005687a8  /system/lib64/libart.so (android::base::LogMessage::~LogMessage()+996)
    #03 pc 00000000002fd02c  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1700)
    #04 pc 00000000002fd280  /system/lib64/libart.so (art::JavaVMExt::JniAbortF(char const*, char const*, ...)+180)
    #05 pc 0000000000344f80  /system/lib64/libart.so (art::JNI::GetMethodID(_JNIEnv*, _jclass*, char const*, char const*)+1400)
    #06 pc 000000000012eab8  /data/app/website.openrct2.debug-yH13UNoqJZVp5diup7yt5w==/lib/arm64/libopenrct2.so (Zip::Open(std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>> const&, ZIP_ACCESS)+124)
    #07 pc 0000000000167a5c  /data/app/website.openrct2.debug-yH13UNoqJZVp5diup7yt5w==/lib/arm64/libopenrct2.so (ObjectFactory::CreateObjectFromZipFile(IObjectRepository&, std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>> const&)+56)
    #08 pc 0000000000172750  /data/app/website.openrct2.debug-yH13UNoqJZVp5diup7yt5w==/lib/arm64/libopenrct2.so (ObjectFileIndex::Create(int, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&) const+272)
    #09 pc 00000000001755b4  /data/app/website.openrct2.debug-yH13UNoqJZVp5diup7yt5w==/lib/arm64/libopenrct2.so (FileIndex<ObjectRepositoryItem>::BuildRange(int, FileIndex<ObjectRepositoryItem>::ScanResult const&, unsigned long, unsigned long, std::__ndk1::vector<ObjectRepositoryItem, std::__ndk1::allocator<ObjectRepositoryItem>>&, std::__ndk1::atomic<unsigned long>&, std::__ndk1::mutex&) const+260)
    #10 pc 0000000000176744  /data/app/website.openrct2.debug-yH13UNoqJZVp5diup7yt5w==/lib/arm64/libopenrct2.so (JobPool::ProcessQueue()+424)
    #11 pc 0000000000176d98  /data/app/website.openrct2.debug-yH13UNoqJZVp5diup7yt5w==/lib/arm64/libopenrct2.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEM7JobPoolFvvEPS7_EEEEEPvSC_+64)
    #12 pc 0000000000067e10  /system/lib64/libc.so (__pthread_start(void*)+36)
    #13 pc 000000000001f240  /system/lib64/libc.so (__start_thread+68)
```

Previous available Android build, bd5b1376cbe098140651a6a4ddfa2876a68b2b0c works fine.

Looking at https://github.com/OpenRCT2/OpenRCT2/compare/bd5b1376cbe098140651a6a4ddfa2876a68b2b0c...829ac11bece800db78e6e52a2b572b3a2866783d it's possible this is a regression from https://github.com/OpenRCT2/OpenRCT2/pull/7512

### PR DESCRIPTION
**Pull request by janisozaur**
This was a regression from #7435 which introduced threads and caused JNI
to misbehave and fail to load our expected classes. Provide a workaround
based on the description in https://stackoverflow.com/a/16302771 which
stores a main thread's class loader and uses that in neighbouring
threads.

### CODE REVIEW

**Comment by janisozaur** [comment]
screen4

File: src/openrct2/platform/Android.cpp [hunk 1]
```diff
@@ -62,4 +62,51 @@ bool platform_get_steam_path(utf8* outPath, size_t outSize)
...
+    // This is a workaround to be able to call JNI's ClassLoader from non-main
+    // thread, based on https://stackoverflow.com/a/16302771
+    // Apparently it's OK to use it from across different thread, but JNI
+    // only looks for ClassLoader in the _current_ thread and fails to find
+    // it when searched for from a native library's non-main thread.
+
+    // If we're here, SDL's JNI_OnLoad has already been called and set env
+    JNIEnv* env = (JNIEnv*)SDL_AndroidGetJNIEnv();
+
+    // First load some our random class
```
Comment (Gymnasiast) [inline src/openrct2/platform/Android.cpp]: This looks ungrammatical to me.

Comment (janisozaur) [reply src/openrct2/platform/Android.cpp]: Same, but can you provide a better alternative?

Comment (Gymnasiast) [reply src/openrct2/platform/Android.cpp]: I would change it to `// While we use 'MainActivity' here, this workaround will work with any class.`, then.

File: src/openrct2/platform/Android.cpp [hunk 2]
```diff
@@ -62,4 +62,51 @@ bool platform_get_steam_path(utf8* outPath, size_t outSize)
...
+    auto randomClass = env->FindClass("website/openrct2/MainActivity");
```
[the remark this answers is not in the document]
Comment (richard-fine) [reply src/openrct2/platform/Android.cpp]: Ah, I see. I think the comment could benefit from explaining *why* any arbitrary class can be chosen, then, rather than just saying that you're picking one at random; having read the code and the SO link I think I get why this works, but it feels like the right place to front-load a bit more explanation to me.

**Comment by janisozaur** [comment]
Updated
