### PR TITLE
Fix #14854. Accidental double inversion

### LINKED ISSUE #14854: Cannot paste elements or insert corrupt elements in Tile Inspector
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 072772a

Pasting tile elements after copying them in the Tile Inspector causes blank error to appear and paste not happening. The same occurs with inserting corrupt element.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open Tile Inspector.
2. Copy an element.
3. Paste an element.

or
1. Open Tile Inspector.
2. Insert a corrupt element on any tile.

**Screenshots / Video:**

https://user-images.githubusercontent.com/20048660/121250509-15c09100-c8a6-11eb-9e1f-62ed92ca2922.mp4

### PR DESCRIPTION
**Pull request by duncanspumpkin**

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
Tested the tile inspector for both copy paste and insert corrupt tile. Both now working again.

File: src/openrct2/world/TileInspector.cpp [hunk 1]
```diff
@@ -359,7 +359,7 @@ namespace OpenRCT2::TileInspector
     GameActionResultPtr PasteElementAt(const CoordsXY& loc, TileElement element, bool isExecuting)
     {
         // Make sure there is enough space for the new element
-        if (!!MapCheckCapacityAndReorganise(loc))
```
Comment (IntelOrca) [inline src/openrct2/world/TileInspector.cpp:362]: I am surprised none of the compilers give a warning for this.

Comment (tupaschoal) [reply src/openrct2/world/TileInspector.cpp:362]: Interesting indeed 🤔
