### PR TITLE
Fix #17784: Colour preset RNG is biased

### LINKED ISSUE #17784: Colour preset RNG is biased
### Operating System

Windows 10, 64 Bit 

### OpenRCT2 build

OpenRCT2, v0.4.1-165-gbe52f64 (be52f64 on develop) provided by GitHub

### Describe the issue

It seems like rides cycle through colors once and then favour one colour over any other. I found this out while adding more presets to a ride, which wouldnt load as it was stuck on the same colour.

image

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Choose a ride type
2. Build it
3. Repeat
4. Eventually you will notice it will only select a single colour and no others.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by IntelOrca**
Fixes both ride colour and vehicle colour presets.

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -2140,48 +2140,50 @@ VehicleColour ride_get_vehicle_colour(Ride* ride, int32_t vehicleIndex)
...
         return 0;
-    if (presetList->count == 255)
+    if (colourPresets->count == 255)
         return 255;
 
-    for (int32_t attempt = 0; attempt < 200; attempt++)
+    // Find all the presets that haven't yet been used in the park for this ride type
+    std::vector<uint8_t> unused;
+    unused.reserve(colourPresets->count);
+    for (size_t i = 0; i < colourPresets->count; i++)
```
Comment (Broxzier) [inline src/openrct2/ride/Ride.cpp:2171]:
```suggestion
    for (uint8_t i = 0; i < colourPresets->count; i++)
```

**Review by Broxzier — APPROVED** [review]
