### PR TITLE
Fix #20196: New scenarios start with an incorrect temperature

### LINKED ISSUE #20196: Scenarios newly created from Scenario Editor start with incorrect temperature in relation to selected climate type
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When you create a new scenario in the Scenario Editor and then begin a new game in that scenario, most of the time it will start with a temperature of 55°F (13°C) and will quite often go into heavy rain near the beginning, even if the scenario in question has its climate set to Hot and dry. Previously, any newly created scenario would begin at 62°F (17°C) if its selected climate was Warm or Hot and dry, but now that is no longer the case. Every newly created scenario now starts with a temperature of 55°F (13°C), which is typical of the Cool and wet climate.
Plagenockite Deadlands 2023-05-12 19-09-46
In the above screenshot I have created a new custom scenario. I selected the Warm climate while setting it up, and in older versions of OpenRCT2, as well as (quite possibly) RCT2 vanilla and RCT Classic, any new scenario created with Warm or Hot and dry climate would be expected to begin at 62°F (17°C). Yet, it starts at 55°F (13°C).

**EDIT (2023-05-13):** Can also confirm that this happens with the Cold climate setting, which incorrectly starts at 55°F (13°C) instead of 48°F (9°C) like it used to in older versions.

**EDIT2 (2023-06-23):** The game always selects Cool and wet as the default scenario climate when you create a new scenario.

### Steps to reproduce

1. Go to Scenario Editor
2. Create a new scenario and set its climate to Warm, Hot and dry, or Cold
3. Start up the scenario
4. Notice that the temperature now starts at 55°F (13°C) instead of 62°F (17°C) despite the scenario not using the Cool and wet climate setting

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by tanzimchowdh**
Climates set and saved in scenario editor will now be correct upon first loading of scenario. Previously, a double save in the scenario editor was necessary to see the climate change in effect.

### CODE REVIEW

File: src/openrct2/actions/ClimateSetAction.cpp [hunk 1]
```diff
@@ -43,7 +43,8 @@ GameActions::Result ClimateSetAction::Query() const
 
 GameActions::Result ClimateSetAction::Execute() const
 {
-    gClimate = ClimateType{ _climate };
+    //gClimate = ClimateType{ _climate };'
```
Comment (ZehMatt) [inline src/openrct2/actions/ClimateSetAction.cpp:46]: Delete the code if its not used

**Review by ZehMatt — CHANGES_REQUESTED** [review]

**Comment by Gymnasiast** [comment]
@ SpartanFrederic104 Could you test this PR and let us know if it solves the issue?

**Comment by SpartanFrederic104** [comment]
Sure thing. Just one question: how would I test this?

**Comment by Gymnasiast** [comment]
You can download a CI from this page: https://github.com/OpenRCT2/OpenRCT2/actions/runs/7431878773

**Comment by SpartanFrederic104** [comment]
Sorry for the late response due to IRL complications, but I can happily confirm this PR fixes the issue. I made four dummy scenarios, each one using one of the four default climate settings, starting from Cool and wet to Cold, then Hot and dry, and finally Warm.

CoolWet test 2024-01-15 13-07-33
Cold Climate Test 2024-01-15 12-58-16
HotDry test 2024-01-15 13-01-35
Warm test 2024-01-15 13-05-01

With this PR, Cool and wet still starts at 55℉ (13℃), but Warm and Hot and dry now start at 62℉ (17℃), and Cold now starts at 48℉ (9℃).

**Review by tupaschoal — COMMENTED** [review]
I haven't tested, but code-wise it seems to make a lot of sense since, among other things, `gClimate` would only be read from on calling `ClearMapForEditing` on the Editor file.

Can you add a changelog entry please @tanzimchowdh ? Also thanks @SpartanFrederic104 for testing and the thorough reporting :)

**Review by Gymnasiast — APPROVED** [review]

**Review by tupaschoal — APPROVED** [review]
