### PR TITLE
Fix #13958: Queue corruption due to intersecting entrances

### LINKED ISSUE #13958: Assertion failed: Peep Ridesubstate should be LeaveEntrance
**OS:** [e.g. Windows 10]
**Version:** [0.3.2]
**Commit/Build:** [8c5cd61]

My server keeps crashing (usually after several hours) with the following message:
image

Here's a save file where it will happen a minute or so after you open it (speed up the game a bit to make it happen faster). Removing all guests from the park will temporarily stop it from happening.
[autosave_2021-01-26_16-43-13.zip](https://github.com/OpenRCT2/OpenRCT2/files/5874470/autosave_2021-01-26_16-43-13.zip)

### PR DESCRIPTION
**Pull request by duncanspumpkin**
There was a whole host of bugs that this issue has exposed which were caused by intersecting the queue of a ride with an entrance/exit or shop. When this was done the peep would be removed from the queue incorrectly and could end up at the wrong station or a variety of other unexpected behaviour

### CODE REVIEW

File: src/openrct2/peep/Peep.cpp [hunk 1]
```diff
@@ -2880,6 +2890,13 @@ static bool peep_interact_with_shop(Peep* peep, const CoordsXYE& coords)
         return true;
     }
 
+    // If we are queuing ignore the 'shop'
+    // This can happen when paths clip through track
+    if (peep->State == PeepState::Queuing)
```
Comment (tupaschoal) [inline src/openrct2/peep/Peep.cpp:2895]: Shouldn't this be
```c++
 if (peep->State == PeepState::Queuing && peep->CurrentRide != rideIndex)
 ```

Like the other one above?

File: src/openrct2/peep/Peep.h [hunk 2]
```diff
@@ -264,7 +264,8 @@ enum class PeepRideSubState : uint8_t
     LeaveVehicle = 7,
     ApproachExit = 8,
     InExit = 9,
-    // 10, 11 not used
+    InQueue = 10,
+    AtQueueFront = 11,
```
Comment (tupaschoal) [inline src/openrct2/peep/Peep.h:268]: Nice find!

File: src/openrct2/peep/Peep.cpp (hunk 1 above)
Comment (duncanspumpkin) [reply src/openrct2/peep/Peep.cpp:2895]: So I thought about that for a while. I don't think so. It can only get to here if a track is intersecting a path. So in theory we want it to skip it even if the track is from the ride we are queueing for as we are going to the entrance only. Counter argument to this is that the ride type has already been checked to see if it's a shop. And shops don't have track or queues so it wouldn't matter having the extra check as it could never get to this point.

Comment (tupaschoal) [reply src/openrct2/peep/Peep.cpp:2895]: Ok, sold!

**Review by tupaschoal — APPROVED** [review]
Looks ok, needs the network bump

**Review by Gymnasiast — APPROVED** [review]
