### PR TITLE
Fix #18805 crash in WallCheckObstructionWithTrack

### LINKED ISSUE #18805: [b43e6f] openrct2.exe: WallPlaceAction::WallCheckObstructionWithTrack, WallPlaceAction::WallCheckObstruction, WallPlaceAction...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/b43e6f625cea3d94a0b8d1462bfba2304a98e35046364c5b73d923768b19a3df">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>20010000-e1b1-3d09-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Fritz\Documents\OpenRCT2\crash\4df93e13-5221-4404-b359-5259817de5e1.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.2-235-g57a1bc4 (57a1bc4 on develop) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>57a1bc4</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
WallPlaceAction::WallCheckObstructionWithTrack
WallPlaceAction::WallCheckObstruction
WallPlaceAction::Query
GameActions::QueryInternal
GameActions::ExecuteNested
TrackDesignPlaceSceneryElement
TrackDesignPlaceAllScenery
TrackDesignPlaceVirtual
TrackDesignAction::Execute
GameActions::ExecuteInternal
TrackDesignPlaceWindow::OnToolDown
InputWidgetLeft
GameHandleInputMouse
GameHandleInput
ContextHandleInput
OpenRCT2::GameState::Tick
OpenRCT2::Context::Tick
EntityTweener::PreTick
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main
UnhandledExceptionFilter</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by zzril**

### CODE REVIEW

File: src/openrct2/actions/WallPlaceAction.cpp [hunk 1]
```diff
@@ -460,6 +460,11 @@ bool WallPlaceAction::WallCheckObstructionWithTrack(
     }
 
     const rct_preview_track* trackBlock = ted.GetBlockForSequence(sequence + 1);
+    if (trackBlock == nullptr)
+    {
+        return true;
```
Comment (janisozaur) [inline src/openrct2/actions/WallPlaceAction.cpp:465]: Is it really the correct value to return here? It seems true should only get returned when proper obstruction is found, all other cases return false instead.

This should also get a replay park for our tests, but this can be added in another PR

Comment (zzril) [reply src/openrct2/actions/WallPlaceAction.cpp:465]: False is returned in the cases where the door piece should not be allowed to be placed. E.g.:  
```c
if (ted.Definition.bank_end != 0)
    {
        return false;
    }
```
returns false when the track is banked (and thus shall not be allowed to have a door).

I ran some tests in the track designer (slamming random walls with or without doors on tracks that allow them or don't), which also suggested that true should be returned.  
(Found a counter-example where setting it to false would not give the expected result.)

However, I'm not sure why the nullptr was returned in the first place.

I'll try to give a replay park once I figure out how to create one. ;)

Comment (Gymnasiast) [reply src/openrct2/actions/WallPlaceAction.cpp:465]: The crash happens when `trackBlock` is null. Until yesterday, `trackBlock` could also be the end marker, checked at line 463/468, but this function will return `null` in such a cause, to catch bugs more easily. (I.e. it avoids using an end marker by accident).

You need to revert these lines, and instead change the `if` statement at line 463/468 to read `if (trackBlock != nullptr)`. That will change the logic to how it behaved until yesterday.

**Review by Gymnasiast — APPROVED** [review]
