### PR TITLE
Fix #22484: Lingering ghost entrance after placing park entrance

### LINKED ISSUE #22484: Park entrance placement races with ghost placement
### Operating System

macOS Sonoma 14.6 (23G80)

### OpenRCT2 build

OpenRCT2, v0.4.13-14 (23c0274012 on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When placing a new park entrance, another ghost entrance is immediately placed on top of the freshly placed park entrance. This does not appear to happen when the placement tool hovers over another existing entrance, just a freshly placed one.

### Steps to reproduce

The order of events appears to be as follows:
```
PlaceParkEntranceToolDown start
Ghost exists and will be removed
PlaceParkEntranceToolDown end
PlaceParkEntranceToolUpdate start
Ghost does not exist
Placing a ghost entrance
PlaceParkEntranceToolUpdate end
Placing a normal entrance
```

Note how the `ToolDown` event executes the placement game action, followed by a `ToolUpdate` event which queues the placement of a ghost entrance, which is not immediately removed. It seems both elements will exist at the same time until the tool is moved again.

NB: we noticed this while working on #21909, but concluded the issue already exists on develop, and is therefore not a regression.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
This applies mix’ solution from #25461 to the park entrance.

### CODE REVIEW

**Comment by mixiate** [comment]
I think the issue is that the ghost removal action doesn't have the ghost flag set. That means the action is not executed immediately, and several new ghosts can be placed before any are removed.

https://github.com/OpenRCT2/OpenRCT2/blob/a7dd47f48bc31b43b7eaf2a6d9a16822d025ff44/src/openrct2/world/Entrance.cpp#L59-L68

Should be `parkEntranceRemoveAction.SetFlags(GAME_COMMAND_FLAG_GHOST | GAME_COMMAND_FLAG_ALLOW_DURING_PAUSED);`

Here's a picture but you can kind of feel it happening anyway, moving the park entrance around is odd. It's fixed with the ghost flag.
Untitled

File: src/openrct2-ui/windows/EditorParkEntrance.cpp [hunk 1]
```diff
@@ -220,6 +228,8 @@ namespace OpenRCT2::Ui::Windows
                 auto pathIndex = isLegacyPath ? gFootpathSelection.LegacyPath : gFootpathSelection.NormalSurface;
                 auto gameAction = GameActions::ParkEntrancePlaceAction(
                     parkEntrancePosition, pathIndex, _selectedEntranceType, isLegacyPath);
+                gameAction.SetCallback(
+                    [&](const GameActions::GameAction*, const GameActions::Result* result) { _placingEntrance = false; });
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/EditorParkEntrance.cpp:232]: This is not safe, the callback can fire when the window is already gone, either that variable is moved outside the window into a static or the callback has to lookup the window first to access that variable.

**Review by mixiate — APPROVED** [review]
I realised that the ghost issue happens (at least for me) when you join a multiplayer game and try to place a park entrance. It will leave ghosts every time. Doesn't seem to happen for the host. For both placing an entrance doesn't actually show up for the other, causing a desync straight away. The accidentally networked removal action for the ghost probably gets run after creation for the other players, and it removes the actual entrance as there is no ghost for them.

That seems to be fixed with only the ghost flag, however it's not a bad thing to prevent a pointless ghost placement anyway.

So something like `- Fix: [#25569] Placing park entrances in multiplayer does not show for other players causing desyncs`
Could probably be worded a little better. I couldn't find an existing issue for this either.
