### PR TITLE
Fix #13609: Crash in LargeSceneryRemoveAction.cpp

### LINKED ISSUE #13609: [44c69a] openrct2.exe: LargeSceneryRemoveAction::Query, ClearAction::ClearSceneryFromTile, ClearAction::QueryExecute, ClearAc...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/44c69aeedd3750710d905bfcd4a7255f7ffbf2f66b2161a53763ea2670a1aafb">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\34651\Documents\OpenRCT2\3c1217a8-375e-4e31-952d-751191ccd564.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\34651\Documents\OpenRCT2\3c1217a8-375e-4e31-952d-751191ccd564.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\34651\Documents\OpenRCT2\screenshot\Geauga Ocean City 2020-12-19 23-30-10.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>4ee47b1</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
LargeSceneryRemoveAction::Query
ClearAction::ClearSceneryFromTile
ClearAction::QueryExecute
ClearAction::Query
GameActions::QueryInternal
window_top_toolbar_tool_update
GameHandleInput</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**
Initially, I had `return res` in both places, but that replaced the crash with a freeze. So I ended up with the current version, which fixes both.

### CODE REVIEW

**Review by tupaschoal — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
This doesn't look safe

File: src/openrct2/actions/LargeSceneryRemoveAction.cpp [hunk 1]
```diff
@@ -139,6 +142,9 @@ GameActions::Result::Ptr LargeSceneryRemoveAction::Execute() const
     tile_element_remove_banner_entry(tileElement);
 
     rct_scenery_entry* scenery_entry = tileElement->AsLargeScenery()->GetEntry();
+    // If we have a bugged scenery entry we cannot determine cost or size.
+    if (scenery_entry == nullptr)
+        return res;
```
Comment (duncanspumpkin) [inline src/openrct2/actions/LargeSceneryRemoveAction.cpp:147]: This is going to leave a broken tileelement. Perform this check prior to the tile_element_remove_banner_entry and also return a failure state. Not that this will mater as you can't get to here without first performing the query but best do things in the correct order.

Comment (Gymnasiast) [reply src/openrct2/actions/LargeSceneryRemoveAction.cpp:147]: How is it going to _leave_ a broken tile element? If the tile is pointing to an unknown scenery entry, it is already broken. Might as well clean up what we can.

Comment (duncanspumpkin) [reply src/openrct2/actions/LargeSceneryRemoveAction.cpp:147]: But it doesn't do that. It just breaks it more. Just do the same make result here to match every other game action

Comment (Gymnasiast) [reply src/openrct2/actions/LargeSceneryRemoveAction.cpp:147]: > But it doesn't do that. It just breaks it more.

Can you explain how?

Comment (duncanspumpkin) [reply src/openrct2/actions/LargeSceneryRemoveAction.cpp]: It removes the banner entry but not the element so you'll have a tile element that will have a bad banner element reference.

Comment (Gymnasiast) [reply src/openrct2/actions/LargeSceneryRemoveAction.cpp]: I see.

I have made the requested changes.

**Review by duncanspumpkin — APPROVED** [review]
