### PR TITLE
Fix #23443: New GOG version of RCT2 is not extracted correctly

### LINKED ISSUE #23443: Unable to detect RCT2 GOG offline installer
### Operating System

Linux pop-os 6.9.3-76060903-generic

### OpenRCT2 build

0.4.17

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When selecting the appropriate file, I get this error: `The selected file is not the offline GOG Installer for RollerCoaster Tycoon 2. You may have downloaded the GOG Galaxy downloader stub or selected the wrong file.`.

### Steps to reproduce

1. Download both GOG offline installer of the game ([RollerCoaster Tycoon® 2: Triple Thrill Pack](https://www.gog.com/en/game/rollercoaster_tycoon_2)).
2. Files are `setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_wacky_worlds_patch_(76932).exe` and `setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_wacky_worlds_patch_(76932)-1.bin`.
3. Launch the game.
4. Select that I have the GOG offline installer.
5. Select the `.exe`.
6. Not recognized.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Review by AaronVanGeffen — APPROVED** [review]
Changes look good to me. Nice to have this patched!

File: src/openrct2/config/Config.cpp [hunk 1]
```diff
@@ -923,17 +923,22 @@ namespace OpenRCT2::Config
                             uiContext->ShowMessageBox(LanguageGetString(STR_NOT_THE_GOG_INSTALLER));
                         }
 
-                        installPath = Path::Combine(dest, u8"app");
+                        // New installer installs in ‘dest’, old installer installs in ‘dest/app’.
```
Comment (Gymnasiast) [inline src/openrct2/config/Config.cpp:926]:
```suggestion
                        // New installer extracts to ‘dest’, old installer installs in ‘dest/app’.
```
