### PR TITLE
Fix crash in map.getAllEntities("car") when car has an invalid ride (#22182)

### LINKED ISSUE #22182: Crash when using `map.getAllEntities("car")` when car has `ride` set to nonexistent ride
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11-199-gd4f97d3 (d4f97d3 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The game will crash and create a dump file when using `map.getAllEntities("car")` when a car has a `ride` value that is not a ride in existence.

### Steps to reproduce

1. Open game with terminal
2. Open forest frontiers or other map with no rides
3. execute `map.createEntity("car",{})`
4. execute `map.getAllEntities("car")`
5. crash

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZeroBreakpoint**
This PR fixes issue #22182, where calling 'map.createEntity("car",{})' and `map.getAllEntities("car")` would crash
when a car had a ride assigned to a nonexistent ride.

- Added a check to ensure `car` is valid before accessing it.
- Prevented infinite loops by verifying `next_vehicle_on_train` is not self-referencing.
- Ensured safe exit from the loop if `car->next_vehicle_on_train` is null or invalid.

Fixes #22182

### CODE REVIEW

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 1]
```diff
@@ -118,8 +118,24 @@ namespace OpenRCT2::Scripting
                 for (auto carId = trainHead->Id; !carId.IsNull();)
                 {
                     auto car = GetEntity<Vehicle>(carId);
+
+                    // Prevent crashes by checking if the car is valid
+                    if (!car)
```
Comment (Gymnasiast) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:123]:
```suggestion
                    if (car == nullptr)
```

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 2]
```diff
@@ -118,8 +118,24 @@ namespace OpenRCT2::Scripting
                 for (auto carId = trainHead->Id; !carId.IsNull();)
                 {
                     auto car = GetEntity<Vehicle>(carId);
+
+                    // Prevent crashes by checking if the car is valid
```
Comment (Gymnasiast) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:122]:
```suggestion
```
Already obvious from the context.

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 3]
```diff
@@ -118,8 +118,24 @@ namespace OpenRCT2::Scripting
...
+                    if (!car)
+                    {
+                        break; // If car is invalid, exit loop safely
```
Comment (Gymnasiast) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:125]:
```suggestion
                        break;
```

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 4]
```diff
@@ -118,8 +118,24 @@ namespace OpenRCT2::Scripting
...
+                    }
+
+                    // Add the car to the result list
```
Comment (Gymnasiast) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:128]:
```suggestion
```

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 5]
```diff
@@ -118,8 +118,24 @@ namespace OpenRCT2::Scripting
...
                     result.push_back(GetObjectAsDukValue(_context, std::make_shared<ScVehicle>(carId)));
-                    carId = car->next_vehicle_on_train;
+
+                    // Prevent infinite loops: Ensure next_vehicle_on_train is valid
+                    auto nextCarId = car->next_vehicle_on_train;
+                    if (nextCarId.IsNull() || nextCarId == carId)
+                    {
+                        break; // Stop if next car is invalid or self-referencing
```
Comment (Gymnasiast) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:135]:
```suggestion
                        break;
```

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 6]
```diff
@@ -118,8 +118,24 @@ namespace OpenRCT2::Scripting
...
+                    }
+
+                    carId = nextCarId; // Move to the next car in the train
```
Comment (Gymnasiast) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:138]:
```suggestion
                    carId = nextCarId;
```

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 7]
```diff
@@ -118,8 +118,24 @@ namespace OpenRCT2::Scripting
...
+                    if (!car)
+                    {
+                        break; // If car is invalid, exit loop safely
+                    }
+
+                    // Add the car to the result list
                     result.push_back(GetObjectAsDukValue(_context, std::make_shared<ScVehicle>(carId)));
-                    carId = car->next_vehicle_on_train;
+
+                    // Prevent infinite loops: Ensure next_vehicle_on_train is valid
```
Comment (Gymnasiast) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:131]:
```suggestion
                    // Prevent infinite loops: Ensure next_vehicle_on_train is valid and not self-referencing
```

**Comment by Gymnasiast** [comment]
The code itself looks good, but it has way too many comments that are stating the obvious. I thus left some line notes about that.

This also needs a changelog entry. Please add it, making sure to list the problem/crash and not the solution.

**Comment by ZeroBreakpoint** [comment]
> The code itself looks good, but it has way too many comments that are stating the obvious. I thus left some line notes about that.
> 
> This also needs a changelog entry. Please add it, making sure to list the problem/crash and not the solution.

Thank you for your really helpful feedback.  This is my first time assisting with a mod, so I wasn't certain on the level of commenting you were after.  Look forward to helping again in future :)

File: src/openrct2/scripting/bindings/world/ScMap.cpp [hunk 8]
```diff
@@ -118,8 +118,22 @@ namespace OpenRCT2::Scripting
...
+                    {
+                        break;
+                    }
+
                     result.push_back(GetObjectAsDukValue(_context, std::make_shared<ScVehicle>(carId)));
-                    carId = car->next_vehicle_on_train;
+
+                    // Prevent infinite loops: Ensure next_vehicle_on_train is valid and not self-referencing
+                    auto nextCarId = car->next_vehicle_on_train;
+                    if (nextCarId.IsNull() || nextCarId == carId)
```
Comment (duncanspumpkin) [inline src/openrct2/scripting/bindings/world/ScMap.cpp:131]: `nextCarId.IsNull()` is already taken care of by L118 so you don't need that check here.

**Comment by duncanspumpkin** [comment]
> This PR fixes issue #22182, where calling 'map.createEntity("car",{})' and `map.getAllEntities("car")` would crash when a car had a ride assigned to a nonexistent ride.
> 
> * Added a check to ensure `car` is valid before accessing it.
> * Prevented infinite loops by verifying `next_vehicle_on_train` is not self-referencing.
> * Ensured safe exit from the loop if `car->next_vehicle_on_train` is null or invalid.
> 
> Fixes #22182

which part fixed the issue? Was it the nullptr check or the self-referencing? It shouldn't ever end up self referencing but it can happen when people really mess with things. Also this is only checking a single step of a self reference you could have a loop. I presume what fixed it was the nullptr check then.

**Comment by ZeroBreakpoint** [comment]
> > This PR fixes issue #22182, where calling 'map.createEntity("car",{})' and `map.getAllEntities("car")` would crash when a car had a ride assigned to a nonexistent ride.
> > 
> > * Added a check to ensure `car` is valid before accessing it.
> > * Prevented infinite loops by verifying `next_vehicle_on_train` is not self-referencing.
> > * Ensured safe exit from the loop if `car->next_vehicle_on_train` is null or invalid.
> > 
> > Fixes #22182
> 
> which part fixed the issue? Was it the nullptr check or the self-referencing? It shouldn't ever end up self referencing but it can happen when people really mess with things. Also this is only checking a single step of a self reference you could have a loop. I presume what fixed it was the nullptr check then.

The nullptr check (if (car == nullptr)) is what fixed the crash, but the self-referencing check (if (nextCarId == carId)) I figured would be useful for preventing potential infinite loops.

**Comment by duncanspumpkin** [comment]
The one thing I'm still not sure about is why this could get invalid cars. It feels like there is some underlying issue here.

**Comment by spacek531** [comment]
@duncanspumpkin If a vehicle entity is created using a plugin, it is not attached to any ride, which might be what you call "invalid"

**Review by spacek531 — APPROVED** [review]
I tried the repro steps on a mainline develop build and this PR. The develop build didn't crash but it did hang, and this fixed that.

**Comment by duncanspumpkin** [comment]
> @duncanspumpkin If a vehicle entity is created using a plugin, it is not attached to any ride, which might be what you call "invalid"

Yes i get that but do you see anywhere where this touches a ride. The train list is just a linked list of train heads it shouldn't have anything to do with rides. Perhaps this is an edge case where when there are no trains it returns one single null entry and if that's the case we should fix the route cause.

**Comment by spacek531** [comment]
The root cause maybe was fixed elsewhere. In the original report I mentioned it crashed with a dump, but when I tested it today in version OpenRCT2, v0.4.18 (68789ec882 on develop) provided by GitHub the game hangs instead of crashes when I perform the repro steps.

**Comment by duncanspumpkin** [comment]
Okay so the route cause is that the CreateEntity command in scripting is unsafe.

**Comment by duncanspumpkin** [comment]
```
diff --git a/src/openrct2/scripting/bindings/world/ScMap.cpp b/src/openrct2/scripting/bindings/world/ScMap.cpp
index dceb9addaf..1ffe0f506c 100644
--- a/src/openrct2/scripting/bindings/world/ScMap.cpp
+++ b/src/openrct2/scripting/bindings/world/ScMap.cpp
@@ -311,7 +311,30 @@ namespace OpenRCT2::Scripting
         DukValue res;
         if (type == "car")
         {
-            res = createEntityType<Vehicle, ScVehicle>(_context, initializer);
+            Vehicle* entity = CreateEntity<Vehicle>();
+            if (entity == nullptr)
+            {
+                // Probably no more space for entities for this specified entity type.
+                res = ToDuk(_context, undefined);
+            }
+            else
+            {
+                auto entityPos = CoordsXYZ{ AsOrDefault(initializer["x"], 0), AsOrDefault(initializer["y"], 0),
+                                            AsOrDefault(initializer["z"], 0) };
+                entity->MoveTo(entityPos);
+
+                entity->sound1_id = OpenRCT2::Audio::SoundId::Null;
+                entity->sound2_id = OpenRCT2::Audio::SoundId::Null;
+                entity->next_vehicle_on_train = EntityId::GetNull();
+                entity->scream_sound_id = OpenRCT2::Audio::SoundId::Null;
+                for (size_t i = 0; i < std::size(entity->peep); i++)
+                {
+                    entity->peep[i] = EntityId::GetNull();
+                }
+                entity->BoatLocation.SetNull();
+
+                res = GetObjectAsDukValue(_context, std::make_shared<ScVehicle>(entity->Id));
+            }
         }
         else if (type == "staff")
         {
```
If we instead fix create entity then we don't need to patch every single interaction with getting the vehicle.

**Comment by duncanspumpkin** [comment]
I've applied my suggested change and rebased this. We are now protected from creating invalid vehicles and also from invalid vehicles that have previously been created.

**Review by duncanspumpkin — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
Along the way i noticed that all the other entity create functions are probably also creating invalid entities. I would strongly suggest plugin authors do not use these functions at all as they are very easy to create invalid entities.

**Comment by Gymnasiast** [comment]
Still needs a changelog entry.
