### PR TITLE
Fix #13688: invalid access in editor_check_object_group_at_least_one_selected()

### LINKED ISSUE #13688: [73eca6] openrct2.exe: editor_check_object_group_at_least_one_selected, window_editor_bottom_toolbar_jump_forward_from_object...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/73eca6707e196525fc6c4305123b13914311754ed981be6821d7129c23ce01f4">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>D:\Users\donat\Documents\OpenRCT2\a8e69e10-5bcb-483a-8c84-bbff0632b22f.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>D:\Users\donat\Documents\OpenRCT2\a8e69e10-5bcb-483a-8c84-bbff0632b22f.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>D:\Users\donat\Documents\OpenRCT2\a8e69e10-5bcb-483a-8c84-bbff0632b22f.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>D:\Users\donat\Documents\OpenRCT2\screenshot\Unnamed park 2021-01-03 23-55-59.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>30aea2b</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
editor_check_object_group_at_least_one_selected
window_editor_bottom_toolbar_jump_forward_from_object_selection
InputStateWidgetPressed
GameHandleInputMouse
GameHandleInput
context_handle_input
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/EditorObjectSelectionSession.cpp [hunk 1]
```diff
@@ -611,13 +611,14 @@ bool window_editor_object_selection_select_object(uint8_t isMasterObject, int32_
 
 bool editor_check_object_group_at_least_one_selected(ObjectType checkObjectType)
 {
-    int32_t numObjects = static_cast<int32_t>(object_repository_get_items_count());
+    auto numObjects = object_repository_get_items_count();
```
Comment (duncanspumpkin) [inline src/openrct2/EditorObjectSelectionSession.cpp:614]: if you made this `std::min(object_repository_get_items_count(), _objectSelectionFlags.size())` then you don't need to add it to the other if. This feels like it will just cause the issue to crop up elsewhere though.

Comment (Gymnasiast) [reply src/openrct2/EditorObjectSelectionSession.cpp:614]: That would work, but it would also make the code harder to understand IMO.

I'm not too fussed either way, but I would like to hear from another team member.

Comment (ZehMatt) [reply src/openrct2/EditorObjectSelectionSession.cpp:614]: Its a bit long but logically speaking that should be preferred over adding a new condition in a loop.
