### PR TITLE
Fix #11068: segfault when trying to clear empty list

### LINKED ISSUE #11068: BACKTRACE c72198
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/c72198e264f03da89eeb2a461d3e096bafd4980aeccf62c1382e7fcc64056884?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Mar 26 2020 21:10:43)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Harrison\\Documents\\OpenRCT2\\97daa2b3-d898-4d48-bd4a-206717452b59.sv6.gz: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Harrison\\Documents\\OpenRCT2\\97daa2b3-d898-4d48-bd4a-206717452b59.ini: <em>1</em><br><strong>assert_failure:</strong> *: <em>1</em><br><strong>attachment_screenshot.png:</strong> C:\\Users\\Harrison\\Documents\\OpenRCT2\\screenshot\\Unnamed park 2020-03-26 21-10-43.png: <em>1</em><br><strong>commit:</strong> 4f6e77e: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_track_list_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> wmain</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by janisozaur**
The report in #11068 was using track designs manager with "Boat hire"
ride, for which there were no designs and selecting "Clear" button on
the list accessed empty vector in `_filteredTrackIds`.

screenshot(8)

### CODE REVIEW

File: src/openrct2-ui/windows/TrackList.cpp [hunk 1]
```diff
@@ -337,7 +337,10 @@ static void window_track_list_mouseup(rct_window* w, rct_widgetindex widgetIndex
             // Keep the highlighted item selected
             if (gScreenFlags & SCREEN_FLAGS_TRACK_MANAGER)
             {
-                w->selected_list_item = _filteredTrackIds[w->selected_list_item];
+                if (static_cast<ssize_t>(_filteredTrackIds.size() - 1) >= w->selected_list_item)
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/TrackList.cpp]: Why not drop the `- 1` and use `>` instead instead of `>=`?

Comment (Broxzier) [inline src/openrct2-ui/windows/TrackList.cpp]: Why is there a subtraction of 1? I may be missing something, but it looks like `_filteredTrackIds.size() > w->selected_list_item` would be sufficient here.

Comment (janisozaur) [reply src/openrct2-ui/windows/TrackList.cpp]: …

Because it's late :sweat_smile: .

Comment (janisozaur) [reply src/openrct2-ui/windows/TrackList.cpp]: I ended up improving the condition slightly, taking into account `w->selected_list_item` is sometimes set to -1 too.

https://github.com/OpenRCT2/OpenRCT2/blob/8351a0477d8d9c640e333b1342aa030eded4e209/src/openrct2-ui/windows/TitleEditor.cpp#L251

https://github.com/OpenRCT2/OpenRCT2/blob/8351a0477d8d9c640e333b1342aa030eded4e209/src/openrct2-ui/windows/ServerList.cpp#L149

https://github.com/OpenRCT2/OpenRCT2/blob/8351a0477d8d9c640e333b1342aa030eded4e209/src/openrct2/interface/Window_internal.h#L45
