### PR TITLE
Fix #4777. Check for enough free elements before placement

### LINKED ISSUE #4777: Placing large scenery objects can crash the game if the object limit is too close to the max
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** a934590

**Steps to reproduce:**
1. Load the BakerLake.sv6 file (I did not make this park, all credit goes to Coupon) 
2. Attempt to place the RamSam12 - 3 Flatride Arms - MT large scenery object (in the Miscellaneous Objects tab)
3. As soon as the game tries to render the ghost object, the game gives an assertion failed message.
**To my best guess,** this is because the game is too close to the object limit (this can be discovered by placing several small scenery obejcts in the map. In my experience it takes about 13 quarter tile scenery objects to fill up the remaining landscape data area). The game isn't yet at the object limit, so the game attempts to render the object, but it doesn't check of the amount of space left against the amount of space that object takes up.

**Save game:**
[BakerLake.zip](https://github.com/OpenRCT2/OpenRCT2/files/579537/BakerLake.zip)

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fix #4777. Check for enough free elements before placement of multi tiled elements

Previously multi tiled placements would only check for one free element before placing. This would cause a crash when it failed to allocate the next element on maps that were close to reaching their full capacity. Renamed sub_68B044 to map_check_free_elements_and_organise and gave it an argument value to check for enough free elements.

### CODE REVIEW

File: src/world/map.c [hunk 1]
```diff
@@ -3769,7 +3765,7 @@ void game_command_place_large_scenery(int* eax, int* ebx, int* ecx, int* edx, in
 
 		curTile.x += x;
 		curTile.y += y;
-
+
```
Comment (IntelOrca) [inline src/world/map.c]: whitespace

File: src/world/map.c [hunk 2]
```diff
@@ -3754,11 +3749,12 @@ void game_command_place_large_scenery(int* eax, int* ebx, int* ecx, int* edx, in
 		}
 	}
 
-
+	uint32 num_elements = 0;
```
Comment (marijnvdwerf) [inline src/world/map.c]: Why snake case?

Comment (duncanspumpkin) [inline src/world/map.c]: well its not consistent in the C files but the main reason is because i copied and pasted the variable name from the function description.
