### PR TITLE
Fix #16572: Crash Placing Track Designs Due to OOB Read on Research.cpp:554

### LINKED ISSUE #16572: Crash Placing Saved Track Designs Due to OOB Read on Research.cpp:554
### Operating System

Ubuntu

### OpenRCT2 build

v0.3.5.1

### Describe the issue

This index into a global array will be OOB when `rideEntryIndex` is `OBJECT_ENTRY_INDEX_NULL`, defined to be `0xFFFF`:

Screenshot_2022-02-02_17-26-17

Here is the bad index register at the time of the crash:

Screenshot_2022-02-02_17-49-03

`ride_entry_is_invented(...)` gets called by the `TrackDesignAction` command class in two places, `::Query()` and `::Execute()`. In both locations is this bizarre code:

Screenshot_2022-02-02_17-53-16

In fact, the code _only_ calls the is_invented function with null entry indexes. It then does nothing with information other than ... set the index to null, again. Maybe this fallback check was only supposed to happen if the index was _not_ null? I fixed my own build by just commenting out the redundant check in both member functions.

The null value only appears for certain combinations of coasters and scenarios, possibly due to differences in what objects are loaded in by scenario. I haven't looked into this further.

Reproducing the OOB value is easy (drop a bounds check assertion there and start placing coasters). Reproducing the crash is difficult due to the plurality of compile and run-time factors that affect your memory mapping and thus whether or not this offset will trigger a fault. My single player game has been crashing consistently for months now, which prompted me to find the cause.

I believe this may also be the cause of #16264, however I've never used multiplayer and do not know if this issue affects other connected clients in the manner so described. I recall seeing other reports of saved designs causing crashes as well and this bug may be the reason why.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. `assert( rideEntryIndex < MAX_RIDE_OBJECTS )` in `ride_entry_is_invented(...)`
2. Load the Woodstock map and select a saved Corkscrew Coaster design. The assert will fire as soon as your mouse hovers over the game area, where the track preview should appear. I believe it is necessary that the saved design's ride vehicle type not be available in the current scenario.
3. OpenRCT2 has crashed!

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/actions/TrackDesignAction.cpp [hunk 1]
```diff
@@ -137,10 +137,10 @@ GameActions::Result TrackDesignAction::Execute() const
 
     auto& objManager = OpenRCT2::GetContext()->GetObjectManager();
     auto entryIndex = objManager.GetLoadedObjectEntryIndex(_td.vehicle_object);
-    if (entryIndex == OBJECT_ENTRY_INDEX_NULL)
+    if (entryIndex != OBJECT_ENTRY_INDEX_NULL)
     {
-        // Force a fallback if the entry is not invented yet a td6 of it is selected,
-        // which can happen in select-by-track-type mode
+        // Force a fallback if the entry is not invented yet a track design using is selected.
```
Comment (pizza2004) [inline src/openrct2/actions/TrackDesignAction.cpp:142]:
```suggestion
        // Force a fallback if the entry is not invented yet a track design using it is selected.
```
