### PR TITLE
Fix #23484: Castle station styles are erroneously remappable

### LINKED ISSUE #23484: Castle station styles are erroneously remappable.
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

OpenRCT2 Release v0.4.17

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

Note that this is *not* an object specific issue as i've checked the object jsons for these and there's no issues there, so please do not move it to the objects repo. As this is an issue with station style rendering that will affect any station style, not just these.

The castle entrance styles (both brown and gray) have pixels on their roof piece that use the pink palette, and get remapped by the ride's second color as a result. This happens in vanilla RCT2 but *not* vanilla RCT1 so it's definitely not intended. Station styles probably should not remap the sprite colors if they don't explictly define that in their object json. (eg: abstract glass & canvas tent styles explictly enable remapping)

### Steps to reproduce

1. Build a ride with either castle station style
2. Change the second color and look closely, pixels on the castle roof change color.

### Attachments

Vanilla RCT1 (How it should look):
Image
Vanilla RCT2 (Note bright blue specks on the roof, Broken in 2002):
Image
OpenRCT2 (Still broken):
Image

### PR DESCRIPTION
**Pull request by Gymnasiast**
The drawing code always applied two or three remaps to the images. Changed it to actually read the correct number from the object.

### CODE REVIEW

**Comment by ZeeMaji** [comment]
Ghosts of station pieces don't display properly anymore with this PR. The non-remappable stations don't render as ghosts and the canvas tent station renders with black stripes.
ksnip_20250325-225712
ksnip_20250325-225657

File: src/openrct2/ride/TrackPaint.cpp [hunk 1]
```diff
@@ -708,14 +708,17 @@ bool TrackPaintUtilDrawStationCovers2(
         imageOffset += SPR_STATION_COVER_OFFSET_TALL;
     }
 
-    auto imageTemplate = session.TrackColours;
-    auto imageId = imageTemplate.WithIndex(baseImageIndex + imageOffset);
+    auto imageId = ImageId(baseImageIndex + imageOffset);
+    if (stationObject->Flags & StationObjectFlags::hasPrimaryColour)
```
Comment (duncanspumpkin) [inline src/openrct2/ride/TrackPaint.cpp:712]: to account for the trackcolours being ghost/highlighted you could check for `session.TrackColours.IsRemap()` that will only be set on ghost/highlight and if it is set then construct ImageId from the session.TrackColours.
```
if (session.TrackColours.IsRemap()){
    imageId = imageId.WithRemap(session.TrackColours.GetRemap());
}else{
    if (stationObject->Flags & StationObjectFlags::hasPrimaryColour){
    ....
}
```

**Comment by Gymnasiast** [comment]
I noticed another bug, also present on `develop`:

image

**Comment by Gymnasiast** [comment]
@ZeeMaji Could you re-test?

**Comment by ZeeMaji** [comment]
Will do.

**Review by ZeeMaji — APPROVED** [review]
All of the built in station styles render as expected both normally and as ghosts.
