### PR TITLE
Fix land tool clearance checks underneath maze track pieces

### LINKED ISSUE #25367: Hovering over a maze entrance while the terrain tool is open crashes the game
### Operating System

Arch Linux 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.27

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue, This issue has to do with park objects and/or asset packs

### Describe the issue

If you open the shovel tool and hover it over a maze entrance, the game crashes.

### Steps to reproduce

1. Create a maze in any park
2. Open the terrain tool
3. Hover the mouse over the entrance

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mixiate**
I forgot about this in #25032. Mazes reuse the track sequence index, this takes the minimum of the track sequence and the track element sequence count (1 for maze track piece) so that it doesn't look up the wrong thing.

I dont know whether this fixes #25367 or not. I can't reproduce a crash and the issue talks about entrances too which this shouldn't affect? Nonetheless this needs to be fixed anyway.

https://github.com/user-attachments/assets/3927ae7c-c8be-4da2-94d3-f26335864695

https://github.com/user-attachments/assets/a2b87807-f1fa-4d83-ba05-c3014c2e9684

Save, although this might not happen for you on the same piece:
[mazelandtoolbug.zip](https://github.com/user-attachments/files/22987712/mazelandtoolbug.zip)

### CODE REVIEW

**Comment by ZehMatt** [comment]
The client shouldn't send anything to the server when the query fails but I think its safer to go with a network bump to make sure.

File: src/openrct2/world/ConstructionClearance.cpp [hunk 1]
```diff
@@ -108,7 +108,9 @@ static bool MapLoc68BABCShouldContinue(
 
         const TrackElement* const trackElement = tileElement->AsTrack();
         const auto& ted = OpenRCT2::TrackMetaData::GetTrackElementDescriptor(trackElement->GetTrackType());
-        const auto& trackClearances = ted.sequences[trackElement->GetSequenceIndex()].clearance;
+        // mazes reuse the sequence index, take min of sequence index and track element sequence count
+        const uint8_t sequenceIndex = std::min<uint8_t>(trackElement->GetSequenceIndex(), ted.numSequences - 1);
+        const auto& trackClearances = ted.sequences[sequenceIndex].clearance;
```
Comment (Gymnasiast) [inline src/openrct2/world/ConstructionClearance.cpp]: This still feels hacky to me. We know the ID of the maze piece, so we can just make sure it’s set to `0` in that case.

```suggestion
        const uint8_t sequenceIndex = (trackElement->GetTrackType() == TrackElemType::maze) ? 0 : trackElement->GetSequenceIndex());
        const auto& trackClearances = ted.sequences[sequenceIndex].clearance;
```

Comment (mixiate) [reply src/openrct2/world/ConstructionClearance.cpp]: Thanks I really should have done this in the first place.
