### PR TITLE
Fix #10713: Correctly encode network ride id over network

### LINKED ISSUE #10713: Rides are disappeared when it is built in multiplayer
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 38907fd

Rides are disappears when build another rides. It doesn't matter it is a flat rides or track rides.
I think it is occured from 723f658. It is fine at df28bca

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Join any multiplayer server
2. Build any ride
3. Build another ride.

**Screenshots / Video:**

d

### PR DESCRIPTION
**Pull request by ZehMatt**
It byte swapped uint16_t and then during decode byte swapped it as uint32_t, now it always uses uint32_t for ride/player id. I could use the underlying type but that would require to re-create all replays again.

Closes #10713

### CODE REVIEW

File: src/openrct2/core/DataSerialiserTraits.h [hunk 1]
```diff
@@ -1,4 +1,4 @@
-/*****************************************************************************
+﻿/*****************************************************************************
```
Comment (IntelOrca) [inline src/openrct2/core/DataSerialiserTraits.h]: BOM?

Comment (ZehMatt) [reply src/openrct2/core/DataSerialiserTraits.h]: God damn Visual Studio
