### PR TITLE
Close #17050: Transparency can be toggled directly

### LINKED ISSUE #17050: Invisible button for vegetation does not work
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1-906-gdaeaa98 (daeaa98 on develop) provided by GitHub

### Describe the issue

See-through works as expected, but invisible does not work at all.

https://user-images.githubusercontent.com/2963232/165075225-f527056d-bd9e-4bd7-a262-5e12254d68e5.mp4

Related to #16797

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Start game
2. Go to transparency options
3. Press invisible button for vegetation as shown in video

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Broxzier**
When toggling on the transparency flag, it now also sets the see-through flag. When disabling the see-through flag, it clears the transparency flag.

I also took the opportunity to move some common code into member functions.

Before:

https://user-images.githubusercontent.com/2963232/165075225-f527056d-bd9e-4bd7-a262-5e12254d68e5.mp4

After:

~~https://user-images.githubusercontent.com/9705046/165490125-581dd009-7055-44d3-9b91-06ffac9d52af.mp4~~

https://user-images.githubusercontent.com/9705046/165505944-3496ffdc-f3e3-4de7-91c0-d3690b6038cf.mp4

### CODE REVIEW

File: src/openrct2-ui/windows/Transparency.cpp [hunk 1]
```diff
@@ -232,6 +243,23 @@ class TransparencyWindow final : public Window
...
+        gConfigGeneral.invisible_vehicles = wflags & VIEWPORT_FLAG_INVISIBLE_VEHICLES;
+        gConfigGeneral.invisible_trees = wflags & VIEWPORT_FLAG_HIDE_VEHICLES;
+        gConfigGeneral.invisible_scenery = wflags & VIEWPORT_FLAG_INVISIBLE_SCENERY;
+        gConfigGeneral.invisible_trees = wflags & VIEWPORT_FLAG_HIDE_SCENERY;
+        gConfigGeneral.invisible_trees = wflags & VIEWPORT_FLAG_INVISIBLE_VEGETATION;
+        gConfigGeneral.invisible_trees = wflags & VIEWPORT_FLAG_HIDE_VEGETATION;
+        gConfigGeneral.invisible_paths = wflags & VIEWPORT_FLAG_INVISIBLE_PATHS;
+        gConfigGeneral.invisible_trees = wflags & VIEWPORT_FLAG_HIDE_PATHS;
+        gConfigGeneral.invisible_supports = wflags & VIEWPORT_FLAG_INVISIBLE_SUPPORTS;
+        gConfigGeneral.invisible_trees = wflags & VIEWPORT_FLAG_HIDE_SUPPORTS;
```
Comment (IntelOrca) [inline src/openrct2-ui/windows/Transparency.cpp:260]: Some kind of copy and paste shenanigans going on here...

**Comment by IntelOrca** [comment]
While I can understand hiding the items if you click the eye. I don't know why you would want it to show the item when you unclick the eye.

The eye is there to toggle how you want it to hide it, it is not a substitute for actually hiding it. Otherwise you might as well have a 3-state button or radio.

**Comment by Broxzier** [comment]
> I don't know why you would want it to show the item when you unclick the eye.

With two buttons for a 3-type state, it's going to be awkward one way or another. Current behaviour on develop is essentially the fourth and invalid state. Always going from invisible to see-through when toggling off the eye is awkward when the state was fully visible before clicking the eye. Going from invisible to normal is awkward when the state was see-though before clicking the eye.

We could add something that remembers the state from before the eye was pressed, but that can get ugly when the user changes things with hotkeys too.

**Comment by IntelOrca** [comment]
I replicated the behaviour from OpenTTD, that is certainly what I am used to. I don't think the eye is something users will change much - once they have set what they prefer most, they shouldn't be changing it again. The shortcuts are just for whether to hide or not, not set the way it is hidden. You can think of this more as an option window rather than a toolbar, but it acts as a toolbar as well if you just concentrate on the image buttons.

Flipping the eye state makes it clear what that is actually changing; the way it hides the item.

**Comment by Broxzier** [comment]
New behaviour:

https://user-images.githubusercontent.com/9705046/165505944-3496ffdc-f3e3-4de7-91c0-d3690b6038cf.mp4

**Comment by IntelOrca** [comment]
@Broxzier I happy with the new behaviour

**Review by IntelOrca — APPROVED** [review]

**Comment by Umdlye** [comment]
I just used this new window for the first time without having read this discussion and without having played OpenTTD before, and wanted to share my experiences with it.

I first clicked the button labeled "see-through vegetation" which toggled the transparency on and off as expected. I then tried the eye button below it labeled "invisible vegetation". Clicking it made the trees invisible as expected, but clicking it again (expecting it to make them visible again) just made them transparent, so I had to click the button above it to make them fully visible again and thought that was not very intuitive.

I then noticed that clicking the "see-through" button with the "invisible" button toggled left the "invisible" button on while the objects weren't invisible at all, so I was about to report this as a bug when I read this discussion saying this window mimics the OpenTTD version. It wasn't until I downloaded OpenTTD to try their version of the window out that I realized that the OpenRCT2 behavior wasn't a bug at all but that they're intended to be toggles for the main button's behavior.

In OpenTTD this is communicated more clearly by having the tooltips of the invisibility toggles say exactly what they do ("set objects invisible instead of transparent" instead of "invisible <type>") and by not actually enabling transparency yet when this toggle is used. If the goal here is to replicate the OpenTTD window, wouldn't it be better to do those things as well?
