### PR TITLE
Fix #5449: Underflow of gNumGuestsHeadingForPark in SC4 import

### LINKED ISSUE #5449: Guests not attracted to Funtopia
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.8]
**Commit/Build:** [e.g. f2debce]

Closing and reopening Funtopia does not replenish guests. (I did this so I could get money from entrance fees.)
This occurs in multiplayer and singleplayer.
Also for some reason in multiplayer, you can't set prices for any rides (not helping the money situation).
I even tried modifying the existing rollercoasters in case guests are attracted to rides under construction. - This didn't seem to do anything either.

- [No] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer?

**Steps to reproduce:**
1. Close park
2. Close all rides
3. Set entrance fee to £20
4. Build some rides if you like
5. Re-open everything
The only way I can get guests to enter the park is with an advertising campaign then I'm maxed out on loan.

**Screenshots / Video:**
funtopia

**Save game:**
[Funtopia.zip](https://github.com/OpenRCT2/OpenRCT2/files/981735/Funtopia.zip)

### PR DESCRIPTION
**Pull request by rwjuk**
gNumGuestsHeadingForPark wasn't being set during SC4 import. Therefore, when the game decremented the value when guests entered the park, it underflowed, causing major issues with guest generation.

(I'm assuming this doesn't need a network version increment as the only change is at import time?)

### CODE REVIEW

File: src/openrct2/rct1/S4Importer.cpp [hunk 1]
```diff
@@ -1417,9 +1417,16 @@ class S4Importer final : public IParkImporter
 
         peep_update_name_sort(dst);
 
-        if (!dst->outside_of_park && dst->type == PEEP_TYPE_GUEST)
+        if (dst->type == PEEP_TYPE_GUEST)
         {
-            gNumGuestsInPark++;
+            if (dst->outside_of_park && !(dst->state == PEEP_STATE_LEAVING_PARK))
```
Comment (IntelOrca) [inline src/openrct2/rct1/S4Importer.cpp]: `dst->state !=`

Comment (rwjuk) [inline src/openrct2/rct1/S4Importer.cpp]: Fixed... not sure what I was thinking there!
