### PR TITLE
Fix #13250. Crash when opening parks with new ride types

### LINKED ISSUE #13250: [2bb699] openrct2.exe: track_paint, sub_68B3FB, paint_session_generate, window_main_paint, window_draw_single, window_draw_co...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/2bb6995abdfb71fef7d524a07055077ca1e645669f1e2bf130e12a4068f9ebb7">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\aroberts\Documents\OpenRCT2\21146cea-e16e-4ed8-b2c1-f18a85060516.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\aroberts\Documents\OpenRCT2\21146cea-e16e-4ed8-b2c1-f18a85060516.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\aroberts\Documents\OpenRCT2\screenshot\Sjleme Mountain Park 2020-10-19 19-44-08.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>d01dcea</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
track_paint
sub_68B3FB
paint_session_generate
window_main_paint
window_draw_single
window_draw_core
window_draw
std::_Func_impl_no_alloc&lt;&lt;lambda_c6239a5f162a90c22f819d59f2036264&gt;,void,rct_window *&gt;::_Do_call
window_visit_each(std::function&lt;void __cdecl
window_draw_all
WindowManager::SetMainView
game_load_init
OpenRCT2::Context::LoadParkFromStream
OpenRCT2::Context::LoadParkFromFile
context_load_park_from_file
game_load_or_quit_no_save_prompt_callback
window_loadsave_select
window_loadsave_scrollmousedown
input_scroll_begin
input_widget_left
game_handle_input_mouse
game_handle_input
context_handle_input
OpenRCT2::Context::Update
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by duncanspumpkin**
This only happens when a new ride type is added and the park is opened in the older version of the game where the ride type does not exist.

These changes will prevent it from instantly crashing on open. You still might crash if peeps are queuing or mechanics are fixing. I'm also thinking of adding additional protection so that it just deletes the ride on load.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Still need to add a warning.

File: src/openrct2/Game.cpp [hunk 1]
```diff
@@ -427,6 +427,20 @@ void game_convert_strings_to_rct2(rct_s6_data* s6)
...
+{
+    for (ride_id_t i = 0; i < RIDE_ID_NULL; ++i)
+    {
+        auto* ride = get_ride(i);
+        if (ride == nullptr || ride->type < RIDE_TYPE_COUNT)
+        {
+            continue;
+        }
+        reset_sprite_spatial_index();
+        ride_action_modify(ride, RIDE_MODIFY_DEMOLISH, GAME_COMMAND_FLAG_APPLY);
```
Comment (ZehMatt) [inline src/openrct2/Game.cpp:440]: This will network the action, is this supposed to happen? Its better to add GAME_COMMAND_FLAG_NO_SPEND otherwise its networked/queued and has side effects money wise.

Comment (AaronVanGeffen) [reply src/openrct2/Game.cpp:440]: Hmm. If the network versions don't match, you can't connect anyway, right? But it sounds like the fix could be applied twice in such a case?

Comment (duncanspumpkin) [reply src/openrct2/Game.cpp:440]: I'm thinking of just making it so that you can't open the parks instead.

Comment (Broxzier) [reply src/openrct2/Game.cpp:440]: My two cents would be to just not load the park and tell the user they may need to update OpenRCT2 in order to load the park.

Comment (tupaschoal) [reply src/openrct2/Game.cpp:440]: I'm with @Broxzier , it's a little nudge to use something newer

**Comment by duncanspumpkin** [comment]
Urgh the loading code is all sorts of wonky. If something fails to load the game half loads it unless it is opening the title screen in which case it tries to reload the title screen?! Think thats back to front. Also if the game fails to load an error message is created with a specific error. This error message is then removed and replaced by a generic error.

**Comment by duncanspumpkin** [comment]
Okay I've messed about with the loading the code so that it now does what I would expect. I think we really need to refactor all of this as its a mess of try's and catches at different levels. I've had to duplicate the title_load call a bunch of times as it needs to happen prior to sending the error message as otherwise the error message will be wiped when title_load is called.

File: data/language/en-GB.txt [hunk 2]
```diff
@@ -3651,6 +3651,7 @@ STR_6394    :Objective
 STR_6395    :Maintenance
 STR_6396    :Disable screensaver and monitor power saving
 STR_6397    :{SMALLFONT}{BLACK}If checked, screensaver and other monitor power saving features will be inhibited while OpenRCT2 is running.
+STR_6398    :File contains unsupported ride types. Please Update.
```
Comment (Gymnasiast) [inline data/language/en-GB.txt:3654]:
```suggestion
STR_6398    :File contains unsupported ride types. Please update to a newer version of OpenRCT2.
```

**Comment by AaronVanGeffen** [comment]
What's the status of this?

**Comment by duncanspumpkin** [comment]
I was waiting for further reviews and agreement that my changes are okay

**Review by tupaschoal — COMMENTED** [review]
Looks ok, though I thought we would just not load the park at all

**Comment by duncanspumpkin** [comment]
It doesn't load the park but i also added some protection code as well so that if you do override it it wont crash immediately

**Review by Gymnasiast — COMMENTED** [review]
Code looks OK to me (haven't taken a look at it extensively), but would like the warning message to be changed.

**Comment by duncanspumpkin** [comment]
string is updated.

**Review by Gymnasiast — APPROVED** [review]
