### PR TITLE
Fix #13567: Added ability for peeps to stop eating certain food constanly

### LINKED ISSUE #13567: several bugs with food and drink
**OS:** Windows10
**Version:** 0.3.2-196
**Commit/Build:** f09b14e

1. Guests buy multiple food or drink.
ex) Guests buy a cup of sujeonggwa even though they already have a sandwich. 

2. Only the last one actually functions. 
ex) If a guest buys a sandwich when he has a cup of hot chocoate already, only the hunger level goes down not thirsty even though both a sandwich and a cup of hot chocolate exist on his inventory.

4. Food and drink in the list of inventory of guests will never disappear. 
ex) All guests who have drink or food are sitting on the bench forever.  

**Steps to reproduce:**
1. Build any food stall or drink stall
2. Create guests and make them hungry or thirsty so that they buy something

**Screenshots / Video:**
미개척된 숲 2020-12-09 23-22-20
미개척된 숲 2020-12-09 23-22-56
As you can see, Iain C has been sitting for over an year.

미개척된 숲 2020-12-10 20-14-14
Guests buy multiple food or drink.

제목 없음
The stalls with bugs 
( +Chicken nuggets stall)

sorry for my terrible english :)

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fix #13567: Added ability for peeps to stop eating certain food constanly

Incorrect assumption that bitscanforward iterated over 64 bits meant that food that was previously within the ExtraItemFlags would never get removed from the peeps inventory. bitscanforward function has been replaced with a 64bit version

### CODE REVIEW

**Review by IntelOrca — APPROVED** [review]

**Review by tupaschoal — COMMENTED** [review]
The 32-bit win build is complaining

File: src/openrct2/util/Util.cpp [hunk 1]
```diff
@@ -172,12 +172,34 @@ int32_t bitscanforward(int32_t source)
...
     return success - 1;
 #else
-#    pragma message "Falling back to iterative bitscan forward, consider using intrinsics"
+#    pragma message("Falling back to iterative bitscan forward, consider using intrinsics")
     // This is a low-hanging optimisation boost, check if your compiler offers
     // any intrinsic.
     // cf. https://github.com/OpenRCT2/OpenRCT2/pull/2093
     for (int32_t i = 0; i < 32; i++)
-        if (source & (1u << i))
+        if (source & (1ull << i))
```
Comment (Gymnasiast) [inline src/openrct2/util/Util.cpp:180]: Is it necessary to also change the 32-bit version?

Comment (duncanspumpkin) [reply src/openrct2/util/Util.cpp:180]: It's not really necessary is because I thought i could get rid of the 32 bit version but realised it would prevent optimisations on x86-32

Comment (IntelOrca) [reply src/openrct2/util/Util.cpp:180]: Why are you casting to a 64-bit type in the 32-bit version?
