### PR TITLE
Fix #4013: Scroll bar can get tiny for extremely long lists

### LINKED ISSUE #592: Very long object list cannot be scrolled
Since my RCT2 was ten years old when I copied it to OpenRCT2, it should be no surprise I have accumulated a ludicrous amount of plug-in objects (my ObjData contains nearly 7000 files, including the original RCT2 ones). This makes the list of Small Objects in the Scenario Editor so long it's not scrollable any more.

This bug is present in both vanilla RCT2 and OpenRCT2.
(Since I'm probably the only one crazy enough to test OpenRCT2 with a setup like this, I sometimes seem to catch bugs that are hard to reproduce. So if you need a copy of my (1.4 GB) setup, I can provide it.)

### LINKED ISSUE #4013: Scroll bar can get tiny for extremely long lists
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.4

For windows with lists (like the list of attractions), you have a scroll bar. But the “bar” which you can click and drag can get tiny if the list is very long, making it hard (but not impossible) to click. This easily happens in the guest list with over 1000 guests.

- Reproducible in RCT2 (vanilla)? Yes, this is originally a RCT2 flaw, OpenRCT should not copy it IMO.
- Multiplayer? N/A

**Steps to reproduce:**
 1. Play a game with a park with over 1000 guests
 2. Open the guets list
 3. Look at the scroll bar

A simple fix for this would be to force a more useful minimum size of the “bar”, not just 1 or 2 pixels. The bar should never get smaller than this mimium size, no matter how large the list. It could still be small but it should be just large enough that it is less annoying to click on it. :-)

### PR DESCRIPTION
**Pull request by gDanix**
WARNING: This is not a 'real' solution, but a hack with the drawing parameters to have bigger scrollbars when the list being scrolled is too large.

Because of that, the scrollbar moves slightly slower than the mouse pointer actually do, so the pointer will ended up pointing ahead the scrollbar.

This would better implemented while rewriting UI system.

Currently, only vertical scrollbars are implemented. If this hack is approved, then the horizontal bars can be implemented before merge.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This is not a fix for #592, but for #4013 by the look of it.

File: src/interface/widget.c [hunk 1]
```diff
@@ -91,7 +93,16 @@ void widget_scroll_update_thumbs(rct_window *w, int widget_index)
 		y += 11;
 		view_size += 10;
 		scroll->v_thumb_bottom = min(y, view_size);
+
+		if(scroll->v_thumb_bottom - scroll->v_thumb_top < 20) {
+			double percent = (scroll->v_thumb_bottom*1.0)/view_size;
+			printf("percent: %f\n", percent);
```
Comment (Gymnasiast) [inline src/interface/widget.c]: I think you accidentally left this in.

Comment (gDanix) [inline src/interface/widget.c]: Yes, but this is only a draft. If this is approved, then I'll do the same for the horizontal scrollbar and some code cleaning

**Comment by gDanix** [comment]
@Gymnasiast Sorry, I thought it was because #4013 was marked as a duplicate of #592.

If this isn't really a fix for #592, I must change the name to avoid Github autoclosing #592, when it really didn't get fixed.

**Comment by Gymnasiast** [comment]
That was because Duncan only read the issue title and didn't pay attention to what #592 was actually about. If you read both issues it's very easy to see they're totally different issues.

**Comment by Gymnasiast** [comment]
Is this finished?

**Comment by gDanix** [comment]
I couldn't test the horizontal scrollbar because I wasn't able to find a window with such a small horizontal scrollbar, but the code is very simple and is equivalent to the vertical scrollbar code, so I can not find why this should not work

**Comment by janisozaur** [comment]
> I can not find why this should not work

Famous last words ;)

**Comment by gDanix** [comment]
@janisozaur true. In fact if there is no window with such a horizontal space, we can revert the untested change in horizontal scrollbar (diff lines 76-82)

**Comment by Gymnasiast** [comment]
You can leave it as it is. It's more consistent this way and not likely to cause problems.
I'll try to test it tonight.
