### PR TITLE
Fix #21330: Tooltips from dropdown widgets have the wrong position

### LINKED ISSUE #21330: Tooltip text in Color Chooser jumps
### Operating System

Window 10

### OpenRCT2 build

OpenRCT2, v0.4.8 (05efdb2) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When choosing a color in the color chooser, the tooltip text displaying the color's name flashes and jumps around on the screen. The tooltip briefly appears in the correct location, then flickers and is displayed where the mouse was clicked instead of the hovering position of the cursor.

### Steps to reproduce

Build a new attraction, change a color option in "Color scheme options".

### Attachments

scr1

### PR DESCRIPTION
**Pull request by ZehMatt**
The issue is that tooltips from dropdowns are handled different than tooltips from hovering over the items, this now properly updates the position and follows the mouse like its supposed to.

Closes #21330

### CODE REVIEW

File: src/openrct2-ui/input/MouseInput.cpp [hunk 1]
```diff
@@ -1463,6 +1463,11 @@ void InputStateWidgetPressed(
         }
         return;
     }
+    else if (_inputState == InputState::DropdownActive && gDropdownIsColour)
```
Comment (tupaschoal) [inline src/openrct2-ui/input/MouseInput.cpp:1466]:
```suggestion
    else if (gDropdownIsColour)
```

It can only be `DropdownActive`, since the `if` above covers all other cases, no?

Comment (ZehMatt) [reply src/openrct2-ui/input/MouseInput.cpp:1466]: I find the inverted logic hard to read, I'll change it maybe someone can refactor that afterwards and do it the other way around.

**Review by tupaschoal — APPROVED** [review]

**Review by Gymnasiast — APPROVED** [review]
