### PR TITLE
Fix #8947: Detection of AVX2 support.

### LINKED ISSUE #8947: BACKTRACE dac250
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/dac25008c5d91da40daf95a4b7ef1f75e5bfab4ceece09caa332f3042f029873?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique errors: [openrct2]</b></a><br /><b>4</b> occurrence(s) <b></b> since (Sat Mar 23 2019 14:49:44)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.EXE</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_screenshot.png:</strong> C:\\Users\\Administrator\\Documents\\OpenRCT2\\screenshot\\The Bayou by Cocoa 2019-03-23 23-53-31.png: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\screenshot\\The Bayou by Cocoa 2019-03-23 23-51-25.png: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\screenshot\\The Bayou by Cocoa 2019-03-23 23-49-46.png: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\screenshot\\The Bayou by Cocoa 2019-03-23 23-49-57.png: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Administrator\\Documents\\OpenRCT2\\b8f63561-ef58-4dac-ba90-257ddc512d9d.ini: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\914be9d0-da37-4e05-a91c-c67b61fe8fde.ini: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\37da6fe6-b8d8-459c-9a36-53ce3cb139d8.ini: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\b160c12a-bdb1-4c1c-9ff9-91ec9f951a0a.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Administrator\\Documents\\OpenRCT2\\b8f63561-ef58-4dac-ba90-257ddc512d9d.sv6.gz: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\914be9d0-da37-4e05-a91c-c67b61fe8fde.sv6.gz: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\37da6fe6-b8d8-459c-9a36-53ce3cb139d8.sv6.gz: <em>1</em>, C:\\Users\\Administrator\\Documents\\OpenRCT2\\b160c12a-bdb1-4c1c-9ff9-91ec9f951a0a.sv6.gz: <em>1</em><br><strong>commit:</strong> fef7a4a: <em>4</em><br><strong>attachment_park.sv6:</strong> *: <em>4</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>ill</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>mask -> gfx_draw_sprite_raw_masked_software -> OpenRCT2::Drawing::X8DrawingContext::DrawSpriteRawMasked -> paint_draw_struct -> window_editor_main_paint -> window_draw -> window_draw_all -> WindowManager::SetMainView -> TitleSequencePlayer::PrepareParkForPlayback -> TitleSequencePlayer::LoadParkFromStream -> TitleSequencePlayer::ExecuteCommand -> TitleSequencePlayer::Update -> OpenRCT2::TitleScreen::TryLoadSequence -> OpenRCT2::TitleScreen::Load -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by ZehMatt**
The comment had it right all along.

### CODE REVIEW

File: src/openrct2/util/Util.cpp [hunk 1]
```diff
@@ -223,18 +223,26 @@ bool sse41_available()
 bool avx2_available()
 {
 #ifdef OPENRCT2_X86
-// For GCC and similar use the builtin function, as cpuid changed its semantics in
-// https://github.com/gcc-mirror/gcc/commit/132fa33ce998df69a9f793d63785785f4b93e6f1
-// which causes it to ignore subleafs, but the new function is unavailable on Ubuntu's
-// prehistoric toolchains
+    // For GCC and similar use the builtin function, as cpuid changed its semantics in
+    // https://github.com/gcc-mirror/gcc/commit/132fa33ce998df69a9f793d63785785f4b93e6f1
+    // which causes it to ignore subleafs, but the new function is unavailable on Ubuntu's
```
Comment (Gymnasiast) [inline src/openrct2/util/Util.cpp]: Time to change this unprofessional comment (if it even still applies).

Comment (ZehMatt) [reply src/openrct2/util/Util.cpp]: I have really no idea what this is about, I believe this was from @janisozaur

Comment (Gymnasiast) [reply src/openrct2/util/Util.cpp]: Who else would write comments like this?

It would have been half-informative if it had mentioned the GCC version that was needed, but it seems sh*tting on Ubuntu was more important.

Comment (ZehMatt) [reply src/openrct2/util/Util.cpp]: Well shit happens, lets try to keep it civil. Should I ditch the comment?

Comment (AaronVanGeffen) [reply src/openrct2/util/Util.cpp]: I think this still applies to Ubuntu 18.04 as well, so the comment should stay.

Personally, I'm not too bothered by the "prehistoric toolchain" comment, but feel free to replace that particular line with something more neutral.

Comment (Gymnasiast) [reply src/openrct2/util/Util.cpp]:
```diff
-but the new function is unavailable on Ubuntu's prehistoric toolchains
+but the new function is unavailable on Ubuntu 18.04's toolchains.
```

**Comment by Gymnasiast** [comment]
One minor nitpick: commit messages should not end with a full stop (`.`).

**Comment by ZehMatt** [comment]
I believe I did quite a few times, I'll avoid in the future.

File: src/openrct2/util/Util.cpp [hunk 2]
```diff
@@ -223,18 +223,26 @@ bool sse41_available()
...
     if (cpuid_x86(regs, 7))
     {
-        return (regs[1] & (1 << 5));
+        bool avxCPUSupport = (regs[1] & (1 << 5)) != 0;
+        if (avxCPUSupport)
+        {
+            // Need to check if OS also supports the register of xmm/ymm
+            // This check has to be conditional, otherwise INVALID_INSTRUCTION exception.
+            uint64_t xcrFeatureMask = _xgetbv(_XCR_XFEATURE_ENABLED_MASK);
+            avxCPUSupport = (xcrFeatureMask & 0x6) || false;
```
Comment (janisozaur) [inline src/openrct2/util/Util.cpp]: `(val || false) == val`

**Comment by IntelOrca** [comment]
@janisozaur what if that link were to break? It is a valid suggestion to mention the toolchains within the comment.

**Comment by janisozaur** [comment]
I don't disagree with that, however the links are still valid as of now and point to exact affected versions. @Gymnasiast explicitly updated the contents with wrong information.
