### PR TITLE
Refactor inspection interval and fix bugs

### LINKED ISSUE #24126: Fix desync when setting default inspection interval for ride
As this setting will be different per user, it needs to be passed via a parameter.

### LINKED ISSUE #25601: Inspection interval of a ride gets reset to default if its construction window gets brought up
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

v0.4.28

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

If you set the inspection interval of a ride to something other than the default 30 minutes and then open the construction window (be it a flat or a tracked ride), the interval will be reset to the default when the window gets closed. The culprit seems to be this line: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/RideConstruction.cpp#L326

### Steps to reproduce

1. Set the inspection interval of a ride to something other than 30 minutes
2. Open the construction window for that ride
3. Close it
4. Notice the inspection interval will be back to 30 minutes

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
Fixes #24126.
Fixes #25601.

Since this touches desyncs, I tagged @janisozaur as he asked for that.

### CODE REVIEW

File: src/openrct2/actions/RideCreateAction.cpp [hunk 1]
```diff
@@ -70,7 +72,7 @@ namespace OpenRCT2::GameActions
         GameAction::Serialise(stream);
 
         stream << DS_TAG(_rideType) << DS_TAG(_subType) << DS_TAG(_entranceObjectIndex) << DS_TAG(_trackColourPreset)
-               << DS_TAG(_vehicleColourPreset);
+               << DS_TAG(_vehicleColourPreset) << DS_TAG(_inspectionInterval);
     }
 
     Result RideCreateAction::Query(GameState_t& gameState) const
```
Comment (janisozaur) [inline src/openrct2/actions/RideCreateAction.cpp:78]: Add validation in here - I suppose careless plugins could set it to unexpected values and we do verify it in RideSetSetting as well

File: src/openrct2/rct2/RCT2.h [hunk 2]
```diff
@@ -260,7 +261,7 @@ namespace OpenRCT2::RCT2
         uint8_t unreliabilityFactor; // 0x198
         // Range from [0, 100]
         uint8_t downtime;                                      // 0x199
-        uint8_t inspectionInterval;                            // 0x19A
+        RideInspection inspectionInterval;                     // 0x19A
```
Comment (duncanspumpkin) [inline src/openrct2/rct2/RCT2.h]: Revert. In general you should be using the uint8_t type for the rct2/1 headers and you should be validating the conversion into RideInspection to ensure invalid values aren't there. (although saying that we don't normally actually do the validation)

File: src/openrct2/rct1/RCT1.h [hunk 3]
```diff
@@ -381,7 +382,7 @@ namespace OpenRCT2::RCT1
         };
         uint8_t unreliabilityFactor;                    // 0x148
         uint8_t downtime;                               // 0x149
-        uint8_t inspectionInterval;                     // 0x14A
+        RideInspection inspectionInterval;              // 0x14A
```
Comment (duncanspumpkin) [inline src/openrct2/rct1/RCT1.h]: Revert

**Review by janisozaur — APPROVED** [review]
