### PR TITLE
Fix #14337: Guest blocking ride entrance after ride price changed to be unaffordable

### LINKED ISSUE #14337: Guest blocking ride entrance after ride price changed to be unaffordable
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 3f65f28

When a guest is waiting at the entrance for another guest, at a ride that takes 2 people per vehicle, and while he waits the ride price changes to something he can't afford, he'll turn around but not leave the station, continuously check his wallet, and "I can't afford [ride name]" will flicker in his "recent thoughts". The guest will prevent others from entering the ride.

I first saw this when using the plugin "Ride price manager" on 0.3.3, but as described seen below, it can be reproduced without the plugin. I never encountered the isue using the plugin on 0.3.2 during many hours of play, but twice on 0.3.3 within ~10 hours, so it's probably new.

- [ ] Reproducible in RCT2 (vanilla)? 
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start a new level
2. Set initial cash to something low in order to get poor guests in
3. Build a boat hire or dinghy ride (issue confirmed on these two, but probably works for ghost train, car ride and others), and set a low ticket price
4. Wait until one guest stands inside the station, awaiting another in order to fill up a vehicle/boat
5. Change ride price to something this guest can no longer afford
6. Wait a bit, issue doesn't crop up immediately. I don't know if it's triggered by a rich guest wanting to get on, by a time delay, or something else, but it started within a minute for me in the saved file

**Screenshots / Video:**
Ride price bug

**Save game:**
[Ride price bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/6151872/Ride.price.bug.zip)

### PR DESCRIPTION
**Pull request by rik-smeets**
Resolves #14337.

### CODE REVIEW

File: src/openrct2/entity/Guest.cpp [hunk 1]
```diff
@@ -2617,7 +2617,13 @@ static bool peep_check_ride_price_at_entrance(Guest* peep, Ride* ride, money32 r
 
     if (ridePrice > peep->CashInPocket)
     {
-        peep->InsertNewThought(PeepThoughtType::CantAffordRide, peep->CurrentRide);
+        // Prevent looping of same thought / animation since Destination Tolerance
+        // is only 0 exactly at entrance and will immediately change as guest
+        // tries to leave hereafter
+        if (peep->DestinationTolerance == 0)
```
Comment (duncanspumpkin) [inline src/openrct2/entity/Guest.cpp:2623]: This is only changing the thought generation so ultimate does nothing different.

Comment (rik-smeets) [reply src/openrct2/entity/Guest.cpp:2623]: This thought is paired with an animation. Since this code is continuously called, the guest became stuck in said animation so it wouldn't ever leave the queue.

This change prevents the endless loop, resolving the issue. You can test that it works with the save file as provided in the issue.

**Comment by duncanspumpkin** [comment]
It feels wrong but its probably the best solution. Can you bump the network version.

**Comment by rik-smeets** [comment]
@duncanspumpkin Just bumped the network version.

**Review by duncanspumpkin — APPROVED** [review]
