### PR TITLE
Fix #19906: Destructible cheat does not allow ride modification

### LINKED ISSUE #19906: Unable to edit a pre-existing rollercoaster
### Operating System

Windows 10 64 bits

### OpenRCT2 build

OpenRCT2, v0.4.4 (9e4918c) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

In scenarios with pre-existing rollercoasters that you cannot remove, the ride cheat "All destructible" allows me you delete the ride, but I cannot edit it, for instance removing a piece track.
It happens in every scenario with pre-built rides like Dragon's Cove, Dusty Desert, etc.

### Steps to reproduce

1. Open a scenario such as Dragon's Cove.
2. Enable "All destructible" ride cheat.
3. Try to remove a piece of track of any coaster.

### Attachments

rct2-bug

### PR DESCRIPTION
**Pull request by Chase-Percy**
- Fixes the all-destructible cheat issue GH-19906.
- Adds a variable to represent if the indestructible flags should be ignored.
- Remove the old function that altered the flags on all the rides.
- Makes the cheat toggleable, but I'm not sure if this is desired.
- Added serialization and deserialization for the new cheat variable.

### CODE REVIEW

File: src/openrct2/actions/TrackRemoveAction.cpp [hunk 1]
```diff
@@ -114,7 +114,7 @@ GameActions::Result TrackRemoveAction::Query() const
         return GameActions::Result(GameActions::Status::InvalidParameters, STR_RIDE_CONSTRUCTION_CANT_REMOVE_THIS, STR_NONE);
     }
 
-    if (tileElement->AsTrack()->IsIndestructible())
+    if (tileElement->AsTrack()->IsIndestructible() && !gCheatsMakeAllDestructible)
```
Comment (tupaschoal) [inline src/openrct2/actions/TrackRemoveAction.cpp:117]: Maybe the `isIndestructible` function itself should check the cheat?

**Review by tupaschoal — COMMENTED** [review]
> Makes the cheat toggleable, but I'm not sure if this is desired.

I'd say yes, but then maybe it also needs to be come a checkbox on the cheats window, instead of a button, since no button is togglable there.

File: src/openrct2/actions/TrackRemoveAction.cpp (hunk 1 above)
Comment (Chase-Percy) [reply src/openrct2/actions/TrackRemoveAction.cpp]: Yup makes sense, [80eb038](https://github.com/OpenRCT2/OpenRCT2/pull/19924/commits/80eb038c24e20cb9dc01e4e2a52b4374b4c2a429)

**Comment by Chase-Percy** [comment]
> > Makes the cheat toggleable, but I'm not sure if this is desired.
> 
> I'd say yes, but then maybe it also needs to be come a checkbox on the cheats window, instead of a button, since no button is togglable there.

Nice, yea makes it a lot cleaner: [8d83676](https://github.com/OpenRCT2/OpenRCT2/pull/19924/commits/8d8367686c8ee0b3edd6a3b5c52b4861af94810c)

**Review by tupaschoal — COMMENTED** [review]
I've tested it and it works great, with the added benefit of being able to restore no "non-destructible" and a bonus of having the ride tab of cheats with symmetrical buttons at the top now :D

image

Can you please add a changelog entry under https://github.com/OpenRCT2/OpenRCT2/blob/60ac375e31d86dbd5b5ca7d10803dfd84cfb3fd5/distribution/changelog.txt ?

@OpenRCT2/developers do you think we should bump the network version on? I mean, people can have different cheat behavior on multiplayer, but it's not like it's game breaking, so I'm inclined not to.

PS: If we decide to bump the network verison it will be her: https://github.com/OpenRCT2/OpenRCT2/blob/60ac375e31d86dbd5b5ca7d10803dfd84cfb3fd5/src/openrct2/network/NetworkBase.cpp#L46

**Comment by ZehMatt** [comment]
The PR looks fine but it does need to bump up the park version and network version, the cheat is saved inside the park file so that needs a save version bump, and the logic was changed for game actions so we need a network bump. Thanks for the PR also.

**Comment by Chase-Percy** [comment]
- Added the changelog info: [426b499](https://github.com/OpenRCT2/OpenRCT2/pull/19924/commits/426b499235414e443cc6cb2daf1ee5db3e1773dd)
- Added my name to contributors under fixes: [dc9aa67](https://github.com/OpenRCT2/OpenRCT2/pull/19924/commits/dc9aa67d3a5cd17dba9e0768cb77d3153f3f80ae)
- Increased the network version (10 -> 11): [8502d32](https://github.com/OpenRCT2/OpenRCT2/pull/19924/commits/8502d3207870ba2d1877d563553f88105a589d58)
- Increased the park save versions (27 -> 28): [f5c0db5](https://github.com/OpenRCT2/OpenRCT2/pull/19924/commits/f5c0db5846c1b812c8e3757250cbbf6b21c883e9). I also increased the min compatible version since old saves that used the cheat altered the rides flags which had no option to undo it.

Let me know if there is anything else I need to tidy up, thanks!

**Review by tupaschoal — APPROVED** [review]

**Comment by tupaschoal** [comment]
Thank you!
