### PR TITLE
Fix #6804: Network permissions are not visible.

### LINKED ISSUE #6804: Multiplayer Permissions are not visible / no checks visible
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [40cea0e]

The permissions for every group are not visble for me. It doesnt matter which group, no group has any permission , even host or admin has no permission.

The permissions are working , **only the function to build multiple trees at same time is not working for me**. It should work because i have the permission for it.

- [ ] Reproducible in RCT2 (vanilla)?
- [ X ] Multiplayer?

**Screenshots / Video:**

sunny swamps remastered 2017-12-09 16-43-47

### LINKED ISSUE #7028: Permission Denied in Scenery Cluster when permission is enabled in any rank
**OS: Windows 10 Home x64 Build 1709**
**Version: 0.1.2-28**
**Commit/Build: 3ba0cc3**

Hello, one of my mods tried to enable scenery cluster for something and he gets permission denied message when he tries to enable scenery cluster in my server. The cluster permission is checked in the moderator group when this was happening.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Join my server for testing purpose.
2. Try enabling scenery cluster to see if you are getting the same bug.

**Screenshots / Video:**

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This PR fixes network permissions not showing up in the multiplayer window, which turned out to be a regression from #6788.

Fixing this probably also fixes #7028, but I have been unable to verify this, as I don't have the relevant permission on any server. :-)

### CODE REVIEW

File: src/openrct2/network/NetworkGroup.cpp [hunk 1]
```diff
@@ -102,9 +102,9 @@ void NetworkGroup::Write(NetworkPacket &packet)
 {
     packet << Id;
     packet.WriteString(GetName().c_str());
-    for (size_t i = 0; i < ActionsAllowed.size(); i++)
+    for (auto &action : ActionsAllowed)
```
Comment (janisozaur) [inline src/openrct2/network/NetworkGroup.cpp]: `const`?

Comment (AaronVanGeffen) [reply src/openrct2/network/NetworkGroup.cpp]: Fails to compile if we make it `const`.

Comment (IntelOrca) [inline src/openrct2/network/NetworkGroup.cpp]: `const auto &action`

Comment (AaronVanGeffen) [reply src/openrct2/network/NetworkGroup.cpp]: If I make it `const auto &action`, I get the following compiler error:

```
In file included from ../src/openrct2/network/NetworkGroup.h:22:0,
                 from ../src/openrct2/network/NetworkGroup.cpp:21:
../src/openrct2/network/NetworkPacket.h: In instantiation of ‘NetworkPacket& NetworkPacket::operator>>(T&) [with T = const unsigned char]’:
../src/openrct2/network/NetworkGroup.cpp:97:19:   required from here
../src/openrct2/network/NetworkPacket.h:53:19: error: assignment of read-only reference ‘value’
             value = 0;
             ~~~~~~^~~
../src/openrct2/network/NetworkPacket.h:57:19: error: assignment of read-only reference ‘value’
             value = ByteSwapBE(*((T *)&GetData()[BytesRead]));
             ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```

Comment (janisozaur) [reply src/openrct2/network/NetworkGroup.cpp]: That's some horrid violation of C++

Comment (IntelOrca) [reply src/openrct2/network/NetworkGroup.cpp]: Huh?, It worked for me

Comment (IntelOrca) [reply src/openrct2/network/NetworkGroup.cpp]: I only said to do it for the second one.

Comment (Broxzier) [reply src/openrct2/network/NetworkGroup.cpp]: Only make this one const, the other one can't be const because there the values get's written to `action`. Here `action` is only only used for writing into the packet.
