### PR TITLE
Fix #17963: Opening research tab breaks marketing tab

### LINKED ISSUE #17963: Marketing campaigns can't be started after Finance window tab has been on Research
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1 (latest build from develop branch)

### Describe the issue

After the 'Research' tab has been opened in the finance window, some marketing campaigns can't be started anymore. 

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Start a new campaign with marketing campaigns available, for example RCT2's Gravity Gardens.
2. Open the Finance window and go to the _Marketing_ tab. 
    - Note that all campaign buttons are clickable: the 'start new campaign' detail window will open as expected.
4. Switch to the _Research_ tab.
5. Go back to the _Marketing_ tab.
6. Try to start all campaigns. Note that some campaign buttons can't be clicked.

I noticed that the window's `Mouse` events aren't triggered at all anymore when pressing these buttons.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

File: src/openrct2-ui/windows/Finances.cpp [hunk 1]
```diff
@@ -772,6 +772,8 @@ class FinancesWindow final : public Window
 
     void OnPrepareDrawMarketing()
     {
+        disabled_widgets = 0;
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Finances.cpp:775]: I’d prefer to do this in OnPrepareDraw(). As it stands, the summary tabs don’t _happen_ to need it, but you can just assume that. Seems more robust to me to do it there.

**Review by Gymnasiast — APPROVED** [review]

File: src/openrct2-ui/windows/Finances.cpp (hunk 1 above)
Comment (Broxzier) [reply src/openrct2-ui/windows/Finances.cpp]: I see you already updated it now. Neither place is really good, it's a bit odd that this has to be updated inside `OnPrepareDraw` at all, but we don't have a proper system to handle it now. Ideally, the game would trigger an event that the window listens to, to update which widgets are enabled or disabled, instead of calculating them every time it gets drawn.
