### PR TITLE
Fix #15908: Out of bounds access for track elements with no ride index

### LINKED ISSUE #15908: Game crash after 1-2 min of loading one file
### Operating System

Win 10 64 bit 21H1

### OpenRCT2 build

OpenRCT2 v0.3.5, 0.3.4

### Describe the issue

Game crashes each time it tries to load a specific scenario save file. Doesn't happen with version 0.3.3 or earlier, but all versions after sees crash/corruption

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Open game 
2.  Load custom Dusty Desert File
3. Play around for a few minutes

### Attachments

[f42877c7-38c1-456f-8e06-ab95f654dffd(b9bc8d0_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/7532919/f42877c7-38c1-456f-8e06-ab95f654dffd.b9bc8d0_x86-64.dmp.gz)

### PR DESCRIPTION
**Pull request by ZehMatt**
Closes #15908

### CODE REVIEW

**Review by IntelOrca — APPROVED** [review]

File: src/openrct2/rct2/S6Importer.cpp [hunk 1]
```diff
@@ -903,7 +910,7 @@ class S6Importer final : public IParkImporter
         dst.State = src.state;
         if (src.current_ride < RCT12_MAX_RIDES_IN_PARK && _s6.rides[src.current_ride].type < std::size(RideTypeDescriptors))
             dst.ProximityTrackType = RCT2TrackTypeToOpenRCT2(
-                src.proximity_track_type, _s6.rides[src.current_ride].type, _isFlatRide[src.current_ride]);
+                src.proximity_track_type, _s6.rides[src.current_ride].type, IsFlatRide(src.current_ride));
```
Comment (Gymnasiast) [inline src/openrct2/rct2/S6Importer.cpp:913]: This is not related to the bug at hand. Please revert.
