### PR TITLE
Fix #19053: MazeConstruction window does not open

### LINKED ISSUE #19053: Selecting "Build Custom Design" when building a maze fails to open construction window
### Operating System

WIndows 10

### OpenRCT2 build

OpenRCT2, v0.4.3-70-gc202fd3 (c202fd3 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Selecting "build custom design" when trying to build a maze will fail to open the construction window, meaning custom mazes are impossible at the moment.

### Steps to reproduce

1. Open the new ride tool
2. Select maze
3. Select "build custom design"
4. Construction window fails to open

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
For some reason, it *needs* certain widgets to be at the same position as those in the regular Ride Construction window.

### CODE REVIEW

File: src/openrct2-ui/windows/MazeConstruction.cpp [hunk 1]
```diff
@@ -41,15 +41,19 @@ enum {
...
     WIDX_MAZE_DIRECTION_SW,
     WIDX_MAZE_DIRECTION_SE,
-    WIDX_MAZE_ENTRANCE = 29,
+    WIDX_MAZE_ENTRANCE = 30,
     WIDX_MAZE_EXIT,
 };
 
+validate_global_widx(WC_MAZE_CONSTRUCTION, WIDX_MAZE_DIRECTION_GROUPBOX);
+validate_global_widx(WC_MAZE_CONSTRUCTION, WIDX_MAZE_ENTRANCE);
+validate_global_widx(WC_MAZE_CONSTRUCTION, WIDX_MAZE_EXIT);
```
Comment (tupaschoal) [inline src/openrct2-ui/windows/MazeConstruction.cpp:55]: Nice!

**Review by tupaschoal — APPROVED** [review]
Tested and it works fine.
