### PR TITLE
Fix #14893. Only check map capacity with valid locations

### LINKED ISSUE #14893: [a84195] openrct2.exe: SmallSceneryPlaceAction::Query, GameActions::QueryInternal, window_top_toolbar_scenery_tool_down, Inpu...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/a84195378bfe682d68bcd7e62effb3668b4fe1e0b4bcdd05f12fd08385b42f1f">New error: [openrct2]</a></b><br /><b>3</b> occurrences since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>error.message</strong> &mdash; 3
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 3</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 3
        <ul>
                <li><code>C:\Users\Dirk\Documents\OpenRCT2\12e72bef-14d8-4b5f-9a96-f26bc9e1b7bc.ini</code> &mdash; 1</li>
                <li><code>C:\Users\Dirk\Documents\OpenRCT2\b6f9e1e3-7a40-4a14-830a-ae95ed886812.ini</code> &mdash; 1</li>
                <li><code>C:\Users\Dirk\Documents\OpenRCT2\d1160975-c6c9-409b-8f06-a4e977c339d1.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 3
        <ul>
                <li><code>*</code> &mdash; 3</li></ul><br>
<strong>commit</strong> &mdash; 3
        <ul>
                <li><code>6b1141b</code> &mdash; 3</li></ul><br>
<strong>fault.address</strong> &mdash; 3
        <ul>
                <li><code>18446744073709551615</code> &mdash; 2</li>
                <li><code>1211</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
SmallSceneryPlaceAction::Query
GameActions::QueryInternal
window_top_toolbar_scenery_tool_down
InputWidgetLeft
GameHandleInputMouse
GameHandleInput
context_handle_input
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Found the source of these unexplained crashes. It happens when invalid coordinates are passed to the map reorganiser. This was happening because the call that checks if the location was valid was later in the query of the game action. Easy way to trigger this was using the scenery scatter tool off the map edge.

I also took the  opertunity to delete duplicated calls that were in the  query and execute. There is no need to do this check in both.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
> I also took the opertunity to delete duplicated calls that were in the query and execute. There is no need to do this check in both.

Just checking: do we _always_ run Query before Execute?

**Comment by duncanspumpkin** [comment]
Yes. They are always run first.

File: src/openrct2/actions/PlaceParkEntranceAction.cpp [hunk 1]
```diff
@@ -51,17 +51,17 @@ GameActions::Result::Ptr PlaceParkEntranceAction::Query() const
     res->Expenditure = ExpenditureType::LandPurchase;
     res->Position = { _loc.x, _loc.y, _loc.z };
 
-    if (!CheckMapCapacity(3))
+    if (!LocationValid(_loc) || _loc.x <= 32 || _loc.y <= 32 || _loc.x >= (gMapSizeUnits - 32)
```
Comment (Gymnasiast) [inline src/openrct2/actions/PlaceParkEntranceAction.cpp:54]: This needs a function. Could you create an issue to make one?

File: src/openrct2/actions/PlaceParkEntranceAction.cpp [hunk 2]
```diff
@@ -51,17 +51,17 @@ GameActions::Result::Ptr PlaceParkEntranceAction::Query() const
...
+            GameActions::Status::InvalidParameters, STR_CANT_BUILD_PARK_ENTRANCE_HERE, STR_TOO_CLOSE_TO_EDGE_OF_MAP);
     }
 
-    if (!LocationValid(_loc) || _loc.x <= 32 || _loc.y <= 32 || _loc.x >= (gMapSizeUnits - 32)
-        || _loc.y >= (gMapSizeUnits - 32))
+    if (!CheckMapCapacity(3))
     {
         return std::make_unique<GameActions::Result>(
-            GameActions::Status::InvalidParameters, STR_CANT_BUILD_PARK_ENTRANCE_HERE, STR_TOO_CLOSE_TO_EDGE_OF_MAP);
+            GameActions::Status::NoFreeElements, STR_CANT_BUILD_PARK_ENTRANCE_HERE, STR_NONE);
```
Comment (Gymnasiast) [inline src/openrct2/actions/PlaceParkEntranceAction.cpp:64]: You can use the LANDSCAPE_DATA_AREA_FULL string here.

**Comment by Gymnasiast** [comment]
I decided to merge it now because of the crashes. The line notes do still apply.
