### PR TITLE
Fix playSplashSound flag regression

### LINKED ISSUE #25991: The Articulated Trains (Wooden Coaster) produce a splash sound at the end of a drop
### Operating System

Windows 10 64-bits

### OpenRCT2 build

OpenRCT2, v0.4.31 (f954f7b66e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

https://youtu.be/_yuqAmHfx9g

A weird bug that the articulated wooden coaster trains will suddently make the splash sound, everytime it reach the bottom of a drop. And this is per vehicule!

### Steps to reproduce

1. Build a wooden coaster
2. build a drop
3. simulate
4. done! each vehicule will make a splash sound despite there's been no water

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by matheusvb3**
Fixes https://github.com/OpenRCT2/OpenRCT2/issues/25991

### CODE REVIEW

File: src/openrct2/ride/RideEntry.h [hunk 1]
```diff
@@ -51,7 +51,11 @@ enum class RideEntryFlag : uint8_t
     hasEnterpriseRotationType,
     disableWanderingDeprecated,
     playSplashSound,
-    playSplashSoundSlide,
+    /*
+     * Since the Water Coaster water sections share the same TrackElemType as the Dinghy Slide covered track, this flag
+     * was originally named playSplashSoundSlide
+     */
+    canHaveWaterSections,
```
Comment (spacek531) [inline src/openrct2/ride/RideEntry.h]:
```suggestion
    coveredTrackIsSplashdown,
```

I think this is more descriptive of what exactly the flag is doing, since this flag does not enable covered pieces (that's in the RTD).

**Comment by spacek531** [comment]
Logic is much better now. Only the flag name to address.

File: src/openrct2/ride/RideEntry.h (hunk 1 above)
Comment (matheusvb3) [reply src/openrct2/ride/RideEntry.h]: Correct me but aren't the water sections in the water coaster kind of like the log flume where it'll keep going albeit slowly? If that's the case it feels weird to call it a splashdown, plus splashdown makes me think of the element in the wooden coaster and I wanted to avoid re-using that term

Comment (spacek531) [reply src/openrct2/ride/RideEntry.h]: That's true... the game calls it "Water Channel (submerged)" so perhaps `coveredTrackIsWaterChannel`

Comment (matheusvb3) [reply src/openrct2/ride/RideEntry.h]: Ok

**Review by spacek531 — APPROVED** [review]
👍

**Review by spacek531 — APPROVED** [review]

File: src/openrct2/ride/Vehicle.cpp [hunk 2]
```diff
@@ -2076,16 +2086,6 @@ void Vehicle::UpdateHandleWaterSplash() const
...
-    else
-    {
-        if (trackType == TrackElemType::down25ToFlat)
-        {
-            if (track_progress == 12)
-            {
-                vehicle_update_play_water_splash_sound();
-            }
-        }
-    }
```
Comment (Gymnasiast) [inline src/openrct2/ride/Vehicle.cpp]: This is not what the logic looked like before your flags refactor. Please restore the _original_ logic - don’t fix a broken refactor with another refactor.

**Review by Gymnasiast — APPROVED** [review]

**Review by spacek531 — APPROVED** [review]
