### PR TITLE
Fix  #16478: No money in .park scenarios

### LINKED ISSUE #16478: No money in .park scenarios
### Operating System

Windows 10, 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1-d97ecdd

### Describe the issue

I tried to search by tags "money" "is open" "dev" "multiplayer", even searched through closed ones. I might missed it as well.
I did try few of the last 30 dev builds, seems they contain this problem too.

Whenever I start scenario that is saved as .park it always is in creative, meaning I have no access to money. They work just fine in singleplayer.

### Area(s) with issue?

New Save Format (NSF), This bug is specific to multiplayer

### Steps to reproduce

1. Create/Use scenario or convert SC6 type to .park scenario on development build. 
2. Select any objective that contains money.
3. Save it. (It is now .park)
4. Run the multiplayer
5. No matter objective, there is no money
6. When you go to edit again to change the goal, it always is set to "no money".

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by IntelOrca**
* Change new game button on start server to force a scenario begin routine.
* Reset the scenario data when saving a scenario.
* Remove the scenario no money flag. We only need one. The original was probably just to make edits in the editor free.
* Fix drawing issues with the editor step buttons.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
I looked at the commits. I understand the first three, but could you explain why the fourth one is necessary? (The one that changes the Scenario Editor UI.)

**Comment by IntelOrca** [comment]
@Gymnasiast Some regressions I found were also in develop. I decided just to fix the all the issues I saw with how those step buttons are drawn.

**Review by Gymnasiast — APPROVED** [review]

File: src/openrct2/rct2/S6Importer.cpp [hunk 1]
```diff
@@ -252,7 +252,15 @@ namespace RCT2
 
             gInitialCash = ToMoney64(_s6.initial_cash);
             gBankLoan = ToMoney64(_s6.current_loan);
-            gParkFlags = _s6.park_flags;
+
+            gParkFlags = _s6.park_flags & ~PARK_FLAGS_NO_MONEY_SCENARIO;
+
+            // RCT2 used a different flag for `no money` when the park is a scenario
+            if (_s6.header.type == S6_TYPE_SCENARIO && (_s6.park_flags & PARK_FLAGS_NO_MONEY_SCENARIO))
```
Comment (Gymnasiast) [inline src/openrct2/rct2/S6Importer.cpp:259]: This contains an error. If the save if not a scenario, but a regular save, this will _always_ turn the `PARK_FLAGS_NO_MONEY` flag off.

File: src/openrct2/rct1/S4Importer.cpp [hunk 2]
```diff
@@ -2206,11 +2206,9 @@ namespace RCT1
                 gParkFlags |= PARK_FLAGS_UNLOCK_ALL_PRICES;
             }
 
-            // RCT2 uses two flags for no money (due to the scenario editor). RCT1 used only one.
-            // Copy its value to make no money scenarios such as Arid Heights work properly.
             if (_s4.park_flags & RCT1_PARK_FLAGS_NO_MONEY)
             {
-                gParkFlags |= PARK_FLAGS_NO_MONEY_SCENARIO;
+                gParkFlags |= PARK_FLAGS_NO_MONEY;
```
Comment (Gymnasiast) [inline src/openrct2/rct1/S4Importer.cpp:2211]: This could probably have been removed altogether, assuming `RCT1_PARK_FLAGS_NO_MONEY` and `PARK_FLAGS_NO_MONEY` have the same value.

File: src/openrct2/rct2/S6Importer.cpp (hunk 1 above)
Comment (Broxzier) [reply src/openrct2/rct2/S6Importer.cpp:259]: Looks like only the `else` block has to be removed in that case.

Comment (Broxzier) [reply src/openrct2/rct2/S6Importer.cpp:259]: Just tested it, and I can confirm that with the else-block removed, the game loads .SV6 parks that were saved with no money correctly.
