### PR TITLE
Fix #23889 and refactor news items import

### LINKED ISSUE #23889: New scenery available messages appear when opening save files
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.20 (1c1b6d4 on HEAD)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

The game started doing that thing again where a bunch of messages related to scenery packs now available pops up when opening save files.

### Steps to reproduce

Open save file
Look at messages.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
I’m seriously questioning the seemingly overengineered ItemQueues and ItemQueue struct. It seems a pair of static vectors (or even regular ones) would do the job better. We should also get rid of accessing both queues as if they are one - I expect this is only because a single 61-item queue looks the same in assembly as an 11-item queue followed by a 50-item one.

I haven’t changed it in this PR though. Rather, I concentrated on 1) fixing the bug at hand, and 2) making sure no garbage/null data is imported in the first place.

Problems include the three park types handling import differently, the Clear() function not actually clearing all items, and S4/S6 parks importing both queues wholly, instead of stopping on encountering a null item. Changing the S4/S6 structs to properly split the two makes it far easier to see what is going on - and it also fixes a hidden bug that would have manifested itself if we ever changed the maximum number of recent news items from 11 (again due to accessing the queue as if it was a single 61-item thing, which is an additional reason to nuke it from orbit).

Needs testing, obviously. Preferably, this includes at least one save that shows a message upon opening.

@James103 Could you verify the scenario you uploaded now correctly opens?

@ZeeMaji Could you test this?

### CODE REVIEW

**Comment by ZeeMaji** [comment]
Sure!

File: src/openrct2/management/NewsItem.cpp [hunk 1]
```diff
@@ -484,3 +484,23 @@ void News::RemoveItem(int32_t index)
     }
     gameState.NewsItems[newsBoundary - 1].Type = News::ItemType::Null;
 }
+
+void News::importNewsItems(
+    GameState_t& gameState, const std::vector<News::Item>& recent, const std::vector<News::Item>& archived)
```
Comment (AaronVanGeffen) [inline src/openrct2/management/NewsItem.cpp:488]: The implementation being a vector isn't really relevant here, right. I'd suggest taking the C++20 approach of using std::span for the parameters. (The construction is implicit on the calling side.)

File: src/openrct2/management/NewsItem.h [hunk 2]
```diff
@@ -315,4 +321,7 @@ namespace OpenRCT2::News
 
     void AddItemToQueue(News::Item* newNewsItem);
     void RemoveItem(int32_t index);
+
+    void importNewsItems(
+        GameState_t& gameState, const std::vector<News::Item>& recent, const std::vector<News::Item>& archived);
```
Comment (AaronVanGeffen) [inline src/openrct2/management/NewsItem.h:329]: The implementation being a vector isn't really relevant here, right. I'd suggest taking the C++20 approach of using std::span for the parameters. The construction is implicit on the calling side. (Just need to swap out the include in this header.)

File: src/openrct2/management/NewsItem.h [hunk 3]
```diff
@@ -241,7 +241,10 @@ namespace OpenRCT2::News
 
         void clear() noexcept
         {
-            front().Type = News::ItemType::Null;
+            for (size_t i = 0; i < N; i++)
+            {
+                Queue[i].Type = News::ItemType::Null;
```
Comment (AaronVanGeffen) [inline src/openrct2/management/NewsItem.h:246]: Perhaps we could change the constructor for News::Item to default to `News::ItemType::Null` instead?

File: src/openrct2/management/NewsItem.h [hunk 4]
```diff
@@ -241,7 +241,10 @@ namespace OpenRCT2::News
...
+            }
```
Comment (AaronVanGeffen) [inline src/openrct2/management/NewsItem.h:247]: This seems like a good loop to replace with `std::fill`.

File: src/openrct2/management/NewsItem.cpp [hunk 5]
```diff
@@ -484,8 +484,7 @@ void News::RemoveItem(int32_t index)
     gameState.NewsItems[newsBoundary - 1].Type = News::ItemType::Null;
 }
 
-void News::importNewsItems(
-    GameState_t& gameState, const std::vector<News::Item>& recent, const std::vector<News::Item>& archived)
+void News::importNewsItems(GameState_t& gameState, const std::span<News::Item> recent, const std::span<News::Item> archived)
```
Comment (ZehMatt) [inline src/openrct2/management/NewsItem.cpp:487]:
```suggestion
void News::importNewsItems(GameState_t& gameState, const std::span<const News::Item> recent, const std::span<const News::Item> archived)
```
Since we are not planning to mutate the input we have to make the element const, making std::span const just means we can't re-assign std::span but News::Item remains mutable.

**Review by AaronVanGeffen — APPROVED** [review]
The changes look fine to me now, but I haven't tested them.

**Review by ZeeMaji — APPROVED** [review]
The issue is fixed and all of the parks i tested with active new messages present work as expected in all loading combinations. (s4 to park, s6 to park, park to s4, park to s6, s6 to s4, s4 to s6)

File: src/openrct2/rct2/S6Importer.cpp [hunk 6]
```diff
@@ -573,30 +605,9 @@ namespace OpenRCT2::RCT2
...
-                else
-                {
-                    // In case where news item type is broken, consider all remaining news items invalid.
-                    LOG_ERROR("Invalid news type 0x%x for news item %d, ignoring remaining news items", src->Type, i);
-                    // Still need to set the correct type to properly terminate the queue
-                    dst->Type = News::ItemType::Null;
-                    break;
-                }
-            }
+            auto recentMessages = convertNewsQueue(_s6.recentMessages, std::size(_s6.recentMessages));
```
Comment (mixiate) [inline src/openrct2/rct2/S6Importer.cpp:608]: I'm getting a build error on MSVC here and the next line:
S6Importer.cpp(608,81): warning C4267: 'argument': conversion from 'size_t' to 'uint8_t', possible loss of data

Also here:
https://github.com/OpenRCT2/OpenRCT2/blob/79d4de341bd22cd54ec8c5dc9ae4c53cc7989446/src/openrct2/rct1/S4Importer.cpp#L2284-L2285
