### PR TITLE
Fix #19991: Crash when using cut-away view

### LINKED ISSUE #19556: [7d0eee] openrct2.exe: BlitPixel, DrawBMPSpriteMinify, DrawBMPSprite, gfx_bmp_sprite_to_buffer, gfx_draw_sprite_palette_set_s...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/7d0eeee1b53964c6343a11ba9e6ccb18f106a6c016739e1e72325a917575cf9a">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>42000000-6caa-b509-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\영한\Documents\OpenRCT2\crash\78ae82dc-43ec-412d-a9cb-45b295ff492f.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>2590609557168</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.3 (285e0fc on master) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li>285e0fc &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
BlitPixel
DrawBMPSpriteMinify
DrawBMPSprite
gfx_bmp_sprite_to_buffer
gfx_draw_sprite_palette_set_software
gfx_draw_sprite_software
OpenRCT2::Drawing::X8DrawingContext::DrawSprite
gfx_draw_sprite
PaintDrawStruct
PaintDrawStructs
MainWindow::OnDraw
window_event_paint_call
window_draw_single
window_draw_core
window_draw
invoke
std::_Invoker_ret&lt;void&gt;::_Call
std::_Func_impl_no_alloc&lt;`window_draw_all&#39;::`2&#39;::&lt;lambda_1&gt;,void,rct_window *&gt;::_Do_call
window_draw_all
window_visit_each(std::function&lt;void __cdecl
window_update_all_viewports
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::Draw
OpenRCT2::Context::RunFixedFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main</code>
        </td>
    </tr></table>

### LINKED ISSUE #19562: [277b12] openrct2.exe: DrawRLESpriteMinify, DrawRLESprite<1>, gfx_draw_sprite_palette_set_software, gfx_draw_sprite_software,...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/277b12ddcc3c8b04e421686ec412c0e0f7a9b43494148bc6af0f089a0d5e8243">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>55000000-6caa-b509-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Sladjana\Documents\OpenRCT2\crash\06f5a795-0faa-4cad-9cca-33e88ef44c22.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>2320631075501</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.3 (285e0fc on master) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_WRITE</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li>285e0fc &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-write</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
DrawRLESpriteMinify
DrawRLESprite&lt;1&gt;
gfx_draw_sprite_palette_set_software
gfx_draw_sprite_software
OpenRCT2::Drawing::X8DrawingContext::DrawSprite
gfx_draw_sprite
PaintDrawStruct
PaintDrawStructs
window_draw_viewport
WindowRideMainPaint
window_event_paint_call
window_draw_single
window_draw_core
window_draw
invoke
std::_Invoker_ret&lt;void&gt;::_Call
std::_Func_impl_no_alloc&lt;`window_draw_all&#39;::`2&#39;::&lt;lambda_1&gt;,void,rct_window *&gt;::_Do_call
window_visit_each(std::function&lt;void __cdecl
window_draw_all
OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::Draw
OpenRCT2::Context::RunFixedFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main</code>
        </td>
    </tr></table>

### LINKED ISSUE #19637: [48b5d2] openrct2.exe: BlitPixel, DrawBMPSpriteMinify, DrawBMPSprite<3>, gfx_bmp_sprite_to_buffer, gfx_sprite_to_buffer, gfx_...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/48b5d273a3b543d9aeb0e96e068b46f9a49de0baa4cdd496529403a6a725cb25">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>8e000000-d7e7-be09-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\miche\OneDrive\Documents\OpenRCT2\crash\28f3a4c6-06b9-4b4e-ad24-be5f82340d7d.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>227618880</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.3 (285e0fc on master) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>285e0fc</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
BlitPixel
DrawBMPSpriteMinify
DrawBMPSprite&lt;3&gt;
gfx_bmp_sprite_to_buffer
gfx_sprite_to_buffer
gfx_draw_sprite_palette_set_software
gfx_draw_sprite_software
OpenRCT2::Drawing::X8DrawingContext::DrawSprite
gfx_draw_sprite
PaintDrawStruct
PaintDrawStructs
MainWindow::OnDraw
window_event_paint_call
window_draw_single
window_draw_core
window_draw
invoke
std::_Invoker_ret&lt;void&gt;::_Call
std::_Func_impl_no_alloc&lt;`window_draw_all&#39;::`2&#39;::&lt;lambda_1&gt;,void,rct_window *&gt;::_Do_call
window_visit_each(std::function&lt;void __cdecl
window_draw_all
OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
viewports_invalidate
EntityBase::Invalidate
OpenRCT2::Context::Draw
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::{ctor}
std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Bxty::{ctor}
std::allocator&lt;std::unique_ptr&lt;std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;,std::default_delete&lt;std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt; &gt; &gt; &gt;::allocate
OpenRCT2::Context::RunOpenRCT2</code>
        </td>
    </tr></table>

### LINKED ISSUE #19762: [4d876b] openrct2.exe: GfxGetG1Element, OpenRCT2::Drawing::X8DrawingContext::DrawSprite, GfxDrawSprite, PaintDrawStruct, Pain...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/4d876b57d707229d60eb27c8aaf2de48c13a7f33306287cf9b9c7c93f63c8a5f">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>d2010000-7f15-c809-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\irwag\OneDrive\Documents\OpenRCT2\crash\b77a1c0b-ff5b-46ee-a8ef-0ee0635292ed.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>140698624467557</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.4 (9e4918c) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ILLEGAL_INSTRUCTION</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li>9e4918c &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>ill</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
GfxGetG1Element
OpenRCT2::Drawing::X8DrawingContext::DrawSprite
GfxDrawSprite
PaintDrawStruct
PaintDrawStructs
ViewportPaintColumn
ViewportPaint
ViewportRender
MainWindow::OnDraw
WindowEventPaintCall
WindowDrawSingle
WindowDrawCore
WindowDraw
invoke
std::_Invoker_ret&lt;void&gt;::_Call
std::_Func_impl_no_alloc&lt;`WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,WindowBase *&gt;::_Do_call
WindowVisitEach(std::function&lt;void __cdecl
WindowDrawAll
OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::Draw
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main</code>
        </td>
    </tr></table>

### LINKED ISSUE #19956: [bb5e16] openrct2.exe: PaintDrawStruct
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJiYjVlMTZjNTI3ZmEzMjY2YmIxYjhhMmY1NTI3ZTkzYWFlYmNjZTgxNjNmNTRmMWI0MmY0ZWVmNjIzZTg0ZGM2IiwidHgiOjIxNDgxfSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=bb5e16c527fa3266bb1b8a2f5527e93aaebcce8163f54f1b42f4eef623e84dc6&amp;_tx=53e9">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Sun Apr 16 2023 17:59:10 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintDrawStruct PaintDrawStructs ViewportPaintColumn ViewportPaint ViewportRender MainWindow::OnDraw WindowEventPaintCall WindowDrawSingle WindowDrawCore WindowDraw invoke std::_Invoker_ret&lt;void&gt;::_Call std::_Func_impl_no_alloc&lt;`WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,WindowBase *&gt;::_Do_call WindowVisitEach(std::function&lt;void __cdecl WindowDrawAll OpenGLDrawingEngine::PaintWindows OpenRCT2::Paint::Painter::Paint OpenRCT2::Context::Draw OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19959: [14e0b1] openrct2.exe: PaintDrawStruct
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIxNGUwYjFhNTBjNjM0MzMwYTljNTkwNDA2MTZkNjg0NzdkN2U3N2RhMWIxNjUyMDdlMzg5NDBjNDc1MWY1MjRlIiwidHgiOjIxNDg2fSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=14e0b1a50c634330a9c59040616d68477d7e77da1b165207e38940c4751f524e&amp;_tx=53ee">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Sun Apr 16 2023 18:59:13 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintDrawStruct PaintDrawStructs ViewportPaintColumn ViewportPaint ViewportRender MainWindow::OnDraw WindowEventPaintCall WindowDrawSingle WindowDrawCore WindowDraw invoke std::_Invoker_ret&lt;void&gt;::_Call std::_Func_impl_no_alloc&lt;`WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,WindowBase *&gt;::_Do_call WindowVisitEach(std::function&lt;void __cdecl WindowDrawAll OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks OpenRCT2::Drawing::X8DrawingEngine::PaintWindows OpenRCT2::Paint::Painter::Paint OpenRCT2::Context::Draw OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19963: [ffa44f] openrct2.exe: PaintDrawStruct
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJmZmE0NGY1NjEzMTIxZTQyOGNlYTU5OTY4MjZmZmQzODhkZmE1OWIzNzA2MTY4MjhjN2ZjMWNiNDMxNzE0MWFmIiwidHgiOjIxNTAxfSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=ffa44f5613121e428cea5996826ffd388dfa59b370616828c7fc1cb4317141af&amp;_tx=53fd">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Apr 17 2023 00:59:18 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintDrawStruct PaintDrawStructs ViewportPaintColumn ViewportPaint ViewportRender MainWindow::OnDraw WindowEventPaintCall WindowDrawSingle WindowDrawCore WindowDraw invoke std::_Invoker_ret&lt;void&gt;::_Call std::_Func_impl_no_alloc&lt;`WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,WindowBase *&gt;::_Do_call WindowVisitEach(std::function&lt;void __cdecl WindowDrawAll OpenGLDrawingEngine::PaintWindows OpenRCT2::Paint::Painter::Paint OpenRCT2::Context::Draw OpenRCT2::Context::RunVariableFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19971: [e23aa1] openrct2.exe: PaintDrawStruct
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJlMjNhYTE0ZjE5YTY1YmRkMzE0YTViM2NiOWJjZTUwYTJhOWUwMjY4MzYyNmZlMjcwYmQxYzg4OGZmZTRhZjMyIiwidHgiOjIxNTE1fSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=e23aa14f19a65bdd314a5b3cb9bce50a2a9e02683626fe270bd1c888ffe4af32&amp;_tx=540b">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Apr 17 2023 14:24:47 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintDrawStruct PaintDrawStructs ViewportPaintColumn JobPool::ProcessQueue invoke( std::thread::_Invoke&lt;std::tuple&lt;void ( JobPool::*)(void),JobPool *&gt;,0,1&gt; thread_start&lt;unsigned int (*)(void *),1&gt; </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19973: [b44099] openrct2.exe: PaintDrawStruct
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJiNDQwOTkzNzJmYTc3MjRhYjExM2ViZWRkMzJiOGQxMzViZTljN2Q2YmYzMWRhNDlkM2E1ZDI0ZWFmNzdjYWU5IiwidHgiOjIxNTE4fSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=b44099372fa7724ab113ebedd32b8d135be9c7d6bf31da49d3a5d24eaf77cae9&amp;_tx=540e">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Apr 17 2023 15:24:48 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintDrawStruct PaintDrawStructs ViewportPaintColumn ViewportPaint ViewportRender MainWindow::OnDraw WindowEventPaintCall WindowDrawSingle WindowDrawCore WindowDraw invoke std::_Invoker_ret&lt;void&gt;::_Call std::_Func_impl_no_alloc&lt;`WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,WindowBase *&gt;::_Do_call WindowVisitEach(std::function&lt;void __cdecl WindowDrawAll OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks OpenRCT2::Drawing::X8DrawingEngine::PaintWindows OpenRCT2::Paint::Painter::Paint OpenRCT2::Context::Draw OpenRCT2::Context::RunVariableFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19977: [1686f1] openrct2.exe: PaintDrawStruct
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIxNjg2ZjE2MmI5YjYzYmUxZTQ0MGNiMTdlOGMzNTc3ZTY3MGNlMTBiYzg2NGI3OWUwMDI2MTZjNjIxODRhMTk4IiwidHgiOjIxNTI5fSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=1686f162b9b63be1e440cb17e8c3577e670ce10bc864b79e002616c62184a198&amp;_tx=5419">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Apr 17 2023 20:33:53 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintDrawStruct PaintDrawStructs ViewportPaintColumn ViewportPaint ViewportRender MainWindow::OnDraw WindowEventPaintCall WindowDrawSingle WindowDrawCore WindowDraw invoke std::_Invoker_ret&lt;void&gt;::_Call std::_Func_impl_no_alloc&lt;`WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,WindowBase *&gt;::_Do_call WindowDrawAll ZoomLevel::operator= ViewportRedrawAfterShift ViewportShiftPixels ViewportMove ViewportUpdatePosition WindowVisitEach(std::function&lt;void __cdecl WindowUpdateAllViewports OpenRCT2::Drawing::X8DrawingEngine::PaintWindows OpenRCT2::Paint::Painter::Paint OpenRCT2::Context::Draw OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19981: [1d2f33] openrct2.exe: ScreenCoordsXY::operator+
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIxZDJmMzMwZGZkZjYzOThhMjEyYjk0ZjczYWY4YjIzMTdiZGM4ZGMzNzdmM2ExYjM5YzQyOWNlYmEyNjVjNjdlIiwidHgiOjIxNTM3fSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=1d2f330dfdf6398a212b94f73af8b2317bdc8dc377f3a1b39c429ceba265c67e&amp;_tx=5421">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Tue Apr 18 2023 01:33:58 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> ScreenCoordsXY::operator+ PaintAttachedPS PaintDrawStruct PaintDrawStructs ViewportPaintColumn JobPool::ProcessQueue invoke( std::thread::_Invoke&lt;std::tuple&lt;void ( JobPool::*)(void),JobPool *&gt;,0,1&gt; thread_start&lt;unsigned int (*)(void *),1&gt; </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19983: [e76a1b] openrct2.exe: PaintDrawStruct
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJlNzZhMWJlNzM3ZTg0YTk1MmMzNTkzZGRkNDI3NzhhNzA4MmRjYjE2MWJjYzk4MGEzNzdhMDdjYjVlZDM3Y2YwIiwidHgiOjIxNTQyfSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=e76a1be737e84a952c3593ddd42778a7082dcb161bcc980a377a07cb5ed37cf0&amp;_tx=5426">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Tue Apr 18 2023 04:33:59 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintDrawStruct PaintDrawStructs ViewportPaintColumn JobPool::ProcessQueue invoke( std::thread::_Invoke&lt;std::tuple&lt;void ( FileWatcher::*)(void),FileWatcher *&gt;,0,1&gt; thread_start&lt;unsigned int (*)(void *),1&gt; </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19984: [553747] openrct2.exe: ScreenCoordsXY::operator+
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiI1NTM3NDc1MTI1NjFiNmRlNjliYmUxOThiMDVmOTJlMWEwMjZkNmJhNGJjYTVjYTE5NTUwZTk0ZjZlYzAzNWRmIiwidHgiOjIxNTQxfSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=553747512561b6de69bbe198b05f92e1a026d6ba4bca5ca19550e94f6ec035df&amp;_tx=5425">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Tue Apr 18 2023 04:34:00 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> ScreenCoordsXY::operator+ PaintAttachedPS PaintDrawStruct PaintDrawStructs ViewportPaintColumn JobPool::ProcessQueue invoke( std::thread::_Invoke&lt;std::tuple&lt;void ( FileWatcher::*)(void),FileWatcher *&gt;,0,1&gt; thread_start&lt;unsigned int (*)(void *),1&gt; </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #19991: Crash when using cut away view
### Operating System

windows 11

### OpenRCT2 build

2fd3eb47e753c4a8c47ddddffdab9e61299609f3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Crash to desktop as said in title

Callstack from visual studio:
```
>	openrct2.exe!PaintDrawStruct(PaintSession & session, PaintStruct * ps) Line 513	C++
 	openrct2.exe!PaintDrawStruct(PaintSession & session, PaintStruct * ps) Line 539	C++
 	openrct2.exe!PaintDrawStructs(PaintSession & session) Line 561	C++
 	openrct2.exe!ViewportPaintColumn(PaintSession & session) Line 941	C++
 	openrct2.exe!ViewportPaint(const Viewport * viewport, DrawPixelInfo & dpi, const ScreenRect & screenRect, std::vector<RecordedPaintSession,std::allocator<RecordedPaintSession>> * recorded_sessions) Line 1073	C++
 	openrct2.exe!ViewportRender(DrawPixelInfo & dpi, const Viewport * viewport, const ScreenRect & screenRect, std::vector<RecordedPaintSession,std::allocator<RecordedPaintSession>> * sessions) Line 840	C++
 	openrct2.exe!MainWindow::OnDraw(DrawPixelInfo & dpi) Line 49	C++
 	[Inline Frame] openrct2.exe!WindowEventPaintCall(WindowBase *) Line 1652	C++
 	openrct2.exe!WindowDrawSingle(DrawPixelInfo & dpi, WindowBase & w, int left, int top, int right, int bottom) Line 1268	C++
 	openrct2.exe!WindowDrawCore(DrawPixelInfo & dpi, WindowBase & w, int left, int top, int right, int bottom) Line 1201	C++
 	openrct2.exe!WindowDraw(DrawPixelInfo & dpi, WindowBase & w, int left, int top, int right, int bottom) Line 1182	C++
 	[External Code]	
 	[Inline Frame] openrct2.exe!std::_Func_class<void,WindowBase *>::operator()(WindowBase * <_Args_0>) Line 874	C++
 	openrct2.exe!WindowVisitEach(std::function<void __cdecl(WindowBase *)> func) Line 100	C++
 	openrct2.exe!WindowDrawAll(DrawPixelInfo & dpi, int left, int top, int right, int bottom) Line 2103	C++
 	[Inline Frame] openrct2.exe!OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks(unsigned int) Line 440	C++
 	openrct2.exe!OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks() Line 369	C++
 	openrct2.exe!OpenRCT2::Drawing::X8DrawingEngine::PaintWindows() Line 211	C++
 	openrct2.exe!OpenRCT2::Paint::Painter::Paint(OpenRCT2::Drawing::IDrawingEngine & de) Line 52	C++
 	openrct2.exe!OpenRCT2::Context::Draw() Line 1169	C++
 	openrct2.exe!OpenRCT2::Context::RunVariableFrame(float deltaTime) Line 1159	C++
 	openrct2.exe!OpenRCT2::Context::RunFrame() Line 1076	C++
 	[Inline Frame] openrct2.exe!OpenRCT2::Context::RunGameLoop() Line 1039	C++
 	openrct2.exe!OpenRCT2::Context::Launch() Line 1002	C++
 	openrct2.exe!OpenRCT2::Context::RunOpenRCT2(int argc, const char * * argv) Line 300	C++
 	openrct2.exe!NormalisedMain(int argc, const char * * argv) Line 73	C++
 	openrct2.exe!wmain(int argc, wchar_t * * argvW, wchar_t * envp) Line 46	C++
 	[External Code]	
```

### Steps to reproduce

Open a game, any game, doesnt have to be running.
Open the cut away window and and hold down on the decrease button on the slider and eventually the game will freeze and go poof.
Profit?

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZehMatt**
PaintHead was just there to point to the next node for the quadrant list and had no useful data stored there, 120 bytes for nothing really. Now its actually the first node in the list and not a temporary. I've tested this a bit as it affects drawing and interactions, as far as I can tell interactions still work the same way and I can't see any artifacts.

Closes #19991, Closes #19984, Closes #19983, Closes #19981, Closes #19971, Closes #19977, Closes #19973, Closes #19963, Closes #19959, Closes #19956, Closes #19762, Closes #19991, Closes #19637, Closes #19562, Closes #19556

### CODE REVIEW

**Comment by ZehMatt** [comment]
Apparently this solves all of those: https://github.com/OpenRCT2/OpenRCT2/issues?q=is%3Aissue+is%3Aopen+paintdrawstructs

The reason for the crash is that PaintHead.NextQuadrantEntry was not reset to zero so when the column is cut away with via the cut-away view thing it would not generate a new list where it initially sets this to zero so it would try to draw the data from the previous frame.

File: src/openrct2/paint/Paint.cpp [hunk 1]
```diff
@@ -477,15 +477,18 @@ template<int TRotation> static void PaintSessionArrangeImpl(PaintSessionCore& se
         return;
     }
 
-    PaintStructsLinkQuadrants(session);
+    PaintStruct psHead{};
```
Comment (duncanspumpkin) [inline src/openrct2/paint/Paint.cpp:480]: i think we should add some comments on this. My understanding is as follows:

The psHead is a temporary that never has any information set to it it just acts as something for things to attach on to. After we have setup everything we set the psHead to the first real paintstruct (or nullptr if there is none?).

**Review by duncanspumpkin — APPROVED** [review]
