### PR TITLE
Fix #17996 - Finances window not cleared when starting some .park scenarios

### LINKED ISSUE #17996: Finances window not cleared when starting some .park scenarios
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-250-ga5a6d3a (a5a6d3a on develop) provided by GitHub

### Describe the issue

Extreme Rainforest Romp 2022-09-09 08-51-22
While I was making a new scenario pack, I discovered that starting a new game in some .park scenarios (including the South America - Rain Forest Plateau 2 (Extreme Rainforest Romp) attached below) does not properly clear the finances window upon startup, even though the finances window always starts blank in regular .sc6 and .sc4 scenarios. In the above screenshot, you can see that I started a new game in Extreme Rainforest Romp (which is a .park scenario), and the Financial Summary window is already partly filled in, which shouldn't be happening. If this scenario was a .sc6 instead, the Financial Summary window would be correctly blanked right at the start of the scenario.

Rainbow Highlands 2022-09-09 08-59-13
Here's another screenshot of me starting a new game in a .sc6 scenario (Rainbow Highlands), where the Financial Summary window is correctly blanked at the start of the scenario.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Start a new game in any scenario (format used doesn't matter)
2. Perform actions in it that change the amount of money on hand (e.g. building rides or scenery) or let guests pay for rides, park entrance, food, drinks, or merchandise (money must be enabled for this)
3. Check the finances window and see that it is partly filled in for March, Year 1, then save the game
4. Convert that saved game into a scenario and then start a new game in it
5. Open the finances window - you will now see that the finances window did not get cleared at all

### Attachments

[South America - Rain Forest Plateau 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/9536948/South.America.-.Rain.Forest.Plateau.2.zip)
The Extreme Rainforest Romp scenario from the screenshot at the top.

### PR DESCRIPTION
**Pull request by kyphii**
Fix https://github.com/OpenRCT2/OpenRCT2/issues/17996

Scenarios created in .park retain their finance graphs, so a new scenario game started from a .park scenario may already show financial activity from the start. Slightly annoying if you're trying to avoid it while making a scenario.

Clearing gExpenditureTable on scenario load is sufficient to fix this. This does not impact saved games loaded from .sv6 or .park, only new scenario games. Alternatively, the reset to gExpenditureTable could be done on converting to scenario, but doing it on scenario load will fix it for all .park scenarios created while this issue was present.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
> Clearing gExpenditureTable on scenario load is sufficient to fix this. This does not impact saved games loaded from .sv6 or .park, only new scenario games. Alternatively, the reset to gExpenditureTable could be done on converting to scenario, but doing it on scenario load will fix it for all .park scenarios created while this issue was present.

Lets clear it on conversion as well. No point having the data in the save file its just wasting bytes that could be compressed to nothing much.

**Comment by kyphii** [comment]
That makes sense, though I'm not sure exactly how to do that (C++ isn't my most familiar language). I think I should be able to pass (flags & S6_SAVE_FLAG_SCENARIO) down through the save game flow, but not sure of the best way to get that to the inner lambda in ReadWriteParkChunk() where the expenditure graph is written. Maybe instead it could clear the graph before going into the save game flow, but that strikes me as a bit bodgey.

**Comment by duncanspumpkin** [comment]
So lol I made a mistake. Turns out `FinanceResetHistory` is already called just before converting a scenario so the work is already done how I was wanting it. Could you revert the last 4 commits.

**Comment by kyphii** [comment]
This branch is pretty messed up now - perhaps I should start over

**Comment by duncanspumpkin** [comment]
> This branch is pretty messed up now - perhaps I should start over

I'll fix it. Just leave it as is.

**Review by duncanspumpkin — APPROVED** [review]

File: src/openrct2/management/Finance.cpp [hunk 1]
```diff
@@ -196,6 +196,14 @@ void FinanceResetHistory()
...
         gParkValueHistory[i] = MONEY64_UNDEFINED;
     }
+
+    for (uint32_t i = 0; i < EXPENDITURE_TABLE_MONTH_COUNT; ++i)
+    {
+        for (uint32_t j = 0; j < static_cast<int32_t>(ExpenditureType::Count); ++j)
+        {
+            gExpenditureTable[i][j] = 0;
+        }
+    }
```
Comment (Broxzier) [inline src/openrct2/management/Finance.cpp:206]: You can get rid of the array dimensions here by either using a range based loops, or by using sizeof/std::size. You can even zero-initialize the entire array in a single memset or std::fill call.
