### PR TITLE
Fix #15086: Crash in vehicle_create_trains()

### LINKED ISSUE #15086: [900f9d] openrct2.exe: vehicle_create_trains, Ride::UpdateMaxVehicles, Ride::CreateVehicles, Ride::Open, RideSetStatusAction:...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/900f9da8cfc55aba4f8f55758a06041174b208d706033358559ef01671616638">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Administrator\Documents\Random\\77d61a34-1581-4e72-8529-31f6e9236f3f.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>e0daac9</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>2</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
vehicle_create_trains
Ride::UpdateMaxVehicles
Ride::CreateVehicles
Ride::Open
RideSetStatusAction::Execute
OpenRCT2::MemoryStream::Write
std::ios_base::_Ios_base_dtor
std::basic_stringstream&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::`vbase destructor&#39;
RideSetStatusAction::Serialise
GameActions::ExecuteInternal
map_get_path_element_at
AnimateSceneryDoor&lt;0&gt;
std::thread::join
Ride::Update
Vehicle::UpdateTrackMotionForwards
ObjectManager::GetLoadedObject
Vehicle::Entry
GameActions::ProcessQueue
map_animation_invalidate_all
OpenRCT2::GameState::UpdateLogic
TcpSocket::SendData
OpenRCT2::GameState::Update
compute_year
common_gmtime_s&lt;__int64&gt;
common_localtime_s&lt;__int64&gt;
OpenRCT2::Context::Update
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
std::vector&lt;char const *,std::allocator&lt;char const *&gt; &gt;::_Change_array
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -4346,7 +4346,8 @@ static void vehicle_create_trains(ride_id_t rideIndex, const CoordsXYZ& trainsPo
         {
             if (ride->vehicles[i] == SPRITE_INDEX_NULL)
             {
-                ride->vehicles[i] = train.head->sprite_index;
+                if (train.head != nullptr)
```
Comment (duncanspumpkin) [inline src/openrct2/ride/Ride.cpp:4349]: we may as well validate on L4332 that the train has been created as there is no point validating any further beyond that point.

Comment (Gymnasiast) [reply src/openrct2/ride/Ride.cpp:4349]: So just check for train.head and train.tail and `continue` if one of them is a nullptr?

Comment (duncanspumpkin) [reply src/openrct2/ride/Ride.cpp:4349]: yes

**Review by duncanspumpkin — APPROVED** [review]
