### PR TITLE
Reset all peep sprite bounds at save file import time

### LINKED ISSUE #23376: Zoomed in software rendering does not properly invalidate balloons.
### Operating System

Any

### OpenRCT2 build

OpenRCT2, v0.4.17-8

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

It seems that the invalidated region may not be scaling properly with the zoom level when zoomed in.

Image

### Steps to reproduce

Zoom in on software rendering and look for guests with balloons

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This changes the S4/S6/park import logic to reset all peep sprite bounds at save file import time, rather than relying on bounds saved in the save file. Graphics aren't available when running the game headlessly, as is the case with most multiplayer servers, making the sprite bounds saved unreliable. I've opted not to change the entity serialising logic at this time; we're now just ignoring them for peeps as well.

In addition, we now compensate inferred sprite bounds for balloon/hat/umbrella sprites. As these items are painted in a second pass, they were previously not accounted for. This led to issues such as #23376. NB: this is not the case with other food items, which _are_ part of the peep sprites.

Fixes #23376

### CODE REVIEW

File: src/openrct2/peep/PeepAnimationData.cpp [hunk 1]
```diff
@@ -999,6 +999,15 @@ namespace OpenRCT2
                     continue;
 
                 anim.bounds = inferMaxAnimationDimensions(anim);
+
+                // Balloons, hats and umbrellas are painted in a second pass, so the inference
+                // algorithm doesn't account for those. We manually compensate for these here.
+                // Between 8-12 pixels are needed, depending on rotation, so we're generalising.
```
Comment (ZehMatt) [inline src/openrct2/peep/PeepAnimationData.cpp:1005]: This comment isn't exactly accurate, there is no second pass it when the peep is drawn and it has a balloon it attaches a child node to the parent paint node.

Comment (AaronVanGeffen) [reply src/openrct2/peep/PeepAnimationData.cpp:1005]: Okay, let's simplify this then:
```suggestion
                // Balloons, hats and umbrellas are painted separately, so the inference
                // algorithm doesn't account for those. We manually compensate for these here.
                // Between 8-12 pixels are needed, depending on rotation, so we're generalising.
```
Is that acceptable?

**Review by ZehMatt — APPROVED** [review]
Everything is now fine.
