### PR TITLE
 Fix #19475: Cannot increase loan when in debt 

### LINKED ISSUE #19475: Can't increase loan when having a debt of more than 1000
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.3-286-gef25274 (ef25274 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When I try to increase my loan (by clicking on the plus-button), the message "Can't pay back loan! Not enough cash available!" pops up when I have a cash debt of more than €1000. When below 1000, it works fine. This is the same message when trying to lower my loan (minus-button). I assume that the game checks in both cases if the cash amount after the action is positive, while this should only happen when trying to lower the loan. Increasing the loan should only be impossible when the maximum loan is reached.

### Steps to reproduce

1. Get a debt of more than 1000 (easy to accomplish in one of the RCT1 real parks, or with cheats)
2. Go to your financial summary
3. Click on the "+"-button next to the loan

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/actions/ParkSetLoanAction.cpp [hunk 1]
```diff
@@ -40,19 +40,18 @@ void ParkSetLoanAction::Serialise(DataSerialiser& stream)
...
     }
-    // FIXME: use money64 literal once it is implemented
-    if (_value < currentLoan && _value < 0)
+    if (_value < gBankLoan && _value < 0.00_GBP)
     {
         return GameActions::Result(GameActions::Status::InvalidParameters, STR_CANT_PAY_BACK_LOAN, STR_LOAN_CANT_BE_NEGATIVE);
     }
-    if (loanDifference > gCash)
+    // When the player is in debt, they need to be able to increase their loan.
+    if (loanDifference > 0 && loanDifference > gCash)
```
Comment (Broxzier) [inline src/openrct2/actions/ParkSetLoanAction.cpp:54]: `loanDifference` isn't very clear on which way it goes. Does a positive value mean that the loan increases? To make this more clear, you can get rid of the variable altogether and just compare the two values it's based on.
```suggestion
    // When the player is in debt, they need to be able to increase their loan.
    if (gBankLoan > _value && gBankLoan - _value > gCash)
```

**Review by Broxzier — APPROVED** [review]
