### PR TITLE
Fix #19250: MusicObjects do not free their preview images

### LINKED ISSUE #19250: "Unknown custom action" popup during play and assertion failure upon exit
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-184-ge09f27d (e09f27d on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Periodic "Unknown custom action" popup, "Assertion failed, 5 images were not freed" error on exit

### Steps to reproduce

1. Begin new game or open any saved game
2. "Unknown custom action" popup occurs every few seconds of play
3. Game crashes when exiting OpenRCT2

### Attachments

[0c6082eb-408e-48a5-a792-b8a3b75949fc(4281914_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/10473136/0c6082eb-408e-48a5-a792-b8a3b75949fc.4281914_x86-64.dmp.gz)
Screenshot 2023-01-21 164001
Screenshot 2023-01-21 164017
Screenshot 2023-01-21 164033

### PR DESCRIPTION
**Pull request by trzejos**
I can confirm this fixes the assertion failure mentioned here:
- https://github.com/OpenRCT2/OpenRCT2/issues/19250

I'm fairly confident it addresses all of these backtrace.io issues, they all have the same `5 images were not freed` assertion failure. I don't know how/if I can access backtrace.io, so if someone could confirm that would be great.
- https://github.com/OpenRCT2/OpenRCT2/issues/19242
- https://github.com/OpenRCT2/OpenRCT2/issues/19244
- https://github.com/OpenRCT2/OpenRCT2/issues/19248
- https://github.com/OpenRCT2/OpenRCT2/issues/19257
- https://github.com/OpenRCT2/OpenRCT2/issues/19258

It may address these backtrace.io issues as well. They have a similar assertion failure but a different image count:
- https://github.com/OpenRCT2/OpenRCT2/issues/19219
- https://github.com/OpenRCT2/OpenRCT2/issues/19208
- https://github.com/OpenRCT2/OpenRCT2/issues/19188
- https://github.com/OpenRCT2/OpenRCT2/issues/19182

### CODE REVIEW

**Comment by Broxzier** [comment]
Great find! This really shows we should aim for a RAII approach for managing resources.

File: src/openrct2/object/MusicObject.cpp [hunk 1]
```diff
@@ -80,6 +80,13 @@ void MusicObject::Load()
 void MusicObject::Unload()
 {
     LanguageFreeObjectString(NameStringId);
+    if (_hasPreview)
```
Comment (IntelOrca) [inline src/openrct2/object/MusicObject.cpp:83]: You can probably omit this check.

Comment (duncanspumpkin) [reply src/openrct2/object/MusicObject.cpp:83]: Yeah its safe to call with zero image and it is allocated on L77 unconditionally

**Review by duncanspumpkin — CHANGES_REQUESTED** [review]
Remove the if

**Review by duncanspumpkin — APPROVED** [review]
