### PR TITLE
Fix #20008: Crash in PaintRotoDropTowerSection

### LINKED ISSUE #20008: [e354d7] openrct2.exe: PaintRotoDropTowerSection
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJlMzU0ZDc2ZGRjMzQ0ZTFhZGZjYTVkMmI1NmY3ODYzN2UyOGQzZTU0OTJlZmE3ZmQ0ZDY5ZDY5OWU4M2I1ODIyIiwidHgiOjIxNjQ1fSwiaW50ZWdyYXRpb24iOnsiaWQiOjQ3Mn0sImluc3RhbmNlIjp7ImFkZHJlc3MiOiJodHRwczovL29wZW5yY3QyLnNwLmJhY2t0cmFjZS5pbyJ9fV0%3D&amp;fingerprint=e354d76ddc344e1adfca5d2b56f78637e28d3e5492efa7fd4d69d699e83b5822&amp;_tx=548d">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Fri Apr 21 2023 14:36:29 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>

<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> PaintRotoDropTowerSection PaintTrack PaintTileElementBase TileElementPaintSetup PaintSessionGenerateRotate PaintSessionGenerate ViewportFillColumn invoke std::_Invoker_ret&lt;void&gt;::_Call std::_Func_impl_no_alloc&lt;`ViewportPaint&#39;::`26&#39;::&lt;lambda_1&gt;,void&gt;::_Do_call JobPool::ProcessQueue invoke( std::thread::_Invoke&lt;std::tuple&lt;void ( JobPool::*)(void),JobPool *&gt;,0,1&gt; thread_start&lt;unsigned int (*)(void *),1&gt; </code>
        </td>
    </tr>
     </table>

### PR DESCRIPTION
**Pull request by Broxzier**
Crash happened because now `nextTileElement` was used before checking `trackElement.IsLastForTile()`, so it could point to garbage. This PR refactors it so that no dangling pointer exists at all.

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
Have you verified that it's still allowing blocking the top with a scenery element?

File: src/openrct2/ride/thrill/RotoDrop.cpp [hunk 1]
```diff
@@ -185,14 +185,17 @@ static void PaintRotoDropTowerSection(
     auto imageId = session.TrackColours[SCHEME_TRACK].WithIndex(SPR_ROTO_DROP_TOWER_SEGMENT);
     PaintAddImageAsParent(session, imageId, { 0, 0, height }, { { 8, 8, height }, { 2, 2, 30 } });
 
-    const TileElement* nextTileElement = reinterpret_cast<const TileElement*>(&trackElement) + 1;
-
-    while (nextTileElement->GetType() != TileElementType::Track && !nextTileElement->IsLastForTile())
+    // The top of the Roto drop is only drawn when there is no other track elements right above it
+    bool paintTopSegment = trackElement.IsLastForTile();
+    const TileElementBase* tileElement = &trackElement;
```
Comment (Broxzier) [inline src/openrct2/ride/thrill/RotoDrop.cpp:190]: Needs to be `TileElement`

**Comment by Broxzier** [comment]
Yes, but I think this can be made simpler. The check for track type doesn't make sense to me.

**Comment by Broxzier** [comment]
Previously, all elements could be used to hide the top, as long as their base height matched the top's clearance. I've preserved this behaviour.

**Review by ZehMatt — APPROVED** [review]

File: src/openrct2/ride/thrill/RotoDrop.cpp [hunk 2]
```diff
@@ -185,14 +185,16 @@ static void PaintRotoDropTowerSection(
     auto imageId = session.TrackColours[SCHEME_TRACK].WithIndex(SPR_ROTO_DROP_TOWER_SEGMENT);
     PaintAddImageAsParent(session, imageId, { 0, 0, height }, { { 8, 8, height }, { 2, 2, 30 } });
 
-    const TileElement* nextTileElement = reinterpret_cast<const TileElement*>(&trackElement) + 1;
-
-    while (nextTileElement->GetType() != TileElementType::Track && !nextTileElement->IsLastForTile())
+    // The top segment of the Roto drop is only drawn when there is no other track element right above it
```
Comment (duncanspumpkin) [inline src/openrct2/ride/thrill/RotoDrop.cpp:188]: Could you perhaps mention that we also want this to block tops with non track.

**Review by duncanspumpkin — APPROVED** [review]
