### PR TITLE
Fix #7223 Vehicle mass not properly recalculated when using remove all guests cheat

### LINKED ISSUE #7223: River rapids get stuck on lift hills
**OS:** [Windows 10]
**Version:** [0.1.2]
**Commit/Build:** [57be3b4]

River rapids sometimes get stuck on lift hills. Few weeks ago i also saw a splash boats ride which sometimes got stuck on a lift hill, probably related. I have attached a save where two river rapids rides are stuck. One is completely stuck, the other one (river rapids 1) has one car stuck on a  lift hill which stays there until pushed off by the next, which then gets stuck.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Build river rapids or splash boats
2. Watch them sometimes get stuck on a lift hill

**Screenshots / Video:**
image

**Save game:**
[Multiplayer park - Squares 8.zip](https://github.com/OpenRCT2/OpenRCT2/files/1760470/Multiplayer.park.-.Squares.8.zip)

### PR DESCRIPTION
**Pull request by deurklink**
Made some changes to the remove all guests cheat so the mass of every vehicle gets properly recalculated.

Normally, the function first removes the peeps from the park, and then removes the list of peeps from vehicles.

I wanted to make use of the already existing loop in the function that cycles through all vehicles. To do that, i had to switch the order of the two functions. So now first the list of peeps in every vehicle is reset, and after that the peeps are removed from the park.

While cycling through all vehicles, a new loop cycles through the peeps that are currently in the vehicle, and subtracts their mass from the vehicle mass. 

I tested this in several parks, and noticed river rapids now keep running properly even when remove guests cheat is used several times. Mass gets properly set now.

### CODE REVIEW

File: src/openrct2/Cheats.cpp [hunk 1]
```diff
@@ -384,19 +375,32 @@ static void cheat_remove_all_guests()
             {
                 vehicle = GET_VEHICLE(spriteIndex);
 
-                vehicle->num_peeps = 0;
-                vehicle->next_free_seat = 0;
+                for (int i = 0; i < vehicle->num_peeps; i++) {
```
Comment (Gymnasiast) [inline src/openrct2/Cheats.cpp]: Please use `size_t`, rather than `int`. Could you also put the brace on the next line?

**Comment by janisozaur** [comment]
Should've bumped network version
