### PR TITLE
Fix #17276: RollerCoaster Tycoon 1 Title screen music not playing

### LINKED ISSUE #17276: RollerCoaster Tycoon 1 Title screen music not playing
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.0-154-ge90ebb3 (e90ebb3 on develop) provided by GitHub

### Describe the issue

Since the merge of the new audio dependencies the RCT1 title menu music doesn't play anymore.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Download & Install ge90ebb3
2. Make sure RCT1 is installed and its path is selected.
3. Go to options
4. Go to music & sound
5. Set title screen music to RollerCoaster Tycoon 1
6. No music is playing.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
Code looks sensible but ive not got rct1 installed so cant test.

File: src/openrct2/scenario/ScenarioRepository.cpp [hunk 1]
```diff
@@ -513,8 +513,7 @@ class ScenarioRepository final : public IScenarioRepository
         // If the user has a Steam installation.
         if (!File::Exists(mpdatPath))
         {
-            mpdatPath = Path::ResolveCasing(
-                Path::Combine(_env->GetDirectoryPath(DIRBASE::RCT1), u8"RCTdeluxe_install", u8"Data", u8"mp.dat"));
+            mpdatPath = _env->FindFile(DIRBASE::RCT1, DIRID::DATA, "mp.dat");
```
Comment (Gymnasiast) [inline src/openrct2/scenario/ScenarioRepository.cpp:516]: This is superfluous, when it gets here it has already checked for the existence of mp.dat in the usual location.

**Review by Gymnasiast — COMMENTED** [review]
Code works correctly on both my Steam install and CD install.

I have one comment, which I have put into a line note.

File: src/openrct2/scenario/ScenarioRepository.cpp (hunk 1 above)
Comment (IntelOrca) [reply src/openrct2/scenario/ScenarioRepository.cpp:516]: So should I just remove the `PATHID::MP_DAT` entry, and replace the top line with this line?

Comment (IntelOrca) [reply src/openrct2/scenario/ScenarioRepository.cpp]: Fixed

File: src/openrct2/PlatformEnvironment.cpp [hunk 2]
```diff
@@ -234,7 +250,6 @@ const u8string PlatformEnvironment::FileNames[] = {
     u8"objects.idx",                             // CACHE_OBJECTS
     u8"tracks.idx",                              // CACHE_TRACKS
     u8"scenarios.idx",                           // CACHE_SCENARIOS
-    u8"Data" PATH_SEPARATOR "mp.dat",            // MP_DAT
```
Comment (Gymnasiast) [inline src/openrct2/PlatformEnvironment.cpp:237]: Since you didn’t remove MP_DAT from the enum, doesn’t this mean the rest of the list now all maps incorrectly?

Comment (IntelOrca) [reply src/openrct2/PlatformEnvironment.cpp:237]: I thought I did :/

**Review by Gymnasiast — APPROVED** [review]
Tested again on both Steam and CD releases. Also tested mp.dat import for good measure.
