### PR TITLE
Improve performance on file indexing, fix progress bar flickering bug, refactors

### LINKED ISSUE #22418: checking object files progress bar flickers in latest development build but not the latest release build
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.12-116-g67fa13f (67fa13f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

https://github.com/user-attachments/assets/ec95f9dc-1915-40ee-8c85-a8791a2415a5

this graphical glitch occurs consistently when updating the game to the latest development build, it has to check object files. Reverting to 0.4.12 release does away with the flickering issue

### Steps to reproduce

Update the game and launch it, object file checking should flicker the screen

### Attachments

_No response_

### LINKED ISSUE #22432: Loading screen glitches out on OpenGL and unlocked frame rate
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.12-117-gf6aa08c (f6aa08c on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When running the game in OpenGL drawing engine and having the framerate unlocked, the loading bar for indexing the objects glitches like crazy. The other loading segments seem to do fine though. On software rendering, and without uncapped framerate, everything works as expected.

I presume that clearing the screen and redrawing the loading bar are not in sync with each other?

### Steps to reproduce

1. Ensure the game is using the OpenGL drawing engine.
2. Unlock your framerate.
3. Delete `objects.idx` from your user directory (to force a reindex next startup).
4. Restart OpenRCT2.

### Attachments

https://github.com/user-attachments/assets/bff94b9a-f103-4342-b7fe-60ecdc7c77d6

### PR DESCRIPTION
**Pull request by ZehMatt**
This improves the usage of SetProgress, we can tell if we are on the main thread by keeping track of who the main thread id. Also to not waste too many CPU cycles on drawing it limits it now to 40hz/fps. The file indexing is also refactored to actually use up all of the CPU in where when we batch groups and some of them might finish early so some cores will go idle.

Closes #22432
Closes #22418

### CODE REVIEW

File: src/openrct2/scenes/preloader/PreloaderScene.cpp [hunk 1]
```diff
@@ -54,11 +54,6 @@ void PreloaderScene::Tick()
     ContextHandleInput();
     WindowInvalidateAll();
 
-    // Reset screen
```
Comment (AaronVanGeffen) [inline src/openrct2/scenes/preloader/PreloaderScene.cpp:57]: With this gone, the following includes can be dropped as well:
```cpp
#include "../../drawing/IDrawingContext.h"
#include "../../drawing/IDrawingEngine.h"
```

**Comment by AaronVanGeffen** [comment]
Could you add a changelog entry for the file index improvements? Maybe something like:
```
Improved: [#22437] File indexing now properly uses all CPU power, improving object and scenario indexing.

**Comment by Gymnasiast** [comment]
Testing note: also test this with `play_intro` enabled.

**Comment by Basssiiie** [comment]
I did some tests and it seems loading got slightly quicker: from ~30 seconds down to ~25 seconds. On both develop and this PR's build the CPU seems to be maxed on all cores, but HDD usage is significantly lower. 🙂

This PR:

https://github.com/user-attachments/assets/cccdf78d-a8f0-4cbc-82cf-02057291aba5

Develop:

https://github.com/user-attachments/assets/db2442c3-3e53-42b0-a947-4628ade4e28d

File: src/openrct2/Context.cpp [hunk 2]
```diff
@@ -151,6 +159,10 @@ namespace OpenRCT2
         NewVersionInfo _newVersionInfo;
         bool _hasNewVersionInfo = false;
 
+        // We keep track of this to perform certain operations different.
```
Comment (Gymnasiast) [inline src/openrct2/Context.cpp:162]:
```suggestion
        // We keep track of this to perform certain operations differently.
```

**Review by AaronVanGeffen — APPROVED** [review]
This is working very nicely! Though I don't have benchmarks to back it up, the speed increase is very noticeable, even on my M1 MacBook Pro. Nice work! :+1:

**Comment by Gymnasiast** [comment]
> Testing note: also test this with `play_intro` enabled.

Was this bit tested? It was merged a bit more quickly than I anticipated, so I haven’t had time yet to check it.

**Comment by AaronVanGeffen** [comment]
> Was this bit tested? It was merged a bit more quickly than I anticipated, so I haven’t had time yet to check it.

Yes, I tested it. The intro performance was not affected at all, which is a good thing 😄
