### PR TITLE
Fix #19935: Part of old multiplayer name remains when entering a shorter name

### LINKED ISSUE #19935: Part of old multiplayer name remains when entering a shorter name
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2 v0.4.4-130-g7e313d4 (7e313d4 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When entering a new name in the multiplayer window in the title screen, and the new name is shorter than what was already entered, the last part of the previous name remains. For example, changing the name from "aaaaaa" to "bbb" would yield "aaabbb".

### Steps to reproduce

1. Enter a name with at least 2 characters
2. Press enter or click anywhere else
3. Enter another, shorter name
4. Press enter or click anywhere else
5. Observe the name changing again

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Chase-Percy**
Fixes #19935

Proposed Solution:

- Memset _playerName with null terminators before the text string view is copied into it.

Note:
-  I'm unsure if it would update the network version since it shouldn't change anything.

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Unless your PR is WIP, there seems to be no file overlap.

**Comment by ZehMatt** [comment]
> This is a good opportunity to turn `_playerName` into a `u8string` instead IMO - not only it lifts an artificial limit while fixing the bug you are addressing, but should also make the code clearer. It's a `.cpp` only UI class so I doubt you need to worry about the network version.

I agree, we should use u8string here and avoid having to use C style APIs in general.

**Comment by Chase-Percy** [comment]
Ah okay yeah a u8string would be clearer. I wasn't sure if there was a reason for the limit on the array. Is there any external documentation somewhere like a confluence or anything? Kinda hard when new to the codebase to know why things were done in a certain way like limitations etc.

**Comment by Chase-Percy** [comment]
Ok cool, good to know going forward! I'll rectify tomorrow

**Comment by Chase-Percy** [comment]
I have updated it to a u8string.

Here are some things worth mentioning:
- I set a value for the length of the player name. I based it on the old truncated value at 32 because otherwise, the names don't fit nicely in the in-game UI.
- I used the fill constructor to set the string size so the underlying c_str isn't invalidated. I was having issues if you opened the window with a short name and then expanded it to be the max size or enough to trigger the underlying c_str to be reallocated.
- I made the WindowStartTextbox function take a const char* so a c_str can be passed in without const casting it.
- I removed the old empty player name check since the text.empty() guard always procs before it can get there.

File: src/openrct2-ui/windows/ServerList.cpp [hunk 1]
```diff
@@ -267,22 +268,17 @@ class ServerListWindow final : public Window
...
 
-                text.copy(_playerName, sizeof(_playerName));
-
-                // Don't allow empty player names
-                if (_playerName[0] != '\0')
-                {
-                    gConfigNetwork.PlayerName = _playerName;
-                    ConfigSaveDefault();
-                }
+                _playerName = temp;
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/ServerList.cpp:279]: This will leak the old pointer. You must reset the widget pointer after this

File: src/openrct2-ui/windows/ServerList.cpp [hunk 2]
```diff
@@ -267,22 +268,17 @@ class ServerListWindow final : public Window
         if (text.empty())
             return;
 
-        std::string temp = static_cast<std::string>(text);
+        u8string temp = static_cast<u8string>(text);
```
Comment (Broxzier) [inline src/openrct2-ui/windows/ServerList.cpp:271]: The cast already states the type explicitly, so no need to state this twice.

```suggestion
        auto temp = static_cast<u8string>(text);
```

File: src/openrct2-ui/windows/ServerList.cpp [hunk 3]
```diff
@@ -267,22 +268,17 @@ class ServerListWindow final : public Window
...
-
-                // Don't allow empty player names
-                if (_playerName[0] != '\0')
-                {
-                    gConfigNetwork.PlayerName = _playerName;
-                    ConfigSaveDefault();
-                }
+                _playerName = temp;
+                gConfigNetwork.PlayerName = _playerName;
+                ConfigSaveDefault();
```
Comment (Broxzier) [inline src/openrct2-ui/windows/ServerList.cpp:281]: More of a remark than something to change right now. This gets called with every character you type. I think it would be nicer to only save it when the input box loses focus, or when Enter is pressed or something.

**Review by Broxzier — CHANGES_REQUESTED** [review]

File: src/openrct2-ui/windows/ServerList.cpp (hunk 1 above)
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp:292]: Yea, I had thought I solved this by setting the underlying c_str to be the same size as the max name length so on it would copy and not proc a realloc, but I thought about it, and this would be vendor implementation specific and is not defined in the standard. I think the approach you suggest is the safest: [3d02334](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/3d02334f2dc3124cf3cc737ee50f49aaa3a849de).

File: src/openrct2-ui/windows/ServerList.cpp [hunk 4]
```diff
@@ -33,6 +33,8 @@
 #    define WHEIGHT_MAX 800
 #    define ITEM_HEIGHT (3 + 9 + 3)
 
+constexpr size_t PLAYER_NAME_LENGTH = 32;
```
[the remark this answers is not in the document]
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp]: Yea sorry, still getting used to the conventions here: [43c8440](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/43c84404f6e04ff5cf40990ad6cce15503633d3e)

File: src/openrct2-ui/windows/ServerList.cpp (hunk 2 above)
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp]: [6f4df6e](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/6f4df6e38ba05451cee9494f4e70063d5d5a10cc)

File: src/openrct2-ui/windows/ServerList.cpp (hunk 3 above)
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp]: I agree, I gave it a shot here so it saves on window close or loss of focus: [c6e2546](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/c6e2546accada9b558422bde983a43943cdd5d84)

File: src/openrct2-ui/windows/ServerList.cpp [hunk 5]
```diff
@@ -76,21 +78,32 @@ void JoinServer(std::string address);
 class ServerListWindow final : public Window
 {
 private:
-    char _playerName[32 + 1] = {};
+    u8string _playerName = {};
```
Comment (CookiePLMonster) [inline src/openrct2-ui/windows/ServerList.cpp:81]:
```suggestion
    u8string _playerName;
```

**Review by CookiePLMonster — COMMENTED** [review]
Left just one nitpick, looks good to me otherwise.

File: src/openrct2-ui/windows/ServerList.cpp [hunk 6]
```diff
@@ -76,21 +78,32 @@ void JoinServer(std::string address);
...
     ServerList _serverList;
     std::future<std::tuple<std::vector<ServerListEntry>, StringId>> _fetchFuture;
     uint32_t _numPlayersOnline = 0;
     StringId _statusText = STR_SERVER_LIST_CONNECTING;
+    bool _nameTextBoxInFocus = false;
 
     bool _showNetworkVersionTooltip = false;
     std::string _version;
 
+    void CheckTextBoxFocus()
```
Comment (Broxzier) [inline src/openrct2-ui/windows/ServerList.cpp:91]: This name is not very descriptive. "Check" is one of the words you should almost never use, because it's so ambiguous.

```suggestion
    void OnFocusLoss()
```

File: src/openrct2-ui/windows/ServerList.cpp [hunk 7]
```diff
@@ -117,17 +128,20 @@ class ServerListWindow final : public Window
     {
         _serverList = {};
         _fetchFuture = {};
+        CheckTextBoxFocus();
```
Comment (Broxzier) [inline src/openrct2-ui/windows/ServerList.cpp:131]: You could just call `ConfigSaveDefault();` here instead.

**Review by Broxzier — CHANGES_REQUESTED** [review]

File: src/openrct2-ui/windows/ServerList.cpp (hunk 3 above)
Comment (Broxzier) [reply src/openrct2-ui/windows/ServerList.cpp]: Nice to see you picked this up. I left a few notes on the implementation.

File: src/openrct2-ui/windows/ServerList.cpp [hunk 8]
```diff
@@ -267,22 +281,17 @@ class ServerListWindow final : public Window
         if (text.empty())
             return;
 
-        std::string temp = static_cast<std::string>(text);
+        auto temp = static_cast<u8string>(text);
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/ServerList.cpp:284]: This looks a bit dubious, text is `std::string_view`, it should be probably `auto temp = u8string{text};`

File: src/openrct2-ui/windows/ServerList.cpp (hunk 5 above)
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp]: Yup, good point [38083b2](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/38083b2cd74b2329d29f68d781a86eb8e0a86d83)

File: src/openrct2-ui/windows/ServerList.cpp (hunk 6 above)
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp]: Yea, it was pretty bad in hindsight, I did sit there thinking what to name it but yea didn't really work lol. A good reminder of ambiguity though.

File: src/openrct2-ui/windows/ServerList.cpp (hunk 7 above)
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp]: Feels silly to not have seen that, I was too focused on the concept of losing focus to see the clearer solution: [b147c0d](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/b147c0dfb23ff4a1af469355ba37d0e69c8fdc8c)

File: src/openrct2-ui/windows/ServerList.cpp (hunk 8 above)
Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp]: Yea, good call. It's been a learning experience this PR with not just updating things but evaluating what they are and the better way to implement them: [c9b3e8f](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/c9b3e8f185d96dacacb721875134e639864f3ea4)

File: distribution/changelog.txt [hunk 9]
```diff
@@ -37,6 +37,7 @@
 - Fix: [#19955] Mine Train Roller Coaster has incorrect supports on the sloped left small turn (original bug).
 - Fix: [#19987] [Plugin] ‘SetCheatAction’ has wrong ID in plugin API.
 - Fix: [#19991] Crash using cut-away view.
+- Fix: [#19935] Part of old multiplayer name remains when entering a shorter name.
```
Comment (Broxzier) [inline distribution/changelog.txt:40]: This is a regression, so no changelog entry is necessary.

**Review by Broxzier — CHANGES_REQUESTED** [review]

File: distribution/changelog.txt (hunk 9 above)
Comment (Chase-Percy) [reply distribution/changelog.txt]: [82cbf57](https://github.com/OpenRCT2/OpenRCT2/pull/20004/commits/82cbf57ec61abe1fa39c3c88b40d44a22632766b)

File: src/openrct2-ui/windows/ServerList.cpp (hunk 6 above)
Comment (Broxzier) [reply src/openrct2-ui/windows/ServerList.cpp]: Generally it's best to pick a name that describes what a function does, not how it is used. That makes the intent much clearer at first glance.

File: src/openrct2-ui/windows/ServerList.cpp [hunk 10]
```diff
@@ -90,7 +92,8 @@ class ServerListWindow final : public Window
 
     void OnOpen() override
     {
-        window_server_list_widgets[WIDX_PLAYER_NAME_INPUT].string = _playerName;
+        _playerName = gConfigNetwork.PlayerName;
+        window_server_list_widgets[WIDX_PLAYER_NAME_INPUT].string = const_cast<utf8*>(_playerName.c_str());
```
Comment (Broxzier) [inline src/openrct2-ui/windows/ServerList.cpp:96]: This doesn't seem very safe. The buffer that `.c_str()` returns is not guaranteed to stay in place when the string changes. When it moves, this widget will point to garbage.

File: src/openrct2-ui/windows/ServerList.cpp [hunk 11]
```diff
@@ -127,7 +129,7 @@ class ServerListWindow final : public Window
                 Close();
                 break;
             case WIDX_PLAYER_NAME_INPUT:
-                WindowStartTextbox(*this, widgetIndex, STR_STRING, _playerName, 63);
+                WindowStartTextbox(*this, widgetIndex, STR_STRING, _playerName.c_str(), MaxPlayerNameLength);
```
Comment (Broxzier) [inline src/openrct2-ui/windows/ServerList.cpp:132]: Interesting that the max length in this call used to be 63, while the max name length was 32 characters.

File: src/openrct2-ui/windows/ServerList.cpp [hunk 12]
```diff
@@ -267,22 +269,17 @@ class ServerListWindow final : public Window
...
-
-                // Don't allow empty player names
-                if (_playerName[0] != '\0')
-                {
-                    gConfigNetwork.PlayerName = _playerName;
-                    ConfigSaveDefault();
-                }
+                _playerName = temp;
+                gConfigNetwork.PlayerName = _playerName;
+                window_server_list_widgets[WIDX_PLAYER_NAME_INPUT].string = const_cast<utf8*>(_playerName.c_str());
```
Comment (Broxzier) [inline src/openrct2-ui/windows/ServerList.cpp:282]: Since the buffer is also set here, I suppose that it's safe, but it's still bad design. One way to ensure that the buffer remains valid is to not use u8string's internal buffer directly.

Since the current implementation works, feel free to just leave this for now.

Comment (Chase-Percy) [reply src/openrct2-ui/windows/ServerList.cpp:282]: I guess it could just use a std array of uint8_t but yea I was just recommended to use the u8string instead of the original c style stuff that was there. What would be the ideal solution? I'm not sure how changing the underlying union in the widget stuff would affect things so I don't know if the solution would be in that area or not or something like I mentioned.

**Review by Broxzier — APPROVED** [review]
