### PR TITLE
Fix #8212: Crash when opening rides with changed mode and no tracks.

### LINKED ISSUE #8212: BACKTRACE 8e9b96 ride_find_track_gap
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/8e9b9635ed7c3b925ff5cbdc57ba85c42858878463a6fefeaa3520bcef7c1ba0?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Nov 02 2018 18:38:34)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> f8add7f: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ride_find_track_gap -> ride_is_valid_for_open -> RideSetStatusAction::Query -> GameActions::Query -> GameActions::Execute -> ride_set_status -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by ZehMatt**
The crash is mainly if the mode is set to something that has no tracks such as the Maze that would try to access null given that in an earlier function it would assign input.element to null given that there are no tracks. Also instead of trying to find the ride index over the tile element I simply pass it down from the beginning which makes more sense in my opinion.

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -1997,7 +1996,7 @@ int32_t ride_modify(CoordsXYE* input)
 
     if (ride_type_has_flag(ride->type, RIDE_TYPE_FLAG_CANNOT_HAVE_GAPS))
     {
-        if (ride_find_track_gap(&tileElement, &endOfTrackElement))
+        if (ride_find_track_gap(rideIndex, &tileElement, &endOfTrackElement))
```
[the remark this answers is not in the document]
Comment (ZehMatt) [reply src/openrct2/ride/Ride.cpp]: Good point actually

[the remark this answers is not in the document]
Comment (ZehMatt) [reply src/openrct2/ride/Ride.cpp]: Well I still have to pass rideIndex as that is required and it seems Ride does not store its own index, at least it can avoid getting the ride again in the new overload.

File: src/openrct2/ride/Ride.cpp [hunk 2]
```diff
@@ -816,18 +816,26 @@ bool track_block_get_previous(int32_t x, int32_t y, TileElement* tileElement, tr
...
-int32_t ride_find_track_gap(CoordsXYE* input, CoordsXYE* output)
+int32_t ride_find_track_gap(int32_t rideIndex, CoordsXYE* input, CoordsXYE* output)
 {
-    assert(input->element->GetType() == TILE_ELEMENT_TYPE_TRACK);
-    int32_t rideIndex = input->element->AsTrack()->GetRideIndex();
     Ride* ride = get_ride(rideIndex);
+    return ride_find_track_gap(ride, rideIndex, input, output);
+}
+
+int32_t ride_find_track_gap(Ride* ride, int32_t rideIndex, CoordsXYE* input, CoordsXYE* output)
```
Comment (Gymnasiast) [inline src/openrct2/ride/Ride.cpp]: If you're already passing `rideIndex`, there is no need to pass in `Ride` as well. You can just do `get_ride` with that `rideIndex`.

Comment (ZehMatt) [reply src/openrct2/ride/Ride.cpp]: The point was to avoid using get_ride twice, most callers already have the Ride obtained, rideIndex is however still required by the function and there seems to be no way to get the ride index from the Ride struct.

Comment (Broxzier) [reply src/openrct2/ride/Ride.cpp]: It seems unnecessary to pass both, though. `get_ride` doesn't take long to call (probably even gets inlined), or is this a step towards removing the index from calls, and having Rides store their own ID? If so, I'm not sure if that's really desirable, a value shouldn't care about its key.

Comment (ZehMatt) [reply src/openrct2/ride/Ride.cpp]: So what should be the final solution? Using get_ride over and over doesn't seem right either.

Comment (Gymnasiast) [reply src/openrct2/ride/Ride.cpp]: Just do `Ride* ride = get_ride(ride_index)` at the start?

Comment (ZehMatt) [reply src/openrct2/ride/Ride.cpp]: Alright, that leaves janisozaur suggestion, apparently I can't have it both ways.
