### PR TITLE
Fix #24952: Duplicate track designs when running via Steam without having RCT1 linked

### LINKED ISSUE #24952: Duplicate of tracks
### Operating System

Windows 11, Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.25 (de986f58fd) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When wanting to build a new ride the tracks show up 2 times per tracks (See attached screenshot).
I run a clean install of both RCT2 and OpenRCT2. RCT2 is installed under steam en OpenRCT2 under program files in my C drive.

When using the debug function it show that both entries point to the same file.
I tested this on a laptop and PC running windows 11 and a PC running windows 10. All with clean installs and all have tracks show up 2 times.

### Steps to reproduce

Have Windows 11.
Install RCT2 through steam.
Install OpenRCT2.
Try building a track and it should show duplicates in the list.

### Attachments

Image

### PR DESCRIPTION
**Pull request by Gymnasiast**
Thanks to "Moreau le Nam" on Discord for investigating.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Moreau le Nam just confirmed via Discord this fixes his issue.

File: src/openrct2/core/FileIndex.hpp [hunk 1]
```diff
@@ -144,6 +144,9 @@ class FileIndex
         std::vector<std::string> files;
         for (const auto& directory : SearchPaths)
         {
+            if (directory.empty())
+                continue;
```
Comment (AaronVanGeffen) [inline src/openrct2/core/FileIndex.hpp:148]: I think I'd prefer for an empty directory to not end up in this `SaearchPaths` vector in the first place... But it's fine, I suppose.

Comment (Gymnasiast) [reply src/openrct2/core/FileIndex.hpp:148]: Yeah, I get what you mean. I tried that, but couldn’t get it to work properly.
