### PR TITLE
Fix #16050: Scenery window positioning

### LINKED ISSUE #16050: Scenery window width not consider for initial position
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (15ee72a on develop)

### Describe the issue

Selecting more scenery groups than was previously possible makes the scenery window wider. This is not taken into account when the window is opened, causing part of the window to be off screen.

The window should be positioned at x = screen_width - scenery_window_width when opened.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Open Park
2. Select the maximum number of scenery groups
3. Open the scenery window. The scenery window will be partially off screen.

### Attachments

image

### PR DESCRIPTION
**Pull request by Broxzier**
This fix supersedes #16095. Some parts of that PR are used here, but many changes weren't necessary for the fix.

The scenery window already handles the number of tabs, but that is only known after construction, while the size of the window is already required by `WindowCreate`. This PR makes the position and size arguments of `WindowCreate` optional.

In this case, it removes the `WF_NO_SCROLLING` flag from the call to `WindowCreate`, but that seems to have no use for the scenery window anyway.

### CODE REVIEW

**Comment by tupaschoal** [comment]
Should we close the other PR, then?

**Comment by oli414** [comment]
Tested it, mostly works but I ran into a crash:
- Select all the vanilla scenery groups (including expansions)
- Open the scenery window
- Deselect all the vanilla scenery groups
- Open the scenery window
- Crash

This crash is not currently present on develop from the looks of it.

[Crash Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/8457190/Crash.Dump.zip)

**Comment by Broxzier** [comment]
@oli414 Nice find, but that bug actually _is_ present on develop. I was able to reproduce it by selecting some scenery from a tab (in your crashdump it was tab index 16 which is out of bounds).

**Comment by oli414** [comment]
@Broxzier Oh, I see, I must not have had an out of bounds tab selected when testing it on develop then.

Apart from the crash, it seemed to work as expected!

**Comment by Broxzier** [comment]
I've now added a fix the crash in this PR as well, and taken the additional refactoring changes from @Ian-Polito's PR.

**Review by oli414 — APPROVED** [review]

File: src/openrct2-ui/windows/Scenery.cpp [hunk 1]
```diff
@@ -1372,11 +1377,8 @@ void WindowScenerySetSelectedTab(const ObjectEntryIndex sceneryGroupIndex)
 // Used after removing objects, in order to avoid crashes.
 void WindowSceneryResetSelectedSceneryItems()
 {
-    auto* w = static_cast<SceneryWindow*>(window_find_by_class(WC_SCENERY));
-    if (w != nullptr)
-    {
-        w->ResetSelectedSceneryItems();
-    }
+    gWindowSceneryTabSelections.clear();
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Scenery.cpp:1380]: This will need to be reverted and fixed correctly. You aren't meant to access that global variable when the window is closed.

Comment (Broxzier) [reply src/openrct2-ui/windows/Scenery.cpp:1380]: But this list gets constructed when the window is initialized, if necessary. It's a global so that the current selection, per tab, is persistent. It cannot be part of the window class itself, since otherwise the last used scenery per tab is forgotten.
