### PR TITLE
Fix #11730, 11731: invalid read / write in plugin code

### LINKED ISSUE #11730: [90795a] openrct2.com: OpenRCT2::Ui::Windows::CustomListView::SortItems, OpenRCT2::Ui::Windows::RefreshWidgets, OpenRCT2::Ui:...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/90795ae165b0b56a5b6c27dc995793ba9eb8163649ddf63fc823eb62f91a0ed4">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-write</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
OpenRCT2::Ui::Windows::CustomListView::SortItems
OpenRCT2::Ui::Windows::RefreshWidgets
OpenRCT2::Ui::Windows::window_custom_open
OpenRCT2::Scripting::ScUi::openWindow
dukglue::detail::MethodInfo<0,OpenRCT2::Scripting::ScUi,std::shared_ptr<OpenRCT2::Scripting::ScWindow>,DukValue>::MethodRuntime::call_native_method
duk__js_execute_bytecode_inner
duk_js_execute_bytecode
duk__handle_call_raw
duk__pcall_raw
duk_handle_safe_call(duk_hthread *,
duk_pcall
OpenRCT2::Scripting::Plugin::Start
OpenRCT2::Scripting::ScriptEngine::StartPlugins
OpenRCT2::Context::Update
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

File: src/openrct2-ui/scripting/CustomListView.cpp [hunk 1]
```diff
@@ -317,7 +317,10 @@ void CustomListView::SortItems(int32_t column, ColumnSortOrder order)
 
     CurrentSortOrder = order;
     CurrentSortColumn = column;
-    Columns[column].SortOrder = order;
+    if (Columns.size() != 0)
```
Comment (Gymnasiast) [inline src/openrct2-ui/scripting/CustomListView.cpp:320]: Perhaps also check if `column < Columns.size()`.

Comment (IntelOrca) [reply src/openrct2-ui/scripting/CustomListView.cpp:320]:
```suggestion
    if (column < Columns.size())
```
