### PR TITLE
Fix #5803: Null map element in onridephoto

### LINKED ISSUE #5803: Random crashes
**OS:** WIndows 7
**Version:** 0.0.8
**Commit/Build:** 446796d

I'm getting random crashes for reasons I cannot figure out. But I am starting to get .dmp files to upload for someone to look. When I load a local game with the same map, No issues. This happened with the previous build as well. Attached is my .dmp and save file.

[2da0c111-5548-4b44-9c84-fd503c98955c.zip](https://github.com/OpenRCT2/OpenRCT2/files/1126340/2da0c111-5548-4b44-9c84-fd503c98955c.zip)

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

File: src/openrct2/world/map_animation.c [hunk 1]
```diff
@@ -312,6 +312,8 @@ static bool map_animation_invalidate_track_onridephoto(sint32 x, sint32 y, sint3
 
     mapElement = map_get_first_element_at(x >> 5, y >> 5);
     do {
+        if (mapElement == NULL)
+            return false;
```
Comment (janisozaur) [inline src/openrct2/world/map_animation.c]: I don't know what this value really means.

Comment (IntelOrca) [inline src/openrct2/world/map_animation.c]: I think it is supposed to return true if the animation should be removed from the animation list.
