### PR TITLE
Fix #21591: Banner text colors are not working properly

### LINKED ISSUE #21591: Banner text colors are not working properly
### Operating System

*

### OpenRCT2 build

OpenRCT2, v0.4.9 (470667e)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The text color for banners currently don't work properly that is due to the scrolling text cache not considering the contents of the text and only compares the Formatter data, since the buffer was moved into Banner the pointer is stable and that is what is stored in the Formatter, most of the time so it will consider the banner text to be identical while the content of the text is not. The way the cache works needs to be refactored and should not use the formatter arguments but rather the text, overall the code for the caching is not in the best shape and requires some overhaul. There seems to be also a problem in how the cache stores the data, for some reason everything ended up at the end while debugging the code, this means every time it asks for the banner cache it will have to iterate over empty slots first before it hits the cache entry which is a waste of CPU cycles, its best to just use some pre-existing LRU container and not re-invent the wheel.

### Steps to reproduce

1. Place a banner.
2. Change the text color.
3. Sometimes it doesn't change the color, sometimes rotating the view changes it, its inconsistent.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by janisozaur**
Add colour to cache hash

This only addresses the "banners not working" part, updating cache LRU will be filed as another issue.

### CODE REVIEW

**Comment by janisozaur** [comment]
This is a view-only thing, no need to update network version here.

File: src/openrct2/actions/BannerSetStyleAction.cpp [hunk 1]
```diff
@@ -163,5 +163,8 @@ GameActions::Result BannerSetStyleAction::Execute() const
     intent.PutExtra(INTENT_EXTRA_BANNER_INDEX, _bannerIndex);
     ContextBroadcastIntent(&intent);
 
+    ScrollingTextInvalidate();
```
Comment (ZehMatt) [inline src/openrct2/actions/BannerSetStyleAction.cpp:166]: The only reason to why the banner colors work now is because of this line, TTF does not process the color and adding color to the cache doesn't make any sense. The problem is the cache used in ScrollingTextSetup.

**Review by ZehMatt — CHANGES_REQUESTED** [review]
Revert the TTF part, we can use the invalidation as a temporary work-around.

**Review by ZehMatt — APPROVED** [review]
It should be noted that this isn't a real fix but hides the issue, I'm fine with it for the moment.
