### PR TITLE
Fix #20433. Dropdown default selections not working

### LINKED ISSUE #20433: Cannot cycle through trains/views by single-clicking into dropdown menu in main ride window
### Operating System

Linux (probably irrelevant)

### OpenRCT2 build

latest develop (97427743a4ace9f16ebd913ed418d524cb6bc9d9)
Update: Bug occurs first in ce1695fab84e8be09df98686fff2cd057cb5ec2a

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

In the main view of the ride window, it used to be possible to cycle through all possible views (different trains, stations, "overall view") just by clicking once into the dropdown menu. (I.e., one single click would simply jump to the next view.)

Currently, this is not possible anymore.
(Instead, one has to now actually open/use the dropdown menu by holding the mouse button, moving the cursor to the desired view and then releasing it.)

### Steps to reproduce

Open any park with at least one tracked ride.
Single-click into the "overall view" / "train 1" / "train 2" / etc dropdown and notice that nothing happens. (Don't open the menu by holding the mouse button, just click and release immediately.)

### Attachments

menu0
menu1
(This is the menu I'm talking about.)

### PR DESCRIPTION
**Pull request by duncanspumpkin**
This fixes it for rides but it is also an issue effecting a few different dropdowns.

Not sure if this warrants a changelog there is more than just the ride window that had default behaviour when clicking the dropdown that was missing.

### CODE REVIEW

File: src/openrct2-ui/windows/GuestList.cpp [hunk 1]
```diff
@@ -381,6 +381,10 @@ class GuestListWindow final : public Window
 
     void OnDropdown(WidgetIndex widgetIndex, int32_t dropdownIndex) override
     {
+        if (dropdownIndex == -1)
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/GuestList.cpp:384]: I've added protetion for -1 dropdownIndex for all windows this PR just adds it to the small selection of windows that were missing it.

**Review by ZehMatt — APPROVED** [review]

**Review by Broxzier — APPROVED** [review]

File: src/openrct2-ui/windows/GuestList.cpp (hunk 1 above)
Comment (duncanspumpkin) [reply src/openrct2-ui/windows/GuestList.cpp:384]: Perhaps i worded this wrong. There are a selection of windows that when it receives -1 it enters a default behaviour mode. The rest of the windows should just return on -1. I've reviewed every single dd event and ensured that the ones that don't have a default event have the return so in the process I've added a few missing returns. I can't see any way you could remove the returns unless you split the dd event into two but that's a bit messy.
