### PR TITLE
Catch exceptions when loading groups.json

### LINKED ISSUE #3899: Game crashes after hosting my server
**OS: Windows 7 Home Premium x64 SP1 with Windows 8.1 UI** 
**Version:0.0.5-11**
**Commit/Build: fd13c20**

When I tried to host my server, the game crashes. I am trying to host my OpenRCT2 server after awhile. I don't want to disappoint my fans by not hosting my server after making an announcement in my Steam group. Can any developers please fix this bug? 

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Launch OpenRCT2
2. Host a server
3. See if you get the same issue as me

**Dump file**
[Crash 617.zip](https://github.com/OpenRCT2/OpenRCT2/files/321480/Crash.617.zip)

### PR DESCRIPTION
**Pull request by janisozaur**
Fixes #3899

### CODE REVIEW

File: src/network/network.cpp [hunk 1]
```diff
@@ -839,33 +863,16 @@ void Network::LoadGroups()
 	platform_get_user_directory(path, NULL);
 	strcat(path, "groups.json");
 
-	if (!platform_file_exists(path)) {
+	json_t * json = nullptr;
+	try {
+		json = Json::ReadFromFile(path);
+	} catch (const std::exception& e) {
```
Comment (IntelOrca) [inline src/network/network.cpp]: Use Exception instead which is inherits std::exception. This is to cope with MSVC / GCC, Clang differences.

**Comment by janisozaur** [comment]
done

File: src/network/network.cpp [hunk 2]
```diff
@@ -839,33 +863,16 @@ void Network::LoadGroups()
 	platform_get_user_directory(path, NULL);
 	strcat(path, "groups.json");
 
-	if (!platform_file_exists(path)) {
+	json_t * json = nullptr;
+	try {
+		json = Json::ReadFromFile(path);
+	} catch (const Exception& e) {
+		log_error("Failed to read %s as JSON. Setting default groups. %s", path, e.what());
```
Comment (IntelOrca) [inline src/network/network.cpp]: e.GetMsg()

Comment (janisozaur) [inline src/network/network.cpp]: done as well, but `what`, `GetMsg` and `GetMessage` look almost exactly the same. Why do we have three versions of it?

Comment (IntelOrca) [inline src/network/network.cpp]: windows.h annoyingly defines a GetMessage macro, I didn't use what() because it wasn't UpperCamelCase, and GetMsg was just a temporary workaround for the GetMessage macro issue.
