### PR TITLE
Fix #17508: Grid Doesn't Disable After Setting Patrol Area

### LINKED ISSUE #17508: Grid Doesn't Disable After Setting Patrol Area
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-6-g5601282 (5601282 on develop) provided by GitHub

### Describe the issue

When I have Display Gridlines disabled in the options menu, they get stuck turned on again whenever I set a staff member's patrol area.

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Disable Display Gridlines in the options menu.
2. Set a staff member's patrol area, the gridlines display like they should.
3. The gridlines don't turn off again after you've finished, leaving them stuck on.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by jazzysoggy**
Fix #17508

Issue: When display gridlines option is disabled in the options menu, setting a staff's patrol area will display gridlines even after closing the patrol area window.

Fix: Added an additional hide_gridlines() function call if tool_set(this, 0, Tool::WalkDown) returns not true, as show_gridlines() is called twice if that returns not true, while hide_gridlines() originally would only be called once.

### CODE REVIEW

File: src/openrct2-ui/windows/PatrolArea.cpp [hunk 1]
```diff
@@ -190,6 +190,8 @@ class PatrolAreaWindow final : public Window
     void OnToolAbort(rct_widgetindex widgetIndex) override
     {
         hide_gridlines();
+        if (!tool_set(this, 0, Tool::WalkDown))
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/PatrolArea.cpp:193]: This is asking for trouble. If the window is closed then the tool is cancelled and then you recreate the tool on a window that is being destroyed leaving a dangling tool???

**Review by duncanspumpkin — CHANGES_REQUESTED** [review]
This looks wrong none of the changes make sense.

File: src/openrct2-ui/windows/Staff.cpp [hunk 2]
```diff
@@ -1160,6 +1160,8 @@ class StaffWindow final : public Window
             viewport_flags = 0;
             if (gConfigGeneral.always_show_gridlines)
                 viewport_flags |= VIEWPORT_FLAG_GRIDLINES;
+            else
+                viewport_flags &= ~VIEWPORT_FLAG_GRIDLINES;
```
[the remark this answers is not in the document]
Comment (jazzysoggy) [reply src/openrct2-ui/windows/Staff.cpp]: Remove redundant flag clear

File: src/openrct2-ui/windows/PatrolArea.cpp (hunk 1 above)
Comment (jazzysoggy) [reply src/openrct2-ui/windows/PatrolArea.cpp]: So, should I remove this hide_gridlines and instead remove the extra show_gridlines that is run when the tool is enabled?

**Review by duncanspumpkin — APPROVED** [review]
That looks good now. Can you add a changelog entry

**Comment by duncanspumpkin** [comment]
Could you rebase this to resolve the changelog conflict.

File: distribution/changelog.txt [hunk 3]
```diff
@@ -13,6 +13,7 @@
 - Fix: [#17444] “Manta Ray” boats slowed down too much in “Ayers Rock” scenario (original bug).
 - Fix: [#17503] Parks with staff with an ID of 0 have all staff windows focus on that staff
 - Fix: [#17553] Crash when moving invention list items to empty list
+- Fix: [#17508] Grid Doesn't Disable After Setting Patrol Area.
```
Comment (Broxzier) [inline distribution/changelog.txt:16]:
```suggestion
- Fix: [#17508] Grid doesn’t disable after setting patrol area.
```

**Review by Broxzier — CHANGES_REQUESTED** [review]

**Review by Broxzier — APPROVED** [review]
