### PR TITLE
Fix #14155, #15994: Map Generator places non-tree objects as trees

### LINKED ISSUE #14155: Curved wall seems to be treated as tree in scenario editor
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 18e8690

``Curved wall`` is placed everywhere in the scenario editor.
I didn't check the object's detailed spec but I think it is considered as a tree object.
But as I know, there are many objects that is treated as a tree even it is not look like a tree.
So I'm not sure it is solvable currently, but I write an issue since it seems that there is no such reported one.

**Steps to reproduce:**
1. Open scenario editor
2. Click "Forward to Next Step:" without (un)checking any items in Object selection window
3. Click [Map generation] button
4. Be sure that ``Place tree`` is checked.
5. Generate the map

**Screenshots / Video:**
image

### PR DESCRIPTION
**Pull request by Gymnasiast**
Caused by a combination of two factors:
- The tree identifiers have changed, so it can’t find any tree.
- The object in slot 0 was always considered as a tree (#14155)

### CODE REVIEW

File: src/openrct2/world/MapGen.cpp [hunk 1]
```diff
@@ -279,9 +279,9 @@ static bool MapGenSurfaceTakesSnowTrees(const TerrainSurfaceObject& surface)
  */
 static void mapgen_place_trees()
 {
-    std::vector<int32_t> grassTreeIds(std::size(GrassTrees), 0);
-    std::vector<int32_t> desertTreeIds(std::size(DesertTrees), 0);
-    std::vector<int32_t> snowTreeIds(std::size(SnowTrees), 0);
+    std::vector<int32_t> grassTreeIds(std::size(GrassTrees), OBJECT_ENTRY_INDEX_NULL);
```
Comment (duncanspumpkin) [inline src/openrct2/world/MapGen.cpp:282]: what is this code doing? I can't understand why it is prepopulating it with nulls.

Comment (duncanspumpkin) [reply src/openrct2/world/MapGen.cpp:282]: Yup just checked this and this is wrong. Can you delete the initialisation of this with any value. The vectors should be all 0. Its artificially reducing the amount of trees.

Comment (duncanspumpkin) [reply src/openrct2/world/MapGen.cpp]: As I had everything running I've made the changes myself and added it as an additional commit.
