### PR TITLE
Fix #5865: input being handled too early

### LINKED ISSUE #5865: Ride preview shadow flickers when trying to build on uneven terrain or in the air
**OS:** [Windows 10]
**Version:** [0.0.8]
**Commit/Build:** [ae282f7]

The ride preview shadow flickers when the cursor isn't on a tile with flat terrain. See [this video](https://www.youtube.com/watch?v=LuYb_74RSuU&feature=youtu.be) for what I mean exactly. I only noticed it today, so it must be a new bug.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Do what I did in the video.

### PR DESCRIPTION
**Pull request by ZehM4tt**
This is a regression from #60bf508, I moved the input behind the logic which appears to be causing objects to flicker. The upside is there are no new desyncs moving it back to where it initially was. Should fix the issue #5865

### CODE REVIEW

File: src/openrct2/game.c [hunk 1]
```diff
@@ -317,6 +317,25 @@ void game_update()
         network_process_game_commands();
     }
 
+    // Update the game one or more times
+    for (i = 0; i < numUpdates; i++) {
```
Comment (janisozaur) [inline src/openrct2/game.c]: doesn't look like loop counter is being used outside of the loop. Can you move variable declaration into the loop? `for (int i…`

File: distribution/changelog.txt [hunk 2]
```diff
@@ -17,6 +17,7 @@
 - Fix: [#5977] Custom music files not showing up in music list
 - Fix: [#5981] Ride list doesn't update after using quick demolish.
 - Fix: [#5984] Allow socket binding to same port after crash
+- Fix: [#5865] Ride preview flickering on uneven terrain or mid air.
```
Comment (IntelOrca) [inline distribution/changelog.txt]: Changelog should be in # order

**Comment by IntelOrca** [comment]
Please make your commit message `Fix #5865: input being handled too early` as well as the PR name.
