### PR TITLE
Fix #24077: Track Designer crashes when clicking the park fence

### LINKED ISSUE #24077: Track Designer crashes when clicking the park fences
### Operating System

Ubuntu 24.04

### OpenRCT2 build

cdb4e659dc0d93a256654738789c77f10a0de59e

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

It appears to be related to the peep animations, probably because it needs them for the window preview. I’ll hazard a guess that they’re not selected.

### Steps to reproduce

1. Open the Track Designer
2. Click the park fence
3. Crash.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
This fixes the issue by having the Track Designer and Scenario Editor share a list of objects (with the Scenario Editor adding a few of its own on top).

When testing, also noticed another bug in the Track Designs Manager, but that’s something for another PR.

### CODE REVIEW

File: src/openrct2/object/DefaultObjects.cpp [hunk 1]
```diff
@@ -11,65 +11,27 @@
 
 #include "Object.h"
 
-// clang-format off
-const std::string_view MinimumRequiredObjects[] = { "rct2.terrain_surface.grass", "rct2.terrain_edge.rock" };
+const std::array<std::string_view, 3> kMinimumRequiredObjects = {
```
Comment (ZehMatt) [inline src/openrct2/object/DefaultObjects.cpp:14]:
```suggestion
constexpr std::array<std::string_view, 3> kMinimumRequiredObjects = {
```

File: src/openrct2/object/DefaultObjects.cpp [hunk 2]
```diff
@@ -11,65 +11,27 @@
...
+    "rct2.terrain_surface.grass",
+    "rct2.terrain_edge.rock",
+
+    "rct2.station.plain",
+};
 
-const std::string_view DefaultSelectedObjects[] = {
+const std::array<std::string_view, 82> kCommonScenarioAndTrackDesignerObjects = {
```
Comment (ZehMatt) [inline src/openrct2/object/DefaultObjects.cpp:21]:
```suggestion
constexpr std::array<std::string_view, 82> kCommonScenarioAndTrackDesignerObjects = {
```

File: src/openrct2/object/DefaultObjects.cpp [hunk 3]
```diff
@@ -158,53 +120,47 @@ const std::string_view DefaultSelectedObjects[] = {
...
-    "rct2.scenery_group.scgshrub", // Scenery: Shrubs and Ornaments
-    "rct2.scenery_group.scggardn", // Scenery: Gardens
-    "rct2.scenery_group.scgfence", // Scenery: Fences and Walls
-    "rct2.scenery_group.scgwalls", // Scenery: Walls and Roofs
-    "rct2.scenery_group.scgpathx", // Scenery: Signs and Items for Footpaths
-    "rct2.water.wtrcyan",          // Water: Natural Water
-    "rct2.park_entrance.pkent1",   // Park Entrance: Traditional Park Entrance
-    "rct2.terrain_surface.grass",
-    "rct2.terrain_edge.rock",
+const std::array<std::string_view, 37> kDefaultScenarioObjects = {
```
Comment (ZehMatt) [inline src/openrct2/object/DefaultObjects.cpp:123]:
```suggestion
constexpr std::array<std::string_view, 37> kDefaultScenarioObjects = {
```

File: src/openrct2/object/DefaultObjects.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/object/DefaultObjects.cpp:14]: That would require me to move them to the .h file, right?

Comment (AaronVanGeffen) [reply src/openrct2/object/DefaultObjects.cpp:14]: No, it just means it gets initialised at compile time instead of at runtime.

Comment (Gymnasiast) [reply src/openrct2/object/DefaultObjects.cpp]: Ah, I see. Updated it.

File: src/openrct2/object/DefaultObjects.cpp [hunk 4]
```diff
@@ -158,53 +120,47 @@ const std::string_view DefaultSelectedObjects[] = {
...
-    "rct2.scenery_group.scggardn", // Scenery: Gardens
-    "rct2.scenery_group.scgfence", // Scenery: Fences and Walls
-    "rct2.scenery_group.scgwalls", // Scenery: Walls and Roofs
-    "rct2.scenery_group.scgpathx", // Scenery: Signs and Items for Footpaths
-    "rct2.water.wtrcyan",          // Water: Natural Water
-    "rct2.park_entrance.pkent1",   // Park Entrance: Traditional Park Entrance
-    "rct2.terrain_surface.grass",
-    "rct2.terrain_edge.rock",
+constexpr std::array<std::string_view, 37> kDefaultScenarioObjects = {
+
```
Comment (AaronVanGeffen) [inline src/openrct2/object/DefaultObjects.cpp:124]: Stray whitespace?

**Review by AaronVanGeffen — APPROVED** [review]
This indeed fixes the issue. Nice work.
