### PR TITLE
Fix #3832: Track piece colour scheme paint not network-safe

### LINKED ISSUE #3832: Multiplayer - Tracked Rides Alternate Color Painting Doesn't Show Changes to Other Clients
If this is a duplicate, sorry!

**OS:** Windows 8.1
**Version:** 0.0.5
**Commit:** 3dc4b601b8327082c5f5b022c4713d62ce2fa1a5

When painting pieces of a tracked ride an alternate color, this data doesn't get sent to the server and other clients connected.
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Build a tracked ride in multiplayer
2. Define an alternate color scheme
3. Paint a piece of the tracked ride with the alternate color scheme
4. Others can't see the change but you can

**Dump file**
N/A

**Screenshots / Video:**
N/A

**Save game:**
N/A

### PR DESCRIPTION
**Pull request by Gymnasiast**
This is the first time I implemented a Game Action, and it has been quite tricky. I expect there will be a lot of things I didn't do correctly. However, I have tested it and it does work.

### CODE REVIEW

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -4286,7 +4288,8 @@ static void window_ride_set_track_colour_scheme(rct_window* w, int32_t x, int32_
 
     z = tileElement->base_height * 8;
     direction = tileElement->GetDirection();
-    sub_6C683D(&x, &y, &z, direction, tileElement->AsTrack()->GetTrackType(), newColourScheme, nullptr, 4);
+    auto gameAction = RideSetColourSchemeAction(x, y, z, direction, tileElement->AsTrack()->GetTrackType(), newColourScheme);
+    auto result = GameActions::Execute(&gameAction);
```
Comment (IntelOrca) [inline src/openrct2-ui/windows/Ride.cpp]: `result` is unused

File: src/openrct2/actions/RideSetColourScheme.hpp [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+struct RideSetColourSchemeAction : public GameActionBase<GAME_COMMAND_SET_COLOUR_SCHEME, GameActionResult>
+{
+private:
+    int32_t _x, _y, _z, _direction, _trackType;
+    uint16_t _newColourScheme;
+
+public:
+    RideSetColourSchemeAction()
+    {
```
Comment (janisozaur) [inline src/openrct2/actions/RideSetColourScheme.hpp]: This will leave all the member fields uninitialised. Provide initialisers for them. Additionally, don't create empty constructor, make it a `= default`ed one.

File: src/openrct2/actions/RideSetColourScheme.hpp [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+#include "../ride/Ride.h"
+#include "../world/Park.h"
+#include "../world/Sprite.h"
+#include "GameAction.h"
+
+struct RideSetColourSchemeAction : public GameActionBase<GAME_COMMAND_SET_COLOUR_SCHEME, GameActionResult>
+{
+private:
+    int32_t _x, _y, _z, _direction, _trackType;
+    uint16_t _newColourScheme;
```
Comment (janisozaur) [inline src/openrct2/actions/RideSetColourScheme.hpp]: All of these fields should be `const`

File: src/openrct2/actions/RideSetColourScheme.hpp (hunk 2 above)
Comment (janisozaur) [reply src/openrct2/actions/RideSetColourScheme.hpp]: Actually, is there any need for a default ctor? It doesn't seem to be a valid use case, so perhaps it should be disabled?

File: src/openrct2/actions/RideSetColourScheme.hpp (hunk 3 above)
Comment (janisozaur) [reply src/openrct2/actions/RideSetColourScheme.hpp]: Ugh, we can't make them const because https://github.com/OpenRCT2/OpenRCT2/pull/8138 needs them the way they are. I'll see if I can come up with a change to address that at some later point.

File: src/openrct2/actions/RideSetColourScheme.hpp (hunk 2 above)
Comment (janisozaur) [reply src/openrct2/actions/RideSetColourScheme.hpp]: I checked and it can't be disabled due to conflicts with https://github.com/OpenRCT2/OpenRCT2/pull/8138. Please provide initialisers for member fields and make this ctor defaulted anyway.

File: src/openrct2/actions/RideSetColourScheme.hpp [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+#include "../management/Finance.h"
+#include "../ride/Ride.h"
+#include "../world/Park.h"
+#include "../world/Sprite.h"
+#include "GameAction.h"
+
+struct RideSetColourSchemeAction : public GameActionBase<GAME_COMMAND_SET_COLOUR_SCHEME, GameActionResult>
+{
+private:
+    int32_t _x, _y, _z, _direction, _trackType;
```
Comment (janisozaur) [inline src/openrct2/actions/RideSetColourScheme.hpp]:
```suggestion
    int32_t _x{}, _y{}, _z{}, _direction{}, _trackType{};
```

File: src/openrct2/actions/RideSetColourScheme.hpp (hunk 3 above)
Comment (janisozaur) [inline src/openrct2/actions/RideSetColourScheme.hpp]:
```suggestion
    uint16_t _newColourScheme{};
```

**Comment by janisozaur** [comment]
BTW, there's no build on travis-ci for this PR, please rebase to trigger it.

File: src/openrct2/actions/RideSetColourScheme.hpp [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+    GameActionResult::Ptr Query() const override
+    {
+        return std::make_unique<GameActionResult>();
+    }
+
+    GameActionResult::Ptr Execute() const override
+    {
+        GameActionResult::Ptr res = std::make_unique<GameActionResult>();
+        res->ExpenditureType = RCT_EXPENDITURE_TYPE_RIDE_CONSTRUCTION;
+        res->ErrorTitle = STR_CANT_SET_COLOUR_SCHEME;
```
Comment (janisozaur) [inline src/openrct2/actions/RideSetColourScheme.hpp]: You set the error title here, but is this error occurring at any point?

**Comment by janisozaur** [comment]
Shouldn't there be some code (old game command) deleted in this PR?

**Comment by Gymnasiast** [comment]
No, because this action was never network safe.

**Comment by janisozaur** [comment]
So it wasn't a game command in the first place?

**Comment by Gymnasiast** [comment]
Exactly.

File: src/openrct2/actions/RideSetColourScheme.hpp (hunk 5 above)
Comment (Gymnasiast) [reply src/openrct2/actions/RideSetColourScheme.hpp]: No. Or not yet, anyway. I figured it might come in handy if more checks need to be implemented later.

**Comment by Gymnasiast** [comment]
@janisozaur Are you OK with merging this?

File: src/openrct2/actions/RideSetColourScheme.hpp (hunk 5 above)
Comment (janisozaur) [reply src/openrct2/actions/RideSetColourScheme.hpp]: Remove it then? Provide a comment? Either way, I'm not very fussed about it.
