### PR TITLE
get_ride_queue_end() fails for some ride queues

### LINKED ISSUE #3541: Broken peep AI: peeps are heading for entrance huts, not queue entrances
See title. In the original game, peeps could find the rides alright, heading for the queue entrance as they should. This gives a lot of problems, unsolvable without redoing entire park sections, when peeps are getting stuck in a corner somewhere because their AI changed from when the area was originally built. In general, this AI mechanic limits park composition a lot. I hope you can solve this soon, because it's the only thing in OpenRCT that ruins my fun occassionally. The other bugs are so minor I can live with them, and the beneifts of Open more than compensate for them. This one though... renders parks made before OpenRCT unusable.

### PR DESCRIPTION
**Pull request by zaxcav**
get_ride_queue_end() fails if any tile in the queue goes up towards the station entry.

In this situation the pathfinding goal is set to the station entry location rather than the queue end location.

This fixes #3541.

### CODE REVIEW

File: src/peep/peep.c [hunk 1]
```diff
@@ -9267,7 +9267,7 @@ static void get_ride_queue_end(sint16 *x, sint16 *y, sint16 *z){
 				if (!footpath_element_is_sloped(mapElement))
 					break;
 
-				if (footpath_element_get_slope_direction(mapElement) != direction)
+				if (footpath_element_get_slope_direction(mapElement) != (direction ^ 2))
 					break;
```
Comment (duncanspumpkin) [inline src/peep/peep.c]: Line 9258 should that not also be ^2

Comment (zaxcav) [inline src/peep/peep.c]: No.  Line 9258 is the case where the queue path slopes up in direction, so the base height doesn't change respective of the level from the previous tile.  Line 9270 is the case where the queue path slopes down in direction (i.e. slopes up in the reverse direction ... towards the entrance), so it's base height is -2 respective to the previous tile.

I tested this out with the "problematic" ride in the save game from #3541 whose queue goes both up and down and this correctly gets the queue end.
