### PR TITLE
Fix #7601: Always-researched items not rendered with inset

### LINKED ISSUE #7601: Visual bug in the invention list
#7562 introduced a visual bug in the invention list:

The (always researched) items in the upper list should be rendered _INSET_

**Steps to reproduce:**
1.  compare pre #7562(1a2958df843f1f3342191e1217d7fe1e0c225db9) with current development(df1e8af73708acf53da3d9e75d3401aa5f7fe284)
2.  The items in the upper list are currently rendered with the incorrect font.

**Screenshots / Video:**
image

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This re-introduces the use of buffers to work around colours being reset. They were previously removed in 1a2958df843f1f3342191e1217d7fe1e0c225db9.

For clipping strings, we also now manually invoke `gfx_clip_string` instead of relying on `gfx_draw_string_left_clipped` to do it for us. The latter resets the current font, meaning it prevents the use of `MEDIUM_EXTRA_DARK` bases. This issue should be addressed in a later commit.

screenshot_20180608_183542

### CODE REVIEW

File: src/openrct2-ui/windows/EditorInventionsList.cpp [hunk 1]
```diff
@@ -773,39 +773,52 @@ static void window_editor_inventions_list_scrollpaint(rct_window *w, rct_drawpix
...
-
-            // Vehicle name
-            gfx_draw_string_left_clipped(dpi, STR_BLACK_STRING, &itemNameId, colourFlags, left + columnSplitOffset, top, columnSplitOffset);
+            format_string(groupNamePtr, 256, STR_INVENTIONS_LIST_RIDE_AND_VEHICLE_NAME, (void*) &rideGroupName);
+            format_string(vehicleNamePtr, 256, itemNameId, nullptr);
         }
         else
         {
-            gfx_draw_string_left_clipped(dpi, STR_BLACK_STRING, &itemNameId, colourFlags, left, top, boxWidth);
+            format_string(groupNamePtr, 256, itemNameId, nullptr);
```
Comment (IntelOrca) [inline src/openrct2-ui/windows/EditorInventionsList.cpp]: `sizeof(groupNameBuffer)`

File: src/openrct2-ui/windows/EditorInventionsList.cpp [hunk 2]
```diff
@@ -773,39 +773,52 @@ static void window_editor_inventions_list_scrollpaint(rct_window *w, rct_drawpix
...
-                rideGroupName,
-            };
-
-            // Group name
-            gfx_draw_string_left_clipped(dpi, STR_BLACK_STRING, &args, colourFlags, left, top, columnSplitOffset);
-
-            // Vehicle name
-            gfx_draw_string_left_clipped(dpi, STR_BLACK_STRING, &itemNameId, colourFlags, left + columnSplitOffset, top, columnSplitOffset);
+            format_string(groupNamePtr, 256, STR_INVENTIONS_LIST_RIDE_AND_VEHICLE_NAME, (void*) &rideGroupName);
+            format_string(vehicleNamePtr, 256, itemNameId, nullptr);
```
Comment (IntelOrca) [inline src/openrct2-ui/windows/EditorInventionsList.cpp]: `sizeof(groupNameBuffer)`
`sizeof(vehicleNameBuffer)`
