### PR TITLE
Fix #6460: Crash when reading corrupt object files

### LINKED ISSUE #6460: Crash when reading corrupt object files
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 202244e]

This .DAT file makes OpenRCT2 crash on loading. I doubt the .DAT is configured incorrectly, as it was generated with X7123M3-256's ride generator.

[the big one.zip](https://github.com/OpenRCT2/OpenRCT2/files/1381400/the.big.one.zip)

**Steps to reproduce:**
1.  Place the included .DAT in your `object` folder
2.  Start OpenRCT2

image

image

### PR DESCRIPTION
**Pull request by IntelOrca**
Move / copy sawyer decoding functions to SawyerChunkReader and replace assertions with exceptions in the process to prevent access violations when reading corrupt chunks.

### CODE REVIEW

File: src/openrct2/rct12/SawyerChunkReader.cpp [hunk 1]
```diff
@@ -120,3 +124,125 @@ void SawyerChunkReader::ReadChunk(void * dst, size_t length)
         }
     }
 }
+
+size_t SawyerChunkReader::DecodeChunk(void * dst, size_t dstCapacity, const void * src, const sawyercoding_chunk_header &header)
+{
+    size_t resultLength;
+    switch (header.encoding) {
```
Comment (Gymnasiast) [inline src/openrct2/rct12/SawyerChunkReader.cpp]: Brace should go... (you know the drill)

File: src/openrct2/rct12/SawyerChunkReader.cpp [hunk 2]
```diff
@@ -120,3 +124,125 @@ void SawyerChunkReader::ReadChunk(void * dst, size_t length)
...
+            throw SawyerChunkException(EXCEPTION_MSG_DESTINATION_TOO_SMALL);
+        }
+        Memory::Copy(dst, src, header.length);
+        resultLength = header.length;
+        break;
+    case CHUNK_ENCODING_RLE:
+        resultLength = DecodeChunkRLE(dst, dstCapacity, src, header.length);
+        break;
+    case CHUNK_ENCODING_RLECOMPRESSED:
+    {
```
Comment (Gymnasiast) [inline src/openrct2/rct12/SawyerChunkReader.cpp]: Should be further indented.

**Comment by Gymnasiast** [comment]
I know you're referencing the original issue name, but wouldn't `Fix #6460: Crash when reading corrupt object files` be a lot better for a commit message?

**Comment by janisozaur** [comment]
Yup, I'm with @gymnasiast on that commit message. Rename the original issue if needed.

**Comment by IntelOrca** [comment]
What commit message? That is just the name of the PR.

**Comment by mrtnptrs** [comment]
This also fixes issue #6463 OpenRCT2 doesn't crash anymore.

**Comment by Gymnasiast** [comment]
Can you fix the formatting?

```
switch (var)
{
case 1:
{
...
```
^ makes little sense.

**Comment by IntelOrca** [comment]
That is the correct way to format it (much more common than the way you are suggesting). I don't think clang format has a way to format it differently. The only alternative is to indent the case labels.

**Comment by Gymnasiast** [comment]
That is not correct, that is madness. After a brace, an indent follows. The case labels are the only exception.
It just makes no bloody sense having two braces on the same indentation level.

**Comment by IntelOrca** [comment]
I can't get clang format to do it the way you are suggesting unless I make it indent the case labels as well.

**Comment by Gymnasiast** [comment]
So we ourselves be dictated by what clang-format can do? I thought we had code rules that helped readability, not rules to satisfy clang-format.

**Comment by IntelOrca** [comment]
I thought we had moved to clang format rules now?

I agree that it shouldn't modify tables, but if it can't format a switch block the way we want it kind of defeats the point in having it at all.

**Comment by Gymnasiast** [comment]
> I thought we had moved to clang format rules now?

Not as far as I know. I don't recall that being discussed in the team chat at all, much less agreeing to it.

> if it can't format a switch block the way we want it kind of defeats the point in having it at all.

That's my point indeed. Clang-format appears to be a bit too inflexible. You can configure it, but not everything can be set.

**Comment by IntelOrca** [comment]
We haven't discussed or agreed on what the format should be for switch. I think it should have the case labels indented because it looked strange now not having the labels indented when the switch brace is on its own line.

In the meantime I have removed the braces altogether from this PR.
