### PR TITLE
 Fix: #22185 Set nausea and intensity after test results are invaildated

### LINKED ISSUE #22185: Sorting rides by intensity or nausea is incorrect when value "not yet known" but had a previous rating
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.11 (71a8eee on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

If you have a ride that received ratings, but then you go and edit the ride so that the stats are not calculated again, the ride does not sort correctly in the Ride/Attractions list. When sorting by excitement the ride drops to the bottom of the list with a value "Not Yet Known". But for intensity and nausea sorting, the ride maintains its original place from the previous calculated stats but displays "not yet known". The ride should drop to the bottom of the list but this does not happen for intensity and nausea.

### Steps to reproduce

Change lift speed for existing coaster
Sort by intensity or nausea in the ride list
Ride fails to drop to the bottom of the list

### Attachments

rides

### PR DESCRIPTION
**Pull request by lewyche**
Fix #22185

### CODE REVIEW

**Review by mrmagic2020 — CHANGES_REQUESTED** [review]
LGTM! Tested and the fix worked as expected 👍
Please add a changelog entry. Also, you might want to amend your first commit message to pass the CI workflow.

**Comment by lewyche** [comment]
I've updated the changelog and amended my commit message.

**Review by mrmagic2020 — APPROVED** [review]

File: src/openrct2/ride/RideRatings.cpp [hunk 1]
```diff
@@ -2262,10 +2262,12 @@ static void RideRatingsApplyPenaltyLateralGs(RatingTuple& ratings, const Ride& r
 
 bool RatingTuple::isNull() const
 {
-    return excitement == kRideRatingUndefined;
+    return excitement == kRideRatingUndefined && intensity == kRideRatingUndefined && nausea == kRideRatingUndefined;
```
Comment (Gymnasiast) [inline src/openrct2/ride/RideRatings.cpp:2265]: No need for this, and it will break existing parks. Please revert.

File: distribution/changelog.txt [hunk 2]
```diff
@@ -49,7 +49,11 @@
 - Fix: [#22152] [Plugin] Negative signed integers are truncated.
 - Fix: [#22161] Using arrow keys in textboxes crashes the game.
 - Fix: [#22174] Cheats are reset when starting a server.
+<<<<<<< HEAD
```
Comment (Gymnasiast) [inline distribution/changelog.txt]: Please fix this.

File: src/openrct2/ride/RideRatings.cpp (hunk 1 above)
Comment (lewyche) [reply src/openrct2/ride/RideRatings.cpp:2265]: Ok, reverted.

File: distribution/changelog.txt [hunk 3]
```diff
@@ -49,6 +49,7 @@
 - Fix: [#22152] [Plugin] Negative signed integers are truncated.
 - Fix: [#22161] Using arrow keys in textboxes crashes the game.
 - Fix: [#22174] Cheats are reset when starting a server.
+- Fix: [#22185] Set nausea and intensity after test results are invaildated.
```
Comment (Gymnasiast) [inline distribution/changelog.txt]: _How_ a bug has been fixed is irrelevant to the user. The changelog should list the problem that has been fixed:

```suggestion
- Fix: [#22185] Intensity and nausea are incorrectly sorted in the rides list after ratings invalidation.
```

File: src/openrct2/ride/RideRatings.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/ride/RideRatings.cpp:2265]:
```suggestion
    return excitement == kRideRatingUndefined;
```

File: distribution/changelog.txt [hunk 4]
```diff
@@ -49,6 +49,7 @@
 - Fix: [#22152] [Plugin] Negative signed integers are truncated.
 - Fix: [#22161] Using arrow keys in textboxes crashes the game.
 - Fix: [#22174] Cheats are reset when starting a server.
+- Fix: [#22185] Set nausea and intensity after test results are invalidated.
```
Comment (Gymnasiast) [inline distribution/changelog.txt:52]: _How_ a bug has been fixed is irrelevant to the user. The changelog should list the problem that has been fixed:

```suggestion
- Fix: [#22185] Intensity and nausea are incorrectly sorted in the rides list after ratings invalidation.
```

File: src/openrct2/ride/RideRatings.cpp [hunk 5]
```diff
@@ -2268,4 +2268,6 @@ bool RatingTuple::isNull() const
 void RatingTuple::setNull()
 {
     excitement = kRideRatingUndefined;
+    intensity = kRideRatingUndefined;
+    nausea = kRideRatingUndefined;
```
Comment (ZehMatt) [inline src/openrct2/ride/RideRatings.cpp:2272]: This does not make any sense and also breaks the game a bit, kRideRatingUndefined is not meant to be used for anything other than excitement as it acts as a value for marking it as invalid/null, null is perhaps not the best choice here. As for the sort problem, perhaps the best choice is to fix the sort order and not modify random variables.

Comment (beesman93) [reply src/openrct2/ride/RideRatings.cpp:2272]: Fixed the sort order - checking for ratings.isNull() on both sides before comparing between them.
Checking for == NULL for nausea and intensity directly wouldn't work, since if you are retesting a ride, it retains those ratings (hence the rides staying in same place on the sorted list before the fix) and excitement is set to the kRideRatingUndefined.
So all gameplay should now be as intended, only difference is untested rides appearing at the tail of the sorted rating lists always.

Comment (lewyche) [reply src/openrct2/ride/RideRatings.cpp:2272]: Just seeing this now, will be more careful with future commits.

Comment (beesman93) [reply src/openrct2/ride/RideRatings.cpp:2272]: > Just seeing this now, will be more careful with future commits.

Don't worry I think it was easy mistake to make, since 1/3 ratings worked the way you wanted the other 2 to work.
If the kRideRatingUndefined was named kRideRatingExcitementUndefined it would be clearer it's intended use is for excitement only I think - this way it was an easy assumption to make it can be used for the other two ratings when setNulling them all.
