### PR TITLE
Fix #16308: Crash when trying to place down a ride on Android

### LINKED ISSUE #16308: Crash when trying to place down any ride
### Operating System

Android 11

### OpenRCT2 build

OpenRCT2, v0.3.5.1

### Describe the issue

The OpenRCT2 app crashed when trying to place down a ride or stand. When placing down a path no crash occurs.

The following log is the log after I touch the screen and the game crashes:
```
12-24 22:11:21.966 29191 29228 V OpenRCT2: [sp] Tick: 1587, GA: RideCreateAction (00000006) (_networkId = 00000000; _flags = 00000000; _playerId = 4294967295; _rideType = 001c; _subType = 0001; _colour1 = 00; _colour2 = 00; ) OK
12-24 22:11:21.966 29191 29228 V OpenRCT2: [sp] Tick: 1587, GA: RideCreateAction (00000006) (_networkId = 00000000; _flags = 00000000; _playerId = 4294967295; _rideType = 001c; _subType = 0001; _colour1 = 00; _colour2 = 00; ) OK
12-24 22:11:31.116 29191 29228 V OpenRCT2: show error, BLACK}CanÔÇÖt construct this hereÔÇª
12-24 22:11:31.116 29191 29228 V OpenRCT2: Raise or lower land first
12-24 22:11:31.116 29191 29228 V OpenRCT2: show error, BLACK}CanÔÇÖt construct this hereÔÇª
12-24 22:11:31.116 29191 29228 V OpenRCT2: (undefined string)
12-24 22:11:31.116 29191 29228 V OpenRCT2: [sp] Tick: 1953, GA: TrackPlaceAction (00000003) (_networkId = 00000000; _flags = 00000000; _playerId = 4294967295; _rideIndex = 0002; _trackType = 00000106; _origin = CoordsXYZD(x = 928, y = 1952, z = 112, direction = 0); _brakeSpeed = 00000000; _colour = 00000000; _seatRotation = 00000004; _trackPlaceFlags = 00000000; ) OK
12-24 22:11:31.116 29191 29228 V OpenRCT2: Invalidating previous region, Min: 0 0, Max: 0 0
12-24 22:11:31.118 29191 29228 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 29228 (SDLThread), pid 29191 (.openrct2.debug)
12-24 22:11:31.177 29285 29285 F DEBUG   : pid: 29191, tid: 29228, name: SDLThread  >>> io.openrct2.debug <<<
12-24 22:11:31.191 29285 29285 F DEBUG   :       #01 pc 00000000000a5ce0  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libc++_shared.so (BuildId: 95dcb5c40abfafc54f706cd95020263dbeb522af)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #02 pc 00000000000a5edc  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libc++_shared.so (BuildId: 95dcb5c40abfafc54f706cd95020263dbeb522af)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #03 pc 00000000000baa68  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libc++_shared.so (BuildId: 95dcb5c40abfafc54f706cd95020263dbeb522af)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #04 pc 00000000000ba170  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libc++_shared.so (BuildId: 95dcb5c40abfafc54f706cd95020263dbeb522af)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #05 pc 00000000000ba0f0  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libc++_shared.so (__cxa_throw+120) (BuildId: 95dcb5c40abfafc54f706cd95020263dbeb522af)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #06 pc 000000000010c618  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2-ui.so (BuildId: 2aef425177aba5c94685202cb08043e70d85a6c8)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #07 pc 000000000010ad64  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2-ui.so (ride_construction_tooldown_construct(ScreenCoordsXY const&)+964) (BuildId: 2aef425177aba5c94685202cb08043e70d85a6c8)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #08 pc 000000000010dfcc  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2-ui.so (BuildId: 2aef425177aba5c94685202cb08043e70d85a6c8)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #09 pc 0000000000088450  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2-ui.so (BuildId: 2aef425177aba5c94685202cb08043e70d85a6c8)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #10 pc 0000000000087520  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2-ui.so (GameHandleInput()+192) (BuildId: 2aef425177aba5c94685202cb08043e70d85a6c8)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #11 pc 0000000000194130  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2.so (context_handle_input()+148) (BuildId: 528d687aed0edc2f9b5dc95c975c420a8f23bc05)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #12 pc 00000000001a14cc  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2.so (OpenRCT2::GameState::Update()+748) (BuildId: 528d687aed0edc2f9b5dc95c975c420a8f23bc05)
12-24 22:11:31.191 29285 29285 F DEBUG   :       #13 pc 0000000000198598  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2.so (OpenRCT2::Context::Update()+164) (BuildId: 528d687aed0edc2f9b5dc95c975c420a8f23bc05)
12-24 22:11:31.192 29285 29285 F DEBUG   :       #14 pc 0000000000198470  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2.so (OpenRCT2::Context::RunFixedFrame()+192) (BuildId: 528d687aed0edc2f9b5dc95c975c420a8f23bc05)
12-24 22:11:31.192 29285 29285 F DEBUG   :       #15 pc 00000000001979c4  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2.so (OpenRCT2::Context::Launch()+580) (BuildId: 528d687aed0edc2f9b5dc95c975c420a8f23bc05)
12-24 22:11:31.192 29285 29285 F DEBUG   :       #16 pc 0000000000195a68  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2.so (OpenRCT2::Context::RunOpenRCT2(int, char const**)+28) (BuildId: 528d687aed0edc2f9b5dc95c975c420a8f23bc05)
12-24 22:11:31.192 29285 29285 F DEBUG   :       #17 pc 000000000007bf4c  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2-ui.so (main+136) (BuildId: 2aef425177aba5c94685202cb08043e70d85a6c8)
12-24 22:11:31.192 29285 29285 F DEBUG   :       #18 pc 000000000013cbd4  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/lib/arm64/libopenrct2-ui.so (Java_org_libsdl_app_SDLActivity_nativeInit+320) (BuildId: 2aef425177aba5c94685202cb08043e70d85a6c8)
12-24 22:11:31.192 29285 29285 F DEBUG   :       #19 pc 000000000002146c  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/oat/arm64/base.odex (art_jni_trampoline+172)
12-24 22:11:31.192 29285 29285 F DEBUG   :       #20 pc 00000000000448b4  /data/app/~~KsG9ggtL-fClj-gMI1iNvg==/io.openrct2.debug-DAYvWgYp0uGEgIbTzYieJA==/oat/arm64/base.odex (org.libsdl.app.SDLMain.run+116)
12-24 22:11:31.474  1119 29289 W ActivityManager: crash : io.openrct2.debug,10304
12-24 22:11:31.479  1119 29289 W ActivityTaskManager:   Force finishing activity io.openrct2.debug/io.openrct2.GameActivity
```

### Steps to reproduce

On a Samsung Galaxy Tab S7+ (Android 11)

1. Followed the Android setup:
- copied game files to rct2 folder
- copied OpenRCT2 files to openrct2 folder
- pointed game_path in config.ini to correct folder
- installed .apk
2. Start game and any scenario
3. Open ride menu and select any ride (or stand)
4. Any touch of the screen now crashes the game

### PR DESCRIPTION
**Pull request by lawrencedemol**
This pull request solves the crashes on Android when placing down any ride, adding staff, adding scenery,... See https://github.com/OpenRCT2/OpenRCT2/issues/16308 for a detailed description.

On Android the any_cast throws a bad_any_cast exception eventhough the data stored is of the same type as the target type.
I solved this by changing the any type to a shared void*. This should not change any functionality but now the Android version works as expected. By using a shared_ptr, the memory should be released once there are no more references to this object.

In the screenshots you can see the stacktrace of the crash when placing a ride and the content of the ResultData object when debugging from my phone.

afbeelding
afbeelding

### CODE REVIEW

File: src/openrct2/actions/GameActionResult.h [hunk 1]
```diff
@@ -82,13 +82,13 @@ namespace GameActions
...
         {
-            ResultData = std::forward<const T&&>(data);
+            ResultData = std::make_shared<T>(data);
         }
 
-        // This function will throw std::bad_any_cast if the type mismatches.
         template<typename T> T GetData() const
         {
-            return std::any_cast<T>(ResultData);
+            T* res = (T*)ResultData.get();
```
Comment (Gymnasiast) [inline src/openrct2/actions/GameActionResult.h:90]: This uses a C-style cast, which are disallowed in our code.

**Comment by Gymnasiast** [comment]
Hi @lawrencedemol , thanks for creating this PR. Very happy to see someone picked this up, it has been puzzling me for a while.

Could you address a few things?

- The commit message should read `Fix #16308: Crash when trying to place down a ride on Android`.
- There should be a changelog entry (the changelog is sorted by type first, number second).
- The code uses a C-style cast, but these are not allowed in our code (because C++-style cast are more explicit).

Addressing these issues should also make the CI happy.

**Comment by janisozaur** [comment]
@lawrencedemol thanks. I'm interested to know what did that throw in the first place?

**Comment by Broxzier** [comment]
Thanks for looking into this and providing a solution. Feel free to add yourself to [contributors.md](https://github.com/OpenRCT2/OpenRCT2/blob/develop/contributors.md) with this PR.

**Comment by lawrencedemol** [comment]
> @lawrencedemol thanks. I'm interested to know what did that throw in the first place?

@janisozaur When the game executes actions, e.g. TrackPlaceAction, it sends the results in a generic GameActions::Result object. This object contains an std::Any variable resultData where specific data of this actiontype is stored. In this case TrackPlaceActionResult. When reading this data, it was casted back to the TrackPlaceActionResult from the any object using any_cast. When debugging on my phone this crashes on multiple different action types with a bad_any_cast exception (see screenshots with stacktrace). This exception is normally thrown when the data in the any object does not match the type it is casted to. This is weird as the types should match. I see that the any implementation comes from the android ndk so this could be a bug in this android specific any implementation. To avoid this I converted the generic any object to a shared void*. This should give the same result as using any in this case and when I test it now the casts succeed.

**Comment by lawrencedemol** [comment]
> Thanks for looking into this and providing a solution. Feel free to add yourself to [contributors.md](https://github.com/OpenRCT2/OpenRCT2/blob/develop/contributors.md) with this PR.

Thanks, I added my name there then. I encounter some other issues in the Android version so I might take a look at those too.

File: src/openrct2/actions/GameActionResult.h [hunk 2]
```diff
@@ -82,13 +82,13 @@ namespace GameActions
...
-            ResultData = std::forward<const T&&>(data);
+            ResultData = std::make_shared<T>(data);
         }
 
-        // This function will throw std::bad_any_cast if the type mismatches.
         template<typename T> T GetData() const
         {
-            return std::any_cast<T>(ResultData);
+            T* res = static_cast<T*>(ResultData.get());
+            return *res;
```
Comment (Gymnasiast) [inline src/openrct2/actions/GameActionResult.h:91]: We discussed this solution in the team chat. A problem with this is that it essentially throws out all type checks.

This solution is fine for Android as a stop-gap measure, but we would like it if the other platforms didn’t have to suffer from this. As such, can you put your changes behind an \#ifdef?

File: src/openrct2/actions/GameActionResult.h [hunk 3]
```diff
@@ -82,13 +87,21 @@ namespace GameActions
...
         }
 
         template<typename T> T GetData() const
         {
-            T* res = static_cast<T*>(ResultData.get());
-            return *res;
+#ifdef __ANDROID__
+            return *static_cast<T*>(ResultDataPtr.get());;
+#else
+            // This function will throw std::bad_any_cast if the type mismatches.
```
Comment (tupaschoal) [inline src/openrct2/actions/GameActionResult.h:102]: I think this is alright to remove. It's on the `any_cast` documentation and you already explain above.
```suggestion
```

File: src/openrct2/actions/GameActionResult.h [hunk 4]
```diff
@@ -70,7 +70,12 @@ namespace GameActions
         CoordsXYZ Position = { LOCATION_NULL, LOCATION_NULL, LOCATION_NULL };
         money32 Cost = 0;
         ExpenditureType Expenditure = ExpenditureType::Count;
-        std::shared_ptr<void> ResultData;
+
+        // Any_cast throws a bad_any_cast exception on Android
+        // To avoid this in the Android release, a shared void pointer is used to store the result data.
+        // Other platforms still use Any as this provides type checks
+        std::shared_ptr<void> ResultDataPtr;
+        std::any ResultData;
```
Comment (tupaschoal) [inline src/openrct2/actions/GameActionResult.h:78]:
```suggestion
#ifdef __ANDROID__
        // Any_cast throws a bad_any_cast exception on Android
        // To avoid this in the Android release, a shared void pointer is used to store the result data.
        std::shared_ptr<void> ResultData;
#else
        // Other platforms still use Any as this provides type checks
        std::any ResultData;
#endif
```

I think we should also branch here and keep just one member variable.

File: src/openrct2/actions/GameActionResult.h [hunk 5]
```diff
@@ -82,13 +87,21 @@ namespace GameActions
         // is still just uint32_t, this guarantees the data is associated with the correct type.
         template<typename T> void SetData(const T&& data)
         {
-            ResultData = std::make_shared<T>(data);
+#ifdef __ANDROID__
+            ResultDataPtr = std::make_shared<T>(data);
```
Comment (tupaschoal) [inline src/openrct2/actions/GameActionResult.h:91]:
```suggestion
            ResultData = std::make_shared<T>(data);
```
To comply with suggestion above.

File: src/openrct2/actions/GameActionResult.h [hunk 6]
```diff
@@ -82,13 +87,21 @@ namespace GameActions
...
+            ResultData = std::forward<const T&&>(data);
+#endif
         }
 
         template<typename T> T GetData() const
         {
-            T* res = static_cast<T*>(ResultData.get());
-            return *res;
+#ifdef __ANDROID__
+            return *static_cast<T*>(ResultDataPtr.get());;
```
Comment (tupaschoal) [inline src/openrct2/actions/GameActionResult.h:100]: To comply with suggestion above.
```suggestion
            return *static_cast<T*>(ResultData.get());;
```

File: src/openrct2/actions/GameActionResult.h (hunk 3 above)
Comment (Gymnasiast) [reply src/openrct2/actions/GameActionResult.h:102]: I’d like to keep it anyway.

File: src/openrct2/actions/GameActionResult.h [hunk 7]
```diff
@@ -70,6 +70,11 @@ namespace GameActions
         CoordsXYZ Position = { LOCATION_NULL, LOCATION_NULL, LOCATION_NULL };
         money32 Cost = 0;
         ExpenditureType Expenditure = ExpenditureType::Count;
+
+        // Any_cast throws a bad_any_cast exception on Android
+        // To avoid this in the Android release, a shared void pointer is used to store the result data.
+        // Other platforms still use Any as this provides type checks
+        std::shared_ptr<void> ResultDataPtr;
```
Comment (Gymnasiast) [inline src/openrct2/actions/GameActionResult.h:77]: Shouldn’t this be ifdef’ed too?

**Review by Gymnasiast — COMMENTED** [review]
Code looks good. Will wait for CI to become all green, and will test the resulting build too for good measure.

**Comment by janisozaur** [comment]
@Gymnasiast can you create a follow up issue to figure out the root cause of this?

**Comment by Gymnasiast** [comment]
@janisozaur Yeah, I created https://github.com/OpenRCT2/OpenRCT2/issues/17016 . Feel free to append/modify it as you see fit.
