### PR TITLE
Fix #18309: Flying and Multi Dim trains glitch when moving between inverted and uninverted track when uncap fps is on

### LINKED ISSUE #18309: Flying RC glitching through track when switching from invert and regular and vice versa
image

### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.2-65-g406b73d (406b73d on develop) provided by GitHub

### Describe the issue

https://i.gyazo.com/e13787097d5862b9b35bd969be07c724.gif

This seems to only be occuring when uncapped FPS is on. It might be a desync in the paint code when swapping between invert and upright and vice versa, but I do not know this for certain.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Turn on uncap fps in settings
2. Build a flying RC with a station, go into an inline twist immediately after and then straight pieces.
3. See the magic happen

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mixiate**
Fixes #18309 Flying and Multi Dim trains glitching when moving between inverted and uninverted track when uncap fps is on.

This happens because the underlying position of the vehicle changes even though visually it looks the same. It now stops the vehicle from being tweened when it changes from invert to uninverted.

https://github.com/user-attachments/assets/ec49ea5f-212c-4d05-a623-145dcc8cf48f

https://github.com/user-attachments/assets/cfa8a58a-4339-4fe7-bf76-7d101f34fa9f

Thanks ZehMatt for pointing out my stupid mistake 😆.

### CODE REVIEW

File: src/openrct2/entity/EntityTweener.cpp [hunk 1]
```diff
@@ -69,6 +69,16 @@ static bool CanTweenEntity(EntityBase* ent)
     return false;
 }
 
+void EntityTweener::SkipEntity(EntityBase* entity)
```
Comment (ZehMatt) [inline src/openrct2/entity/EntityTweener.cpp:72]: Is this really necessary? It should come down to the same result by just RemoveEntity

Comment (mixiate) [reply src/openrct2/entity/EntityTweener.cpp:72]: Oh yeah 🤦... Haha. I was reading RemovEntity completely wrong.

**Review by ZehMatt — APPROVED** [review]

**Review by ZeeMaji — APPROVED** [review]
Capped FPS remains the same as expected and the issue is fixed when using uncapped FPS.

**Comment by ZehMatt** [comment]
I think a changelog entry is in order.

**Comment by mixiate** [comment]
It has one?

**Comment by ZehMatt** [comment]
> It has one?

My bad, I was looking for that commit but you had it all in one, all good.
