### PR TITLE
Fix #20948: Incorrect diagonal brakes supports

### LINKED ISSUE #20948: Diagonal Breaks block supports
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.6-124-ge24b59e (e24b59e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The supports get blocked by the block breaks, if they are in the same height, they must be build in a backwards way to execute the bug, as the breaks/block breaks will be the first object on the list, it will block any metal supports "above it"

### Steps to reproduce

1. Open any parks
2. Get a ride whit diagonal breaks
3. Now it depends of the way it's done
- 1. You must build them backwards on the track (commencing whit the last break if building normally)
- 2. Build them
- 3. Realises that the next supports aren't showing up

+ 1. Build track above (Preferably stations pieces)
+ 2. Realises than no supports (Where the diagonal brakes/block brakes are having sprites on a tile), appears under the track that is above the diagonal.

### Attachments

What we see (Both stations and normal track)

image
image

How it should be done (Station only)

image

### PR DESCRIPTION
**Pull request by Gymnasiast**
Thanks to @mixiate for pointing out the cause.

@TheClaudeQC could you test if this addresses all the incorrect supports?

@ZeeMaji Could you give it a test as well?

### CODE REVIEW

**Comment by ZeeMaji** [comment]
Steel supports of the affected diagonal brakes get blocked by nothing and redirected when built backwards and viewing from this angle.
The wooden supports aren't affected by this from what i can tell.
Screenshot at 2025-02-21 08-10-56

File: src/openrct2/paint/track/coaster/LatticeTriangleTrack.cpp [hunk 1]
```diff
@@ -18417,7 +18417,7 @@ static void LatticeTriangleTrackDiagBrakes(
             session, supportType.metal, kDiagSupportPlacement[direction], 0, height, session.SupportColours);
     }
 
-    PaintUtilSetSegmentSupportHeight(session, kSegmentsAll, 0xFFFF, 0);
+    PaintUtilSetSegmentSupportHeight(session, BlockedSegments::kDiagStraightFlat[trackSequence], 0xFFFF, 0);
```
Comment (mixiate) [inline src/openrct2/paint/track/coaster/LatticeTriangleTrack.cpp:18420]:
```suggestion
    PaintUtilSetSegmentSupportHeight(session, PaintUtilRotateSegments(BlockedSegments::kDiagStraightFlat[trackSequence], direction), 0xFFFF, 0);
```

I think these should be rotated.

**Comment by Gymnasiast** [comment]
Thanks @mixiate , that seems to have done the trick.

**Review by ZeeMaji — APPROVED** [review]
Building diagonal brakes backwards properly displays supports, they still display properly when built forwards, and all of the parks i looked at with them still render as i'd expect.
