### PR TITLE
Fix clear scenery window closing (again)

### LINKED ISSUE #22439: Clear Scenery window closes when you open it
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.12-140-g30e890c (30e890c on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The Clear Scenery window closes itself after opening

### Steps to reproduce

Just open the Clear Scenery window, and it should close immediately.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
This fixes the clear scenery closing immediately after opening, and adds a function to actually apply/paint map selection for the tool.

Will fix #22439, a regression from #22411. (Unlike #22442, which missed a bit.)

### CODE REVIEW

File: src/openrct2-ui/windows/ClearScenery.cpp [hunk 1]
```diff
@@ -224,12 +224,80 @@ namespace OpenRCT2::Ui::Windows
             return ClearAction(range, itemsToClear);
         }
 
+        int8_t ToolUpdateClearLandPaint(const ScreenCoordsXY& screenPos)
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/ClearScenery.cpp:227]: This function was previously shared with the land tool, which is how it was missed.

File: src/openrct2-ui/windows/LandRights.cpp [hunk 2]
```diff
@@ -250,7 +250,7 @@ static Widget window_land_rights_widgets[] = {
                 if (_landRightsCost != kMoney64Undefined)
                 {
                     _landRightsCost = kMoney64Undefined;
-                    WindowInvalidateByClass(WindowClass::ClearScenery);
+                    WindowInvalidateByClass(WindowClass::LandRights);
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/LandRights.cpp:253]: Unrelated fix.

**Review by mrmbernardi — APPROVED** [review]
