### PR TITLE
Fix #17297: Crash when switching language

### LINKED ISSUE #17297: Crash when switching language
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.0-169-gd56a6a9 (d56a6a9 on develop) provided by GitHub

### Describe the issue

When switching language (doesn't seem to do it for every language, some just turn off the music of the title screen until you refresh the menu) the game closes itself. The language does change afterwards, so that's a good thing atleast. But this is not something you would want happening while working on a park.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Go to options (either on the title screen or in game)
2. Switch Language from English (UK) to Nederlands
3. Your game will crash or your title screen's music will turn off (or a combination of both)

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by IntelOrca**
Very large change because it cleans up a lot of old C style code and move towards a typed `shared_ptr` instead for `IAudioChannel`. This should hopefully mean we don't crash accessing channels that have been deleted either because the audio source got disposed or it finished playing.

* Refactor all uses of IAudioChannel and the audio mixer.
* Use shared_ptr to avoid dead pointers hanging about.
* Reload particular audio channels where necessary after object reload.

### CODE REVIEW

File: src/openrct2-ui/audio/AudioMixer.cpp [hunk 1]
```diff
@@ -79,10 +75,10 @@ void AudioMixer::Unlock()
     SDL_UnlockAudioDevice(_deviceId);
 }
 
-IAudioChannel* AudioMixer::Play(IAudioSource* source, int32_t loop, bool deleteondone)
+std::shared_ptr<IAudioChannel> AudioMixer::Play(IAudioSource* source, int32_t loop, bool deleteondone)
 {
     Lock();
-    auto* channel = AudioChannel::Create();
+    auto channel = std::shared_ptr<ISDLAudioChannel>(AudioChannel::Create());
```
Comment (CookiePLMonster) [inline src/openrct2-ui/audio/AudioMixer.cpp:81]: `AudioChannel::Create` could just return a shared pointer I reckon?

**Review by duncanspumpkin — APPROVED** [review]

**Comment by IntelOrca** [comment]
@Broxzier sorry, I clicked merge before I saw you had requested a review. I can make follow up changes for anything you find.

**Comment by Broxzier** [comment]
@IntelOrca No worries, I mainly assigned myself to test this tonight and get this merged asap.
