### PR TITLE
Position land rights tool size widget relative to title bar

### LINKED ISSUE #24285: land rights window's preview widget is not correct position with Enlarged UI.
### Operating System

Debian Bookworm

### OpenRCT2 build

OpenRCT2-v0.4.21-121-g317d8c4970

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

park entrance's land rights button clicked,
Window is alike this screenshot.

Image

I found at "src/openrct2-ui/windows/LandRights.cpp"

I think that 310~316 line seems to be the cause.

> // Position land size tool
            widgets[WIDX_PREVIEW].top = 17;
            widgets[WIDX_PREVIEW].bottom = widgets[WIDX_PREVIEW].top + 32;
            widgets[WIDX_DECREMENT].top = 18;
            widgets[WIDX_DECREMENT].bottom = widgets[WIDX_DECREMENT].top + 16;
            widgets[WIDX_INCREMENT].top = 32;
            widgets[WIDX_INCREMENT].bottom = widgets[WIDX_INCREMENT].top + 16;

### Steps to reproduce

1. Click Enatrace
2. Click Land Rights button.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Fixes #24285

### CODE REVIEW

File: src/openrct2-ui/windows/LandRights.cpp [hunk 1]
```diff
@@ -308,11 +308,11 @@ namespace OpenRCT2::Ui::Windows
             }
 
             // Position land size tool
-            widgets[WIDX_PREVIEW].top = 17;
+            widgets[WIDX_PREVIEW].top = 17 + getTitleBarDiffNormal();
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/LandRights.cpp:311]: Why not make this relative to the page widget, like I did for all other cases I encountered?

Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/LandRights.cpp:311]: Yeah, that might be nicer. Let me change it to that then.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
The `+` button is misaligned:

afbeelding

**Comment by AaronVanGeffen** [comment]
> The `+` button is misaligned:

The maths was off by two pixels. Looks like that was an issue in the last release, too! Nice catch.

**Review by Gymnasiast — APPROVED** [review]
