### PR TITLE
Close #21227: Sort entrance styles in dropdown

### LINKED ISSUE #21227: Entrance style dropdown not sorted in a consistent way
### Operating System

Linux

### OpenRCT2 build

33523c98c24d17d2df0f2e47e8a1db51496271d4

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

(Came across this when investigating #21054 .)

The sorting of entrance styles in the corresponding dropdown in the ride / paint window is not always the same.

In parks originating from old `*.SC6` scenarios, the sorting is as in vanilla RCT2, with the "plain" entrance style on top, then "wooden", "canvas tent", ... and finally "space" on the bottom:  
(And the new "no entrance" style added below that.)

from-sc6-scenario

In parks originating from new, `*.park` scenarios, the sorting is purely alphabetic:  
(No "no entrance" in the example picture as I had not selected that when creating the scenario.)

from-new-scenario

In the track designer, we also get the alphabetic sorting:

from-track-designer

---

I am not a 100% sure what the preferred order would be. Alphabetic sorting makes some sense, but the original ordering from vanilla RCT2 seems deliberate as well, with the "plain" one on top, followed by the ones from RCT1 (iirc), then the newer ones.  
Surely, it should be uniform across all parks, though.

---

From what I can tell so far, this is not a UI issue, but stems from the fact that park objects are loaded in a different order in the old parks compared to new parks or the track designer.

### Steps to reproduce

1. Start any scenario from RCT2 base game that has at least one ride that's not a stall (e. g. Electric Fields).
2. Click on any ride, open paint tab, click on the entrance style dropdown.
3. Repeat steps 1 and 2 this in track designer.
4. Create a new scenario and repeat steps 1 and 2 there.

Observe that the sorting is different in the RCT2 base game scenario.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by zzril**
This PR changes the entrance style dropdown in the "paint" tab of the ride window to sort the available entrance styles according to some comparing function before displaying them.  
This makes the order in which they are displayed independent from the order in which the entrance objects were loaded. (Which varies depending on whether they were loaded from an `*.SC6` or a `*.park`.)  
As a result, the sorting criteria are now the same everywhere (old scenarios, new scenarios, track designer).

For the actual sorting, the enum values returned by `GetStationStyleFromIdentifier` from `src/openrct2/rct12/RCT12.cpp` are used. This leads to the same sorting as in RCT2 ("plain", "wooden" and "canvas tent" on top), with newly added styles at the bottom.

Closes #21227

### CODE REVIEW

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -4271,28 +4302,19 @@ class RideWindow final : public Window
             break;
             case WIDX_ENTRANCE_STYLE_DROPDOWN:
             {
-                auto ddIndex = 0;
-                auto& objManager = GetContext()->GetObjectManager();
-                for (auto i = 0; i < MAX_STATION_OBJECTS; i++)
+                if (static_cast<std::vector<EntranceTypeLabel>::size_type>(dropdownIndex) >= _entranceStyleDropdownData.size())
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/Ride.cpp:4305]: That is quite the line, just use size_t which all STL containers use

Comment (zzril) [reply src/openrct2-ui/windows/Ride.cpp]: Changed it.

File: src/openrct2-ui/windows/Ride.cpp [hunk 2]
```diff
@@ -49,6 +49,7 @@
 #include <openrct2/object/ObjectRepository.h>
 #include <openrct2/object/StationObject.h>
 #include <openrct2/rct1/RCT1.h>
+#include <openrct2/rct12/RCT12.h>
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/Ride.cpp:52]: Is this header really required? After the import we should use the internal structures.

Comment (ZehMatt) [reply src/openrct2-ui/windows/Ride.cpp:52]: I see, not ideal but will do for now.

**Review by ZehMatt — APPROVED** [review]

File: src/openrct2-ui/windows/Ride.cpp (hunk 2 above)
Comment (Gymnasiast) [reply src/openrct2-ui/windows/Ride.cpp:52]: There is a good reason this function resides in `GetStationStyleFromIdentifier()` - it should **only** be used for export. It only supports entrances present in vanilla.

Comment (zzril) [reply src/openrct2-ui/windows/Ride.cpp]: Changed to alphabetic sorting, analogous to the ride type and vehicle type dropdown.

File: src/openrct2-ui/windows/Ride.cpp [hunk 3]
```diff
@@ -619,17 +619,27 @@ struct VehicleTypeLabel
     const char* label_string;
 };
 
+// Used for sorting the entrance type dropdown.
+struct EntranceTypeLabel
+{
+    ObjectEntryIndex EntranceTypeId;
+    StringId LabelId;
+    const char* label_string;
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Ride.cpp:627]: Could you rename this to `LabelString`? We use TitleCase for struct members.

Comment (zzril) [reply src/openrct2-ui/windows/Ride.cpp:627]: That's the name and data type used in the other sorting-related structs, `RideTypeLabel` and `VehicleTypeLabel`.  
Shall I update them as well then?

Comment (zzril) [reply src/openrct2-ui/windows/Ride.cpp]: Renamed to TitleCase; also did that for the other 2 structs.  
Also wrapped it in `u8string_view`. Again, same for the other structs.

Comment (Gymnasiast) [reply src/openrct2-ui/windows/Ride.cpp]: Thank you, that is a nice cleanup.

**Review by Gymnasiast — APPROVED** [review]
Tested, and appears to work correctly.
