### PR TITLE
Fix #8333: Replace assert with in-game error.

### LINKED ISSUE #8333: BACKTRACE d28834
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/d288346d8edd7717723581338ed4e93c9e434f63015b31ebc8ddcff802c7e6e3?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Dec 01 2018 00:21:09)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\User\\Documents\\OpenRCT2\\a8da9a37-f43c-4800-85b9-0b01c4fae85a.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\User\\Documents\\OpenRCT2\\a8da9a37-f43c-4800-85b9-0b01c4fae85a.sv6.gz: <em>1</em><br><strong>commit:</strong> ebd4e8f: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> openrct2_assert_fwd -> rct_peep::UpdateRideAdvanceThroughEntrance -> rct_peep::UpdateRide -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by ZehMatt**
I feel like this makes more sense than a crash as long we offer the option to change the ride to any arbitrary type.

Affected Park: 
[park (4).sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2700736/park.4.sv6.gz)

### CODE REVIEW

File: src/openrct2/localisation/StringIds.h [hunk 1]
```diff
@@ -3899,8 +3899,10 @@ enum
 
     STR_INVALID_CLIMATE_ID = 6269,
 
+    STR_GUESTS_GETTING_STUCK_ON_RIDE = 6270,
+
     // Have to include resource strings (from scenarios and objects) for the time being now that language is partially working
-    STR_COUNT = 32768
+    STR_COUNT = 32769
```
Comment (janisozaur) [inline src/openrct2/localisation/StringIds.h]: I don't think you're supposed to change this.

**Comment by janisozaur** [comment]
Other than the string thing, it looks good.

File: src/openrct2/localisation/StringIds.h (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/localisation/StringIds.h]: Who would change it? Or is that the maximum amount of possible strings?

**Comment by janisozaur** [comment]
LGTM, but I'd like someone who knows the gameplay more to take a look as well. @Broxzier @Gymnasiast @IntelOrca ?

File: src/openrct2/peep/Guest.cpp [hunk 2]
```diff
@@ -3596,10 +3596,20 @@ void rct_peep::UpdateRideAdvanceThroughEntrance()
...
+        else
+        {
+            // If the ride type was changed guests will become stuck.
+            auto intent = Intent(WC_RIDE);
+            intent.putExtra(INTENT_EXTRA_RIDE_ID, current_ride);
+            context_open_intent(&intent);
 
-        peep_update_ride_leave_entrance_spiral_slide(this, ride, entranceLocation);
-        return;
+            context_show_error(STR_WARNING, STR_GUESTS_GETTING_STUCK_ON_RIDE);
```
Comment (duncanspumpkin) [inline src/openrct2/peep/Guest.cpp]: The previous code returned at this point we now fall through into the code that assumes we have vehicles on the ride. If we don't have vehicles on the ride then this will cause a nullptr deref. Is this what we want. I can't remember off the top of my head if rides always have at least one vehicle.

Comment (ZehMatt) [reply src/openrct2/peep/Guest.cpp]: You are right, its an out of bound but I was not able to actually trigger it. I'll add the return statement back. As for the spam, perhaps its better to do this on the host/local game only?

**Comment by ZehMatt** [comment]
I've just pushed a new commit. I've added two new fields to the Ride struct, one that contains current issues and the other field about the last time the player was informed. If the ride for example has guests stuck due to the invalid ride type it will now add it to the news queue like how the player would be informed about broken rides. In case there are more issues with hacked rides we can easily expand the flags and this allows the user to act with more information instead of crashing him or leaving him puzzled about why the ride behaves like that.

File: src/openrct2/ride/Ride.h [hunk 3]
```diff
@@ -899,6 +904,12 @@ enum
     RIDE_MODIFY_RENEW
 };
 
+enum
+{
+    RIDE_ISSUE_NONE = 0,
+    RIDE_ISSUE_GUSESTS_STUCK = (1 << 0),
```
Comment (pizza2004) [inline src/openrct2/ride/Ride.h]: GUESTS is misspelled in this.

File: src/openrct2/peep/Guest.cpp [hunk 4]
```diff
@@ -3596,10 +3596,30 @@ void rct_peep::UpdateRideAdvanceThroughEntrance()
             peep_update_ride_leave_entrance_maze(this, ride, entranceLocation);
             return;
         }
-        Guard::Assert(ride->type == RIDE_TYPE_SPIRAL_SLIDE);
```
Comment (Gymnasiast) [inline src/openrct2/peep/Guest.cpp]: Do you have a save this hits this assert in develop and is fixed by this PR?

Comment (ZehMatt) [reply src/openrct2/peep/Guest.cpp]: I've attached the park to the first post.
