### PR TITLE
 Fix #17009: “No money” flag in SV6 saves not imported correctly 

### LINKED ISSUE #17009: Loading SV6 saves with money disabled starts with it enabled
### Operating System

Linux, Manjaro

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (2653aOc97 on develop, DEBUG)

### Describe the issue

Loading a SV6 save that has money disabled will re-enable money. I haven't tested with the new .park format.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. `openrct2 https://gitlab.com/sanin.dev/ffa-tycoon/-/raw/master/parks/Arid%20Heights_free_old.sv6`
2. Notice money is enabled.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/rct2/S6Importer.cpp [hunk 1]
```diff
@@ -256,10 +256,13 @@ namespace RCT2
...
-                gParkFlags |= PARK_FLAGS_NO_MONEY;
-            else
-                gParkFlags &= ~PARK_FLAGS_NO_MONEY;
+            if (_s6.header.type == S6_TYPE_SCENARIO)
+            {
+                if (_s6.park_flags & PARK_FLAGS_NO_MONEY_SCENARIO)
+                    gParkFlags |= PARK_FLAGS_NO_MONEY;
+                else
+                    gParkFlags &= ~PARK_FLAGS_NO_MONEY;
+            }
```
Comment (IntelOrca) [inline src/openrct2/rct2/S6Importer.cpp:265]: Thanks, error on my part - shouldn't of combine the conditions in the IF.

**Review by IntelOrca — APPROVED** [review]
