### PR TITLE
Close #17073: Writing out of bounds when trains have over 144 cars

### LINKED ISSUE #17073: Corrupt ride window when trains have more than 144 cars
This is likely the source of many crash reports that have to do with the ride window's events. When there are more than 144 cars, `WindowRideVehicleScrollpaint` writes out of bounds, overwriting other static fields (most likely the others in `Ride.cpp` though).

The static array:
https://github.com/OpenRCT2/OpenRCT2/blob/85baa6f7ca55bb5745dec0514b9854234f51b161/src/openrct2-ui/windows/Ride.cpp#L2906

Used in this loop, which may loop more than 144 times for cheated trains:
https://github.com/OpenRCT2/OpenRCT2/blob/85baa6f7ca55bb5745dec0514b9854234f51b161/src/openrct2-ui/windows/Ride.cpp#L2932-L2934

Writing out of bounds here:
https://github.com/OpenRCT2/OpenRCT2/blob/85baa6f7ca55bb5745dec0514b9854234f51b161/src/openrct2-ui/windows/Ride.cpp#L2971-L2974

Making sure the array is longer than the maximum number of vehicles may fix this, though since trains can have invisible cars, I'm not entirely sure the actual number can still be higher than 255.

### PR DESCRIPTION
**Pull request by Broxzier**
This fixes some of the unclear "openrct2.exe openrct2.exe openrct2.exe openrct2.exe openrct2.exe" etc crash logs we've been getting. The array was not large enough to hold more than 144 cars. Now the array is long enough, and a `static_assert` ensures that it will stay that way or generate an error during compile time.

This fixes:
 - https://github.com/OpenRCT2/OpenRCT2/issues/17066
 - https://github.com/OpenRCT2/OpenRCT2/issues/16927
 - https://github.com/OpenRCT2/OpenRCT2/issues/17051
 - https://github.com/OpenRCT2/OpenRCT2/issues/16758
 - https://github.com/OpenRCT2/OpenRCT2/issues/16702

And maybe more, I went back 3 months on the issue tracker.

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -2929,13 +2928,15 @@ static void WindowRideVehicleScrollpaint(rct_window* w, rct_drawpixelinfo* dpi,
     startY += rideVehicleEntry->tab_height;
 
     // For each train
+    static VehicleDrawInfo _sprites_to_draw[OpenRCT2::Limits::MaxCarsPerTrain];
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Ride.cpp:2931]: Can you change the name to trainCarImages. This should really be a fixed size vector but it will require refactoring to use. Also move the definition to l2934 and drop the static we don't want to waste time checking if the array is constructed every loop and that should help the optimiser

**Review by duncanspumpkin — APPROVED** [review]
