### PR TITLE
Fix #20164: Grass and Rock terrain objects cannot be de-selected

### LINKED ISSUE #20164: Grass and Rock terrain objects cannot be de-selected
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The Terrain Surface of grass and the Terrain Edge of rock are permanently enabled, not allowing a player to de-select the objects, even if there is no grass or rock in any surface in the map.

### Steps to reproduce

An associated .park file has also been attached which will allow you to skip immediately to Step 3.

1. Open any park and enable sandbox mode
2. Change all terrain to use a surface other than grass and an edge other than rock (easiest to do if you also decrease the size of the map by clicking the compass icon in the top left menu)
3. Under Cheats, select the Object Selection window
4. Toggle to view the Advanced selections
5. Go to Terrain Surfaces/Terrain Edges
6. See that Grass/Rock are permanently selected despite not being present in the map (this can be seen by the fact the checkmark is greyed out instead of being white, and when clicked, it displays the message, "Unable to de-select this object. This object is currently in use")

### Attachments

[Park File with no Grass or Rock](https://github.com/OpenRCT2/OpenRCT2/files/11424473/park.zip)

Grass Error
Rock Error

### PR DESCRIPTION
**Pull request by KatieZeldaKat**
Fixes #20164.

After investigating, @Gymnasiast's prediction was correct, and the surface tiles in the void were being taken into consideration for the object selection check in `SetupInUseSelectionFlags()`. The simple fix was to modify how the `TileElementIterator` is updated so it only looks at the tiles on the map. I couldn't find a reason this iterator originally checked the maximum size of a map every single time as I was looking through the references to the functions. The now reduced tiles to check should improve performance when using this iterator on smaller maps, albeit probably not by much.

Todo:

- [x] ~~Fix default sprites in Land tool~~

### CODE REVIEW

**Comment by duncanspumpkin** [comment]
I'm not sure if this would be safe to do. I guess its fine as long as the object selection always ensures that you can't close it without first selecting a style. Could you confirm that that happens.

**Comment by KatieZeldaKat** [comment]
> I'm not sure if this would be safe to do. I guess its fine as long as the object selection always ensures that you can't close it without first selecting a style. Could you confirm that that happens.

If I'm understanding you correctly, that would be impossible. Even if you had the entire park be Void, that means the object check would grey out that option (as objects being used cannot be deselected). No matter what, each tile should have some style of surface and/or edge, and thus you can't close the object selection without having at least one.

This PR does make it so that you don't have to have the default surface and edges selected at all times, however. You'd just need the ones in the park.

File: src/openrct2/world/Map.cpp [hunk 1]
```diff
@@ -313,16 +313,16 @@ int32_t TileElementIteratorNext(TileElementIterator* it)
         return 1;
     }
```
Comment (Harry-Hopkinson) [inline src/openrct2/world/Map.cpp:315]: You could create a reference to the gameState to avoid fetching it twice.

```cpp
auto& gameState = GetGameState();
```

File: src/openrct2/world/Map.cpp [hunk 2]
```diff
@@ -313,16 +313,16 @@ int32_t TileElementIteratorNext(TileElementIterator* it)
...
 
-    if (it->y < (MAXIMUM_MAP_SIZE_TECHNICAL - 1))
+    if (it->y < (GetGameState().MapSize.y - 2))
```
Comment (Harry-Hopkinson) [inline src/openrct2/world/Map.cpp:316]: You could create a reference to the gameState to avoid fetching it twice.

```cpp
auto& gameState = GetGameState();
```

Comment (KatieZeldaKat) [reply src/openrct2/world/Map.cpp]: Implemented this.

**Review by Harry-Hopkinson — APPROVED** [review]

**Review by Gymnasiast — APPROVED** [review]
Seems to work correctly. Also verified that, as @KatieZeldaKat said, it is impossible to deselect _all_ land types as one of them will always be in use.

**Review by tupaschoal — APPROVED** [review]
