### PR TITLE
Fix #6388: Construction rights wrongly shown as available on some RCT1 parks

### LINKED ISSUE #6388: Game sometimes offers to buy construction rights even if none are available
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 0217734c4ef4b83e2e68f8c239c03bf37e43637d

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start a new game with the RCT1 scenario "Trinity Islands"
2. Open the "Buy land rights and construction rights" window
3. The button for construction rights is enabled while the other button is disabled but selected
4. Clicking on the other button reveals no buyable construction rights

In RCT2 scenarios this seems to work correctly.

### PR DESCRIPTION
**Pull request by rwjuk**
Some RCT1 parks seemingly have owned tiles with the 'construction rights available' flag set, which led to the behaviour in #6388. This PR tweaks the conditions to check for ownership first.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Some RCT1 parks (e.g. Urban Park) have tiles that both full and construction rights for sale. This is also technically possible in SV6, but never used and not supported in the Scenario Editor.

File: src/openrct2/world/map.c [hunk 1]
```diff
@@ -434,20 +434,31 @@ void map_count_remaining_land_rights()
...
 
             uint8 flags = element->properties.surface.ownership;
 
-            if ((flags & OWNERSHIP_AVAILABLE) && (flags & OWNERSHIP_OWNED) == 0) {
-                gLandRemainingOwnershipSales++;
-            } else if ((flags & OWNERSHIP_CONSTRUCTION_RIGHTS_AVAILABLE) && (flags & OWNERSHIP_CONSTRUCTION_RIGHTS_OWNED) == 0) {
-                gLandRemainingConstructionSales++;
+            // Do not combine this condition with (flags & OWNERSHIP_AVAILABLE)
+            // As some RCT1 parks have owned tiles with the 'construction rights available' flag also set
+            if ((flags & OWNERSHIP_OWNED) == 0)
```
Comment (Gymnasiast) [inline src/openrct2/world/map.c]: I'd prefer
```
if (!(flags & OWNERSHIP_OWNED))
```
I think it's a little more explicit.

**Comment by rwjuk** [comment]
@Gymnasiast WRT Urban Park and other cases where construction and full rights are available, this change won't affect that (I tested it). If the full rights exist, the entire 'rights available' block will be skipped, which is expected behaviour - no point in buying construction rights if you own the tile.

Conditional style changed.

**Comment by Gymnasiast** [comment]
@rwjuk I know, I was just providing the reason why this situation can occur.

**Comment by rwjuk** [comment]
@Gymnasiast Ahh, I see - sorry. Changelog updated.
