### PR TITLE
Fix #21748: TileElement out of bounds

### LINKED ISSUE #21748: [83461e] openrct2.exe: TileElementBase::GetBaseZ
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiI4MzQ2MWU3YWZjZDlhOTE2OTE5MGE3YWI5ODY1NWU1OWNlYjM3ZWE5ZGY2YWU5N2IxMmVkZjI3ZjllNDUyYTY4IiwidHgiOjI1OTIxfSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=83461e7afcd9a9169190a7ab98655e59ceb37ea9df6ae97b12edf27f9e452a68&amp;_tx=6541&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Sun Apr 07 2024 20:50:57 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\mrvos\Documents\OpenRCT2\crash\baa015bc-ef74-4f3b-a74c-2a9fd3a52d56.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                <code>828eb0e</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x02</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.10-15-g828eb0e (828eb0e on develop) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>27000000-a3a2-c30b-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>{&#34;frame&#34;:[&#34;TileElementBase::GetBaseZ&#34;,&#34;MapAnimationAutoCreateAtTileElement&#34;]}</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> TileElementBase::GetBaseZ MapAnimationAutoCreateAtTileElement </code>
        </td>
    </tr>
     </table>

### PR DESCRIPTION
**Pull request by janisozaur**
This fixes crashes observed and allows the park to load. The park is overlarge and breaks some assumptions we have in our code.

### CODE REVIEW

File: src/openrct2/world/Map.cpp [hunk 1]
```diff
@@ -301,7 +301,14 @@ int32_t TileElementIteratorNext(TileElementIterator* it)
...
         it->element = MapGetFirstElementAt(TileCoordsXY{ it->x, it->y });
-        return 1;
+        if (it->element == nullptr)
+        {
+            return 0;
+        }
+        else
+        {
+            return 1;
+        }
```
Comment (tupaschoal) [inline src/openrct2/world/Map.cpp:311]: I'd use a ternary, but I understand some people don't like it (applies elsewhere)

**Comment by janisozaur** [comment]
Regression from #21399

**Comment by AaronVanGeffen** [comment]
Good to hear the fix is working. I agree with @tupaschoal that ternaries might be better, code style-wise, though. Would you mind amending?

File: src/openrct2/world/Map.cpp [hunk 2]
```diff
@@ -314,15 +321,29 @@ int32_t TileElementIteratorNext(TileElementIterator* it)
...
```
Comment (janisozaur) [inline src/openrct2/world/Map.cpp:346]:
```suggestion
        return it->element == nullptr ? 0 : 1;
```

**Review by AaronVanGeffen — APPROVED** [review]

**Review by ZehMatt — APPROVED** [review]
