### PR TITLE
 Close #11209: Show a warning when the user is running OpenRCT2 in Wine

### LINKED ISSUE #11209: Detect when user is running OpenRCT2 via Wine
If a user is running OpenRCT2 via Wine, it is likely to be a mistake. Perhaps they assumed they needed the Windows version because they extract their RCT2 files that way.

This could have lead to crashes like https://github.com/OpenRCT2/OpenRCT2/issues/11205 .

When the game detects Wine, it could then display a warning in the same way that it already warns for running as root.

### PR DESCRIPTION
**Pull request by ifimfree**
Adds functionality to display a warning (similar to that of the warning displayed when running on root) when the user is detected to be using Wine to run the application instead of the better supported Linux per Issue #11209

### CODE REVIEW

File: src/openrct2/platform/platform.h [hunk 1]
```diff
@@ -124,6 +124,7 @@ uint8_t platform_get_locale_temperature_format();
 uint8_t platform_get_locale_date_format();
 bool platform_process_is_elevated();
 bool platform_get_steam_path(utf8* outPath, size_t outSize);
+bool is_running_in_wine();
```
Comment (AaronVanGeffen) [inline src/openrct2/platform/platform.h:127]: platform.h is a legacy file. Please use Platform2.h instead. We are in the process of transitioning, sorry about that…

A version of this function will need to be implemented for other platforms, too, even if it just returns false. I think you can put it in Platform.Posix.cpp.

File: src/openrct2/platform/Windows.cpp [hunk 2]
```diff
@@ -693,6 +693,17 @@ void platform_remove_file_associations()
     SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, nullptr, nullptr);
 }
 
+bool is_running_in_wine()
```
Comment (AaronVanGeffen) [inline src/openrct2/platform/Windows.cpp:696]: Please define this in Platform.Win32.cpp instead.

**Comment by AaronVanGeffen** [comment]
Thanks for tackling this. Could you split off the unrelated (flag) changes to another PR?

File: src/openrct2/localisation/StringIds.h [hunk 3]
```diff
@@ -3911,8 +3911,10 @@ enum
 
     STR_COPY_INPUT_TO_CLIPBOARD = 6363,
 
+    STR_WINE_NOT_RECOMMENDED = 6368,
+
     // Have to include resource strings (from scenarios and objects) for the time being now that language is partially working
-    STR_COUNT = 32768
+    STR_COUNT = 32769
```
Comment (Gymnasiast) [inline src/openrct2/localisation/StringIds.h:3917]: I understand why you incremented this, but it shouldn't be incremented when you add strings.

File: data/language/en-GB.txt [hunk 4]
```diff
@@ -3677,6 +3677,7 @@ STR_6360    :{SMALLFONT}{BLACK}{COMMA32}
 STR_6361    :Enable lighting effects on rides (experimental)
 STR_6362    :{SMALLFONT}{BLACK}If enabled, vehicles for tracked rides will be lit up at night.
 STR_6363    :Copied text to clipboard
+STR_6368    :For compatability reasons, it is not recommended to run OpenRCT2 with WINE. Instead, Linux is supported.
```
Comment (tupaschoal) [inline data/language/en-GB.txt:3680]: A few comments:
- The number should be the increment from the previous
- Typo fix and a change on the last sentence which I think makes it clearer.
```suggestion
STR_6364    :For compatibility reasons, it is not recommended to run OpenRCT2 with WINE. Linux is natively supported.
```

File: src/openrct2/localisation/StringIds.h (hunk 3 above)
Comment (tupaschoal) [inline src/openrct2/localisation/StringIds.h:3917]: Just adding a suggestion reflecting what Gymnasiast said.
```suggestion
    STR_COUNT = 32768
```

File: src/openrct2/localisation/StringIds.h [hunk 5]
```diff
@@ -3911,8 +3911,10 @@ enum
 
     STR_COPY_INPUT_TO_CLIPBOARD = 6363,
 
+    STR_WINE_NOT_RECOMMENDED = 6368,
```
Comment (tupaschoal) [inline src/openrct2/localisation/StringIds.h:3914]:
```suggestion
    STR_WINE_NOT_RECOMMENDED = 6364,
```
To reflect the suggestion above.

File: src/openrct2/platform/Platform2.h [hunk 6]
```diff
@@ -44,7 +44,7 @@ namespace Platform
 #ifdef _WIN32
     bool IsOSVersionAtLeast(uint32_t major, uint32_t minor, uint32_t build);
 #endif
-
+    bool is_running_in_wine();
```
Comment (tupaschoal) [inline src/openrct2/platform/Platform2.h:47]: This should follow the style of the file (which is actually our coding guideline
```suggestion
    bool IsRunningInWine();
```

File: data/language/en-GB.txt [hunk 7]
```diff
@@ -3677,7 +3677,7 @@ STR_6360    :{SMALLFONT}{BLACK}{COMMA32}
 STR_6361    :Enable lighting effects on rides (experimental)
 STR_6362    :{SMALLFONT}{BLACK}If enabled, vehicles for tracked rides will be lit up at night.
 STR_6363    :Copied text to clipboard
-
+STR_6368    :For compatibility reasons, it is not recommended to run OpenRCT2 with WINE. Linux is natively supported.
```
[the remark this answers is not in the document]
Comment (janisozaur) [reply data/language/en-GB.txt:3680]: Wine is available for other platforms: BSD, OS X, Android… don't assume Linux.

[the remark this answers is not in the document]
Comment (Gymnasiast) [reply data/language/en-GB.txt:3680]: @tupaschoal STR_6364 has already been used. The number is correct, but the OP has branched off an outdated `develop`.

[the remark this answers is not in the document]
Comment (Gymnasiast) [reply data/language/en-GB.txt:3680]: The Wine project writes its name like that - with only a capital at the start.

To address this and janisozaur's point:
```suggestion
STR_6368    :For compatibility reasons, it is not recommended to run OpenRCT2 with Wine. OpenRCT2 has native support for macOS, Linux, FreeBSD and NetBSD.
```

**Comment by Gymnasiast** [comment]
You reverted a few commits, but you should have dropped them using a rebase. Since there are some conflicts, you will need to do so anyway.

If you're unsure how to do it, we can help you with it.

File: src/openrct2/localisation/StringIds.h (hunk 3 above)
Comment (pizza2004) [reply src/openrct2/localisation/StringIds.h]: I see people make this mistake all the time, perhaps it would be a good idea to change this name to something like MAX_STR_COUNT instead?

File: data/language/en-GB.txt (hunk 7 above)
[the remark this answers is not in the document]
Comment (tupaschoal) [reply data/language/en-GB.txt:3680]: Ah, I see, thanks for clarifying Michael

File: src/openrct2/localisation/StringIds.h (hunk 3 above)
Comment (tupaschoal) [reply src/openrct2/localisation/StringIds.h]: It's a good idea indeed, or to add a comment explaining. I'll see if I can tend to it today

**Comment by ifimfree** [comment]
Thanks all for being so patient with me, I'm quite new both to this project and (honestly) also to Git.

In terms of needing to rebase, I've never had to do that sort of thing before.  Will the following work?  This is what I found by looking around but want to be sure this will give the intended result.

git remote add upstream https://github.com/OpenRCT2/OpenRCT2.git
git fetch upstream
git rebase upstream/develop
git push origin wine-detection

File: src/openrct2/localisation/StringIds.h [hunk 8]
```diff
@@ -3911,6 +3911,8 @@ enum
 
     STR_COPY_INPUT_TO_CLIPBOARD = 6363,
 
+    STR_WINE_NOT_RECOMMENDED = 6364,
```
Comment (Gymnasiast) [inline src/openrct2/localisation/StringIds.h:3914]:
```suggestion
    STR_WINE_NOT_RECOMMENDED = 6368,
```

**Comment by tupaschoal** [comment]
> Thanks all for being so patient with me, I'm quite new both to this project and (honestly) also to Git.
> 
> In terms of needing to rebase, I've never had to do that sort of thing before. Will the following work? This is what I found by looking around but want to be sure this will give the intended result.
> 
> git remote add upstream https://github.com/OpenRCT2/OpenRCT2.git
> git fetch upstream
> git rebase upstream/develop
> git push origin wine-detection

There are multiple ways of doing so, typically the upstream is already configured, you can check it out with `git remote -v`. Then you need to:
1 - `git checkout develop` checkout your local develop
2 - `git fetch upstream` fetch changes from the main `OpenRCT2` repo
3 - `git rebase upstream/develop` rebase your develop onto OpenRCT2/develop
4 - `git checkout wine-detection` checkout your branch again
5 - `git rebase -i develop` this is to interactively rebase your current branch atop your own develop, you can omit the `-i` i you want

**Comment by ifimfree** [comment]
I seem to have messed up what/how I rebased - currently trying to fix this.

File: src/openrct2/platform/Posix.cpp [hunk 9]
```diff
@@ -488,6 +489,11 @@ bool platform_process_is_elevated()
 #    endif // __EMSCRIPTEN__
 }
 
+bool Platform::IsRunningInWine()
```
Comment (Gymnasiast) [inline src/openrct2/platform/Posix.cpp:492]: This needs to be in Platform.Posix.cpp, in the same way it had to go into Platform.Win32.cpp.

**Comment by Gymnasiast** [comment]
I have nuked your branch and cherry-picked the commits. They'll still need to be squashed on merging, and there are still two line notes to address, along with the formatting.
