### PR TITLE
Fix #15289: Duplicated banner correction using the wrong index

### LINKED ISSUE #15289: Fix Banner Fix
The fix duplicate banners is broken and produces corrupted banners. 
https://github.com/OpenRCT2/OpenRCT2/blob/465d1c541446569fec7c627653ff5ea9543eea63/src/openrct2/world/Banner.cpp#L296
This bit of code overwrites the new banner id!
Modify the code to save the ID prior to copying over the other banner and then actually set the ID!

### PR DESCRIPTION
**Pull request by ZehMatt**
I also took the liberty of cleaning up the code a bit.

Closes #15289

### CODE REVIEW

File: src/openrct2/world/Banner.cpp [hunk 1]
```diff
@@ -253,57 +254,50 @@ void fix_duplicated_banners()
...
+                    log_info(
+                        "Duplicated banner with index %d found at x = %d, y = %d and z = %d.", bannerIndex, x, y,
+                        bannerElement->base_height);
+
+                    // Banner index is already in use by another banner, so duplicate it
+                    auto newBanner = CreateBanner();
+                    if (newBanner == nullptr)
+                    {
+                        log_error("Failed to create new banner.");
+                        continue;
```
Comment (ZehMatt) [inline src/openrct2/world/Banner.cpp:281]: I think if it comes down to this it should probably just return, any further attempt will likely return nullptr.

**Review by Gymnasiast — APPROVED** [review]
Looks good, have you been able to test it?

**Comment by ZehMatt** [comment]
> Looks good, have you been able to test it?

I did, I whacked the tile inspector to allow duplications and saved the park, it did fix them correctly.
