### PR TITLE
Fix #20843: Remove 0 padding from file path in scenario index filename

### LINKED ISSUE #20843: Scenario completion lost
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2, v0.4.6-44-g39ecab4

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Previously completed scenarios have been lost, so non-beginner parks are locked.

Save files still exist and open of completed parks, but no parks are unlocked.

### Steps to reproduce

Open the game
Select start a new game

### Attachments

Screenshot 2023-10-03 203645

### PR DESCRIPTION
**Pull request by ZehMatt**
Regression from #20700

Closes #20843

### CODE REVIEW

File: src/openrct2/scenario/ScenarioRepository.cpp [hunk 1]
```diff
@@ -155,6 +155,15 @@ class ScenarioFileIndex final : public FileIndex<ScenarioIndexEntry>
     void Serialise(DataSerialiser& ds, const ScenarioIndexEntry& item) const override
     {
         ds << item.Path;
+        if (ds.IsLoading())
```
Comment (duncanspumpkin) [inline src/openrct2/scenario/ScenarioRepository.cpp:158]: Are we sure this is the only place we need to do this

Comment (ZehMatt) [reply src/openrct2/scenario/ScenarioRepository.cpp:158]: Only place affected by the PR

**Review by duncanspumpkin — APPROVED** [review]
