### PR TITLE
Fix #11752: Track pieces with fractional cost are too cheap to build

### LINKED ISSUE #11752: Free money exploit with level-to-steep elements of hypercoasters
**OS:** Win 10
**Version:** 0.2.6, 0.3.0
**Commit/Build:** 6c3c857, 135cc10

Building a level to steep element of a hypercoaster costs $0.50 less than demolishing it, causing you to gain $0.50 every time you build and delete such an element on level ground.

- Reproducible in RCT2 (vanilla)? **No**
- Specific to multiplayer? **No**

**Steps to reproduce:**
1. Start a hypercoaster.
2. Build a station.
3. Build a level to steep element.
4. Demolish the level to steep element.
5. You've just made $0.50!

**Save game:**
[Test Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/4631299/Test.Park.zip)

### PR DESCRIPTION
**Pull request by CookiePLMonster**
Fixes an inconsistency with RCT2 where track prices with a fractional part did not have their price rounded up when building, but did when refunding.

This created an exploit where refunding such a track piece granted the player 0.50€ more than they spent on the piece.

Mazes are also affected looking at `MazePlaceTrackAction`, so I corrected it. However, I don't know how does it compare to RCT2.

References:
1. With a hacked currency format display, we can clearly see building pieces of Chairlift at specific levels costs less than what is refunded.
image
2. The bug has already been researched here, but never fixed: https://github.com/OpenRCT2/OpenRCT2/issues/11752#issuecomment-629992728
2. Marcel Vos mentioned this disparity between RCT2 and OpenRCT2 in one of his videos (timestamped): https://youtu.be/EFE37bU9R2A?t=247
However, it's incorrectly assumed to be a fix.

Fixes #11752

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
Side note: In the very same video, Marcel Vos notices that **Boat Hire** does have support cost (despite not having visible supports), while **Submarine Ride** does not have any support costs (despite having visible supports). You can see this under this timestamp: https://youtu.be/EFE37bU9R2A?t=406

Do you think this could be considered an original game bug? It affects both RCT2 and OpenRCT2, but makes absolutely no sense and looks like an error.

File: src/openrct2/actions/TrackPlaceAction.cpp [hunk 1]
```diff
@@ -522,7 +522,7 @@ GameActions::Result TrackPlaceAction::Execute() const
             supportHeight = (10 * COORDS_Z_STEP);
         }
 
-        cost += ((supportHeight / (2 * COORDS_Z_STEP)) * ride->GetRideTypeDescriptor().BuildCosts.SupportPrice) * 5;
+        cost += (supportHeight / (2 * COORDS_Z_STEP)) * ride->GetRideTypeDescriptor().BuildCosts.SupportPrice;
```
Comment (Gymnasiast) [inline src/openrct2/actions/TrackPlaceAction.cpp:525]: This looks incorrect - why did you remove the `* 5` part?

**Comment by Gymnasiast** [comment]
> Side note: In the very same video, Marcel Vos notices that Boat Hire does have support costs (despite not having visible supports), while Submarine Ride does not have any support costs (despite having visible supports). You can see this under this timestamp: https://youtu.be/EFE37bU9R2A?t=406
>
> Do you think this could be considered an original game bug? It affects both RCT2 and OpenRCT2, but makes absolutely no sense and looks like an error.

Yes, I think so. If you’d like to fix it, please open another PR for that.

File: src/openrct2/actions/TrackPlaceAction.cpp (hunk 1 above)
Comment (CookiePLMonster) [reply src/openrct2/actions/TrackPlaceAction.cpp:525]: The previous cost was calculated as
`canBuild.Cost + price / 2 * 10;`
which is
`canBuild.Cost + (price / 2 * 10);`
so I assumed that the `* 5` in this line was added to offset too low costs introduced by this parenthesis bug. I have not checked the original disassembly though so maybe it should be something yet different, but looking at what @duncanspumpkin found previously I am almost 100% sure that the algo should be `((canBuild.Cost + price) / 2) * 10;`. Maybe costs are too high for a reason different than this `* 5`?

Comment (duncanspumpkin) [reply src/openrct2/actions/TrackPlaceAction.cpp:525]: image
This is the original code. dl is the supportHeight / Coords_Z_step. So it is doing `cost += (dl / 2) * supportPrice` Your change looks correct.

File: src/openrct2/actions/TrackPlaceAction.cpp [hunk 2]
```diff
@@ -400,7 +400,7 @@ GameActions::Result TrackPlaceAction::Query() const
     price *= ted.Price;
 
     price >>= 16;
-    res.Cost = cost + ((price / 2) * 10);
+    res.Cost = ((cost + price) / 2) * 10;
```
Comment (duncanspumpkin) [inline src/openrct2/actions/TrackPlaceAction.cpp:403]: You need to also modify line 396

Comment (CookiePLMonster) [reply src/openrct2/actions/TrackPlaceAction.cpp:403]: Good catch, fixed

File: src/openrct2/actions/MazePlaceTrackAction.cpp [hunk 3]
```diff
@@ -119,7 +119,7 @@ GameActions::Result MazePlaceTrackAction::Query() const
 
     const auto& ted = GetTrackElementDescriptor(TrackElemType::Maze);
     money32 price = (((ride->GetRideTypeDescriptor().BuildCosts.TrackPrice * ted.Price) >> 16));
-    res.Cost = canBuild.Cost + price / 2 * 10;
+    res.Cost = ((canBuild.Cost + price) / 2) * 10;
```
Comment (duncanspumpkin) [inline src/openrct2/actions/MazePlaceTrackAction.cpp:122]: This differs from vanilla. For whatever reason it did `canBuild.Cost + price / 2 * 10;` It makes sense that it would do that tbh.

Comment (CookiePLMonster) [reply src/openrct2/actions/MazePlaceTrackAction.cpp:122]: Thanks for checking, this is the one change I made blindly without knowing if it's correct. Good to know it can stay.

Comment (duncanspumpkin) [reply src/openrct2/actions/MazePlaceTrackAction.cpp:122]: Does it actually make sense.

Comment (CookiePLMonster) [reply src/openrct2/actions/MazePlaceTrackAction.cpp:122]: The cost of placing a premade layout should be the same as the cost of building that layout by hand, right? Seems to me like it makes sense for them to be calculated the same way.

**Comment by CookiePLMonster** [comment]
Rebased to fix the changelog conflict.

File: src/openrct2/actions/MazePlaceTrackAction.cpp (hunk 3 above)
Comment (Gymnasiast) [reply src/openrct2/actions/MazePlaceTrackAction.cpp:122]: @duncanspumpkin What do you think we should do? Follow vanilla or do what the other occurrences do?

Comment (duncanspumpkin) [reply src/openrct2/actions/MazePlaceTrackAction.cpp:122]: yeah keep it as per @CookiePLMonster 's design.

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Can you rebase and bump the network version, Cookie? We’re going to merge it.

**Comment by CookiePLMonster** [comment]
Done! I hope I changed the right version number, please check.
