### PR TITLE
Fix #7180: Compiler error: trackType may be used uninitialised

### LINKED ISSUE #7180: Compiler error: trackType may be used uninitialised (_legacy.cpp:349)
**OS:** Gentoo Linux (64-bit)
**Version:** Kernel 4.14.7
**Commit/Build:** 9cc8d36
**Compiler:**
```
$ gcc --version
gcc (Gentoo 6.4.0-r1 p1.3) 6.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Trying to compile the project in the last few days is failing with the following compiler output during make:

```
[ 68%] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/world/Entrance.cpp.o
/usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++ -DOPENGL_NO_LINK -D__ENABLE_LIGHTFX__ -D__WARN
_SUGGEST_FINAL_METHODS__ -D__WARN_SUGGEST_FINAL_TYPES__ -isystem /usr/lib64/libzip/include -
I/usr/include/libpng16 -I/usr/include/freetype2   -DNDEBUG -march=native -Os -pipe -fomit-frame-pointer -Wnull-dereference -Wsuggest-final-types -Wsuggest-final-methods -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wredundant-decls -Wignored-qualifiers -Wstrict-overflow=1 -std=gnu++14  -fstrict-overflow -fstrict-aliasing -Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wno-unknown-pragmas -Wno-unused-function -Wno-missing-braces  -Wno-comment -Wshadow  -Wmissing-declarations -Wnonnull -DDEBUG=0 -fPIC -std=gnu++14 -std=gnu++14   -Wundef -pthread -o CMakeFiles/libopenrct2.dir/src/openrct2/world/Entrance.cpp.o -c /var/tmp/portage/games-simulation/openrct2-9999/work/openrct2-9999/src/openrct2/world/Entrance.cpp
/var/tmp/portage/games-simulation/openrct2-9999/work/openrct2-9999/src/openrct2/windows/_legacy.cpp: In function ‘bool sub_6CA2DF(sint32*, sint32*, sint32*, sint32*, sint32*, sint32*, sint32*, sint32*)’:
/var/tmp/portage/games-simulation/openrct2-9999/work/openrct2-9999/src/openrct2/windows/_legacy.cpp:349:83: error: ‘trackType’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         if (ride->type != RIDE_TYPE_WATER_COASTER || trackType == TRACK_ELEM_FLAT || trackType == TRACK_ELEM_LEFT_QUARTER_TURN_5_TILES || trackType == TRACK_ELEM_RIGHT_QUARTER_TURN_5_TILES) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/libopenrct2.dir/build.make:6375: CMakeFiles/libopenrct2.dir/src/openrct2/windows/_legacy.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/games-simulation/openrct2-9999/work/openrct2-9999_build'
make[1]: *** [CMakeFiles/Makefile2:142: CMakeFiles/libopenrct2.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/games-simulation/openrct2-9999/work/openrct2-9999_build'
make: *** [Makefile:130: all] Error 2
```

Here's the excerpt from function `bool sub_6CA2DF`:

```
/**
 * rct2: 0x006CA2DF
 *
 * @param[out] _trackType (dh)
 * @param[out] _trackDirection (bh)
 * @param[out] _rideIndex (dl)
 * @param[out] _liftHillAndAlternativeState (liftHillAndAlternativeState)
 * @param[out] _x (ax)
 * @param[out] _y (cx)
 * @param[out] _z (di)
 * @param[out] _properties (edirs16)
 * @return (CF)
 */
bool sub_6CA2DF(sint32 *_trackType, sint32 *_trackDirection, sint32 *_rideIndex, sint32 *_li
ftHillAndAlternativeState, sint32 *_x, sint32 *_y, sint32 *_z, sint32 *_properties) {
    uint8 trackType, trackDirection, rideIndex;
    uint16 z, x, y, liftHillAndAlternativeState, properties;

    if (!sub_6CA2DF_get_track_element(&trackType)) {
        return true;
    }

    liftHillAndAlternativeState = 0;
    rideIndex = _currentRideIndex;
    if (_currentTrackLiftHill & CONSTRUCTION_LIFT_HILL_SELECTED) {
        liftHillAndAlternativeState |= CONSTRUCTION_LIFT_HILL_SELECTED;
    }

    if (_currentTrackAlternative & RIDE_TYPE_ALTERNATIVE_TRACK_TYPE) {
        liftHillAndAlternativeState |= RIDE_TYPE_ALTERNATIVE_TRACK_TYPE;
    }

    Ride *ride = get_ride(rideIndex);

    if (_enabledRidePieces & (1ULL << TRACK_SLOPE_STEEP_LONG)) {
        switch (trackType) {
        case TRACK_ELEM_FLAT_TO_60_DEG_UP:
            trackType = TRACK_ELEM_FLAT_TO_60_DEG_UP_LONG_BASE;
            break;

        case TRACK_ELEM_60_DEG_UP_TO_FLAT:
            trackType = TRACK_ELEM_60_DEG_UP_TO_FLAT_LONG_BASE;
            break;

        case TRACK_ELEM_FLAT_TO_60_DEG_DOWN:
            trackType = TRACK_ELEM_60_DEG_UP_TO_FLAT_LONG_BASE_122;
            break;

        case TRACK_ELEM_60_DEG_DOWN_TO_FLAT:
            trackType = TRACK_ELEM_FLAT_TO_60_DEG_DOWN_LONG_BASE;
            break;

        case TRACK_ELEM_DIAG_FLAT_TO_60_DEG_UP:
        case TRACK_ELEM_DIAG_60_DEG_UP_TO_FLAT:
        case TRACK_ELEM_DIAG_FLAT_TO_60_DEG_DOWN:
        case TRACK_ELEM_DIAG_60_DEG_DOWN_TO_FLAT:
            return true;
        }
    }

    if (ride_type_has_flag(ride->type, RIDE_TYPE_FLAG_TRACK_ELEMENTS_HAVE_TWO_VARIETIES) && _currentTrackAlternative & RIDE_TYPE_ALTERNATIVE_TRACK_PIECES) {
        if (ride->type != RIDE_TYPE_WATER_COASTER || trackType == TRACK_ELEM_FLAT || trackType == TRACK_ELEM_LEFT_QUARTER_TURN_5_TILES || trackType == TRACK_ELEM_RIGHT_QUARTER_TURN_5_TILES) {
            sint16 alternativeType = AlternativeTrackTypes[trackType];
            if (alternativeType > -1) {
                trackType = (uint8) alternativeType;
            }
            liftHillAndAlternativeState &= ~CONSTRUCTION_LIFT_HILL_SELECTED;
        }
    }
```

I'm not sure what's wrong. I suspect the compiler thinks that by the time the variable's value needs to be considered in the if statement that it might not have been defined yet, perhaps because the switch block has no `default`, but from what I've gathered this variable actually will always be defined earlier in the function (in a function call taking trackType's reference as a parameter.) As a result I was not sure what could be an appropriate code change to solve this issue, so I've filed this report.

Perhaps I'm mistaken but nonetheless if more information about my build environment or runtime environment will help, I can provide that.

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

File: src/openrct2/windows/_legacy.cpp [hunk 1]
```diff
@@ -28,6 +28,8 @@
 #include "../world/Scenery.h"
 #include "Intent.h"
 
+#include <tuple>
```
Comment (IntelOrca) [inline src/openrct2/windows/_legacy.cpp]: At the top?
