### PR TITLE
Fix #6118, #6245, #6366: Tracked animated vehicles not animating

### LINKED ISSUE #6118: Miniature railway's wheels no longer turn
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.0]
**Commit/Build:** [e.g. 426e106]

The miniature railway's driving wheels are static and do not rotate. This does not happen in RCT2 and hasn't happened in any previous version of ORCT2 I've seen.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

### LINKED ISSUE #6245: multi-dimension coaster's car-angulation inacurate
**OS:**vista 32-bit
**Version:** 0.1.2 x86
**Commit/Build:** 49066ba

This multi dimension coaster's car angulation is non reflective of what i programmed. Several game updates ago the ride _was_ displaying the car-angles that i programmed. I tested this coaster in vanilla by opening the same exact park in vanilla, and the coaster's car angulations **_were_** reflective of what i intended.

- [does not occur in vanilla] Reproducible in RCT2 (vanilla)?
- [did not test] Multiplayer?

**Steps to reproduce:**
1. observe car-angulation of coaster while it operates in openrct2 vs. observing it's car angulation while it operates in vanilla.
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

[the fourth dimension by  JoshMarsilio 1.0.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1272707/the.fourth.dimension.by.JoshMarsilio.1.0.sv6.zip)

### PR DESCRIPTION
**Pull request by oli414**
Fixes https://github.com/OpenRCT2/OpenRCT2/issues/6245

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Hm, if the error is really in the line you modified, then it should have been broken for a _long_ time. Is it broken in, say, 0.0.4?

File: src/openrct2/ride/vehicle.h [hunk 1]
```diff
@@ -232,8 +232,8 @@ enum {
     VEHICLE_ENTRY_FLAG_ENABLE_ADDITIONAL_COLOUR_2 = 1 << 9,
     VEHICLE_ENTRY_FLAG_10 = 1 << 10,
     VEHICLE_ENTRY_FLAG_11 = 1 << 11,
-    VEHICLE_ENTRY_FLAG_OVERRIDE_NUM_VERTICAL_FRAMES = 1 << 12,            // Setting this will cause the game to set vehicleEntry->num_vertical_frames to vehicleEntry->num_vertical_frames_override, rather than determining it itself.
-    VEHICLE_ENTRY_FLAG_13 = 1 << 13,
+    VEHICLE_ENTRY_FLAG_OVERRIDE_NUM_VERTICAL_FRAMES = 1 << 12,  // Setting this will cause the game to set vehicleEntry->num_vertical_frames to vehicleEntry->num_vertical_frames_override, rather than determining it itself.
+    VEHICLE_ENTRY_FLAG_HAS_SEAT_ROTATION = 1 << 13,             // Used on vehicles that use a seat rotation, i.e. the Flying and Multi-dimension RCs.
```
Comment (Gymnasiast) [inline src/openrct2/ride/vehicle.h]: Are you sure about this? Have you checked? I especially have a bit of doubt about the Flying RC - it could very well be true, though.

**Comment by oli414** [comment]
Yeah nevermind. There was definitely some errors in my thinking since the Flying RC does not have this issue. Should've just gone to bed. 

The bug has been here since #6058. This incorrect statement:
`vehicleEntry->flags_b & VEHICLE_ENTRY_FLAG_A_7`
Was (understandably) changed to:
`vehicleEntry->flags & VEHICLE_ENTRY_FLAG_7`
While the vehicle entry flag should've been `VEHICLE_ENTRY_FLAG_23`.

File: src/openrct2/ride/vehicle.h [hunk 2]
```diff
@@ -243,7 +243,7 @@ enum {
     VEHICLE_ENTRY_FLAG_RIDERS_SCREAM = 1 << 20,
     VEHICLE_ENTRY_FLAG_21 = 1 << 21,
     VEHICLE_ENTRY_FLAG_22 = 1 << 22,
-    VEHICLE_ENTRY_FLAG_23 = 1 << 23,
+    VEHICLE_ENTRY_FLAG_23 = 1 << 23,// oli414
```
Comment (Gymnasiast) [inline src/openrct2/ride/vehicle.h]: ?

**Comment by oli414** [comment]
Further tests show that this flag is used for rides with animated vehicles.
The following rides use this flag but haven't been working properly either:
- Multi-dimension coaster (Seat)
- Tri-cycle water ride (Wheels)
- Mini railroad (Side rod)
- Huskie ride (From expansions) (Huskies)
- Helicopter ride (Rotor)
But the flag is also used for some flat rides:
- Any observation tower
- Any dodgems ride
So I'm not sure what to call the flag yet as it seems to have multiple purposes.

File: src/openrct2/ride/vehicle.h (hunk 2 above)
Comment (oli414) [reply src/openrct2/ride/vehicle.h]: Whoops that's one of my debug markers that I forgot to remove.

**Comment by Gymnasiast** [comment]
Ha, it seems I wasn't the only one who suspected this being related to the locomotives and helicycles issue that spacek was talking about! I missed your comment but found it out independently.

File: src/openrct2/ride/vehicle.h (hunk 2 above)
Comment (oli414) [reply src/openrct2/ride/vehicle.h]: I really have to better check my changes before I push. I'm still trying to find my workflow, sorry about that.

**Comment by oli414** [comment]
Thanks! That's all the related issues I was able to find.

**Comment by Gymnasiast** [comment]
Good, thanks! Can you make sure, though, next time you only update a changelog or so, to put `[ci skip]` into the description field? That avoids unnecessarily firing off AppVeyor and Travis.

**Comment by oli414** [comment]
Sure, wasn't aware of that.

File: distribution/changelog.txt [hunk 3]
```diff
@@ -1,4 +1,4 @@
-0.1.2 (in development)
+﻿0.1.2 (in development)
```
Comment (Gymnasiast) [inline distribution/changelog.txt]: Please remove the BOM here (shouldn't be in UTF-8, but MS insists on it).
