### PR TITLE
Fix debug dirty visuals scaling on high DPI displays

### LINKED ISSUE #21768: Dirty blocks rendering on macOS with high DPI screens is rendered incorrectly
### Operating System

macOS

### OpenRCT2 build

v0.4.10

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

On macOS with high DPI screen ("retina") dirty blocks are rendered at incorrect scale.

image

The code that should likely get modified is https://github.com/OpenRCT2/OpenRCT2/blob/4e7d5d987a4e3e7eeb434ba66c8d16a8d61ee9ca/src/openrct2-ui/drawing/engines/HardwareDisplayDrawingEngine.cpp#L344-L370 and it should also take into account internal scaling of the window/renderer. Maybe https://wiki.libsdl.org/SDL2/SDL_RenderGetScale or checking the surface dimensions vs window dimensions?

### Steps to reproduce

Have high DPI screen on macOS
Enable debug mode
Enable dirty visuals rendering

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZzzhHe**
Fix #21768 

Get viewport dimensions with `SDL_GetRendererOutputSize()`, then calculate scaling ratios using it.

### CODE REVIEW

**Comment by ZzzhHe** [comment]
I've tested this on macOS and noticed slight misalignment. I'm going to test it on Windows tomorrow. 
Screenshot 2025-01-24 at 19 01 04

File: src/openrct2-ui/drawing/engines/HardwareDisplayDrawingEngine.cpp [hunk 1]
```diff
@@ -365,8 +365,10 @@ class HardwareDisplayDrawingEngine final : public X8DrawingEngine
 
     void RenderDirtyVisuals()
     {
-        float scaleX = Config::Get().general.WindowScale;
-        float scaleY = Config::Get().general.WindowScale;
+        int viewX, viewY;
+        SDL_GetRendererOutputSize(_sdlRenderer, &viewX, &viewY);
+        float ratioX = static_cast<float>(viewX) / static_cast<float>(_dirtyGrid.BlockColumns * _dirtyGrid.BlockWidth);
+        float ratioY = static_cast<float>(viewY) / static_cast<float>(_dirtyGrid.BlockRows * _dirtyGrid.BlockHeight);
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/drawing/engines/HardwareDisplayDrawingEngine.cpp:371]: Do you get the desired outcome if you explicitly use std::round/floor/ceil?

Comment (ZzzhHe) [reply src/openrct2-ui/drawing/engines/HardwareDisplayDrawingEngine.cpp:371]: Using std::round, std::floor, or std::ceil causes the dirty block to become more misaligned (for example, the frame rate block), as shown in the screenshot below:
Screenshot 2025-01-25 at 10 34 35

After testing various approaches, I found that the current implementation provides results most similar to the original behavior. Here’s a comparison

|  Current  |  Original  |
| -------- | ------- |
| New Commit  | Original |

Comment (AaronVanGeffen) [reply src/openrct2-ui/drawing/engines/HardwareDisplayDrawingEngine.cpp:371]: Ahh, I think the rounding needs to take place where currently an int32 cast is used, i.e. lines 383–386. The ratio variables themselves should not be rounded.

Comment (ZzzhHe) [reply src/openrct2-ui/drawing/engines/HardwareDisplayDrawingEngine.cpp:371]: Ahh, I see. Let me try!

Comment (ZzzhHe) [reply src/openrct2-ui/drawing/engines/HardwareDisplayDrawingEngine.cpp:371]: It looks better, but there’s still some slight misalignment. Additionally, I noticed it doesn’t display well on non-Retina screens. I’ll try another solution to address this.

**Comment by ZzzhHe** [comment]
It calculates display scale ratio using window and renderer dimensions now. It looks better on both high DPI screen and others. 

|  High DPI Screen  |  Others  |
| -------- | ------- |
| New Commit  |  Original |

**Review by AaronVanGeffen — APPROVED** [review]
