### PR TITLE
Fix #8377: Change number of autosaves that are stored

### LINKED ISSUE #8377: Feature: Change number of autosaves that are stored
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** dc7d141

On my server, I currently have my autosave frequency set to 5 minutes, so people don't lose much work if the game crashes for some reason. If something happens when I'm not there (like someone destroying stuff) and we only find out after several hours, we're kind of screwed because the autosaves will have been overwritten. It would be nice if we could set the number of autosaves that are stored locally instead of just the frequency.

### PR DESCRIPTION
**Pull request by ltoenning**
Fixes #8377 

This adds a spinning widget in the advanced options tab to adjust the amount of autosaves to keep.

I'm not sure if the added strings are already completly implemented because within my build is displays undefined string. But this is perhaps only a build error.

### CODE REVIEW

File: src/openrct2/Game.cpp [hunk 1]
```diff
@@ -1341,7 +1339,8 @@ void game_autosave()
         timeName, sizeof(timeName), "autosave_%04u-%02u-%02u_%02u-%02u-%02u%s", currentDate.year, currentDate.month,
         currentDate.day, currentTime.hour, currentTime.minute, currentTime.second, fileExtension);
 
-    limit_autosave_count(NUMBER_OF_AUTOSAVES_TO_KEEP, (gScreenFlags & SCREEN_FLAGS_EDITOR));
+    int32_t autosave_amount = gConfigGeneral.autosave_amount;
+    limit_autosave_count(autosave_amount-1, (gScreenFlags & SCREEN_FLAGS_EDITOR));
```
Comment (janisozaur) [inline src/openrct2/Game.cpp]: Why `autosave_amount - 1`?

**Comment by janisozaur** [comment]
I think there was discussion at some point whether to add this as an option or not and we settled on not doing so. Now this was before #8377 was filed as a request and I would say it's fine for this to be merged, although I don't see a point in having this exposed as an option in the UI. But then again you already went through the trouble of dealing with our horrendous UI code…

It's +1 from me once you fix CI, address my comment and add changelog entry, but will need another sign-off.

File: src/openrct2/localisation/StringIds.h [hunk 2]
```diff
@@ -3893,6 +3893,8 @@ enum
 
     STR_CANT_SET_COLOUR_SCHEME = 6274,
 
+    STR_AUTOSAVE_AMOUNT = 6275,
+    STR_AUTOSAVE_AMOUNT_TIP = 6276,
```
Comment (Broxzier) [inline src/openrct2/localisation/StringIds.h]: Please add a new line after this

File: src/openrct2/config/Config.cpp [hunk 3]
```diff
@@ -137,6 +137,7 @@ namespace Config
             auto model = &gConfigGeneral;
             model->always_show_gridlines = reader->GetBoolean("always_show_gridlines", false);
             model->autosave_frequency = reader->GetInt32("autosave", AUTOSAVE_EVERY_5MINUTES);
+            model->autosave_amount = reader->GetInt32("autosave_amount", 8);
```
Comment (Broxzier) [inline src/openrct2/config/Config.cpp]: Where does this `8` come from? The current autosave limit is 10.

File: src/openrct2/Game.cpp (hunk 1 above)
Comment (Broxzier) [reply src/openrct2/Game.cpp]: The old code was not correct, this function makes sure there are X autosaves and removes older ones. The value of `NUMBER_OF_AUTOSAVES_TO_KEEP` was 9, but it kept 10 saves, because later in this function a new one will be made. I think this code is nicer.

I'd still request this variable to be renamed to something like `autosavesToKeep`. (And add spaces around the `-`).

Comment (ltoenning) [reply src/openrct2/Game.cpp]: I haven't looked into the limit_autosave_count() but I tested it and autosave_amount +1 autosaves were saved without subtracting 1.

File: src/openrct2-ui/windows/Options.cpp [hunk 4]
```diff
@@ -359,9 +362,10 @@ static rct_widget window_options_advanced_widgets[] = {
...
     { WWT_DROPDOWN,         1,  165,    299,    145,    157,    STR_NONE,                                   STR_NONE },                                         // Autosave dropdown
     { WWT_BUTTON,           1,  288,    298,    146,    156,    STR_DROPDOWN_GLYPH,                         STR_AUTOSAVE_FREQUENCY_TIP },                       // Autosave dropdown button
-    { WWT_LABEL,            1,  23,     298,    165,    176,    STR_PATH_TO_RCT1,                           STR_PATH_TO_RCT1_TIP },                             // RCT 1 path text
-    { WWT_BUTTON,           1,  24,     289,    180,    193,    STR_NONE,                                   STR_STRING_TOOLTIP },                               // RCT 1 path button
-    { WWT_BUTTON,           1,  289,    299,    180,    193,    STR_CLOSE_X,                                STR_PATH_TO_RCT1_CLEAR_TIP },                       // RCT 1 path clear button
+    SPINNER_WIDGETS         (1,  165,    299,    165,    180,    STR_NONE,                                   STR_AUTOSAVE_AMOUNT_TIP ),                         // Autosave amount spinner
```
Comment (Broxzier) [inline src/openrct2-ui/windows/Options.cpp]: These widgets do not appear for me. Have you made sure they fit in the window?

Minor change to improve reability (done everywhere else where `SPINNER_WIDGETS` is used:
```suggestion
    SPINNER_WIDGETS        (1,  165,    299,    165,    180,    STR_NONE,                                   STR_AUTOSAVE_AMOUNT_TIP ),                          // Autosave amount spinner
```

File: src/openrct2/config/Config.cpp (hunk 3 above)
Comment (Broxzier) [reply src/openrct2/config/Config.cpp]: Strangely enough, even though a new autosave was made, there are still 10 saved games in my autosave folder.

File: src/openrct2-ui/windows/Options.cpp (hunk 4 above)
Comment (ltoenning) [reply src/openrct2-ui/windows/Options.cpp]: Actually it seems the entry fits in my build:
unbenannt

File: data/language/en-GB.txt [hunk 5]
```diff
@@ -3722,6 +3722,8 @@ STR_6271    :Terrain Edges
 STR_6272    :Stations
 STR_6273    :Music
 STR_6274    :Can't set colour scheme...
+STR_6275    :Autosave-Amount
```
Comment (Gymnasiast) [inline data/language/en-GB.txt]:
```suggestion
STR_6275    :Autosave amount:
```

File: src/openrct2-ui/windows/Options.cpp (hunk 4 above)
Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/Options.cpp]: In the screenshot above, the field is a little too high, and the line spacing is off. Have a look at other spinners to see what (line) height they use.

Also, the decimals should be hidden, as the setting is an integer.

Comment (ltoenning) [reply src/openrct2-ui/windows/Options.cpp]: > In the screenshot above, the field is a little too high, and the line spacing is off. Have a look at other spinners to see what (line) height they use.
> 
> Also, the decimals should be hidden, as the setting is an integer.

Fixed after removing the decimals.

**Comment by ltoenning** [comment]
Anything further that should be changed?

**Comment by janisozaur** [comment]
Hey @Broxzier mind taking it for a spin again?

File: src/openrct2-ui/windows/Options.cpp [hunk 6]
```diff
@@ -1318,6 +1325,22 @@ static void window_options_mousedown(rct_window* w, rct_widgetindex widgetIndex,
                     window_options_show_dropdown(w, widget, AUTOSAVE_NEVER + 1);
                     dropdown_set_checked(gConfigGeneral.autosave_frequency, true);
                     break;
+                case WIDX_AUTOSAVE_AMOUNT_UP:
+                    gConfigGeneral.autosave_amount += 1;
+                    config_save_default();
+                    gfx_invalidate_screen();
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Options.cpp]: You can remove all the stuff between `config_save_default()` and `break`. Same applies for the other button.

File: src/openrct2/Game.cpp [hunk 7]
```diff
@@ -1384,7 +1384,8 @@ void game_autosave()
         timeName, sizeof(timeName), "autosave_%04u-%02u-%02u_%02u-%02u-%02u%s", currentDate.year, currentDate.month,
         currentDate.day, currentTime.hour, currentTime.minute, currentTime.second, fileExtension);
 
-    limit_autosave_count(NUMBER_OF_AUTOSAVES_TO_KEEP, (gScreenFlags & SCREEN_FLAGS_EDITOR));
+    int32_t autosavesToKeep = gConfigGeneral.autosave_amount;
+    limit_autosave_count(autosavesToKeep - 1, (gScreenFlags & SCREEN_FLAGS_EDITOR));
```
Comment (Gymnasiast) [inline src/openrct2/Game.cpp]: Since this code makes it unnecessary, you should remove `NUMBER_OF_AUTOSAVES_TO_KEEP`.

File: data/language/en-GB.txt [hunk 8]
```diff
@@ -3725,6 +3725,8 @@ STR_6274    :Can't set colour scheme...
 STR_6275    :{WINDOW_COLOUR_2}Station style:
 STR_6276    :{RED}{STRINGID} has guests getting stuck, possibly due to invalid ride type or operating mode.
 STR_6277    :{WINDOW_COLOUR_2}Station index: {BLACK}{COMMA16}
+STR_6278    :Autosave amount
+STR_6279    :Amount of how many autosaves should be kept
```
Comment (Gymnasiast) [inline data/language/en-GB.txt]:
```suggestion
STR_6279    :{SMALLFONT}{BLACK}Number of autosaves that should be kept
```

File: src/openrct2-ui/windows/Options.cpp (hunk 6 above)
Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/Options.cpp]: Should probably invalidate the widget though, so the current value is displayed properly.

File: src/openrct2-ui/windows/Options.cpp [hunk 9]
```diff
@@ -1318,6 +1325,18 @@ static void window_options_mousedown(rct_window* w, rct_widgetindex widgetIndex,
...
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Options.cpp]: Sorry for being nitpicky, but it's still not necessary to invalidate the whole screen -- `widget_invalidate()` is enough.
```suggestion
                    widget_invalidate(WIDX_AUTOSAVE);
                    widget_invalidate(WIDX_AUTOSAVE_DROPDOWN);
                    widget_invalidate(WIDX_AUTOSAVE_AMOUNT);
```

File: src/openrct2-ui/windows/Options.cpp [hunk 10]
```diff
@@ -1318,6 +1325,18 @@ static void window_options_mousedown(rct_window* w, rct_widgetindex widgetIndex,
...
+                    break;
+                case WIDX_AUTOSAVE_AMOUNT_DOWN:
+                    if (gConfigGeneral.autosave_amount > 1)
+                    {
+                        gConfigGeneral.autosave_amount -= 1;
+                        config_save_default();
+                        gfx_invalidate_screen();
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Options.cpp]:
```suggestion
                    widget_invalidate(WIDX_AUTOSAVE);
                    widget_invalidate(WIDX_AUTOSAVE_DROPDOWN);
                    widget_invalidate(WIDX_AUTOSAVE_AMOUNT);
```

**Comment by Gymnasiast** [comment]
Sorry for giving such scattered feedback and directions, but we're nearly there.

File: src/openrct2/config/Config.cpp [hunk 11]
```diff
@@ -137,6 +137,7 @@ namespace Config
             auto model = &gConfigGeneral;
             model->always_show_gridlines = reader->GetBoolean("always_show_gridlines", false);
             model->autosave_frequency = reader->GetInt32("autosave", AUTOSAVE_EVERY_5MINUTES);
+            model->autosave_amount = reader->GetInt32("autosave_amount", 10);
```
Comment (Broxzier) [inline src/openrct2/config/Config.cpp]: Could you replace `10` with a define like `DEFAULT_NUM_AUTOSAVES_TO_KEEP`?
