### PR TITLE
Remove format string in server name from Discord rich presence

### LINKED ISSUE #18109: Server name in Discord rich presence include format string, makes server name super long
### Operating System

Windows 11 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-350-gcf6de24 (cf6de24 on develop) provided by GitHub

### Describe the issue

This is not a bug, but an enhancement.

When you join server which use format string to spice up their server name, the discord rich presence will include those string like raw data make the server name too long to discord to display, even though server name might be short.

image
image

I think I can fix this by filter out all {}. Is this method ok?

### Area(s) with issue?

_No response_

### Steps to reproduce

1. join server with formatted server name like Deurklink's server
2. Look at rich presence on discord
3. On the last line it will show the server name with {.....}

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by beam41**
As I said in [this comment](https://github.com/OpenRCT2/OpenRCT2/issues/18109#issuecomment-1261769987) `FmtString::WithoutFormatTokens` removes `{}` from escape string and I don't want to modify it. So I add directly to `DiscordService`. But tell me if you want me to modify `FmtString::WithoutFormatTokens` instead.

Fix #18109

### CODE REVIEW

File: src/openrct2/network/DiscordService.cpp [hunk 1]
```diff
@@ -7,6 +7,7 @@
  * OpenRCT2 is licensed under the GNU General Public License version 3.
  *****************************************************************************/
 
+#include "openrct2/localisation/Formatting.h"
```
Comment (Gymnasiast) [inline src/openrct2/network/DiscordService.cpp:10]: This needs to read `#include "../localisation/Formatting.h"` and should be put around line 19, in alphabetical order.

**Review by IntelOrca — APPROVED** [review]

**Comment by Gymnasiast** [comment]
@beam41 Did you test this?

**Comment by beam41** [comment]
I did, this is my test string 
```
{YELLOW}Test {{ESCAPE}}{INVALID_TOKEN}{INLINE_SPRITE}{254}{19}{00}{00}{INLINE_SPRITE}{999}{99}{99}{99}     string
```

This is the result.
image
image
