### PR TITLE
Fix #7689: Deleting 0-tile maze gives a MONEY32_UNDEFINED (negative) refund.

### LINKED ISSUE #7689: Deleting a 0-tile maze gives an overflow error that will take all your money away
**OS:** [Windows 8]
**Version:** [e.g. 0.2.0]
**Commit/Build:** [e39f89c]

octagon park 2018-06-14 20-51-49

**Steps to reproduce:**
1. Build a 1-tile maze.
2. Fill in all the pathways on the maze (the one tile will disappear).
3. Close the construction window (the ride window will open, centered on the bottom corner of the map).
4. Demolish the (nonexistant) ride (the confirmation window will appear, as in the screenshot, and instead of granting you money, it threatens to remove a ludicrous amount).

- [ ? ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

### PR DESCRIPTION
**Pull request by felixpelletier**
#7689 
When deleting, a function is called to get the origin of a ride in order to delete it track by track.
If the ride has no tracks a STR_TRACK_TOO_LARGE_OR_TOO_MUCH_SCENERY error was declared and MONEY32_UNDEFINED was returned.

Looking at the code for ride_try_get_origin_element() it can be found that this error can't really happen, and the only reason it could return false is that the ride has no tracks. Therefore, the refund should be 0.

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -5989,8 +5989,7 @@ int32_t ride_get_refund_price(int32_t ride_id)
 
     if (!ride_try_get_origin_element(ride_id, &trackElement))
     {
-        gGameCommandErrorText = STR_TRACK_TOO_LARGE_OR_TOO_MUCH_SCENERY;
-        return MONEY32_UNDEFINED;
+        return 0; // Ride has no track to refund
```
Comment (duncanspumpkin) [inline src/openrct2/ride/Ride.cpp]: A log error or log verbose would have been useful to put in here.
