### PR TITLE
prevent crash with hacked spiral slides

### LINKED ISSUE #5546: Opening park crashes the game
Windows 8.1
Version 0.0.8 36ca5b3

I can't open this park. Well, I can open it, but it gives me an error trapper immediately. https://www.nedesigns.com/park/3436/electric-fields-amusement-park/

### PR DESCRIPTION
**Pull request by Chaosmeister**
fix #5546

### CODE REVIEW

File: src/openrct2/ride/ride.c [hunk 1]
```diff
@@ -2202,6 +2202,9 @@ static void ride_spiral_slide_update(rct_ride *ride)
         sint32 y = ride->station_starts[i] >> 8;
 
         rct_map_element *mapElement = ride_get_station_start_track_element(ride, i);
+        if (mapElement == NULL)
+            return;
```
Comment (IntelOrca) [inline src/openrct2/ride/ride.c]: `continue` might be right.

Comment (Gymnasiast) [inline src/openrct2/ride/ride.c]: I think that would be better, yes.
