### PR TITLE
Fix #7324: Research window shows vehicle name instead of ride name

### LINKED ISSUE #7324: Research window now shows the name of trains/cars for each ride, instead of the name of the ride itself.
**OS:** Windows 8
**Version:** e.g. 0.1.3
**Commit/Build:** ccb1b33

Research window now shows the name of trains/cars for each ride, instead of the name of the ride itself.

This happens not only for roller coasters, but even for flat rides that have vehicles, like the reverse freefall.

Shops/stalls, scenery, and rides without vehicles (like mazes or mini-golf) still appear in the research as normal.

amity airfield 2018-03-20 12-58-13

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open research window.
2. Research any ride that has vehicles.

### PR DESCRIPTION
**Pull request by Gymnasiast**
This iterates over the research list upon loading a save and determines whether a vehicle is the first to be invented for its type. If so, it sets a flag.

Six Flags Great Adventure 2020-06-17 16-50-02

### CODE REVIEW

File: src/openrct2-ui/windows/Research.cpp [hunk 1]
```diff
@@ -362,16 +363,33 @@ void window_research_development_page_paint(rct_window* w, rct_drawpixelinfo* dp
     else
     {
         // Research type
-        stringId = STR_RESEARCH_UNKNOWN;
+        rct_string_id strings[2] = { STR_RESEARCH_UNKNOWN, 0 };
```
Comment (tupaschoal) [inline src/openrct2-ui/windows/Research.cpp:366]:
```suggestion
        std::array<rct_string_id, 2> strings = { STR_RESEARCH_UNKNOWN, 0 };
```
If it works, prefer the `std::array`

File: src/openrct2-ui/windows/Research.cpp [hunk 2]
```diff
@@ -402,11 +420,31 @@ void window_research_development_page_paint(rct_window* w, rct_drawpixelinfo* dp
     rct_string_id lastDevelopmentFormat;
```
Comment (tupaschoal) [inline src/openrct2-ui/windows/Research.cpp:420]: Move this to be inside the if, so we reduce its scope, as it's not needed anymore later. Also either initialize it to `STR_RESEARCH_SCENERY_LABEL` and change if `type != RESEARCH_ENTRY_TYPE_SCENERY` or to something invalid, so we know in case we break this someday.

File: src/openrct2/management/Research.cpp [hunk 3]
```diff
@@ -910,3 +890,107 @@ bool ResearchItem::Exists() const
...
+static std::bitset<RIDE_TYPE_COUNT> _seenRideType = {};
+static std::bitset<RIDE_TYPE_COUNT* MAX_RIDE_GROUPS_PER_RIDE_TYPE> _seenRideGroup = {};
+
+static void research_update_first_of_type(ResearchItem* researchItem)
+{
+    if (researchItem->IsNull())
+        return;
+
+    if (researchItem->type != RESEARCH_ENTRY_TYPE_RIDE)
+        return;
```
Comment (tupaschoal) [inline src/openrct2/management/Research.cpp:903]: I'd merge these ifs with an `||`, but that's your call

File: src/openrct2/management/Research.cpp [hunk 4]
```diff
@@ -910,3 +890,107 @@ bool ResearchItem::Exists() const
...
+
+    auto rideType = researchItem->baseRideType;
+    if (rideType >= RIDE_TYPE_COUNT)
```
Comment (tupaschoal) [inline src/openrct2/management/Research.cpp:906]: Should we log an error if this happens?

File: src/openrct2/management/Research.cpp [hunk 5]
```diff
@@ -910,3 +890,107 @@ bool ResearchItem::Exists() const
...
+        }
+    }
+}
+
+void research_determine_first_of_type()
+{
+    _seenRideType.reset();
+    _seenRideGroup.reset();
+
+    for (auto& researchItem : gResearchItemsInvented)
```
Comment (tupaschoal) [inline src/openrct2/management/Research.cpp:944]:
```suggestion
    for (const auto& researchItem : gResearchItemsInvented)
```

File: src/openrct2/management/Research.cpp [hunk 6]
```diff
@@ -910,3 +890,107 @@ bool ResearchItem::Exists() const
...
+        auto tmpVal = gResearchLastItem.value();
+        research_update_first_of_type(&tmpVal);
+        gResearchLastItem = tmpVal;
+    }
+    if (gResearchNextItem.has_value())
+    {
+        auto tmpVal = gResearchNextItem.value();
+        research_update_first_of_type(&tmpVal);
+        gResearchNextItem = tmpVal;
+    }
```
Comment (tupaschoal) [inline src/openrct2/management/Research.cpp:990]: Seems like you should extract a function and call `foo(gResearchLastItem)` and `foo(gResearchNextItem)`

File: src/openrct2/management/Research.cpp [hunk 7]
```diff
@@ -910,3 +890,107 @@ bool ResearchItem::Exists() const
...
+
+    for (auto& researchItem : gResearchItemsUninvented)
```
Comment (tupaschoal) [inline src/openrct2/management/Research.cpp:992]:
```suggestion
    for (const auto& researchItem : gResearchItemsUninvented)
```

File: src/openrct2/management/Research.cpp [hunk 8]
```diff
@@ -910,3 +890,107 @@ bool ResearchItem::Exists() const
     }
     return false;
 }
+
+static std::bitset<RIDE_TYPE_COUNT> _seenRideType = {};
+static std::bitset<RIDE_TYPE_COUNT* MAX_RIDE_GROUPS_PER_RIDE_TYPE> _seenRideGroup = {};
+
+static void research_update_first_of_type(ResearchItem* researchItem)
```
Comment (tupaschoal) [inline src/openrct2/management/Research.cpp:897]: Is there a thing such as a `Research` class? Just trying to understand the reason for the free function in here,

Comment (Gymnasiast) [reply src/openrct2/management/Research.cpp:897]: There is no Research class, no. (Most files are still a collection of C-style functions.)

File: src/openrct2/management/Research.cpp (hunk 7 above)
Comment (Gymnasiast) [reply src/openrct2/management/Research.cpp:992]: No. It has to update the `researchItem`s.

File: src/openrct2-ui/windows/Research.cpp [hunk 9]
```diff
@@ -362,16 +363,33 @@ void window_research_development_page_paint(rct_window* w, rct_drawpixelinfo* dp
     else
     {
         // Research type
-        stringId = STR_RESEARCH_UNKNOWN;
+        std::array<rct_string_id, 2> strings = { STR_RESEARCH_UNKNOWN, 0 };
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Research.cpp:366]: Shouldn't we be using the Formatter here instead of a std::array?

Comment (Gymnasiast) [reply src/openrct2-ui/windows/Research.cpp:366]: `strings` acts as a buffer here, not as a formatter.

The formatter would still have to format to _a_ buffer - either this one or gCommonFormatArgs. But I really don't want to introduce any more instances of the latter.
