### PR TITLE
Fix #23636: Mismatched entity count in save file

### LINKED ISSUE #23636: Very rare parkfile misreporting number of entity save-breaking glitch
### Operating System

Windows 10/11

### OpenRCT2 build

Latest, but has been for a while

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

I've seen several occasions where a parkfile has mysteriously become corrupt. It has never happened to me personally.
The parkfile would not open anymore, and recent autosaves would likewise not open either, all having become corrupt.
I know of 3 occasions of this happening.
For two of the occasions, I thoroughly examined the parkfiles, and found the problem, fixing it for the respective owners. The third one the files had already been deleted before I heard of it, but the description of the problem still fits.

On both parks I examined, (in breakpoint mode in visual studio), there was a mismatch in enitity count, and actual entities. 
On the first park the amount of litter was reported as 7, while in reality being 6. The parkfile would attempt to read a 7th litter piece, reading stuff from the adjacent entities, and that would eventually lead to a failure. 
In the 2nd park the number of peeps was off by 1. 

_something_ is causing this. I've seen it too often in a too similar way to attribute it to random bitflips. 
Maybe there's a race condition during saving, that the number is saved, then a piece of litter is swept up, or a guest despawned, while the list is still being saved? I am not sure, but I felt it necessary to report. 

In the attachments are the 4 files I have, broken, and fixed. 

[corruptedsaves.zip](https://github.com/user-attachments/files/18460257/corruptedsaves.zip)

### Steps to reproduce

Load the parks, see that the parks with  BROKEN in the name don't load, while the ones with FIXED, do.
Then use visual studio's breakpoints, put a breakpoint in ReadEntitiesOfType in ParkFile.cpp, on line 2560 (the start of the for loop)
In case of the litter park, continue until entitype is litter, and then manually set count 1 lower. (From 7, to 6)
In case of peeps park, continue until enitytype is guest, and manually set count 1 lower. (from 3848 to 3847)
After that, let it continue load the park, and observe it being the fixed park.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
This is based on #24552, with two changes:
1. The entity list is copied and used for both the count and the actual writes
2. It no longer asserts if the count mismatches (which is why #24552 was not merged).

### CODE REVIEW

File: src/openrct2/park/ParkFile.cpp [hunk 1]
```diff
@@ -2639,10 +2639,19 @@ namespace OpenRCT2
...
+        const auto entityList = EntityList<T>();
+        // We do not rely on GetEntityListCount as there is a potential issue (#23636) that needs investigating.
+        const auto count = [&]() -> uint16_t {
+            uint16_t res = 0;
+            for ([[maybe_unused]] auto* _ : entityList)
+            {
+                res++;
+            }
+            return res;
+        }();
```
Comment (AaronVanGeffen) [inline src/openrct2/park/ParkFile.cpp:2651]: This seems like a good candidate for [`std:count`](https://en.cppreference.com/w/cpp/algorithm/count.html#eq-fun-cpp-table).

Comment (Gymnasiast) [reply src/openrct2/park/ParkFile.cpp:2651]: It doesn’t seem that way, `std::count` counts the number of items that have a certain value, it does not count the whole set.

Comment (AaronVanGeffen) [reply src/openrct2/park/ParkFile.cpp:2651]: I think you might be looking at `std::count_if` not `std::count`? They share the same page, but the latter doesn't take a predicate.

Comment (Gymnasiast) [reply src/openrct2/park/ParkFile.cpp:2651]: `count_if` takes a predicate, `count` takes a simple value to compare with.

All signatures of `std::count` take a `const T& value` which is explained as follows under Parameters:
`value 	- 	the value to search for`

Comment (AaronVanGeffen) [reply src/openrct2/park/ParkFile.cpp:2651]: You're right; I'm misremembering. And the `EntityTileIterator` implicitly skips over null entries, so that's why this trickery is needed.

This does makes me think we should add a `size()` method to `EntityList` that does the calculation, rather than calculating it locally, tbh. Then you _could_ use `std::count`, given `EntityList` has access to its private `std::list<EntityId>`. What do you think?

**Comment by deurklink** [comment]
I have been running this build for almost 2 weeks now on my server without any issues. I can load saves that I made on the server with this build on different computers. There don't appear to be any issues.

File: src/openrct2/park/ParkFile.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/park/ParkFile.cpp:2651]: I don't understand either of those well enough to tell. It’s something better left for another PR IMO. I’d like to get this (well-tested) fix in for the upcoming release.

**Review by AaronVanGeffen — APPROVED** [review]

File: src/openrct2/park/ParkFile.cpp (hunk 1 above)
Comment (AaronVanGeffen) [reply src/openrct2/park/ParkFile.cpp:2651]: Sure, I can see the need for this fix. It is worth revisiting at some point in the near future, though.
