### PR TITLE
Fix #11624 and clean up loc_6B4F6B()

### LINKED ISSUE #11624: [cc0766] openrct2.exe: ride_check_track_contains_inversions, ride_is_valid_for_test, RideSetStatusAction::Execute, GameAction...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/cc0766f3f6bdf4d7d6ab24beaf31b5f36a95c11e47aeacc64a82bada13021b47">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
ride_check_track_contains_inversions
ride_is_valid_for_test
RideSetStatusAction::Execute
GameActions::ExecuteInternal
Ride::Update
Ride::UpdateAll
OpenRCT2::GameState::UpdateLogic
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -3918,7 +3918,14 @@ static int32_t ride_check_block_brakes(CoordsXYE* input, CoordsXYE* output)
  */
 static bool ride_check_track_contains_inversions(CoordsXYE* input, CoordsXYE* output)
 {
-    ride_id_t rideIndex = input->element->AsTrack()->GetRideIndex();
+    if (input->element == nullptr)
+        return false;
+
+    const auto& trackElement = input->element->AsTrack();
+    if (trackElement == nullptr)
```
Comment (AaronVanGeffen) [inline src/openrct2/ride/Ride.cpp:3925]: This can't be a `nullptr`, consistering the `input->element == nullptr` above, right?

File: src/openrct2/ride/Ride.cpp [hunk 2]
```diff
@@ -3966,7 +3973,14 @@ static bool ride_check_track_contains_inversions(CoordsXYE* input, CoordsXYE* ou
  */
 static bool ride_check_track_contains_banked(CoordsXYE* input, CoordsXYE* output)
 {
-    auto rideIndex = input->element->AsTrack()->GetRideIndex();
+    if (input->element == nullptr)
+        return false;
+
+    const auto& trackElement = input->element->AsTrack();
+    if (trackElement == nullptr)
```
Comment (AaronVanGeffen) [inline src/openrct2/ride/Ride.cpp:3980]: Same as above.

File: src/openrct2/ride/Ride.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/ride/Ride.cpp:3925]: It can most definitely be a nullptr. AsTrack() will return nullptr if the element is not a track, but another tile element type.

File: src/openrct2/ride/Ride.cpp [hunk 3]
```diff
@@ -3918,7 +3918,14 @@ static int32_t ride_check_block_brakes(CoordsXYE* input, CoordsXYE* output)
  */
 static bool ride_check_track_contains_inversions(CoordsXYE* input, CoordsXYE* output)
 {
-    ride_id_t rideIndex = input->element->AsTrack()->GetRideIndex();
+    if (input->element == nullptr)
+        return false;
+
+    const auto& trackElement = input->element->AsTrack();
```
Comment (ZehMatt) [inline src/openrct2/ride/Ride.cpp:3924]:
```suggestion
    const auto* trackElement = input->element->AsTrack();
```
One could think it results a reference actually.
