### PR TITLE
Fix #23238: Guest ride favourite mistake

### LINKED ISSUE #23238: Guests determine their favourite ride wrongly
### Operating System

Windows 11

### OpenRCT2 build

0.0.3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The way that the favourite ride of guests gets calculated was changed. I haven't done super involved testing, but right now in OpenRCT2 when a guest has max happiness, their favourite ride will always be the last one they've ridden. In the original games this is not the case. My test still works the same as vanilla in v0.0.2 and it's different in v0.0.3

### Steps to reproduce

1. Open the attached save file (it works in vanilla and all OpenRCT2 versions)
2. Have a guest first ride the wooden coaster and then the lift.
3. Check which ride of the two is their favourite.
4. In vanilla and 0.0.2 it will be the wooden coaster, and in 0.0.3 and later it will be the lift as that's the one they rode last.

[Favourite ride test.zip](https://github.com/user-attachments/files/17832916/Favourite.ride.test.zip)

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fix #23238  Guest ride favourite mistake

Mistake made during implementation

### CODE REVIEW

**Review by LordMarcel — COMMENTED** [review]
Based on my limited tests it seems to behave the same as in vanilla now

File: src/openrct2/entity/Guest.cpp [hunk 1]
```diff
@@ -440,7 +440,7 @@ static void PeepRideIsTooIntense(Guest* peep, Ride& ride, bool peepAtRide);
 static void PeepResetRideHeading(Guest* peep);
 static void PeepTriedToEnterFullQueue(Guest* peep, Ride& ride);
 static int16_t PeepCalculateRideSatisfaction(Guest* peep, const Ride& ride);
-static void PeepUpdateFavouriteRide(Guest* peep, const Ride& ride);
+static void PeepUpdateFavouriteRide(Guest& peep, const Ride& ride, const uint8_t satisfaction);
```
Comment (Gymnasiast) [inline src/openrct2/entity/Guest.cpp:443]: It’s optional, but since we’re modifying the function anyway, I think it’s a good idea to rename it to `GuestUpdateFavouriteRide`.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
This needs a changelog entry.

Optionally, I’d like the function to be renamed. See the line note.

Looks good otherwise.

**Review by Gymnasiast — APPROVED** [review]
