### PR TITLE
Fix #17664: Ride music channel data leaks when stopping inactive music

### LINKED ISSUE #17664: Can't save parks/tracks or write anything to disk
### Operating System

Windows 10 64 bit

### OpenRCT2 build

889293f

### Describe the issue

At some point after playing for a few hours, a certain bug occured that prevented all writing to disk. I discovered that the bug had happened when trying to save the park and it said "save game failed".

The last autosave was made at 22:42:59, so the bug happened between that point and 5 minutes after it. This time period starts at roughly 2 hours and 46 minutes into the stream: https://www.twitch.tv/videos/1548387157

### Area(s) with issue?

_No response_

### Steps to reproduce

I have no idea how to reproduce it or what triggered it.

### Attachments

The last autosave:
[autosave_2022-07-31_22-42-59.zip](https://github.com/OpenRCT2/OpenRCT2/files/9229764/autosave_2022-07-31_22-42-59.zip)

### PR DESCRIPTION
**Pull request by CookiePLMonster**
Fixes a resource leak in `RideMusicChannel`'s move operator that caused the music source data to stick around. This kept the music file handles open while opening new handles the next time a new channel was created. The limit of open handles is still relatively low, at least on Windows (512), and so moving the camera enough times to start and stop enough ride music sources would eventually lead to the handles pool running out, leading to effects such as:
* Music not playing (can't open files for read)
* **Inability to save** (can't open files for write)

To make the move operator truly `noexcept`, instead of releasing sources in the function body I opted for a swap idiom, letting the moved-from object's destructor deal with it. I have verified **all** uses of `RideMusicChannel` against wrong assumptions, and they all deal with the moved-from object properly.

Fixes #17664.

### CODE REVIEW

File: src/openrct2/ride/RideAudio.cpp [hunk 1]
```diff
@@ -85,15 +87,8 @@ namespace OpenRCT2::RideAudio
...
-            {
-                Channel->Stop();
-            }
-            Channel = src.Channel;
-            src.Channel = nullptr;
-
-            Source = src.Source;
-            src.Source = nullptr;
+            swap(Channel, src.Channel);
+            swap(Source, src.Source);
```
Comment (Gymnasiast) [inline src/openrct2/ride/RideAudio.cpp:91]: For the std library, we always use the full namespace rather than "using std".

Comment (CookiePLMonster) [reply src/openrct2/ride/RideAudio.cpp:91]: That's not it. By adding `using std::swap` which is not the same as `using namespace [X];` I let Argument Dependent Lookup figure out what `swap` function to pick - if types of `Channel` or `Source` end up getting their own specializations of `swap` (right now they don't, but this may change) then this syntax will automatically make use of them; else it falls back to `std::swap`.

**Review by Gymnasiast — APPROVED** [review]

**Review by IntelOrca — APPROVED** [review]
I am not keen on the swap because it doesn't make sense for the RHS item to get the old pointer of the LHS item.

Trying to ensure it is noexcept is not that beneficial when the destructor can. However this can be left to another PR that moves the actual disposal code to the audio mixer logic and having the release call just be a simple field assignment. This could also look into moving to shared_ptr or some kind of other RAII auto release mechanism.

**Comment by CookiePLMonster** [comment]
> I am not keen on the swap because it doesn't make sense for the RHS item to get the old pointer of the LHS item.

However, the more you think about the more IMO it makes sense - the moved-from object is left in a valid but indeterminate state. Notice that before this PR, the move constructor leaves all primitive types untouched, while zeroing pointers - so although it wasn't as obvious, even right now the moved-from object is not "left empty".

As weird as it looks at first, I think in the end it makes perfect sense. IMO it's no different to an erase/remove idiom moving elements to be erased to the end of the container before pruning them.

**Comment by IntelOrca** [comment]
> As weird as it looks at first, I think in the end it makes perfect sense. IMO it's no different to an erase/remove idiom moving elements to be erased to the end of the container before pruning them.

I don't think we will ever agree on this then.

**Comment by CookiePLMonster** [comment]
Can this stay as-is for this PR though, given the fact this class has a very narrow and specialized use and essentially only ever gets destructed from `std` methods?

**Comment by janisozaur** [comment]
Wouldn't https://github.com/OpenRCT2/OpenRCT2/blob/34cb2a96f17109c089271eacd658e00be3c214f4/src/openrct2/paint/Paint.cpp#L954 and https://github.com/OpenRCT2/OpenRCT2/blob/34cb2a96f17109c089271eacd658e00be3c214f4/src/openrct2/paint/Paint.cpp#L996 be the same problem then? Just less critical resources getting leaked
