### PR TITLE
Fix #5795: Implement sprite cycle checking

### LINKED ISSUE #5795: The game freezes with maptile (0,0) on screen after an autosave
**OS:** [Windows 10]
**Version:** [0.0.8]
**Commit/Build:** [4e4022d693d4149eddea906ec71f22ddc626411f]

If the appended scenario is loaded, an autosave has occurred and maptile (0,0) is in the active viewport, the game freezes

**Steps to reproduce:**
1. load the appended scenario.
2. wait for an autosave.
3. pan the camera to the top of the map.

**Save game:**
[Sandbox.zip](https://github.com/OpenRCT2/OpenRCT2/files/1123149/Sandbox.zip)

### PR DESCRIPTION
**Pull request by rwjuk**
This PR implements a check for cycles in the sprite linked lists on import and export. On import, an attempt to fix this is made (the fix is sub-optimal, and suggestions on improvements are more than welcome). On export, an assert is generated.

Furthermore, two causes of the cycles have been fixed - in both cases it was due to the `next_in_quadrant` field being improperly reset.

I've yet to find a way to repair SV6s that are corrupted, but this will stop any more from ending up in a bugged state.

This fixes #5795 (unable to get the game to lock up on autosave with this applied).

Massive thanks to @IntelOrca & @janisozaur for the sprite cycle checking function basics, and the aforementioned along with @PFCKrutonium for helping us track this heisenbug down!

### CODE REVIEW

File: src/openrct2/world/sprite.c [hunk 1]
```diff
@@ -823,3 +826,106 @@ bool sprite_get_flashing(rct_sprite *sprite)
...
+        increment_slow = !increment_slow;
+        if (fast == slow)
+        {
+            cycled = true;
+            if (fix)
+            {
+                rct_sprite * spr = get_sprite(sprite_idx);
+
+                // There may be a better solution than simply setting this to 0xFFFF
+                spr->unknown.next_in_quadrant = SPRITE_INDEX_NULL;
```
Comment (rwjuk) [inline src/openrct2/world/sprite.c]: I did look for a better solution here, and also in `sprite_is_in_cycle()` but was unable to find something that would work (most functions rely on the sprite being 'sane'). I was tempted to adapt one (e.g. using a wrapper), but thought I'd seek input first.

File: src/openrct2/world/sprite.c [hunk 2]
```diff
@@ -267,6 +267,7 @@ void sprite_clear_all_unused()
         sprite->previous = previousSpriteIndex;
         sprite->linked_list_type_offset = SPRITE_LIST_NULL * 2;
         sprite->sprite_index = spriteIndex;
+        sprite->next_in_quadrant = (sprite->next_in_quadrant == 0) ? SPRITE_INDEX_NULL : sprite->next_in_quadrant;
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: A comment would be nice, also this is self-assignment. Please change it to this form `if (sprite->next_in_quadrant == 0) { sprite->next_in_quadrant = SPRITE_INDEX_NULL; }`

File: src/openrct2/world/sprite.c [hunk 3]
```diff
@@ -285,6 +287,7 @@ static void sprite_reset(rct_unk_sprite *sprite)
 
     sprite->linked_list_type_offset = llto;
     sprite->next = next;
+    sprite->next_in_quadrant = next_in_quadrant;
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: Can you also add `sprite->sprite_identifier = SPRITE_IDENTIFIER_NULL;` to this function and change `sprite_clear_all_unused` to use it?

File: src/openrct2/world/sprite.c [hunk 4]
```diff
@@ -823,3 +826,106 @@ bool sprite_get_flashing(rct_sprite *sprite)
...
+        if (fast == slow)
+        {
+            cycled = true;
+            if (fix)
+            {
+                rct_sprite * spr = get_sprite(sprite_idx);
+                // There may be a better solution than simply setting this to 0xFFFF
+                spr->unknown.next = SPRITE_INDEX_NULL;
+            }
+            break;
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: I don't like this. The function is called `sprite_is_in_cycle` and `bool` return value suggests the answer is "yes" or "no", but in a case where you pass in the "fix = true" argument, the return value makes no sense.

As the sprite being fixed is the one passed in (and it doesn't really matter, as there is no other fixing up), I'd rather see the caller take care of fixing it.

File: src/openrct2/world/sprite.c (hunk 1 above)
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: See my comment above.

File: src/openrct2/world/sprite.c [hunk 5]
```diff
@@ -823,3 +826,106 @@ bool sprite_get_flashing(rct_sprite *sprite)
...
+
+bool check_for_spatial_index_cycles(bool fix)
+{
+    for (size_t i = 0; i < 0x10000; i++) {
+        if (sprite_is_in_cycle_quadrant(gSpriteSpatialIndex[i], fix)) {
+            return true;
+        }
+    }
+    return false;
+}
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: missing newline

File: src/openrct2/world/sprite.c [hunk 6]
```diff
@@ -823,3 +826,106 @@ bool sprite_get_flashing(rct_sprite *sprite)
...
+                // There may be a better solution than simply setting this to 0xFFFF
+                spr->unknown.next = SPRITE_INDEX_NULL;
+            }
+            break;
+        }
+    }
+    return cycled;
+}
+
+static bool sprite_is_in_cycle_quadrant(uint16 sprite_idx, bool fix)
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: Wouldn't `sprite_is_in_quadrant_cycle` sound more natural?

File: src/openrct2/world/sprite.c [hunk 7]
```diff
@@ -823,3 +826,106 @@ bool sprite_get_flashing(rct_sprite *sprite)
...
+            }
+            break;
+        }
+    }
+    return cycled;
+}
+
+bool check_for_sprite_list_cycles(bool fix)
+{
+    for (sint32 i = 0; i < 6; i++) {
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: `NUM_SPRITE_LISTS`

File: src/openrct2/world/sprite.c [hunk 8]
```diff
@@ -823,3 +826,106 @@ bool sprite_get_flashing(rct_sprite *sprite)
...
+        if (sprite_is_in_cycle(gSpriteListHead[i], fix)) {
+            return true;
+        }
+    }
+    return false;
+}
+
+bool check_for_spatial_index_cycles(bool fix)
+{
+    for (size_t i = 0; i < 0x10000; i++) {
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: `SPATIAL_INDEX_LOCATION_NULL`, `sint32`

File: src/openrct2/world/sprite.c [hunk 9]
```diff
@@ -259,15 +259,13 @@ void sprite_clear_all_unused()
...
         sprite = &get_sprite(spriteIndex)->unknown;
-        nextSpriteIndex = sprite->next;
-        previousSpriteIndex = sprite->previous;
-        memset(sprite, 0, sizeof(rct_sprite));
-        sprite->sprite_identifier = SPRITE_IDENTIFIER_NULL;
-        sprite->next = nextSpriteIndex;
-        sprite->previous = previousSpriteIndex;
+        sprite_reset(sprite);
         sprite->linked_list_type_offset = SPRITE_LIST_NULL * 2;
-        sprite->sprite_index = spriteIndex;
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: It looks innocuous, but right before release I'd rather have this one line left in. There's no guarantee the sprite's index is set correctly. You can leave a comment explaining this oddity.

Comment (rwjuk) [inline src/openrct2/world/sprite.c]: Good point! Reverted.

File: src/openrct2/world/sprite.c [hunk 10]
```diff
@@ -912,8 +898,15 @@ static bool sprite_is_in_cycle_quadrant(uint16 sprite_idx, bool fix)
 
 bool check_for_sprite_list_cycles(bool fix)
 {
-    for (sint32 i = 0; i < 6; i++) {
+    for (sint32 i = 0; i < NUM_SPRITE_LISTS; i++) {
         if (sprite_is_in_cycle(gSpriteListHead[i], fix)) {
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: superfluous argument?

Comment (rwjuk) [inline src/openrct2/world/sprite.c]: Whoops.

File: src/openrct2/world/sprite.c [hunk 11]
```diff
@@ -823,3 +830,107 @@ bool sprite_get_flashing(rct_sprite *sprite)
...
+bool check_for_sprite_list_cycles(bool fix)
+{
+    for (sint32 i = 0; i < NUM_SPRITE_LISTS; i++) {
+        if (sprite_is_in_cycle(gSpriteListHead[i])) {
+            if (fix)
+            {
+                rct_sprite * spr = get_sprite(gSpriteListHead[i]);
+
+                // There may be a better solution than simply setting this to 0xFFFF
+                spr->unknown.next = SPRITE_INDEX_NULL;
```
Comment (janisozaur) [inline src/openrct2/world/sprite.c]: Thinking about it a bit more, this is not a proper fix.

Imagine such a list:
```
A--->B--->C--->D--->E
     ^              |
     |              |
     +--------------+
```

You will only have removed node `A` from it, while there is still a loop present. You need to fix `slow` (or `fast`, but it is the same node at the time it detects the cycle), not the head.

Comment (rwjuk) [inline src/openrct2/world/sprite.c]: ... you're absolutely right. For some reason I'd thought that it'd be the same as it was iterating through, but no, further iteration goes on to find the loop. Hmm... now how to fix that.

**Comment by janisozaur** [comment]
@PFCKrutonium can you please post results of your testing?

**Comment by rwjuk** [comment]
This isn't the cause of @PFCKrutonium 's bug, that's a regression in #5708 and will need a separate fix.

**Comment by janisozaur** [comment]
@Gymnasiast that merge was a bit premature. There was still review pending from @IntelOrca and there are still more improvements to be done I discussed with @rwjuk. Sorry about not leaving a request to hold the merge off a little.

**Comment by janisozaur** [comment]
Regarding the improvements I mentioned earlier, consider such a list:

```
A--->B--->C--->D--->E
     ^              |
     |              |
     +--------------+
```

Right now the code breaks the cycle at arbitrary link and does nothing else, so you end up with lists: `ABC` and `DE` (actually, `DEBC`). It is unclear how the `DE` sprites will work. The fix should relink the list to form a single conformant list, say by re-ordering sprites in such a way: `E` should have its `next` relinked to `A`, which will cause the list to be `DEABC`.
