### PR TITLE
Sub 68F41A

### LINKED ISSUE #1594: Crash when using hyper speed
Every time I speed up the game to hyper speed, it seems to crash at some. It has happened when the game ran at hyper speed, but also when the game ran at normal speed, 30 seconds after switching back from hyper speed.

A crash dump:
```
Unhandled exception: page fault on read access to 0x000004b6 in 32-bit code (0x70097bca).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:70097bca ESP:0033fb64 EBP:0033fb78 EFLAGS:00210202(  R- --  I   - - - )
 EAX:00000000 EBX:b541ff09 ECX:00000017 EDX:00000478
 ESI:01420538 EDI:00000000
Stack dump:
0x0033fb64:  011139bc 00000000 00000000 0033fc10
0x0033fb74:  700af62f 0033fbd8 7004b7f7 00000000
0x0033fb84:  000000a6 000000af 0000023e 0033fbc0
0x0033fb94:  7007732f 00f718c0 00000011 00000ac0
0x0033fba4:  fffff6e0 00000940 fffff692 00000900
0x0033fbb4:  00f718c0 00000ae0 fffff700 0033fbf0
000c: sel=0067 base=00000000 limit=00000000 32-bit r-x
Backtrace:
=>0 0x70097bca in openrct2 (+0x97bca) (0x0033fb78)
  1 0x7004b7f7 in openrct2 (+0x4b7f6) (0x0033fbd8)
  2 0x0068f990 in openrct2 (+0x28f98f) (0x702c7680)
  3 0x7004a6df in openrct2 (+0x4a6de) (0x7004a573)
  4 0x7004a5b8 in openrct2 (+0x4a5b7) (0x7004a573)
  5 0x00000000 (0x7004a573)
  6 0x18b808ec (0x83e58955)
0x70097bca: movzbl	0x4b6(%eax),%eax
Modules:
Module	Address			Debug info	Name (124 modules)
PE	  400000- 14b6000	Export          openrct2
PE	64940000-6497d000	Deferred        libwinpthread-1
PE	6c740000-6c83f000	Deferred        sdl2
PE	70000000-70c2f000	Dwarf           openrct2
ELF	7b800000-7ba5b000	Deferred        kernel32<elf>
  \-PE	7b810000-7ba5b000	\               kernel32
ELF	7bc00000-7bcdb000	Deferred        ntdll<elf>
  \-PE	7bc10000-7bcdb000	\               ntdll
ELF	7bf00000-7bf04000	Deferred        <wine-loader>
ELF	7cfaf000-7cfe3000	Deferred        msctf<elf>
  \-PE	7cfc0000-7cfe3000	\               msctf
ELF	7cfe3000-7cfec000	Deferred        libogg.so.0
ELF	7cfec000-7d01a000	Deferred        libvorbis.so.0
ELF	7d01a000-7d0a9000	Deferred        libvorbisenc.so.2
ELF	7d0a9000-7d0dd000	Deferred        libflac.so.8
ELF	7d0dd000-7d0e4000	Deferred        libasyncns.so.0
ELF	7d0e4000-7d156000	Deferred        libsndfile.so.1
ELF	7d156000-7d1c5000	Deferred        libpulsecommon-4.0.so
ELF	7d1c5000-7d214000	Deferred        libpulse.so.0
ELF	7d23e000-7d266000	Deferred        winepulse<elf>
  \-PE	7d240000-7d266000	\               winepulse
ELF	7d266000-7d288000	Deferred        mmdevapi<elf>
  \-PE	7d270000-7d288000	\               mmdevapi
ELF	7d2ce000-7d2fe000	Deferred        p11-kit-trust.so
ELF	7d2fe000-7d307000	Deferred        librt.so.1
ELF	7d307000-7d30e000	Deferred        libffi.so.6
ELF	7d30e000-7d313000	Deferred        libgpg-error.so.0
ELF	7d313000-7d32b000	Deferred        libresolv.so.2
ELF	7d32b000-7d32f000	Deferred        libkeyutils.so.1
ELF	7d32f000-7d37a000	Deferred        libdbus-1.so.3
ELF	7d37a000-7d3b6000	Deferred        libp11-kit.so.0
ELF	7d3b6000-7d3ca000	Deferred        libtasn1.so.6
ELF	7d3ca000-7d450000	Deferred        libgcrypt.so.11
ELF	7d450000-7d45c000	Deferred        libkrb5support.so.0
ELF	7d45c000-7d48c000	Deferred        libk5crypto.so.3
ELF	7d48c000-7d54a000	Deferred        libkrb5.so.3
ELF	7d54a000-7d610000	Deferred        libgnutls.so.26
ELF	7d610000-7d655000	Deferred        libgssapi_krb5.so.2
ELF	7d655000-7d6c2000	Deferred        libcups.so.2
ELF	7d6c4000-7d6ce000	Deferred        libwrap.so.0
ELF	7d6ce000-7d6d9000	Deferred        libjson-c.so.2
ELF	7d6d9000-7d6ec000	Deferred        gnome-keyring-pkcs11.so
ELF	7d6ec000-7d723000	Deferred        uxtheme<elf>
  \-PE	7d6f0000-7d723000	\               uxtheme
ELF	7d723000-7d729000	Deferred        libxfixes.so.3
ELF	7d729000-7d734000	Deferred        libxcursor.so.1
ELF	7d734000-7d744000	Deferred        libxi.so.6
ELF	7d744000-7d748000	Deferred        libxcomposite.so.1
ELF	7d748000-7d753000	Deferred        libxrandr.so.2
ELF	7d753000-7d75e000	Deferred        libxrender.so.1
ELF	7d75e000-7d764000	Deferred        libxxf86vm.so.1
ELF	7d764000-7d768000	Deferred        libxinerama.so.1
ELF	7d768000-7d76f000	Deferred        libxdmcp.so.6
ELF	7d76f000-7d773000	Deferred        libxau.so.6
ELF	7d773000-7d795000	Deferred        libxcb.so.1
ELF	7d795000-7d8c9000	Deferred        libx11.so.6
ELF	7d8c9000-7d8dc000	Deferred        libxext.so.6
ELF	7d8df000-7d8e4000	Deferred        libcom_err.so.2
ELF	7d8e4000-7d8f6000	Deferred        libavahi-client.so.3
ELF	7d8f6000-7d904000	Deferred        libavahi-common.so.3
ELF	7d906000-7d998000	Deferred        winex11<elf>
  \-PE	7d910000-7d998000	\               winex11
ELF	7da27000-7da50000	Deferred        libexpat.so.1
ELF	7da50000-7da8b000	Deferred        libfontconfig.so.1
ELF	7da8b000-7dab3000	Deferred        libpng12.so.0
ELF	7dab3000-7dacd000	Deferred        libz.so.1
ELF	7dacd000-7db6d000	Deferred        libfreetype.so.6
ELF	7db97000-7dccd000	Deferred        oleaut32<elf>
  \-PE	7dbb0000-7dccd000	\               oleaut32
ELF	7dccd000-7dcf2000	Deferred        imm32<elf>
  \-PE	7dcd0000-7dcf2000	\               imm32
ELF	7dcf2000-7dd28000	Deferred        ws2_32<elf>
  \-PE	7dd00000-7dd28000	\               ws2_32
ELF	7dd28000-7ddd0000	Deferred        msvcrt<elf>
  \-PE	7dd40000-7ddd0000	\               msvcrt
ELF	7ddf4000-7de3d000	Deferred        dsound<elf>
  \-PE	7de00000-7de3d000	\               dsound
ELF	7de3d000-7de81000	Deferred        dplayx<elf>
  \-PE	7de40000-7de81000	\               dplayx
ELF	7de81000-7decc000	Deferred        dinput<elf>
  \-PE	7de90000-7decc000	\               dinput
ELF	7decc000-7df0c000	Deferred        winspool<elf>
  \-PE	7ded0000-7df0c000	\               winspool
ELF	7df0c000-7e013000	Deferred        comctl32<elf>
  \-PE	7df10000-7e013000	\               comctl32
ELF	7e013000-7e08d000	Deferred        shlwapi<elf>
  \-PE	7e020000-7e08d000	\               shlwapi
ELF	7e08d000-7e2c0000	Deferred        shell32<elf>
  \-PE	7e0a0000-7e2c0000	\               shell32
ELF	7e2c0000-7e3ab000	Deferred        comdlg32<elf>
  \-PE	7e2d0000-7e3ab000	\               comdlg32
ELF	7e3ab000-7e4ba000	Deferred        opengl32<elf>
  \-PE	7e3d0000-7e4ba000	\               opengl32
ELF	7e4ba000-7e5fa000	Deferred        wined3d<elf>
  \-PE	7e4d0000-7e5fa000	\               wined3d
ELF	7e5fa000-7e66f000	Deferred        ddraw<elf>
  \-PE	7e600000-7e66f000	\               ddraw
ELF	7e66f000-7e69a000	Deferred        msacm32<elf>
  \-PE	7e670000-7e69a000	\               msacm32
ELF	7e69a000-7e71b000	Deferred        rpcrt4<elf>
  \-PE	7e6b0000-7e71b000	\               rpcrt4
ELF	7e71b000-7e857000	Deferred        ole32<elf>
  \-PE	7e730000-7e857000	\               ole32
ELF	7e857000-7e8c9000	Deferred        advapi32<elf>
  \-PE	7e860000-7e8c9000	\               advapi32
ELF	7e8c9000-7e9e6000	Deferred        gdi32<elf>
  \-PE	7e8e0000-7e9e6000	\               gdi32
ELF	7e9e6000-7eb40000	Deferred        user32<elf>
  \-PE	7ea00000-7eb40000	\               user32
ELF	7eb40000-7ebfa000	Deferred        winmm<elf>
  \-PE	7eb50000-7ebfa000	\               winmm
ELF	7ef6a000-7ef77000	Deferred        libnss_files.so.2
ELF	7ef77000-7ef90000	Deferred        libnsl.so.1
ELF	7ef90000-7efd6000	Deferred        libm.so.6
ELF	7efe6000-7f000000	Deferred        version<elf>
  \-PE	7eff0000-7f000000	\               version
ELF	f7331000-f74df000	Deferred        libc.so.6
ELF	f74df000-f74e4000	Deferred        libdl.so.2
ELF	f74e5000-f7501000	Deferred        libpthread.so.0
ELF	f7504000-f7510000	Deferred        libnss_nis.so.2
ELF	f7522000-f752b000	Deferred        libnss_compat.so.2
ELF	f752b000-f76e0000	Dwarf           libwine.so.1
ELF	f76e2000-f7704000	Deferred        ld-linux.so.2
ELF	f7706000-f7707000	Deferred        [vdso].so
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\Spelletjes\RollerCoaster Tycoon 2\openrct2.exe
	0000002f    2
	0000002e   15
	0000002d   15
	0000002c    0
	0000002b    0
	0000002a   15
	00000009    0 <==
0000000e services.exe
	00000024    0
	00000023    0
	0000001c    0
	00000014    0
	00000010    0
	0000000f    0
00000012 mscorsvw.exe
	00000019    0
	00000017    0
	00000013    0
0000001a winedevice.exe
	00000022    0
	0000001f    0
	0000001e    0
	0000001b    0
00000020 plugplay.exe
	00000026    0
	00000025    0
	00000021    0
00000027 explorer.exe
	00000029    0
	00000028    0
System information:
    Wine build: wine-1.6.2
    Platform: i386
    Host system: Linux
    Host version: 4.0.0-040000-generic
```

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Implementation of a bunch of peep related logic. This could easily have different behavior to the base game as this is used extensively for peep interactions.

Fixes #1594

### CODE REVIEW

File: src/peep/peep.c [hunk 1]
```diff
@@ -129,13 +134,523 @@ void peep_update_all()
...
+	loc_68F9F3:
+		if (peep->happiness_growth_rate >= 128)
+			peep->happiness_growth_rate--;
+		else
+			peep->happiness_growth_rate++;
+
+		peep->nausea_growth_rate = max(peep->nausea_growth_rate - 2, 0);
+
+		if (peep->energy <= 50){
+			peep->energy = max(peep->energy - 2, 0);
```
Comment (duncanspumpkin) [inline src/peep/peep.c:514]: This isn't correct its `peep->happiness_growth_rate = max(peep->happiness_growth_rate - 2, 0);` Silly me.
