### PR TITLE
Fix #14412: NPE in vehicle_create_car()

### LINKED ISSUE #14412: [c34853] openrct2.exe: vehicle_create_car, vehicle_create_trains, Ride::CreateVehicles, Ride::Test, RideSetStatusAction::Exec...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/c3485304ab4f4dead1c40d1f8e2aa3509247164b36a60f8233cc0c16a681b2d5">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\조신익\Documents\OpenRCT2\7a6af5e9-747b-40a7-b88d-9df9abab8713.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\조신익\Documents\OpenRCT2\7a6af5e9-747b-40a7-b88d-9df9abab8713.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\조신익\Documents\OpenRCT2\screenshot\뇘쟑샇 엷뗥뛳 2021-04-01 04-43-34.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>6ec379c</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
vehicle_create_car
vehicle_create_trains
Ride::CreateVehicles
Ride::Test
RideSetStatusAction::Execute
GameActions::ExecuteInternal
Ride::Update
Ride::UpdateAll
OpenRCT2::GameState::UpdateLogic</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -4097,6 +4097,9 @@ static Vehicle* vehicle_create_car(
     if (vehicle == nullptr)
         return nullptr;
 
+    if (trackElement == nullptr)
+        return nullptr;
+
```
Comment (tupaschoal) [inline src/openrct2/ride/Ride.cpp:4102]: Small possible optimization, but we should probably do this check first in the function, then we avoid calling a handful of gets?

**Review by tupaschoal — APPROVED** [review]
