### PR TITLE
Fix #6318: Can't fire staff that are being placed

### LINKED ISSUE #6318: Cannot sack staff that have not been placed
**OS:** Linux
**Version:** 0.1.1 and above
**Commit/Build:** 4601265 and newer

Staff whose location is "(select location)" cannot be sacked by any available means.

- [ ] Reproducible in RCT2 (vanilla)? Cannot verify on my platform (even with Wine -- the game exits after a "CD-ROM drive not found" error), but does not occur in RCT1.

**Steps to reproduce:**
1. Optional: disable "Automatically place staff"
2. Pick up a staff member (and/or if following step 1, hire a new staff member) so that their location is "(select location)". Doesn't matter what type of staff.
3. Attempt to sack the staff member, either by using the "quick fire" method from the Staff window or the trash can from the staff member's own window.
4. Staff member will still be employed.

### PR DESCRIPTION
**Pull request by trigger-death**
Removed `peep->state == PEEP_STATE_PICKED` check as well as the
redundant `remove_peep_from_ride` from `game_command_fire_staff_member`.

### CODE REVIEW

**Comment by janisozaur** [comment]
@trigger-death this needs network version change in `network.h`

**Comment by janisozaur** [comment]
And it should be "Can't", not "Can" in commit message

File: src/openrct2/peep/staff.c [hunk 1]
```diff
@@ -502,11 +502,6 @@ void game_command_fire_staff_member(sint32 *eax, sint32 *ebx, sint32 *ecx, sint3
             *ebx = MONEY32_UNDEFINED;
             return;
         }
-        if (peep->state == PEEP_STATE_PICKED) {
-            *ebx = MONEY32_UNDEFINED;
-            return;
-        }
-        remove_peep_from_ride(peep);
```
Comment (Gymnasiast) [inline src/openrct2/peep/staff.c]: Are you sure this is not going to have side effects? Especially the removal of the `remove_peep_from_ride()` call? (I did check that function and I think it should be okay, but any particular reason you removed it?)

Comment (trigger-death) [reply src/openrct2/peep/staff.c]: `remove_peep_from_ride` is the first function called in `peep_sprite_remove` so it's okay.

**Comment by Gymnasiast** [comment]
Could you rebase and bump the network version? I'll merge it.
