### PR TITLE
Make renewing a ride also reset its downtime

### LINKED ISSUE #25625: Refurbishing or renewing a ride does not reset the dowtime
### Operating System

Any

### OpenRCT2 build

Any

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Renewing a ride, either via the cheat or refurbishing, should include the downtime being reset to 0%.

### Steps to reproduce

Refurbish a ride with downtime.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by MarcelVos96**
Fixes #25625

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -5386,6 +5386,11 @@ void Ride::renew()
     // Set build date to current date (so the ride is brand new)
     buildDate = GetDate().GetMonthsElapsed();
     reliability = kRideInitialReliability;
+    for (int32_t i = OpenRCT2::Limits::kDowntimeHistorySize - 1; i >= 0; i--)
```
Comment (Gymnasiast) [inline src/openrct2/ride/Ride.cpp]: Why are you iterating over this backwards?

Comment (MarcelVos96) [reply src/openrct2/ride/Ride.cpp]: I copied the bit of code where the downtime gets updated, and that does it backwards: https://github.com/OpenRCT2/OpenRCT2/blob/b1103708ea4e78844eff6f610b1c4644b4166d84/src/openrct2/ride/Ride.cpp#L1426

Should I change it to forwards?

Comment (AaronVanGeffen) [reply src/openrct2/ride/Ride.cpp]: For resetting, forwards will be more efficient.

In fact, this is probably be a good case for using `std::fill` instead of a for loop. This will likely compile down to not using a loop at all.

Comment (MarcelVos96) [reply src/openrct2/ride/Ride.cpp]: Ok, I changed it to a fill.

**Review by Gymnasiast — APPROVED** [review]
