### PR TITLE
Fix #19076: scrolling on money amounts doesn’t work

### LINKED ISSUE #19076: Scrolling doesn't work anymore
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.3-85-g6017983 (6017983 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

Issues building the game

### Describe the issue

Hi !

Since the last version of openRCT2, I cannot scroll anymore to increase prices or loan.
openrct2_nVccQeT5fn
I used to be able to put my mouse on the amout and scroll to increase/decrease.
This also happens with shops, and basically any prizes.

### Steps to reproduce

1. Open any park
2. Try to increase/decrease loan or a shop's price by scrolling with your mouse. It won't work, but it used to work.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2-ui/interface/Window.cpp [hunk 1]
```diff
@@ -478,8 +478,8 @@ static bool WindowOtherWheelInput(rct_window& w, WidgetIndex widgetIndex, int32_
         case WindowWidgetType::Spinner:
             buttonWidgetIndex = wheel < 0 ? widgetIndex + 1 : widgetIndex + 2;
             expectedType = WindowWidgetType::Button;
-            expectedContent[0] = ImageId(STR_NUMERIC_UP, FilterPaletteID::PaletteNull);
-            expectedContent[1] = ImageId(STR_NUMERIC_DOWN, FilterPaletteID::PaletteNull);
+            expectedContent[0] = ImageId(STR_NUMERIC_UP);
```
Comment (duncanspumpkin) [inline src/openrct2-ui/interface/Window.cpp:481]: What is this even doing? Why are we turning a string into an image.

Comment (Gymnasiast) [reply src/openrct2-ui/interface/Window.cpp:481]: It checks if the next button has a + image, so that it knows it’s dealing with a spinner/stepper.

Comment (duncanspumpkin) [reply src/openrct2-ui/interface/Window.cpp:481]: Urgh this is messy code. Its actually checking that the next button has a + string so that it knows its dealing with a spinner stepper. We should really split this code in two one for the image button and one for the string button then we aren't trying to stuff a string in the ImageId and compare a ImageId with a string.

Comment (Gymnasiast) [reply src/openrct2-ui/interface/Window.cpp]: I have pushed a refactor.

**Review by duncanspumpkin — APPROVED** [review]
