### PR TITLE
Fix #5318 - clearing ghost paths with bulldozer yields unlimited free money

### LINKED ISSUE #5318: Using the bulldozer tool on under-construction paths results in unlimited free money.
**OS:** [Windows 8.1]
**Version:** [?]
**Commit/Build:** [?]

Using the bulldozer tool on under-construction paths results in unlimited free money.

- [ No] Reproducible in RCT2 (vanilla)?
- [ No] Multiplayer?

**Steps to reproduce:**
1: Open up the path builder

2: Set it to the continuous mode (where it automatically suggests the next piece; the one you use to build elevated paths; where you don't have to click each square you want a path one by one)

3: Click anywhere you can build a path, so that the white (or transparent) about-to-be-built path piece appears

4: Open the bulldozer menu, and set it to destroy paths only

5: With the bulldozer tool, click on the not-built-yet path section

When you do that, you get the $10 for destroying the path ... even though it doesn't destroy the path, because the path isn't built yet. And if you hold it down, it just does it over and over again, in quick succession. Holding it down for just a few seconds will give you thousands.

### PR DESCRIPTION
**Pull request by rwjuk**
Currently ghost footpaths are treated as regular paths when handling removal; this results in a refund when clearing these ghosts with the bulldozer tool as detailed in #5318. This pull request fixes that by returning a refund of zero for ghost paths.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you update the network version?

**Comment by rwjuk** [comment]
Done! Wasn't sure whether it'd be needed for this one!

**Comment by janisozaur** [comment]
@rwjuk if it affects logic of the game\*, it needs a new network version. It is done so we can have a technical assurance all clients are executing the same logic, otherwise it would lead to desyncs.

There are still some desync causes left unsolved.

\* other than fixing crashes, as a crashed client/server doesn't execute any logic. We sometimes also bump it for [lesser reasons](https://github.com/OpenRCT2/OpenRCT2/pull/5202#issuecomment-280584297).

File: src/openrct2/world/footpath.c [hunk 1]
```diff
@@ -449,7 +449,7 @@ money32 footpath_remove_real(sint32 x, sint32 y, sint32 z, sint32 flags)
 		sub_6A759F();
 	}
 
-	return (flags & (1 << 5)) || (gParkFlags & PARK_FLAGS_NO_MONEY) ? 0 : -MONEY(10,00);
+	return (flags & (1 << 5)) || (gParkFlags & PARK_FLAGS_NO_MONEY) || map_element_is_ghost(mapElement) ? 0 : -MONEY(10,00);
```
Comment (duncanspumpkin) [inline src/openrct2/world/footpath.c]: This is starting to look horrible split it onto a separate line.

Comment (rwjuk) [inline src/openrct2/world/footpath.c]: As in break it out into an if/else rather than a ternary expression?

Comment (Gymnasiast) [inline src/openrct2/world/footpath.c]:
```
if (
    flags & (1 << 5)) || 
    (gParkFlags & PARK_FLAGS_NO_MONEY) || 
    map_element_is_ghost(mapElement)
) {
    return 0;
}
else
{
    return -MONEY(10,00);
}
```

Comment (rwjuk) [inline src/openrct2/world/footpath.c]: Ahh, I see - to prevent you from having to scroll horizontally to see the conditions. Understood.

Comment (IntelOrca) [inline src/openrct2/world/footpath.c]:
```c
money32 cost = -MONEY(10,00);
bool is??? = (flags & (1 << 5);
bool moneyEnabled = (gParkFlags & PARK_FLAGS_NO_MONEY);
bool isGhost = map_element_is_ghost(mapElement);
if (is??? || moneyEnabled || isGhost) {
    cost = 0;
}
return cost;
```

The above approach ensures single entry, single exit principle and debugging is easier as each sub condition can be easily queried.

Comment (rwjuk) [inline src/openrct2/world/footpath.c]: While we're here, we should also probably replace that (1 << 5) magic number with the appropriate constant, if only so that we can name the variable something sane...

Comment (Gymnasiast) [inline src/openrct2/world/footpath.c]: @IntelOrca I find that ugly. I also don't see the advantage of the 'single entry, single exit' rule: it usually needlessly complicates code.

Comment (IntelOrca) [inline src/openrct2/world/footpath.c]: @Gymnasiast I originally thought like you - but was told to do this way at work. Eventually I saw the benefits.

My own personal rule is to extract as much as possible to separate functions. Something like `gParkFlags & PARK_FLAGS_NO_MONEY` should be a new function called `IsMoneyEnabled()`.

File: src/openrct2/world/footpath.c [hunk 2]
```diff
@@ -449,8 +449,18 @@ money32 footpath_remove_real(sint32 x, sint32 y, sint32 z, sint32 flags)
...
+	bool isNotOwnedByPark = (flags & (1 << 5));
+	bool moneyDisabled = (gParkFlags & PARK_FLAGS_NO_MONEY);
+	bool isGhost = map_element_is_ghost(mapElement);
+
+	if (isNotOwnedByPark || moneyDisabled || isGhost) {
+		cost = 0;
+	}
+
+	return cost;
+	}
```
Comment (Gymnasiast) [inline src/openrct2/world/footpath.c]: This right curly bracket should not be intended.

Comment (rwjuk) [inline src/openrct2/world/footpath.c]: Duh! Fixed.

File: src/openrct2/world/footpath.c (hunk 1 above)
Comment (rwjuk) [inline src/openrct2/world/footpath.c]: It also allows for easier debugging. You can set a breakpoint on each condition and go poking around in the state after each is evaluated should weird things start happening.

**Comment by Gymnasiast** [comment]
I have merged this. One thing to look out for is the commit message: you should describe what your commit _changes_. For example, this commit became:
```Do not return money when demolishing a ghost footpath, fixes #5318```

**Comment by rwjuk** [comment]
Noted, thanks.
