### PR TITLE
Fix #21318: VirtualFloor not properly invalidated

### LINKED ISSUE #21318: Virtual floor for building scenery at non-ground level not properly invalidated when moving cursor while releasing shift key
### Operating System

Linux

### OpenRCT2 build

8abda17cb3bb204a2394eb7311c221f0e69a2c46

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When building scenery above the ground via pressing the shift key, the blue "virtual floor" that is displayed at the height the scenery would be built at is not properly invalidated after the shift key has been released.  
More precisely, if the cursor is moved *while* releasing the shift key, parts of the floor will remain visible.  
As usual, invalidation / redrawing can be forced by hovering over the affected areas.

release-up

### Steps to reproduce

1. Start any scenario or track designer
2. Select "build scenery" and then some basic block
3. Move cursor at middle or lower part of screen, somewhere above flat land
4. Press shift and hold it ("virtual floor" gets displayed)
5. Move cursor up and release shift during the movement (parts of "virtual floor" remain visible)

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by zzril**
This PR changes the `VirtualFloorInvalidate` function to use a local variable to remember whether new base coordinates exist for the VirtualFloor.  
(Previously, it was attempted to deduce this by comparing them to some dummy values (max/min int32), but this would fail because the coordinates would actually be set to max/min int32 minus/plus the size of the floor.)

Closes #21318

### CODE REVIEW

File: src/openrct2/paint/VirtualFloor.cpp [hunk 1]
```diff
@@ -122,6 +122,11 @@ void VirtualFloorInvalidate()
         }
     }
 
+    bool existsNewRegion
```
Comment (ZehMatt) [inline src/openrct2/paint/VirtualFloor.cpp:125]: I think a variable name like `invalidateNewRegion` is perhaps better?

**Review by ZehMatt — APPROVED** [review]
I've tested the code and it fixes the issue, left a little remark but its not too important for the fix, I generally think we should clean up the code and also introduce some constants to avoid all that numeric_limits usage.

File: src/openrct2/paint/VirtualFloor.cpp (hunk 1 above)
Comment (zzril) [reply src/openrct2/paint/VirtualFloor.cpp]: Indeed, changed it.

**Review by tupaschoal — APPROVED** [review]
