### PR TITLE
Fix #19694: Show guest purchases influencing the game state

### LINKED ISSUE #19694: Replays will not work correctly when show_guest_purchases = true is set.
The setting seems to influence replays to be unusable, even when the replay is recorded locally with the setting enabled and then tested on the same machine. This might be due to the fact that in headless it probably skips creating the money effect even when the setting is enabled, this is just a guess and needs some more investigation.

### PR DESCRIPTION
**Pull request by ZehMatt**
I renamed Vertical to GuestPurchase as this also better matches the actual usage of the variable. Money will no longer be conditionally created for guest purchases and instead hides the money when the option to show guest purchases is disabled which keeps the game state identical regardless of the user choice.

This makes it also safe for network play, people can now turn the option on or off without having any side effects on the entity registry. This most likely will invalidate bpb replay

Closes #19694

### CODE REVIEW

File: src/openrct2/entity/MoneyEffect.cpp [hunk 1]
```diff
@@ -172,6 +173,18 @@ void MoneyEffect::Paint(PaintSession& session, int32_t imageDirection) const
 {
     PROFILED_FUNCTION();
 
+    if (gScreenFlags & SCREEN_FLAGS_TITLE_DEMO)
+    {
+        // Don't render any money in the title screen.
+        return;
+    }
```
Comment (Broxzier) [inline src/openrct2/entity/MoneyEffect.cpp:180]: I believe there is some code that removes guest purchases when the title sequence player loads a park. With this bit of code, that part can likely be removed.

Comment (ZehMatt) [reply src/openrct2/entity/MoneyEffect.cpp:180]: Guest purchases are no longer conditional, this has to stay or it will show guests purchasing stuff in the title screen.

Comment (Broxzier) [reply src/openrct2/entity/MoneyEffect.cpp:180]: Yes, I talking about the part that removes the money effects when loading a park. I'll try to find this tonight when I'm home if you haven't found it them already.

Comment (ZehMatt) [reply src/openrct2/entity/MoneyEffect.cpp:180]: Sorry misunderstood that, yeah makes sense to remove that code that removes the money.

**Comment by ZehMatt** [comment]
Ideally #19683 gets merged first or I'll have to re-create replays twice.

**Review by duncanspumpkin — APPROVED** [review]

File: src/openrct2/entity/Guest.cpp [hunk 2]
```diff
@@ -2300,15 +2300,7 @@ void Guest::SpendMoney(money64& peep_expend_type, money64 amount, ExpenditureTyp
...
 
-    if (gConfigGeneral.ShowGuestPurchases && !(gScreenFlags & SCREEN_FLAGS_TITLE_DEMO))
-    {
-        // HACK Currently disabled for multiplayer due to limitation of all sprites
-        //      needing to be synchronised
-        if (NetworkGetMode() == NETWORK_MODE_NONE && !gOpenRCT2Headless)
-        {
-            MoneyEffect::CreateAt(amount, GetLocation(), true);
-        }
-    }
```
Comment (Broxzier) [inline src/openrct2/entity/Guest.cpp:2311]: This is the bit responsible for no money effects to appear in the title sequence, so my other comment is already taken care of in this PR.

**Review by Broxzier — APPROVED** [review]

**Comment by janisozaur** [comment]
Nice fix!
