### PR TITLE
Fix #20134: Don't update grass length outside of the actual map

### LINKED ISSUE #20134: Screen is invalidated due to grass in the void
### Operating System

*

### OpenRCT2 build

v0.4.0

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Whenever the grass length is updated it invalidates the screen for the specific tile. It currently updates tiles that are in the void and invisible due to not checking if the map position is outside the actual park.

### Steps to reproduce

Open any park and enable show dirty virtuals, the void will be constantly invalidated at one side.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZehMatt**
Closes #20134

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
What's the impact of this PR on FPS?

**Comment by ZehMatt** [comment]
develop: 
image

PR: 
image

Biggest effect is on the largest zoom.

File: src/openrct2/world/Map.cpp [hunk 1]
```diff
@@ -1345,7 +1348,6 @@ void MapUpdateTiles()
         }
 
         gGrassSceneryTileLoopPosition++;
-        gGrassSceneryTileLoopPosition &= 0xFFFF;
```
Comment (tupaschoal) [inline src/openrct2/world/Map.cpp:1348]: Was this supposed to be the "MapIsEdge"

Comment (ZehMatt) [reply src/openrct2/world/Map.cpp:1348]: The the type is uint16_t and its used to continuously update the grass, from that variable it extracts the tile position. Given its uint16_t that operation makes no sense.

Comment (IntelOrca) [reply src/openrct2/world/Map.cpp:1348]: The algorithm is a bit funky. It tries to update grass with a arbitary scan, so to distribute the growing over the whole map. This was tied to the 256x256 map (even if the map was smaller).

When increasing the map size limit, I opted to do the same 256x256 algorithm repeatedly across the whole map. So the whole map is divided into 256x256 chunks - the algorithm works like before on each chunk per update.

Comment (ZehMatt) [reply src/openrct2/world/Map.cpp:1348]: I noticed that, I wonder if we should maybe just the the prng to select the next tile to update, but all of this I would prefer to do in another PR. As for the line that was removed, this doesn't affect the logic.

File: src/openrct2/network/NetworkBase.cpp [hunk 2]
```diff
@@ -43,7 +43,7 @@
 // It is used for making sure only compatible builds get connected, even within
 // single OpenRCT2 version.
 
-#define NETWORK_STREAM_VERSION "18"
+#define NETWORK_STREAM_VERSION "19"
```
Comment (janisozaur) [inline src/openrct2/network/NetworkBase.cpp:46]: This will need to be bumped again
```suggestion
#define NETWORK_STREAM_VERSION "20"
```

https://github.com/OpenRCT2/OpenRCT2/pull/20123 already claims v19

Comment (ZehMatt) [reply src/openrct2/network/NetworkBase.cpp:46]: Will rebase

Comment (ZehMatt) [reply src/openrct2/network/NetworkBase.cpp:46]: Actually that isn't merged yet, will rebase once the PR is merged.

Comment (ZehMatt) [reply src/openrct2/network/NetworkBase.cpp]: done

File: src/openrct2/world/Map.cpp (hunk 1 above)
Comment (IntelOrca) [reply src/openrct2/world/Map.cpp:1348]: Each tile needs to be updated before each one is updated again. So for rng to work, it would need to shuffle a list of all the tiles which isn't as memory efficient.

Comment (ZehMatt) [reply src/openrct2/world/Map.cpp:1348]: I'm thinking more about a simple random distribution which would seem a bit more natural in my opinion, the prng is not too bad and has a decent distribution and grass just grows wherever it wants to grow, but I don't think we should discuss this any further here.

File: distribution/changelog.txt [hunk 3]
```diff
@@ -44,6 +44,7 @@
 - Fix: [#20033] Asset packs cannot reference game data.
 - Fix: [#20104] [Plugin] Some network APIs use player index and group index.
 - Fix: [#20099] Some scrollbar is glitched or have incorrect size when open window for the first time
+- Fix: [#20134] Grass length being updated for tiles in the void causing unneccesary drawing operations.
```
Comment (Broxzier) [inline distribution/changelog.txt:47]:
```suggestion
- Fix: [#20134] Grass length being updated for tiles in the void, causing unneccesary drawing operations.
```

**Review by Broxzier — CHANGES_REQUESTED** [review]

File: src/openrct2/world/Map.cpp (hunk 1 above)
Comment (Broxzier) [reply src/openrct2/world/Map.cpp:1348]: A uniform distribution will look more natural than the current grass update algorithm. The whole reason I immediately recognized the pattern in Matt's gif that led to this fix is pretty much proof of that.

**Review by Broxzier — APPROVED** [review]
