### PR TITLE
Fix #3598: Validate vehicle track movement

### LINKED ISSUE #3598: Multiplayer Crash
**OS:** Windows 10
**Version:** 0.0.5
**Commit:** f62932a
**Dump file**
[Dump Files.zip](https://github.com/OpenRCT2/OpenRCT2/files/264501/Dump.Files.zip)

### PR DESCRIPTION
**Pull request by zsilencer**
This should fix a lot of the crashes with vehicles from different track types.

### CODE REVIEW

File: src/ride/vehicle.c [hunk 1]
```diff
@@ -150,13 +150,54 @@ const uint8 _soundParams[SOUND_MAXID][2] = {
 	{ 0, 0 }	// SOUND_62
 };
 
+bool vehicle_move_info_valid(int cd, int typeAndDirection, int offset)
```
Comment (IntelOrca) [inline src/ride/vehicle.c]: If cd is an index into gTrackVehicleInfo, maybe it can be called trackVehicleInfoId or something?

**Comment by janisozaur** [comment]
nice
