### PR TITLE
Test prepended wooden supports

### LINKED ISSUE #4849: Supports rendered incorrectly when mixed with scenery
I hope this is not a duplicate, however I just noticed that the supports for the wooden roller coaster aren't rendered correctly if there is some scenery

**OS:** Ubuntu 16.04
**Version:** 0.0.5
**Commit/Build:** 1ae2ca5

**Screenshots / Video:**
https://youtu.be/ErlVGrUNl-0

To reproduce, build the "Black Widow" wooden roller coaster.

**Save game:**
[bugreport.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/628440/bugreport.sv6.zip)

### PR DESCRIPTION
**Pull request by marijnvdwerf**
Fixes #4849

### CODE REVIEW

File: test/testpaint/PaintIntercept.cpp [hunk 1]
```diff
@@ -132,19 +145,18 @@ namespace PaintIntercept {
...
     ) {
-        function_call call = _calls[_callCount];
-        call.function = function;
-        call.paint.image_id = imageID;
-        call.paint.offset = {xOffset, yOffset};
-        call.paint.bound_box_length = {boundBoxLengthX, boundBoxLengthY, boundBoxLengthZ};
-        call.paint.bound_box_offset = {boundBoxOffsetX, boundBoxOffsetY, boundBoxOffsetZ};
-        call.paint.z_offset = zOffset;
-        call.paint.rotation = rotation;
+		function_call * call = &_calls[_callCount];
```
Comment (janisozaur) [inline test/testpaint/PaintIntercept.cpp]: Misaligned
