### PR TITLE
Fix #17921: NPE in track_block_get_next()

### LINKED ISSUE #17921: [905956] openrct2.exe: track_block_get_next, footpath_element_dest_in_dir, Vehicle::UpdateCrossings, Vehicle::UpdateTrackMoti...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/905956fd57bb72ee6d2fa7586608286821934a54a60b2bc227d7e4d772964453">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>1d000000-1671-bc08-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\63bru\Documents\OpenRCT2\crash\9a8187c6-fbd3-463d-9679-495387b46ff2.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>18446744073709551615</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.1-154-g980e3cb (980e3cb on develop) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>980e3cb</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
track_block_get_next
footpath_element_dest_in_dir
Vehicle::UpdateCrossings
Vehicle::UpdateTrackMotionForwards
Vehicle::UpdateTrackMotion
Vehicle::UpdateTravelling
Vehicle::Update
vehicle_update_all
OpenRCT2::GameState::UpdateLogic
OpenRCT2::GameState::Tick
OpenRCT2::Context::Tick
OpenRCT2::Context::RunFixedFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -558,6 +558,8 @@ bool track_block_get_next(CoordsXYE* input, CoordsXYE* output, int32_t* z, int32
         return false;
 
     trackBlock += inputElement->GetSequenceIndex();
+    if (trackBlock == nullptr)
+        return false;
```
Comment (IntelOrca) [inline src/openrct2/ride/Ride.cpp:562]: I think this is mostly luck. If the sequence index is higher then it could be a non-nullptr but still invalid pointer. Can we instead check if the sequence index is greater than the number of sequences that track block has?

Comment (Gymnasiast) [reply src/openrct2/ride/Ride.cpp:562]: Does it have to be "instead", or can I do both?

**Review by IntelOrca — APPROVED** [review]
Could be extracted to a method
