### PR TITLE
Fix #11166: Null pointer read in Guest::UpdateRideAdvanceThroughEntrance

### LINKED ISSUE #11166: BACKTRACE ed3b54 Guest::UpdateRideAdvanceThroughEntrance
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/ed3b54844b22ad1c8a1034503ef3c54c15271fc50da6c8d6e6c6cef310049439?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Mar 30 2020 23:27:20)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Administrator\\Documents\\Random\\\\e04b7e31-cb60-499c-a1a4-618bb890d5a9.sv6.gz: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Administrator\\Documents\\Random\\\\e04b7e31-cb60-499c-a1a4-618bb890d5a9.ini: <em>1</em><br><strong>assert_failure:</strong> *: <em>1</em><br><strong>attachment_screenshot.png:</strong> *: <em>1</em><br><strong>commit:</strong> 4f6e77e: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guest::UpdateRideAdvanceThroughEntrance -> Guest::UpdateRide -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> wmain</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by janisozaur** [comment]
There's little to review really and if you tested it, I think it's fine. That said now there's #11190 I'm tempted to not merge these until we figure out some of the root causes here.

File: src/openrct2/peep/Guest.cpp [hunk 1]
```diff
@@ -3728,9 +3728,18 @@ void Guest::UpdateRideAdvanceThroughEntrance()
...
     Vehicle* vehicle = GET_VEHICLE(ride->vehicles[current_train]);
+    if (vehicle == nullptr)
+    {
+        return;
+    }
+
     for (int32_t i = current_car; i != 0; --i)
     {
         vehicle = GET_VEHICLE(vehicle->next_vehicle_on_train);
+        if (vehicle == nullptr)
```
Comment (tupaschoal) [inline src/openrct2/peep/Guest.cpp:3739]: Should this one really have been added? I guess the for was to look for the vehicle, no?

Comment (Gymnasiast) [reply src/openrct2/peep/Guest.cpp:3739]: Just take a good look at the code. It keeps fetching the next vehicle, which could eventually be `NULL`, even before the for loop ends.
