### PR TITLE
Duck improvements and fixes

### LINKED ISSUE #10093: BACKTRACE 7fcf4e scenario_create_ducks
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/7fcf4e8599e5a3a8b4832675cb6ce8ed8055def0cc903de8b80aabb021e192e5?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Oct 14 2019 11:47:23)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_screenshot.png:</strong> E:\\Documents\\OpenRCT2\\screenshot\\Bitcoinland 2019-10-14 13-47-23.png: <em>1</em><br><strong>attachment_config.ini:</strong> E:\\Documents\\OpenRCT2\\62cd89d3-3fbf-496c-b7db-1ee1ad9d08a4.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> E:\\Documents\\OpenRCT2\\62cd89d3-3fbf-496c-b7db-1ee1ad9d08a4.sv6.gz: <em>1</em><br><strong>commit:</strong> c8acb15: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ForceCrash -> Guard::Assert_VA -> openrct2_assert_fwd -> scenario_create_ducks -> scenario_week_update -> scenario_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> invoke_main</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by ZehMatt**
This PR introduces two new cheats to create and remove ducks which helps debugging them a bit better as they would only spawn during a certain time of year. This PR also fixes #10093 which now uses the correct search size for all the positions, previously it was hardcoded to 0x7F which was too big for for the selection within the 7x7 radius.

openrct2_2019-10-15_17-37-50

I also enabled duck drawing with zoom level 1, I don't think there will be ever enough ducks to have an actual performance impact.

### CODE REVIEW

File: src/openrct2/actions/SetCheatAction.hpp [hunk 1]
```diff
@@ -772,4 +780,17 @@ DEFINE_GAME_ACTION(SetCheatAction, GAME_COMMAND_CHEAT, GameActionResult)
         auto parkSetParameter = ParkSetParameterAction(isOpen ? ParkParameter::Open : ParkParameter::Close);
         GameActions::ExecuteNested(&parkSetParameter);
     }
+
+    void CreateDucks(int count) const
```
Comment (tupaschoal) [inline src/openrct2/actions/SetCheatAction.hpp]: Did you think about returning a bool, just in case it fails to create any ducks in any of the `count*100` attempts?

File: src/openrct2/actions/SetCheatAction.hpp [hunk 2]
```diff
@@ -772,4 +780,17 @@ DEFINE_GAME_ACTION(SetCheatAction, GAME_COMMAND_CHEAT, GameActionResult)
...
+    {
+        for (int i = 0; i < count; i++)
+        {
+            // 100 attempts at finding some water to create a few ducks at
+            for (int32_t attempts = 0; attempts < 100; attempts++)
```
Comment (tupaschoal) [inline src/openrct2/actions/SetCheatAction.hpp]: Is there any reason to not use pre-increment instead of post?

File: src/openrct2/scenario/Scenario.cpp [hunk 3]
```diff
@@ -473,15 +473,16 @@ static int32_t scenario_create_ducks()
     for (int32_t i = 0; i < duckCount; i++)
     {
         int32_t r = scenario_rand();
-        innerPos.x = (r >> 16) & 0x7F;
-        innerPos.y = (r & 0xFFFF) & 0x7F;
+        innerPos.x = (r >> 16) & (SquareRadiusSize - 1);
+        innerPos.y = (r & 0xFFFF) & (SquareRadiusSize - 1);
```
Comment (jensj12) [inline src/openrct2/scenario/Scenario.cpp]: Since squareRadiusSize is 96, it looks a bit strange to me to use & instead of %.

File: src/openrct2/actions/SetCheatAction.hpp (hunk 2 above)
Comment (Broxzier) [reply src/openrct2/actions/SetCheatAction.hpp]: For primitives there's no difference. The compiler is smart enough to see that the return value is not used and that there is no need to create a copy.

File: src/openrct2/scenario/Scenario.cpp (hunk 3 above)
Comment (ZehMatt) [reply src/openrct2/scenario/Scenario.cpp]: The reason has been due to r being signed, I changed the type to unsigned.

File: src/openrct2/actions/SetCheatAction.hpp (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/actions/SetCheatAction.hpp]: We don't need error handling for cheats like that.

File: src/openrct2/actions/SetCheatAction.hpp (hunk 2 above)
Comment (ZehMatt) [reply src/openrct2/actions/SetCheatAction.hpp]: This code was copied and nothing changed except the variable name, most of the code consists doing post and not pre increment. I would agree that this might have benefits if it were a hot path but this is not even close.

Comment (tupaschoal) [reply src/openrct2/actions/SetCheatAction.hpp]: I know and don't think it'll make a difference here (or maybe on most cases), but then there's no real reason to use post if not interested in the old value. Anyway, thanks for answering folks :)

Comment (ZehMatt) [reply src/openrct2/actions/SetCheatAction.hpp]: Yeah but there is also consistency which is already hard to on this mixed C/C++ environment :)

**Comment by Omaranwa** [comment]
what is Duck?
hmmmm

**Comment by Gymnasiast** [comment]
@Omaranwa 

afbeelding

**Comment by Omaranwa** [comment]
Well, You Never Know! Right!
@Gymnasiast
