### PR TITLE
Fix #14686, #23996, #25981: Preview images from different windows overwrite each other when using OpenGL

### LINKED ISSUE #14686: Coaster design preview window shows map & vice versa
**OS:** [Windows 10]
**Version:** [0.3.3]
**Commit/Build:** [3f65f28]

The coaster design preview in the Ride construction window, and the map in the Map window, show the same thing when they're both open.

- Reproducible in RCT2 (vanilla)? _NO_
- Specific to multiplayer? _NO_

**Steps to reproduce:**
1. Click the "Build new ride/attraction" icon in the toolbar
2. Click on the "Roller coasters" tab and select a coaster of any type
3. Click the "Show map of park" icon in the toolbar and select "Show map"
_The coaster design preview and the Map window both show the map_
4. Click "Select another ride" in the Ride construction window and click on a coaster of any type
_The coaster design preview and the Map window both show the coaster design now_
5. Once you select a coaster design to build, the preview will show the map again
_Alternatively:_
3. Select a coaster design to build
4. Click the "Show map of park" icon in the toolbar and select "Show map"
_The coaster design preview and the Map window both show the map_

**Screenshots / Video:**
image
image
image

**Save game:**
[DiamondHeights_map-bug_zcatch.zip](https://github.com/OpenRCT2/OpenRCT2/files/6491765/DiamondHeights_map-bug_zcatch.zip)

### PR DESCRIPTION
**Pull request by frozensnowy**
Fixes #14686, #23996, #25981

The Map, Track Design List, Track Design Placement, Install Track, and Park Preview windows all shared a single `SPR_TEMP` sprite ID for rendering dynamic preview images. 

The issue only manifests itself in OpenGL mode because they overwrite each other's textures when multiple windows were open at the same time

## Changes:
- Added separate temp sprite IDs for each window that needs one (`SPR_TEMP_MAP`, `SPR_TEMP_TRACK_LIST`, `SPR_TEMP_TRACK_PLACE`, `SPR_TEMP_PARK_PREVIEW`, `SPR_TEMP_INSTALL_TRACK`)
- Changed `_g1Temp` from a single `G1Element` to an array to store each sprite separately
- Updated range checks in drawing code to handle the new sprite ID range
- Kept `SPR_TEMP` as a legacy alias pointing to `SPR_TEMP_MAP`

Before:
image

After:
image

### CODE REVIEW

**Review by Gymnasiast — COMMENTED** [review]
Code LGTM, haven’t tested it yet.

File: src/openrct2/SpriteIds.h [hunk 1]
```diff
@@ -15,10 +15,24 @@
...
+    SPR_TEMP_BEGIN = 0x7FFFA,
+    SPR_TEMP_MAP = SPR_TEMP_BEGIN + 0,           // Map.cpp minimap
+    SPR_TEMP_TRACK_LIST = SPR_TEMP_BEGIN + 1,    // TrackList.cpp track design preview
+    SPR_TEMP_TRACK_PLACE = SPR_TEMP_BEGIN + 2,   // TrackDesignPlace.cpp placement preview
+    SPR_TEMP_PARK_PREVIEW = SPR_TEMP_BEGIN + 3,  // ParkPreview.cpp scenario/save preview
+    SPR_TEMP_INSTALL_TRACK = SPR_TEMP_BEGIN + 4, // InstallTrack.cpp track install preview
+    SPR_TEMP_END = SPR_TEMP_BEGIN + kTempSpriteCount,
+
+    // Legacy alias - kept for backward compatibility
+    SPR_TEMP = SPR_TEMP_MAP,
```
Comment (Gymnasiast) [inline src/openrct2/SpriteIds.h]: I don’t think there is any point in keeping this, especially since it’s not serialised into anything.

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
Testing was successful. Left one line note after all.

File: src/openrct2/SpriteIds.h (hunk 1 above)
Comment (frozensnowy) [reply src/openrct2/SpriteIds.h]: I've removed it yeah

**Review by Gymnasiast — APPROVED** [review]
