### PR TITLE
Fix #25201: Maintain ride list sort order, apply natural sorting

### LINKED ISSUE #25201: Ride List sorting breaks for the secondary sort
### Operating System

Windows 11

### OpenRCT2 build

Any

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC), This is a development issue

### Describe the issue

Currently the list of rides is sorted using SortListByPredicate:

```C++
        template<typename TSortPred>
        void SortListByPredicate(const TSortPred& pred)
        {
            bool desc = _windowListSortDescending;
            std::stable_sort(_rideList.begin(), _rideList.end(), [desc, pred](const auto& lhs, const auto& rhs) {
                const Ride* rideLhs = GetRide(lhs.Id);
                const Ride* rideRhs = GetRide(rhs.Id);
                if (rideLhs == nullptr || rideRhs == nullptr)
                {
                    return rideLhs != nullptr;
                }
                bool result = pred(*rideLhs, *rideRhs);
                return desc ? !result : result;
            });
        }
```

https://github.com/OpenRCT2/OpenRCT2/blob/f5faef7bea437cefe9e65ec229f4d9bc5600f5b9/src/openrct2-ui/windows/RideList.cpp#L911

std::stable_sort seems to, when both items are equal, fall back to the previous sorting of the list as a fallback.
This is why, when you open the window it starts alphabetically, and you go to another sorting (e.g. Popularity) - it appears to keep the secondary sorting of alphabetically. If you reverse the sorting then, or go to another sorting (e.g. Nausea) it breaks - first it will just not be alphabetical anymore, but on reversing the same sort again the secondary sorting (items that are equal in their primary value) will flap back and forth.

https://github.com/user-attachments/assets/f04c264a-fdf6-4d13-9653-1126f2a1b99d

pred(*rideLhs, *rideRhs) only returns a bool - True if *rideLhs comes first, False if it doesnt come first. So there is no way to catch matching primary values here to go for a fallback sorting of the name. Currently im looking what can be done but im not sure yet because im not very smart.

### Steps to reproduce

Open ride list window
Have rides with similar names and same values (e.g. popularity)
sort by this value and sort again for reversing it -> flapping values
sort by this value and then by another value that has rides on equal values -> no longer alphabetically sorted within the equal values

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZehMatt**
This PR keeps the sort consistent no matter the sort direction and keeps it stable. Also fixes the logical compare, this now matches the output of what Notepad++ or VSCode/VS will do.
develop:
image

PR:
image

Also changes the order for unknown popularity and satisfaction:
develop:
image image

PR:
image image

Close #25201

### CODE REVIEW

**Comment by ZehMatt** [comment]
Apparently the new sort order is a bit strange for some things, will have to rework that.

File: src/openrct2/core/String.cpp [hunk 1]
```diff
@@ -731,34 +731,108 @@ namespace OpenRCT2::String
...
+                if (std::isdigit(static_cast<unsigned char>(*s)))
+                {
+                    return true;
+                }
+                s++;
+            }
+            return false;
+        };
+
+        // Prioritize strings starting with digits
```
Comment (Gymnasiast) [inline src/openrct2/core/String.cpp]:
```suggestion
        // Prioritise strings starting with digits
```
(ditto for other occurrences)

File: src/openrct2/core/String.cpp [hunk 2]
```diff
@@ -731,34 +731,108 @@ namespace OpenRCT2::String
...
+        bool s1_starts_digit = std::isdigit(static_cast<unsigned char>(*s1));
```
Comment (Gymnasiast) [inline src/openrct2/core/String.cpp]:
```suggestion
        bool s1StartDigit = std::isdigit(static_cast<unsigned char>(*s1));
```
Use lowerCamelCase for local variables.

**Comment by ZehMatt** [comment]
Simplified the thing a bit and applied the review suggestions, now its good I think.

**Comment by AaronVanGeffen** [comment]
> Sorting works, expect for "Status" - it sorts by name instead in that view.

That is not new to this PR, to be fair. I wasn't sure how to tackle that in my PR that introduced the header buttons. We decided it was out of scope at the time, as it wasn't sortable before.

I agree it's worth addressing, but shouldn't block this PR, imo.

**Comment by ZehMatt** [comment]
> Sorting works, expect for "Status" - it sorts by name instead in that view. But clicking the Name column already does that. It should instead sort by the current number of guests on that ride.

Yeah, that did look a bit strange when looking at the code but that is not something I introduced in this PR. I can look at that afterwards, lets keep this PR small and work from there.

**Comment by Gymnasiast** [comment]
Makes sense, let’s get this one in as-is, then.
