### PR TITLE
Fix #14149: Numpad shortcut keys are not loaded correctly

### LINKED ISSUE #14149: Numpad shortcut keys are not loaded correctly
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 18e8690

When I map shortcut keys to either the Page Up or Page Down keys or the numpad, they get cleared once I close the game and restart it. This happens regardless of whether or not NumLock is enabled. Generally, I use "/" and "*" as my shortcut keys for decreasing and increasing the scale factor, respectively, but because of this issue, I have resorted to "Ctrl+-" and "Ctrl++" for now.

**Steps to reproduce:**
1. Start up the game and map shortcut keys to either Page Up, Page Down, or the numpad
2. Close the game
3. When you restart the game, the shortcut keys that were mapped to the aforementioned keyboard areas will be reset

**Screenshots:**
**Before closing the game:**
Way Over The Edge 2021-02-22 10-17-21
Way Over The Edge 2021-02-22 10-17-27
You can see here I have mapped shortcut keys to PgUp, PgDn, and the numpad.

**After closing the game:**
Sabulous Downs 2021-02-22 17-41-20
Sabulous Downs 2021-02-22 17-41-24
You can see here I have restarted the game, and all of my shortcut keys that were mapped to PgUp, PgDn, and/or the numpad have now been cleared.

### PR DESCRIPTION
**Pull request by IntelOrca**
I decided it was too complicated and unnecessary storing our own internal strings for keyboard keys. Instead I just use the SDL2 internal name for serialisation / deserialisation to JSON. This means the JSON file will now store `Keypad 1`, where as the UI will still show the localised name: `Numpad 1`.

I have also added a remove button to the change shortcut window so that you can now clear all shortcut bindings for a single shortcut entry.

image

### CODE REVIEW

File: src/openrct2-ui/windows/ShortcutKeys.cpp [hunk 1]
```diff
@@ -48,18 +48,25 @@ static rct_widget window_shortcut_widgets[] = {
...
+
+enum
+{
+    WIDX_REMOVE = 3
+};
 
 // clang-format off
 static rct_widget window_shortcut_change_widgets[] = {
     WINDOW_SHIM(CHANGE_WINDOW_TITLE, CHANGE_WW, CHANGE_WH),
+    MakeWidget({ 75, 56 }, { 100, 12 }, WindowWidgetType::Button, WindowColour::Primary, STR_SHORTCUT_REMOVE, STR_SHORTCUT_REMOVE_TIP),
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/ShortcutKeys.cpp:61]: 12px is too small for CJK; suggest 14px instead.
```suggestion
    MakeWidget({ 75, 56 }, { 100, 14 }, WindowWidgetType::Button, WindowColour::Primary, STR_SHORTCUT_REMOVE, STR_SHORTCUT_REMOVE_TIP),
```

**Review by janisozaur — APPROVED** [review]
