### PR TITLE
Fix #6196: Guest's energy underflows and never decreases

### LINKED ISSUE #6196: Minimum Energy Cheat Bug
**OS: Windows 10**
**Version: 0.1.2-develop**
**Commit/Build: 6547116**

Setting guests' energy to minimum using cheats causes their energy to be set at minimum as intended but receive a sudden energy boost after a second or two. The energy bar will also be off the screen when observing guest stats when it happens.

- [ Y ] Reproducible in RCT2 (vanilla)?
- [ Y ] Multiplayer?

**Steps to reproduce:**
1. Have any number of guests in the park
2. Set guests' energy to minimum using cheats

**Screenshots / Video:**
superenergy

### PR DESCRIPTION
**Pull request by Gymnasiast**
Issue caused by using max where min was intended.
This also reverts an earlier change in capping the energy target, since it seems to max out at 255, unlike energy itself.

### CODE REVIEW

File: src/openrct2/peep/peep.c [hunk 1]
```diff
@@ -1298,25 +1300,28 @@ static void sub_68F41A(rct_peep *peep, sint32 index)
...
+        if (energy < energy_target)
+            energy = energy_target;
     }
-    else{
-        energy = min(255, energy + 4);
-        if (energy > energy_growth)
-            energy = energy_growth;
+    else
+    {
+        energy = min(PEEP_MAX_ENERGY_TARGET, energy + 4);
```
Comment (janisozaur) [inline src/openrct2/peep/peep.c]: This doesn't look correct. It will always end up being `energy = energy + 4`, because the only way it could end up as `PEEP_MAX_ENERGY_TARGET` is if `energy + 4 >= 256`, but that's not a valid value for `uint8`.

Comment (Gymnasiast) [reply src/openrct2/peep/peep.c]: It _could_ have been like that in the original.

Comment (janisozaur) [reply src/openrct2/peep/peep.c]: That doesn't make it any more correct, though.

Comment (Gymnasiast) [reply src/openrct2/peep/peep.c]: Perhaps an add_clamp_uint8 would be more appropriate more then?

**Comment by ZehMatt** [comment]
```
template<class T, class U> int8 __CFADD__(T x, U y)
{
  int size = sizeof(T) > sizeof(U) ? sizeof(T) : sizeof(U);
  if ( size == 1 )
    return uint8(x) > uint8(x+y);
  if ( size == 2 )
    return uint16(x) > uint16(x+y);
  if ( size == 4 )
    return uint32(x) > uint32(x+y);
  return uint64(x) > uint64(x+y);
}
 
{
  
  if ( peep->energy < peep->energy_target )
  {
    v6 = __CFADD__(peep->energy, 4);
    peep->energy = peep->energy + 4;
    if ( v6 )
      peep->energy = -1;
    if ( peep->energy > peep->energy_target )
      peep->energy = peep->energy_target;
  }
  else
  {
    peep->energy = peep->energy - 2;
    if ( peep->energy < peep->energy_target )
      peep->energy = peep->energy_target;
  }
  
  if ( peep->energy < 0x20u )
    peep->energy = 0x20u; // Min energy
  if ( peep->energy > 0x80u )
    peep->energy = 0x80u; // Max energy
 
}
```
Thats how the original game does it, keep in mind that __CFADD__ is something from IDA to emulate carry add as seen at rct2.exe:0x0068FB9E

The current version looks slightly different.

File: src/openrct2/peep/peep.c (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/peep/peep.c]:
```
template<class T, class U> int8 __CFADD__(T x, U y)
{
  int size = sizeof(T) > sizeof(U) ? sizeof(T) : sizeof(U);
  if ( size == 1 )
    return uint8(x) > uint8(x+y);
  if ( size == 2 )
    return uint16(x) > uint16(x+y);
  if ( size == 4 )
    return uint32(x) > uint32(x+y);
  return uint64(x) > uint64(x+y);
}
 
{
  
  if ( peep->energy < peep->energy_target )
  {
    v6 = __CFADD__(peep->energy, 4);
    peep->energy = peep->energy + 4;
    if ( v6 )
      peep->energy = -1;
    if ( peep->energy > peep->energy_target )
      peep->energy = peep->energy_target;
  }
  else
  {
    peep->energy = peep->energy - 2;
    if ( peep->energy < peep->energy_target )
      peep->energy = peep->energy_target;
  }
  
  if ( peep->energy < 0x20u )
    peep->energy = 0x20u; // Min energy
  if ( peep->energy > 0x80u )
    peep->energy = 0x80u; // Max energy
 
}
```
Thats how the original game does it, keep in mind that __CFADD__ is something from IDA to emulate carry add as seen at rct2.exe:0x0068FB9E

The current version looks slightly different.

**Comment by Gymnasiast** [comment]
I have merged this to solve the immediate bug, but I have created https://github.com/OpenRCT2/OpenRCT2/issues/6431.
