### PR TITLE
fixes #1445, now checks for existance of g1.dat files in the game pat…

### LINKED ISSUE #1445: Game doesn't ask for path to RCT2 on first launch
Instead upon creation of config file, it writes OpenRCT2 root folder as `game_path`.
Most likely caused by #1352 

Reproduction:
* Move or rename your old `config.ini`
* Launch OpenRCT2 to create a new one
* Unless you have copied necessary files to OpenRCT2 root it will crash with this error
image

Offtopic enhancment proposition - what if instead of creating a location link to RCT2 files, it would copy necessary files and folders into OpenRCT2 root, which would make `game_path` unnecessary?

### PR DESCRIPTION
**Pull request by mzmiric5**
…h rather than just for the folder

### CODE REVIEW

File: src/platform/windows.c [hunk 1]
```diff
@@ -101,6 +101,14 @@ int platform_directory_exists(const char *path)
 	return dwAttrib != INVALID_FILE_ATTRIBUTES && (dwAttrib & FILE_ATTRIBUTE_DIRECTORY);
 }
 
+int platform_original_game_data_exists(const char *path)
+{
+	char checkPath[MAX_PATH];
+	sprintf(checkPath, "%s%c%s%c%s", path, platform_get_path_separator(), "data", platform_get_path_separator(), "g1.dat");
+	DWORD dwAttrib = GetFileAttributes(checkPath);
+	return dwAttrib != INVALID_FILE_ATTRIBUTES;
```
Comment (IntelOrca) [inline src/platform/windows.c]: Can we use platform_file_exists instead?
