### PR TITLE
Fix #17390: Object selection ride tab uses wrong animations

### LINKED ISSUE #17390: Object Selection ride tab animations glitch when holding mouse button down on an inactive ride tab
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0-240-g9a244b1 (9a244b1 on develop) provided by GitHub

### Describe the issue

This was reported by Jettomukade on Discord.

In the object selection, when holding down the mouse button on an active tab, two ride tabs will play their animations, twice as fast and with possible out-of-bounds sprites.

Some refactoring is required to have support for more than 1 animated tab. Alternatively, fix this by _not_ playing the animation for the tab that is pressed but not active (other windows with animated tabs do this)

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Open the object selection
2. Click and hold down the mouse button on any of the other ride tabs
3. The tab animation now plays twice as fast, and may include random sprites

### Attachments

https://user-images.githubusercontent.com/9705046/173927771-279e7e53-46d7-4240-ae0b-db79e8c494e7.mov

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
The ride tab animations in the object selection window were defined incorrectly. The sequence appears to have been copied from the 'New Ride' window, but the definitions for the Research tab appear to not have been taken into account. Instead, there's an 'All' tab, which is compensated for, but everything is still off by one. Compare:

NewRide.cpp:
```cpp
    static constexpr int32_t TabAnimationLoops[] = {
        20, // TRANSPORT_TAB
        32, // GENTLE_TAB
        10, // ROLLER_COASTER_TAB
        72, // THRILL_TAB
        24, // WATER_TAB
        28, // SHOP_TAB
        16, // RESEARCH_TAB
    };
```

EditorObjectSelection.cpp (before this PR):
```cpp
    static constexpr int32_t window_editor_object_selection_animation_loops[] = {
        20, // All
        32, // Transport
        10, // Gentle
        72, // Coaster
        24, // Thrill
        28, // Water
        16, // Stall
    };
```

EditorObjectSelection.cpp (as of this PR):
```cpp
    static constexpr int32_t window_editor_object_selection_animation_loops[] = {
        20, // Transport
        32, // Gentle
        10, // Coaster
        72, // Thrill
        24, // Water
        28, // Stall
    };
```

The `window_editor_object_selection_animation_divisor` array was corrected analogously.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
NB: with #22345 in mind, I'd like to rework how these sub tabs work. They still exhibit strange behaviour when the mouse pointer is held down on the widget, which shows the limits of the current approach.

Should probably add a changelog entry before this is merged.

File: src/openrct2-ui/windows/EditorObjectSelection.cpp [hunk 1]
```diff
@@ -333,18 +332,17 @@ static std::vector<Widget> _window_editor_object_selection_widgets = {
...
-                if (!IsWidgetPressed(i))
-                    continue;
+            if (GetSelectedObjectType() != ObjectType::Ride)
+                return;
 
-                frame_no++;
-                if (frame_no >= window_editor_object_selection_animation_loops[i - WIDX_FILTER_RIDE_TAB_TRANSPORT])
-                    frame_no = 0;
+            if (_selectedSubTab == 0)
+                return;
```
Comment (Broxzier) [inline src/openrct2-ui/windows/EditorObjectSelection.cpp:339]: The reason for this condition isn't immediately clear when reading the code. Why is tab 0 skipped here? This is the "all" tab, if I get this right?

**Review by Broxzier — APPROVED** [review]
Tested and couldn't trigger the bug any more. Nice to see this fixed after so long! :D

File: src/openrct2-ui/windows/EditorObjectSelection.cpp (hunk 1 above)
Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/EditorObjectSelection.cpp:339]: Thanks. Yes, that is indeed the 'all rides' tab. This is completely refactored by #22352, though, so it won't be a problem for much longer.
