### PR TITLE
Fix #25735: Ride synchronisation z-check works incorrectly

### LINKED ISSUE #25735: Rides no not synchronize with stations 1 unit below their height
### Operating System

Any

### OpenRCT2 build

At least since 0.2.0

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

In vanilla rides will synchronize with stations that are at their height, one unit above, or one unit lower, but in Open they don't synch with stations one unit lower. The comment in the code does say they do, but the check for z-tolerence is wrong.

### Steps to reproduce

Test various setups of synchronizing rides with one unit height difference and see if they wait for each other.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by MarcelVos96**
Fixes #25735

I looked at the logic for the z-coordinate check from version 0.1.0 where it did still work as in vanilla and applied that to the current code.

Rides should synchronise with any station that is one unit below, at the same height, or one unit above.

### CODE REVIEW

**Comment by MarcelVos96** [comment]
Don't merge this yet, I have still found an inconsistency with the vanilla behaviour that I need to fix first.

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -5422,8 +5422,8 @@ TileElement* GetStationPlatform(const CoordsXYRangedZ& coords)
             /* Check if tileElement is a station platform. */
             if (!tileElement->AsTrack()->IsStation())
                 continue;
-
-            if (coords.baseZ > tileElement->GetBaseZ() || coords.clearanceZ < tileElement->GetBaseZ())
+            if (coords.baseZ - coords.clearanceZ > tileElement->GetBaseZ()
+                || coords.baseZ + coords.clearanceZ < tileElement->GetBaseZ())
```
Comment (mixiate) [inline src/openrct2/ride/Ride.cpp]:
```suggestion
            if (coords.baseZ > tileElement->GetBaseZ() || coords.clearanceZ < tileElement->GetBaseZ())
```

File: src/openrct2/ride/Ride.cpp [hunk 2]
```diff
@@ -5454,8 +5454,7 @@ static bool CheckForAdjacentStation(const CoordsXYZ& stationCoords, uint8_t dire
     {
         adjX += CoordsDirectionDelta[direction].x;
         adjY += CoordsDirectionDelta[direction].y;
-        TileElement* stationElement = GetStationPlatform(
-            { { adjX, adjY, stationCoords.z }, stationCoords.z + 2 * kCoordsZStep });
+        TileElement* stationElement = GetStationPlatform({ { adjX, adjY, stationCoords.z }, 2 * kCoordsZStep });
```
Comment (mixiate) [inline src/openrct2/ride/Ride.cpp]:
```suggestion
        TileElement* stationElement = GetStationPlatform(
            { adjX, adjY, stationCoords.z - 2 * kCoordsZStep, stationCoords.z + 2 * kCoordsZStep });
```

File: src/openrct2/ride/Vehicle.cpp [hunk 3]
```diff
@@ -1696,7 +1696,7 @@ static bool try_add_synchronised_station(const CoordsXYZ& coords)
         return false;
     }
 
-    TileElement* tileElement = GetStationPlatform({ coords, coords.z + 2 * kCoordsZStep });
+    TileElement* tileElement = GetStationPlatform({ coords, 2 * kCoordsZStep });
```
Comment (mixiate) [inline src/openrct2/ride/Vehicle.cpp]:
```suggestion
    TileElement* tileElement = GetStationPlatform(
        { coords.x, coords.y, coords.z - 2 * kCoordsZStep, coords.z + 2 * kCoordsZStep });
```

**Review by mixiate — COMMENTED** [review]
It needs to lower the base z by the same amount. The check in `GetStationPlatform` is otherwise the same already.

Based on the code from 0.1.0:
https://github.com/OpenRCT2/OpenRCT2/blob/6d1f732ed6f36c590c529402a5e241581bbd3245/src/openrct2/ride/ride.c#L8466-L8467

very simple test park:
[syncheighttest.zip](https://github.com/user-attachments/files/24442610/syncheighttest.zip)

File: src/openrct2/ride/Ride.cpp (hunk 2 above)
Comment (Gymnasiast) [reply src/openrct2/ride/Ride.cpp]: I should hope this doesn’t actually use tiny Z - all usages should have been refactored out and confined to import code. As such, `kCoordsZPerTinyZ` is the wrong constant to use.

File: src/openrct2/ride/Ride.cpp (hunk 1 above)
Comment (MarcelVos96) [reply src/openrct2/ride/Ride.cpp]: What you're suggesting here is changing it back to how it is currently, which does not work. 

What my check does is check if the height of the station minus the clearance (16 / 1 unit) is above the height of the station next to it (the adjacent station is more than 1 unit below it), or if the height of the station plus the clearance is below the height of the adjacent station (the adjacent station is more than 1 unit above it).

I do see the other changes as well and I'm not sure what exactly to make of it. The way this PR currently works is by passing the coordinates of the station and how much any adjacent stations may differ in height (the clearanceZ), and then it uses those two to check if the Z of the adjacent station is within the correct limits. I have done several tests just now and it matches vanilla behaviour in every test.

Some synchronization still works differently because OpenRCT2 is more liberal in when stations synchronize with respect to the X and Y coordinates, but I'm not touching that here, I'm only changing the Z-check.

**Comment by MarcelVos96** [comment]
It turns out that it did already work fine. One test suddenly showed very different behaviour from vanilla, and since you had already requested a review I wanted to quickly get in to say I needed to do more tests before it potentially got merged. The reason it behaved differently is that OpenRCT2 allows more horizontal separation than vanilla, which I forgot about for a second. Doing tests without any extended horizontal separation I get the exact same behaviour for the Z-check as in vanilla.

File: src/openrct2/ride/Ride.cpp (hunk 1 above)
Comment (mixiate) [reply src/openrct2/ride/Ride.cpp]: The CoordsXYRangedZ type is supposed to have absolute baseZ and clearanceZ values.
It's clearer, better type safety, better if something else needs to use `GetStationPlatform`

File: src/openrct2/ride/Ride.cpp (hunk 2 above)
Comment (mixiate) [reply src/openrct2/ride/Ride.cpp]: Oh well that's fine you can change it back to `2 * kCoordsZStep`. It's the same value.
`kCoordsZPerTinyZ` is already being used for that purpose elsewhere, that's where I got it from.

File: distribution/changelog.txt [hunk 4]
```diff
@@ -15,6 +15,7 @@
 - Fix: [#23519] Title sequence cannot open .sea scenarios from RCTC.
 - Fix: [#25237] Wrong colours on the Knight costume (original bug).
 - Fix: [#25712, #25727] Crash during startup from window list race condition.
+- Fix: [#25735] Ride synchronisation z-check works incorrectly.
```
Comment (Gymnasiast) [inline distribution/changelog.txt]: This needs rebasing, and moving up.

**Review by Gymnasiast — COMMENTED** [review]
Code LGTM. I haven’t tested it, but I trust you have done so.

This needs rebasing, its changelog updated and the network version bumped.

**Comment by MarcelVos96** [comment]
I did indeed test it when I originally made this PR, but I did some tests again and it seems to have stopped working. Need to look into that.

**Review by Gymnasiast — APPROVED** [review]

**Comment by MarcelVos96** [comment]
Nevermind, I accidentally had the wrong version loaded when doing the test that didn't work. I did some very extensive testing now and it works as it should.

I did switch to the correct branch before doing that failed test, but forgot to rebuild so I was working in the build of a different branch, hence why it didn't work.
