### PR TITLE
Fix #21959: No save prompt when starting a new game

### LINKED ISSUE #21959: "Save this before...?" message does not appear when selecting "New Game"
### Operating System

Linux Mint 21.3 Cinnamon

### OpenRCT2 build

OpenRCT2, v0.4.10

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

There is no prompt to the player to save the game if selecting "New Game" under the floppy disk dropdown, even if it does display a prompt for loading and quitting.

### Steps to reproduce

1. Open some scenario or save.
2. Play long enough that you get a prompt when attempting to load a new game.
3. Open the floppy disk menu and select "New Game" (and no prompt displays).

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by tmatale**
Resolves #21959 

Instead of directly linking to the new game menu, it will first ask the user if you want to save the game if necessary. The SaveBeforeNewGame functionality was already present.

### CODE REVIEW

File: src/openrct2-ui/windows/TopToolbar.cpp [hunk 1]
```diff
@@ -3251,15 +3249,6 @@ static Widget _topToolbarWidgets[] = {
         }
     };
 
-    static void ScenarioSelectCallback(const utf8* path)
-    {
-        WindowCloseByClass(WindowClass::EditorObjectSelection);
-        GameNotifyMapChange();
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/TopToolbar.cpp:3257]: These callbacks exist for scripting purposes. Are we sure they can just be removed?

Comment (Gymnasiast) [reply src/openrct2-ui/windows/TopToolbar.cpp:3257]: Quite sure they can’t.

Comment (tmatale) [reply src/openrct2-ui/windows/TopToolbar.cpp:3257]: The new callback it is calling [is referenced here](https://github.com/OpenRCT2/OpenRCT2/blob/cd528665e64d252dbfe754268432d32df569002a/src/openrct2/Game.cpp#L625-L632). The changes will call this instead of the callback in the TopToolbar. If this will still have an affect on scripting then I can cancel this PR but it looks like this callback is only referenced in the location I changed.

**Comment by KatieZeldaKat** [comment]
Would love if this fix was looked into again as it seems to have been marked stale.

File: src/openrct2-ui/windows/TopToolbar.cpp (hunk 1 above)
Comment (tupaschoal) [reply src/openrct2-ui/windows/TopToolbar.cpp:3257]: @tmatale's analysis seem correct. When in `PromptMode::SaveBeforeNewGame` the save dialog will eventually fall into `GameLoadOrQuitNoSavePrompt` which will call the aforementioned function

**Review by tupaschoal — APPROVED** [review]

**Comment by KatieZeldaKat** [comment]
Anything else need to be done (other than fixing the branch's conflicts) before this gets merged?

**Comment by tupaschoal** [comment]
LGTM, needs reassessment from either @AaronVanGeffen or @Gymnasiast

File: distribution/changelog.txt [hunk 2]
```diff
@@ -1,6 +1,7 @@
 0.4.15 (in development)
 ------------------------------------------------------------------------
 - Feature: [#15642] Track design placement can now use contruction modifier keys (ctrl/shift).
+- Fix: [#21959] "Save this before...?" message does not appear when selecting "New Game".
```
Comment (Gymnasiast) [inline distribution/changelog.txt:4]:
```suggestion
- Fix: [#21959] “Save this before...?” message does not appear when selecting “New Game”.
```

**Review by Gymnasiast — APPROVED** [review]

File: src/openrct2-ui/windows/TopToolbar.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2-ui/windows/TopToolbar.cpp:997]: Very well, I’ll go with that.
