### PR TITLE
Fix #18606: JSON objects do not take priority over DATs they supersede

### LINKED ISSUE #18606: DAT files take priority over Parkobj's using the same original ID.
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.2-167-gae9bf66 (ae9bf66 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When having a DAT file and a parkobj with the same original ID the original DAT file takes priority rather than the newer parkobj version. It should be the other way around so bugs, graphical issues, etc can be removed without needing to remove the DAT file manually.

### Steps to reproduce

Download the provided file in attachments, drop both in the objects folder. As you can see the original DAT file takes priority over the converted/edited file with the same original ID.

### Attachments

[Example.zip](https://github.com/OpenRCT2/OpenRCT2/files/10024689/Example.zip)

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/object/ObjectRepository.cpp [hunk 1]
```diff
@@ -419,6 +419,23 @@ class ObjectRepository final : public IObjectRepository
...
+            {
+                const auto& currentItem = _items[i];
+                if (currentItem.Generation == ObjectGeneration::DAT && currentItem.ObjectEntry == conflict->ObjectEntry)
+                {
+                    Console::Error::WriteLine(
+                        "Object conflict: '%s' was overridden by '%s'", conflict->Path.c_str(), item.Path.c_str());
+                    const auto id = currentItem.Id;
+                    _items[i] = item;
+                    _items[i].Id = id;
+                    return true;
```
Comment (Gymnasiast) [inline src/openrct2/object/ObjectRepository.cpp:435]: Should also set _newItemMap.

File: src/openrct2/object/ObjectRepository.cpp [hunk 2]
```diff
@@ -419,6 +419,23 @@ class ObjectRepository final : public IObjectRepository
         {
             conflict = FindObject(item.Identifier);
         }
+        // When there is a conflict between a DAT file and a JSON file, the JSON should take precedence.
+        if (conflict != nullptr && item.Generation == ObjectGeneration::JSON && conflict->Generation == ObjectGeneration::DAT)
+        {
+            for (size_t i = 0; i < _items.size(); i++)
```
Comment (IntelOrca) [inline src/openrct2/object/ObjectRepository.cpp:425]: Can you use `conflict->Id`  to get the index rather than having to loop through the list?

Comment (Gymnasiast) [reply src/openrct2/object/ObjectRepository.cpp:425]: I’ll try that.

**Review by IntelOrca — APPROVED** [review]
