### PR TITLE
 Fix #5261 pasting and deleting signs

### LINKED ISSUE #5261: Deleting the sign after copy/pasting it will crash the game
OS: Windows 7
Version: 0.0.7
Build: f6f6d27

If you open up a park then build a sign and then copy and paste it onto another tile. Deleting either copied one or original one will cause the game to crash. It will still crash even if you dont use the tile inspector to delete the sign.

- [N/A ] Reproducible in RCT2 (vanilla)?
- [ both] Multiplayer?

**Steps to reproduce:**
1. Open up any park
2.  Build any sign on any path.
3. Open up tile inspector and click on the signs
4. Click Copy
5. Click Paste on any other tile
6. Delete either one of the signs, and the game will crash.

untitled

### PR DESCRIPTION
**Pull request by Broxzier**
Previously banners could be copied and pasted using the tile inspector, causing the pasted banner to refer to the same banner entry, which in turn can refer to the same user string.

This PR fixes this behaviour by creating a new banner (and possibly user string too) when pasting a banner, and when loading a saved game.

### CODE REVIEW

File: src/openrct2/world/TileInspector.cpp [hunk 1]
```diff
@@ -285,6 +288,68 @@ sint32 tile_inspector_paste_element_at(sint32 x, sint32 y, rct_tile_element elem
 
     if (flags & GAME_COMMAND_FLAG_APPLY)
     {
+        // Check if the element to be pasted refers to a banner index
+        uint8                     bannerIndex = BANNER_NULL;
+        const rct_scenery_entry * entry;
+        switch (tile_element_get_type(&element))
+        {
+        case TILE_ELEMENT_TYPE_WALL:
```
Comment (Gymnasiast) [inline src/openrct2/world/TileInspector.cpp]: We have `tile_element_get_banner_index()` for this sort of thing.

Comment (Broxzier) [reply src/openrct2/world/TileInspector.cpp]: I must have overlooked that function, thanks for pointing it out.
