### PR TITLE
Fix divide by zero when there is no scenery

### LINKED ISSUE #24354: [11aed9] openrct2.exe: OpenRCT2::Ui::Windows::SceneryWindow::OnPrepareDraw
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIxMWFlZDk5MDdiNTYzYzljOTU3Y2NmNTM4ODUxOTdmNDYwMWUwZTU2YzY1Yjc2NGI4ZTdhNDUxY2FlYWI3ODQyIiwidHgiOjMxODc2fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=11aed9907b563c9c957ccf53885197f4601e0e56c65b764b8e7a451caeab7842&amp;_tx=7c84&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Thu May 08 2025 07:25:00 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\dltmd\OneDrive\Documents\OpenRCT2\crash\6f0d1c8b-2027-4338-aa5f-217a7fe79a95.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                099791ba76 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x00007FF7D9BFE467</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_INT_DIVIDE_BY_ZERO</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.22 (099791ba76 on develop) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>03000000-daae-d10d-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2::Ui::Windows::SceneryWindow::OnPrepareDraw</code> 
                                <code>WindowDrawSingle</code> 
                                <code>OpenRCT2::WindowDrawCore</code> 
                                <code>OpenRCT2::WindowDraw</code> 
                                <code>invoke</code> 
                                <code>std::_Func_impl_no_alloc&lt;`OpenRCT2::WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,OpenRCT2::WindowBase *&gt;::_Do_call</code> 
                                <code>OpenRCT2::WindowVisitEach(std::function&lt;void __cdecl(OpenRCT2::WindowBase *)&gt;)</code> 
                                <code>OpenRCT2::WindowDrawAll</code> 
                                <code>OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks</code> 
                                <code>OpenRCT2::Drawing::InvalidationGrid::traverseDirtyCells&lt;`OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks&#39;::`2&#39;::&lt;lambda_1&gt; &gt;</code> 
                                <code>OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks</code> 
                                <code>OpenRCT2::Drawing::X8DrawingEngine::PaintWindows</code> 
                                <code>OpenRCT2::Paint::Painter::Paint</code> 
                                <code>OpenRCT2::Context::Draw</code> 
                                <code>OpenRCT2::Context::RunVariableFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::Launch</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>intdiv</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> OpenRCT2::Ui::Windows::SceneryWindow::OnPrepareDraw WindowDrawSingle OpenRCT2::WindowDrawCore OpenRCT2::WindowDraw invoke std::_Func_impl_no_alloc&lt;`OpenRCT2::WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,OpenRCT2::WindowBase *&gt;::_Do_call OpenRCT2::WindowVisitEach(std::function&lt;void __cdecl(OpenRCT2::WindowBase *)&gt;) OpenRCT2::WindowDrawAll OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks OpenRCT2::Drawing::InvalidationGrid::traverseDirtyCells&lt;`OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks&#39;::`2&#39;::&lt;lambda_1&gt; &gt; OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks OpenRCT2::Drawing::X8DrawingEngine::PaintWindows OpenRCT2::Paint::Painter::Paint OpenRCT2::Context::Draw OpenRCT2::Context::RunVariableFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### PR DESCRIPTION
**Pull request by garrettleach**
Other places in the code guard against zero rows but this line does not and it appears to have caused a divide by zero in at least one crashdump. Fix #24354

### CODE REVIEW

**Comment by fivemeyestore** [comment]
Excellent contribution to open source! The community will benefit greatly from this.

File: src/openrct2-ui/windows/Scenery.cpp [hunk 1]
```diff
@@ -641,7 +641,12 @@ namespace OpenRCT2::Ui::Windows
         {
             // Minimum window height: title, one scenery button, status bar, padding
             _actualMinHeight = getTitleBarTargetHeight() + SCENERY_BUTTON_HEIGHT + kDescriptionHeight + 2 * kTabMargin;
-            _actualMinHeight += static_cast<int32_t>(1 + (_tabEntries.size() / GetMaxTabCountInARow())) * TabHeight;
+            int32_t fullRows = 0;
+            if (GetMaxTabCountInARow() > 0)
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/Scenery.cpp:645]: Let’s put the result of `GetMaxTabCountInARow()` into a variable, rather than calculating it twice 99.9% of the time.

Comment (garrettleach) [reply src/openrct2-ui/windows/Scenery.cpp]: For sure

**Review by Gymnasiast — APPROVED** [review]
Code LGTM. Could you add a changelog entry?

**Review by AaronVanGeffen — COMMENTED** [review]
I think this entire problem could be resolved more elegantly by instead adjusting `GetMaxTabCountInARow` to never return 0.

Consider:
```diff
        int32_t GetMaxTabCountInARow()
        {
            int32_t tabEntries = static_cast<int32_t>(_tabEntries.size());
-           return std::min(tabEntries, MaxTabsPerRow);
+           return std::clamp(tabEntries, 1, MaxTabsPerRow);
        }
```

**Comment by garrettleach** [comment]
I think you are right. That function doesn't have a lot of meaning if it can even return 0.

**Comment by AaronVanGeffen** [comment]
Alright, could you amend the PR then?

**Review by Gymnasiast — APPROVED** [review]

**Review by AaronVanGeffen — APPROVED** [review]
