### PR TITLE
adjust openrct2.d.ts to changes in FootpathPlaceArgs

### LINKED ISSUE #25464: FootpathPlaceArgs and FootpathLayoutPlaceArgs interfaces do not match arguments used in game
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.28 (5847457 on HEAD)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The required args of `FootpathPlaceArgs` and `FootpathLayoutPlaceArgs` in game are changed in v0.4.28 but their interfaces in [openrct2.d.ts](https://github.com/OpenRCT2/OpenRCT2/blob/v0.4.28/distribution/openrct2.d.ts#L838) have not changed to reflect this.

Specifically, this part in both interfaces:
```typescript
 interface FootpathPlaceArgs extends GameActionArgs {
    ...
    /**
     * - `0`: Flat
     * - `4`, `5`, `6`, `7`: Slope direction + 4
     */
    slope: number;
}
```
is now invalid, being replaced with `slopeType` (0 for flat, 1 for sloped) and `slopeDirection` (0, 1, 2, 3).

This change breaks plugins that use `FootpathPlaceArgs` or `FootpathLayoutPlaceArgs`. I don't know why this change was made, but I'd suggest that `slope` still be accepted as a legacy argument even if it should be removed from openrct2.d.ts.

### Steps to reproduce

1. In v0.4.27, run `executeAction` with `action: "footpathplace"` or `action: "footpathlayoutplace"` and args including `slope` but not `slopeType` and `slopeDirection`, verifying that the path can be placed.
2. In v0.4.28, try again with the same args and observe that the game considers the args invalid.

### Attachments

In v0.4.28, I ran `executeAction(action: "footpathlayoutplace",...)` with args:
```
{ x: 4320, 
  y: 352,
  z: 112,
  edges: 2,
  object: 0,
  railingsObject: 0,
  slope: 5,
  constructFlags: 0,
  flags: 136 }
```
and received "Error: Invalid action parameters." These equivalent args had no such error:
```
{ x: 4320, 
  y: 352,
  z: 112,
  edges: 2,
  object: 0,
  railingsObject: 0,
  slopeDirection: 1,
  slopeType: 1,
  constructFlags: 0,
  flags: 136 }
```

### PR DESCRIPTION
**Pull request by Sadret**
Replaces `slope` with `slopeType` and `slopeDirection`.
Closes #25464.

### CODE REVIEW

**Review by Gymnasiast — APPROVED** [review]

**Review by AaronVanGeffen — APPROVED** [review]

File: distribution/openrct2.d.ts [hunk 1]
```diff
@@ -844,11 +844,10 @@ declare global {
...
         railingsObject: number;
-        /**
-         * - `0`: Flat
-         * - `4`, `5`, `6`, `7`: Slope direction + 4
-         */
-        slope: number;
+        /** 0 if flat, 1 if sloped */
+        slopeType: number; // 
+        /** direction if sloped, otherwise ignored */
+        slopeDirection: number;
```
Comment (Basssiiie) [inline distribution/openrct2.d.ts]:
```suggestion
        slopeDirection: Direction;
```
Since I assume the possible numbers are 0-3?

Comment (AaronVanGeffen) [reply distribution/openrct2.d.ts]: You're right, yes. Looks like `slopeDirection_set` will technically let you set any `uint8_t` value, though... Something to get more defensive about.

Comment (Basssiiie) [reply distribution/openrct2.d.ts]: I believe this interface refers to [this](https://github.com/OpenRCT2/OpenRCT2/blob/d4302bc6c9922332d3dbd8a1837480eb831cfa69/src/openrct2/actions/footpath/FootpathPlaceAction.cpp#L54-L63) "parser" though. Still allow any `uint8_t` but I believe few if not none of the game actions are validated in any way outside of "it fits the type". Ideally, `slopeDirection` should also be optional, which isn't the case currently as all fields in game actions are required at the moment.

All fruitful ideas for another PR, potentially. 😄

Comment (Sadret) [reply distribution/openrct2.d.ts]: I am not a big fan of number unions, but I will change it.

**Comment by Sadret** [comment]
I uploaded via GitHub editor, please squash before merge.

**Review by Basssiiie — APPROVED** [review]
