### PR TITLE
Fix #23508: RideConstruction and Footpath windows racing to set the VirtualFloor

### LINKED ISSUE #23508: Flickering simultaneous VirtualFloors from Ride and Footpath Construction windows
### Operating System

Linux

### OpenRCT2 build

25ac4cf5d688328703fc3d298ad742345073e6b5

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When having ride and footpath construction windows open and raising the to-be-placed footpath tile with Shift (nd moving the cursor up), a VirtualFloor will be shown not only for the footpath tile, but also for the ride construction.  
Some flickering is going on also.

Expected behavior: Show only the VirtualFloor associated with the footpath (as that's the thing you're gonna build when clicking anywhere on the map).

Happened regardless of the renderer (software / openGL).

### Steps to reproduce

1. Open some park.
2. Start building a tracked ride.
3. With the ride construction still open, open footpath construction (choose single tile mode)
4. Move the cursur somewhere on te map (to place a path tile), hold shift and raise the footpath
5. Observe that a VirtualFloor is shown for both the ride and the footpath.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by zzril**
This PR disables the `VirtualFloor` for the `RideConstruction` window when `MAP_SELECT_FLAG_ENABLE` is set, thus preventing double virtual floors to be shown e. g. from the ride construction and footpath windows.

Closes #23508

### CODE REVIEW

File: src/openrct2/paint/VirtualFloor.cpp [hunk 1]
```diff
@@ -195,7 +196,7 @@ bool VirtualFloorTileIsFloor(const CoordsXY& loc)
         return true;
     }
 
-    if (gMapSelectFlags & MAP_SELECT_FLAG_ENABLE_CONSTRUCT)
+    if (gMapSelectFlags & MAP_SELECT_FLAG_ENABLE_CONSTRUCT && !isToolActive(WindowClass::Footpath))
```
Comment (AaronVanGeffen) [inline src/openrct2/paint/VirtualFloor.cpp:199]: This seems a bit hacky. Any particular reason this isn't at the calling side?

Comment (zzril) [reply src/openrct2/paint/VirtualFloor.cpp]: That was more of a test whether I was on the right track. Pushed it rather out of habit.

I have now changed it to simply fail early in case `MAP_SELECT_FLAG_ENABLE` is set, but the current tile is not close to the selection. That appears to do the trick. (Checked with ride, footpath, small scenery and large scenery, and all combinations of the last 3 and an open ride construction window.)

Will do the clean up tomorrow, after I get some sleep.

Do you prefer keeping both PRs separate or shall I merge this one into #23502 ?

Comment (AaronVanGeffen) [reply src/openrct2/paint/VirtualFloor.cpp]: We can merge them separately at this point. Different issues as well, after all.

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 2]
```diff
@@ -2213,7 +2214,7 @@ namespace OpenRCT2::Ui::Windows
         {
             // If the scenery tool is active, we do not display our tiles as it
             // will conflict with larger scenery objects selecting tiles
-            if (isToolActive(WindowClass::Scenery))
+            if (gMapSelectFlags & MAP_SELECT_FLAG_ENABLE)
```
Comment (zzril) [inline src/openrct2-ui/windows/RideConstruction.cpp:2217]: Not sure if that change is correct, need some testing still.

Comment (zzril) [reply src/openrct2-ui/windows/RideConstruction.cpp:2217]: Oh, this is responsible for keeping the tiles of the provisional piece marked with a yellow border.  
Didn't find any negative interference with the footpath tool. (When playing a provisional footpath in one of the tiles of the provisional track piece, the footpath tile gets a white border while the others remain yellow. That seams reasonable.) So I think this can stay as it was. Reverting all my changes in this line.

File: src/openrct2/paint/VirtualFloor.cpp [hunk 3]
```diff
@@ -187,12 +187,13 @@ bool VirtualFloorTileIsFloor(const CoordsXY& loc)
...
-        && loc.y >= gMapSelectPositionA.y - _virtualFloorBaseSize && loc.x <= gMapSelectPositionB.x + _virtualFloorBaseSize
-        && loc.y <= gMapSelectPositionB.y + _virtualFloorBaseSize)
+    // and if the current tile is near or on them
+    // (short-circiut to false otherwise - we don't want to show a second
+    //  virtual floor from e. g. an open ride construction window)
+    if (gMapSelectFlags & MAP_SELECT_FLAG_ENABLE)
     {
-        return true;
+        return loc.x >= gMapSelectPositionA.x - _virtualFloorBaseSize && loc.y >= gMapSelectPositionA.y - _virtualFloorBaseSize
+            && loc.x <= gMapSelectPositionB.x + _virtualFloorBaseSize && loc.y <= gMapSelectPositionB.y + _virtualFloorBaseSize;
```
[the remark this answers is not in the document]
Comment (zzril) [reply src/openrct2/paint/VirtualFloor.cpp]: That does make it more readable indeed. Changed it.

File: src/openrct2/paint/VirtualFloor.cpp [hunk 4]
```diff
@@ -31,6 +31,7 @@
 using namespace OpenRCT2;
 
 static uint16_t _virtualFloorBaseSize = 5 * 32;
+static CoordsXY _virtualFloorBaseSizeXY = { _virtualFloorBaseSize, _virtualFloorBaseSize };
```
Comment (AaronVanGeffen) [inline src/openrct2/paint/VirtualFloor.cpp:34]:
```suggestion
static constexpr uint16_t kVirtualFloorBaseSize = 5 * kCoordsXYStep;
static constexpr CoordsXY kVirtualFloorBaseSizeXY = { kVirtualFloorBaseSize, kVirtualFloorBaseSize };
```

File: src/openrct2/paint/VirtualFloor.cpp [hunk 5]
```diff
@@ -187,21 +188,21 @@ bool VirtualFloorTileIsFloor(const CoordsXY& loc)
     }
 
     // Check if map selection (usually single tiles) are enabled
-    //  and if the current tile is near or on them
-    if ((gMapSelectFlags & MAP_SELECT_FLAG_ENABLE) && loc.x >= gMapSelectPositionA.x - _virtualFloorBaseSize
-        && loc.y >= gMapSelectPositionA.y - _virtualFloorBaseSize && loc.x <= gMapSelectPositionB.x + _virtualFloorBaseSize
-        && loc.y <= gMapSelectPositionB.y + _virtualFloorBaseSize)
+    // and if the current tile is near or on them
+    // (short-circiut to false otherwise - we don't want to show a second
```
Comment (Gymnasiast) [inline src/openrct2/paint/VirtualFloor.cpp:192]:
```suggestion
    // (short-circuit to false otherwise - we don't want to show a second
```

**Comment by Gymnasiast** [comment]
Looks good code-wise - just find a typo. Could you rebase this PR (taking care to properly update the changelog)? I’ll take it for a spin afterwards.

**Review by Gymnasiast — APPROVED** [review]
