### PR TITLE
Fix #26425: Benches don't reduce watching spots from 4 to 2 while other path additions do

### LINKED ISSUE #26425: There are 4 watching spots on path tiles with benches and 2 for other additions (should be the other way around)
### Operating System

Any

### OpenRCT2 build

0.5.0

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When watching a ride or scenery there are by default 4 spots available per path tile, but if there's a bench on the path then there are only 2 spots. Other path additions don't impact the 4 spots.

That's how it works in vanilla, but Open does it the wrong way around and reduces to 2 spots if the addition is NOT a bench.

OpenRCT2

Image

Vanilla

Image

### Steps to reproduce

Recreate the screenshots

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by MarcelVos96**
Fixes #26425

### CODE REVIEW

File: src/openrct2/entity/Guest.cpp [hunk 1]
```diff
@@ -5652,7 +5652,7 @@ namespace OpenRCT2
                     return;
                 }
 
-                if (!(pathAddEntry->flags & PATH_ADDITION_FLAG_IS_BENCH))
+                if ((pathAddEntry->flags & PATH_ADDITION_FLAG_IS_BENCH))
```
Comment (duncanspumpkin) [inline src/openrct2/entity/Guest.cpp:5655]: Image
This is the assembly `ebp` is the `position_free` variable. If PATH_ADDITION_FLAG_IS_BENCH is set it selects 9. Looks like this change is correct.

**Review by duncanspumpkin — APPROVED** [review]

File: src/openrct2/entity/Guest.cpp (hunk 1 above)
Comment (ghost) [reply src/openrct2/entity/Guest.cpp:5655]: I have a question: since OpenRCT2 was made by converting assembly of vanilla to C++, how is it possible it still is not having identical behavior as vanilla?
Is this because not every assembly part is converted and other things are filled in without comparing to vanilla or are these just assembly -> C++ conversion bugs/mistakes?

Comment (MarcelVos96) [reply src/openrct2/entity/Guest.cpp:5655]: These are all mistakes from the code was originally converted to c++. While they did plenty of testing I assume, it was unreasonable to expect them to test every little detail as that takes forever, so mistakes like this are easily missed.
