### PR TITLE
Fix #21145, #21158: Keep handles for intervals stable and resolve crash

### LINKED ISSUE #21145: Plugin: clearTimeout might clear wrong timeout
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.7-3-g1d8dc11 (1d8dc11 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Steps to reproduce

```js
    var handle = context.setInterval(function() {
        console.log("foo");
        context.clearInterval(handle);
        context.setTimeout(function() {
            console.log("bar");
        }, 1);
    }, 1);
```

### Describe the issue

See code above.

Expected output is `foo bar`. Explanation:
Create an interval. In its first run, it prints 'foo', then clears itself and creates a timeout, which prints 'bar'.

Actual output is `foo`. Explanation:
When the interval is cleared, [its handle is freed](https://github.com/OpenRCT2/OpenRCT2/blob/1d8dc111f1d9814be2a4c9fd8814fb78e42a742c/src/openrct2/scripting/ScriptEngine.cpp#L1636) and then [reused](https://github.com/OpenRCT2/OpenRCT2/blob/1d8dc111f1d9814be2a4c9fd8814fb78e42a742c/src/openrct2/scripting/ScriptEngine.cpp#L1613) when the timeout is created. After the interval call has finished, the handle now points to the timeout and not the interval. Thus, [it is cleaned up](https://github.com/OpenRCT2/OpenRCT2/blob/1d8dc111f1d9814be2a4c9fd8814fb78e42a742c/src/openrct2/scripting/ScriptEngine.cpp#L1667).

### Notes

Testing this in the console will crash the game with a dump. This happens since in the console there is no plugin owner. It is not related to the bug reported here.

### LINKED ISSUE #21158: [Plugin] `context.setTimeout()` crashes debug builds with read access violations
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.7, 296e8cd

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Using `context.setTimeout()` seems to crash debug builds with read access violations in certain cases, making debugging impossible in combination with plugins that use this API.

### Steps to reproduce

1. Get a plugin that uses `context.setTimeout()`, like [Sadret's Tetris plugin](https://openrct2plugins.org/plugin/R_kgDOLBRY8A/openrct2-rctris)
2. Start a debug build.
3. Start a Tetris game with the plugin.
4. Experience the read access violation crash within a second or two.

### Attachments

A screenshot of the crash in Visual Studio. Things that might be of note are the stack trace and the locals. It seems to crash in shared_ptr internal code when incrementing refs? In the locals window, the `_Uses` = `???` and it stayed like that even when I inspected the specific fields.

image

### PR DESCRIPTION
**Pull request by ZehMatt**
For iterator stability I decided to use std::map instead, the handles will be also no longer recycled and won't keep dead intervals in memory anymore. I've tested how V8 deals with this and it doesn't re-use handles as well.

Closes #21145, Closes #21158

### CODE REVIEW

**Comment by ZehMatt** [comment]
This doesn't work correctly either, need to come up with a different solution.

**Comment by ZehMatt** [comment]
Looks like a false alarm, full rebuild did solve it, the standard does promise that iterators don't invalidate on insert so that was weird.

File: src/openrct2/scripting/ScriptEngine.cpp [hunk 1]
```diff
@@ -1597,44 +1597,48 @@ void ScriptEngine::SetParkStorageFromJSON(std::string_view value)
...
+    _nextIntervalHandle++;
+
+    // In case of overflow start from 1 again
+    if (_nextIntervalHandle == 0)
     {
-        if (!_intervals[i].IsValid())
-        {
-            return static_cast<IntervalHandle>(i + 1);
-        }
+        _nextIntervalHandle = 1;
```
Comment (tupaschoal) [inline src/openrct2/scripting/ScriptEngine.cpp:1606]: Would it work to just do ``
```c++
IntervalHandle ScriptEngine::AllocateHandle()
{
    // In case of overflow start from 1 again
    _nextIntervalHandle = std::max(_nextIntervalHandle++, 1)
    return _nextIntervalHandle;
}
```

File: src/openrct2/scripting/ScriptEngine.cpp [hunk 2]
```diff
@@ -1645,42 +1649,47 @@ void ScriptEngine::UpdateIntervals()
...
 
-                interval.LastTimestamp = timestamp;
-                if (!interval.Repeat)
-                {
-                    RemoveInterval(nullptr, interval.Handle);
-                }
+            interval.LastTimestamp = timestamp;
+            if (!interval.Repeat)
+            {
+                _intervals.erase(it);
```
Comment (tupaschoal) [inline src/openrct2/scripting/ScriptEngine.cpp:1674]: Doesn't `erase` return the next iterator after the one removed?
I think the code could be just:

```c++
    for (auto it = _intervals.begin(), it != _intervals.end();)
    {
        auto& interval = it->second;
        if (timestamp >= interval.LastTimestamp + interval.Delay)
        {
            ExecutePluginCall(interval.Owner, interval.Callback, {}, false);
            interval.LastTimestamp = timestamp;
            if (!interval.Repeat)
            {
                it = _intervals.erase(it);
            }
            else
            {
                ++it;
            }
        }
    }
```

File: src/openrct2/scripting/ScriptEngine.cpp [hunk 3]
```diff
@@ -1645,42 +1649,47 @@ void ScriptEngine::UpdateIntervals()
...
+        auto& interval = it->second;
+
         if (interval.Owner == plugin)
         {
-            interval = {};
+            it = _intervals.erase(it);
+            continue;
         }
+
+        it++;
```
Comment (tupaschoal) [inline src/openrct2/scripting/ScriptEngine.cpp:1692]:
```suggestion
            continue;
        }
        else
        {
            it++;
        }
```
Would this be easier to understand? Not sure, but it's how I added the suggestion above.

File: src/openrct2/scripting/ScriptEngine.cpp (hunk 2 above)
Comment (ZehMatt) [reply src/openrct2/scripting/ScriptEngine.cpp:1674]: That will cause an infinite loop, I opted to just use a secondary variable so it doesn't need to increment the iterator in two places.

File: src/openrct2/scripting/ScriptEngine.cpp (hunk 3 above)
Comment (ZehMatt) [reply src/openrct2/scripting/ScriptEngine.cpp]: I'm not torn about this, a habit of mine to just bail as early as possible, it won't make a difference code-gen wise. Changed it.

File: src/openrct2/scripting/ScriptEngine.cpp (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/scripting/ScriptEngine.cpp]: Good point.

**Review by tupaschoal — APPROVED** [review]
Code seems ok

File: src/openrct2/scripting/ScriptEngine.cpp (hunk 2 above)
Comment (ZehMatt) [reply src/openrct2/scripting/ScriptEngine.cpp:1669]: It wouldn't increment the iterator if it hasn't reached the delay you only accounted for the nested condition which would require another else for `if (timestamp >= interval.LastTimestamp + interval.Delay)`. I left it as is for now, iterators in c++ are quite annoying at times.
