### PR TITLE
Fix #23781: Changing weather does not update state for next weather

### LINKED ISSUE #23781: Changing weather does not appear to fix the weather issues of save-game made in v0.4.19 “Just a harmless little bunny”
### Operating System

Windows 10 Pro

### OpenRCT2 build

OpenRCT2, v0.4.19.1 (455f22bbca) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

When playing in version 0.4.19 I found that my park was having bad thunderstorm weather all the time. Today I found that there was a new version available that had fixed said issue and told me to fix the save game by changing the weather to another type in the cheats menu. However this does not appear to resolve the issue as it turns to thunderstorm after a short while. When it does so the weather UI seems to indicate sunny.

### Steps to reproduce

1. Open provided park save file.
2. Unpause the game.
3. Open Cheats window, go to weather tab and change to Sunny.
4. Set speed to maximum and wait till around the 30th of April.
5. Observe that the weather is now thunderstorm and the UI reports sunny weather.

[Three Monkeys Park - Pretty 17.zip](https://github.com/user-attachments/files/18648952/Three.Monkeys.Park.-.Pretty.17.zip)

### Attachments

Image

### PR DESCRIPTION
**Pull request by ZehMatt**
The actual issue that the weather never changes is that the variable level contains garbage so its never able to reach the condition for the next weather to activate. 

It seems that the cheat also had the issue that it would not update the next weather state which is decided on the current one so that was sort of buggy, now the cheat properly selects the next weather when its forced.

Close #23781

### CODE REVIEW

File: src/openrct2/world/Climate.cpp [hunk 1]
```diff
@@ -223,7 +223,7 @@ void ClimateForceWeather(WeatherType weather)
     gameState.ClimateCurrent.Temperature = pattern.baseTemperature + trait.temperatureDelta;
     gameState.ClimateUpdateTimer = 1920;
 
-    ClimateUpdate();
+    ClimateDetermineFutureWeather(ScenarioRand());
```
Comment (AaronVanGeffen) [inline src/openrct2/world/Climate.cpp:226]: Admittedly I was slightly taken aback by this PR. From my testing, I was under the impression that this wouldn't require any additional changes, but it clearly you've reached a different conclusion.

This change forces the future weather to be updated, which definitely gets rid of any nasty values present. I was under the impression the existing `ClimateUpdate` also took care of that, but it looks like its call to `ClimateDetermineFutureWeather` is guarded to only be called every few ticks.

Conversely, `ClimateUpdate` takes care of more business logic, such as lightning/thunder effects. However, `gameStateUpdateLogic` already calls it every tick, so I think this replacement is fine.

File: src/openrct2/world/Climate.cpp [hunk 2]
```diff
@@ -311,8 +311,8 @@ static void ClimateDetermineFutureWeather(uint32_t randomValue)
     // Generate a random index with values 0 up to randomBias-1
     // and choose weather from the distribution table accordingly
     const auto& pattern = kClimatePatterns[EnumValue(gameState.Climate)][month];
-    size_t randomIndex = ((randomValue % 256) * pattern.randomBias) / 256;
-    auto nextWeather = pattern.distribution[randomIndex];
+    const auto randomIndex = ((randomValue % 256) * pattern.randomBias) / 256;
+    const auto nextWeather = pattern.distribution[randomIndex];
```
Comment (AaronVanGeffen) [inline src/openrct2/world/Climate.cpp:315]: Could you elaborate why you changed this back to `auto`? I get the added `const`ness, but was under the impression it needed to be made unsigned, explicitly.

Comment (Gymnasiast) [reply src/openrct2/world/Climate.cpp:315]: I was wondering that as well, considering line +314 using `auto` caused the corruption.

Also, maybe we should add an `assert` here to make sure it’s actually a valid value?

File: src/openrct2/world/Climate.cpp (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/world/Climate.cpp:226]: The problem is that with those garbage values set it would never reach into a call to ClimateDetermineFutureWeather, also when cheats force the state it should be doing the same as when it would switch the weather which always decides the next one. This cheat just now sets the next cycle as it should have been.

File: src/openrct2/world/Climate.cpp (hunk 2 above)
Comment (ZehMatt) [reply src/openrct2/world/Climate.cpp:315]: Following should illustrate how the problem happened.
```cpp
uint32_t randValue = 0xF1F2F3F4;       // 11110001111100101111001111110100, sign bit set.
int32_t inputValue = randValue;        // Becomes negative due to the sign bit, this is where the issue started, the compiler did not warn about passing uint32_t as int32_t to the function.
int32_t moduloRes = inputValue % 256;  // Remains negative.
int32_t biasRes = moduloRes * bias;    // Bias is quite small so good chance it remains negative.
int32_t final = biasRes / 256;         // If negative it will remain negative.
```

**Review by AaronVanGeffen — APPROVED** [review]

**Comment by Gymnasiast** [comment]
I do hope this was tested extensively to check if it didn’t accidentally re-introduce the bug?

**Comment by AaronVanGeffen** [comment]
> I do hope this was tested extensively to check if it didn’t accidentally re-introduce the bug?

Yes, I did my best. No worries.
