### PR TITLE
Fix #9859. Actually keep the loading of a track design with try.

### LINKED ISSUE #9859: BACKTRACE ce47e7 TD6Importer::Load
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/ce47e7889a0d3d76bd9727ad4e4be42a9f5a804b37820649c66ec6f224ce8e27?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Aug 12 2019 03:50:18)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_screenshot.png:</strong> C:\\Users\\Andro\\Documents\\OpenRCT2\\screenshot\\Unnamed park 2019-08-12 11-50-19.png: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Andro\\Documents\\OpenRCT2\\ed2eb984-4fc0-4444-b11d-584d3454844c.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Andro\\Documents\\OpenRCT2\\ed2eb984-4fc0-4444-b11d-584d3454844c.sv6.gz: <em>1</em><br><strong>commit:</strong> 056ebc2: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>unhandled-exception</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>TD6Importer::Load -> track_design_open -> TrackDesignFileIndex::Create -> FileIndex<TrackRepositoryItem>::BuildRange -> std::_Func_impl_no_alloc<std::_Binder<std::_Unforced,void ( FileIndex<scenario_index_entry>::*)(int,FileIndex<scenario_index_entry>::ScanResult const &,unsigned __int64,unsigned __int64,std::vector<scenario_index_entry,std::allocator<scenario_index_entry> > &,std::atomic<unsigned __int64> &,std::mutex &)const ,FileIndex<scenario_index_entry> const *,int &,std::reference_wrapper<FileIndex<scenario_index_entry>::ScanResult const >,unsigned __int64 &,unsigned __int64,std::reference_wrapper<std::vector<scenario_index_entry,std::allocator<scenario_index_entry> > >,std::reference_wrapper<std::atomic<unsigned __int64> >,std::reference_wrapper<std::mutex> >,void>::_Do_call -> JobPool::ProcessQueue -> std::_LaunchPad<std::unique_ptr<std::tuple<void ( JobPool::*)(void),JobPool *>,std::default_delete<std::tuple<void ( JobPool::*)(void),JobPool *> > > >::_Go -> std::_Pad::_Call_func -> invoke_thread_procedure( -> thread_start<unsigned int (*)(void *)></code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Mistake whilst implementing track desing importer and changing where code that could throw.

### CODE REVIEW

File: src/openrct2/ride/TrackDesign.cpp [hunk 1]
```diff
@@ -569,9 +569,9 @@ rct_string_id TrackDesign::CreateTrackDesignScenery()
 std::unique_ptr<TrackDesign> track_design_open(const utf8* path)
 {
     auto trackImporter = TrackImporter::Create(path);
```
Comment (ZehMatt) [inline src/openrct2/ride/TrackDesign.cpp]: You can also move this inside the try block
