### PR TITLE
Fix #14003: NPE in TryReconnectBoatToTrack()

### LINKED ISSUE #14003: [b4ecab] openrct2.exe: Vehicle::TryReconnectBoatToTrack, Vehicle::UpdateMotionBoatHire, Vehicle::Update, OpenRCT2::GameState:...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/b4ecab38275d1cd653997808f5507ed9736f023022078ea097fac7f66d19b5f1">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Administrator\Documents\CS2\\315fc0d6-f667-46ad-878d-9fa89499507b.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Administrator\Documents\CS2\\315fc0d6-f667-46ad-878d-9fa89499507b.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Administrator\Documents\CS2\\315fc0d6-f667-46ad-878d-9fa89499507b.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>cea5fab</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
Vehicle::TryReconnectBoatToTrack
Vehicle::UpdateMotionBoatHire
Vehicle::Update
OpenRCT2::GameState::UpdateLogic
OpenRCT2::GameState::Update
OpenRCT2::Context::Update
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/ride/Vehicle.cpp [hunk 1]
```diff
@@ -4339,12 +4339,13 @@ void Vehicle::TryReconnectBoatToTrack(const CoordsXY& currentBoatLocation, const
...
-        auto trackElement = map_get_track_element_at(TrackLocation);
-
         auto curRide = GetRide();
         if (curRide != nullptr)
         {
-            SetTrackType(trackElement->GetTrackType());
+            auto trackElement = map_get_track_element_at(TrackLocation);
+            if (trackElement != nullptr)
+                SetTrackType(trackElement->GetTrackType());
+
```
Comment (duncanspumpkin) [inline src/openrct2/ride/Vehicle.cpp:4348]: not sure this is safe to do. If it fails to reconnect then setting the boat location to null and not setting the track type will cause other issues. I think perhaps this if != nullptr should encompass the same amount of scope as the curRide check.

Comment (Gymnasiast) [reply src/openrct2/ride/Vehicle.cpp:4348]: Is `BoatLocation` null if the boat is on a guide track, and set if it's floating freely?

Comment (Gymnasiast) [reply src/openrct2/ride/Vehicle.cpp:4348]: Also, if you take a look at git blame, the BoatLocation.setNull() call was put inside the if because it was split off from trackdirection, and that was only inside the if to prevent a NPE when `ride` was null.

Still, I'm not sure what the "safest" thing to do is here: leave it alone, or set it to a fail-safe value.

Comment (duncanspumpkin) [reply src/openrct2/ride/Vehicle.cpp:4348]: Hmm not sure what would be best

Comment (tupaschoal) [reply src/openrct2/ride/Vehicle.cpp:4348]: So do we close or merge this @duncanspumpkin ?

Comment (duncanspumpkin) [reply src/openrct2/ride/Vehicle.cpp:4348]: I'm still not sure. We could just make the boat explode. Its the easiest get out for this...

**Comment by rik-smeets** [comment]
I don't see this issue occurring anymore, so perhaps we should close this one (for now)?

**Comment by rik-smeets** [comment]
Closed due to inactivity and this issue seemingly no longer occurring.

**Comment by Gymnasiast** [comment]
The issue _does_ occur, only not that often. And it’s mostly Duncan’s reservations that caused inactivity.

**Comment by rik-smeets** [comment]
Fair enough, but as @IntelOrca said in October 2021, let's wrap this one up ;-).

Change looks fine to me, feel free to check in with @duncanspumpkin again before merging though.

**Review by rik-smeets — APPROVED** [review]
