### PR TITLE
Fix #5677: Balloons pop when they hit something

### LINKED ISSUE #5677: Underground balloons
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 7748184

Guests are able to drop balloons while underground.
I don't remember this ever occurring in the original games.

- [X] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Make an underground park
2. Sell balloons
3. Press H and V
4. Watch balloons being dropped from under-ground paths

**Screenshots / Video:**
beforeballoon

afterballoon

### PR DESCRIPTION
**Pull request by mrmbernardi**
Fix for #5677

Balloons will pop if they intersect with the bottom of any tile element, including the ground. 

This could potentially cause a slowdown when everyone drops balloons after you win a scenario (maybe not since the number of balloons is limited to a few hundred)

An alternate method could involve pre-computing the height at which the balloon should pop when the guest releases it. This wouldn't be up to date if players make changes to the map, but that could be acceptable to deal with most cases of balloons floating through things.

### CODE REVIEW

**Comment by ocalhoun6** [comment]
>This could potentially cause a slowdown when everyone drops balloons after you when a scenario.

I could also foresee an issue with the audio of balloons popping when a large mass of guests all release them at once at the end of a scenario -- if large amounts of guests are underground or underneath other things, then shortly after winning a scenario, you'll be assaulted by the sound of hundreds of balloons popping at once. Could be a bit disruptive and annoying.

Even during the middle of the scenario, if there are a lot of underground or covered paths, you could still end up getting pretty frequent popping sounds with no apparent source. This could also get annoying.

Maybe the sound of the balloon popping could be disabled if it's popped because of this -- still pop the balloon, but do it silently.

**Comment by ZehMatt** [comment]
I would actually prefer that guests don't release the balloon when underground rather than having the balloon pop once it hits something.

**Comment by mrmbernardi** [comment]
> I would actually prefer that guests don't release the balloon when underground rather than having the balloon pop once it hits something.

Easy to implement and easy on performance. The one issue I have this that I feel many parks have objects over the guests heads, be it rides, paths or scenery, and sometimes this is quite high above the guest so I think it could reduce the amount of released balloons we end up seeing.

**Comment by ZehMatt** [comment]
> > I would actually prefer that guests don't release the balloon when underground rather than having the balloon pop once it hits something.
> 
> Easy to implement and easy on performance. The one issue I have this that I feel many parks have objects over the guests heads, be it rides, paths or scenery, and sometimes this is quite high above the guest so I think it could reduce the amount of released balloons we end up seeing.

That's a fair point however I think it would be a bit more realistic if guests didn't release them if there is something above them that would block the path of the balloons, there is probably still more than enough guests that would release them.

**Comment by tupaschoal** [comment]
Other than scenario completion, what else makes a guest release a balloon, just random chance?

Because I'd say people hardly ever want to release balloons, but with kids it just happens, so I don't think they pick whether there is something above or not.

**Comment by ZehMatt** [comment]
> Other than scenario completion, what else makes a guest release a balloon, just random chance?
> 
> Because I'd say people hardly ever want to release balloons, but with kids it just happens, so I don't think they pick whether there is something above or not.

Maybe its not a bad idea to add a collision check for them and have them pop with low enough random chance so they won't float forever, I would still have them avoid release them underground or also have an super low chance for that to happen.

**Comment by ocalhoun6** [comment]
>Other than scenario completion, what else makes a guest release a balloon, just random chance?

They will also release a balloon if they're dropped into water and drowning.

**Comment by AaronVanGeffen** [comment]
> Other than scenario completion, what else makes a guest release a balloon, just random chance?

Do they keep them while riding a ride? I was under the impression they'd lose them upon riding a coaster or some such.

**Comment by ocalhoun6** [comment]
Guests can keep a balloon in their inventory without actually holding/displaying it. They do this on rides, yes, but also when eating/drinking or when holding an umbrella, and while doing a few other animations.

They just put the balloon in their pocket, I guess. Kind of like how the handyman keeps a lawn mower in his pocket.

**Comment by mrmbernardi** [comment]
I looked into this a bit more and found out that there's a theoretical limit of 300 balloons with the number in practice being typically much lower. IMO this obviates the performance and sound concerns.

I did some testing; yes you can hear the sound of popping but its generally quieter than the applause and IMO adds to the celebratory feeling :)

But that said, if people don't like it, I can easily implement a flag or something to make balloons released by the applause function have no sound unless they are specifically clicked on the user (IMO there should always be a sound for this).

I've also put some extra code in to prevent balloons phasing through entrance buildings, covered stations, and also the dodgems ride ceiling.

**Comment by SpartanFrederic104** [comment]
Keep open please

**Comment by SpartanFrederic104** [comment]
This still being worked on? If so, please keep open

**Comment by mrmbernardi** [comment]
> Where does this stand @mrmbernardi ?

It works. I think I would maybe make a quick change to remove the sound when popping from collisions. I said earlier that I personally like it but I'd prefer to make the least intrusive PR possible at the moment

**Comment by SpartanFrederic104** [comment]
Keep open please

**Comment by mrmbernardi** [comment]
I removed the popping sound on collisions and made some minor readability improvements.

File: src/openrct2/entity/Balloon.cpp [hunk 1]
```diff
@@ -77,11 +84,12 @@ void Balloon::Press()
     }
 }
 
-void Balloon::Pop()
+void Balloon::Pop(bool silent)
```
Comment (tupaschoal) [inline src/openrct2/entity/Balloon.cpp:87]:
```suggestion
void Balloon::Pop(bool popSilentOnCollision)
```
Would this be a better name?

File: src/openrct2/entity/Balloon.cpp [hunk 2]
```diff
@@ -77,11 +84,12 @@ void Balloon::Press()
...
 {
     popped = 1;
     frame = 0;
-    OpenRCT2::Audio::Play3D(OpenRCT2::Audio::SoundId::BalloonPop, { x, y, z });
+    if (!silent)
+        OpenRCT2::Audio::Play3D(OpenRCT2::Audio::SoundId::BalloonPop, { x, y, z });
```
Comment (tupaschoal) [inline src/openrct2/entity/Balloon.cpp:92]:
```suggestion
    if (!silent)
    {
        OpenRCT2::Audio::Play3D(OpenRCT2::Audio::SoundId::BalloonPop, GetLocation());
    }
```

File: src/openrct2/entity/Balloon.cpp [hunk 3]
```diff
@@ -47,6 +47,13 @@ void Balloon::Update()
...
+
+            if (Collides())
+            {
+                Pop(true);
+                return;
+            }
+
             MoveTo({ x, y, z + 1 });
 
             int32_t maxZ = 1967 - ((x ^ y) & 31);
```
Comment (tupaschoal) [inline src/openrct2/entity/Balloon.cpp:59]: Should we make this an `else` part, so that the compiler knows it's only executed if not `Collides`? Also would remove the need for the `return`

File: src/openrct2/entity/Balloon.h [hunk 4]
```diff
@@ -24,8 +24,9 @@ struct Balloon : EntityBase
     uint8_t colour;
     static void Create(const CoordsXYZ& balloonPos, int32_t colour, bool isPopped);
     void Update();
-    void Pop();
+    void Pop(bool silent = false);
```
Comment (tupaschoal) [inline src/openrct2/entity/Balloon.h:27]: Does it need a default parameter? I always like not adding one if there are few cases to cover

File: src/openrct2/ride/Ride.cpp [hunk 5]
```diff
@@ -5983,3 +5983,14 @@ ResultWithMessage Ride::ChangeStatusCreateVehicles(bool isApplying, const Coords
...
+
+uint8_t Ride::GetEntranceStyle() const
+{
+    const auto* stationObject = GetStationObject();
+    if (stationObject == nullptr)
+        return RCT12_STATION_STYLE_PLAIN;
+
+    const auto objectName = stationObject->GetIdentifier();
+
+    return GetStationStyleFromIdentifier(objectName);
```
Comment (tupaschoal) [inline src/openrct2/ride/Ride.cpp:5995]:
```suggestion
    if (const auto* stationObject = GetStationObject() != nullptr)
    {
        const auto objectName = stationObject->GetIdentifier();
        return GetStationStyleFromIdentifier(objectName);
    }
    else
    {
        return RCT12_STATION_STYLE_PLAIN;
    }
```

**Review by tupaschoal — COMMENTED** [review]
I tested and it works great, I have a few code style related comments.}

Also this would need a changelog entry and I guess a network bump?

File: src/openrct2/entity/Balloon.cpp (hunk 3 above)
Comment (mrmbernardi) [reply src/openrct2/entity/Balloon.cpp:59]: As far as the compiler is concerned both options produce the same control flow. It's just a matter of style. Some people don't like returning from the middle of a function and other people don't like having too many indents. I find the current code slightly more readable but it's subjective and there's not much in it

File: src/openrct2/entity/Balloon.cpp (hunk 1 above)
Comment (mrmbernardi) [reply src/openrct2/entity/Balloon.cpp:87]: I don't think so, because the Pop method knows nothing about the reason for the pop.

I changed it to `playSound`

File: src/openrct2/entity/Balloon.h (hunk 4 above)
Comment (mrmbernardi) [reply src/openrct2/entity/Balloon.h:27]: Good point, I removed the default.

File: src/openrct2/entity/Balloon.cpp (hunk 2 above)
Comment (mrmbernardi) [reply src/openrct2/entity/Balloon.cpp:92]: I've made the change. If braces are preferred it should be mentioned in the code style document

File: src/openrct2/ride/Ride.cpp (hunk 5 above)
Comment (mrmbernardi) [reply src/openrct2/ride/Ride.cpp]: This didn't compile for me but I did something similar

**Comment by mrmbernardi** [comment]
> I tested and it works great, I have a few code style related comments.}
> 
> Also this would need a changelog entry and I guess a network bump?

I'm not sure whether balloons are synchronised after they are dropped, but I bumped the network version anyway.

**Review by tupaschoal — APPROVED** [review]

File: src/openrct2/ride/Ride.cpp (hunk 5 above)
Comment (Gymnasiast) [reply src/openrct2/ride/Ride.cpp]: This is simply incorrect. Station objects have a flag that you can check. It should never check RCT2 ID’s for anything. The function was defined in TrackDesign.cpp for a **very** good reason.
