### PR TITLE
Fix #5977: Custom music being discarded due length being 0.

### LINKED ISSUE #5977: Custom Music 1 & 2 Missing
**OS: Windows 10**
**Version: 0.1.1**
**Commit/Build: 3409662** 

Custom Music 1 and 2 are missing from the dropdown list for ride music. Not sure what build this happened in, but must have been quite recent.

**Steps to reproduce:**
1. Change ride music.
2. Custom Music 1 and 2 aren't there.

**Dump file**

**Screenshots / Video:**

image

### PR DESCRIPTION
**Pull request by ZehM4tt**
When the music list is populated it checks if length is 0 and discards those, also the audio mixer is incapable of playing when length is 0 it seems. This PR sets the length to the file size at runtime while other entries have it set compile time except for custom ones.

Should fix #5977

### CODE REVIEW

File: src/openrct2/audio/audio.cpp [hunk 1]
```diff
@@ -370,6 +370,13 @@ void audio_init_ride_sounds_and_info()
                 {
                     rideMusicInfo->length = 0;
                 }
+                // FIX: Custom ones have no length set and while populating the combo box
+                //      they are ignored if 0.
+                if ((m == 36 || m == 37) && rideMusicInfo->length == 0)
```
Comment (IntelOrca) [inline src/openrct2/audio/audio.cpp]: There are constants you can use instead of 36 and 37.

Comment (Gymnasiast) [inline src/openrct2/audio/audio.cpp]: ... which are? I haven't been able to find them. It's not PATH_ID_CUSTOM1, neither is it MUSIC_STYLE_CUSTOM_MUSIC_1.

**Comment by Nubbie** [comment]
In other words, it will populate the list even if no custom music is installed? (length 0)
Wouldn't it be good with a tool-tip/error box with a message that it couldn't load the song as it doesn't exist/give directions where it should be located to work?
Like the title screen music

**Comment by Gymnasiast** [comment]
@Nubbie No, it does not work like that at all.

File: src/openrct2/audio/audio.cpp (hunk 1 above)
Comment (Gymnasiast) [inline src/openrct2/audio/audio.cpp]: Probably best to create an issue for creating constants.
