### PR TITLE
Close #9104: Calculate maze support costs

### LINKED ISSUE #9104: Mazes don't cost more or less based on height.
**OS:** Windows 10
**Version:** 0.2.2-246
**Commit/Build:** cdf5870

Mazes do not changed in price depending on elevation, unlike every other anything in the game.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a maze on the ground
2. Now build one in the air or on water.

### PR DESCRIPTION
**Pull request by rik-smeets**
Resolves #9104.

### CODE REVIEW

File: src/openrct2/actions/MazeActionBase.h [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+    MazeAction(GameCommand type)
+        : GameAction(type)
+    {
+    }
+
+protected:
+    money64 MazeCalculateCost(const Ride& ride, const CoordsXYZ& _loc) const;
+};
+
+template<GameCommand TType> struct MazeActionBase : MazeAction
```
Comment (duncanspumpkin) [inline src/openrct2/actions/MazeActionBase.h:26]: Why make this a game action? Just make it a standalone function.

**Comment by duncanspumpkin** [comment]
I would see this as a change rather than a fix as it feels like a conscious change.

**Review by tupaschoal — COMMENTED** [review]
Can you split these up into two commits, please? One extracting the price to a `MazeAction`, and then another adding the calculation for the supports? That makes things more organized, as these are two separate changes :)

**Comment by rik-smeets** [comment]
@tupaschoal Good idea, I split the commit in two. Even noticed a bug in my original solution where some costs weren't taken into consideration so it _really_ was a good idea ;-).

File: src/openrct2/actions/MazeAction.h [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+ * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
+ *
+ * OpenRCT2 is licensed under the GNU General Public License version 3.
+ *****************************************************************************/
+
+#pragma once
+
+#include "GameAction.h"
+
+money64 MazeCalculateCost(money32 constructionCost, const Ride& ride, const CoordsXYZ& _loc);
```
Comment (Broxzier) [inline src/openrct2/actions/MazeAction.h:14]: This entire header only contains one function, and nothing relates to it being an action. This would better fit in `src/openrct2/ride/gentle/Maze.cpp` for example.

**Review by Broxzier — DISMISSED** [review]

**Comment by tupaschoal** [comment]
> @tupaschoal Good idea, I split the commit in two. Even noticed a bug in my original solution where some costs weren't taken into consideration so it _really_ was a good idea ;-). 

This is like music to my ears, glad to know!

File: src/openrct2/actions/MazeAction.h (hunk 2 above)
Comment (rik-smeets) [reply src/openrct2/actions/MazeAction.h]: I moved the code and also updated the network version while I was at it.

File: src/openrct2/ride/gentle/meta/Maze.h [hunk 3]
```diff
@@ -63,3 +63,5 @@ constexpr const RideTypeDescriptor MazeRTD =
     SET_FIELD(ConstructionWindowContext, RideConstructionWindowContext::Maze),
 };
 // clang-format on
+
+money64 MazeCalculateCost(money32 constructionCost, const Ride& ride, const CoordsXYZ& _loc);
```
Comment (duncanspumpkin) [inline src/openrct2/ride/gentle/meta/Maze.h:67]: The meta header isn't really the best location for this. I would just create a new header for the maze if it doesn't already exist.

Comment (rik-smeets) [reply src/openrct2/ride/gentle/meta/Maze.h]: Moved to a new header file.

**Review by duncanspumpkin — APPROVED** [review]
