### PR TITLE
Fix #4617: Crash when rotating with invalid viewport open

### LINKED ISSUE #4617: Signs Causing Crashes
**OS:** Windows 10
**Version:** e.g. 0.0.5
**Commit/Build:** 5fa5f29 and many previous ones
**Explanation of the issue:** 
I'm having several issues with the "3D Sign" and "Scrolling Signs." The first issue I noticed was after I had placed 4 of the 3D Signs. When I placed the Scrolling Sign, it changed one of my 3D Signs to the text that was on the Scrolling Sign. When I tried to switch that 3D Sign back, it changed the Scrolling Sign as well. Then, oddly enough, I tried to nickname a Janitor and it changed a different 3D Sign to his name.  And occasionally when I try to edit the signs I will crash upon right clicking them. The bug seems to vary over time, as certain signs will cause crashes one day and then different ones will cause crashes the next day while the old ones are fine. I haven't been able to reproduce it or have it occur in the multiplayer.
**Reproducible in RCT2 (vanilla)?** Unknown
**Multiplayer?** Unknown
**Steps to reproduce:**
1. Glitch varies, difficult to reproduce. To see it, open my saved game and right click the four signs on the two buildings. One of them will likely cause a crash.
**Dump file:**
[8b7db1df-c3fc-4f7a-a56b-a56add8d724a(5fa5f29).zip](https://github.com/OpenRCT2/OpenRCT2/files/530302/8b7db1df-c3fc-4f7a-a56b-a56add8d724a.5fa5f29.zip)

**Save game:**
[Monsanto World.zip](https://github.com/OpenRCT2/OpenRCT2/files/530303/Monsanto.World.zip)

### PR DESCRIPTION
**Pull request by ZehMatt**
This fixes the issue described here: https://github.com/OpenRCT2/OpenRCT2/pull/11094#issuecomment-606820960 when clicking on those banners:
openrct2_2020-09-28_23-39-56
and then rotating.

The main issue is that the viewport is actually not working correctly with those, this just prevents the crash but the viewport issue remains.

### CODE REVIEW

File: src/openrct2-ui/windows/Sign.cpp [hunk 1]
```diff
@@ -323,6 +323,9 @@ static void window_sign_paint(rct_window* w, rct_drawpixelinfo* dpi)
 static void window_sign_viewport_rotate(rct_window* w)
 {
     rct_viewport* view = w->viewport;
+    if (view == nullptr)
+        return;
+
     w->viewport = nullptr;
 
     view->width = 0;
```
Comment (Broxzier) [inline src/openrct2-ui/windows/Sign.cpp:331]: I assume it crashed here. Why is this needed? Can't this just be removed, or moved down to the other null check?

Comment (IntelOrca) [reply src/openrct2-ui/windows/Sign.cpp:331]: Yeah, I think this is the correct fix:
```c
if (w->viewport != nullptr)
{
    w->viewport->width = 0;
    w->viewport = nullptr;
}
```

Comment (ZehMatt) [reply src/openrct2-ui/windows/Sign.cpp]: I applied @IntelOrca suggestion.

**Review by Gymnasiast — APPROVED** [review]
I can no longer get it to crash by rotating any viewport.
