### PR TITLE
Fix #9322: Peep crashing the game trying to find a ride to look at

### LINKED ISSUE #9322: BACKTRACE 300458
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/3004584cb3100c0401e7a6575364b1b88f4f032aa118c27c3e082f69478de1ba?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue May 28 2019 03:49:35)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_screenshot.png:</strong> C:\\Users\\Ian\\Documents\\OpenRCT2\\screenshot\\Mass Destruction 2019-05-27 22-49-36.png: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Ian\\Documents\\OpenRCT2\\a44add9a-6023-4429-abb7-eb3bebaf6b5b.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Ian\\Documents\\OpenRCT2\\a44add9a-6023-4429-abb7-eb3bebaf6b5b.sv6.gz: <em>1</em><br><strong>commit:</strong> 46889b5: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>peep_find_ride_to_look_at -> Guest::UpdateWalking -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> invoke_main</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by ZehMatt**
Another missing nullptr check. I believe this happens when peeps are walking near the edge of the map and then trying to find a ride to look at.

### CODE REVIEW

File: src/openrct2/peep/Guest.cpp [hunk 1]
```diff
@@ -6385,6 +6397,8 @@ static bool peep_find_ride_to_look_at(Peep* peep, uint8_t edge, uint8_t* rideToV
     tileElement = surfaceElement;
     do
     {
+        if (tileElement == nullptr)
+            break;
```
Comment (IntelOrca) [inline src/openrct2/peep/Guest.cpp]: How come you put this one inside the loop?

File: src/openrct2/peep/Guest.cpp [hunk 2]
```diff
@@ -6341,6 +6351,8 @@ static bool peep_find_ride_to_look_at(Peep* peep, uint8_t edge, uint8_t* rideToV
...
```
Comment (IntelOrca) [inline src/openrct2/peep/Guest.cpp]: surfaceElement has already been null checked above.

File: src/openrct2/peep/Guest.cpp (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/peep/Guest.cpp]: Yeah true, that was my initial plan but then realized the existing check which did it right after calling map_get_surface_element as I wasn't entirely sure about the logic of this function given that it sometimes returns false and when the loop runs out of elements it would jump to the next loop, its quite confusing.
