### PR TITLE
Fix two ride construction bugs

### LINKED ISSUE #2881: Disable left/right hand curve buttons after steep drop and then the level piece
**Vertical Drop Roller Coaster**

Select the level piece and it'll also enable the left/right hand curve. This shouldn't be selectable as this piece does not exist and is just the 'no roll' piece.
scr11

(This is done correctly for the normal 'slope down' piece)

### LINKED ISSUE #2882: Slope up not working with suspended swinging coaster
Even though the button is enabled, clicking it does nothing. However, 'slope down' works fine.

scr12

### PR DESCRIPTION
**Pull request by danidoedel**
Fix #2881 and #2882

### CODE REVIEW

File: src/windows/ride_construction.c [hunk 1]
```diff
@@ -720,6 +720,12 @@ static void window_ride_construction_resize(rct_window *w)
 			(1ULL << WIDX_BANK_STRAIGHT) |
 			(1ULL << WIDX_BANK_RIGHT);
 	}
+	// Disable banking if the start track is steep and the end of the track becomes flat.
+	if (_previousTrackSlopeEnd == TRACK_SLOPE_DOWN_60 || _previousTrackSlopeEnd == TRACK_SLOPE_UP_60 || _currentTrackSlopeEnd == TRACK_SLOPE_TO_FLAT) {
```
Comment (IntelOrca) [inline src/windows/ride_construction.c]: This if expression does not match your comment. I think you intended to have:
```(previous = down or previous = up) and current = flat```

**Comment by danidoedel** [comment]
Yeah that makes sense. I hope it's correct now :grin:
