### PR TITLE
Fix #6514: Groupbox titles break format arguments

### LINKED ISSUE #6514: Some strings are broken
**OS:** Arch Linux x86_64
**Version:** 0.1.2
**Commit/Build:** ec22d04089e5516658427ae58c2a7f956c01f98e

Some strings appear to be broken. Happens in every language.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
2017-10-18-132240_5120x1080_scrot
2017-10-18-135444_5120x1080_scrot

### PR DESCRIPTION
**Pull request by marijnvdwerf**

### CODE REVIEW

File: src/openrct2/interface/widget.c [hunk 1]
```diff
@@ -538,10 +538,12 @@ static void widget_groupbox_draw(rct_drawpixelinfo *dpi, rct_window *w, rct_widg
         if (widget_is_disabled(w, widgetIndex))
             colour |= 0x40;
 
-        format_string(gCommonStringFormatBuffer, sizeof(gCommonStringFormatBuffer), widget->text, gCommonFormatArgs);
-        set_format_arg(0, uintptr_t, gCommonStringFormatBuffer);
-        gfx_draw_string_left(dpi, STR_STRING, gCommonFormatArgs, colour, l, t);
-        textRight = l + gfx_get_string_width(gCommonStringFormatBuffer) + 1;
+        utf8 buffer[512] = {0};
+        uint8 args[sizeof(uintptr_t)] = {0};
```
Comment (Gymnasiast) [inline src/openrct2/interface/widget.c]: `{ 0 }`
