### PR TITLE
Fix track deletion confirmation prompt not being aligned vertically 

### LINKED ISSUE #24611: Track Delete Confirmation Prompt window has misaligned text in Enlarged UI
### Operating System

Ubuntu 24.04

### OpenRCT2 build

a12cf878fae77a7298021062a80cad6d8a313aa9

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

_No response_

### Describe the issue

Image

### Steps to reproduce

1. Turn on Enlarged UI
2. Go to Track Designs Manager
3. Click a ride type
4. Click a design
5. Click ‘delete’

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by spaghetticat08**
Fix for issue #24611; the text in the track delete confirmation prompt is now aligned properly when Enlarged UI setting is enabled.

However, I am not fully satisfied as the text is still not exactly centered, it still is mostly fixed towards to the top. I have played around using different values in the ScreenCoordsXY parameter used for DrawTextWrapped() which is influencing the offset of the text, but even when I put value 1 or nothing, the text is still not perfectly aligned in the middle. Is this even achievable? Or is this fix good enough?

enlarged_ui_fix_not_centre

I have tested this on Windows 11 but the issue was reported for Ubuntu 24.04. I will test it tomorrow on Ubuntu as well, just need to update my machine as it is currently running 22.

### CODE REVIEW

File: src/openrct2-ui/windows/TrackDesignManage.cpp [hunk 1]
```diff
@@ -233,7 +233,7 @@ namespace OpenRCT2::Ui::Windows
         auto ft = Formatter();
         ft.Add<const utf8*>(_trackDesignFileReference->name.c_str());
         DrawTextWrapped(
-            rt, windowPos + ScreenCoordsXY{ (kWindowSizeDeletePrompt.width / 2), ((kWindowSizeDeletePrompt.height / 2) - 9) },
+            rt, windowPos + ScreenCoordsXY{ (kWindowSizeDeletePrompt.width / 2), ((kWindowSizeDeletePrompt.height / 2) - 3) },
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/TrackDesignManage.cpp]: Changing the offset from 9 to 3 is not going to have the desired effect in all situations. The Y coordinate should be expressed using the `.bottom` of the title widget instead. See e.g. #24290 for an example.

Comment (spaghetticat08) [reply src/openrct2-ui/windows/TrackDesignManage.cpp]: Thank you for reviewing and the feedback. I now changed it and used widgets[WIDX_TITLE].bottom instead, is this what you mean? Are there other scenarios I should test? I now tested by trying to delete a track in the track manager, both with and without the Enlarge UI option. In both cases the text is now centered in the middle of the prompt.

File: src/openrct2-ui/windows/TrackDesignManage.cpp [hunk 2]
```diff
@@ -233,7 +233,7 @@ namespace OpenRCT2::Ui::Windows
         auto ft = Formatter();
         ft.Add<const utf8*>(_trackDesignFileReference->name.c_str());
         DrawTextWrapped(
-            rt, windowPos + ScreenCoordsXY{ (kWindowSizeDeletePrompt.width / 2), ((kWindowSizeDeletePrompt.height / 2) - 9) },
+            rt, windowPos + ScreenCoordsXY{ (kWindowSizeDeletePrompt.width / 2), (widgets[WIDX_TITLE].bottom + 16) },
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/TrackDesignManage.cpp]: This now no longer longer vertically aligns the text (`kWindowSizeDeletePrompt.height / 2`). Note that the `- 9` was here originally to exclude the title bar height. This is what ought to be replaced with e.g. `widgets[WIDX_TITLE].bottom - 2`.

File: src/openrct2-ui/windows/TrackDesignManage.cpp (hunk 1 above)
Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/TrackDesignManage.cpp]: The new code is not quite what I meant, unfortunately. I've left another line comment on the new code.

File: src/openrct2-ui/windows/TrackDesignManage.cpp (hunk 2 above)
Comment (spaghetticat08) [reply src/openrct2-ui/windows/TrackDesignManage.cpp]: I'm sorry, I think I do not fully understand how this mechanism works. I tried what you suggested, but then the text is not vertically aligned anymore. Without Enlarged UI it is slightly upwards and with Enlarged UI, it overlaps with the titlebar. I think I understand that we retrieve the correct y parameter by dividing the height of the window by 2 and then subtract the .bottom of the widgets to correct UI scaling, but after playing around with some variations I cannot seem to get it working. I think I am missing something here, but I'm not sure exactly what. Can you point me to the right direction?

Comment (spaghetticat08) [reply src/openrct2-ui/windows/TrackDesignManage.cpp]: Okay, after fiddling for hours yesterday with the code I think I understand and have two solutions. So from what I see the text is positioned by windowPos (which I assume starts left upper corner of that prompt) plus the X, Y coordinate. The X is divided by two and centered and the Y was the height divided by 2 minus that fixed value for the title bar. However, that does not dynamically scale, so essentially you want to push the text 'down' by increasing the Y value. In the current solution I am solving it by calculating the Y value: Y = the position of the bottom of the title bar (widgets[WIDX_TITLE].bottom) + the size of the window minus the titlebar (else the text ends up too high) divided by 3. The 3 is instead of 2 because if you take two it is always centered, but I noticed with the ennlarged UI, not everything scales evenly so essentially the text will not have a consistent position. With this solution the text is consistently positioned in the window, regardless of the scaling.

An alternative is to just only use kWindowSizeDeletePrompt.height / 2, which also works but then you see the text positioning slightly different when enabling UI scaling, which makes it less consistent.

Let me know what you think of this :)

**Comment by AaronVanGeffen** [comment]
Ultimately, I think the issue was that the original code just wasn't very clear to begin with. I've pushed a commit to rewrite the positioning code, which fixes the issue and hopefully makes the intent of the code clearer in the process.

With enlarged UI:
Screenshot 2025-07-21 at 21 10 03

Without enlarged UI:
Screenshot 2025-07-21 at 21 10 16

File: src/openrct2-ui/windows/TrackDesignManage.cpp (hunk 2 above)
Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/TrackDesignManage.cpp]: I've pushed a commit to rewrite the positioning code, which fixes the issue and hopefully makes the intent of the code clearer in the process.

**Review by Gymnasiast — APPROVED** [review]
