### PR TITLE
Fix user being able to enter formatting characters (fixes #2892)

### LINKED ISSUE #2892: Adding a tilde (~) at the end of a name causes some weirdness.
Its hard to explain but it looks like it causes some temporary string corruption

Below are two examples, the "corruption" seems to happen when you're moused over something and you move the camera. It also happens in places like guest thoughts. 

ss 2016-02-06 at 02 33 30
ss 2016-02-06 at 02 32 43

Here's a save file http://puu.sh/mXxoS/dca5484378.zip

and the version of OpenRCT2 I'm running is 0.0.4 build 1073 (a8eca93) from appveyor.com

### PR DESCRIPTION
**Pull request by Overv**
The original game silently removes these characters after entering them. It seems more appropriate for OpenRCT2 to simply not accept entering them.

### CODE REVIEW

File: src/platform/shared.c [hunk 1]
```diff
@@ -712,6 +712,10 @@ void platform_process_messages()
 				if (e.text.text[0] == '`' && gConsoleOpen)
 					break;
 
+				// Entering formatting characters is not allowed
+				if (utf8_is_format_code((int)e.text.text[0]))
```
Comment (IntelOrca) [inline src/platform/shared.c]: This is not handling UTF-8 correctly, you need to use ```utf8_get_next```.

Comment (Overv) [inline src/platform/shared.c]: Should line 712 stay the way it is?

Comment (IntelOrca) [inline src/platform/shared.c]: Yea, UTF-8 is backwards compatible with ASCII, its only because some format codes are not ASCII that we need to do this.
