### PR TITLE
Fix #16821: sprite exportalldat prints illegal backslashes

### LINKED ISSUE #16821: sprite exportalldat prints illegal backslashes
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.5.1 d7f5995

### Describe the issue

When using `sprite exportalldat`, the json output uses backslashes for path instead of forward slashes, which is illegal in json, it means that users using the offsets provided by the game must manually convert the backslashes to forward slashes before using them in a parkobj json.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. export sprite of dat
2. observe backslash

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@spacek531 Could you test?

File: src/openrct2/CmdlineSprite.cpp [hunk 1]
```diff
@@ -449,6 +449,7 @@ int32_t cmdline_for_sprite(const char** argv, int32_t argc)
                 return -1;
             }
 
+            std::replace(path.begin(), path.end(), '\\', '/');
```
Comment (CookiePLMonster) [inline src/openrct2/CmdlineSprite.cpp:452]: Consider using `std::filesystem::path` to do it for you, for example
```cpp
path = u8path(path).generic_u8string();
```

**Comment by spacek531** [comment]
Both solutions work on my computer
