### PR TITLE
Fix #25879: Guest window viewport doesn't follow vehicle when on ride

### LINKED ISSUE #25879: Guest viewport doesn't update after guest enters ride
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.30 (545d269295 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The viewport of the guest doesn't update after the guest enters a ride, if you were viewing the guest before it entered.

The viewport does work if you click on guests that are already in the ride.

### Steps to reproduce

1. Watch a guest entering a ride from the queue.
2. Wait until the vehicle leaves.
3. The viewport doesn't move with the vehicle the guest is in.

### Attachments

https://github.com/user-attachments/assets/2d6293f1-70b6-4fa8-ba4c-d48d5b835b91

### PR DESCRIPTION
**Pull request by frozensnowy**
Fixes #25879

### CODE REVIEW

File: src/openrct2-ui/windows/Guest.cpp [hunk 1]
```diff
@@ -947,7 +947,11 @@ namespace OpenRCT2::Ui::Windows
 
             const std::optional<Focus> currentFocus = peep->State != PeepState::picked ? std::optional(Focus(peep->Id))
                                                                                        : std::nullopt;
-            if (focus != currentFocus)
+            // Also update when guest is on a ride but viewport still points to the guest (not the vehicle)
+            if (focus != currentFocus
+                || (viewportTargetSprite == EntityId::FromUnderlying(number)
+                    && (peep->State == PeepState::onRide || peep->State == PeepState::enteringRide
+                        || (peep->State == PeepState::leavingRide && peep->x == kLocationNull))))
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/Guest.cpp]: I think we should extract this to a helper function to keep this readable.

Comment (frozensnowy) [reply src/openrct2-ui/windows/Guest.cpp]: Alright, sounds good

**Review by Gymnasiast — APPROVED** [review]
Seems to address both issues.

**Comment by AaronVanGeffen** [comment]
Missing a changelog entry?

**Comment by Gymnasiast** [comment]
Good point, fixed with 4a5ca9eb3f58cbf723db391dfab2d1c653ea0b9b.

**Comment by Basssiiie** [comment]
@Gymnasiast the changelog entry seems to have a mistake in it 🙊

> Guest window viewport doesn’t follow vehicle when **on** they board a ride.

**Comment by Gymnasiast** [comment]
Fixed.
