### PR TITLE
Fix #26140: TimeInQueue overflows back to 0 after 65535 (about a year)

### LINKED ISSUE #26140: TimeInQueue overflows back to 0 after 65535 (about a year)
### Operating System

Any

### OpenRCT2 build

Any

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

-

### Steps to reproduce

-

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by MarcelVos96**
Fixes #26140

### CODE REVIEW

File: src/openrct2/entity/Guest.cpp [hunk 1]
```diff
@@ -7525,7 +7525,7 @@ int32_t GetPeepFaceSpriteLarge(Guest* peep)
  */
 bool Guest::UpdateQueuePosition(PeepActionType previous_action)
 {
-    TimeInQueue++;
+    TimeInQueue = std::min<uint32_t>(TimeInQueue + 1, 65535);
```
Comment (Gymnasiast) [inline src/openrct2/entity/Guest.cpp]: Use AddClamp

**Review by Gymnasiast — APPROVED** [review]
I trust you tested this?

**Comment by MarcelVos96** [comment]
I did, hence the "remove debug print statement" commit. Outputting the value after every increase is how I discovered it resetted in the first place.
