### PR TITLE
Make some PVS-Studio fixes

### LINKED ISSUE #12523: Make PVS-Studio Fixes
Fix the issues identified by PVS Studio in the following post:

https://www.viva64.com/en/b/0749/

### PR DESCRIPTION
**Pull request by vjavs**
PVS-Studio is a tool for static code analysis. It has a free license for open-source projects.

Some warnings for this project were reported [here](https://www.viva64.com/en/b/0749/)

Close #12523

### CODE REVIEW

File: src/openrct2-ui/input/MouseInput.cpp [hunk 1]
```diff
@@ -1089,7 +1089,8 @@ void process_mouse_over(const ScreenCoordsXY& screenCoords)
 
     if (window != nullptr)
     {
-        int32_t ebx, edi;
+        int32_t ebx;
+        [[maybe_unused]] int32_t edi;
```
Comment (duncanspumpkin) [inline src/openrct2-ui/input/MouseInput.cpp:1093]: just remove edi completely we don't need it anymore.

File: src/openrct2-ui/input/MouseInput.cpp [hunk 2]
```diff
@@ -1116,7 +1117,6 @@ void process_mouse_over(const ScreenCoordsXY& screenCoords)
                     edi = cursorId;
                     // Window event WE_UNKNOWN_0E was called here, but no windows actually implemented a handler and
                     // it's not known what it was for
-                    cursorId = edi;
                     if ((ebx & 0xFF) != 0)
```
Comment (duncanspumpkin) [inline src/openrct2-ui/input/MouseInput.cpp:1120]: This is always false. remove whole if case and comment.

File: src/openrct2/object/ObjectFactory.cpp [hunk 3]
```diff
@@ -440,6 +440,7 @@ namespace ObjectFactory
             result->ReadJson(&readContext, jRoot);
             if (readContext.WasError())
             {
+                delete result;
```
Comment (duncanspumpkin) [inline src/openrct2/object/ObjectFactory.cpp:443]: This does fix this specific instance but we still need to track that this needs conversion to using something like a unique ptr. This PR is not to be merged without making an issue for that.

File: src/openrct2/rct12/RCT12.h [hunk 4]
```diff
@@ -589,9 +589,9 @@ assert_struct_size(RCT12EntranceElement, 8);
 struct RCT12BannerElement : RCT12TileElementBase
 {
 private:
-    uint8_t index;    // 4
-    uint8_t position; // 5
-    uint8_t flags;    // 6
+    uint8_t index;        // 4
+    uint8_t position;     // 5
+    uint8_t banner_flags; // 6
```
Comment (duncanspumpkin) [inline src/openrct2/rct12/RCT12.h:594]: You will need to check every instance of RCT12BannerElement to make sure if it was meant to use banner_flags or flags.

File: src/openrct2/ride/gentle/ObservationTower.cpp [hunk 5]
```diff
@@ -35,11 +35,11 @@ void vehicle_visual_observation_tower(
     int32_t baseImage_id = (vehicle->restraints_position / 64);
     if (vehicle->restraints_position >= 64)
     {
-        if ((imageDirection / 8) && (imageDirection / 8) != 3)
+        if (auto directionOffset = imageDirection / 8; (directionOffset != 0) && (directionOffset != 3))
```
Comment (duncanspumpkin) [inline src/openrct2/ride/gentle/ObservationTower.cpp:38]: needs checked against the assembly. Also we tend not to use the if with initializer.

File: src/openrct2/object/ObjectFactory.cpp (hunk 3 above)
Comment (vjavs) [reply src/openrct2/object/ObjectFactory.cpp:475]: Please see #13100

File: src/openrct2/rct12/RCT12.h (hunk 4 above)
Comment (vjavs) [reply src/openrct2/rct12/RCT12.h:594]: Luckily that member is private, so the changes were easily done.

File: src/openrct2/ride/gentle/ObservationTower.cpp (hunk 5 above)
Comment (vjavs) [reply src/openrct2/ride/gentle/ObservationTower.cpp:38]: I wrote two functions to get the difference between the assemblies.

First:
```
#include <cstdint>

auto f(int32_t imageDirection){
    return (imageDirection / 8) && (imageDirection / 8) != 3;
}
```
[https://godbolt.org/z/7Yczqe](https://godbolt.org/z/7Yczqe)

Second:
```
#include <cstdint>

auto f(int32_t imageDirection){
    auto directionOffset = imageDirection / 8;
    return (directionOffset != 0) && (directionOffset != 3);
}
```
[https://godbolt.org/z/hz61Te](https://godbolt.org/z/hz61Te)

The diff between assemblies can be seen here: [https://www.diffchecker.com/OJKsMcBr](https://www.diffchecker.com/OJKsMcBr)

I ran these functions in all range of ```int32_t``` and results were identical.
I've noticed that this same technique was already employed here: [LaunchedFreefall.cpp#L61](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/thrill/LaunchedFreefall.cpp#L61)

Comment (duncanspumpkin) [reply src/openrct2/ride/gentle/ObservationTower.cpp:38]: No I mean checked against the original rct2 assembly

Comment (vjavs) [reply src/openrct2/ride/gentle/ObservationTower.cpp]: Here we have artifacts before and after the change:
 - [before](https://github.com/vjavs/OpenRCT2/actions/runs/288461434)
 - [after](https://github.com/vjavs/OpenRCT2/actions/runs/288494654)

But I have no clue how to compare them. Either against each other or against the original rct2 assembly.
Actually I checksum file `libopenrct2.so` and they diverged.

How could we do that? Also, I would love to know why is it necessary to check against the binary in such a condition.

Comment (duncanspumpkin) [reply src/openrct2/ride/gentle/ObservationTower.cpp]: It's necessary because it looks wrong so I'd like to make sure that it is doing what it is meant to do. You can check the assembly with a debugger/dissassembler like olydbg or ida or you can just leave it for me to check

Comment (vjavs) [reply src/openrct2/ride/gentle/ObservationTower.cpp]: > or you can just leave it for me to check

Sure, please.

Comment (duncanspumpkin) [reply src/openrct2/ride/gentle/ObservationTower.cpp]: image
Yup all looks fine. Could you make it a bit more readable by moving around the if:

```
        auto directionOffset = imageDirection / 8;
        if ((directionOffset == 0) || (directionOffset == 3))
        {
            baseImage_id = vehicleEntry->base_image_id + 8;
        }
        else
        {
            baseImage_id *= 2;
            baseImage_id += vehicleEntry->base_image_id;
            if (directionOffset == 1)
            {
                 baseImage_id += 28;
            }
            else
            {
                baseImage_id += 22;
            }
        }

```

Comment (vjavs) [reply src/openrct2/ride/gentle/ObservationTower.cpp]: Nice check! :)

File: src/openrct2/rct12/RCT12.h (hunk 4 above)
Comment (duncanspumpkin) [reply src/openrct2/rct12/RCT12.h:594]: I question if these should even be called flags maybe should call it allowed edges. Give me a little while to check things

Comment (duncanspumpkin) [reply src/openrct2/rct12/RCT12.h:594]: after a review of the codebase I dont think these should be called flags. They are `AllowedEdges` can you please rename them. Can you also rename the `BannerElement` version of them as well `TileElement.h` will need modifcations in `Banner.cpp` as well. I realise that `AllowedEdges` wont match the code style surrounding this but that is how it should be styled as per our coding style document

Comment (vjavs) [reply src/openrct2/rct12/RCT12.h]: That totally makes sense.

**Review by duncanspumpkin — APPROVED** [review]

**Review by tupaschoal — APPROVED** [review]
