### PR TITLE
Fix #21908: Ride mode warnings when hovering track designs

### LINKED ISSUE #21908: Uncap FPS causes a red error to pop up: "Unable to change ride operating mode"
### Operating System

Windows 11 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.10-101-gbe9f1a2 (be9f1a2 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

So I have bene ecountering a weird issue where it tells me  Unable to change ride operating mode. I have narrowed it down to uncap fps causing the issue.

### Steps to reproduce

Open up any park. Open any rollercoaster or track based ride and select a prefab and move it around map with uncap fps on and off.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/actions/RideSetSettingAction.cpp [hunk 1]
```diff
@@ -50,7 +50,12 @@ GameActions::Result RideSetSettingAction::Query() const
     auto ride = GetRide(_rideIndex);
     if (ride == nullptr)
     {
-        LOG_ERROR("Ride not found for rideIndex %u.", _rideIndex.ToUnderlying());
+        LOG_ERROR(
+            "Ride not found for rideIndex %u, trying to apply setting %d.", _rideIndex.ToUnderlying(), EnumValue(_setting));
```
Comment (ZehMatt) [inline src/openrct2/actions/RideSetSettingAction.cpp:54]: Please get rid of this entirely, within Query the game actions are supposed to ask if something would work so this doesn't make much sense, never did.

Comment (ZehMatt) [reply src/openrct2/actions/RideSetSettingAction.cpp:54]: Would be also good to remove those in all the other ones, no need to do this in this PR but generally speaking.

**Review by AaronVanGeffen — APPROVED** [review]

File: distribution/changelog.txt [hunk 2]
```diff
@@ -17,6 +17,7 @@
 - Fix: [#18169] CJK, Arabic and Vietnamese display all text as ‘???’ on Android.
 - Fix: [#18309] Flying and Multi Dimension trains glitch when changing between inverted and uninverted track when uncap fps is on.
 - Fix: [#19506] Queue paths can be placed on level crossings by replacing an existing regular path.
+- Fix: [#21908] Ride mode warnings when hovering track designs.
```
Comment (AaronVanGeffen) [inline distribution/changelog.txt:20]: This issue is also reported fixed in the changelog for v0.4.14. The fix in question turned out to be a partial fix. Are we fine with both lines existing? Just checking if there's a policy.

Comment (Gymnasiast) [reply distribution/changelog.txt:20]: I don’t think we have a standard procedure for this. It should at least be in the changelog for this version, I’d say - not sure what to do with the older line.

File: src/openrct2/actions/TrackDesignAction.cpp [hunk 3]
```diff
@@ -238,7 +239,11 @@ GameActions::Result TrackDesignAction::Execute() const
 
     auto numCircuits = std::max<uint8_t>(1, _td.operation.numCircuits);
     SetOperatingSettingNested(ride->id, RideSetSetting::NumCircuits, numCircuits, flags);
-    ride->setToDefaultInspectionInterval();
+
+    uint8_t defaultInspectionInterval = Config::Get().general.DefaultInspectionInterval;
+    if (defaultInspectionInterval <= RIDE_INSPECTION_NEVER)
+        SetOperatingSettingNested(ride->id, RideSetSetting::InspectionInterval, defaultInspectionInterval, flags);
```
Comment (ZehMatt) [inline src/openrct2/actions/TrackDesignAction.cpp:245]: I realized this a bit too late but this will now cause desyncs if other clients have a different value set. The correct way would be to pass this as an argument to the game action.

Comment (Gymnasiast) [reply src/openrct2/actions/TrackDesignAction.cpp:245]: Good point, I created https://github.com/OpenRCT2/OpenRCT2/issues/24126 to keep track of it.

But I’m not sure the desync was _introduced_ here though - the `ride->setToDefaultInspectionInterval()` function, which it called before this PR, seems to have the same issue.
