### PR TITLE
Fix #16197. Park award time and type accidentally swapped

### LINKED ISSUE #16197: All awards show up as the "worst value park" award
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (b83f7c3 on develop) provided by GitHub

### Describe the issue

I got 3 awards, but in the awards screen they all show up as the worst value park.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Get awards
2. Check awards screen

### Attachments

Coaster Dreams 2021-12-12 01-47-47

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Mistake caused by incorrect types so I went and also made it type safe.

### CODE REVIEW

File: src/openrct2/management/Award.h [hunk 1]
```diff
@@ -38,13 +32,19 @@ enum class ParkAward : uint8_t
     MostDazzlingRideColours,
     MostConfusingLayout,
     BestGentleRides,
-    Count
+    Count // Count must be less than 32
```
Comment (Gymnasiast) [inline src/openrct2/management/Award.h:35]: If it must be less than 32, let’s add a static assert.

File: src/openrct2/management/Award.h [hunk 2]
```diff
@@ -13,13 +13,7 @@
...
 #include <vector>
 
-struct Award
-{
-    uint16_t Time;
-    uint16_t Type;
-};
-
-enum class ParkAward : uint8_t
+enum class ParkAward : uint16_t
```
Comment (Gymnasiast) [inline src/openrct2/management/Award.h:16]: Having `ParkAward` and `Award` is quite confusing. Would be better to rename to `AwardType`.

May be done in a later PR, though.

**Review by Gymnasiast — APPROVED** [review]
While I would like to see the line notes addressed, I think it’s important to merge this quickly.
