### PR TITLE
Fix #22726: Force park rating cheat does not save

### LINKED ISSUE #22726: "Force park rating" cheat doesn't reset when opening a different park
### Operating System

Windows 10

### OpenRCT2 build

v0.4.0 and newer

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When the new save format was introduced, the cheats saved with the park, and when you open up a new scenario they all turn off again. However, this doesn't happen with the "force park rating" cheat, that one stays on when you load a saved game or open up a new scenario.

### Steps to reproduce

1. Turn on the force park rating cheat
2. Load up a different park
3. Check the cheat menu

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by RedMarcher**
Force park rating is stored in Park.cpp rather than Gamestate with the rest of the cheats. Added forced park rating variable to Gamestate cheats struct. Added serialization for forced park rating. Removed and refactored prior variable and logic in Park.cpp

### CODE REVIEW

File: src/openrct2/Cheats.cpp [hunk 1]
```diff
@@ -57,6 +57,7 @@ void CheatsReset()
     gameState.Cheats.AllowSpecialColourSchemes = false;
     gameState.Cheats.MakeAllDestructible = false;
     gameState.Cheats.SelectedStaffSpeed = StaffSpeedCheat::None;
+    gameState.Cheats.ForcedParkRating = -1;
```
Comment (Gymnasiast) [inline src/openrct2/Cheats.cpp:60]: Could you create a constant for this? E.g. `kForcedParkRatingDisabled`.

Comment (RedMarcher) [reply src/openrct2/Cheats.cpp]: You got it. I changed it just now.

BTW, what does the comment 
TODO: Refactor this. Cheat variables should contain the cheat type and a serialisation method
mean exactly?

File: src/openrct2/Cheats.h [hunk 2]
```diff
@@ -47,6 +47,7 @@ struct CheatsState
     bool AllowSpecialColourSchemes;
     bool MakeAllDestructible;
     StaffSpeedCheat SelectedStaffSpeed;
+    int ForcedParkRating;
```
Comment (Gymnasiast) [inline src/openrct2/Cheats.h:50]:
```suggestion
    int32_t ForcedParkRating;
```
Idem for the constant. We never use plain `int`.

File: src/openrct2/world/Park.cpp [hunk 3]
```diff
@@ -395,12 +392,13 @@ namespace OpenRCT2::Park
 
     int32_t CalculateParkRating()
     {
-        if (_forcedParkRating >= 0)
+        auto& gameState = GetGameState();
+
+        if (gameState.Cheats.ForcedParkRating >= 0)
```
Comment (Gymnasiast) [inline src/openrct2/world/Park.cpp:397]:
```suggestion
        if (gameState.Cheats.ForcedParkRating != kForcedParkRatingDisabled)
```

File: src/openrct2/Cheats.cpp [hunk 4]
```diff
@@ -27,6 +27,8 @@ using namespace OpenRCT2;
 // TODO: Refactor this. Cheat variables should contain the cheat type
 // and a serialisation method.
 
+const int kForcedParkRatingDisabled = -1;
```
Comment (Gymnasiast) [inline src/openrct2/Cheats.cpp:30]:
```suggestion
const int32_t kForcedParkRatingDisabled = -1;
```

File: src/openrct2/Cheats.h (hunk 2 above)
Comment (Gymnasiast) [reply src/openrct2/Cheats.h]: No, just the one you added. There rest is indeed better done in another PR.

File: src/openrct2/Cheats.cpp [hunk 5]
```diff
@@ -57,6 +59,7 @@ void CheatsReset()
     gameState.Cheats.AllowSpecialColourSchemes = false;
     gameState.Cheats.MakeAllDestructible = false;
     gameState.Cheats.SelectedStaffSpeed = StaffSpeedCheat::None;
+    gameState.Cheats.ForcedParkRating = kForcedParkRatingDisabled;
```
Comment (Harry-Hopkinson) [inline src/openrct2/Cheats.cpp:62]: Remember to change ` ForcedParkRating`  to the renamed ` forcedParkRating` .

File: src/openrct2/Cheats.cpp [hunk 6]
```diff
@@ -115,6 +118,7 @@ void CheatsSerialise(DataSerialiser& ds)
         CheatEntrySerialise(ds, CheatType::MakeDestructible, gameState.Cheats.MakeAllDestructible, count);
         CheatEntrySerialise(ds, CheatType::SetStaffSpeed, gameState.Cheats.SelectedStaffSpeed, count);
         CheatEntrySerialise(ds, CheatType::IgnorePrice, gameState.Cheats.IgnorePrice, count);
+        CheatEntrySerialise(ds, CheatType::SetForcedParkRating, gameState.Cheats.ForcedParkRating, count);
```
Comment (Harry-Hopkinson) [inline src/openrct2/Cheats.cpp:121]: Same applies here.

File: src/openrct2/Cheats.cpp [hunk 7]
```diff
@@ -222,6 +226,8 @@ void CheatsSerialise(DataSerialiser& ds)
                 case CheatType::SetStaffSpeed:
                     ds << gameState.Cheats.SelectedStaffSpeed;
                     break;
+                case CheatType::SetForcedParkRating:
+                    ds << gameState.Cheats.ForcedParkRating;
```
Comment (Harry-Hopkinson) [inline src/openrct2/Cheats.cpp:230]: Same applies here as well.

File: src/openrct2/world/Park.cpp [hunk 8]
```diff
@@ -395,12 +392,13 @@ namespace OpenRCT2::Park
 
     int32_t CalculateParkRating()
     {
-        if (_forcedParkRating >= 0)
+        auto& gameState = GetGameState();
+
+        if (gameState.Cheats.ForcedParkRating != kForcedParkRatingDisabled)
```
Comment (Harry-Hopkinson) [inline src/openrct2/world/Park.cpp:397]: Same applies here.

File: src/openrct2/world/Park.cpp [hunk 9]
```diff
@@ -734,15 +732,15 @@ namespace OpenRCT2::Park
 
     void SetForcedRating(int32_t rating)
     {
-        _forcedParkRating = rating;
+        GetGameState().Cheats.ForcedParkRating = rating;
```
Comment (Harry-Hopkinson) [inline src/openrct2/world/Park.cpp:735]: Same here.

File: src/openrct2/world/Park.cpp [hunk 10]
```diff
@@ -734,15 +732,15 @@ namespace OpenRCT2::Park
...
         GetGameState().Park.Rating = CalculateParkRating();
         auto intent = Intent(INTENT_ACTION_UPDATE_PARK_RATING);
         ContextBroadcastIntent(&intent);
     }
 
     int32_t GetForcedRating()
     {
-        return _forcedParkRating;
+        return GetGameState().Cheats.ForcedParkRating;
```
Comment (Harry-Hopkinson) [inline src/openrct2/world/Park.cpp:743]: Same here.,

**Review by Harry-Hopkinson — APPROVED** [review]
Thanks for making the changes.

File: src/openrct2/Cheats.h [hunk 11]
```diff
@@ -134,6 +135,7 @@ constexpr int kCheatsDuckIncrement = 20;
 constexpr int kCheatsStaffFastSpeed = 0xFF;
 constexpr int kCheatsStaffNormalSpeed = 0x60;
 constexpr int kCheatsStaffFreezeSpeed = 0;
+const int32_t kForcedParkRatingDisabled = -1;
```
Comment (ZehMatt) [inline src/openrct2/Cheats.h:138]:
```suggestion
constexpr int32_t kForcedParkRatingDisabled = -1;
```

File: src/openrct2/world/Park.cpp [hunk 12]
```diff
@@ -734,15 +732,15 @@ namespace OpenRCT2::Park
 
     void SetForcedRating(int32_t rating)
     {
-        _forcedParkRating = rating;
+        GetGameState().Cheats.forcedParkRating = rating;
```
Comment (ZehMatt) [inline src/openrct2/world/Park.cpp:735]:
```suggestion
        auto& gameState = GetGameState();
        gameState.Cheats.forcedParkRating = rating;
```
Also adjust the line below.

**Review by ZehMatt — CHANGES_REQUESTED** [review]
Seems overall alright, few remarks.

File: src/openrct2/world/Park.cpp [hunk 13]
```diff
@@ -734,15 +732,16 @@ namespace OpenRCT2::Park
 
     void SetForcedRating(int32_t rating)
     {
-        _forcedParkRating = rating;
+        auto& gameState = GetGameState();
+        gameState.Cheats.forcedParkRating = rating;
         GetGameState().Park.Rating = CalculateParkRating();
```
Comment (ZehMatt) [inline src/openrct2/world/Park.cpp:737]: You forgot to edit this line.

**Review by ZehMatt — CHANGES_REQUESTED** [review]

**Review by ZehMatt — APPROVED** [review]
Code looks alright, only needs clang-format fixed to make the CI happy.

**Review by Harry-Hopkinson — APPROVED** [review]

**Comment by ZehMatt** [comment]
Before this gets merged we need to not forget to raise the network version.

**Comment by RedMarcher** [comment]
> Before this gets merged we need to not forget to raise the network version.

So what does this mean exactly? Is this something I do, or something you guys do?

**Comment by tupaschoal** [comment]
> So what does this mean exactly? Is this something I do, or something you guys do?

You can do, just go here and change the constant to the next number:
https://github.com/OpenRCT2/OpenRCT2/blob/290b39ade2d70835b001621ac616311b5889abb0/src/openrct2/network/NetworkBase.cpp#L52

File: src/openrct2/network/NetworkBase.cpp [hunk 14]
```diff
@@ -49,7 +49,7 @@ using namespace OpenRCT2;
 // It is used for making sure only compatible builds get connected, even within
 // single OpenRCT2 version.
 
-constexpr uint8_t kNetworkStreamVersion = 0;
+constexpr uint8_t kNetworkStreamVersion = 1;
```
Comment (ZehMatt) [inline src/openrct2/network/NetworkBase.cpp:52]: https://github.com/OpenRCT2/OpenRCT2/blob/290b39ade2d70835b001621ac616311b5889abb0/src/openrct2/network/NetworkBase.cpp#L52
This is already at 1 in the current develop branch, please rebase first and then raise it again.

Comment (Gymnasiast) [reply src/openrct2/network/NetworkBase.cpp:52]: It will be at 2 within a few minutes, better to wait a bit (an hour is more than sufficient).

**Comment by Gymnasiast** [comment]
@duncanspumpkin Does this PR require changes to cheats serialisation and/or a park file version bump?

**Comment by ZehMatt** [comment]
> @duncanspumpkin Does this PR require changes to cheats serialisation and/or a park file version bump?

No, cheats are serialized via count and type so we don't need a new version.

**Comment by Gymnasiast** [comment]
Adding new features that are saved have always come with at least a "soft bump", that is a bump of the version number, while leaving the minimum version as is.

(Also asked Duncan via DM and he confirmed as much.)

**Review by Gymnasiast — APPROVED** [review]

**Review by ZehMatt — APPROVED** [review]
