### PR TITLE
Fix #5507: RCT1 path check is case-sensitive on Linux

### LINKED ISSUE #5507: RCT1 path check is case-sensitive on Linux
**OS:** Linux
**Version:** 0.0.8
**Commit/Build:** latest

The check for `csg1.1` and `csg1.dat` on setting an RCT1 path is case sensitive - lower case works, upper case does not.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Clear your RCT1 path if set.
2. Rename `csg1.dat` to `CSG1.DAT`.
3. Try to set the RCT1 path again.
4. OpenRCT2 says the directory is invalid.

EDIT: This bug does **not** occur on macOS.

### PR DESCRIPTION
**Pull request by IntelOrca**
If the csg path does not exist, find the first file in the directory that matches (case insensitive).

**Note:** this does not fix the casing of the `Data` directory.

### CODE REVIEW

File: src/openrct2/drawing/sprite.cpp [hunk 1]
```diff
@@ -188,41 +189,53 @@ extern "C"
...
+        if (str_is_null_or_empty(gConfigGeneral.rct1_path))
         {
-            safe_strcpy(pathData, gConfigGeneral.rct1_path, sizeof(pathData));
-            safe_strcat_path(pathData, "Data", sizeof(pathData));
-            safe_strcat_path(pathData, "csg1.dat", sizeof(pathData));
+            log_verbose("  unable to load CSG, RCT1 path not set");
+            return false;
         }
 
+        auto pathHeaderPath = std::unique_ptr<utf8>(gfx_get_csg_header_path());
```
Comment (janisozaur) [inline src/openrct2/drawing/sprite.cpp]: This will call (default) `delete` on `malloc`-allocated buffer

**Comment by janisozaur** [comment]
I honestly don't understand some of the design choices for our string class (or why do we have it at all in the first place).

`utf8 * Duplicate(const std::string &src)` will call `utf8 * Duplicate(const utf8 * src)`, which will call `size_t SizeOf(const utf8 * str)`, which is basically a wrapper for `strlen`, so we have to spend time inspecting length of the string, value which we can extract from `std::string` that we begin our journey with.

**Comment by IntelOrca** [comment]
There only for the jumping between C and C++ code.
