### PR TITLE
Fix #11526: Plugin: Crash when using sprite type in park.postMessage

### LINKED ISSUE #11526: Plugin: Crash when using sprite type in park.postMessage
**OS:** Windows 10
**Version:** 0.2.6-362
**Commit/Build:** 96222ebac

When using the function `park.postMessage` with a message type that required a sprite to be drawn, a crash occurs when the game tries to draw it. This seems to be caused by the sprite ID for the message having an invalid index of -1.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Create a simple script that posts a message using the "peep" type
2. Open any park

**Script**
```js
var main = function () {
	park.postMessage({
		type: 'peep_on_attraction',
		text: 'Hello Park!'
	});
};
registerPlugin({
    name: 'test',
    version: '0.1',
    authors: ['test'],
    type: 'local',
    main: main
});

```

### PR DESCRIPTION
**Pull request by IntelOrca**
- Add safety checks for subject.
- Implement subject as another property in `postMessage`.
- Support formatted strings in `postMessage`.

### CODE REVIEW

File: src/openrct2/peep/Peep.cpp [hunk 1]
```diff
@@ -329,6 +329,11 @@ bool rct_sprite::IsPeep() const
     return peep.sprite_identifier == SPRITE_IDENTIFIER_PEEP;
 }
 
+bool rct_sprite::IsVehicle() const
+{
+    return peep.sprite_identifier == SPRITE_IDENTIFIER_VEHICLE;
+}
```
Comment (Broxzier) [inline src/openrct2/peep/Peep.cpp:335]: Wouldn't this be better to defined in `src/openrct2/ride/Vehicle.cpp` and use the `vehicle` identifier rather than `peep`?

File: src/openrct2/peep/Peep.cpp [hunk 2]
```diff
@@ -339,6 +344,16 @@ Peep* rct_sprite::AsPeep()
...
 
+Vehicle* rct_sprite::AsVehicle()
+{
+    Vehicle* result = nullptr;
+    if (IsVehicle())
+    {
+        return reinterpret_cast<Vehicle*>(this);
+    }
+    return result;
+}
```
Comment (Broxzier) [inline src/openrct2/peep/Peep.cpp:355]: Same as the previous comment.

Comment (IntelOrca) [reply src/openrct2/peep/Peep.cpp]: I wasn't using it in the end, so have removed it.

File: src/openrct2/peep/Peep.cpp (hunk 1 above)
Comment (IntelOrca) [reply src/openrct2/peep/Peep.cpp]: Leaving it as `peep` was an unintentional, nice spot. I didn't actually use these functions in the end, so have removed them.
