### PR TITLE
Fix #6667: Match sample rate to games audio content.

### LINKED ISSUE #6667: Scratchy Audio in 0.1.2
**OS:** Windows 10 x64 (Fall Creators update)
**Version:** 0.1.2
**Commit/Build:** 5409ded

I've noticed that since last Saturday or Sunday (so probably an eariler commit before this), all of the music in the game sounds noticeably more scratchy. I've compared this to the stable build and the stable build sounds much better. It is only an issue with the music.

- [ ] Reproducible in RCT2 (vanilla)?

- [x] Multiplayer?

**Steps to reproduce:**
1. Download Development build
2. Open the game, it is immediately noticeable in the title music.

### PR DESCRIPTION
**Pull request by ZehMatt**
Apparently SDL is not capable of converting streams properly and adds zero padding therefor the crackle noise as seen here https://github.com/spurious/SDL-mirror/blob/master/src/audio/SDL_audiocvt.c#L726

The solution is to set the frequency back to 22050hz which matches the games audio content so no conversion is required. The other possible solution is to pre-convert everything but adds quite the loading time.

Also keep in mind this noise only happens when audio is upsampled while downsampling should be okay.

### CODE REVIEW

File: src/openrct2-ui/audio/MemoryAudioSource.cpp [hunk 1]
```diff
@@ -159,44 +171,62 @@ namespace OpenRCT2 { namespace Audio
...
+            return _isLoading;
+        }
+
+        virtual bool Convert(const AudioFormat * format) override
         {
             if (*format != _format)
             {
-                SDL_AudioCVT cvt;
-                if (SDL_BuildAudioCVT(&cvt, _format.format, _format.channels, _format.freq, format->format, format->channels, format->freq) >= 0)
+                if (true)
```
Comment (janisozaur) [inline src/openrct2-ui/audio/MemoryAudioSource.cpp]: what's the point of this `if`?

Comment (ZehMatt) [reply src/openrct2-ui/audio/MemoryAudioSource.cpp]: Disables or enables the threading for now, question will be do we want this. Thats why I left it there.

**Comment by Patrik356b** [comment]
@ZehMatt I'd assume the other solution would just be a one-time event, like the extra long loading time when running RCT2 for the first time. (otherwise it's not a good solution)

**Comment by ZehMatt** [comment]
No thats not what I meant.

**Comment by Patrik356b** [comment]
Could you please elaborate then?

If your other solution is meant to bundle the pre-converted files with OpenRCT2, wouldn't it significantly increase the download size?

**Comment by AaronVanGeffen** [comment]
@Patrik356b This PR sets the frequency and sampling rate to match RCT2's original files, thereby removing the need for any conversion or resampling.

**Comment by Gymnasiast** [comment]
Tested it. It does indeed get rid of pops I heard on `develop`. Although I do think we'll need a better solution in the long run. I don't think we'll want to stick with 22,050 Hz once the music project gets anywhere near completion.

**Comment by ZehMatt** [comment]
We also need to hope that SDL ever adds a streaming state so we can convert chunk by chunk on demand instead of pre-converting the entire track all at once.

**Comment by Patrik356b** [comment]
@AaronVanGeffen

That wasn't what I was asking @ZehMatt about.
