### PR TITLE
Fix #24289: Prebuilt track designs using an invalid drawing state

### LINKED ISSUE #24289: Game crashes whenever a ride type with saved designs is selected
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.21 (0d96235f32 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

Happens in this dev build only, not before it. Happens with both software and OpenGL rendering.

### Steps to reproduce

1. Try to build a ride type that has saved designs.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by ZehMatt**
I don't know how I missed that one, I specifically looked for anything that creates the X8DrawingEngine.

Close #24289

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]

File: src/openrct2/ride/TrackDesign.cpp [hunk 1]
```diff
@@ -2141,6 +2143,8 @@ void TrackDesignDrawPreview(TrackDesign& td, uint8_t* pixels)
         dpi.bits += kTrackPreviewImageSize;
     }
 
+    drawingEngine->EndDraw();
+
```
Comment (tupaschoal) [inline src/openrct2/ride/TrackDesign.cpp:2147]: We could likely be using RAII to make these neater with something like:

```c++
struct DrawingScope
{
    DrawingScope(auto* drawingEngine)
        : m_drawingEngine(drawingEngine)
    {
        m_drawingEngine->BeginDraw();
    }
    ~DrawingScope()
    {
        m_drawingEngine->EndDraw();
    }
    auto* drawingEngine;
}
```

**Review by tupaschoal — APPROVED** [review]

File: src/openrct2/ride/TrackDesign.cpp (hunk 1 above)
Comment (ZehMatt) [reply src/openrct2/ride/TrackDesign.cpp:2147]: Perhaps, however I'm not sure its also worth it as this happens about 3 times. I'll consider it in the next cleansing PRs
