### PR TITLE
Fix ride music related desyncs

### LINKED ISSUE #1968: Multiplayer desynchronises without any player input.
This is the first desynchronise issue that should be properly investigated. Something unrelated to player actions is causing a desync. The length of time a client will stay connected for varies but seems to be shorter for parks containing a lot of stuff - its likely some kind of game logic is using client specific state to determine its logic or something is not being initialised properly.

### PR DESCRIPTION
**Pull request by zsilencer**
I think this might fix #1968 finally

### CODE REVIEW

File: src/peep/peep.c [hunk 1]
```diff
@@ -610,19 +611,24 @@ static uint8 peep_assess_surroundings(sint16 center_x, sint16 center_y, sint16 c
 					break;
 				case MAP_ELEMENT_TYPE_TRACK:
 					ride = get_ride(mapElement->properties.track.ride_index);
+					if (ride->lifecycle_flags & RIDE_LIFECYCLE_MUSIC &&
+						ride->status != RIDE_STATUS_CLOSED &&
+						!(ride->lifecycle_flags & (RIDE_LIFECYCLE_BROKEN_DOWN | RIDE_LIFECYCLE_CRASHED))){
+						music_on = true;
+					}
```
Comment (IntelOrca) [inline src/peep/peep.c]: All the if blocks below this line can be moved into the if block above removing the need for `music_on`
