### PR TITLE
Prevent peeps walking up and back down ride queues

### LINKED ISSUE #3499: Guests can enter closed queue lines
**OS:** win10
**Version:** 0.0.5 develop
**Commit:** d8068a4

(this is the issue raised in the comments of #3271 )
If two queue lines from the same ride are on the opposite side of a path tile, guests can enter the queue without joining the queue, they'll walk to the end and back. Same for a queue and a shop. Two queue lines from different rides doesn't seem to trigger the issue.
I can't test anything in vanilla.

**Steps to reproduce:**
1. Open this save and watch

**Screenshots / Video:**
scr104

**Save game:**
[ClosedQueue.zip](https://github.com/OpenRCT2/OpenRCT2/files/250956/ClosedQueue.zip)

### PR DESCRIPTION
**Pull request by zaxcav**
This bug is caused by inconsistent use of peep->interactionRideIndex.

The primary use of this value is to record when a peep has decided to go on the ride at the queue entrance so they remember that decision when entering each queue path tile - without this they would re-decide whether to go on the ride each time they walk into a new ride queue tile while queuing.
This is also important for making the peeps walk up and back out of the queue when the ride gets closed.

This value is also set when a peep decides not to go on a ride (though the reason why is not clear to me), but is not reset/changed on interaction with other tile types (e.g. shops) causing peeps who bounce back on a ride queue entrance to walk up and down the queue.

Also added comments to peep.c documenting the use of peep->interactionRideIndex

Fixes #3499

Requires new network version.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Thanks! I love the added comments about as much as the actual fix.

File: src/openrct2/peep/peep.c [hunk 1]
```diff
@@ -8321,36 +8341,56 @@ static sint32 peep_interact_with_path(rct_peep* peep, sint16 x, sint16 y, rct_ma
...
+			// Case 1 above applies, so walk the queue.
 			return peep_footpath_move_forward(peep, x, y, map_element, vandalism_present);
 		}
 
+		// Case 2 above applies - decide whether to go on the ride.
 		peep->var_F4 = 0;
 		uint8 stationNum = (map_element->properties.path.additions & 0x70) >> 4;
 		if (!peep_should_go_on_ride(peep, rideIndex, stationNum, PEEP_RIDE_DECISION_AT_QUEUE)){
-			peep->interactionRideIndex = rideIndex;
+			// Peep has decided not to go on the ride.
```
Comment (duncanspumpkin) [inline src/openrct2/peep/peep.c]: Correct me if wrong but I thought the reason it set the interactionRideIndex was to prevent it from considering going on this ride again until it had tried a different ride. So really we should change Case 1 to check that it has been added to the queue rather than change case 2.

Comment (zaxcav) [inline src/openrct2/peep/peep.c]: It's inconsistent (in my opinion).
In some places it is used like this ... although it's effect is limited to within a single path tile. As soon as a peep walks into another tile it's reset. Problem is it's used inconsistently for this purpose.  E.g. Interacting with a shop doesn't reset it, so bouncing off a shop back onto the ride queue results in the peep walking up the queue.
 
The main (and more important) use of interactionRideIndex is to let the peep walk up the queue when actually queuing and also and walk out of the queue when not queuing.

This particular line (8347 in the original) is critical for letting the peep walk back out of the queue when they aren't queuing. Without it they get stuck in the queue. Removing this fixed peeps walking into queues when they shouldn't, but trapped peeps trying to get back out of a queue - quite a regression.
A much improved fix is in #5442 commit ef1bdba - it probably shouldn't been part of that PR, but that's where the above regression was identified.
