### PR TITLE
Fix #8199: Crash using player id as index.

### LINKED ISSUE #8199: BACKTRACE d79955
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/d79955bf16944ad026bb590059b23ef8e016c2ef9a99df8f5ca6b467073d86c3?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Nov 01 2018 11:30:12)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 698426d: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>GameActions::Execute -> Network::ProcessGameCommandQueue -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by ZehMatt**
Another hard to find bug since the player id and player index are identical the very first few players until someone disconnects and reconnects.

### CODE REVIEW

File: src/openrct2/actions/GameAction.cpp [hunk 1]
```diff
@@ -197,12 +197,13 @@ namespace GameActions
...
-                    uint32_t playerId = action->GetPlayer();
+                    const uint32_t playerId = action->GetPlayer();
+                    const uint32_t playerIndex = network_get_player_index(playerId);
 
-                    network_set_player_last_action(network_get_player_index(playerId), action->GetType());
+                    network_set_player_last_action(playerIndex, action->GetType());
                     if (result->Cost != 0)
                     {
-                        network_add_player_money_spent(playerId, result->Cost);
+                        network_add_player_money_spent(playerIndex, result->Cost);
```
Comment (janisozaur) [inline src/openrct2/actions/GameAction.cpp]: Given how easy it is to confuse the two:
a) why do we even have two of them in the first place?
b) they should have incompatible types, so they cannot be such easily confused.

Comment (ZehMatt) [reply src/openrct2/actions/GameAction.cpp]: The game action logging PR introduces new types for this stuff, it needs some cleaning afterwards to adopt everything later to the new game action system rather than the old game command enums and types.
