### PR TITLE
Fix #19722: Forbid removal of large trees if scenario forbids it

### LINKED ISSUE #19722: "Forbid tree removal" restriction doesn't forbid removal of large scenery tree items
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT v0.4.3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

In RCT2 vanilla the 'forbid tree removal' restriction was implemented wonky and just disabled removing any small scenery item taller than about 4 units. 

This was mostly fixed years ago, but you can still remove any trees that are larger than 1x1 tile, aka large tree scenery items.

### Steps to reproduce

Open a scenario with the tree removal restriction.
Build a large tree scenery item.
Try to remove it.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by krrg**
Previously only small trees were prevented from being removed in scenarios with the "forbid tree removal" flag. This change expands this behavior to similarly prevent large trees from being removed.

NoRemoveBigTree_Screenshot_20230831_175615

### CODE REVIEW

**Review by Broxzier — CHANGES_REQUESTED** [review]
Changes LGTM. Need a network version bump.

File: src/openrct2/object/LargeSceneryEntry.h [hunk 1]
```diff
@@ -74,6 +74,11 @@ struct LargeSceneryEntry
     uint8_t scrolling_mode;
     LargeSceneryText* text;
     uint32_t text_image;
+
+    constexpr bool HasFlag(const uint32_t _flags) const
```
Comment (duncanspumpkin) [inline src/openrct2/object/LargeSceneryEntry.h:78]: flags are uint16_t

Comment (krrg) [reply src/openrct2/object/LargeSceneryEntry.h:78]: Ah, good catch. I'll update the enum with `: uint16_t` as well if that's okay.

**Review by Broxzier — APPROVED** [review]

File: distribution/changelog.txt [hunk 2]
```diff
@@ -3,14 +3,15 @@
 - Change: [#20790] Default ride price set to free if park charges for entry.
 - Fix: [#20737] Spent money in player window underflows when getting refunds.
 - Fix: [#20778] [Plugin] Incorrect target api when executing custom actions.
+- Fix: [#19722] Forbid removal of large trees if scenario forbids tree removal
```
Comment (Broxzier) [inline distribution/changelog.txt:6]: Approved too quickly. Fixed should state what was broken, not what has changed. The full stop is also missing.

```suggestion
- Fix: [#19722] “Forbid tree removal” restriction doesn't forbid removal of large scenery tree items.
```

**Review by Broxzier — CHANGES_REQUESTED** [review]
