### PR TITLE
Fix #14217: Crash in large_scenery_paint()

### LINKED ISSUE #14217: [fb1712] openrct2.exe: large_scenery_paint, sub_68B3FB, PaintSessionGenerate, JobPool::ProcessQueue, std::thread::_Invoke<std...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/fb1712012d05745a105bb000b005edd52f946bc8cd8a1508af6e84dbadcc9087">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\tpkre\Documents\OpenRCT2\a91ad9cd-fabe-48b2-bb92-9b3ac6e6a4b6.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\tpkre\Documents\OpenRCT2\a91ad9cd-fabe-48b2-bb92-9b3ac6e6a4b6.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\tpkre\Documents\OpenRCT2\a91ad9cd-fabe-48b2-bb92-9b3ac6e6a4b6.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\tpkre\Documents\OpenRCT2\screenshot\WITCHTOPIA 2021-03-02 23-48-47.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>2c3c014</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
large_scenery_paint
sub_68B3FB
PaintSessionGenerate
JobPool::ProcessQueue
std::thread::_Invoke&lt;std::tuple&lt;void ( JobPool::*)(void),JobPool *&gt;,0,1&gt;
thread_start&lt;unsigned int (*)(void *),1&gt;</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/paint/tile_element/Paint.LargeScenery.cpp [hunk 1]
```diff
@@ -233,6 +233,9 @@ void large_scenery_paint(paint_session* session, uint8_t direction, uint16_t hei
 
     uint32_t image_id = (sequenceNum << 2) + entry->image + 4 + direction;
     rct_large_scenery_tile* tile = &entry->large_scenery.tiles[sequenceNum];
+    if (tile == nullptr)
```
Comment (duncanspumpkin) [inline src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:236]: Is this actually possible? Isn't the address always going to real. Perhaps we should be checking instead that sequence number is within tiles size

Comment (Gymnasiast) [reply src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:236]: If it isn't possible, how do you explain #14217 crashing on line 259/262, where it references `tile`? ;-)

Comment (duncanspumpkin) [reply src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:236]: I just don't think it would create an npe it should be creating some bad memory access instead.

Comment (IntelOrca) [reply src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:236]: @Gymnasiast make sure to check the `fault.address` which on this issue is 0x07, so not a null pointer exception but still an access violation. This fix will not resolve the issue, unless the out of bounds memory just happened to be 0. What I suggest doing is creating a helper method on LargeSceneryElement that returns `nullptr` if sequenceNum is out of bounds.

Comment (Gymnasiast) [reply src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:236]: It's hard to tell, since I cannot reproduce the crash myself. Can't we just check for both?

Comment (Gymnasiast) [reply src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:236]: OK, should I check using `std::size(tiles)`?

Comment (IntelOrca) [reply src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:236]: `rct_large_scenery_entry` doesn't have the number of tiles, but `LargeSceneryObject` does. You could either fetch that instance to get the total number of tiles, or you could add a new field to `rct_large_scenery_entry`. Although technically we should be moving towards the new Object classes for information rather than continue to use the old entry structs.

Comment (Gymnasiast) [reply src/openrct2/paint/tile_element/Paint.LargeScenery.cpp:241]: OK, that should be it.

**Review by IntelOrca — APPROVED** [review]
