### PR TITLE
Fix #19782: Game stops counting inversions after 31

### LINKED ISSUE #19782: Game stops counting inversions after 31
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.3 (62b0a5e on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

If you build a coaster with more than 31 inversions, the game stops counting. The stats will always read 31.

### Steps to reproduce

Build a coaster with more than 31 inversions
Test and view stats

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/Limits.h [hunk 1]
```diff
@@ -17,7 +17,7 @@ namespace OpenRCT2::Limits
     constexpr uint8_t kCustomerHistorySize = RCT12::Limits::kCustomerHistorySize;
     constexpr uint16_t kMaxGolfHoles = RCT12::Limits::kMaxGolfHoles;
     constexpr uint16_t kMaxHelices = RCT12::Limits::kMaxHelices;
-    constexpr uint16_t kMaxInversions = RCT12::Limits::kMaxInversions;
+    constexpr uint16_t kMaxInversions = std::numeric_limits<uint16_t>::max();
```
Comment (AaronVanGeffen) [inline src/openrct2/Limits.h:20]: Ironically, for a file named Limits.h, <limits> has not yet been included.

**Comment by janisozaur** [comment]
Bump the network version as well - park version probably too? Does it get serialized into the file?

**Comment by AaronVanGeffen** [comment]
> Bump the network version as well - park version probably too? Does it get serialized into the file?

Hmm, not sure it'll be necessary. It's already being serialised to a uint8_t, right? Just capped.

**Comment by Gymnasiast** [comment]
It’s serialised into a uint16_t. It is indeed not necessary to bump to park file version, but I will bump the network version.

File: src/openrct2/Limits.h [hunk 2]
```diff
@@ -8,16 +8,19 @@
...
+#include <limits>
+
 namespace OpenRCT2::Limits
 {
     constexpr uint16_t kMaxRidesInPark = 1000;
     constexpr uint16_t kMaxStationsPerRide = 255;
     constexpr uint8_t kCustomerHistorySize = RCT12::Limits::kCustomerHistorySize;
     constexpr uint16_t kMaxGolfHoles = RCT12::Limits::kMaxGolfHoles;
     constexpr uint16_t kMaxHelices = RCT12::Limits::kMaxHelices;
-    constexpr uint16_t kMaxInversions = RCT12::Limits::kMaxInversions;
```
Comment (tupaschoal) [inline src/openrct2/Limits.h:20]: Isn't `RCT12::Limits::kMaxInversions` now unused?

File: src/openrct2/Limits.h [hunk 3]
```diff
@@ -8,16 +8,19 @@
...
 
+#include <limits>
+
 namespace OpenRCT2::Limits
 {
     constexpr uint16_t kMaxRidesInPark = 1000;
     constexpr uint16_t kMaxStationsPerRide = 255;
     constexpr uint8_t kCustomerHistorySize = RCT12::Limits::kCustomerHistorySize;
     constexpr uint16_t kMaxGolfHoles = RCT12::Limits::kMaxGolfHoles;
     constexpr uint16_t kMaxHelices = RCT12::Limits::kMaxHelices;
```
Comment (tupaschoal) [inline src/openrct2/Limits.h:22]: These are also `31`, should we take the chance to update them as well?

File: src/openrct2/Limits.h (hunk 2 above)
Comment (Gymnasiast) [reply src/openrct2/Limits.h:20]: Probably yes. Not sure if we should remove it, though.

File: src/openrct2/Limits.h (hunk 3 above)
Comment (tupaschoal) [reply src/openrct2/Limits.h]: I found out that helices are stored on the last 5 bits of `special_track_elements`, so they shouldn't be changed arbitrarily because everything there might break, therefore I added 9a455774dd4e7f7970dcff6cd8b18f73170be07d to warn if anyone wants to change it.

In any case, it seems that for ride ratings they are never shown explicitly, nor accounted for when over 15
https://github.com/OpenRCT2/OpenRCT2/blob/930e215103752fec1f6f02c1ce25a6805e9c4efb/src/openrct2/ride/RideRatings.cpp#L1588-L1595

Comment (tupaschoal) [reply src/openrct2/Limits.h]: As for golf holes, I removed the cap since they are stored separately. That does make it possible to theoretically infinitely boost the excitement of a mini golf:
https://github.com/OpenRCT2/OpenRCT2/blob/930e215103752fec1f6f02c1ce25a6805e9c4efb/src/openrct2/ride/RideRatings.cpp#L2031-L2035
But it is such a tiny bump compared to the other bonuses, that I think we're fine.
https://github.com/OpenRCT2/OpenRCT2/blob/930e215103752fec1f6f02c1ce25a6805e9c4efb/src/openrct2/ride/rtd/gentle/MiniGolf.h#L63-L69

File: src/openrct2/Limits.h (hunk 2 above)
Comment (tupaschoal) [reply src/openrct2/Limits.h:20]: I commented them out on 48073edb7e6cd1287a0a67e744368517c5cb3e47

**Review by tupaschoal — COMMENTED** [review]
@Gymnasiast I took the liberty of investigating my own comments and sharing what I found.

**Comment by Gymnasiast** [comment]
I want to take a proper look, so I’ll take some more time. It’s not like this is a very pressing issue.

**Comment by astraylife1** [comment]
Keep open

**Comment by xrgtmx** [comment]
Merge for 0.4.17?

**Comment by astraylife1** [comment]
Would be nice to see this implemented

**Comment by tupaschoal** [comment]
@Gymnasiast have you had a chance to check this (and my considerations)?

File: distribution/changelog.txt [hunk 4]
```diff
@@ -189,6 +189,7 @@
 - Fix: [#2614] The colour tab of the ride window does not hide invisible cars (original bug).
 - Fix: [#7672] Wide path status is set to all ‘wide’ paths, instead of only a quarter, impeding pathfinding.
 - Fix: [#15406] Tunnels on steep Side-Friction track are drawn too low.
+- Fix: [#19782] Game stops counting inversions and golf holes after 31.
```
Comment (Gymnasiast) [inline distribution/changelog.txt:192]: Move to v0.4.21

File: src/openrct2/rct12/Limits.h [hunk 5]
```diff
@@ -40,8 +40,9 @@ namespace OpenRCT2::RCT12::Limits
 
     constexpr uint16_t kRideMeasurementMaxItems = 4800;
 
-    constexpr uint16_t const kMaxInversions = 31;
-    constexpr uint16_t const kMaxGolfHoles = 31;
+    // The following are not being used anymore, but have been left commented out as documentation
+    // constexpr uint16_t const kMaxInversions = 31;
+    // constexpr uint16_t const kMaxGolfHoles = 31;
```
Comment (Gymnasiast) [inline src/openrct2/rct12/Limits.h:45]: Revert this, it doesn’t really hurt having them.

File: src/openrct2/ride/Vehicle.cpp [hunk 6]
```diff
@@ -1093,6 +1093,8 @@ void Vehicle::UpdateMeasurements()
         if (trackFlags & TRACK_ELEM_FLAG_HELIX)
         {
             uint8_t helixes = RideGetHelixSections(*curRide);
+            // helixes are stored on the last 5 bits of special_track_elements
+            // *DO NOT* change limits over 31 without revisiting this logic
```
Comment (Gymnasiast) [inline src/openrct2/ride/Vehicle.cpp:1097]: I think I’m just going to make this field private and have getters and setters, so that this isn’t a problem anymore.

**Comment by Gymnasiast** [comment]
@astraylife1 Since you created the issue, would you take this for a spin?

**Comment by astraylife1** [comment]
The inversions were counting correctly for me, though the number of drops stops counting at 63.

**Comment by Gymnasiast** [comment]
Right, I’ll go and check the drops.

File: src/openrct2/ride/Ride.h [hunk 7]
```diff
@@ -53,10 +53,8 @@ constexpr uint16_t kMaxStationLocations = OpenRCT2::Limits::kMaxStationsPerRide
 
 constexpr uint16_t kMazeClearanceHeight = 4 * kCoordsZStep;
 
-constexpr uint8_t kRideMaxDropsCount = 63;
-constexpr uint8_t kRideNumDropsMask = 0b00111111;
-constexpr uint8_t kRideMaxNumPoweredLiftsCount = 3;
-constexpr uint8_t kRideNumPoweredLiftsMask = 0b11000000;
+constexpr uint8_t kRideMaxDropsCount = std::numeric_limits<uint8_t>::max();
+constexpr uint8_t kRideMaxNumPoweredLiftsCount = std::numeric_limits<uint8_t>::max();
```
Comment (Gymnasiast) [inline src/openrct2/ride/Ride.h:57]: Move to Limits.h

File: src/openrct2/ride/Vehicle.cpp [hunk 8]
```diff
@@ -1100,22 +1102,21 @@ void Vehicle::UpdateMeasurements()
...
         {
-            uint8_t helixes = RideGetHelixSections(*curRide);
-            if (helixes != OpenRCT2::Limits::kMaxHelices)
+            auto helixes = curRide->numHelices;
+            if (helixes < OpenRCT2::Limits::kMaxHelices)
                 helixes++;
 
-            curRide->specialTrackElements &= ~0x1F;
-            curRide->specialTrackElements |= helixes;
+            curRide->numHelices = helixes;
```
Comment (Gymnasiast) [inline src/openrct2/ride/Vehicle.cpp:1119]: Modify directly, like the others.

**Comment by Gymnasiast** [comment]
@astraylife1 Can you check this again?

**Comment by astraylife1** [comment]
The MacOS x64 download was missing the G2.dat file but I was still able to test. The drops and inversions now have an upper limit of 255.

**Comment by Gymnasiast** [comment]
> The MacOS x64 download was missing the G2.dat file

It sounds like you used the separate x86_64 build, rather than the universal build. Can you check if that one does ship with g2.dat: https://github.com/OpenRCT2/OpenRCT2/actions/runs/14430095830/artifacts/2935206766

(If it doesn’t, it might be a bug due to a recent change, so I want to double check.)

**Comment by James103** [comment]
> Can you check if [the universal build] does ship with g2.dat: https://github.com/OpenRCT2/OpenRCT2/actions/runs/14430095830/artifacts/2935206766
> 
> (If it doesn’t, it might be a bug due to a recent change, so I want to double check.)

The universal build does ship with g2.dat.

**Comment by astraylife1** [comment]
> > Can you check if [the universal build] does ship with g2.dat: https://github.com/OpenRCT2/OpenRCT2/actions/runs/14430095830/artifacts/2935206766
> > (If it doesn’t, it might be a bug due to a recent change, so I want to double check.)
> 
> I can confirm the MacOS x86-64 build `OpenRCT2-macOS-x64-cmake` does not have g2.dat, while the universal build `OpenRCT2-v0.4.21-27-gc47c66c535-macOS-universal` does ship with g2.dat.

Thanks. I wasn't able to test until now. All good.

**Comment by ZeeMaji** [comment]
Saving to TD6 seems to cause inversion count to overflow, i assume this is expected due to the inherent limitations of TD6?
ksnip_20250414-190509

**Comment by Gymnasiast** [comment]
It does that for a lot of properties. I could, however, add some code to at least gracefully maximise it.

Did you find any other bugs?

**Comment by ZeeMaji** [comment]
I did not, all s4/s6/park files i tested import stats as i'd expect. The only slight minor issue i noticed is old saves with rides that have over 31 inversions/holes aren't updated but i assume that is to be expected?

**Comment by Gymnasiast** [comment]
@ZeeMaji I pushed a commit to gracefully maximise some of the statistics when writing to TD6. Could you test that with one or two coasters?

**Comment by LordMarcel** [comment]
It now only counts up to 31 drops in saved designs instead of the 63 it used to do. Here on the left is a ride saved in the current dev version and on the right is one saved in this PR version.

image

**Comment by LordMarcel** [comment]
Also, this increase in max count for inversions also increases the mini golf hole as those are the same, and putting 255 holes on the minigolf gives it a lot of excitement. I think this is probably not a good thing to have so putting a limit on the number of holes that give excitement of 31 (the original limit) might be a handy thing to do.

image

**Comment by Gymnasiast** [comment]
> Also, this increase in max count for inversions also increases the mini golf hole as those are the same, 

Haven’t been the same since the NSF. They just happened to be increased in the same PR.

**Review by LordMarcel — APPROVED** [review]
Did some tests and found no bugs anymore.
