### PR TITLE
Guard against null ride types in peep AI. Fix #3790

### LINKED ISSUE #3790: Singleplayer Crash
**OS:** 
Windows 8.1

**Version:** 
OpenRCT2 Build: 853

It's just a crash to desktop after about 5 seconds of being in this park. It's a collaboration park but not in multiplayer.

**Steps to reproduce:**
1. Open the park in OpenRCT2
2. Wait

**Dump file**
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/292237/OpenRCT2.zip)

**Save game:**
[Spayculowse Asylum 9.zip](https://github.com/OpenRCT2/OpenRCT2/files/292239/Spayculowse.Asylum.9.zip)

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

File: src/peep/peep.c [hunk 1]
```diff
@@ -1668,6 +1668,9 @@ static void peep_go_to_ride_entrance(rct_peep* peep, rct_ride* ride){
 
 	uint8 shift_multiplier = 21;
 	rct_ride_entry* ride_type = get_ride_entry(ride->subtype);
+	if (ride_type == NULL) {
+		return;
+	}
```
Comment (IntelOrca) [inline src/peep/peep.c]: It might be better to instead skip the code that uses ride entry and vehicle entry. Let the peep still walk to the exit.

File: src/peep/peep.c [hunk 2]
```diff
@@ -2420,6 +2423,9 @@ void peep_update_ride_sub_state_7(rct_peep* peep){
 			}
 
 			ride_entry = get_ride_entry(ride->subtype);
+			if (ride_entry == NULL) {
+				return;
+			}
```
Comment (IntelOrca) [inline src/peep/peep.c]: It might be better to instead skip the code that uses ride entry and vehicle entry. Let the peep still walk to the exit.

File: src/peep/peep.c (hunk 1 above)
Comment (IntelOrca) [inline src/peep/peep.c]: Just skip the part that uses ride_type, let the peep go to the ride entrance.

**Comment by janisozaur** [comment]
How about now?

File: src/peep/peep.c [hunk 3]
```diff
@@ -2420,7 +2425,9 @@ void peep_update_ride_sub_state_7(rct_peep* peep){
 			}
 
 			ride_entry = get_ride_entry(ride->subtype);
-			vehicle_entry = &ride_entry->vehicles[ride_entry->default_vehicle];
+			if (ride_entry != NULL) {
+				vehicle_entry = &ride_entry->vehicles[ride_entry->default_vehicle];
+			}
```
Comment (IntelOrca) [inline src/peep/peep.c]: It needs to block further, vehicle_entry is used below

Comment (janisozaur) [inline src/peep/peep.c]: there is a valid `vehicle_entry` from before

**Comment by janisozaur** [comment]
It does not crash anymore, but please check if it looks valid to you.

**Comment by mrtnptrs** [comment]
I think someone forgot something here :P @IntelOrca

**Comment by Nubbie** [comment]
Seems like the map owner kinda want this fix :(
