### PR TITLE
Fix #19800. Crash when more than 62 stations on a ride

### LINKED ISSUE #19800: [a6fc6d] openrct2.com: ForceCrash, Guard::Assert_VA, Guard::Assert, WindowFindByNumber, ScreenCoordsXY::operator-, WindowRide...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/a6fc6d8b3285fd011f84f167a3f0836b42fea440fd655991cd3691d976ddb5eb">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>71000000-f888-da09-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\james\Documents\OpenRCT2\crash\81192db7-35c3-4420-803b-33fe45072e99.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>Increment is greater than buffer size!</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.4-25-gde06f60 (de06f60 on develop) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_WRITE</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li>de06f60 &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-write</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
ForceCrash
Guard::Assert_VA
Guard::Assert
WindowFindByNumber
ScreenCoordsXY::operator-
WindowRideMeasurementsPaint
WindowEventPaintCall
WindowDrawSingle
WindowDrawCore
WindowDraw
invoke
std::_Invoker_ret&lt;void&gt;::_Call
std::_Func_impl_no_alloc&lt;`WindowDrawAll&#39;::`2&#39;::&lt;lambda_1&gt;,void,WindowBase *&gt;::_Do_call
WindowVisitEach(std::function&lt;void __cdecl
WindowDrawAll
OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::Draw
OpenRCT2::Context::RunFixedFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main
UnhandledExceptionFilter</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by duncanspumpkin**
This is a bit of a temporary fix. The crash happens due to exhausting the space in the formatter but the format string only ever handled 4 stations so it was still not going to work for 5 <=> 62 stations. So for the time being capped the output at 4 stations.

### CODE REVIEW

**Comment by IntelOrca** [comment]
We should also try to make the formatter more robust if possible to prevent the crash.
As for the station issue, after the ride window becomes class, we will need to think about how to display all the station information. Maybe a list view in a new tab?

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -5772,7 +5772,10 @@ static void WindowRideMeasurementsPaint(WindowBase* w, DrawPixelInfo& dpi)
                     // Ride time
                     ft = Formatter();
                     int32_t numTimes = 0;
-                    for (int32_t i = 0; i < ride->num_stations; i++)
+                    // TODO: STR_RIDE_TIME only takes up to 4 stations modify to take more
+                    // also if modified may need to be split into multiple format strings
+                    // as formatter cannot take more than 256 bytes
+                    for (int32_t i = 0; i < ride->num_stations && i < 4; i++)
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/Ride.cpp:5778]:
```suggestion
                    for (int32_t i = 0; i < std::min(ride->num_stations, 4); i++)
```

File: src/openrct2-ui/windows/Ride.cpp [hunk 2]
```diff
@@ -5810,7 +5813,8 @@ static void WindowRideMeasurementsPaint(WindowBase* w, DrawPixelInfo& dpi)
                 // Ride length
                 ft = Formatter();
                 int32_t numLengths = 0;
-                for (int32_t i = 0; i < ride->num_stations; i++)
+                // TODO: see above STR_RIDE_LENGTH is also only able to display max 4
+                for (int32_t i = 0; i < ride->num_stations && i < 4; i++)
```
Comment (ZehMatt) [inline src/openrct2-ui/windows/Ride.cpp:5817]: Same here

**Review by ZehMatt — APPROVED** [review]
