### PR TITLE
Fix #21310: Clearance on half loop elements is not symmetrical

### LINKED ISSUE #21310: Downward half loops require too much clearance
### Operating System

Linux

### OpenRCT2 build

ceafb684811e6c2426adf805f775321b066d9f24

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

For the Twister and Inverted coasters, the downward half loops (both left and right) require more clearance above them on one tile than their upward counterparts.  
Comparing it with the clearance required by other half-inversions (e. g. half corkscrews) or simply building these pieces at maximum height suggest that it's the downward half loop that's off.

twister-clearance
(Concrete blocks are placed in the closest proximity to the track that was possible. Polystyrene blocks are just there to show how things align to the other side.)

twister-too-high
(No ghost piece shown for the downwards large half loop because the extra bit of clearance required makes it "too high for supports", so it cannot be built.)

inverted-too-high
(Same as above; limits / height markers are slightly different for the inverted track.)

Same thing for the regular half loops.

Haven't checked other coaster types yet.

### Steps to reproduce

Twister coaster:  
1. For the Twister coaster, try building an upwards large half loop from 36m (doesn't work; too high)
2. Try the same from 34.5m (works, so this is the upper limit)
3. Notice that the suggested next element cannot be built (too high)
4. Notice that the corkscrew pieces can actually be built

Inverted coaster:  
* Same as above, but the limits are 1.5m higher each.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by zzril**
This PR...  
* gives the 5th member of `struct PreviewTrack` (which indicates an element's height) a more meaningful name
* lowers this height value for each tile of every half loop element as necessary to match the value from its symmetrical counterparts

Closes #21310

### CODE REVIEW

**Comment by Gymnasiast** [comment]
This needs to be checked thoroughly, since we tried to make clearance fixes on parts before.

**Comment by zzril** [comment]
Note: Because I have only lowered the height values, everything that was buildable (without cheats) before will remain buildable with these changes.  
Also, doing it this way required the least changes, so I'm pretty sure these are now the "correct" values.

---

Also note: The goal of this PR was solely to make the clearance values symmetrical. I.e. the vertical clearance required for the very first tile of an upwards loop should match the clearance required for the very last tile of its downward counterpart.

During testing it turned out that there several elements where the clearance required is unrealistic, e.g. at the apex of small vertical loops. We may want to change those, but it's hard to determine what values should actually be used there. Would prefer doing that in a new issue.

---

Also note that the Flying coaster's elements still look glitchy / have too little clearance. (E. g. the station platform.) That is, however, not caused by the values in the `PreviewTrack` structs in `TrackData.cpp`, but by the way clearance is calculated for this coaster type in inverted / "flying" position in general. Again, this should probably be tackled in a separate issue / PR.

**Review by Gymnasiast — APPROVED** [review]
Code looks good.

File: src/openrct2/ride/Track.h [hunk 1]
```diff
@@ -79,7 +79,7 @@ struct PreviewTrack
     int16_t x;     // 0x01
     int16_t y;     // 0x03
     int16_t z;     // 0x05
-    uint8_t var_07;
+    uint8_t VerticalSize;
```
Comment (duncanspumpkin) [inline src/openrct2/ride/Track.h:82]: To match the style of the codebase this would be called `ClearZ` or `ClearanceZ`

Comment (zzril) [reply src/openrct2/ride/Track.h]: Changed it to `ClearanceZ`.

**Review by ZehMatt — APPROVED** [review]
Code looks fine, would be good to have someone test this.

**Review by ZeeMaji — APPROVED** [review]
I've tested this, everything seems to be okay after testing most of the affected ride types. The way you handled this shouldn't break any pre-existing designs as you just lowered some clearances. I also glanced through all of my saved track designs for all of the affected ride types and none of them turned invisible in the track selection window (would indicate clearance issues) so it seems like this is working as it should to me.
