### PR TITLE
 Fix #4927: Giant screenshot cut off at bottom and top

### LINKED ISSUE #4927: Giant screenshot cut off at bottom and top
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** c3035b7

When taking a giant screenshot, the top and bottom are cut off. 

**Steps to reproduce:**
1. Open any park and take a giant screenshot from the option under the save menu
2. Observe how the top and bottom are missing

**Screenshots / Video:**
ccc2 2016-12-26 23-28-44

### PR DESCRIPTION
**Pull request by IntelOrca**

### CODE REVIEW

File: src/openrct2/world/Map.cpp [hunk 1]
```diff
@@ -453,6 +453,11 @@ void map_update_tile_pointers()
     gNextFreeTileElement = tileElement;
 }
 
+int16_t tile_element_height(CoordsXY location)
```
Comment (duncanspumpkin) [inline src/openrct2/world/Map.cpp]: This is already in my map refactor branch.

File: src/openrct2/interface/Screenshot.cpp [hunk 2]
```diff
@@ -607,16 +524,140 @@ int32_t cmdline_for_screenshot(const char** argv, int32_t argc, ScreenshotOption
...
+                if (centreMapX)
+                    customX = (mapSize / 2) * 32 + 16;
+                if (centreMapY)
+                    customY = (mapSize / 2) * 32 + 16;
+
+                int32_t z = tile_element_height(customX, customY);
+                CoordsXYZ coords3d = { customX, customY, z };
 
-    WriteDpiToFile(outputPath, &dpi, renderedPalette);
+                CoordsXY coords2d = translate_3d_to_2d_with_z(customRotation, coords3d);
```
Comment (duncanspumpkin) [inline src/openrct2/interface/Screenshot.cpp]: If you change this to auto then my change that makes this screen coords will merge nicer.
