### PR TITLE
Fix #8870: Use player index instead of id.

### LINKED ISSUE #8870: BACKTRACE 0e57ef
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/0e57ef38e862c9a78a79c794829de1f2437e42a04bdb2e230001265c25e4a1d8?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Mar 14 2019 18:26:48)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_screenshot.png:</strong> C:\\Users\\Skyla\\Documents\\OpenRCT2\\screenshot\\Santa Miranda Beach 2019-03-14 13-26-49.png: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Skyla\\Documents\\OpenRCT2\\bdc60878-1f87-40a8-97d7-8147c2b5e6b8.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Skyla\\Documents\\OpenRCT2\\bdc60878-1f87-40a8-97d7-8147c2b5e6b8.sv6.gz: <em>1</em><br><strong>commit:</strong> 1d9b17a: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_player_overview_invalidate -> window_player_set_page -> window_player_open -> input_scroll_begin -> input_widget_left -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by ZehMatt**
Regression from #8734, small oversight on using id vs index. Also made sure the window gets closed in case the player no longer exists.

### CODE REVIEW

File: src/openrct2-ui/windows/Player.cpp [hunk 1]
```diff
@@ -400,6 +400,13 @@ void window_player_overview_paint(rct_window* w, rct_drawpixelinfo* dpi)
 
 void window_player_overview_invalidate(rct_window* w)
 {
+    int32_t playerIndex = network_get_player_index((uint8_t)w->number);
+    if (playerIndex == -1)
+    {
+        window_close(w);
```
Comment (IntelOrca) [inline src/openrct2-ui/windows/Player.cpp]: I am not sure if this is valid, do any other windows close the window within `invalidate`? Perhaps the update event would be a better place.

Comment (ZehMatt) [reply src/openrct2-ui/windows/Player.cpp]: Theres another invalidate function where this is the happening as well but yeah this feels somewhat dirty. I'm not even entirely sure if this is really required more a fail safe to not access out of bounds data.

Comment (IntelOrca) [reply src/openrct2-ui/windows/Player.cpp]: Well I mean just keep the check and return but actually close the window in a safer event handler. But if another window already does this then I guess it isn't a problem. I just didn't know whether the same window would try to then be painted after being closed.

Comment (ZehMatt) [reply src/openrct2-ui/windows/Player.cpp]: Turns out window_player_statistics_update is already the update event, easy to overlook given that its a list of pointers. I'll just return like you suggested.
