### PR TITLE
fixes #2126 Ferris wheel backward rotation

### LINKED ISSUE #2126: Ferris Wheels set to "backward rotation" stop working
This is a bug in the original RCT2 that applies to OpenRCT2 (tested in build 1358).

Simply create a Ferris Wheel, set it to backward rotation, and wait.  It seems that once the ride fills up, the wheel simply stops spinning, leaving passengers stuck on the ride and queuing guests frustrated.

[Here](https://dl.dropboxusercontent.com/u/10663130/OpenRCT2/Broken%20Ferris%20Wheel.sv6)'s a save file with a broken Ferris Wheel for example.

### PR DESCRIPTION
**Pull request by jackinloadup**
This fixes #2126. This is my first time contributing here. Hope I lived up to your standards.

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Would you also add the following to `distribution/changelog.txt` (at the top):
```
0.0.4 (not yet released)
------------------------------------------------------------------------
- Fix: [#2126] Ferris Wheels set to "backward rotation" stop working (original bug)
```

**Comment by duncanspumpkin** [comment]
Can you change the comment above the if

File: src/peep/peep.c [hunk 1]
```diff
@@ -2290,8 +2290,9 @@ void peep_update_ride_sub_state_7(rct_peep* peep){
 		vehicle = GET_VEHICLE(vehicle->next_vehicle_on_train);
 	}
 
-	// Unsure why backward rotation is missing.
-	if (ride->mode != RIDE_MODE_FORWARD_ROTATION){
+	// Check if ride is NOT Farris Wheel.
+	if (ride->mode != RIDE_MODE_FORWARD_ROTATION &&
+	        ride->mode != RIDE_MODE_BACKWARD_ROTATION){
 		if (vehicle->num_peeps - 1 != peep->current_seat)
```
Comment (jackinloadup) [inline src/peep/peep.c]: Any idea what this is targeting? I was trying to add a comment but I wasn't sure what it was trying to do.

As I'm not sure what other rides this accounts for I'm assuming all. It seems it would only run when the peep is the last person in the vehicle. Great or one person vehicles I guess

Comment (IntelOrca) [inline src/peep/peep.c]: Typo: **"Ferris Wheel"**

**Comment by jackinloadup** [comment]
Corrected my bad spelling of Ferris Wheel.
