### PR TITLE
More tile element stuff

### LINKED ISSUE #7997: Segfault when playing nightly version
**OS:** Ubuntu 18.04
**Version:** nightly build: `0.2.1-develop-0~6901-201809151253-g47eea29~ubuntu18.04.1`
**Commit/Build:** 47eea29

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Play game for a while (in single-player)
2. Crash :(

Here's what appears on my console:

    ERROR[/build/openrct2-gIgx0c/openrct2-0.2.1-develop-0~6901-201809151253/src/openrct2/object/ObjectFactory.cpp:435 (CreateObjectFromJson)]: Object rct2.rckc has an incorrect sourceGame parameter.
    WARNING[/build/openrct2-gIgx0c/openrct2-0.2.1-develop-0~6901-201809151253/src/openrct2/object/ObjectManager.cpp:68 (GetLoadedObject)]: Object index 2048 exceeds maximum for type 2.
    Segmentation fault (core dumped)

There doesn't seem to be any rhyme or reason to the crash; it just happens after a while.

**Save game:**
[autosave_2018-09-15_13-35-54.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/2385950/autosave_2018-09-15_13-35-54.sv6.zip)

### PR DESCRIPTION
**Pull request by Gymnasiast**
This wasn't quite as easy as the small scenery. Especially the surface elements, which have both the surface and edge styles spread out over two bytes. 

Also fixes #7997.

### CODE REVIEW

File: src/openrct2/world/TileInspector.cpp [hunk 1]
```diff
@@ -512,11 +512,11 @@ int32_t tile_inspector_surface_toggle_corner(int32_t x, int32_t y, int32_t corne
 
     if (flags & GAME_COMMAND_FLAG_APPLY)
     {
-        const uint8_t originalSlope = surfaceElement->properties.surface.slope;
+        const uint8_t originalSlope = surfaceElement->AsSurface()->GetSlope();
         const bool diagonal = (originalSlope & TILE_ELEMENT_SLOPE_DOUBLE_HEIGHT) >> 4;
 
-        surfaceElement->properties.surface.slope ^= 1 << cornerIndex;
-        if (surfaceElement->properties.surface.slope & TILE_ELEMENT_SLOPE_ALL_CORNERS_UP)
+        surfaceElement->AsSurface()->SetSlope(surfaceElement->AsSurface()->GetSlope() ^ (1 << cornerIndex));
```
Comment (AaronVanGeffen) [inline src/openrct2/world/TileInspector.cpp]: I'd prefer non-trivial arguments to be computed in a temporary variable on their own line.

File: src/openrct2/world/TileInspector.cpp [hunk 2]
```diff
@@ -577,12 +578,12 @@ int32_t tile_inspector_surface_toggle_diagonal(int32_t x, int32_t y, int32_t fla
 
     if (flags & GAME_COMMAND_FLAG_APPLY)
     {
-        surfaceElement->properties.surface.slope ^= TILE_ELEMENT_SLOPE_DOUBLE_HEIGHT;
-        if (surfaceElement->properties.surface.slope & TILE_ELEMENT_SLOPE_DOUBLE_HEIGHT)
+        surfaceElement->AsSurface()->SetSlope(surfaceElement->AsSurface()->GetSlope() ^ TILE_ELEMENT_SLOPE_DOUBLE_HEIGHT);
```
Comment (AaronVanGeffen) [inline src/openrct2/world/TileInspector.cpp]: I'd prefer non-trivial arguments to be computed in a temporary variable on their own line.

File: src/openrct2/world/Map.cpp [hunk 3]
```diff
@@ -698,18 +694,18 @@ void map_update_path_wide_flags()
...
 {
-    if (!(slope & TILE_ELEMENT_SLOPE_S_CORNER_UP))
+    if (!(slope & FOOTPATH_PROPERTIES_FLAG_IS_SLOPED))
         return 0;
 
-    switch (slope & TILE_ELEMENT_SLOPE_NE_SIDE_UP)
+    switch (slope & FOOTPATH_PROPERTIES_SLOPE_DIRECTION_MASK)
     {
-        case TILE_ELEMENT_SLOPE_FLAT:
+        case 0:
```
Comment (AaronVanGeffen) [inline src/openrct2/world/Map.cpp]: I understand the change from tile elements to footpath properties, but I don't like the introduction of magic numbers. Could you use or add constants for these?

Comment (Gymnasiast) [reply src/openrct2/world/Map.cpp]: Directions always appear to use naked numbers in OpenRCT2.

**Comment by Gymnasiast** [comment]
Sure, that's a good idea. I caught two bugs already by testing it myself.

File: src/openrct2/world/Surface.cpp [hunk 4]
```diff
@@ -9,49 +9,209 @@
...
+    grass_length = length;
+
+    if (newLength == oldLength)
+    {
+        return;
+    }
+
+    // If the new grass length won't result in an actual visual change
+    // then skip invalidating the tile, no point
+    if (((oldLength > 0 && oldLength < 4) && (newLength > 0 && newLength < 4))
```
Comment (thetorpedodog) [inline src/openrct2/world/Surface.cpp]: This might be easier to read if all the comparisons go low-to-high:

`(0 < oldLength && oldLength < 4) && (0 < newLength && newLength < 4)` etc.

(this is a drive-by comment that you're free to ignore; just noticed it as I was idly looking through the change out of curiosity)

**Comment by AaronVanGeffen** [comment]
Fences aren't correctly repositioned after purchasing land:

screenshot_20180916_212615

**Comment by Gymnasiast** [comment]
Fence bug has been fixed, along with another one in map_init().

File: src/openrct2/paint/tile_element/Paint.Surface.cpp [hunk 5]
```diff
@@ -565,34 +565,34 @@ static void viewport_surface_smoothen_edge(
         return;
     }
 
-    uint8_t dh = 0, cl = 0;
```
Comment (Gymnasiast) [inline src/openrct2/paint/tile_element/Paint.Surface.cpp]: change back to `dh`. (Stupid CLion)

File: src/openrct2/ride/TrackDesign.cpp [hunk 6]
```diff
@@ -2330,10 +2330,11 @@ static void track_design_preview_clear_map()
         tile_element->flags = TILE_ELEMENT_FLAG_LAST_TILE;
         tile_element->base_height = 2;
         tile_element->clearance_height = 0;
-        tile_element->properties.surface.slope = 0;
-        tile_element->properties.surface.terrain = 0;
-        tile_element->properties.surface.grass_length = GRASS_LENGTH_CLEAR_0;
-        tile_element->properties.surface.ownership = OWNERSHIP_OWNED;
+        tile_element->AsSurface()->SetSlope(TILE_ELEMENT_SLOPE_FLAT);
```
Comment (Gymnasiast) [inline src/openrct2/ride/TrackDesign.cpp]: memset to 0 first

File: src/openrct2/world/Map.cpp [hunk 7]
```diff
@@ -3862,35 +3731,32 @@ void map_remove_out_of_range_elements()
...
-            & TILE_ELEMENT_SURFACE_EDGE_STYLE_MASK;
-        newTileElement->properties.surface.terrain = existingTileElement->properties.surface.terrain;
-        newTileElement->properties.surface.grass_length = existingTileElement->properties.surface.grass_length;
-        newTileElement->properties.surface.ownership = 0;
+        existingTileElement = map_get_surface_element_at(x, y - 1)->AsSurface();
+        newTileElement = map_get_surface_element_at(x, y)->AsSurface();
+        newTileElement->SetSurfaceStyle(existingTileElement->GetSurfaceStyle());
+        newTileElement->SetEdgeStyle(existingTileElement->GetEdgeStyle());
+        newTileElement->SetGrassLength(existingTileElement->GetGrassLength());
+        newTileElement->SetOwnership(OWNERSHIP_UNOWNED);
```
Comment (Gymnasiast) [inline src/openrct2/world/Map.cpp]: incomplete, also copy water height

File: src/openrct2/world/Map.cpp [hunk 8]
```diff
@@ -3912,29 +3778,27 @@ void map_extend_boundary_surface()
...
-        newTileElement->type = (newTileElement->type & 0x7C) | (existingTileElement->type & 0x83);
-        newTileElement->properties.surface.slope = existingTileElement->properties.surface.slope
-            & TILE_ELEMENT_SURFACE_EDGE_STYLE_MASK;
-        newTileElement->properties.surface.terrain = existingTileElement->properties.surface.terrain;
-        newTileElement->properties.surface.grass_length = existingTileElement->properties.surface.grass_length;
-        newTileElement->properties.surface.ownership = 0;
+        newTileElement->SetSurfaceStyle(existingTileElement->GetSurfaceStyle());
+        newTileElement->SetEdgeStyle(existingTileElement->GetEdgeStyle());
+        newTileElement->SetGrassLength(existingTileElement->GetGrassLength());
+        newTileElement->SetOwnership(OWNERSHIP_UNOWNED);
```
Comment (Gymnasiast) [inline src/openrct2/world/Map.cpp]: also copy water height

File: src/openrct2/world/Map.cpp [hunk 9]
```diff
@@ -3966,10 +3830,11 @@ static void clear_element_at(int32_t x, int32_t y, rct_tile_element** elementPtr
...
             element->clearance_height = 2;
-            element->properties.surface.slope = TILE_ELEMENT_SLOPE_FLAT;
-            element->properties.surface.terrain = 0;
-            element->properties.surface.grass_length = GRASS_LENGTH_CLEAR_0;
-            element->properties.surface.ownership = 0;
+            element->AsSurface()->SetSlope(TILE_ELEMENT_SLOPE_FLAT);
+            element->AsSurface()->SetSurfaceStyle(TERRAIN_GRASS);
+            element->AsSurface()->SetEdgeStyle(TERRAIN_EDGE_ROCK);
+            element->AsSurface()->SetGrassLength(GRASS_LENGTH_CLEAR_0);
+            element->AsSurface()->SetOwnership(OWNERSHIP_UNOWNED);
```
Comment (Gymnasiast) [inline src/openrct2/world/Map.cpp]: set water height/memset to 0.
