### PR TITLE
Fix crash where peeps enter through extra ride entrances

### LINKED ISSUE #16170: Assertion Fail (with park file to reproduce =D)
### Operating System

Windows 10, 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (6e839bd on develop) provided by GitHub

### Describe the issue

An assertion popped up.
I wasn't doing anything, though the park I had loaded does contain a lot of trippy rides.
It didn't crash right away in the park though, only after like a minute after loading it.
It is reproducable, I tried it a few times, it crashes every single time, a bit after the rain stops. 

Knipsel
 

### Area(s) with issue?

_No response_

### Steps to reproduce

1.  Open park
2. Wait ~30 seconds or so

### Attachments

[Painful hairpin.zip](https://github.com/OpenRCT2/OpenRCT2/files/7688648/Painful.hairpin.zip)

### LINKED ISSUE #16177: [ddd8b9] openrct2.com: Guard::Assert_VA, Guard::Assert, Guest::UpdateRideAdvanceThroughEntrance, peep_update_all, OpenRCT2::G...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/ddd8b964119afae461599d16c708da7053369549ef15cfa0e9bc7c5b9ca18386">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\james\Documents\OpenRCT2\crash\12ed8925-d53a-49b0-bf49-486e2196aedb.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>Peep ridesubstate should be LeaveEntrance</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.3.5.1 (2d1af0e on develop) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_WRITE</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>2d1af0e</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-write</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
Guard::Assert_VA
Guard::Assert
Guest::UpdateRideAdvanceThroughEntrance
peep_update_all
OpenRCT2::GameState::UpdateLogic
HandleSimulate
NormalisedMain
wmain
invoke_main</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by csm10495**
This should fix #16170 and close #16177. 

WIth this change the peep gets on the ride... and exits after over as expected. No crash. :)

### CODE REVIEW

**Comment by csm10495** [comment]
I think cheats were still used to add the extra entrances. Once they were added the game could crash if guests used them at certain times.

This change fixes that crash.

I'm still not 100% sure how they added multiple entrances. I just debugged from the given save file.

**Comment by ZehMatt** [comment]
They probably used the Tile Inspector to copy the element. And no this probably doesn't make them usable.

**Comment by csm10495** [comment]
100% sure guests used at least one of them. Before this change, it would crash when a guest used it at a certain time.

**Comment by ZehMatt** [comment]
I'm not sure that this is the right way to fix it, anyway @duncanspumpkin self requested a review he knows this part of the code a lot better.

**Comment by Broxzier** [comment]
Rides can only have one functional entrance and exit per station. I assume that this bug occurred because a guest happened to bump into the non-usable one and decided to enter the ride then. A proper way of handling this is to check if the entrance used matches the coordinates and direction of the station entrance that the ride expects.

**Comment by csm10495** [comment]
The ride state for this guest (without this PR changes):
image

So we're walking then we're queuing, then we're queuing in front, then we enter... then somehow go back and forth between queuing in front and entering..

Maybe we should make it so they can only queue (and queue front) if in the correct queue. I'm not that familiar with the code... how / where could we check for that?

**Comment by csm10495** [comment]
@duncanspumpkin any guidance here?

**Comment by duncanspumpkin** [comment]
In what situation do you see this as being valid. We added the assert because the state is clearly not meant to become possible. All you are doing is overriding the assert which is not a clever idea. The issue is upstream of this. When you are inEntrance the next state you are meant to go to is `FreeVehicleCheck` by leaving the entrance without doing the vehicle check you are causing invalid state to be now passed into the next bit of code that handles entering a vehicle. From a quick look you will: mess up the ride profit as they wont pay for entrance; potentially void the peep if the vehicle is already occupied; potentially corrupt the ride peeps.

 The only logical solution here is that if the peep is `InEntrance` at this point then its to always go to the `FreeVehicleCheck` not to skip that state and go straight to `LeaveEntrance`. And if you are doing that then the assert is no longer needed.

File: src/openrct2/entity/Guest.cpp [hunk 1]
```diff
@@ -3644,6 +3644,10 @@ void Guest::UpdateRideAdvanceThroughEntrance()
         MoveTo({ loc.value(), actionZ });
         return;
     }
+    else if (RideSubState == PeepRideSubState::InEntrance)
+    {
+        RideSubState = PeepRideSubState::LeaveEntrance;
+    }
 
     Guard::Assert(RideSubState == PeepRideSubState::LeaveEntrance, "Peep ridesubstate should be LeaveEntrance");
```
Comment (duncanspumpkin) [inline src/openrct2/entity/Guest.cpp:3652]: remove

File: src/openrct2/entity/Guest.cpp [hunk 2]
```diff
@@ -3644,6 +3644,10 @@ void Guest::UpdateRideAdvanceThroughEntrance()
         MoveTo({ loc.value(), actionZ });
         return;
     }
+    else if (RideSubState == PeepRideSubState::InEntrance)
```
Comment (duncanspumpkin) [inline src/openrct2/entity/Guest.cpp:3647]: remove else not related to the above.

File: src/openrct2/entity/Guest.cpp [hunk 3]
```diff
@@ -3644,6 +3644,10 @@ void Guest::UpdateRideAdvanceThroughEntrance()
...
+    {
+        RideSubState = PeepRideSubState::LeaveEntrance;
```
Comment (duncanspumpkin) [inline src/openrct2/entity/Guest.cpp:3649]: This is unsafe should perform `FreeVehicleCheck` then immediately return from this function.

**Review by duncanspumpkin — CHANGES_REQUESTED** [review]

**Comment by csm10495** [comment]
@duncanspumpkin , mind checking once more? I think I did what you asked. Thanks again.

File: src/openrct2/entity/Guest.cpp (hunk 1 above)
Comment (duncanspumpkin) [reply src/openrct2/entity/Guest.cpp:3654]: You can remove this assert now.

**Comment by duncanspumpkin** [comment]
Remove the assert and bump the network version and this is good to go.

**Comment by Legotown55** [comment]
How do you add second entrance to a ride

**Comment by Broxzier** [comment]
@Legotown55 please keep questions and unrelated comments to discussions and our Discord server.

**Comment by csm10495** [comment]
@duncanspumpkin done. One more check time hopefully. Thanks!

**Review by duncanspumpkin — APPROVED** [review]

**Comment by csm10495** [comment]
@duncanspumpkin can you merge this?

**Comment by duncanspumpkin** [comment]
I was waiting on a different pr to be merged first. Could you rebase as the other pr is now merged

**Comment by csm10495** [comment]
Sorry I didn't know that you were waiting on another pr. I've rebased this to latest develop.
