### PR TITLE
Close #23018: Close windows before loading new game

### LINKED ISSUE #23018: Close windows before starting new game
#23015 closes all windows before loading a game, but some crashes are caused by starting a new game when having windows open. So this also needs to be done.

### PR DESCRIPTION
**Pull request by Gymnasiast**
When starting a new game from an existing one, close all windows before loading the new map in order to prevent crashes. Also see #23015.

### CODE REVIEW

File: src/openrct2/Game.cpp [hunk 1]
```diff
@@ -622,7 +622,11 @@ static void GameLoadOrQuitNoSavePromptCallback(int32_t result, const utf8* path)
 
 static void NewGameWindowCallback(const utf8* path)
 {
-    WindowCloseByClass(WindowClass::EditorObjectSelection);
+    // Closing this will cause a Ride window to pop up, so we have to do this to ensure that
```
Comment (janisozaur) [inline src/openrct2/Game.cpp:625]: Closing what? And it does sound quite odd, do you know why a new window shows up?

**Comment by spacek531** [comment]
image
Ride construction window still appears when loading a game - game screen not being drawn? No crashes observed on test build nor OpenRCT2, v0.4.13-89-ga1d479d (a1d479d on develop) provided by GitHub when building a ride then loading a park with no rides (Whispering Cliffs).

File: src/openrct2/Game.cpp (hunk 1 above)
Comment (AaronVanGeffen) [reply src/openrct2/Game.cpp:625]: Assuming _something_ has been built, closing the construction window opens the associated ride window.

**Review by spacek531 — APPROVED** [review]

File: src/openrct2/Game.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/Game.cpp:625]: I would have thought that was obvious, considering the comment is right above a call to close windows of the RideConstruction class.

**Review by janisozaur — APPROVED** [review]
