### PR TITLE
Fix #5881: Automatically Set Unlock All Prices For Saves

### LINKED ISSUE #5881: Unlock All Prices Cheat Persists When Switching from RCT1 to LL and RCT2 Scenarios
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 3d48754

When loading a RCT1 scenario (imported from the original game; Deluxe in my case), the Unlock All Prices cheat will activate correctly for those scenarios. However, if you then load Loopy Landscapes or RCT2 scenarios, this cheat will persist incorrectly until you restart the game. Basically ever scenario will have unlock all prices selected from then on.

This only happens after loading RCT1 scenarios. When going from LL or RCT2 to RCT1, the Unlock All Prices cheat triggers like it should. Perhaps LL and RCT2 scenarios need to force Unlock All Prices off.

**Steps to reproduce:**
1. Load a RCT1 (minus Loopy Landscapes) scenario.
2. Load LL or RCT2 scenario.

### PR DESCRIPTION
**Pull request by CharlesLove**
Fix for #5881 

In regards to RCT1/AA scenarios using the Unlock All Prices cheat, I've toggled unlock all prices for save files based on scenario file names, ideally would use IDs in the future.

Cheats are also reset on starting a new scenario.

### CODE REVIEW

**Comment by CharlesLove** [comment]
I'm not sure what you mean by initial solution. What would you like me to restore?

**Comment by Gymnasiast** [comment]
The first fix you came up with simply set gCheatsUnlockAllPrices to `false` in S4Importer and S6Importer.

**Comment by CharlesLove** [comment]
Would you like me to remove the save file  specific fix as well?

**Comment by Gymnasiast** [comment]
@CharlesLove _Especially_ that one. Setting `gCheatsUnlockAllPrices` to false at the beginning of S4Importer and S6Importer should suffice, really.

**Comment by CharlesLove** [comment]
I've reverted back to the old version. Only newly created scenarios will toggle the cheat, saves will purely use whatever the last option selected was. I'll look into a more elegant solution to the save file thing in a separate request later perhaps.

**Comment by Gymnasiast** [comment]
Could you change the following two points as well:
- Change the tabs to spaces (we use spaces for indenting)
- There are some files that appear changed because you added newlines. Please remove the added newlines from files you didn't add code to.

**Comment by CharlesLove** [comment]
Just took care of both of those things.

File: src/openrct2/rct2/S6Importer.cpp [hunk 1]
```diff
@@ -217,6 +217,8 @@ class S6Importer final : public IParkImporter
         gBankLoan        = _s6.current_loan;
         gParkFlags       = _s6.park_flags;
         gParkEntranceFee = _s6.park_entrance_fee;
+		// Force RCT2 scenarios to Unlock All Prices being false
```
Comment (Gymnasiast) [inline src/openrct2/rct2/S6Importer.cpp]: This bit still has tabs.

File: src/openrct2/rct1/S4Importer.cpp [hunk 2]
```diff
@@ -2042,6 +2042,12 @@ class S4Importer final : public IParkImporter
         {
             gCheatsUnlockAllPrices = true;
         }
+        // Default Loopy Landscapes to unlock all prices being false
```
Comment (Gymnasiast) [inline src/openrct2/rct1/S4Importer.cpp]: Remove this comment.

File: src/openrct2/rct1/S4Importer.cpp [hunk 3]
```diff
@@ -2042,6 +2042,13 @@ class S4Importer final : public IParkImporter
         {
             gCheatsUnlockAllPrices = true;
         }
+        // Loopy Landscape parks can set a flag to lock the entry price to free.
```
Comment (Gymnasiast) [inline src/openrct2/rct1/S4Importer.cpp]: Could you move this comment above the `if`?

**Comment by Gymnasiast** [comment]
Thanks for your patience! 
Sorry for my nitpickery, I want to ensure that only good code gets into the game.

**Comment by CharlesLove** [comment]
No worries! Glad to finally be able to contribute after playing OpenRCT2 for so long!
