### PR TITLE
Fix #17931: The in-game command ‘count_objects’ crashes the game.

### LINKED ISSUE #17931: [07c928] openrct2.exe: common_strnlen_c, common_strnlen_simd, common_strnlen, strnlen, common_vsprintf, String::Format_VA, In...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/07c928e3ec402a52c384fc698c37ed4e975452093403067ca0e743b7781255ce">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>_rxid</strong> &mdash; 1
        <ul>
                <li><code>29000000-1671-bc08-0000-000000000000</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\eriks.000\Documents\OpenRCT2\crash\683f2873-c6be-4d29-9d38-2fb182b65e13.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>12</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>OpenRCT2, v0.4.1-230-g9dd28c9 (9dd28c9 on develop) provided by GitHub</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_READ</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>9dd28c9</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
common_strnlen_c
common_strnlen_simd
common_strnlen
strnlen
common_vsprintf
String::Format_VA
InteractiveConsole::WriteFormatLine
cc_object_count
InteractiveConsole::Execute
OpenRCT2::Ui::InGameConsole::Input
OpenRCT2::Ui::InputManager::Process
WindowManager::HandleKeyboard
context_input_handle_keyboard
game_handle_keyboard_input
OpenRCT2::GameState::Tick
OpenRCT2::Context::Tick
EntityTweener::PreTick
OpenRCT2::Context::RunVariableFrame
OpenRCT2::Context::RunFrame
OpenRCT2::Context::Launch
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain
invoke_main</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by Broxzier**

### CODE REVIEW

File: src/openrct2/interface/InteractiveConsole.cpp [hunk 1]
```diff
@@ -1265,25 +1266,41 @@ static int32_t cc_load_object(InteractiveConsole& console, const arguments_t& ar
...
+    "Terrain Surface",
+    "Terrain Edges",
+    "Stations",
+    "Music",
+    "Footpath Surface",
+    "Footpath Railings",
+    "Audio",
+};
+static_assert(_objectTypeNames.size() == EnumValue(ObjectType::Count));
 static int32_t cc_object_count(InteractiveConsole& console, [[maybe_unused]] const arguments_t& argv)
```
Comment (Gymnasiast) [inline src/openrct2/interface/InteractiveConsole.cpp:1290]:
```suggestion

static int32_t cc_object_count(InteractiveConsole& console, [[maybe_unused]] const arguments_t& argv)
```
For legibility.

**Review by Gymnasiast — APPROVED** [review]
