### PR TITLE
Smooth map based on inferred PNG image size, not leftover setting

### LINKED ISSUE #24711: "Smooth Tile Edges" doesn't work for Heightmaps larger than 148x148 (Map Generator)
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.23 (b8d73b523c)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The "Smooth Tile Edges" option in the Map Generator currently only works with Heightmap files 148x148 pixels or smaller, which is a bit of an issue as I wish to make huge parks based off of real-world topological heightmaps.

### Steps to reproduce

1. Open the game, go to Scenario Editor.
2. Go to Landscape Editor -> Map Generator. Select "Heightmap file".
3. Select any heightmap larger than 148 by 148 pixels.
4. Turn OFF "Normalise height map" and "Smooth height map", BUT keep "Smooth tile edges" in the second tab turned on.
5. The differences between the correctly smoothed and ignored unsmoothed tiles should be apparent.

### Attachments

Image

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
When applying tile smoothing in the map generator, a generalised loop is used to iterate over the entire map (#24280). To this end, the map size property from the generator settings struct is used. However, for PNG images, the map size is not set by the user, but _inferred_ from the selected PNG image. This leads to only part of the map being iterated over.

Fixes #24711, #24729

### CODE REVIEW

File: src/openrct2/world/map_generator/PngTerrainGenerator.cpp [hunk 1]
```diff
@@ -236,7 +236,7 @@ namespace OpenRCT2::World::MapGenerator
         if (settings->smoothTileEdges)
         {
             // Set the tile slopes so that there are no cliffs
-            smoothMap(settings->mapSize, smoothTileWeak);
+            smoothMap({ mapWidth, mapHeight }, smoothTileWeak);
```
Comment (JanStrauss) [inline src/openrct2/world/map_generator/PngTerrainGenerator.cpp:239]: https://github.com/OpenRCT2/OpenRCT2/pull/24884

`mapWidth` and `mapHeight` should be flipped here like in the `MapInit` call above:

Image
Image


```suggestion
            smoothMap({ mapHeight, mapWidth }, smoothTileWeak);
```
