### PR TITLE
Fix #9487: Access violation in UpdateRideEnterVehicle

### LINKED ISSUE #9487: BACKTRACE 428b71 Guest::UpdateRideEnterVehicle
<table>
    <tr>
        <td></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/428b71eea14ed133c7851b504730b5358f06eb2e1adf653e3f5182bce3f847c9?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Jun 27 2019 02:28:13)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_screenshot.png:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Administrator\\Documents\\Random\\\\06d84b5b-9226-43cf-beea-bbe29b5799cb.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Administrator\\Documents\\Random\\\\06d84b5b-9226-43cf-beea-bbe29b5799cb.sv6.gz: <em>1</em><br><strong>commit:</strong> 6bd298b: <em>1</em><br><strong>attachment_park.sv6:</strong> *: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guest::UpdateRideEnterVehicle -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> invoke_main</code></td></tr>
</table>

### PR DESCRIPTION
**Pull request by 41northstudios**

### CODE REVIEW

File: src/openrct2/peep/Guest.cpp [hunk 1]
```diff
@@ -4178,51 +4178,58 @@ void Guest::UpdateRideEnterVehicle()
...
+            {
+                if (current_seat != vehicle->num_peeps)
+                    return;
+            }
 
-        vehicle->num_peeps++;
-        ride->cur_num_customers++;
+            if (vehicle_is_used_in_pairs(vehicle))
+            {
+                auto seated_peep = (GET_PEEP(vehicle->peep[current_seat ^ 1]))->AsGuest();
```
Comment (duncanspumpkin) [inline src/openrct2/peep/Guest.cpp]: This hasn't actually fixed the source of the crash. This call to `AsGuest()` nullptr derefs if the paired peep doesn't exist. (This can happen when people really mess with the game)

Comment (41northstudios) [reply src/openrct2/peep/Guest.cpp]: OK I'll take another look...

**Comment by 41northstudios** [comment]
OK I think this PR will fix the issue but I won't have a chance to test until I get home this evening. 

I added another variable `seated_guest` to avoid having to use casts when calling the Guest function `OnEnterRide` (since the initial assignment of `seated_peep` is not using `AsGuest` anymore, `seated_peep` winds up as a `Peep*` instead of `Guest*` and the function wasn't being recognized)

File: src/openrct2/peep/Guest.cpp [hunk 2]
```diff
@@ -4179,51 +4179,63 @@ void Guest::UpdateRideEnterVehicle()
...
+            {
+                if (current_seat != vehicle->num_peeps)
+                    return;
+            }
 
-        vehicle->num_peeps++;
-        ride->cur_num_customers++;
+            if (vehicle_is_used_in_pairs(vehicle))
+            {
+                auto* seated_peep = GET_PEEP(vehicle->peep[current_seat ^ 1]);
```
Comment (duncanspumpkin) [inline src/openrct2/peep/Guest.cpp]: Since you are touching most of this function may as well switch to camelCase for all of the variables.

Comment (41northstudios) [reply src/openrct2/peep/Guest.cpp]: OK, I changed all the local function variables...if you want to create new issues to refactor some of the other var names in the Peep and Guest structs I can take a crack at those also.

Comment (41northstudios) [reply src/openrct2/peep/Guest.cpp]: OK I updated the vars that were local to the function. If you want to open some new issues to refactor the names in `Peep` and `Guest` structs I can take a crack at those, too.
