### PR TITLE
Fix #14587: Send queued packets before disconnecting the client

### LINKED ISSUE #14587: [bug] error when joining server
### Server
**OS:** `Ubuntu 20.04.2 LTS (5.4.0-1042-gcp #45-Ubuntu x86_64)`
**Version:** `OpenRCT2, v0.3.3 (, DEBUG) Linux (x86-64)`
**Commit/Build:** installed from ppa. i can see this in package metadata: `Version: 0.3.3-develop-0~2443-202104040054-g9b2c94648~ubuntu20.04.1`

### Client
**OS:** `Manjaro Linux 21.0.3 (5.10.32-1-MANJARO #1 x86_64)`
**Version:** `OpenRCT2, v0.3.3 Linux (x86-64)`
**Commit/Build:** could not find this info, but the arch/manjaro package metadata says `Version               : 0.3.3-3`, package name `openrct2`

started an openrct2 server on ubuntu in gce and tried to connect to it from my manjaro laptop.
every time i try to connect to the server it fails.

- n/a Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. on server add ppa and instlal package `openrct2`, then run command `openrct2-cli host ./orct2-nlacombe-test.sv6 --port 11753`
2. on client install `openrct2` pacakge and either try to connect with the gui app or just run `openrct2-cli join PUBLIC_IP`

if I run the server and try to connect from a client on the same computer (tried for both server and client) it works (using the cli).
i used netcat to test that the port/ip was open and relaying data correctly and my netcat test passed.

**Save game:**
[orct2-nlacombe-test.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/6445024/orct2-nlacombe-test.sv6.zip)

error in server logs:
```
VERBOSE: Client 207.236.123.18 heartbeat
VERBOSE: Signature verification ok. Hash 00224610dd335b8c276b8f53e6d1994e6392a875
ERROR[/build/openrct2-bJ3TlJ/openrct2-0.3.3-develop-0~2443-202104040054/src/openrct2/network/NetworkBase.cpp:2607 (Server_Handle_AUTH)]: Unknown failure (3) while authenticating client
```

### PR DESCRIPTION
**Pull request by ZehMatt**
Users never got to see this:
openrct2_2021-05-08_23-28-18bc7075ec70d8b530e

or this:
openrct2_2021-05-08_23-29-32975c1ba29ba42e41b

This happened because the socket was closed before it had the chance to send the packet with the auth status in it, this PR does the disconnect post-tick and ensures the packets are sent.

### CODE REVIEW

File: src/openrct2/network/NetworkBase.cpp [hunk 1]
```diff
@@ -1512,7 +1506,7 @@ void NetworkBase::Server_Send_TICK()
     // but debug version can check more often.
     static int32_t checksum_counter = 0;
     checksum_counter++;
-    if (checksum_counter >= 100)
+    if (checksum_counter >= 0)
```
Comment (janisozaur) [inline src/openrct2/network/NetworkBase.cpp:1509]: Is this intended?

Comment (ZehMatt) [reply src/openrct2/network/NetworkBase.cpp:1509]: Damn, its not.

File: src/openrct2/network/NetworkBase.cpp [hunk 2]
```diff
@@ -2568,26 +2566,31 @@ void NetworkBase::Server_Handle_AUTH(NetworkConnection& connection, NetworkPacke
         if (!gameversion || network_get_version() != gameversion)
         {
             connection.AuthStatus = NetworkAuth::BadVersion;
+            log_info("Connection %s: Bad version.", connection.Socket->GetHostName());
```
Comment (IntelOrca) [inline src/openrct2/network/NetworkBase.cpp:2569]: Can we not use `hostName` for the rest of these occurrences of `GetHostName`?

Comment (ZehMatt) [reply src/openrct2/network/NetworkBase.cpp:2569]: I wanted to, must have missed some cases.

**Review by IntelOrca — APPROVED** [review]

**Comment by AaronVanGeffen** [comment]
Nice find! Worth adding a changelog entry for this, I think.
