### PR TITLE
Fix #16287. Incorrect sv6 extension applied when using console or system browser

### LINKED ISSUE #16287: NSF build saves parks as .sv6 instead of .park when "use system file browser" is selected from save window
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (ee62962 on develop)

### Describe the issue

When using a new save format build (ie. develop build past v0.3.5.1) and selecting "use system file browser" when saving the game, the resulting save will be .sv6 format instead of .park format which it should be. Even if you type .park at the end of the file name it will create a .sv6 file.

Example:
Here, Test_01 is saved using the OpenRCT2 file window and Test_02 is saved after selecting "use system file browser". The Test_02 file can still be opened fine by OpenRCT2, but won't open in a pre-NSF build (such as v0.3.5.1 release) and very likely won't open in vanilla if the old limits are broken.

image

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Create a new save game.
2. Click "use system file browser" in the save window.
3. Save the game and view the file in a browser to see extension and file format.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by duncanspumpkin**

### CODE REVIEW

File: src/openrct2/Game.cpp [hunk 1]
```diff
@@ -544,7 +549,12 @@ void save_game_cmd(const utf8* name /* = nullptr */)
 {
     if (name == nullptr)
     {
-        save_game_with_name(gScenarioSavePath.c_str());
+        char savePath[MAX_PATH];
```
Comment (duncanspumpkin) [inline src/openrct2/Game.cpp:552]: This is possible to be reached if you open an existing sv6 save file and use the console to `save_park` it will save with the wrong extension.

File: src/openrct2/Game.cpp [hunk 2]
```diff
@@ -532,7 +532,12 @@ void save_game()
 {
     if (!gFirstTimeSaving)
     {
-        save_game_with_name(gScenarioSavePath.c_str());
+        char savePath[MAX_PATH];
```
Comment (duncanspumpkin) [inline src/openrct2/Game.cpp:535]: I am unsure if this is possible to be reached with an sv6 path but applied the same code anyway.

File: src/openrct2/interface/InteractiveConsole.cpp [hunk 3]
```diff
@@ -1365,9 +1365,10 @@ static int32_t cc_load_park([[maybe_unused]] InteractiveConsole& console, [[mayb
     {
         safe_strcpy(savePath, argv[0].c_str(), sizeof(savePath));
     }
-    if (!String::EndsWith(savePath, ".sv6", true) && !String::EndsWith(savePath, ".sc6", true))
+    if (!String::EndsWith(savePath, ".sv6", true) && !String::EndsWith(savePath, ".sc6", true)
+        && !String::EndsWith(savePath, ".park", true))
     {
-        path_append_extension(savePath, ".sv6", sizeof(savePath));
+        path_append_extension(savePath, ".park", sizeof(savePath));
```
Comment (duncanspumpkin) [inline src/openrct2/interface/InteractiveConsole.cpp:1371]: This is actually for loading from the console not for saving but I feel it is a good idea to change to default .park.

File: src/openrct2-ui/windows/LoadSave.cpp [hunk 4]
```diff
@@ -349,8 +349,8 @@ static bool Browse(bool isSave, char* path, size_t pathSize)
     switch (_type & 0x0E)
     {
         case LOADSAVETYPE_GAME:
-            extension = ".sv6";
-            fileType = FILE_EXTENSION_SV6;
+            extension = ".park";
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/LoadSave.cpp:352]: Shouldn’t this list _all_ the types that OpenRCT2 can open?

(May be done in a later PR.)

Comment (duncanspumpkin) [reply src/openrct2-ui/windows/LoadSave.cpp:352]: That's handled by a different part of this
