### PR TITLE
Fix #17571: Researched rides show up as new vehicles in .park scenarios

### LINKED ISSUE #17571: All tracked/tower ride types show up as new vehicles in research in .park scenarios
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

In scenarios, when a new tracked/tower ride type is researched, the game erroneously claims it is a new vehicle for said ride type even though the ride type was not available prior to it being researched. This is similar to #13236, except this time **ALL tracked/tower ride types** are affected (except for the Mini Golf). This can get really annoying as I have to constantly open the Invention list window just to avoid the "New vehicle now available for (ride type): (vehicle name)" message always popping up. I can confirm that this only happens on newly created .park scenarios. I tested this in several sc4 and sc6 scenarios (using Volcania and Amity Airfield as examples) and this issue does not occur - if it does occur, it only occurs on one or a few tracked/tower ride types.

Powdery Forest 2022-07-19 11-33-41
Screenshot above shows the issue in Powdery Forest, a .park scenario. The game thinks that the Wooden Roller Coaster was already researched beforehand and therefore thinks the **Wooden Roller Coaster Trains** will be researched even though the Wooden Roller Coaster is NOT available at the start of the scenario and logically should be treated as a new ride type. If I made it as an .sc6 scenario, it would correctly show just **Wooden Roller Coaster** in the research tab unless the Wooden Roller Coaster was already pre-invented.

Amity Airfield 2022-07-19 11-23-05
Volcania 2022-07-19 11-22-09
These two above screenshots are from Amity Airfield and Volcania, which are sc6 and sc4 scenarios, respectively. The Lay-down Roller Coaster and Water Coaster in Amity Airfield and Volcania, respectively, are correctly showing up as new ride types in research.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Create a new .park scenario (either through the Scenario Editor or by converting any .park or .sv6 save to a .park scenario)
2. Start a new game in any .park scenario (i.e. the Powdery Forest scenario attached below)
3. Wait until a new tracked/tower ride type is researched (the Mini Golf does not work for this)
4. It will show up as a new vehicle for said ride type

### Attachments

[Powdery Forest.zip](https://github.com/OpenRCT2/OpenRCT2/files/9143794/Powdery.Forest.zip)
Please note that you need RCT1 Deluxe linked to OpenRCT2 for this scenario to fully work since it contains the Classic Mini Roller Coaster and other RCT1 assets, namely the terrain edge and surface styles and a red wooden fence.

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/park/ParkFile.cpp [hunk 1]
```diff
@@ -867,6 +867,11 @@ namespace OpenRCT2
                 // Invention list
                 cs.ReadWriteVector(gResearchItemsUninvented, [&cs](ResearchItem& item) { ReadWriteResearchItem(cs, item); });
                 cs.ReadWriteVector(gResearchItemsInvented, [&cs](ResearchItem& item) { ReadWriteResearchItem(cs, item); });
+
+                if (cs.GetMode() == OrcaStream::Mode::READING)
+                {
+                    research_determine_first_of_type();
+                }
```
Comment (IntelOrca) [inline src/openrct2/park/ParkFile.cpp:874]: Might be better to move this to the Import method, before the call to fix_game_save_vars.

**Review by IntelOrca — APPROVED** [review]
