### PR TITLE
Fix #6300: Saving track triggers assertion

### LINKED ISSUE #6300: When Saving Tracks - An Assertion Failed
**OS:** Windows 10 Pro 1703 x64
**Version:** v0.1.2
**Commit/Build:** develop build 4e3a38b provided by AppVeyor

Getting an error when saving any kind of track:
An assertion failed, please report this to the OpenRCT2 developers.
Version (see above)
Actual type doesn't match requested type
Abort - Retry - Ignore

- [ ] Reproducible in RCT2 (vanilla)?  I was able to save Looping designs in the original RCT2.
- [ ] Multiplayer? Have not tried it.

I have tried to save many track types and gotten this error.  Previously this week, I was able to save new tracks.  It also occurs in a park (RCT1 or 2 new scenario), not just the Track Designer.  

**Steps to reproduce:**
1. Launch the Track Designer
2. Create a Looping Roller Coaster, either a pre-saved track or from scratch; can be continuous or power launched. 
3. Test the ride
4. Click Save

If I can help elaborate the issue further, then just let me know.

### PR DESCRIPTION
**Pull request by marijnvdwerf**
The actual issue was caused by not setting `INTENT_EXTRA_PATH`, but I attempted to merge uint/sint to prevent future issues.

### CODE REVIEW

File: src/openrct2/windows/Intent.cpp [hunk 1]
```diff
@@ -75,8 +75,8 @@ uint32 Intent::GetUIntExtra(uint32 key)
     }
 
     auto data = _Data.at(key);
-    openrct2_assert(data.type == IntentData::DT_UINT, "Actual type doesn't match requested type");
-    return data.uintVal;
+    openrct2_assert(data.type == IntentData::DT_INT, "Actual type doesn't match requested type");
```
Comment (janisozaur) [inline src/openrct2/windows/Intent.cpp]: You assert on INT here, but request uint?

Comment (marijnvdwerf) [reply src/openrct2/windows/Intent.cpp]: I've combined UINT and SINT storage-wise, and get the proper type when fetching sint or uint

Comment (janisozaur) [reply src/openrct2/windows/Intent.cpp]: Nevermind that comment…
