### PR TITLE
Fix #19878: Pre-built rides respect scenery research

### LINKED ISSUE #19878: If trees and shrubbery aren't avaliable, they can still be placed with prebuilt design
### Operating System

WIndows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.4-63-gce4ca96 (ce4ca96 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The title speaks for itself, if the scenery groups "Trees" and "Shrubs and Ornaments" are not available, but prebuilt rides can still place them as if they were unlocked.

### Steps to reproduce

You can check this by disabling those two scenery groups and try to build anything that uses stuff from there, like the Inverted Hairpin Coaster "Hawksnest" or the Looping Roller Coaster "Bumble Bee."

### Attachments

Mad Matrix 2023-04-07 22-55-45

### PR DESCRIPTION
**Pull request by mrmbernardi**
Fix for #19878

Pre built tracks now respect whether or not scenery has been researched. This matches the behaviour with vehicle types.

There is also a fix for `ResearchIsInvented`, which was incorrectly converting `ObjectType` enums to `SceneryType` enums.

### CODE REVIEW

File: src/openrct2/ride/TrackDesign.cpp [hunk 1]
```diff
@@ -762,7 +762,7 @@ static std::optional<TrackSceneryEntry> TrackDesignPlaceSceneryElementGetEntry(c
             result.Type = obj->GetObjectType();
             result.Index = objectMgr.GetLoadedObjectEntryIndex(obj);
         }
-        else
+        if (obj == nullptr || (!ResearchIsInvented(result.Type, result.Index) && !gCheatsIgnoreResearchStatus))
```
Comment (Broxzier) [inline src/openrct2/ride/TrackDesign.cpp:765]: The first condition is the exact inverse of the previous, so imo it's nicer to keep this as an else-block:
```suggestion
        else if (!ResearchIsInvented(result.Type, result.Index) && !gCheatsIgnoreResearchStatus)
```

Comment (mrmbernardi) [reply src/openrct2/ride/TrackDesign.cpp:765]: That would defeat the point of this PR. Scenery which is in the scenario (`obj != nullptr`) but not yet researched would then never be marked as unavailable since it would always take first if branch.

Your suggestion would work if we were testing an && condition, but this is an ||.

Comment (Broxzier) [reply src/openrct2/ride/TrackDesign.cpp:765]: You're right, these two ifs aren't mutually exclusive anymore, and I now notice that this is actually using the values from the previous if block in the condition.

Rewriting this to make it more obvious that there are two conditions for the object's availability would be nice:


```cpp
        auto obj = objectMgr.GetLoadedObject(scenery.scenery_object);
        bool objectIsAvailable = obj != nullptr;
        if (objectIsAvailable)
        {
            result.Type = obj->GetObjectType();
            result.Index = objectMgr.GetLoadedObjectEntryIndex(obj);
            objectIsAvailable = ResearchIsInvented(result.Type, result.Index);
        }

        if (objectIsAvailable && !gCheatsIgnoreResearchStatus))
```

**Comment by mrmbernardi** [comment]
I rebased, added a changelog entry, and changed the logic to match your suggestion @Broxzier

**Review by Broxzier — APPROVED** [review]
LGTM. Haven't tested the build, though.

**Comment by mrmbernardi** [comment]
A simple test case is trying to build the Deep Freeze looping coaster in the build your own six flags park. Try it with and without the cheat, and after using hyperspeed to research the scenery.

File: src/openrct2/management/Research.cpp [hunk 2]
```diff
@@ -537,11 +537,15 @@ bool ResearchIsInvented(ObjectType objectType, ObjectEntryIndex index)
...
+            return SceneryIsInvented({ SCENERY_TYPE_SMALL, index });
         case ObjectType::LargeScenery:
+            return SceneryIsInvented({ SCENERY_TYPE_LARGE, index });
         case ObjectType::Walls:
+            return SceneryIsInvented({ SCENERY_TYPE_WALL, index });
         case ObjectType::Banners:
+            return SceneryIsInvented({ SCENERY_TYPE_BANNER, index });
         case ObjectType::PathAdditions:
-            return SceneryIsInvented({ static_cast<uint8_t>(objectType), index });
+            return SceneryIsInvented({ SCENERY_TYPE_PATH_ITEM, index });
```
Comment (duncanspumpkin) [inline src/openrct2/management/Research.cpp:548]: urgh we really need to get rid of SCENERY_TYPE and just have object type. Future problem.

Comment (mrmbernardi) [reply src/openrct2/management/Research.cpp:548]: Is there an issue for this?
