### PR TITLE
Fix #11343, 11344. Remove all peeps cheat causes a crash/hang

### LINKED ISSUE #11343: Using remove all guests cheat freezes the game
**OS:** [Windows 10]
**Version:** [0.2.6]
**Commit/Build:** [3bf316e]

1. Use remove all guests cheat in any park
2. Game will freeze

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Caused by a refactor.

### CODE REVIEW

File: src/openrct2/actions/SetCheatAction.hpp [hunk 1]
```diff
@@ -685,9 +685,12 @@ DEFINE_GAME_ACTION(SetCheatAction, GAME_COMMAND_CHEAT, GameActionResult)
             }
         }
 
-        Peep* peep;
-        FOR_ALL_GUESTS (spriteIndex, peep)
+        // Do not use the FOR_ALL_PEEPS macro for this as next sprite index
+        // will be fetched on a delted peep.
```
Comment (tupaschoal) [inline src/openrct2/actions/SetCheatAction.hpp:689]:
```suggestion
        // will be fetched on a deleted peep.
```

Comment (Gymnasiast) [inline src/openrct2/actions/SetCheatAction.hpp:689]:
```suggestion
        // will be fetched on a deleted peep.
```

File: src/openrct2/actions/SetCheatAction.hpp [hunk 2]
```diff
@@ -685,9 +685,12 @@ DEFINE_GAME_ACTION(SetCheatAction, GAME_COMMAND_CHEAT, GameActionResult)
...
 
-        Peep* peep;
-        FOR_ALL_GUESTS (spriteIndex, peep)
+        // Do not use the FOR_ALL_PEEPS macro for this as next sprite index
+        // will be fetched on a deleted peep.
+        for (spriteIndex = gSpriteListHead[SPRITE_LIST_PEEP]; spriteIndex != SPRITE_INDEX_NULL;)
         {
+            auto peep = GET_PEEP(spriteIndex);
+            spriteIndex = peep->next;
             peep->Remove();
```
Comment (duncanspumpkin) [inline src/openrct2/actions/SetCheatAction.hpp:694]: This will also remove staff. Need to fix.
