### PR TITLE
Fix #25963: Crash when loading corrupted saves with duplicate entity indices

### LINKED ISSUE #15128: [1003dd] openrct2.exe: S6Importer::ImportEntity<Vehicle>
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/1003dd40545f59df3e692603ca81cac4fdbc4fd87414ffa2e2d6ce4fae9adb25">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\Krieger\Documents\OpenRCT2\fc957de6-9add-4ef9-9250-b5854838878e.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>fault.address</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>version</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>error.message</strong> &mdash; 1
        <ul>
                <li><code>EXCEPTION_ACCESS_VIOLATION_WRITE</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>5087e77</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-write</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
S6Importer::ImportEntity&lt;Vehicle&gt;</code>
        </td>
    </tr></table>

### LINKED ISSUE #25963: [3aeae6] openrct2.exe: OpenRCT2::RCT2::S6Importer::ImportEntityCommonProperties
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIzYWVhZTYxZDg5Yjg1YzFiNDY4Nzk2YjI1N2NjMzBhMDNjMjNlZTZhOTFhYTM4MGYyMTRlYmY1MTNkNzBiZTljIiwidHgiOjM0Nzg0fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=3aeae61d89b85c1b468796b257cc30a03c23ee6a91aa380f214ebf513d70be9c&amp;_tx=87e0&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Sat Feb 07 2026 00:09:11 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\marjo\OneDrive\Documenten\OpenRCT2\crash\42cff3a5-d14f-4d70-831a-847dcabe7321.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                dae57fccf6 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x00</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_WRITE</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.31 (dae57fccf6) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>0c000000-479f-390f-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2::RCT2::S6Importer::ImportEntityCommonProperties</code> 
                                <code>OpenRCT2::RCT2::S6Importer::ImportEntity&lt;Vehicle&gt;</code> 
                                <code>OpenRCT2::RCT2::S6Importer::ImportEntities</code> 
                                <code>OpenRCT2::RCT2::S6Importer::Import</code> 
                                <code>OpenRCT2::Context::LoadParkFromStream</code> 
                                <code>OpenRCT2::Context::LoadParkFromFile</code> 
                                <code>OpenRCT2::Ui::FileBrowser::Select</code> 
                                <code>OpenRCT2::Ui::Windows::LoadSaveWindow::onScrollMouseDown</code> 
                                <code>OpenRCT2::InputScrollBegin</code> 
                                <code>OpenRCT2::InputWidgetLeft</code> 
                                <code>OpenRCT2::GameHandleInputMouse</code> 
                                <code>OpenRCT2::GameHandleInput</code> 
                                <code>ContextHandleInput</code> 
                                <code>OpenRCT2::TitleScene::Tick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::Launch</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-write</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> OpenRCT2::RCT2::S6Importer::ImportEntityCommonProperties OpenRCT2::RCT2::S6Importer::ImportEntity&lt;Vehicle&gt; OpenRCT2::RCT2::S6Importer::ImportEntities OpenRCT2::RCT2::S6Importer::Import OpenRCT2::Context::LoadParkFromStream OpenRCT2::Context::LoadParkFromFile OpenRCT2::Ui::FileBrowser::Select OpenRCT2::Ui::Windows::LoadSaveWindow::onScrollMouseDown OpenRCT2::InputScrollBegin OpenRCT2::InputWidgetLeft OpenRCT2::GameHandleInputMouse OpenRCT2::GameHandleInput ContextHandleInput OpenRCT2::TitleScene::Tick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### PR DESCRIPTION
**Pull request by frozensnowy**
Fixes #15128, #15626, #16331, #17443, #18626, #21597, #24175, #24971 and #25963

Corrupted RCT1 and RCT2 saves can have multiple entities with the same `EntityIndex`, causing `CreateEntityAt` to return `nullptr` which causes a crash in `ImportEntityCommonProperties`

This fix sanetizes `EntityIndex` values during import by setting each entity's index to match its array position.

I also added a unit test for this case with a corrupted version of "Blackpool Pleasure Beach"

### CODE REVIEW

**Comment by janisozaur** [comment]
Any idea how does it get corrupted?

**Comment by frozensnowy** [comment]
Not sure, I tried looking for a specific reason why it could be happening too. Maybe a race condition or a multiplayer desync? Entities are checksummed but not individually synchronized by index so if a desync occurs it could create entities at wrong indices

**Comment by janisozaur** [comment]
That can't be it - we would see this in .park files as well then

**Comment by frozensnowy** [comment]
Hmm, that's true. It could be old saves from the original RCT2 that were already corrupted somehow?, or maybe something specific to how S6 files are exported? The crash reports don't have much context about where the saves came from

But I'm just guessing at this point, I have no clue

File: test/tests/EntityImportTests.cpp [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+    auto* entity2 = gameState.entities.CreateEntityAt<Guest>(EntityId::FromUnderlying(100));
+    EXPECT_EQ(entity2, nullptr);
+}
+
+// This test verifies that corrupted S6 files with duplicate EntityIndex values can be loaded without crashing.
+TEST_F(EntityImportTests, S6ImportCorruptedDuplicateEntityIndicesDoesNotCrash)
+{
+    MemoryStream buffer;
+    std::string testParkPath = TestData::GetParkPath("corrupted_duplicate_entity_indices.sv6");
+    ASSERT_TRUE(LoadFileToBuffer(buffer, testParkPath));
```
Comment (janisozaur) [inline test/tests/EntityImportTests.cpp]: Use `FileStream` here

**Review by janisozaur — APPROVED** [review]

**Comment by Gymnasiast** [comment]
@ZeeMaji Could you test this with a few SV4/SV6 files to see if nothing breaks?

**Comment by ZeeMaji** [comment]
Sure.

**Review by ZeeMaji — APPROVED** [review]
Tested quite a few different s4 and s6 parks, both normal and hacked. All of them seemed to import and work fine.

**Review by Gymnasiast — APPROVED** [review]

**Comment by janisozaur** [comment]
I haven't checked earlier how big sv6 file was, I kinda wish I had - it seems it's fairly large compared to what it tests. I haven't actually loaded it, is there anything else in it?

**Comment by frozensnowy** [comment]
@janisozaur It's a modified version of Blackpool Pleasure Beach as I mentioned in the PR description, but it's pretty big, I should see if I can make a smaller one
