### PR TITLE
Fix #25237: Wrong colours on Knight costume

### LINKED ISSUE #25237: Peep animations always render pink tones as secondary remap
### Operating System

Linux (Debian 13)

### OpenRCT2 build

OpenRCT2, v0.4.26

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This issue has to do with park objects and/or asset packs

### Describe the issue

Peep animations always render the pink tones as secondary remap, even if the peep type or object doesn't enable the second remap explicitly. This is causing issues for the knight entertainer costume as it uses pink tones on a few of it's frames so they look worse now. On newly spawned entertainers it will always render pink tones as black as that's what value it defaults to in OpenRCT2, but for ones inherited from older save games like the attached good knight park save it can be other colors. Like yellow as seen below.

It would probably make sense to fix this by adding 'has remap' flags to peep animation objects similar to what many other objects have, and to render pink tones as pink whenever secondary remap is disabled.

### Steps to reproduce

1. Open the attached park, the knights' capes have yellow & black splotches where it should be pink.

### Attachments

Test park
[Good Knight Parkknightcapesrecolored.park.tar.gz](https://github.com/user-attachments/files/22483127/Good.Knight.Parkknightcapesrecolored.park.tar.gz)
How the sprites look (note the pink highlights on the cape)
Image
How it looks ingame (pink getting treated as second remap)
Image

### PR DESCRIPTION
**Pull request by Gymnasiast**
Templated the function while I was at it, which may make it a smidgen faster if there are a lot of peeps.

### CODE REVIEW

File: src/openrct2/entity/Peep.cpp [hunk 1]
```diff
@@ -2741,13 +2741,14 @@ void Peep::Serialise(DataSerialiser& stream)
     stream << PeepFlags;
 }
 
+template<bool isStaff>
 void Peep::Paint(PaintSession& session, int32_t imageDirection) const
```
Comment (AaronVanGeffen) [inline src/openrct2/entity/Peep.cpp]: Have you compared codegen for this? Templating the function means it'll likely generate two separate functions. I wonder if this means we're more likely to get a cache miss when iterating over all peeps. I'll take minor branching over that.

Comment (Gymnasiast) [reply src/openrct2/entity/Peep.cpp]: >  Templating the function means it'll likely generate two separate functions.

Well... yes, that’s the whole point.

> I wonder if this means we're more likely to get a cache miss when iterating over all peeps.

No. This function is called from `EntityPaintSetup()`, which uses a switch to map all entity types. So we’re not losing any speed there.

File: src/openrct2/entity/Peep.cpp [hunk 2]
```diff
@@ -2797,55 +2798,63 @@ void Peep::Paint(PaintSession& session, int32_t imageDirection) const
...
+            auto itemOffset = kPeepSpriteUmbrellaItemStart;
+            imageId = ImageId(itemOffset + (imageDirection >> 3) + itemFrame * 4, guest->UmbrellaColour);
+            PaintAddImageAsChild(session, imageId, offset, bb);
+            return;
+        }
     }
 }
 
+template void Peep::Paint<false>(PaintSession& session, int32_t imageDirection) const;
+template void Peep::Paint<true>(PaintSession& session, int32_t imageDirection) const;
```
Comment (AaronVanGeffen) [inline src/openrct2/entity/Peep.cpp]: I assume this is leftover from an earlier stage, considering it's at the end of the file?

File: src/openrct2/entity/Peep.cpp (hunk 1 above)
Comment (AaronVanGeffen) [reply src/openrct2/entity/Peep.cpp]: Okay, but this was not obvious to me when I looked at the diff. It would help to write down your thoughts in the OP in such cases.

I'll be frank; I don't really see the point in templating this. I expect there to not be a measurable performance difference, either way. But if you feel strongly about this, I don't feel strongly about it, either.

File: src/openrct2/entity/Peep.cpp (hunk 2 above)
Comment (AaronVanGeffen) [reply src/openrct2/entity/Peep.cpp]: Never mind, I see why this is necessary. The functions need to be instantiated at _some_ point. I'm not a fan of this, tbh, but it's not a blocker for me either.

File: src/openrct2/paint/Paint.Entity.cpp [hunk 3]
```diff
@@ -138,8 +138,10 @@ void EntityPaintSetup(PaintSession& session, const CoordsXY& pos)
                 }
                 break;
             case EntityType::guest:
+                entity->cast<Peep>()->Paint<false>(session, image_direction);
```
Comment (duncanspumpkin) [inline src/openrct2/paint/Paint.Entity.cpp]: Are we sure this is a hot function that actually needs to be templated? There looks to be all of 3 compares that this is for which seems a bit ott. I think it might make more sense to just have a GuestPaint and StaffPaint with a small amount of common code. Then we get the benefit of any templating but also improve the readability.

Comment (Gymnasiast) [reply src/openrct2/paint/Paint.Entity.cpp]: Fair enough, I have now done that.

**Comment by Gymnasiast** [comment]
I have now refactored the code to split out the guest and staff paint functions, which I will happily admit has made for more readable code than my initial templating approach. I used the tile element paint refactor as the base of my approach.

File: src/openrct2/entity/Peep.cpp [hunk 4]
```diff
@@ -26,7 +26,6 @@
 #include "../core/Guard.hpp"
 #include "../core/String.hpp"
 #include "../drawing/Drawing.h"
```
Comment (AaronVanGeffen) [inline src/openrct2/entity/Peep.cpp:28]: I think the Drawing.h and Paint.h can be removed now. (And possibly more?)

**Review by AaronVanGeffen — COMMENTED** [review]
Cheers for reworking this into moving the paint functions into different files. This separation of concerns (or lack thereof) is something that's been bugging me for a while.

File: src/openrct2/entity/Peep.h [hunk 5]
```diff
@@ -421,7 +421,6 @@ struct Peep : EntityBase
     [[nodiscard]] CoordsXY GetDestination() const;
 
     void Serialise(class DataSerialiser& stream);
-    void Paint(PaintSession& session, int32_t imageDirection) const;
```
Comment (Gymnasiast) [inline src/openrct2/entity/Peep.h:424]: Forward declare of PaintSession can also be removed from Peep.h.

File: src/openrct2/entity/Peep.cpp (hunk 4 above)
Comment (Gymnasiast) [reply src/openrct2/entity/Peep.cpp:28]: Unfortunately, no. `Drawing.h` is needed for `gPickupPeepImage` and `Paint.h` is needed for `GfxInvalidateScreen()`.

Comment (AaronVanGeffen) [reply src/openrct2/entity/Peep.cpp:28]: But `GfxInvalidateScreen` is declared in `Drawing.h`, not `Paint.h`. IDE fluke?

Comment (Gymnasiast) [reply src/openrct2/entity/Peep.cpp:28]: It may just be a Gymnasiast fluke, actually.

**Review by AaronVanGeffen — APPROVED** [review]
Might be worth separating the refactor from the fix. LGTM otherwise.
