### PR TITLE
Fix #25028: Food stall objects cannot use more than one carColours entry for random placement

### LINKED ISSUE #25028: Food stall objects cannot use more than one carColours entry for random placement.
### Operating System

Linux (Debian 13)

### OpenRCT2 build

OpenRCT2, v0.4.25

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

If a food stall object has more than one carColours entry defined, only the first one will be used. All subsequent entries will be ignored. Replacing the fruity ices stall carColours table with the following table:
```
        "carColours": [
            [
                [
                    "light_blue",
                    "black",
                    "black"
                ]
            ],
            [
                [
                    "bright_red",
                    "black",
                    "black"
                ]
            ],
            [
                [
                    "black",
                    "black",
                    "black"
                ]
            ]
        ]
```
-will not work as expected. Expected behavior would be a random preset being used from this list upon building a new stall similar to other rides, however the actual behavior will be the light blue (first) preset being picked every time.

### Steps to reproduce

1. Make a custom food stall or modify a default one to use the above carColours table.
2. Build that stall in-game, the colours will always be the first preset.

### Attachments

11 stalls all placed with the same colour, this is with the carColours table from above being used.
Image

### PR DESCRIPTION
**Pull request by traggodsanoj**
Fixes #25028

Fixes the issue with stall objects (any shop/stall) always being placed using the first carColours preset as opposed to a random one.

Here a version of the Fruity Ice Stall with the original 3 presets (light blue, bright red, black) for testing:
[rct2.ride.icecr1new.parkobj.zip](https://github.com/user-attachments/files/23286918/rct2.ride.icecr1new.parkobj.zip)
Also a hat stall (same color presets):
[rct2.ride.hatstnew.json](https://github.com/user-attachments/files/23286967/rct2.ride.hatstnew.json)

A separate pull request will be opened on the objects repo to fix the Fruity Ice Stall

### CODE REVIEW

**Comment by traggodsanoj** [comment]
See [OpenRCT2/objects/#417](https://github.com/OpenRCT2/objects/pull/417) for the correction to the RCT1 and 2 Objects

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -4347,7 +4347,7 @@ int32_t RideGetRandomColourPresetIndex(ride_type_t rideType)
  *
  *  Based on rct2: 0x006B4776
  */
-void Ride::setColourPreset(uint8_t index)
+void Ride::setColourPreset(uint8_t index, uint8_t indexVeh)
```
Comment (Gymnasiast) [inline src/openrct2/ride/Ride.cpp]: `indexVeh` is not remotely making clear what it does. The code at line +4360-4364 isn’t either.

Comment (traggodsanoj) [reply src/openrct2/ride/Ride.cpp]: Would `indexVehicle` written out make it clearer, or just use `index2` to be more consistent with the RideCreateAction code?
Instead of only taking the randomised track color scheme index, it is now also getting the randomised vehicle color scheme index. Should I also rename the original index to `indexTrack` or something as well?

Comment (Gymnasiast) [reply src/openrct2/ride/Ride.cpp]: Let’s make them `trackColourPreset` and `vehicleColourPreset`.

File: src/openrct2/actions/RideCreateAction.cpp [hunk 2]
```diff
@@ -139,7 +139,7 @@ namespace OpenRCT2::GameActions
 
         ride->type = _rideType;
         ride->subtype = rideEntryIndex;
-        ride->setColourPreset(_colour1);
+        ride->setColourPreset(_colour1, _colour2);
```
Comment (Gymnasiast) [inline src/openrct2/actions/RideCreateAction.cpp]: I take it `_colour1` represents the track colour preset index, and `_colour2` the vehicle colour preset index? If so, please rename `_colour1` to `_trackColourPreset` and `_colour2` to `_vehicleColourPreset`.

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
I like it. It’s a small detail, but still fun.
And it makes players aware that this colour _can_ be changed.

afbeelding
