### PR TITLE
Fix #21289: Map window does not layout properly

### LINKED ISSUE #21289: Letters sticking out of the Map window
### Operating System

Windows 11 Pro,  64-bit

### OpenRCT2 build

OpenRCT2, v0.4.7

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The "Info, Kiosk" string in some languages is too long and does not fit the window.
Also when you move the screen by moving the cursor to the edge of the screen while having the "Info, Kiosk" tag outside of the window, it would print out the letters outside a lot of times and looks buggy.

スクリーンショット 2024-01-28 124856
スクリーンショット 2024-01-28 124920

### Steps to reproduce

1. Change the language to one of the following: Català, Español, Français, Français (CA), Japanese, Português
2. Open a park.
3. Click on the map option in the top toolbar and show the map.
4. Change the tab inside to "Show rides and stalls on map".

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mrmbernardi**
Fixes #21289

Map window will now layout dynamically depending on the width of the text in each column.

Also fixes a small issue where the scrollbars for the map don't update properly when changing tabs.

I've added a window event so the window can be notified when the language changes and update its layout.  Currently its only used for this window but I think there are other bugs to do with changing languages that could use this in a fix.

### CODE REVIEW

File: src/openrct2/interface/Window.cpp [hunk 1]
```diff
@@ -1522,6 +1527,11 @@ void WindowEventScrollDrawCall(WindowBase* w, DrawPixelInfo& dpi, int32_t scroll
     w->OnScrollDraw(scrollIndex, dpi);
 }
 
+void WindowEventLanguageChangeCall(WindowBase* w)
```
[the remark this answers is not in the document]
Comment (mrmbernardi) [reply src/openrct2/interface/Window.cpp]: Removed. Is there an issue to remove the others?

[the remark this answers is not in the document]
Comment (Gymnasiast) [reply src/openrct2/interface/Window.cpp]: I don’t think there is one yet.

**Review by Gymnasiast — APPROVED** [review]

**Comment by Gymnasiast** [comment]
Tested it, appears to work correctly.

File: src/openrct2-ui/windows/Map.cpp [hunk 2]
```diff
@@ -1404,18 +1410,49 @@ class MapWindow final : public Window
...
+        for (uint32_t i = 4; i < std::size(MapLabels); i++)
+        {
+            OpenRCT2::FormatStringLegacy(buffer, sizeof(buffer), MapLabels[i], ft.Data());
+            min_width = std::max(static_cast<int16_t>(textOffset + GfxGetStringWidth(buffer, FontStyle::Medium)), min_width);
+        }
+        width = std::max(min_width, width);
+        _recalculateScrollbars = true;
+    }
+
     uint8_t _activeTool;
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Map.cpp:1437]: why is this window upside down for the member variables ???. Could you in a follow on PR make it so that member variables are at the top of the class.

File: src/openrct2-ui/windows/Map.cpp [hunk 3]
```diff
@@ -1404,18 +1410,49 @@ class MapWindow final : public Window
...
+    void CalculateTextLayout()
+    {
+        utf8 buffer[512];
+        Formatter ft;
+
+        int32_t textOffset = 4 + LIST_ROW_HEIGHT;
+        _firstColumnWidth = 118;
+        for (uint32_t i = 0; i < 4; i++)
+        {
+            OpenRCT2::FormatStringLegacy(buffer, sizeof(buffer), MapLabels[i], ft.Data());
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Map.cpp:1422]: Formatter is empty here? what is this even doing. All you are doing here is getting the string for the maplabel. LanguageGetString(MapLabel[i]) would do that much simpler

```cpp
int32_t maxFirstColumnString = 0;
for (uint32_t i = 0; i < 4; i++)
{
    const auto label = MapLabels[i];
    const auto* labelStr = GetLanguageString(label);
    maxFirstColumnString = std::max(GfxGetStringWidth(labelStr, FontStyle::Medium), maxFirstColumnString);
}
_firstColumnWidth = std::max(textOffset + maxFirstColumnString, 118); // Is 118 defined anywhere??
```

Comment (Gymnasiast) [reply src/openrct2-ui/windows/Map.cpp:1422]: The last argument to `FormatStringLegacy` is a buffer, so it’s hardly surprising `ft` is empty.

Comment (mrmbernardi) [reply src/openrct2-ui/windows/Map.cpp:1422]: Does it make a difference if the map label has formatting tags in it?

Comment (duncanspumpkin) [reply src/openrct2-ui/windows/Map.cpp:1422]: If they had formatting tags that need args then yes if they are just post process tags then no.  I guess should check which sort they are before making my sort of change.

File: src/openrct2-ui/windows/Map.cpp (hunk 2 above)
Comment (mrmbernardi) [reply src/openrct2-ui/windows/Map.cpp]: I did it in a separate commit on this PR since I figured I've been a bit slow.

File: src/openrct2-ui/windows/Map.cpp (hunk 3 above)
Comment (mrmbernardi) [reply src/openrct2-ui/windows/Map.cpp]: They're just colours. Seems to work fine with your suggestion. Thanks.

**Review by Gymnasiast — APPROVED** [review]

**Review by duncanspumpkin — APPROVED** [review]
