### PR TITLE
Fix #25745: Crash when a player connection is aborted early

### LINKED ISSUE #25737: [50853a] openrct2.exe: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiI1MDg1M2FlMTJhYmRlMzljODM2NWI5ZjAwYjA3YmNlZTI4YjI4ZmI0YTg0NTZmNzE2OGYwNzdhNTdjNjMxNDhlIiwidHgiOjM0Mzc4fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=50853ae12abde39c8365b9f00b07bcee28b28fb4a8456f7168f077a57c63148e&amp;_tx=864a&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Jan 05 2026 04:34:42 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\Gabriel\Documents\OpenRCT2\crash\a6b0648d-c808-42a1-ba2d-306d0fc9e1bf.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>67000000-3417-f90e-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateUpdateLogic</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunVariableFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateUpdateLogic OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunVariableFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25738: [400e7d] openrct2.exe: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiI0MDBlN2Q1ZTY0M2U1MDQzOGRkNjIwMDkzYmViOTVkZjJlYzUzNGEzM2EwYzM0Mzk4Yzg5YTAzODU1MDZkNDg4IiwidHgiOjM0MzgzfSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=400e7d5e643e50438dd620093beb95df2ec534a33a0c34398c89a0385506d488&amp;_tx=864f&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>2</b> occurrences since (Mon Jan 05 2026 06:34:42 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 2        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 2        <ul>
                        <li>
                                <code>C:\Users\tofem\OneDrive\Documents\OpenRCT2\crash\9f7b21ad-ca4f-430a-827a-fb7cf860483c.ini B</code> 
                                &mdash; 1 (50.00%)
            </li>
                        <li>
                                <code>C:\Users\tofem\OneDrive\Documents\OpenRCT2\crash\bcbcab57-871e-40f8-bf4d-9013b8ded571.ini B</code> 
                                &mdash; 1 (50.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 2        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 2        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 2        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 2        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 2        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 2        <ul>
                        <li>
                                <code>6c000000-3417-f90e-0000-000000000000</code> 
                                &mdash; 1 (50.00%)
            </li>
                        <li>
                                <code>6b000000-3417-f90e-0000-000000000000</code> 
                                &mdash; 1 (50.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 2        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25745: [a74840] openrct2.com: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJhNzQ4NDA1MDliZTAyMGExNmE2MGVjM2M0YzE2ODJmMDc0MzAzNDNlNTEwNTY2MTg1OGVmM2RmYjg2MWZmNTA1IiwidHgiOjM0Mzg5fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=a74840509be020a16a60ec3c4c1682f07430343e5105661858ef3dfb861ff505&amp;_tx=8655&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Jan 05 2026 18:34:43 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.com</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.com</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>D:\AMPDatastore\Instances\RollerCoasterTycoon201\openrct2\server\user-data\crash\e19514fc-8dcf-4ac9-b333-2ce392b379b3.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>72000000-3417-f90e-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25755: [2f2780] openrct2.exe: std::_String_val<std::_Simple_types<char> >::_Large_mode_engaged
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIyZjI3ODAzNDJjZTUzNzg3YzI3OTJiZWNhMzJlNzRjNGExZmJkODllODdlMmRkMzcwMmQ1MDQxZDZmNmRhOTY0IiwidHgiOjM0NDAyfSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=2f2780342ce53787c2792beca32e74c4a1fbd89e87e2dd3702d5041d6f6da964&amp;_tx=8662&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Tue Jan 06 2026 18:34:49 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\brady\OneDrive\Documents\OpenRCT2\crash\b181d1c6-d666-4f48-ae3e-b8c486154b62.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x18</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>82000000-3417-f90e-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Large_mode_engaged</code> 
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Large_mode_engaged std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25785: [1c425a] RCT2.exe: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIxYzQyNWE3OTUzYWI1N2VhZWJmMDg4YTAyZjQ4MjU1ZjdkMzkzMjc5NDMyOGRiZWYxMDlkYTdkYWYwZjdiMGM3IiwidHgiOjM0NDMwfSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=1c425a7953ab57eaebf088a02f48255f7d3932794328dbef109da7daf0f7b0c7&amp;_tx=867e&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Fri Jan 09 2026 18:39:57 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>RCT2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>RCT2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\dodam\OneDrive\문서\OpenRCT2\crash\25aa8320-41e0-4447-985c-46666f712bd2.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>0d000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateUpdateLogic</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateUpdateLogic OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25789: [28993d] openrct2.exe: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIyODk5M2QwYjM0Y2QzOTRmY2M3ZDZjOTA1ZTFkMTU0MmEyNGYyZGQxNTgzZjMxZDI5OGQ4NzlhYTU3NWQ5MzVmIiwidHgiOjM0NDU3fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=28993d0b34cd394fcc7d6c905e1d1542a24f2dd1583f31d298d879aa575d935f&amp;_tx=8699&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>2</b> occurrences since (Sun Jan 11 2026 02:40:01 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 2        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 2        <ul>
                        <li>
                                <code>D:\Documents\OpenRCT2\crash\1d1a9d39-914d-4de8-89cb-337904a94fae.ini B</code> 
                                &mdash; 1 (50.00%)
            </li>
                        <li>
                                <code>D:\Documents\OpenRCT2\crash\e6605686-e754-4689-aec8-3f7abceffbfa.ini B</code> 
                                &mdash; 1 (50.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 2        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 2        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 2        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 2        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 2        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 2        <ul>
                        <li>
                                <code>30000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (50.00%)
            </li>
                        <li>
                                <code>2f000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (50.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 2        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunVariableFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 2 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunVariableFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25795: [ae0839] openrct2.com: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJhZTA4MzkwOGM0YTQxYjAwYzQxNzZjMGQwMmZhMmRmZjJiMjY4NDAzZGM1NzJjMzI3ODM0ZmNmZmRjYjY2YmFkIiwidHgiOjM0NDc2fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=ae083908c4a41b00c4176c0d02fa2dff2b268403dc572c327834fcffdcb66bad&amp;_tx=86ac&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>4</b> occurrences since (Sun Jan 11 2026 16:40:04 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.com</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 4        <ul>
                        <li>
                                <code>openrct2.com</code> 
                                &mdash; 4 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 4        <ul>
                        <li>
                                <code>C:\Users\FransWeerwag\Documents\OpenRCT2\crash\faf14e5b-b844-4784-b865-e2335bc342cf.ini B</code> 
                                &mdash; 1 (25.00%)
            </li>
                        <li>
                                <code>C:\Users\FransWeerwag\Documents\OpenRCT2\crash\e992717e-b22f-4500-8271-9ea5128165db.ini B</code> 
                                &mdash; 1 (25.00%)
            </li>
                        <li>
                                <code>C:\Users\FransWeerwag\Documents\OpenRCT2\crash\56b778b2-b6a5-4216-bedb-82446f2bb886.ini B</code> 
                                &mdash; 1 (25.00%)
            </li>
                        <li>
                                <code>C:\Users\FransWeerwag\Documents\OpenRCT2\crash\e560322d-3e8b-4104-a6d9-23c7f81a6cac.ini B</code> 
                                &mdash; 1 (25.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 4        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 4 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 4        <ul>
                        <li>
                                e4d122d7be 
                                &mdash; 4 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 4        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 4 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 4        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 4 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 4        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (e4d122d7be on develop) provided by GitHub</code> 
                                &mdash; 4 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 4        <ul>
                        <li>
                                <code>43000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (25.00%)
            </li>
                        <li>
                                <code>42000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (25.00%)
            </li>
                        <li>
                                <code>41000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (25.00%)
            </li>
                        <li>
                                <code>40000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (25.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 4        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::Launch</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 4 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::Launch OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25800: [73fd6d] openrct2.com: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiI3M2ZkNmRlMGQwNDIzYzZjNWY0NDY3MzNkYTEzM2Q2NTBkM2FlZGI0NzUyZTlkNzExNDQ1MTVhMmQ5NzUyZjQ4IiwidHgiOjM0NDg5fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=73fd6de0d0423c6c5f446733da133d650d3aedb4752e9d71144515a2d9752f48&amp;_tx=86b9&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Jan 12 2026 01:40:05 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.com</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.com</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\AMPDatastore\Instances\RCT01\openrct2\server\user-data\crash\5a8ac9c8-5654-4f08-835a-76b48c5e6e9b.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>50000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateUpdateLogic</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateUpdateLogic OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25807: [05eaef] RCT2.EXE: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIwNWVhZWZjMTVmMWJlMmRkYzk3NGZjOTQ0MDk1YjY3MGYzNWUzMTE5MWJlMTA4MzQ5ZTIxZmE2MDA2OTVhNTI2IiwidHgiOjM0NTAwfSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=05eaefc15f1be2ddc974fc944095b670f35e31191be108349e21fa600695a526&amp;_tx=86c4&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Mon Jan 12 2026 23:43:07 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>RCT2.EXE</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>RCT2.EXE</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\AdmiralCrayon\Documents\OpenRCT2\crash\5335f0ec-75be-4cdb-b160-56a083820af5.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>5c000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### LINKED ISSUE #25808: [35929a] RCT2.EXE: std::_String_val<std::_Simple_types<char> >::_Myptr
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiIzNTkyOWEzNTkxZjg1MjlhOGZjOWUyODgyOTUxYTFiNTVhYTkwNmUwMjM1NDcxMjY0NjY3ZWJjNzIyNmJlOWNlIiwidHgiOjM0NTAyfSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=35929a3591f8529a8fc9e2882951a1b55aa906e0235471264667ebc7226be9ce&amp;_tx=86c6&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Tue Jan 13 2026 00:43:09 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>RCT2.EXE</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>RCT2.EXE</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\AdmiralCrayon\Documents\OpenRCT2\crash\89018e5b-9346-42ed-b343-f722c7a59aac.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                b0f30a5bfa 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x20</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_ACCESS_VIOLATION_READ</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.30 (b0f30a5bfa) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>5e000000-93b9-140f-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr</code> 
                                <code>std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str</code> 
                                <code>OpenRCT2::Network::NetworkBase::TickServer</code> 
                                <code>OpenRCT2::Network::NetworkBase::Tick</code> 
                                <code>OpenRCT2::Network::Tick</code> 
                                <code>OpenRCT2::gameStateUpdateLogic</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>invalid-read</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> std::_String_val&lt;std::_Simple_types&lt;char&gt; &gt;::_Myptr std::basic_string&lt;char,std::char_traits&lt;char&gt;,std::allocator&lt;char&gt; &gt;::c_str OpenRCT2::Network::NetworkBase::TickServer OpenRCT2::Network::NetworkBase::Tick OpenRCT2::Network::Tick OpenRCT2::gameStateUpdateLogic OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### PR DESCRIPTION
**Pull request by Gymnasiast**
Note: there are 5-6 additional issues that should be linked, but GitHub only allows linking 10.

### CODE REVIEW

File: src/openrct2/network/NetworkBase.cpp [hunk 1]
```diff
@@ -547,7 +547,10 @@ namespace OpenRCT2::Network
 
             if (!ProcessConnection(*connection))
             {
-                LOG_INFO("Disconnecting player %s", connection->player->Name.c_str());
+                if (connection->player != nullptr)
+                    LOG_INFO("Disconnecting player %s", connection->player->Name.c_str());
+                else
+                    LOG_INFO("Disconnecting unknown player");
                 connection->Disconnect();
```
Comment (AaronVanGeffen) [inline src/openrct2/network/NetworkBase.cpp:554]: This is still dereferencing the nullptr, isn't it? We should probably move it into the `if` block.

Comment (Gymnasiast) [reply src/openrct2/network/NetworkBase.cpp:554]: No, it is not. The nullptr check is for `connection->player`. We’ve already established `connection` is not null on line 548.

Comment (AaronVanGeffen) [reply src/openrct2/network/NetworkBase.cpp:554]: You're right. I misread, sorry.

**Review by AaronVanGeffen — APPROVED** [review]
