### PR TITLE
Fix #12969: Crash opening ride window with invalid mechanic assigned

### LINKED ISSUE #12969: [b7d42f] openrct2.com: window_ride_maintenance_paint, window_draw_single, window_draw, std::_Func_impl_no_alloc<<lambda_c6239...
<table>
    <tr>
        <td></td>
        <td><b><a href="https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/b7d42ff0fcd7d8dbf0fe827d782dc70dff4a49baa5f48c35abd5e79df2e99fa9">New error: [openrct2]</a></b><br /><b>1</b> occurrence since (Fri Nov 15 2019 11:27:39)<br /></td>
    </tr>
</table><table>
    <tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>
<tr>
    <td><strong>Attributes</strong></td>
    <td>
<strong>dummy</strong> &mdash; 1
        <ul>
                <li><code>0</code> &mdash; 1</li></ul><br>
<strong>attachment_replay.sv6r</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\ELAC\Documents\OpenRCT2\da2ee99d-f60e-4ccf-b7bf-5e63957a1865.sv6r</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_config.ini</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\ELAC\Documents\OpenRCT2\da2ee99d-f60e-4ccf-b7bf-5e63957a1865.ini</code> &mdash; 1</li></ul><br>
<strong>assert_failure</strong> &mdash; 1
        <ul>
                <li><code>*</code> &mdash; 1</li></ul><br>
<strong>attachment_park.sv6.gz</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\ELAC\Documents\OpenRCT2\da2ee99d-f60e-4ccf-b7bf-5e63957a1865.sv6.gz</code> &mdash; 1</li></ul><br>
<strong>attachment_screenshot.png</strong> &mdash; 1
        <ul>
                <li><code>C:\Users\ELAC\Documents\OpenRCT2\screenshot\Cliffside Castle 2020-09-18 22-11-57.png</code> &mdash; 1</li></ul><br>
<strong>commit</strong> &mdash; 1
        <ul>
                <li><code>135cc10</code> &mdash; 1</li></ul><br></td>
    </tr>
    <tr>
        <td><strong>Classifiers</strong></td>
        <td>
            <strong>invalid-read</strong><br></td>
    </tr>
    <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code>
window_ride_maintenance_paint
window_draw_single
window_draw
std::_Func_impl_no_alloc&lt;&lt;lambda_c6239a5f162a90c22f819d59f2036264&gt;,void,rct_window *&gt;::_Do_call
window_visit_each(std::function&lt;void __cdecl
window_draw_all
OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks
OpenRCT2::Drawing::X8DrawingEngine::PaintWindows
OpenRCT2::Paint::Painter::Paint
OpenRCT2::Context::RunGameLoop
OpenRCT2::Context::RunOpenRCT2
NormalisedMain
wmain</code>
        </td>
    </tr></table>

### PR DESCRIPTION
**Pull request by ZehMatt**
Closes #12969

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]

File: src/openrct2-ui/windows/Ride.cpp [hunk 1]
```diff
@@ -4295,7 +4295,7 @@ static void window_ride_maintenance_paint(rct_window* w, rct_drawpixelinfo* dpi)
             }
             else
             {
-                auto peep = GetEntity<Peep>(ride->mechanic)->AsStaff();
+                auto peep = GetEntity<Staff>(ride->mechanic);
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/Ride.cpp:4298]: could change the name to staff

Comment (ZehMatt) [reply src/openrct2-ui/windows/Ride.cpp:4298]: Yeah true, lemme do it.

**Review by tupaschoal — APPROVED** [review]
