### PR TITLE
Fix #7239: Remove all guests cheat crashes with ferris wheel

### LINKED ISSUE #7239: The remove Guest cheat option crashes the game on some maps
- [ no] Reproducible in RCT2 (vanilla)?
- [no ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the maps
2. Press the remove guest cheat
[The OpenRCT2 Group Park 7.96.zip](https://github.com/OpenRCT2/OpenRCT2/files/1789776/The.OpenRCT2.Group.Park.7.96.zip)

**Dump file**

**Screenshots / Video:**

**Save game:**

### PR DESCRIPTION
**Pull request by deurklink**
Unlike other rides, a ferris wheel does not start from vehicle->peeps[0] when storing the guests that are currently riding it. This caused the loop i made in my previous commit to try and get a peep with index SPRITE_INDEX_NULL. I fixed this by adding an offset. 

If the loop now encounters a peep with SPRITE_INDEX_NULL in the list, it will increment offset until it finds one with a correct index. This loop now works regardless of whether the null index is at the start, center, or end of the list. Other rides should be unaffected because they fill vehicle->peeps starting from peeps[0].

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you bump the network version?

File: src/openrct2/Cheats.cpp [hunk 1]
```diff
@@ -374,10 +374,14 @@ static void cheat_remove_all_guests()
             while (spriteIndex != SPRITE_INDEX_NULL)
             {
                 vehicle = GET_VEHICLE(spriteIndex);
-
+                size_t offset = 0;
                 for (size_t i = 0; i < vehicle->num_peeps; i++)
```
Comment (Gymnasiast) [inline src/openrct2/Cheats.cpp]: `for (size_t i = 0, offset = 0; i < vehicle->num_peeps; i++) `

Comment (deurklink) [reply src/openrct2/Cheats.cpp]: OK, didn't know that syntax 😁
