### PR TITLE
Fix #11829: Glitches when using mismatched csg1/csg1i

### LINKED ISSUE #11829: Missing RCT1 Installation mismatch fail case check
**OS:** Windows 10
**Version:** 0.2.6-659-g2bd92527f
**Commit/Build:** 2bd9252

The game crashes when the RCT1 installation has a mismatch of data files, where the csg1i.dat from Loopy Landscapes is present while the installation for Loopy Landscapes on the other CSG files is not.
This means that a user (definitely not me) who's had RCT1 installed prior to OpenRCT2 may have forgotten to install the Loopy Landscapes expansion, even though having copied the csg1i.dat file from the Loopy Landscapes CD.

**Steps to reproduce:**
1. Install the RCT1 base game (optionally Added Attractions as well)
2. Copy the csg1i.dat from the Loopy Landscapes CD as OpenRCT2 instructs
3. The game will crash occasionally upon loading the game, and parks/scenarios

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/config/Config.cpp [hunk 1]
```diff
@@ -1000,7 +1000,7 @@ bool RCT1DataPresentAtLocation(const utf8* path)
 
 bool CsgIsUsable(const rct_gx& csg)
 {
-    return csg.header.num_entries == RCT1_NUM_LL_CSG_ENTRIES;
+    return csg.header.total_size == 41402869 && csg.header.num_entries == RCT1_NUM_LL_CSG_ENTRIES;
```
Comment (tupaschoal) [inline src/openrct2/config/Config.cpp:1003]: We should have a `constexpr` for that hardcoded number to improve documentation

**Review by tupaschoal — APPROVED** [review]
