### PR TITLE
Fix "Can't remove this" error when trying to remove rotated rides

### LINKED ISSUE #15947: Error "can't remove this" when removing a turned pirate ship via the ride construction window
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (c9c6172 on develop) provided by GitHub

### Describe the issue

Trying to remove a rotateds pirate ship results in a error "can't remove this", causing an invalid game state where the game thinks you remove the pirate ship, but it is still in the world.

If you don't spot this error, you can then place the pirate ship down again, and it gets quite confusing as the rest of the code only expects a pirate ship ride to only have 1 building

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Load a new game
2. Select the pirate ship in the building menu
3. Press the rotate button (https://i.imgur.com/FQNjEWj.png)
4. Place the rotated pirate ship in the game (https://i.imgur.com/bJ0tTJ6.png)
5. Press right click to select it
6. Press the destroy button ( https://i.imgur.com/qgpA9ax.png)

Observe the bug: 
image

The game now allows you to place it down again, while it is still present in the world, leading to all other "can't happen" state bugs

### Attachments

_No response_

### LINKED ISSUE #15960: Built 2 "stations" for pirate ship by accident?
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (b9bc8d0) provided by GitHub

### Describe the issue

Was trying to build pirate ship, built it, entrance, but when I tried to build exit there was no usable space left, I clicked at some busy spot (landscape issue), got message about landscape, tried to remove ship, got error that it can't be removed and got suggested to build second pirate ship which I successfully did as displayed in this screenshot.

### Area(s) with issue?

_No response_

### Steps to reproduce

As described above.

### Attachments

[2 pirate ship is this a bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/7580169/2.pirate.ship.is.this.a.bug.zip)
2021-11-22-15-20-04_openrct2

### PR DESCRIPTION
**Pull request by GalBr**
Fixes #15947
Fixes #15960 
This change fixes a problem where when trying to remove a rotated ride,
_currentTrackPieceDirection would be reset back to 0 by calling
ride_initialise_construction_window, causing TrackRemoveAction to not
being able to find and remove the ride.
Using a local variable with the current direction, saved before resetting
the global variable, fixes this issue.

### CODE REVIEW

**Comment by GalBr** [comment]
This change breaks removing a tracked ride (roller coasters, water rides, etc) elements one by one. I'll investigate. Feel free to suggest a better way to fix this issue.

File: src/openrct2-ui/windows/RideConstruction.cpp [hunk 1]
```diff
@@ -1586,6 +1586,7 @@ static void WindowRideConstructionConstruct(rct_window* w)
 static void WindowRideConstructionMouseupDemolish(rct_window* w)
 {
     int32_t direction;
+    Direction currentDirection = _currentTrackPieceDirection;
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/RideConstruction.cpp:1589]: Let’s add a comment here explain why we need to save the direction (because it is reset by `ride_initialise_construction_window()`).

Comment (GalBr) [reply src/openrct2-ui/windows/RideConstruction.cpp:1590]: Good idea, thanks.
