### PR TITLE
Fix #9970: Wait for quarter load fails

### LINKED ISSUE #9970: Wait for quarter load fails
**OS:** Windows 10
**Version:** 0.2.3-324
**Commit/Build:** 1d6e4d7

Wait for quarter load does not wait for any guests. Trains will still leave as if this option was not selected (even empty).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open RCT1LL scenario Megaworld Park
2. Observe Viper (in the sand area)
Or build any coaster and enable 'wait for quarter load'. (I checked multiple coasters in different parks, but coincidentally only corkscrews)

### PR DESCRIPTION
**Pull request by aw20368**
Two commits:
* First commit only fixes the bug. Brings behaviour in line with vanilla.
* Second commit contains a refactor. This change will make rides will actually wait for >= 25% load (described in #9970), unlike vanilla.

Will squash if both commits approved.
Assuming network version bump + changelog entry (can repro in v0.0.5).

### CODE REVIEW

File: src/openrct2/ride/Vehicle.cpp [hunk 1]
```diff
@@ -2363,61 +2363,20 @@ static void vehicle_update_waiting_for_passengers(rct_vehicle* vehicle)
...
-            }
-
-            uint8_t three_quater_seats = (3 * num_seats_on_train) / 4;
-            if (three_quater_seats != 0 && num_peeps_on_train >= three_quater_seats)
-            {
-                vehicle->update_flags |= VEHICLE_UPDATE_FLAG_TRAIN_READY_DEPART;
-                train_ready_to_depart(vehicle, num_peeps_on_train, num_used_seats_on_train);
-                return;
-            }
+            double peepTarget = (((double)load + 1) * num_seats_on_train) / 4;
```
Comment (ZehMatt) [inline src/openrct2/ride/Vehicle.cpp]: This can actually yield different results on different cpus/platforms, use integers only.

**Comment by Gymnasiast** [comment]
I have decided to cherry-pick the fix while we sort out the refactor. Could you rebase this PR?

**Comment by aw20368** [comment]
Done. Rebased and addressed review.

**Comment by aw20368** [comment]
Does the refactor need another network version bump? It'll change when a train can leave (by a little bit).

**Comment by ZehMatt** [comment]
If it changes the mechanics then it should be done or the game will diverge during multiplayer if you have two different versions.

File: src/openrct2/ride/Vehicle.cpp [hunk 2]
```diff
@@ -2363,60 +2363,20 @@ static void vehicle_update_waiting_for_passengers(rct_vehicle* vehicle)
...
-                return;
-            }
-
-            if (num_seats_on_train / 2 != 0 && num_peeps_on_train >= num_seats_on_train / 2)
-            {
-                vehicle->update_flags |= VEHICLE_UPDATE_FLAG_TRAIN_READY_DEPART;
-                train_ready_to_depart(vehicle, num_peeps_on_train, num_used_seats_on_train);
-                return;
-            }
+            uint8_t peepTarget = ((load + 1) * num_seats_on_train + 3) / 4;
```
Comment (Gymnasiast) [inline src/openrct2/ride/Vehicle.cpp]: `+3` looks very messy, and isn't in the original code.

Comment (aw20368) [reply src/openrct2/ride/Vehicle.cpp]: The intent was to compute ceiling( (load+1)/4 * num_seats), and the +3 is a trick to bypass the need of floats/doubles.

It's not in the original code because it did not actually wait for a quarter load. In #9970 there's a screenshot of vanilla RCT1 starting an 18-car train with 4 occupants at "wait for quarter load".

I mean, it's a bit of an argument over semantics, but I expected that 18-car train to leave at 6 occupants rather than 4. I could be convinced otherwise (removing the +3 reverts the behaviour to vanilla and doesn't affect the rest of the logic).

Comment (Gymnasiast) [reply src/openrct2/ride/Vehicle.cpp]: I wrote out the results for a train with room for 18 people:

Load | "Real" result | RCT1/2 | This PR
--- | --- | --- | ---
Quarter | 4.5 | 4 | 5
Half | 9 | 9 | 9
Three q. | 13.5 | 13 | 14

Since the option is _minimum_ load, rounding up is indeed more in line with what people expect. I am assuming that the compiler will first do the multiplication and only then the addition.

I'd like to see the following things:
- A comment that explains why the +3 is there
- A changelog entry: `- Improved: [#9987] Minimum load rounding.`
- A network version bump

Comment (aw20368) [reply src/openrct2/ride/Vehicle.cpp]: Done, force pushed.
