### PR TITLE
Fix #24617: Prevent hired boat with 0 speed causing division by 0

### LINKED ISSUE #24617: [ede1fd] openrct2.exe: Vehicle::UpdateMotionBoatHire
<table>
    <tr>
        <td></td>
        <td>
            <b><a href="https://openrct2.sp.backtrace.io/p/openrct2/triage?_t=W3siZXJyb3IiOnsiZmluZ2VycHJpbnQiOiJlZGUxZmRiMTc5ZWE1ODJhNDhkYTY3ZGVjZGY1YzBkNjRjZGVhM2Q2YTE3NjY3YjBjMGUzZjEwZjUzMDQ2ZTg0IiwidHgiOjMyMzk5fSwicGx1Z2luIjp7InBsdWdpbklkIjoiZ2l0aHViIn0sImludGVncmF0aW9uIjp7ImlkIjo0NzJ9LCJpbnN0YW5jZSI6eyJhZGRyZXNzIjoiaHR0cHM6Ly9vcGVucmN0Mi5zcC5iYWNrdHJhY2UuaW8ifX1d&amp;fingerprint=ede1fdb179ea582a48da67decdf5c0d64cdea3d6a17667b0c0e3f10f53046e84&amp;_tx=7e8f&amp;time=quarter">New error: [openrct2]</a></b
            ><br /><b>1</b> occurrence since (Fri Jun 13 2025 22:42:42 GMT+0000 (Coordinated Universal Time))<br />
        </td>
    </tr>
</table>
<table>
    <tr>
        <td><strong>Application</strong></td>
        <td>openrct2.exe</td>
    </tr>
        <td><strong>Attributes</strong></td>
    <td>
                 <strong>application</strong> &mdash; 1        <ul>
                        <li>
                                <code>openrct2.exe</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>attachment_config.ini</strong> &mdash; 1        <ul>
                        <li>
                                <code>C:\Users\rbris\Documents\OpenRCT2\crash\413380e7-4386-403d-9674-be3eac546220.ini B</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>assert_failure</strong> &mdash; 1        <ul>
                        <li>
                                <code>*</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>commit</strong> &mdash; 1        <ul>
                        <li>
                                <code>b8d73b523c</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>fault.address</strong> &mdash; 1        <ul>
                        <li>
                                <code>0x00007FF650476417</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>error.message</strong> &mdash; 1        <ul>
                        <li>
                                <code>EXCEPTION_INT_DIVIDE_BY_ZERO</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>version</strong> &mdash; 1        <ul>
                        <li>
                                <code>OpenRCT2, v0.4.23 (b8d73b523c) provided by GitHub</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>_rxid</strong> &mdash; 1        <ul>
                        <li>
                                <code>21000000-eed0-ff0d-0000-000000000000</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
                <strong>callstack</strong> &mdash; 1        <ul>
                        <li>
                                <code>Vehicle::UpdateMotionBoatHire</code> 
                                <code>Vehicle::UpdateTravellingBoat</code> 
                                <code>Vehicle::Update</code> 
                                <code>VehicleUpdateAll</code> 
                                <code>OpenRCT2::gameStateUpdateLogic</code> 
                                <code>OpenRCT2::gameStateTick</code> 
                                <code>OpenRCT2::Context::Tick</code> 
                                <code>OpenRCT2::Context::RunFixedFrame</code> 
                                <code>OpenRCT2::Context::RunFrame</code> 
                                <code>OpenRCT2::Context::RunGameLoop</code> 
                                <code>OpenRCT2::Context::RunOpenRCT2</code> 
                                <code>NormalisedMain</code> 
                                <code>wmain</code> 
                                <code>invoke_main</code> 
                                &mdash; 1 (100.00%)
            </li>
                     </ul>
             </td>
         <tr>
        <td><strong>Classifiers</strong></td>
        <td>
                        <strong>intdiv</strong><br />
                    </td>
    </tr>
         <tr>
        <td><strong>Frames</strong></td>
        <td>
            <code> Vehicle::UpdateMotionBoatHire Vehicle::UpdateTravellingBoat Vehicle::Update VehicleUpdateAll OpenRCT2::gameStateUpdateLogic OpenRCT2::gameStateTick OpenRCT2::Context::Tick OpenRCT2::Context::RunFixedFrame OpenRCT2::Context::RunFrame OpenRCT2::Context::RunGameLoop OpenRCT2::Context::RunOpenRCT2 NormalisedMain wmain invoke_main </code>
        </td>
    </tr>
     </table>

### PR DESCRIPTION
**Pull request by janisozaur**
In the failing scenario `Vehicle::speed` was set to 0

### CODE REVIEW

File: src/openrct2/ride/Vehicle.cpp [hunk 1]
```diff
@@ -3920,7 +3920,10 @@ void Vehicle::UpdateMotionBoatHire()
             }
             eax -= velocity;
             edx = powered_acceleration * 2;
-            ecx += (eax * edx) / ebx;
+            if (ebx != 0)
```
Comment (ZehMatt) [inline src/openrct2/ride/Vehicle.cpp:3923]: Can't believe we still have such variable names, most of the code looks like its working out acceleration.

**Review by Gymnasiast — COMMENTED** [review]
I’d like a changelog entry.

I don’t have strong views on changing the variable naming (seems a bit outside the scope for me.

File: src/openrct2/ride/Vehicle.cpp (hunk 1 above)
Comment (Gymnasiast) [reply src/openrct2/ride/Vehicle.cpp:3923]: A few lines down it writes the value of `ecx` to `acceleration`. So I guess we could name this `newAcceleration` or something? Not sure if that should be done here or in another PR - I’ll leave that up to you two.

Comment (ZehMatt) [reply src/openrct2/ride/Vehicle.cpp:3923]: Just saying, it can be done in this PR or another, either way works for me.

**Review by Gymnasiast — APPROVED** [review]
