### PR TITLE
Map window: fix technical/practical terminology

### LINKED ISSUE #22225: Scroll bar scales wrong in -1x-1 sized park
### Operating System

Win 11

### OpenRCT2 build

Latest Dev (4-12-2023)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

I edited the safe file to create a park that displays as -1x-1 in the map. In doing so I noticed the scrollbar was broken. This might be due to some other issue, and hence the bug report here. 

### Steps to reproduce

Open park, see map, see scroll bar

### Attachments

[-1x-1ParkNoCS.zip](https://github.com/user-attachments/files/16110051/-1x-1ParkNoCS.zip)

### PR DESCRIPTION
**Pull request by Gymnasiast**
The technical size is 2 tiles bigger than the practical size, due to the ring of invisible tiles at the edge. This was not correctly used in the Map window.

### CODE REVIEW

File: src/openrct2-ui/windows/Map.cpp [hunk 1]
```diff
@@ -54,22 +54,22 @@ namespace OpenRCT2::Ui::Windows
     {
         return MapColour2((colour & 0xFF00) >> 8, PALETTE_INDEX_10);
     }
-    static int32_t getTechnicalMapSize()
+    static int32_t getPracticalMapSize()
     {
         // Take non-square maps into account
-        return std::max(GetGameState().MapSize.x, GetGameState().MapSize.y) - 2;
+        return std::max(std::max(GetGameState().MapSize.x, GetGameState().MapSize.y) - 2, 0);
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/Map.cpp:60]:
```suggestion
        return std::max({GetGameState().MapSize.x, GetGameState().MapSize.y, 0});
```
(Might not match what clang-format expects)

Comment (Gymnasiast) [reply src/openrct2-ui/windows/Map.cpp:60]: `clang-format` has not complained, so it’s apparently fine with him.

I’d have to test to see if 1×1 would work, assuming stuff is going to end in tears :')

Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/Map.cpp:60]: > `clang-format` has not complained, so it’s apparently fine with him.

Heh, I meant my suggestion, not what's currently there. (I suspect `clang-format` would like spaces around the braces.)

Comment (Gymnasiast) [reply src/openrct2-ui/windows/Map.cpp:60]: I think you removed the `- 2` in your suggestion by accident.

Comment (AaronVanGeffen) [reply src/openrct2-ui/windows/Map.cpp:60]: Nice catch. Yes, that was unintentional.

File: src/openrct2-ui/windows/Map.cpp [hunk 2]
```diff
@@ -764,9 +765,12 @@ static Widget window_map_widgets[] = {
         {
             int32_t x = 0, y = 0, dx = 0, dy = 0;
 
-            int32_t pos = (_currentLine * (getMiniMapWidth() - 1)) + getTechnicalMapSize() - 1;
-            auto destinationPosition = ScreenCoordsXY{ pos % getMiniMapWidth(), pos / getMiniMapWidth() };
-            auto destination = _mapImageData.data() + (destinationPosition.y * getMiniMapWidth()) + destinationPosition.x;
+            auto miniMapWidth = getMiniMapWidth();
+            int32_t pos = (_currentLine * (miniMapWidth - 1)) + getPracticalMapSize() - 1;
+            auto destinationPosition = ScreenCoordsXY(0, 0);
+            if (miniMapWidth > 0)
```
Comment (AaronVanGeffen) [inline src/openrct2-ui/windows/Map.cpp:771]: Hmm, I don't like the added guard here, to be honest. I'd also prefer not to have to add one to `getPracticalMapSize` either. 

Frankly, I think the hacked map should be rejected as corrupted instead. At best, I think the map size should be corrected to a positive integer when the park is imported, but honestly, there's no saving it, anyway, is there?

**Comment by ZehMatt** [comment]
I think it would be best to just clamp the value at the source, speaking of s4, s6, park, so we don't have to check it everywhere, that is runtime overhead we can avoid.

**Comment by Gymnasiast** [comment]
Very well. I’ll remove the bounds check stuff from this PR and keep just the function rename.

**Review by ZehMatt — APPROVED** [review]
