### PR TITLE
Fix #20607: Unicode string not limited properly

### LINKED ISSUE #20607: Freezing problem
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.5-202-g0a3573e (0a3573e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The game crashes every time I try to name the specific rollercoaster.

### Steps to reproduce

The game crashes when I click the name tag symbol of this rollercoaster.

### Attachments

Bug report

Here is a screenshot

### PR DESCRIPTION
**Pull request by mrmbernardi**
This is a fix for #20607. 

The cause appears to be that the string is limited to 32 characters. The existing code just chops it at 32 bytes without regarding the size of unicode characters. This leads to an invalid unicode character at the end of the string, and down the line an iterator gets confused and runs on forever.

I've fixed the code to properly limit the length unicode string, respecting the variable unicode character sizes.

I've also added a clamp to the iterator to prevent it running on forever if this bug appears elsewhere. I tested this without the length limiting fix and it prevents a crash, although the last few characters of the string will behave weirdly until the user backspaces through them.

### CODE REVIEW

File: src/openrct2/localisation/UTF8.cpp [hunk 1]
```diff
@@ -92,6 +92,21 @@ int32_t UTF8Length(const utf8* text)
     return count;
 }
 
+/**
+ * Gets the number of bytes required to store the first x characters in a UTF-8 string
```
Comment (duncanspumpkin) [inline src/openrct2/localisation/UTF8.cpp:96]: These aren't characters they are codepoints.

Comment (mrmbernardi) [reply src/openrct2/localisation/UTF8.cpp]: Changed to match the previous function

File: src/openrct2/core/String.hpp [hunk 2]
```diff
@@ -222,6 +222,10 @@ class CodepointView
                 GetNextCodepoint(&_str[_index], &nextch);
                 _index = nextch - _str.data();
             }
+            else
+            {
+                _index = _str.size();
+            }
```
Comment (ZehMatt) [inline src/openrct2/core/String.hpp:228]: This is still problematic, the _index is out of bounds for one iteration before it calls the operator again and only then it would equal the end iterator. Use std::min on line 223 to ensure _index is always clamped.

File: src/openrct2/core/String.hpp [hunk 3]
```diff
@@ -233,6 +237,10 @@ class CodepointView
...
```
Comment (ZehMatt) [inline src/openrct2/core/String.hpp:243]: Same here

File: src/openrct2/localisation/UTF8.cpp [hunk 4]
```diff
@@ -92,6 +92,21 @@ int32_t UTF8Length(const utf8* text)
...
 }
 
+/**
+ * Gets the number of bytes required to store the first x characters / codepoints in a UTF-8 string
+ */
+size_t UTF8Limit(const utf8* text, size_t limit)
+{
+    const utf8* ch = text;
+    const utf8* next_ch = text;
+    while (UTF8GetNext(ch, &next_ch) != 0 && limit > 0)
```
Comment (ZehMatt) [inline src/openrct2/localisation/UTF8.cpp:102]: UTF8GetNext should have a safe version, this is still prone to read past the buffer.

**Review by ZehMatt — CHANGES_REQUESTED** [review]

File: src/openrct2/core/String.hpp (hunk 3 above)
Comment (mrmbernardi) [reply src/openrct2/core/String.hpp]: As before

File: src/openrct2/localisation/UTF8.cpp [hunk 5]
```diff
@@ -92,6 +92,21 @@ int32_t UTF8Length(const utf8* text)
     return count;
 }
 
+/**
+ * Gets the number of bytes required to store the first x characters / codepoints in a UTF-8 string
+ */
+size_t UTF8Limit(const utf8* text, size_t limit)
```
[the remark this answers is not in the document]
Comment (mrmbernardi) [reply src/openrct2/localisation/UTF8.cpp]: I've removed this function and written a new function in `String.cpp`  which does the same thing but with string views. I moved it because UTF8.cpp seems to only have unsafe functions like this, whereas `String.cpp` has safer ones which use string views.

**Comment by mrmbernardi** [comment]
I've written a new version. Now the `CodepointView` is also resized to contain only valid utf8 codepoints upon construction.

https://github.com/OpenRCT2/OpenRCT2/pull/20623/files#diff-94ec288e999d421a6ddaca9a69ef3921151da5e4fa590a0ee6042f5408d43dc8R254

File: src/openrct2/core/String.hpp [hunk 6]
```diff
@@ -179,6 +179,12 @@ namespace String
      */
     std::string_view UTF8Truncate(std::string_view v, size_t size);
 
+    /**
+     * Truncates a string to at most `size` codepoints,
+     * making sure not to cut in the middle of a sequence.
+     */
+    std::string_view UTF8TruncateCodePoints(std::string_view v, size_t size);
```
Comment (ZehMatt) [inline src/openrct2/core/String.hpp:186]: Is this perhaps the same as UTF8Truncate?

Comment (mrmbernardi) [reply src/openrct2/core/String.hpp:186]: No, one limits the length in bytes and the other limits the length in terms of codepoints (unicode characters).

UTF8TruncateCodePoints("ゲスト", 3) gives "ゲスト"
 UTF8Truncate("ゲスト", 3) gives "ゲ"

**Comment by ZehMatt** [comment]
I think to fix the issue this is good enough, I'm not too happy about all the other places where it uses the unbounded version but that's for another PR. The code looks sensible to me, could you add a changelog entry please.

**Review by ZehMatt — APPROVED** [review]
