### PR TITLE
fix #2620 and preventing names with dots from breaking.

### LINKED ISSUE #2620: Game Crashes when saving in scenario editor
I'm not quite sure what exactly the problem is, but as soon as I enter in a Park and/or a scenario name and then try to save the scenario or the landscape the game instantly crashes.
Saving the landscape goes well unless I entered in a Park Name and/or a scenario name.
It might help that I've setted the game language to german and RCT2 and Open RCT2 are both on a second Hard Drive but are in different folders.

### PR DESCRIPTION
**Pull request by Broxzier**
A park named `before the dot.after the dot` would also save as just `before the dot`.

### CODE REVIEW

File: src/util/util.c [hunk 1]
```diff
@@ -109,7 +109,7 @@ void path_remove_extension(utf8 *path)
 {
 	// Find last dot in filename, and replace it with a null-terminator
 	char *lastDot = strrchr(path, '.');
-	if (*lastDot) *lastDot = '\0';
+	if (lastDot != NULL) *lastDot = '\0';
```
Comment (IntelOrca) [inline src/util/util.c]: Ah yes, I fixed this in my scenario select branch. I should have done it in develop.
