### PR TITLE
Fix naming inconsistencies and minor bugs concerning half loop elements

### LINKED ISSUE #19450: Medium Half Loop isn't build right when building from behind
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.3-276-geb33147 (eb33147 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

So, when you are building half loops fowards, it is fine, but when doing it the opposite way, it gose wrongly and stay as right if the 1st backward half is right and the same happens whit left if it was at first a left one. Colliding whit itself.

My develop version might be outdated, but I didn't found a develop version which fix this.

### Steps to reproduce

1. Build a single rail coaster (easiest option as it don't need any cheats)
2. build tracks backwards
3. try building a half loop
4. now the loop somewhat gose into itself when building the 2nd one

### Attachments

[https://youtu.be/eU24eP6DvGo](url)

### LINKED ISSUE #20342: something is double into the track list if you build
### Operating System

Windows 10 64 bit

### OpenRCT2 build

latest develop build

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

delete one into the code list

### Steps to reproduce

the large half loop left is double into the track list

### Attachments

image

### LINKED ISSUE #20456: Flying coaster large half loops (fly-to-lie) misnamed
### Operating System

Linux (doesn't matter)

### OpenRCT2 build

42ff4716172d07c4555c7519e9d91c379b1a95ed (latest develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

For the flying coaster, the names of the left and right downwards half-loops (fly-to-lie) are swapped. The "left" one actually goes right and vice-versa.

### Steps to reproduce

1. Open Track Designer
2. Choose Flying Coaster
3. Build a high-enough lift (say 30m), end with level piece
4. Select Special Elements -> Large Half Loop (left)
5. See that it actually goes right.

### Attachments

left-is-right

### PR DESCRIPTION
**Pull request by zzril**
This PR does:
* switch the variable names for left and right downward half loops to be consistent with the other elements
* update the names of painting functions specific to these elements in `src/openrct2/ride/coaster`
* reorder the large half loops in the special elements dropdown menu, so they only show up once
* reorder the medium half loops in the `gTrackCurveChain` array, so the correct pieces get suggested when building backwards

Fixes #19450.
Fixes #20342, which was a regression from #19951.
Fixes #20456.

### CODE REVIEW

**Comment by zzril** [comment]
I'm not really sure about *why* this change fixes it, see the [discussion](https://github.com/OpenRCT2/OpenRCT2/issues/20342#issuecomment-1595314507) started by me in the corresponding issue.

**Comment by ZehMatt** [comment]
I think it would be good to know what the cause of this problem is, while this seem to fix something it may break something else then. I'll see if I can figure out why this change causes it to be correct.

**Comment by ZehMatt** [comment]
> @ZehMatt I think I understand now why this solution works. See [this](https://github.com/OpenRCT2/OpenRCT2/issues/20342#issuecomment-1601605441) comment.
> 
> Instead of merely fixing the dropdown order array, I'll also take this chance to rename the variable in the code, so it'll hopefully lead to less confusion in the future. Converting this PR back to draft until I'm done with that.

Sorry for the delay, been a bit occupied with other things. I looked into the comment and it looks like you are right, I did look briefly into this but also got my head spinning around whats wrong with it so that makes quite a lot of sense. Also would be good if you can do the rename also so this is clear. We should perhaps also find a better way to keep those things matched but for a fix this will do.

File: src/openrct2/ride/coaster/SingleRailRollerCoaster.cpp [hunk 1]
```diff
@@ -13829,14 +13829,14 @@ namespace SingleRailRC
         }
     }
 
-    static void TrackRightLargeHalfLoopDown(
+    static void TrackLeftLargeHalfLoopDown(
         PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
         const TrackElement& trackElement)
     {
         TrackRightLargeHalfLoopUp(session, ride, 6 - trackSequence, direction, height, trackElement);
```
Comment (ZehMatt) [inline src/openrct2/ride/coaster/SingleRailRollerCoaster.cpp:13836]: Would this need adjusting in the name too or is that shared code for either left and right pieces?

Comment (zzril) [reply src/openrct2/ride/coaster/SingleRailRollerCoaster.cpp:13836]: There are 4 of these `Track(Left|Right)LargeHalf(Up|Down)` functions, one for each combination.

Since this is for some painting stuff, and the upwards left half-loop looks exactly the same as the downward right one, just viewed from the opposite angle (and vice-versa), the code for the "down" pieces just calls the code for the (visually identical) upper piece.

These functions are only called in the large switch statement in `GetTrackPaintFunction` and nowhere outside this file.

However, their names are based on the name of the to-be-painted `TrackElemType`. (See the [original file](https://github.com/OpenRCT2/OpenRCT2/blob/42ff4716172d07c4555c7519e9d91c379b1a95ed/src/openrct2/ride/coaster/SingleRailRollerCoaster.cpp#L17816-L17823).)

My first commit changed only the names of the `TrackElemType` constants (at their definition site and in all cases where the names are used), this commit now renames the SingleRailCoaster's specific painting functions whose names where based on the to-be-painted `TrackElemType` constants.

I'm doing the same for each coaster type in `src/openrct2/ride/coaster` that has a specific painting function for the half-loop element (there are like 5 or so), each in its own commit.

---

Will later squash some of the commits, but for the moment I try to split this refactor into as small bits as possible (while keeping the code fully functional at each commit).

**Comment by zzril** [comment]
Just realized that the track element flags for the flying coaster are also somewhat strange, need to investigate.

**Comment by zzril** [comment]
Alright, for the Flying Coaster, the `TRACK_ELEM_NORMAL_TO_INVERSION` flags are actually set on the lie-to-fly pieces, and `TRACK_ELEM_INVERSION_TO_NORMAL` is set on fly-to-lie pieces. (So, it starts in "inverted" mode.)

This is maybe somewhat unintuitive, but shouldn't make a difference for the inversion count.

And changing it is not easily possible as it shares some elements with the 4th-dimension coaster (the `MultiDimInvertedFlatToDown90QuarterLoop` and `MultiDimUp90ToInvertedFlatQuarterLoop`) where the flags make sense the way they are now ("inverted" is when the train is under the track).

So, I'll keep the flags as they are.

**Comment by zzril** [comment]
Turns out the large half loops with the train outside are indeed possible to build with cheats enabled, and I did not correctly rename those.
Will fix that and change to draft meanwhile.

**Comment by zzril** [comment]
Alright, had set some of the track elem flags incorrectly. Fixed.

**Review by ZehMatt — APPROVED** [review]
Great work on this, I've confirmed each individual issue to be resolved. Code also seems fine, so big thanks.

**Comment by ZehMatt** [comment]
Also requires a network version bump.

**Comment by zzril** [comment]
> Also requires a network version bump.

Done.

Shall I squash my commits or are you going to do a squash-merge anyway?

**Comment by ZehMatt** [comment]
> Shall I squash my commits or are you going to do a squash-merge anyway?

No need

**Review by Broxzier — APPROVED** [review]
Tested, and all looks good :+1:
