### PR TITLE
Fix #21919: Non-recolourable cars still show colour picker 

### LINKED ISSUE #21919: Teleporter Lift Cabins are not actually recolorable
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.10-107-g9266a6f (9266a6f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

The teleporter styled lift Cabin is not recolorable
asdadadasds

### Steps to reproduce

build elevator, switch to teleporter style, try to recolor cabins, nothing happens

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
Dependent on the v1.6.1 objects release, which will be pulled in in another PR.

### CODE REVIEW

File: src/openrct2/ride/CarEntry.h [hunk 1]
```diff
@@ -202,7 +203,7 @@ struct CarEntry
     uint8_t sprite_height_negative;
     uint8_t sprite_height_positive;
     CarEntryAnimation animation;
-    uint32_t flags;
+    uint64_t flags;
```
Comment (AaronVanGeffen) [inline src/openrct2/ride/CarEntry.h:206]: Just to check: does this require a park version bump?

Comment (Gymnasiast) [reply src/openrct2/ride/CarEntry.h:206]: It doesn’t, but it’s good you checked.

**Review by AaronVanGeffen — APPROVED** [review]
Seems to be working fine for me. Just needs a rebase and changelog entry.
