### PR TITLE
Fix #4415. Rides that change colours each train were incorrectly loaded

### LINKED ISSUE #4415: Go Karts are all in the same colour
**Commit/Build:** b0a8fb0a7c771d35e51e9f422c50758beabe4162 

When you build a Go Karts track in vanilla, the karts will all have a different colour. In OpenRCT2, they will all have the same colour.

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fix #4415 Rides that change colours each train were incorrectly loaded causing all same colour.

Mistake caused by new object loader not reproducing legacy technique used to indicate that a ride is a change colour each train type.

### CODE REVIEW

**Comment by IntelOrca** [comment]
Rather than storing a boolean for differentPerTrainColour. Just store the number of colours that need reading and use that for the loop.

File: src/object/RideObject.cpp [hunk 1]
```diff
@@ -90,15 +90,20 @@ void RideObject::ReadLegacy(IReadObjectContext * context, IStream * stream)
...
+        coloursCount = 32;
     }
-    for (uint8 i = 0; i < _presetColours.count; i++)
+
+    for (uint8 i = 0; i < coloursCount; i++)
     {
         _presetColours.list[i] = stream->ReadValue<vehicle_colour>();
     }
-
+
```
Comment (IntelOrca) [inline src/object/RideObject.cpp]: Trailing spaces
