### PR TITLE
Fix #17553: Crash when moving invention list items to empty list

### LINKED ISSUE #17553: Crash when moving invention list items to empty list
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-24-g213696e (213696e on develop) provided by GitHub

### Describe the issue

The game crashes when trying to move an invention list item from one list to the other one when the destination list is empty.

### Area(s) with issue?

_No response_

### Steps to reproduce

1. Open any park
2. Open the object selection
3. Move all items to top or bottom
4. Drag one item to the other list

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by jazzysoggy**
Fix #17553 

The original implementation was only checking whether the optional variable had at least one of the sub variables are defined. 

This leads to an error where if one of the Researched/non-researched list is a nullptr and the other variable exists, then the if condition will try to access a item on a nullptr array, leading to a crash.

The fix for this is to specifically check whether the list is a nullptr or not.

### CODE REVIEW

**Comment by Broxzier** [comment]
Please have another look at this regarding git commit messages: https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

File: src/openrct2-ui/windows/EditorInventionsList.cpp [hunk 1]
```diff
@@ -618,7 +618,7 @@ class InventionDragWindow final : public Window
         {
             res = inventionListWindow->GetResearchItemAt(newScreenCoords);
             newScreenCoords.y += LIST_ROW_HEIGHT;
-        } while (res.has_value() && res->research->IsAlwaysResearched());
+        } while (res->research != nullptr && res->research->IsAlwaysResearched());
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/EditorInventionsList.cpp:621]: You should still check has value

Comment (jazzysoggy) [reply src/openrct2-ui/windows/EditorInventionsList.cpp]: Readd has_check() to the while condition

**Review by duncanspumpkin — APPROVED** [review]
