### PR TITLE
Fix #18035: Favorited servers don't get their online status updated.

### LINKED ISSUE #18035: Favorited servers don't get their online status updated.
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.1-310-ga1be5de (a1be5de on develop) provided by GitHub

### Describe the issue

When you add a server to your favorites the online status is not updated/shown when fetching servers. So information like network version, online status and the amount of online players is missing.
The screenshot below shows the top of my Server List with a newly favorited server and the fetched version below it. I tried this with multiple servers and got the same result.
image

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Add server to favorites
2. Click "Fetch Servers" or close and reopen server menu
3. No online status shown

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by beam41**
From fetching flow, list will always have favorited servers but no code to update those entries only append.
This code updates those favorited servers in the list with new data from internet by matching address.
This will fix list having 2 duplicate servers too. (one favorited and one not)

### CODE REVIEW

**Review by IntelOrca — APPROVED** [review]

File: src/openrct2/network/ServerList.cpp [hunk 1]
```diff
@@ -150,6 +150,33 @@ void ServerList::AddRange(const std::vector<ServerListEntry>& entries)
...
 
+void ServerList::AddOrUpdateRange(const std::vector<ServerListEntry>& entries)
+{
+    for (auto& existsEntry : _serverEntries)
+    {
+        auto match = std::find_if(
+            entries.begin(), entries.end(), [&](const ServerListEntry& entry) { return existsEntry.Address == entry.Address; });
+        if (match != entries.end())
+        {
+            // keep favorites
```
Comment (Gymnasiast) [inline src/openrct2/network/ServerList.cpp:161]:
```suggestion
            // Keep favourites
```

File: src/openrct2-ui/windows/ServerList.cpp [hunk 2]
```diff
@@ -581,7 +580,8 @@ static void ServerListFetchServersCheck(rct_window* w)
             try
             {
                 auto [entries, statusText] = _fetchFuture.get();
-                _serverList.AddRange(entries);
+                _serverList.AddOrUpdateRange(entries);
+                _serverList.WriteFavourites(); // update favourites in case favourited server info changes.
```
Comment (Gymnasiast) [inline src/openrct2-ui/windows/ServerList.cpp:584]:
```suggestion
                _serverList.WriteFavourites(); // Update favourites in case favourited server info changes
```

**Review by Gymnasiast — CHANGES_REQUESTED** [review]
This needs a changelog entry:

`Fix: [#18035] Favourited servers don’t get their online status updated.`

I also have two minor corrections for the comments.

**Review by Gymnasiast — APPROVED** [review]
