### PR TITLE
Fix #4080 - Adding a error message when the track can't load

### LINKED ISSUE #4080: Ride list doesn't update when a ride gets deleted when game is open
Os: Windows 10
Version: 0.0.5
Build:fb456a8
If you delete a track design while in game. The list doesn't get update and shows just a blank ride. Not sure if causes a crash if chosen.

### PR DESCRIPTION
**Pull request by Nubbie**
Potential fix for: #4080

This will make a pop up message appear with a warning message, telling the player that something is wrong instead of not indicating anything 

asasg

### CODE REVIEW

File: src/windows/track_list.c [hunk 1]
```diff
@@ -181,7 +181,10 @@ static void window_track_list_close(rct_window *w)
 static void window_track_list_select(rct_window *w, int index)
 {
 	w->track_list.var_480 = index;
-
+	if (_loadedTrackDesign == NULL)
+		window_error_open(STR_CANT_BUILD_PARK_ENTRANCE_HERE, STR_TRACK_LOAD_FAILED_ERROR);
+	else
```
Comment (IntelOrca) [inline src/windows/track_list.c]: just return after showing the error.

Comment (Nubbie) [inline src/windows/track_list.c]: Would it be better to have ''return;'' would that display and work properly instead of this? As it feels like I should move this code further down or something xox

**Comment by Nubbie** [comment]
No clue if there is anything else that can be done than being tested xox

File: src/windows/track_list.c (hunk 1 above)
Comment (IntelOrca) [inline src/windows/track_list.c]: You need to add braces so that it only returns if _loadedTrackDesign is NULL

**Comment by Nubbie** [comment]
@IntelOrca Have done it now :+1: 
Hopefully put the brackets in the right place, if not, if it could be something _you or someone else_ could dom that would be much appreciated .n.
_Just so I don't spam a ton of commits_

File: src/windows/track_list.c [hunk 2]
```diff
@@ -181,7 +181,12 @@ static void window_track_list_close(rct_window *w)
 static void window_track_list_select(rct_window *w, int index)
 {
 	w->track_list.var_480 = index;
-
+	if (_loadedTrackDesign == NULL) // Displays a message if the ride can't load, fix #4080
+		{
```
Comment (duncanspumpkin) [inline src/windows/track_list.c]: Youve indented this one too many times it should be one tab for the bracket and two tab for the window_error_open line.

**Comment by Nubbie** [comment]
@duncanspumpkin well um something someone can fix before a merge so it doesn't take ages to get the tabs etc right? :(

**Comment by IntelOrca** [comment]
@Nubbie we can't edit the code via the web interface, only merge. So it would be easier if you did it.

**Comment by Nubbie** [comment]
@IntelOrca 
.n.

so is this correct
```
static void window_track_list_select(rct_window *w, int index)
{
	w->track_list.var_480 = index;
	if (_loadedTrackDesign == NULL) // Displays a message if the ride can't load, fix #4080
	{
			window_error_open(STR_CANT_BUILD_PARK_ENTRANCE_HERE, STR_TRACK_LOAD_FAILED_ERROR);
			return; 
		}
```

**Comment by IntelOrca** [comment]
no

**Comment by IntelOrca** [comment]
```
static void window_track_list_select(rct_window *w, int index)
{
    w->track_list.var_480 = index;

     // Displays a message if the ride can't load, fix #4080
    if (_loadedTrackDesign == NULL) {
            window_error_open(STR_CANT_BUILD_PARK_ENTRANCE_HERE, STR_TRACK_LOAD_FAILED_ERROR);
            return; 
    }
```

**Comment by Nubbie** [comment]
Yeah will definitely read more and look at examples everywhere to see how it's done

**Comment by IntelOrca** [comment]
@Nubbie now change it to use tabs, 1 tab = 4 spaces.

**Comment by Nubbie** [comment]
@IntelOrca Sorry about the inconvenience :/

**Comment by IntelOrca** [comment]
You are still using spaces.

**Comment by Nubbie** [comment]
:gun: 
Hope you're having a good time.. so how was ur day xoxox

**Comment by Nubbie** [comment]
Better?
