### PR TITLE
Fix #18839: New staff members now picked up correctly

### LINKED ISSUE #18839: Hiring new staff doesn't properly pick them up
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.2 built from 69e918b47bdc48c3645a918fd769b0e31158567c

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

_No response_

### Describe the issue

See title.

### Steps to reproduce

Have auto place staff disabled and hire any staff member.
Notice that their window opens up but is not held in the claw to place them somewhere.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by mdbckrtn**
When "Automatically place staff" is disabled, new staff members were not automatically placed into the "picked" state as is the case with vanilla RCT. This change ensures that new staff members are automatically placed into the picker and that, in scenarios where multiple new staff members are queued up without having first placed one, the most recently created staff member will be the actively picked up peep (also the case with vanilla).

It looks like this has been broken for some time (at least since 2020, when a refactor of `GameActions` occurred. But i'd suspect it's been around longer). The approach to resolving this was interesting - I initially thought it would make sense to wrap a `PeepPickupAction` inside of `StaffNewHireAction` but after more investigation this did not seem to be an idiomatic approach. Instead, I pulled what I needed into the callback of the relevant instance of `StaffNewHireAction` (which, I think, ends up being easier to read, too). I have not been able to test this PR in a networked context (any help there would be appreciated).

This PR resolves issue #18839

### CODE REVIEW

File: src/openrct2/actions/StaffHireNewAction.cpp [hunk 1]
```diff
@@ -190,6 +190,8 @@ GameActions::Result StaffHireNewAction::QueryExecute(bool execute) const
 
             // INVESTIGATE: x and y are LOCATION_NULL at this point.
             newPeep->MoveTo(newPeep->GetLocation());
+            network_set_pickup_peep(network_get_current_player_id(), newPeep);
```
Comment (duncanspumpkin) [inline src/openrct2/actions/StaffHireNewAction.cpp:193]: I'm not sure this will work. This action will be getting called by networked clients so you'll end up setting a peep to the wrong player id.

Comment (mdbckrtn) [reply src/openrct2/actions/StaffHireNewAction.cpp:193]: Thanks @duncanspumpkin. I did some testing and this indeed does not work in online games. Will take some time to review alternative options.

**Review by duncanspumpkin — CHANGES_REQUESTED** [review]
As discussed has issues with multiplayer atm.

**Comment by mdbckrtn** [comment]
> As discussed has issues with multiplayer atm.

Issues should be addressed now. Fix is in place and working for both SP and MP. @duncanspumpkin, please take another look when you get a chance. Thanks!

File: src/openrct2-ui/windows/StaffList.cpp [hunk 2]
```diff
@@ -531,6 +532,30 @@ class StaffListWindow final : public Window
             auto intent = Intent(WindowClass::Peep);
             intent.PutExtra(INTENT_EXTRA_PEEP, staff);
             ContextOpenIntent(&intent);
+
+            // If autoposition of staff is disabled, set the pickup tool on the newly created staff window
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/StaffList.cpp:536]: This looks fine. I need to have a little think if the fact the window is being opened by an intent is an issue with this function checking for a window being open

File: src/openrct2-ui/windows/StaffList.cpp [hunk 3]
```diff
@@ -531,6 +532,30 @@ class StaffListWindow final : public Window
...
+            if (staff->State == PeepState::Picked)
+            {
+                picked_peep_old_x = staff->x;
+                CoordsXYZ nullLoc{};
+                nullLoc.SetNull();
+
+                PeepPickupAction pickupAction{ PeepPickupType::Pickup,
+                                               EntityId::FromUnderlying(staff->sprite_index.ToUnderlying()), nullLoc,
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/StaffList.cpp:544]: No need for a `From` and a `To`

File: src/openrct2-ui/windows/StaffList.cpp [hunk 4]
```diff
@@ -531,6 +532,30 @@ class StaffListWindow final : public Window
...
+                                               NetworkGetCurrentPlayerId() };
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/StaffList.cpp:545]: On L525 you could give `const GameAction*` a name and then use the game actions `GetPlayer()` function. It's all going to be the same value but it feels neater in my mind.

File: src/openrct2-ui/windows/StaffList.cpp (hunk 2 above)
Comment (duncanspumpkin) [reply src/openrct2-ui/windows/StaffList.cpp:536]: Had a think with @ZehMatt and it would be best to do this differently. If we move the intent to open into a branch that is just for auto position we can have another intent to open purely from the pickup game action. Would look something like:
```
            auto* staff = GetEntity<Staff>(actionResult.StaffEntityId);

            // If autoposition of staff is disabled, pickup peep then open the staff window
            if (staff->State == PeepState::Picked)
            {
                picked_peep_old_x = staff->x;
                CoordsXYZ nullLoc{};
                nullLoc.SetNull();

                PeepPickupAction pickupAction{ PeepPickupType::Pickup,
                                               EntityId::FromUnderlying(staff->sprite_index.ToUnderlying()), nullLoc,
                                               NetworkGetCurrentPlayerId() };
                pickupAction.SetCallback(
                    [&staff](const GameAction* ga, const GameActions::Result* result) {
                        if (result->Error != GameActions::Status::Ok)
                            return;

                        auto intent = Intent(WindowClass::Peep);
                        intent.PutExtra(INTENT_EXTRA_PEEP, staff);
                        auto* wind = ContextOpenIntent(&intent);
                        if (wind != nullptr)
                        {
                            ToolSet(*wind, WC_STAFF__WIDX_PICKUP, Tool::Picker);
                        }
                    });
                GameActions::Execute(&pickupAction);
            }
            else
            {
                // Open window for new staff.
                auto intent = Intent(WindowClass::Peep);
                intent.PutExtra(INTENT_EXTRA_PEEP, staff);
                ContextOpenIntent(&intent);
            }
```

Comment (mdbckrtn) [reply src/openrct2-ui/windows/StaffList.cpp]: Done!

File: src/openrct2-ui/windows/StaffList.cpp (hunk 3 above)
Comment (mdbckrtn) [reply src/openrct2-ui/windows/StaffList.cpp]: Fixed!

File: src/openrct2-ui/windows/StaffList.cpp (hunk 4 above)
Comment (mdbckrtn) [reply src/openrct2-ui/windows/StaffList.cpp:540]: These two methods don't return the same value in my testing. In single player, `GetPlayer()` returns `-1` and `NetworkGetCurrentPlayerId()` returns `0` and so the pickup action doesn't work correctly. Am I missing something?

Comment (duncanspumpkin) [reply src/openrct2-ui/windows/StaffList.cpp:540]: Oh, that's a bit surprising. Leave as is then

**Review by duncanspumpkin — APPROVED** [review]
