### PR TITLE
Fix #3178: Precompose file name strings on macOS to prevent mojibake when displayed

### LINKED ISSUE #3178: Accents in open/save dialogs are displayed wrongly
**OS:** MacOS 10.11.4
**Version:** 0.0.4

When saving or loading a game, if a file has accents in its name, it will be shown as the unaccentuated letter followed with a ?. However on the disk, accents are fine.

For example, "é" becomes "e?", "à" becomes "a?".
- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
capture d ecran 2016-03-26 a 14 50 47
« Frontie?res Forestie?res » should read as « Frontières Forestières ».

capture d ecran 2016-03-26 a 14 54 00
It's fine in the Finder.

### PR DESCRIPTION
**Pull request by rwjuk**
Fixes #3178.

### CODE REVIEW

File: src/openrct2/platform/posix.c [hunk 1]
```diff
@@ -391,6 +391,10 @@ sint32 platform_enumerate_files_begin(const utf8 *pattern)
 				safe_strcpy(paths[idx], dir_name, path_len);
 				safe_strcat_path(paths[idx], d->d_name, path_len);
 				log_verbose("paths[%d] = %s", idx, paths[idx]);
+
+				#ifdef __MACOSX__
+					paths[idx] = macos_str_decomp_to_precomp(paths[idx]);
```
Comment (Gymnasiast) [inline src/openrct2/platform/posix.c]: Is it safe to overwrite `paths[idx]` like this?

Comment (rwjuk) [inline src/openrct2/platform/posix.c]: Hmmm... I suppose that'd depend on whether the precomposed string ends up being longer than the decomposed one. I can't think of any cases where that'd be the case, but either way, probably best to use `safe_strcpy()` just in case.

**Comment by Gymnasiast** [comment]
I'd like to see a comment explaining this block, as well as an entry in the changelog.

**Comment by Gymnasiast** [comment]
Could you rebase this? (Never merge develop into a PR branch, only rebase.)

File: src/openrct2/platform/posix.c [hunk 2]
```diff
@@ -391,6 +391,17 @@ sint32 platform_enumerate_files_begin(const utf8 *pattern)
 				safe_strcpy(paths[idx], dir_name, path_len);
 				safe_strcat_path(paths[idx], d->d_name, path_len);
 				log_verbose("paths[%d] = %s", idx, paths[idx]);
+
+				// macOS uses decomposed Unicode strings (e.g. an 'e' and a combining accent) in filenames
+				// This causes problems with the sprite font, as the font only contains precomposed characters
+				// The block below converts all filename strings to their precomposed form, preventing mojibake
+				#ifdef __MACOSX__
```
Comment (marijnvdwerf) [inline src/openrct2/platform/posix.c]: `#ifdefs` are supposed to be the aligned to the left of the file, with the contents being aligned to their usual position.

Comment (rwjuk) [inline src/openrct2/platform/posix.c]: Ah, okay - I was following precedent elsewhere in the file (L813) - I'll fix both.

**Comment by rwjuk** [comment]
@Gymnasiast I didn't! I used the 'resolve conflicts' tool on GitHub to resolve the conflict - I didn't realise it'd do it with a merge. Lesson learned!
