### PR TITLE
Fix #7568: Demolish button causes hang

### LINKED ISSUE #7561: Coasters with incomplete tracks only save the first station piece
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 06105c3

When you save the design of a coaster with an incomplete track, such as a boomerang, the saved design will only have the first station piece when you build it. You will even be able to save and build it if either or both the entrance and exit aren't on the first station piece.

**Steps to reproduce:**
1. Build launched coaster with incomplete track
2. Save the track 
3. Build that track

**Screenshots / Video:**

image

### LINKED ISSUE #7568: Trying to demolish a continuous circuit without a station crashes the game
**Version:** 0.1.3
**Commit/Build:** cce3769

The game hangs when trying to demolish a ride that has a 'continuous' circuit that doesn't go through a station.
This only makes the client hang in multiplayer, the server is not affected.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build any tracked ride and create a circuit without a station in it (a circle using 4 turns for example)
2. Open the ride window and click the Demolish button
Result: the game hangs

Alternatively, start building a track with a station, but make it loop with itself (not passing through the station).

I think there was a very similar bug with testing/opening a ride in such situations before.

**Screenshots / Video:**
To clarify what I mean with the alternative method:
forest frontiers 2018-05-27 16-31-36

### PR DESCRIPTION
**Pull request by jensj12**
Fix #7568.
Fix #7561.
Fixed by adding the standard infinite loop check from #7062. Also makes the save button save the entire track again. Since it increases the cost of refurbishing rides in some cases, the network version has to be raised.

### CODE REVIEW

File: src/openrct2/ride/Ride.cpp [hunk 1]
```diff
@@ -5484,22 +5484,36 @@ void ride_get_start_of_track(CoordsXYE * output)
...
             };
 
-            if (!track_block_get_previous(trackBeginEnd.end_x, trackBeginEnd.end_y, trackBeginEnd.begin_element, &trackBeginEnd)) {
+            if (!track_block_get_previous(trackBeginEnd.end_x, trackBeginEnd.end_y, trackBeginEnd.begin_element, &trackBeginEnd))
+            {
                 trackElement = lastGood;
                 break;
             }
+
+            moveSlowIt = !moveSlowIt;
```
Comment (wolfreak99) [inline src/openrct2/ride/Ride.cpp]: does moveSlowIt mean it's slowly interacting through the track pieces?

Comment (janisozaur) [reply src/openrct2/ride/Ride.cpp]: _iterating_. Yes, to detect loops you need two iterators, `fast` and `slow` one, you iterate them until `fast` reaches end of the list or the two meet.

File: src/openrct2/ride/Ride.cpp [hunk 2]
```diff
@@ -5540,7 +5557,18 @@ sint32 ride_get_refund_price(sint32 ride_id)
...
 
         if (!track_block_get_next(&trackElement, &trackElement, NULL, NULL))
+        {
             break;
+        }
+
+        moveSlowIt = !moveSlowIt;
+        if (moveSlowIt)
+        {
+            if (!track_block_get_next(&slowIt, &slowIt, NULL, NULL) || slowIt.element == trackElement.element)
```
Comment (Gymnasiast) [inline src/openrct2/ride/Ride.cpp]: `nullptr`. `NULL` is naughty.

**Comment by Gymnasiast** [comment]
Line note needs addressing. PR also needs to be rebased and the network version rebumped.

File: src/openrct2/ride/Ride.cpp (hunk 1 above)
Comment (wolfreak99) [reply src/openrct2/ride/Ride.cpp]: that must have been my phones spell check.
