### PR TITLE
Fix #5249: No collision detection when building ride entrance at heights > 85.5m

### LINKED ISSUE #5249: Ride entrance/exit may be built in the same position over 85.5m(=57 units)
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 7005d5d

It is issued with #5248 together in korean community,
ride entrance/exit could be built in the same position if their height is over 85.5m (=57 unit).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Disable support limit
2. Build any ride with height as 85.5m (=57 unit)
3. Then the clearance check of their entrance/exit isn't checked correctly. They could be built in the same position

**Dump file**

**Screenshots / Video:**
image

**Save game:**

### PR DESCRIPTION
**Pull request by Gymnasiast**
When doing https://github.com/OpenRCT2/OpenRCT2/issues/10468 , I remembered a similar bug, so I decided to look into that one as well. As I expected, it was caused by an overflowing 8-bit signed integer.

### CODE REVIEW

File: src/openrct2/actions/RideEntranceExitPlaceAction.hpp [hunk 1]
```diff
@@ -105,7 +105,7 @@ DEFINE_GAME_ACTION(RideEntranceExitPlaceAction, GAME_COMMAND_PLACE_RIDE_ENTRANCE
             return MakeResult(GA_ERROR::NOT_OWNED, errorTitle);
         }
 
-        int8_t clear_z = (z / 8) + (_isExit ? 5 : 7);
+        auto clear_z = (z / 8) + (_isExit ? 5 : 7);
```
Comment (duncanspumpkin) [inline src/openrct2/actions/RideEntranceExitPlaceAction.hpp]: Make the same changes to L176 for this to actually work.

Comment (Gymnasiast) [reply src/openrct2/actions/RideEntranceExitPlaceAction.hpp]: It _does_ work, as I have tested it...
