### PR TITLE
Fix #16061: Incorrect colours in minimap

### LINKED ISSUE #16061: Landsurfaces not colored correctly in the minimap
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (c30d574 on develop) provided by GitHub

### Describe the issue

With the NSF, the coloring of the ground surfaces in the minimap is not correct anymore. There seems to be some kind of shift.

grafik

### Area(s) with issue?

NSF

### Steps to reproduce

1.  Color ground
2.  Open minimap

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**
Requires an object release before merging. The accompanying object changing are here: https://github.com/OpenRCT2/objects/commit/6cabf489aaa31bcca014e1240f91ac2d88d72997

Besides showing the wrong colours, the old code also frequently read beyond the end of the array. The new code should be very robust against that sort of thing, only continuing if exactly two colours have been specified and falling back to 0 otherwise.

### CODE REVIEW

File: src/openrct2/object/TerrainSurfaceObject.h [hunk 1]
```diff
@@ -53,6 +53,7 @@ class TerrainSurfaceObject final : public Object
     uint8_t Rotations{};
     money32 Price{};
     TERRAIN_SURFACE_FLAGS Flags{};
+    uint8_t MapColours[2];
```
Comment (IntelOrca) [inline src/openrct2/object/TerrainSurfaceObject.h:56]: I think we need to create a new typedef for palette index, otherwise it is difficult to know whether we are talking about the 32 possible user colours or the palette index.

File: src/openrct2/object/TerrainSurfaceObject.h [hunk 2]
```diff
@@ -53,6 +53,7 @@ class TerrainSurfaceObject final : public Object
     uint8_t Rotations{};
     money32 Price{};
     TERRAIN_SURFACE_FLAGS Flags{};
+    PaletteIndex MapColours[2];
```
Comment (IntelOrca) [inline src/openrct2/object/TerrainSurfaceObject.h:56]:
```suggestion
    PaletteIndex MapColours[2]{};
```

File: src/openrct2/object/TerrainSurfaceObject.h [hunk 3]
```diff
@@ -53,6 +53,7 @@ class TerrainSurfaceObject final : public Object
     uint8_t Rotations{};
     money32 Price{};
     TERRAIN_SURFACE_FLAGS Flags{};
+    PaletteIndex MapColours[2]{};
```
Comment (tupaschoal) [inline src/openrct2/object/TerrainSurfaceObject.h:56]:
```suggestion
    std::array<PaletteIndex, 2> MapColours;
```

File: src/openrct2/interface/Colour.h [hunk 4]
```diff
@@ -65,7 +67,7 @@ enum
     COLOUR_LIGHT_WATER = 10
 };
 
-enum : uint8_t
+enum : PaletteIndex
 {
     PALETTE_INDEX_0 = 0,     // Transparent
     PALETTE_INDEX_10 = 10,   // Black (0-dark), Dark grey (0)
```
Comment (tupaschoal) [inline src/openrct2/interface/Colour.h:73]: Seems like some (if not all, haven't checked) of these became unused. Should we clean it up?

Comment (Gymnasiast) [reply src/openrct2/interface/Colour.h:73]: I don’t think so. I would actually argue that we should create constants for all palette indices, with correct naming.
