### PR TITLE
Fix Recent Messages only shows at most 6 or 7 notifications once opened

### LINKED ISSUE #14674: Recent Messages only shows at most 6 or 7 notifications once opened
**OS:** Windows 10
**Version:** 0.3.3+
**Commit/Build:** 0123a3d

If any time you open the Recent Messages window, as soon as you get the seventh, eighth, or so notification while in a scenario, only the first 6 or 7 will show up although the seventh/eighth notification and all later ones will correctly still show up in the message bar at the bottom of the screen. This bug was first observed in the .park test build but I have confirmed that it also happens in develop. This bug can be annoying as it can hide important notifications (e.g. park rating warnings, awards, newly researched ride/scenery).

**Steps to reproduce:**
1. Open any scenario or save file (can be the one attached below).
2. Open the Recent Messages window at least once.
3. Generate at least 6 or 7 notifications (can be done by drowning 7 guests/staff members or crashing 7 rides). Only the first 6/7 notifications received since opening Recent Messages will show up.

**Screenshots:**
Carmine Calderas 2021-05-15 14-59-41
Carmine Calderas 2021-05-15 14-59-44
As you can see, in the first screenshot, Reverse Freefall Coaster 1 has just broken down. However, the game only recorded all notifications up to the seventh one, which was the Wooden Wild Mouse being researched on June 26th, Year 1. So, clicking on the "Reverse Freefall Coaster 1 has broken down" message did not send it to Recent Messages because it was beyond the first 7 notifications after I opened up Recent Messages at the start of the scenario. Note that I did not disable any of the notification types.

**Save game:**
[Carmine Calderas.zip](https://github.com/OpenRCT2/OpenRCT2/files/6488333/Carmine.Calderas.zip)
Attached is a .zip file containing the scenario I was playing when I spotted this bug, along with the save file. The SV6 was saved on October 4th, Year 1, the date that the Reverse Freefall Coaster 1 breakdown pictured above took place.

### PR DESCRIPTION
**Pull request by GalBr**
Fixes #14674
_scrollHeight was a static variable,  causing it to always have the value 0. Honestly I'm not sure why that happened.
This commit fixes this issue by changing this variable to not be static.

### CODE REVIEW

File: src/openrct2-ui/windows/News.cpp [hunk 1]
```diff
@@ -120,7 +120,7 @@ class NewsWindow final : public Window
 
     ScreenSize OnScrollGetSize(int32_t scrollIndex) override
     {
-        static int32_t _scrollHeight = static_cast<int32_t>(gNewsItems.GetArchived().size()) * CalculateItemHeight();
+        int32_t _scrollHeight = static_cast<int32_t>(gNewsItems.GetArchived().size()) * CalculateItemHeight();
```
Comment (duncanspumpkin) [inline src/openrct2-ui/windows/News.cpp:123]: can you drop the `_` as well.

**Review by duncanspumpkin — APPROVED** [review]

**Comment by duncanspumpkin** [comment]
Oh actually this should be in the changelog could you add an entry.

**Comment by GalBr** [comment]
Done. Also added myself to the contributors file. I realized I never did that up until now.
