### PR TITLE
Don't parse invalid names from highscores fixes #3333

### LINKED ISSUE #3333: Invalid highscores.dat files can cause crashes/hanging with no warnings
**OS:** All (Tested Windows and OS X)
**Version:** 0.0.4 Stable & 0.0.5 Develop
**Commit:** Tested on 24eaa0a

The highscores.dat file has a number indicating the number of entries and then the entries listed. If the number of entries indicated is greater than the number of entries in the file, then the program doesn't handle the issue gracefully. A user on Gitter reported that this issue caused the game to hang indefinitely on loading with Windows. My testing on OS X showed both crashes with EXC_BAD_ACCESS and indefinite hanging with increasing memory usage (depending on how I used breakpoints). The program really shouldn't have these sorts of catastrophic errors, even if the file corruption was user-error.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Replace (or add) the highscores.dat file in the OpenRCT2 Documents folder with the one linked below, or modify the file there (with a hex editor) to indicate 1 (or more) entries than are actually in the file.
2. Run the game and see that it doesn't launch.

**Example File**
[highscores.dat.zip](https://github.com/OpenRCT2/OpenRCT2/files/223095/highscores.dat.zip)

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

File: src/scenario_list.c [hunk 1]
```diff
@@ -294,10 +294,12 @@ static int scenario_list_sort_by_index(const void *a, const void *b)
 
 scenario_index_entry *scenario_list_find_by_filename(const utf8 *filename)
 {
-	for (int i = 0; i < gScenarioListCount; i++) {
-		const utf8 *scenarioFilename = path_get_filename(gScenarioList[i].path);
-		if (_strcmpi(filename, scenarioFilename) == 0) {
-			return &gScenarioList[i];
+	if (filename != NULL) {
```
Comment (LinusU) [inline src/scenario_list.c]: Could just be `if (filename == NULL) return NULL;`, just a thought...

**Comment by IntelOrca** [comment]
I don't like this, filename != null should be a pre-condition of the function.

**Comment by janisozaur** [comment]
updated + one more
